### ISSUE TITLE
[Problem] Thru-hole in PRO-E not appearing in FreeCAD

### ISSUE THREAD

**Issue by DrewHeath** [FreeCAD/FreeCAD#10004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33656 (Git)
Build type: Release
Branch: master
Hash: 9f1e2c9f37dda46a10840095d0a044ca2e4d89cf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * QuickMeasure 2022.10.28
[/code]
```

### Subproject(s) affected?

None

### Problem description

This part created in PRO-E has three thru-holes. In FreeCAD one of the holes is not displayed correctly. Screenshots and model are attached. Problem exists in v 0.20.0 and development build.

Reproduction steps:

1. Open FreeCAD.
2. Open model.

Help Forum Link: https://forum.freecad.org/viewtopic.php?p=695748

### Anything else?

![Pro-E_view](https://github.com/FreeCAD/FreeCAD/assets/5154248/27b0c25a-7ecb-4b39-972c-9e1afeb7e6fc)
![FreeCAD_view](https://github.com/FreeCAD/FreeCAD/assets/5154248/a4a2477d-a491-420e-b95c-4137af357b1e)
[FMLC00015400.zip](https://github.com/FreeCAD/FreeCAD/files/12186136/FMLC00015400.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
The file looks the same with the current dev version but the .step looks also broken when opening with other applications. So I guess it's an issue with the ProE file. I'm closing this.
