### ISSUE TITLE
[Problem] Recent Files is weirdly positioned in the menu.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#10001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
0.21
```

### Subproject(s) affected?

Core

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/26b4ed5f-ea19-480a-9c53-8f0af7ff9bc1)

Recent files is weirdly placed by itself at the end of the menu.
I suggest renaming it 'Open recent' and place it right under Open.
This will make it more intuitive and make the menu easier on the eye : remove one separator and one section. And naming it 'Open ----' makes the eye instantaneously understand what this is, which makes the menu look less cluttered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
I've just opened Origin, it has _Recent_ at the bottom of the menu, a near _Exit_. So, as LibreCAD, Notepad++, Diamond.

Though, I have software that has _Recent_ a near _Open_, Inkscape and Paint.NET.

So far I concluded that programs put it at the bottom of the file menu, except for graphics editors.

**Comment by PaddleStroke** [comment]
I have looked at a lot of softwares, and found some that put it at the bottom indeed. However not only graphic editors put it near open. Few other examples : Eagle, LibreOffice, VLC, KDenLive...

Putting recent files at the end makes sense in the case where they are directly in the menu :
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/5325a5f1-6eb0-48ad-ae83-1e0a1477e505)
Because then the menu stays 'static' but the end of the menu that changes with the files.

But in the case where it is only 'Recent Files' submenu put at the end, I cannot see any advantage. Whereas putting it as Open Recent next to Open increase clarity.
