### ISSUE TITLE
[Problem] Segfault when creating a new figure using Plot module

### ISSUE THREAD

**Issue by oliveroxtoby** [FreeCAD/FreeCAD#10003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 20.04.6 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33656 (Git)
Build type: Debug
Branch: upstream
Hash: 9f1e2c9f37dda46a10840095d0a044ca2e4d89cf
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.2
Locale: English/South Africa (en_ZA)
Installed mods: 
  * AirPlaneDesign 0.4.0
  * AirPlaneDesign.backup1662065198.1826277
  * CfdOF 1.24.3
  * Curves 0.5.0
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

The Plot workbench causes FreeCAD to crash with a segfault when trying to create a new plot window. This is affecting the CfdOF addon. The problem was not present in the 0.20.X releases.

To reproduce the problem, open FreeCAD and enter the following in the Python console:
```
from FreeCAD.Plot import Plot
Plot.figure("foo")
```
(this is supposed to open a blank plot window).

I have used git bisect to identify the commit which causes this as: https://github.com/FreeCAD/FreeCAD/commit/a19e2454becdf4980acfd79d29962cbf2f5cfcd3
(@abdullahtahiriyo, @0penBrain FYI)

Moving the lines
```
if (!view)
    return;
```
[here](https://github.com/FreeCAD/FreeCAD/commit/a19e2454becdf4980acfd79d29962cbf2f5cfcd3#diff-a858c8d2d1dce20a3b475fd7013ed3348e86e11528b167843c72d304f4de12c0R1198) to before the line where view is used, resolves the problem (although I do wonder if this is an indication that Plot is not creating its MDI window in the correct manner...but I guess that's a separate discussion!).

### Anything else?

Log file:
[FreeCAD.log](https://github.com/FreeCAD/FreeCAD/files/12180975/FreeCAD.log)
Forum discussion:
https://forum.freecad.org/viewtopic.php?t=79820

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0penBrain** [comment]
Your solution is correct IMO. Would you submit a PR?
