### ISSUE TITLE
[Problem] DlgGeneralImp is hard to find

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#10014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
0.21
```

### Subproject(s) affected?

Core

### Problem description

The general page of preference is implemented in DlgGeneralImp.cpp / ui / h. While the other pages all follow DlgSettingsXxxxxxx.cpp

It's a small thing but it makes it hard to find this page in the folder.

So I suggest renaming this DlgSettingsGeneral

Besides I think it could be best to put all the preferences files inside a gui/preferences subfolder.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benj5378** [comment]
> The general page of preference is implemented in DlgGeneralImp.cpp / ui / h. While the other pages all follow DlgSettingsXxxxxxx.cpp

This seems trivial, so if you make the change and do a pull request, I think we would be happy to merge it.


> Besides I think it could be best to put all the preferences files inside a gui/preferences subfolder.

@PaddleStroke Thanks for the consideration. This is subjective and probably need to be discussed on the forum where an agreement can be reached. That said, I do agree with you.

**Comment by chennes** [comment]
@benj5378 I'd argue that right here (in an GitHub issue) is the "correct" place to discuss code details like directory layout. The gui folder is a bit overfull IMO, so I definitely support cleaning it up with some appropriate subfolders, including the one proposed here. In short, I agree with both suggested changes.

**Comment by benj5378** [comment]
@chennes Okay, just be aware that such discussions have already taken place on the forum where there were multiple opinions.

**Comment by luzpaz** [comment]
What's the status of this ?
