### ISSUE TITLE
Issue with editing the 'some editable text' from TechDraw Generator Tutorial

### ISSUE THREAD

**Issue by nahinojo** [FreeCAD/FreeCAD#10045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.6, Qt 5.15.9, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Behave-Dark-Colors 0.1.1
[/code]
```

### Subproject(s) affected?

Techdraw

### Problem description

In the TechDraw TemplateGenerator Tutorial on the FreeCAD Wiki website (https://wiki.freecad.org/TechDraw_TemplateGenerator) there's an issue when trying to render the final SVG stated in the section **Resulting Macro**. When I import the example TechDraw template, I cannot edit the 'some editable text'. There's no green box available for me to change the selection; it's almost as if the editable text is static.

Fortunately I found the fix for this issue: the SVG metadata attribute xmlns:freecad should be changed to:
```
<svg
xmlns:freecad="http://www.freecadweb.org/wiki/index.ph ... _Namespace"
...>
...
<svg/>
```

The difference between this URL and the one posted in the tutorial is that I changed _freecad.org_ to f_reecadweb.org_. This now allows the SVG to be editable.

The GitHub wiki demonstrates this solution yet the website wiki does not, hence **I argue the website needs to be updated**.

I am running the current-most version of FreeCAD 0.20.2 on Linux Min

### Anything else?
[Link to Forum Post](https://forum.freecad.org/viewtopic.php?p=695483#p695483)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
See comment in the forum:
https://forum.freecad.org/viewtopic.php?p=695483#p697049

Closing this as resolved.
