### ISSUE TITLE
Hope to improve the functionality[Problem] 

### ISSUE THREAD

**Issue by a937983423** [FreeCAD/FreeCAD#10049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: EndeavourOS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33678 (Git)
Build type: None
Branch: master
Hash: e296c1ffc75e59cbb12a1b7ea0f9522e771daec7
Python 3.11.3, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: Chinese/China (zh_CN)
Installed mods: 
  * kicadStepUpMod 10.18.5
  * InventorLoader 1.4.0
  * CurvedShapes 1.0.4
  * EM
  * AirPlaneDesign 0.4.0
  * Behave-Dark-Colors 0.1.1
  * DesignSPHysics 0.6.3(24-09-2022)
  * Dracula 0.0.4
  * Design456 0.0.1
  * 3DfindIT 1.2.0
  * Estimate 0.1.2
  * DynamicData 2.46.0
  * dodo 1.0.0
  * A2plus 0.4.60m
  * Cfd
  * 3D_Printing_Tools
  * CubeMenu
  * ExplodedAssembly
  * Beltrami 1.0.8-alpha
  * Assembly4 0.12.7
  * BCFPlugin 1.0.0
  * Alternate_OpenSCAD 1.0.0
  * fasteners 0.4.56
  * CfdOF 1.22.5
  * Curves 0.6.8
  * ArchTextures
  * sheetmetal 0.2.63
  * AnimationFreeCAD 1.0.0
  * freecad.gears 1.0.0
  * FEM_FrontISTR 0.1.0
  * Fcmcua 1.0.0
  * Defeaturing 1.2.0
[/code]
```

### Subproject(s) affected?

Core

### Problem description

First of all, thank you for your open source and dedication, I want to give you suggestions for improvement, the software is too difficult to use, just can still operate, the result is reported in the operation of the error, I don't know why the error is reported, sometimes the design is wrong can not use ctrl+z to go back, the sketch is the most affecting experience, the sketch in the same model after copying and pasting can not pull out the entity, pull out the error must be new to pull out, is it possible to create a sketch once every time you draw, it cannot be reused, and the sketch cannot be customized, I hope to back up the commonly used sketches by myself and pull it directly when using, hope to solve the error and sketch problems, I support you, I hope you get better and better

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Thanks for the comments -- if you aren't already a Forums member, I suggest joining the FreeCAD forums at https://forum.freecad.org -- there are many discussions going on there about various improvements like those you suggest. I'm going to close this bug report because it's too general to act upon, but your feedback is appreciated.
