### ISSUE TITLE
[Problem] Missing lines when inserting projection group into Techdraw

### ISSUE THREAD

**Issue by gilmiz** [FreeCAD/FreeCAD#10041]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.0.33669 (Git)
Build type: Release
Branch: (HEAD detached at 0.21rc1a)
Hash: e5a00e153d36b0d53ebd568f4f47e95fbb5d0fcd
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Danish/Denmark (da_DK)
Installed mods: 
  * Assembly4 0.50.2
  * fasteners 0.4.56
  * freecad.gears-master 1.0.0
  * Materials
  * MeshRemodel 1.8919.0
  * Render 2023.2.6
  * sheetmetal 0.2.63
  * toSketch 1.0.1
[/code]
```

### Subproject(s) affected?

Techdraw

### Problem description

Some lines, looks like arcs, are missing when inserting a projection group. See the attached image.
The same operation results without errors on FC 0.20.

![projection grou II](https://github.com/FreeCAD/FreeCAD/assets/16917848/3168c570-cd2e-4d7f-8830-56e52544208c)

Source file:
[base.zip](https://github.com/FreeCAD/FreeCAD/files/12247813/base.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Can you attach the FCStd file?

**Comment by WandererFan** [comment]
Also a marked up picture showing where the missing bits should be, please.

**Comment by gilmiz** [comment]
Updated image with missing lines and source file added.

**Comment by WandererFan** [comment]
The Direction and XDirection for the views are off a bit which is causing those segments to be projected as ellipses with very small diameters.
`Front
>>> obj.Direction
Vector (2e-06, -2e-06, 1.0)
>>> obj.XDirection
Vector (4e-12, 1.000000000004, 2e-06)
>>> 

Left
>>> obj.Direction
Vector (-4e-12, -0.9999999999980002, -2e-06)
>>> obj.XDirection
Vector (2e-06, -2e-06, 0.9999999999960002)`
To fix it, update these properties to be exactly the correct values (like (0.0, 0.0, 1.0).

**Comment by WandererFan** [comment]
![base_noMissingLines](https://github.com/FreeCAD/FreeCAD/assets/3587161/ac2afcb1-4a34-4b16-a006-197e469c4a46)
![baseBadDirectionLeft](https://github.com/FreeCAD/FreeCAD/assets/3587161/a5e7a5bc-fb9a-4d14-b3cb-8be801362a7b)

**Comment by luzpaz** [comment]
Maybe techdraw should somehow highlight the negative floating point number or offer a hazard emoji next to it with a hover tooltip explaining the possible warning ?

**Comment by WandererFan** [comment]
A negative number is perfectly acceptable (ex (0, 0, -1) indicates view from the bottom)

"-0.00" is a clue that the real number is something like "-0.00000123".

The real fix might be for Gui::View3DInventorViewer::getViewDirection() to not return garbage after the sixth or seventh decimal place.

Don't know how we would tell the PropertyEditor vector updater that TD Direction vector should be handled differently.

**Comment by luzpaz** [comment]
> Don't know how we would tell the PropertyEditor vector updater that TD Direction vector should be handled differently.

@WandererFan open a ticket for this ?

**Comment by WandererFan** [comment]
I'd rather get the right value from Coin for the Direction.
