### ISSUE TITLE
[Problem] Export step 3d Model Broken - fcad_pcb

### ISSUE THREAD

**Issue by qaqcvc** [FreeCAD/FreeCAD#10053]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.12.3
  * kicadStepUpMod 10.15.0
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

I am trying to export the model to step for another software.
But the output model is broken in a very weird way that I could not find the reason.

In the Freecad:
![image](https://github.com/FreeCAD/FreeCAD/assets/52302145/81497f05-bf80-4087-97ef-ae2a3f7931e8)

Export to step file and open in other software:
![image](https://github.com/FreeCAD/FreeCAD/assets/52302145/d18b7ed7-28dc-4bda-a10a-eb32d4ffd7ca)

I also opened it with other software, they are showing the broken features. 
Anybody has any idea about this issue? Thank you in advance.

The model is generated by fcad_pcb. 
My freecad model: 
[git_issue.zip](https://github.com/FreeCAD/FreeCAD/files/12249182/git_issue.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Have you read [Std_Export](https://wiki.freecad.org/Std_Export)? In particular the advice about what to select and what not?

**Comment by Roy-043** [comment]
Can't confirm. Please retest using V0.21. See attachments.

Step export preferences:
![Step_export_prefs](https://github.com/FreeCAD/FreeCAD/assets/70520633/3ac81c2b-ed00-482a-a730-203863ef153e)

Version info:
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33636 (Git)
Build type: Release
Branch: master
Hash: a5e350ad469f4030b46baa6fd3d1770375f1ddd1
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

[git_issue_imported.zip](https://github.com/FreeCAD/FreeCAD/files/12249479/git_issue_imported.zip)

**Comment by qaqcvc** [comment]
Hi Roy, thank you for your answer. From my side, if I import the step model in my Freecad (0.20), it is also fine. The problem is if I import this step file with other CAD software or FEM software, it is broken.

And seems that it relates with the shape of the model. 
Please check these two practices:
1) 
In Freecad:
![image](https://github.com/FreeCAD/FreeCAD/assets/52302145/9d81f1fb-a1f9-44c4-8645-1a48c8a5df0b)

Import in another software:
![image](https://github.com/FreeCAD/FreeCAD/assets/52302145/99286457-5444-4c98-9276-c2163eab6681)

2)
In Freecad:
![image](https://github.com/FreeCAD/FreeCAD/assets/52302145/e21a451c-112e-4fbb-88fb-ab54166f22f2)

Import in another software:
![image](https://github.com/FreeCAD/FreeCAD/assets/52302145/66b8a34e-fe9d-4211-b0a9-b1ae86f76682)


The only difference is that I changed the outline shape of each layers. Do you have any idea about this? Thank you.

**Comment by luzpaz** [comment]
So is this issue a downstream fcad_pcb bug ?

**Comment by qaqcvc** [comment]
Still no idea how to solve this issue. But I have found a way to avoid this workflow. Thank you as well.

**Comment by luzpaz** [comment]
I bumped downstream ticket (https://github.com/realthunder/fcad_pcb/issues/68#issuecomment-1673464377) asking if this ticket is still relevant

**Comment by HJFSTX** [comment]
@qaqcvc 

Can you elaborate on your workaround?
