### ISSUE TITLE
[Problem] Could not create pixmap from qss:images_dark-light/background_freecad_ExtremProDark.svg

### ISSUE THREAD

**Issue by sdifru** [FreeCAD/FreeCAD#10051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: makepkg
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.11.3, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * dodo 1.0.0
  * FreeCAD_assembly3 0.12.0
  * FreeCAD_FastenersWB 0.4.58
  * FreeCAD_Assembly4 0.50.2
  * FreeCAD_SheetMetal 0.2.63
  * Lattice2 1.0.0
  * freecad.gears 1.0.0
  * CurvesWB 0.6.12
[/code]
```

### Subproject(s) affected?

None

### Problem description

`Could not create pixmap from qss:images_dark-light/background_freecad_ExtremProDark.svg`

The message shows up on report view right after I open freecad. I don't know what to do with it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
I bet that's a typo (assuming you copied the message?) -- it should probably be referencing "qss:images_dark-light/background_freecad_Extrem**e**ProDark.svg" (with an "e" at the end of Extreme). @MisterMakerNL ?

**Comment by sdifru** [comment]
@chennes You are right. I copied pasted the message.

![2023-08-03_15-08-1691049790](https://github.com/FreeCAD/FreeCAD/assets/123437835/d8f078cf-1657-46c8-a797-c9f809d4757f)

**Comment by luzpaz** [comment]
This is a quick fix. Lets just get it done?

**Comment by MisterMakerNL** [comment]
This PR should be first https://github.com/FreeCAD/FreeCAD/pull/10238#issuecomment-1682572139
After that I'll make a new cleaner pr.

**Comment by luzpaz** [comment]
bump

**Comment by MisterMakerNL** [comment]
This been fix with the theme pr. Don't have an exact number at hand tho.
