### ISSUE TITLE
[Problem] FEM experimental characteristic (Group meshing for analysis) is set to true in FEM General Preferences and can't be changed

### ISSUE THREAD

**Issue by Alberto4343** [FreeCAD/FreeCAD#10071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Spanish/Peru (es_PE)
Installed mods: 
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Problem description

When trying to create a FEM mesh via the "FEM MeshGmshFromShape" tool this message appears:

"Group meshing for analysis is set to true in FEM General Preferences. Are you really sure about this? You could run into trouble!"

When i go to FEM General Preferences that option is grayed out and activated.

I'm having troubles to create a FEM mesh via the "FEM MeshGmshFromShape" tool and maybe this is the reason.

Excellent program and initiative. Thank you so much.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FOSCAS** [comment]
On the wiki it is shown greyed out and unchecked. After checking I have the same problem

**Comment by Alberto4343** [comment]
I hope they check this issue soon, ¿Do you know how much do we have to wait?

**Comment by luzpaz** [comment]
To raise probability of this issue getting addressed please open a thread in the FEM subforum https://forum.freecad.org/viewforum.php?f=18 (x-post link back to ticket)

**Comment by Alberto4343** [comment]
@luzpaz, i can't register, when chosing my language it sends me to the previous page. ¿Do you know where to report that problem?

**Comment by luzpaz** [comment]
What are you seeing ?

**Comment by Alberto4343** [comment]
From this page https://forum.freecad.org/ucp.php?mode=register it sends me to this page https://forum.freecad.org/ucp.php?mode=register

**Comment by Roy-043** [comment]
You can change this preference manually:

Start the [Std_DlgParameter](https://wiki.freecad.org/Std_DlgParameter) command:
Tools > Edit parameters

Go to the correct group:
BaseApp > Preferences > Mod > Fem > General

Change `AnalysisGroupMeshing` to `false`

**Comment by Alberto4343** [comment]
It worked thank you. have you repaired it in the program?

**Comment by Roy-043** [comment]
Issues are closed when they get fixed. I am not involved with the FEM code, so somebody else would need to step in.

**Comment by Alberto4343** [comment]
I don't know well how this work, when we post an issue does it get to the developer team somehow or not?

**Comment by luzpaz** [comment]
@Alberto4343 there are many many tickets open (897 at the moment) and we are all volunteers here. It's not instant fix just because it was reported.
