### ISSUE TITLE
[Problem] Window layout redraw is botched (on Windows)

### ISSUE THREAD

**Issue by DubDublin** [FreeCAD/FreeCAD#10088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Problem description

Window layout gets botched and is apparently unfixable w/o restarting FreeCAD, and sometimes, Windows.  (I'm now using 0.21, but this was a problem in 0.20.2 as well...) There seem to be several (probably related) problems here:  

1. After either the monitor going to sleep, or the laptop going to sleep and waking again, FreeCAD does not correctly redraw the screen - all menus, controls, etc. are outside the viewport, and resizing, minimizing, maximizing, etc. the window does not provoke a refresh as expected.  See attached image.  The only way I've found to fix this is kill the app and restart it.  (Sometimes a Windows restart is required?)   
2.  FreeCAD always wants to be on the primary display, which is almost always the wrong one for a laptop with an attached monitor.  Simply moving the FreeCAD window to the secondary/external display (by either Shift-Win-RtArrow or draging and then maximizing) can also cause this problem.
3. More troublingly, it appears that in some cases, the controls may actually still be there, but are not visible - you can roll over the top area of the screen and see tooltips, but can't see the controls themselves.  This also makes using the menus via the Alt-key and mouse impossible - I had to file this bug report via Alt-H, then use the keyboard ONLY to navigate down to "Report a bug", since using the mouse to try to select one of the menu items blows you out and does God only knows what...
![image](https://github.com/FreeCAD/FreeCAD/assets/9810995/6373f4cc-abbc-4f02-9f0e-3254b5fe4916)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DubDublin** [comment]
BTW, problem is worse when using FreeCAD on second monitor, but I'm pretty sure I've seen it on the primary monitor as well.

**Comment by xtemp09** [comment]
This problem could be vendor-dependent. I use few displays at once and have never encounter this. I use Intel GPU and it's not a laptop, so I don't have energy-saving settings.

Could you also report your CPU, GPU, their driver versions and, perhaps, what settings are on (`Settings  > System  > Power & sleep  > Additional power settings`)?



```ruby
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Russian/Russia (ru_RU)
```

**Comment by DubDublin** [comment]
Sure: Here you go - nothing very exotic at all (This is a newish laptop, and I haven't even gotten a dock for it yet - it's just the monitor plugged directly into the laptop.  It's a Lenovo 9i 14" i7, with a Dell P2815Q 4K monitor connected via HDMI) - there is nothing else attached - until I get a dock, I'm using the laptop's built-in keyboard and a Microsoft Precision bluetooth mouse as the only peripheral other than the monitor.)

![image](https://github.com/FreeCAD/FreeCAD/assets/9810995/5edd833d-f99b-4f52-b167-c5d3c02462fb)

DeviceName                                                 Manufacturer              DriverVersion
----------                                                 ------------              -------------
Local Print Queue                                          OKI                       10.0.22621.1
Local Print Queue                                          Microsoft                 10.0.22621.1
Local Print Queue                                          Microsoft                 10.0.22621.1
Local Print Queue                                          Microsoft                 10.0.22621.1
Local Print Queue                                          Microsoft                 10.0.22621.1
Generic software device                                    Microsoft                 10.0.22621.1
Generic software device                                    Microsoft                 10.0.22621.1
Generic software device                                    Microsoft                 10.0.22621.1
Generic software device                                    Microsoft                 10.0.22621.1
Generic software device                                    Microsoft                 10.0.22621.1
Generic software device                                    Microsoft                 10.0.22621.1
Generic software device                                    Microsoft                 10.0.22621.1
Computer Device                                            Microsoft                 10.0.22621.1
Remote Desktop Device Redirector Bus                       Microsoft                 10.0.22621.608
Universal Device Client Device                             Lenovo                    23.5.0.38
System Interface Foundation V2 Device                      Lenovo                    1.2.0.11
Plug and Play Software Device Enumerator                   (Standard system devices) 10.0.22621.1
Microsoft System Management BIOS Driver                    (Standard system devices) 10.0.22621.1
NDIS Virtual Network Adapter Enumerator                    Microsoft                 10.0.22621.1
Microsoft Hyper-V Virtual Disk Server                      Microsoft                 10.0.22621.1702
Microsoft Basic Render Driver                              Microsoft                 10.0.22621.608
Microsoft Hyper-V PCI Server                               Microsoft                 10.0.22621.1
System Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Device Firmware                                            Microsoft                 10.0.22621.1
Microsoft UEFI-Compliant System                            Microsoft                 10.0.22621.1
ACPI Thermal Zone                                          (Standard system devices) 10.0.22621.1
ACPI Fan                                                   (Standard system devices) 10.0.22621.1
ACPI Fan                                                   (Standard system devices) 10.0.22621.1
ACPI Fan                                                   (Standard system devices) 10.0.22621.1
ACPI Fan                                                   (Standard system devices) 10.0.22621.1
ACPI Fan                                                   (Standard system devices) 10.0.22621.1
Motherboard resources                                      (Standard system devices) 10.0.22621.1
UCM-UCSI ACPI Device                                       Microsoft                 10.0.22621.1
Trusted Platform Module 2.0                                (Standard)                10.0.22621.608
Intel(R) Innovation Platform Framework Manager             Intel                     1.0.11000.27915
HID-compliant system controller                            (Standard system devices) 10.0.22621.819
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID Keyboard Device                                        (Standard keyboards)      10.0.22621.1
Converted Portable Device Control device                   Microsoft                 10.0.22621.1
Portable Device Control device                             Microsoft                 10.0.22621.1
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID-compliant system controller                            (Standard system devices) 10.0.22621.819
HID-compliant system controller                            (Standard system devices) 10.0.22621.819
HID-compliant system controller                            (Standard system devices) 10.0.22621.819
HID-compliant wireless radio controls                      (Standard system devices) 10.0.22621.819
HID Keyboard Device                                        (Standard keyboards)      10.0.22621.1
Intel(R) HID Event Filter                                  Intel(R) Corporation      2.2.1.386
Intel(R) Power Engine Plug-in                              Intel Corporation         10.0.22621.1485
Microsoft Windows Management Interface for ACPI            Microsoft                 10.0.22621.1
Microsoft Windows Management Interface for ACPI            Microsoft                 10.0.22621.1
ACPI Processor Aggregator                                  (Standard system devices) 10.0.22621.1
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
Intel Processor                                            Intel                     10.0.22621.1485
ACPI Sleep Button                                          (Standard system devices) 10.0.22621.1
Microsoft Windows Management Interface for ACPI            Microsoft                 10.0.22621.1
Lenovo Intelligent Sensing                                 Lenovo                    1.0.5.60
Microsoft Windows Management Interface for ACPI            Microsoft                 10.0.22621.1
Microsoft Windows Management Interface for ACPI            Microsoft                 10.0.22621.1
Lenovo Fn and function keys                                Lenovo                    2.0.6.78
Microsoft Windows Management Interface for ACPI            Microsoft                 10.0.22621.1
Microsoft Windows Management Interface for ACPI            Microsoft                 10.0.22621.1
ACPI Power Button                                          (Standard system devices) 10.0.22621.1
ACPI Lid                                                   (Standard system devices) 10.0.22621.1
Microsoft AC Adapter                                       Microsoft                 10.0.22621.1
Motherboard resources                                      (Standard system devices) 10.0.22621.1
Intel(R) Serial IO GPIO Host Controller - INTC1055         Intel Corporation         30.100.2134.22
Motherboard resources                                      (Standard system devices) 10.0.22621.1
Motherboard resources                                      (Standard system devices) 10.0.22621.1
ACPI Wake Alarm                                            (Standard system devices) 10.0.22621.1
Motherboard resources                                      (Standard system devices) 10.0.22621.1
Intel(R) SPI (flash) Controller - 51A4                     INTEL                     10.1.36.6
Intel(R) SMBus - 51A3                                      INTEL                     10.1.36.6
Audio Endpoint                                             Microsoft                 10.0.22621.1
HD Audio Driver for Display Audio                          Intel Corporation         31.0.101.1999
HD Audio Driver for Display Audio                          Intel Corporation         31.0.101.1999
Audio Endpoint                                             Microsoft                 10.0.22621.1
Intel® Smart Sound Technology for Digital Microphones      Intel(R) Corporation      10.29.0.6755
Intel® Smart Sound Technology for Bluetooth® Audio         Intel(R) Corporation      10.29.0.6755
Intel® Smart Sound Technology for USB Audio                Intel(R) Corporation      10.29.0.6755
Audio Endpoint                                             Microsoft                 10.0.22621.1
Elevoc Hardware Support Application                        Elevoc Technology Co.,Ltd 1.0.1.32
Elevoc Audio Effects Component                             Elevoc Technology Co.,Ltd 3.0.3.127
Realtek Audio Universal Service                            Realtek                   1.0.0.464
Realtek Hardware Support Application                       Realtek                   11.0.6000.260
Realtek Audio Effects Component                            Realtek                   11.0.6000.991
DolbyAPO Software Device (HSA)                             Dolby                     3.30201.210.0
DolbyAPO SWC Device                                        Dolby                     3.30205.250.0
Realtek High Definition Audio(SST)                         Microsoft                 6.0.9275.1
Intel® Smart Sound Technology Detection Verification       Intel(R) Corporation      1.0.2036.0
Intel® Smart Sound Technology OED                          Intel(R) Corporation      10.29.0.6755
Intel® Smart Sound Technology BUS                          Intel(R) Corporation      10.29.0.6755
Standard PS/2 Keyboard                                     (Standard keyboards)      10.0.22621.1
Motherboard resources                                      (Standard system devices) 10.0.22621.1
System timer                                               (Standard system devices) 10.0.22621.1
Motherboard resources                                      (Standard system devices) 10.0.22621.1
Programmable interrupt controller                          (Standard system devices) 10.0.22621.1
High precision event timer                                 (Standard system devices) 10.0.22621.1
Intel(R) Innovation Platform Framework Generic Participant Intel                     1.0.11000.27915
Intel(R) Innovation Platform Framework Generic Participant Intel                     1.0.11000.27915
Intel(R) Innovation Platform Framework Generic Participant Intel                     1.0.11000.27915
Intel(R) Innovation Platform Framework Generic Participant Intel                     1.0.11000.27915
GPIO Laptop or Slate Indicator Driver                      Microsoft                 10.0.22621.608
Lenovo Yoga Mode Control Device                            Lenovo                    3.0.1.3
Lenovo Notebook ITS Driver                                 Lenovo                    5.0.21.23
Lenovo ACPI-Compliant Virtual Power Controller             Lenovo                    15.11.29.70
Microsoft ACPI-Compliant Control Method Battery            Microsoft                 10.0.22621.1
Microsoft ACPI-Compliant Embedded Controller               (Standard system devices) 10.0.22621.1
Intel(R) LPC Controller - 5182                             INTEL                     10.1.36.6
Intel(R) Management Engine WMI Provider                    Intel                     2130.1.15.0
Intel(R) Dynamic Application Loader Host Interface         Intel                     1.41.2021.121
Intel(R) Management Engine Interface #1                    Intel                     2145.1.42.0
Microsoft Input Configuration Device                       Microsoft                 10.0.22621.1
HID-compliant touch pad                                    (Standard system devices) 10.0.22621.819
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
HID-compliant mouse                                        Microsoft                 10.0.22621.1
I2C HID Device                                             Microsoft                 10.0.22621.608
Intel(R) Serial IO I2C Host Controller - 51E9              Intel Corporation         30.100.2134.22
Wacom Service                                              Wacom Technology          7.7.1.81
HID-compliant mouse                                        Microsoft                 10.0.22621.1
HID-compliant digitizer                                    (Standard system devices) 10.0.22621.819
HID-compliant device                                       (Standard system devices) 10.0.22621.819
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
HID-compliant pen                                          (Standard system devices) 10.0.22621.819
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
Microsoft Input Configuration Device                       Microsoft                 10.0.22621.1
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
HID-compliant touch screen                                 (Standard system devices) 10.0.22621.819
Wacom Device                                               Wacom Technology          7.7.2.48
Intel(R) Serial IO I2C Host Controller - 51E8              Intel Corporation         30.100.2134.22
Microsoft Wi-Fi Direct Virtual Adapter                     Microsoft                 10.0.22621.1
Microsoft Wi-Fi Direct Virtual Adapter                     Microsoft                 10.0.22621.1
Intel(R) Connectivity Performance Suite                    Intel Corporation         1.1122.615.2
Intel(R) Wi-Fi 6E AX211 160MHz                             Intel Corporation         22.160.0.4
Intel(R) Shared SRAM - 51EF                                INTEL                     10.1.36.6
Billboard Device                                           WinUsb Device             10.0.22621.608
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
HID-compliant vendor-defined device                        (Standard system devices) 10.0.22621.819
Precision Mouse Setting                                    Surface                   10.8.137.0
Microsoft Precision Mouse Firmware Update                  Surface                   1.3.137.0
Microsoft Precision Mouse Integration Device               Surface                   1.1.136.0
HID-compliant consumer control device                      Microsoft                 10.0.22621.1
HID Keyboard Device                                        (Standard keyboards)      10.0.22621.1
Precision Mouse (Mouse and Keyboard Center)                Microsoft                 14.23.137.0
Bluetooth Low Energy GATT compliant HID device             Microsoft                 10.0.22621.2070
Scan Parameter Service                                     Microsoft                 10.0.22621.1778
Bluetooth LE Generic Attribute Service                     Microsoft                 10.0.22621.1778
Device Information Service                                 Microsoft                 10.0.22621.1778
Generic Attribute Profile                                  Microsoft                 10.0.22621.1778
Generic Access Profile                                     Microsoft                 10.0.22621.1778
Bluetooth LE Device                                        Microsoft                 10.0.22621.1778
Bluetooth LE Device                                        Microsoft                 10.0.22621.1778
Microsoft Bluetooth LE Enumerator                          Microsoft                 10.0.22621.1778
Bluetooth Device (Personal Area Network)                   Microsoft                 10.0.22621.1555
Bluetooth Device                                           Microsoft                 10.0.22621.2070
Wireless iAP v2
GATT
MAP MAS-iOS
Phonebook Access Pse Service                               Microsoft                 10.0.22621.2070
Microsoft Bluetooth Hands-Free Profile Handsfree role      Microsoft                 10.0.22621.1
Personal Area Network NAP Service                          Microsoft                 10.0.22621.2070
Microsoft Bluetooth Avrcp Transport Driver                 Microsoft                 10.0.22621.1778
Microsoft Bluetooth Avrcp Transport Driver                 Microsoft                 10.0.22621.1778
Microsoft Bluetooth A2dp Sink                              Microsoft                 10.0.22621.1
Service Discovery Service                                  Microsoft                 10.0.22621.2070
Wireless iAP
Microsoft Bluetooth Enumerator                             Microsoft                 10.0.22621.2070
Bluetooth Device (RFCOMM Protocol TDI)                     Microsoft                 10.0.22621.1778
Intel Tile Device                                          Intel Corporation
Intel(R) Wireless Bluetooth(R)                             Intel Corporation         22.160.0.4
Goodix fingerprint                                         Goodix                    3.0.550.180
WinUsb Device                                              WinUsb Device             10.0.22621.608
Integrated IR Camera                                       SunplusIT                 5.0.18.167
Integrated Camera                                          SunplusIT                 5.0.18.167
USB Composite Device                                       (Standard USB Host Con... 10.0.22621.1194
USB Root Hub (USB 3.0)                                     (Standard USB HUBs)       10.0.22621.1992
USB xHCI Compliant Host Controller                         Generic USB xHCI Host ... 10.0.22621.1928
HID Sensor Collection V2                                   Microsoft                 10.0.22621.1928
HID PCI Minidriver for ISS                                 Intel                     3.1.0.4557
HID Sensor Collection V2                                   Microsoft                 10.0.22621.1928
HID PCI Minidriver for ISS                                 Intel                     3.1.0.4557
ISS Dynamic Bus Enumerator                                 (Standard system devices) 3.1.0.4557
Intel(R) Integrated Sensor Solution                        Intel
USB4(TM) Root Device Router (Microsoft)                    Generic USB4 Device Ro... 10.0.22621.1928
USB4 Virtual power coordination device
USB4(TM) Host Router (Microsoft)                           Generic USB4 Host Router  10.0.22621.1928
USB Root Hub (USB 3.0)                                     (Standard USB HUBs)       10.0.22621.1992
USB xHCI Compliant Host Controller                         Generic USB xHCI Host ... 10.0.22621.1928
Intel(R) Platform Monitoring Technology Driver             Intel(R) Platform Moni... 10.0.22621.1485
Intel(R) GNA Scoring Accelerator module                    Intel Corporation         3.0.0.1400
PCI Express Root Port                                      (Standard system devices) 10.0.22621.1778
PCI Express Root Port                                      (Standard system devices) 10.0.22621.1778
Disk drive                                                 (Standard disk drives)    10.0.22621.1778
Standard NVM Express Controller                            Standard NVM Express C... 10.0.22621.2070
Intel(R) PEG60 - 464D                                      INTEL                     10.1.45.4
Intel(R) Dynamic Tuning Technology                         Intel                     9.0.11000.27915
Intel(R) Innovation Platform Framework Processor Partic... Intel                     1.0.11000.27915
Dell P2815Q (HDMI)                                         Dell Inc.                 1.0.0.1
Lenovo DisplayHDR                                          Lenovo                    20.21.0.3
Intel(R) Graphics Command Center                           Intel Corporation         31.0.101.1999
Intel(R) Iris(R) Xe Graphics                               Intel Corporation         31.0.101.1999
Intel(R) Host Bridge/DRAM Registers - 4621                 INTEL                     10.1.45.4
PCI Express Root Complex                                   (Standard system devices) 10.0.22621.1778
Microsoft ACPI-Compliant System                            Microsoft                 10.0.22621.1485
ACPI x64-based PC                                          (Standard computers)      10.0.22621.1
Charge Arbitration Driver                                  (Standard system devices) 10.0.22621.1
UMBus Root Bus Enumerator                                  Microsoft                 10.0.22621.608
Facial Recognition (Windows Hello) Software Device         Microsoft                 10.0.22621.2070
Microsoft Kernel Debug Network Adapter                     Microsoft                 10.0.22621.1
Microsoft Storage Spaces Controller                        Microsoft                 10.0.22621.900
Microsoft Virtual Drive Enumerator                         Microsoft                 10.0.22621.1
Composite Bus Enumerator                                   Microsoft                 10.0.22621.1
Microsoft Hyper-V Virtualization Infrastructure Driver     Microsoft                 10.0.22621.608
Microsoft Hypervisor Service                               Microsoft                 10.0.22621.608
Microsoft Basic Display Driver                             (Standard display types)  10.0.22621.1
Microsoft Hyper-V Virtual Machine Bus Provider             Microsoft                 10.0.22621.1702
Volume                                                     Microsoft                 10.0.22621.1
Generic volume shadow copy                                 Microsoft                 10.0.22621.1
Generic volume shadow copy                                 Microsoft                 10.0.22621.1
Volume                                                     Microsoft                 10.0.22621.1
Volume                                                     Microsoft                 10.0.22621.1
Volume                                                     Microsoft                 10.0.22621.1
Volume Manager                                             Microsoft                 10.0.22621.608

                                                                                     2:10.0,2:6.3...
                                                                                     2:10.0,2:6.3...
                                                                                     2:10.0,2:6.3...
                                                                                     2:10.0,2:6.3...
![image](https://github.com/FreeCAD/FreeCAD/assets/9810995/536238d3-fe84-41ec-b21d-0a5446cd92b6)

**Comment by xtemp09** [comment]
Could you create a boolean parameter named _DisableDpiScaling_ in `Tools → Edit parameters` at `BaseApp/Preferences/HighDPI` and set it to _true_? Or _false_ and see how it influences.

**Comment by DubDublin** [comment]
OK, will do - just woke it up again after being AFK for a while, here's what I saw that may help:  when the computer woke back up, it momentarily flashed the FreeCAD window on the laptop's screen before restoring it to the 4K external display.  (This is normal, if awkward, wake behavior for Win11 and this laptop/monitor combo - my old Win10/Surface Pro did not do this even on the same monitor.)  Here's what's interesting:  The FreeCAD window was correctly laid out with all the controls when it momentarily flashed onto the laptop screen (as though it was maximized there), but was then instantly botched again as in the original image I posted when it showed up on the external 4K screen.  There is no way I can find to force a redraw/relayout short of killing the app and starting over.

**Comment by DubDublin** [comment]
With this set to True, FreeCAD starts up with all the UI elements being *very* small, with tiny icons and unreadable text.  (That may make sense, since both the built-in display and the external display have high pixel counts - 3840x2400 for the built-in display, and of course the usual 4K 3840x2160 for the external monitor.) 

It did NOT botch the redraw after my first try with this setting.

I'm going to try again a couple of times with True before setting it to False to see if that changes anything...

**Comment by luzpaz** [comment]
@DubDublin thanks! keep us posted!

**Comment by DubDublin** [comment]
UI is of course, unusable with _DisableDpiScaling_  set to True, so it's hard to do much to test how it works.  I haven't seen it fail the same way, but I'm not sure it's a good test.  Problem does persist with it set to False, just as it does when it's not set at all, like it is out of the box...

**Comment by DubDublin** [comment]
Just documenting that this problem still persists, regardless of anything I've tried.  There is a bug with redraw after waking that is different than just resizing the window when moving to a new monitor - large parts of the UI are off-screen and cannot be brought back.  So far, the only remedy is still to close FreeCAD and restart it.

**Comment by luzpaz** [comment]
@DubDublin can you still reproduce this on latest development version ? 
(https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds)

**Comment by maxwxyz** [comment]
any news on this, is this still relevant? I'll close if there is no feedback.

**Comment by maxwxyz** [comment]
closing for no feedback

**Comment by andylovescode** [comment]
This issue is still a problem, even on the latest version!
