### ISSUE TITLE
[Backport] Regex speed improvement on QuantitySpinBox

### ISSUE THREAD

**Issue by chennes** [FreeCAD/FreeCAD#10082]
### Original PR

https://github.com/FreeCAD/FreeCAD/pull/10067

### Description and Justification

Speed improvement to QuantitySpinBox when using large numbers of digits.

**Comment by adrianinsaval** [comment]
@chennes was this ever backported?

**Comment by chennes** [comment]
No, I don't think so.

**Comment by Roy-043** [comment]
Backported.
