### ISSUE TITLE
Std_ToggleClipPlane task panel is too large and doesn't permit to hide it partially when in left+bottom sidebars

### ISSUE THREAD

**Issue by Alberto4343** [FreeCAD/FreeCAD#10095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Spanish/Peru (es_PE)
Installed mods: 
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Problem description

Clipping plane is too large and doesn´t permit to hide it parcially when in the the left sidebar or in the bottom sidebar. It consumes too much space.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Do you mind providing a screenshot please?

**Comment by Alberto4343** [comment]
Note: I don't have a good english level.
Yes. 

This is the minimum width when in left sidebar:
![image](https://github.com/FreeCAD/FreeCAD/assets/141293804/69ca338e-60ed-4faf-9f70-1cd2e2a19b25)

This is the minimum height when in bottom sidebar:
![image](https://github.com/FreeCAD/FreeCAD/assets/141293804/0d47d4ca-ca93-4c62-b37a-6aef8f8d3598)

**Comment by luzpaz** [comment]
Related to #8477  
It looks like a duplicate
