### ISSUE TITLE
Recent clang-format change is harder to read

### ISSUE THREAD

**Issue by berniev** [FreeCAD/FreeCAD#10123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
na
```

### Subproject(s) affected?

None

### Problem description

#9994 Introduced a welcome change to break up long parameter lists onto separate lines, but introduces positional  inconsistency between long and short parameter lists. Every little inconsistency makes things just that little bit more difficult.

```
    int autoConstraint(
        double precision = Precision::Confusion() * 1000,
        double angleprecision = M_PI / 20,
        bool includeconstruction = true
    );

    int autoConstraint2(double precision = Precision::Confusion() * 1000);
```

Setting `AlignAfterOpenBracket: Align` would produce
```
    int autoConstraint(double precision = Precision::Confusion() * 1000,
                       double angleprecision = M_PI / 20,
                       bool includeconstruction = true);

    int autoConstraint2(double precision = Precision::Confusion() * 1000);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
Especially for the implementation of a function I find this style difficult because it makes it hard to quickly distinguish the function arguments from the function body:
```
void someLongFunction(
    std::vector<std::vector<int>> argument1,
    std::vector<std::vector<int>> argument2
)
{
    auto test1 = argument1;
    auto test2 = argument2;
}
```

I also vote to restore `AlignAfterOpenBracket: Align`

**Comment by berniev** [comment]
PR #101167
