### ISSUE TITLE
Keyboards essentially not working while FreeCAD 0.18.4 is processing

### ISSUE THREAD

**Issue by nathanielstenzel** [FreeCAD/FreeCAD#10145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
FreeCAD 0.18.4
Linux Mint 20.2 with the Cinnamon desktop
```

### Subproject(s) affected?

None

### Problem description

I have FreeCAD 0.18.4. My apologies for bugging you about something old.

My keyboards stop sending characters when I am trying to convert some STL files to solids for some binary operation. I imagine that this is better than the full lockup that I have had with OpenSCAD lately, but it is still not ideal. I have seen some control combo reports but nothing like this. I am on Linux Mint 20.2 (also old) with the Cinnamon desktop. This is the only thing that stops key presses from being recognized.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Starting a GitHub issue related to a version that old makes no sense.

Closing this.
