### ISSUE TITLE
[Problem] Path: Helix operation positive Extra Offset error

### ISSUE THREAD

**Issue by glasbenik** [FreeCAD/FreeCAD#10157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Fedora 33 (Workstation Edition) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33719 (Git) AppImage
Build type: Release
Branch: master
Hash: 2a88c7c7dfed699d2a4944bda13bf8626ed39315
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * fasteners 0.3.50
  * FeedsAndSpeeds 0.4.0
[/code]
```

### Subproject(s) affected?

Path

### Problem description

When I try to set a positive Extra Offset for the Helix operation I get an error. It works for a negative offset.  See the forum link and a proposed fix.

### Anything else?

https://forum.freecad.org/viewtopic.php?t=76707

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stevecosoft** [comment]
PR: #10430 

@sliptonic 
In my testing I found that the proposed fix still blocked Extra Offset values which are valid (meaning that there is enough space for the Extra Offset plus the tool inside the designed hole diameter).

The check compares hole_radius - inner_radius to tool_diameter.  The variable hole_radius contains the designed hole radius - inner_radius.  So hole_radius - inner_radius = (designed hole radius - inner_radius) - inner_radius = designed hole radius - inner_radius - inner_radius.  I couldn't see how it made sense to compare that value to the tool diameter or the tool radius.

So I tested removing the entire check, and verified that the check which follows it will catch cases where the diameter of the hole to be cut is less than the diameter of the tool.

Some values captured while testing through the GUI:
```
inner_radius
(Extra Offset)     hole_radius          I (from G2 in the GCode)
0                  7.94                 1.59
0.7                7.24                 0.89
1.0                6.94                 0.59
1.4                6.54                 0.19
1.59               6.3500000000000005   0.0
1.6                6.34                 <class 'ValueError'>: Cannot helix a hole of diameter 12.68 with a tool of diameter 12.7
``` 

P.S. this is my first PR for FreeCAD, so please let me know if I need to change anything.

**Comment by Stevecosoft** [comment]
@sliptonic merged the PR, and I tested the latest master (commit b277feed7d550cd11495c81d2178dafaa4b39146).  So I think this issue can be closed.
