### ISSUE TITLE
[Feature Request] Reset tab button in Preferences (only reset preferences in the active tab)

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#10161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Core

### Problem description

Currently, there's only a Reset button resetting all the preferences to their default values. But it would be very useful to have an additional "Reset tab" button that would reset the values of preferences only in an active tab. This would be particularly helpful e.g. for tessellation settings.

Forum discussion: https://forum.freecad.org/viewtopic.php?t=80253

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalligaroV** [comment]
For future reference, as reported in #11969, to be sure that all the parameters reset correctly it will be better also to check, and eventually modify, the Preference Pages in the various `Mod` folders (only those ones with parameters that aren't set using `PrefWidgets` objects)
