### ISSUE TITLE
[Problem] missing estlcam_post.py in installation package of release 0.21

### ISSUE THREAD

**Issue by haraldhartmann** [FreeCAD/FreeCAD#10208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
[/code]
```

### Subproject(s) affected?

Path

### Problem description

In the installation packages (neither windows nor linux) of release 0.21 the file estlcam_post.py is missing although it's [there](https://github.com/FreeCAD/FreeCAD/blob/releases/FreeCAD-0-21/src/Mod/Path/Path/Post/scripts/estlcam_post.py) in the codebase of releases/FreeCAD-0-21.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
I would have expected the maintainer who merged the original post processor pull request to have made it clear that the PR was incomplete without https://github.com/FreeCAD/FreeCAD/blob/releases/FreeCAD-0-21/src/Mod/Path/CMakeLists.txt being modified to include the new file. @haraldhartmann are you Ok to submit a PR to master and request it be backported to the 0.21 branch please?
