### ISSUE TITLE
Union function for parts unreliable

### ISSUE THREAD

**Issue by StarcatcherASD** [FreeCAD/FreeCAD#10249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
FreeCAD 0.20.2
```

### Subproject(s) affected?

Part

### Problem description

Nothing complicated:
- I created sketches inn part design workbench.
- Using them, i created volumes in the part workbench. E.g. "extrude", "loft", ...
Some of these volumes are based on the same sketches, some are based on different sketches, which lies on the same datum plane.
- then i applies the union function in the part workbench to merge the volumes into one.

Result:
All elements in the object tree successfully moved under one common "Sufion" element.
However in the 3d when applying tools->clipping plane: i can see that some volumes did not merge. They still kept the walls between, which should have disappeared. Now these walls are inside the merged volume. This happens seemingly arbitrary.
Also sometimes a volume disappears aptically, when merged.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Your workflow seems dubious. You need to post an example file. Without a file we cannot do anything with your report.
