### ISSUE TITLE
[Feature Request] Automatic vertical and horizontal constrain

### ISSUE THREAD

**Issue by NXTler** [FreeCAD/FreeCAD#10261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33458 (Git) AppImage
Build type: Release
Branch: master
Hash: 8b89dd29d2382c72d738c52e8974216130ffa9db
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * PieMenu 1.2.7
  * sheetmetal 0.2.63
  * toSketch 1.0.1
  * A2plus 0.4.60n
  * QuickMeasure 2022.10.28
  * Curves 0.6.12
  * CfdOF 1.23.1
  * TabBar
  * IconThemes
  * Glass
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

Sketcher

### Problem description

Hello all,
due to the vertical and horizontal constrain being separate, you have to do a lot of switching back and forth while sketching, which makes the workflow feel chunky. Other CAD programs get around this, by having only one function, which applies the right constrain based on if the line is closer to vertical or horizontal.
In case of FreeCAD, I would leave the existing functions as they are and only add a function on top, which chooses as stated.

Many thanks in Advance

### Anything else?

Here is an example from another CAD programs:
![HorizontalVertical_Constraint](https://github.com/FreeCAD/FreeCAD/assets/73062438/98aa64dc-7e91-4b35-9684-0f008f35a88e)
![horizontal-and-vertical-constraint-in-creo-parametric-sketch](https://github.com/FreeCAD/FreeCAD/assets/73062438/8a19e852-5f04-4a99-980c-1bb5aa34406a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
So pressing the `H` key or the `V` key is too clunky? I've been using FreeCAD for 6 years on a near daily basis for real work and have never wanted or even thought the functionality you are suggesting was necessary.

**Comment by Roy-043** [comment]
There is also the "Auto constraints" feature. When switch on, new lines that are nearly horizontal or vertical automatically receive the corresponding constraint. See [Sketcher Dialog](https://wiki.freecad.org/Sketcher_Dialog).

**Comment by NXTler** [comment]
I didn't even know that, the `h` `v` shortcut existed... That explains a lot, thanks!
I find the "Auto constraints" feature a bit too finicky from time to time, and I have a lot of cases where I set the constraints afterward.

**Comment by FEA-eng** [comment]
There's another issue with separate horizontal/vertical constraints - when you work with a rotated view of the sketch, those constraints often have switched meanings (so you have to use vertical for lines that are viewed as horizontal and vice versa). Such automatic constraint would eliminate this issue.

**Comment by NXTler** [comment]
Yeah, this is also a reason, why I wanted this feature. Though, I think I will open another Feature Request for this one, since one Solution might be to automatically change the meaning internally without extra function. You can reopen this one, if you feel like a better solution.

**Comment by luzpaz** [comment]
@NXTler please open a new ticket and link to this one so we have continuity
