### ISSUE TITLE
[Problem] single quote in file path breaks opening from recent history

### ISSUE THREAD

**Issue by janvanderwatt** [FreeCAD/FreeCAD#10264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Australia (en_AU)
Installed mods: 
  * 3D_Printing_Tools
  * CurvedShapes 1.0.4
  * Curves 0.4.3
  * DynamicData 2.46.0
[/code]
```

### Subproject(s) affected?

None

### Problem description

If a file path contains a single quote (apostrophe), it can be opened using File->Open, and it will appear in the recent history displayed at startup; however, clicking on it will result in this error:
![image](https://github.com/FreeCAD/FreeCAD/assets/4944435/6e9f25a5-2db0-471a-9478-96cc9c526e7a)
This problem is new to 0.21, and does not occur in 0.20.2:
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Australia (en_AU)
Installed mods: 
  * 3D_Printing_Tools
  * CurvedShapes 1.0.4
  * Curves 0.4.3
  * DynamicData 2.46.0
[/code]

Removing the single quote from the directory name is a successful workaround to this problem.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
This was fixed in master and fix was also backported to v0.21
Props to @bdieterm
