### ISSUE TITLE
[Problem] PartDesign Helix negative cone angle reverses the coil

### ISSUE THREAD

**Issue by Anthony-Gaudino** [FreeCAD/FreeCAD#10284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * MeshRemodel 1.8919.0
  * Launcher
  * InventorLoader 1.4.0
  * Render 2023.2.6
  * Silk 0.1.3
  * Defeaturing 1.2.0
  * A2plus 0.4.60n
  * Manipulator 1.5.0
  * fasteners 0.4.59
  * lattice2 1.0.0
  * sheetmetal 0.2.63
  * toSketch 1.0.1
  * Curves 0.6.13
  * Assembly4 0.50.2
  * Assembly3 0.12.0
```

### Subproject(s) affected?

PartDesign

### Problem description

When creating an additive coil in PartDesign, If I set the cone angle to a negative number it reverses the coil.
I expected the diameter of the coil to decrease, but instead it reverses the coil and increases it's diameter.

Coil with positive cone angle value:
<img width="828" alt="Screenshot 2023-08-20 at 21 07 00" src="https://github.com/FreeCAD/FreeCAD/assets/2439728/821d0c31-17f5-4fc0-af2f-bf29cf3b972d">

Coil with negative cone angle value:
<img width="670" alt="Screenshot 2023-08-20 at 21 07 27" src="https://github.com/FreeCAD/FreeCAD/assets/2439728/c439ecc0-afc2-4bc7-8d5e-6b89d77e222e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grubertechnic** [comment]
Confirmed in the newest version.

```
OS: Debian GNU/Linux 12 (bookworm) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33917 (Git)
Build type: Release
Branch: master
Hash: 0c0a4473cd032945912768c2e5821b668a132199
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * QuickMeasure 2022.10.28
```

**Comment by luzpaz** [comment]
Whomever take a look at this, do you mind also checking out #9377 ? TIA

**Comment by bgbsww** [comment]
I'd take a swing at this, but I don't understand it.  The two images above look correct to me.  Is the expectation that the second image should be automatically offset by the height, or should it look different somehow?

**Comment by Anthony-Gaudino** [comment]
> I'd take a swing at this, but I don't understand it. The two images above look correct to me. Is the expectation that the second image should be automatically offset by the height, or should it look different somehow?

The behavior as is is not correct. When a negative value is entered the whole helix is flipped.

When using the Part workbench helix it also provides an angle property that seems to be correct. Try inputting 10deg or -10deg for example.

**Comment by luzpaz** [comment]
Thanks so much for the fix @bgbsww. You rock!

**Comment by luzpaz** [comment]
@Anthony-Gaudino please confirm fix when you get a chance, TIA
