### ISSUE TITLE
[Backport] Revert change to PDFA1b

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FreeCAD#10283]
### Original PR

https://github.com/FreeCAD/FreeCAD/pull/10277

### Description and Justification

Commit 12f137397d should be backported.  Setting PDF version to A1b in QPrinter or QPdfWriter can cause issues with graphics.   See https://forum.freecad.org/viewtopic.php?t=80532&sid=39976b8ae9944d1bf07cc52c4b231882  for original problem report.

**Comment by Roy-043** [comment]
Done with: a7bf4f33f864abec29463f233d090cc63d5a47bd
