### ISSUE TITLE
[Feature Request] Group horizontal and vertical constraints

### ISSUE THREAD

**Issue by NXTler** [FreeCAD/FreeCAD#10320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33458 (Git) AppImage
Build type: Release
Branch: master
Hash: 8b89dd29d2382c72d738c52e8974216130ffa9db
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * PieMenu 1.2.7
  * sheetmetal 0.2.63
  * toSketch 1.0.1
  * A2plus 0.4.60n
  * QuickMeasure 2022.10.28
  * Curves 0.6.13
  * CfdOF 1.24.4
  * TabBar
  * IconThemes
  * Glass
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

Sketcher

### Problem description

Hello all,
when you work with a rotated view of the sketch, the vertical and horizontal constraints often have switched meanings, which can be disorientating or confusing.
This is just an open discussion for now, but I see two potential ways this can be handled.
First is creating an extra function on top of the current system, which automatically applies a horizontal or vertical constrain based on which is closest (previously seen in #10261).
Second is doing some sort of automatic switching intern the current system, based on the viewing direction. Though I'm not sure how it would actually work and if it would be easier to implement.

Many thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grubertechnic** [comment]
As user, in my opinion, it make little sense. Vertical and horizontal is defined orientation the sketch, not a point of view. When you need a different orientation of the sketch, you can easily adapt it in the attachments, placement and/or properties.

**Comment by NXTler** [comment]
Yes, it's currently possible to rotate the sketch, but you often can't change it afterward. With the first solution, the vertical and horizontal constrain would still be defined by the sketch. (See #10261 for more information)

**Comment by grubertechnic** [comment]
> Yes, it's currently possible to rotate the sketch, but you often can't change it afterward.

Of course you change the attachment and placement afterwards.


Anyway, define a constraint from point of view is as conception in parametric CAD really not a good idea, besides the handling of it.

**Comment by NXTler** [comment]
You can change the attachment and placement afterward, but many if not all dependencies will be broken or messed up. As I have stated, the constraints will not be defined by the point of view and will continue to work as normal, as you would have realized from #10261.
Many professional programs like Solid Edge, Solid Works, ANSIs and Inventor already utilize a similar function for their vertical and horizontal constrain.

**Comment by grubertechnic** [comment]
Only because some CADs have a similar function, does not mean that it is a good idea, i see some professional CAD with crappy ideas. I also have used some commercial CADs, but none of these you listed. Are you sure, that they have such a function?

I suppose (pure guess now), they have a general constraint tool, but none for explicit vertical/horizontal point of view. Due it is  general constraint tool, it looks like, that they change vertical/horizontal, but in reality they only constraint parallel from the lines, independent from the view. And because they are parallel, they ignore the actual parallel from one line (or both and override it with a new), because else it would be overconstraint.

**Comment by NXTler** [comment]
I have been modeling both professional and private for more than 4 years now and have well over 4000 hours in Solid Edge alone. I have tried all of these and worked with them for a bit, though I have to admit that I'm not 100% sure with ANSIs and Solid Works.
Solid Edge uses this function since at least 2015 as the only way to set vertical and horizontal constraints. I think that my explanation of this function might not have been clear enough:
This function would apply a vertical or horizontal constrain to a line based on which one it is closer too. It does not depend on point of view.

**Comment by maxwxyz** [comment]
> I have been modeling both professional and private for more than 4 years now and have well over 4000 hours in Solid Edge alone. I have tried all of these and worked with them for a bit, though I have to admit that I'm not 100% sure with ANSIs and Solid Works.
> Solid Edge uses this function since at least 2015 as the only way to set vertical and horizontal constraints. I think that my explanation of this function might not have been clear enough:
> This function just applies your normal vertical and horizontal constraints to a line, based on which is closes to the current line angle. So if a line has an angle of 30°, it would apply a horizontal constrain. If it had an 84° angle, it's closer to a vertical constrain, so the function would apply one. For the Sketch, it's just like you applying normal constraints, nothing fancy.

That is the way. Group horizontal and vertical constraints in the task view under a new "straight" icon which picks the right constraint automatically to which the selected geometry is closer, similar to @PaddleStroke contextual dimension tool.
I often work on sketches from a rotated view or even from behind and I always have to think of the line should now be horizontal or vertical.
