### ISSUE TITLE
Cannot turn off Auto constraints

### ISSUE THREAD

**Issue by karl3200** [FreeCAD/FreeCAD#10321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Problem description

Steps taken: File>New, Create Body, Create Sketch, Select XY-Plane, Click Rectangle icon and draw a rectangle.
Problem: The rectangle is fully  constrained.
At Edit>Preferences>Sketcher>General Tab, the Auto constraints" box is unchecked.
In the Combo View>Tasks Tab>Edit Controls section, The "Auto constraints" box is unchecked.
Program does not follow "Auto constraints" preferences.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grubertechnic** [comment]
Do you mean, that also the size (lenght) is fully constraint?

**Comment by grubertechnic** [comment]
Also as i see, you use an old version, the recent stable is 0.21.

**Comment by karl3200** [comment]
See attached screen video.

**Comment by karl3200** [comment]
I was following a youtube video that shows the rectangle in white and
allows entering the measurements. I my case the lines were green and I
could only use the map the set the size. Attached are a couple screenshots
showing what I was watching.

**Comment by luzpaz** [comment]
Please either post URL or drag drop media in to the github text area for it to be attached to ticket (attaching to email won't work)

**Comment by karl3200** [comment]
Video of what I am seeing. (green lines)

https://github.com/FreeCAD/FreeCAD/assets/4162352/05ac9248-09aa-4d91-8b87-48c4e239d309

Screenshots of YouTube video
![whitelines](https://github.com/FreeCAD/FreeCAD/assets/4162352/3b258fe9-8116-41f5-9bf4-718d180a2268)
![enteringmeasurements](https://github.com/FreeCAD/FreeCAD/assets/4162352/6f833a85-5e86-4825-9f33-2e6e17da4f4a)
 
Link to YouTube:  https://www.youtube.com/watch?v=rglvJH9z5ng&list=LL&index=10&t=310s
His rectangle creation (white lines) begins at  3:17 minutes and ends at 3:41 and is started again at 4:05

**Comment by grubertechnic** [comment]
It is as expected, your sketch is not fully constraint, see in the task panel.

That is green can have several reason.
 - the most presumably, you changed the color of the lines to green in the sketcher preferences
 - some qt configs (it seems that is adapted, because the colors are not default)
 - you configs are destroyed, because you do version hopping
 - some graphic card issue

But still, you use an old FreeCAD version, the current is 0.21.

IMHO i candiate to close.

**Comment by karl3200** [comment]
How can I type in the measurements for the rectangle?
I haven't changed any color preferences.
I just upgraded to 21. Same situation. I had 20 previously. No hopping.
I have no indication of graphics card issue.

**Comment by grubertechnic** [comment]
> I haven't changed any color preferences.

Screenshot from Preferences --> Sketcher --> Colors please



> How can I type in the measurements for the rectangle?

Really? Read the manual https://wiki.freecad.org/Sketcher_Workbench

or @PLChris (chrisb in the forum) document about Sketcher, see https://forum.freecad.org/viewtopic.php?t=30104 or better on his signature.

**Comment by karl3200** [comment]
![FreeCadColors](https://github.com/FreeCAD/FreeCAD/assets/4162352/1234c621-21ee-40b4-966e-4a7a451b0a75)
Yes Really. I cannot find any mouse clicks or icons that allow me to type in the dimensions for a line.

**Comment by grubertechnic** [comment]
The color is edited, clearly. It does not change itself.


> Yes Really.

Do you read the links i posted and execute it?

@luzpaz : consider to close it, since it is a user issue, besides the OP opened a thread in the forum anyway (https://forum.freecad.org/viewtopic.php?t=80594).

**Comment by karl3200** [comment]
I reset the colors and  now I can enter the dimensions for each line.
