### ISSUE TITLE
Annotation Size Issue Opening Files From 0.20.2

### ISSUE THREAD

**Issue by mgroz** [FreeCAD/FreeCAD#10413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * Assembly4 0.50.2
  * fasteners 0.4.60
[/code]
```

### Subproject(s) affected?

Techdraw

### Problem description

Opening files created from 0.20.2 are creating issues with annotations in TechDraw. Due to this problem, I cannot upgrade to the latest version of Freecad.

### Anything else?

![0 20 2](https://github.com/FreeCAD/FreeCAD/assets/119752187/d6ca0793-84e2-49bd-9de9-d20ad6b29cef)
![0 21](https://github.com/FreeCAD/FreeCAD/assets/119752187/176a978a-d895-4b16-8a0e-8e1ce2bccabc)
[Annotation_Issue_TechDraw.zip](https://github.com/FreeCAD/FreeCAD/files/12456712/Annotation_Issue_TechDraw.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
If I measure the text in the Annotation or Dimension, I get about 0.15" from v0.21.  I get about 0.10" from v0.20.2.  So v0.21 has the correct size. 

The history of this change is here: https://forum.freecad.org/viewtopic.php?p=507048#p507048

**Comment by WandererFan** [comment]
Strictly old school.  I printed from both versions, then measured the text with a caliper.

We could probably make a script/macro to convert the nominal text sizes to a value that gives the old height.   I'd have to do some digging to see if the necessary functions are available in Python. 

We need to convert Annotation and Dimension text.  What has to be converted in Sections?  The symbol beside the section line?

**Comment by Roy-043** [comment]
This may be a better version of the issue: #10404

**Comment by WandererFan** [comment]
Can you share a copy of the file with the section please?  The first picture looks like ISO convention and the second looks like ANSI convention.

**Comment by WandererFan** [comment]
The v0.21 picture above is using the ISO convention for section line (Annotation tab in TD preferences).   If you flip that preference, the section symbol will go back to where it was (more or less).

![AnsiSectionConvention](https://github.com/FreeCAD/FreeCAD/assets/3587161/125f4a21-e712-47aa-b8c6-351725026620)

**Comment by WandererFan** [comment]
I've been working on this macro.  It will redo a Page to so it looks like it did in v0.20.  Read the comments first and make backups,  I was going to do more testing on it. 

[scalev020Text.py.txt](https://github.com/FreeCAD/FreeCAD/files/12491617/scalev020Text.py.txt)
