### ISSUE TITLE
[Problem] Build failing on macOS with undeclared identifier

### ISSUE THREAD

**Issue by sfmissionmark** [FreeCAD/FreeCAD#10415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
(anaconda3)markbutler@Marks-MacBook-Pro FreeCAD % git checkout 
Your branch is up to date with 'origin/master'.
```

### Subproject(s) affected?

None

### Problem description

/FreeCAD/FreeCAD/src/App/Application.cpp:2492:61: error: use of undeclared identifier 'FCVersionSuffix'
        App::Application::Config()["BuildVersionSuffix" ] = FCVersionSuffix;
                                                            ^
1 error generated.
ninja: build stopped: subcommand failed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
You need to recreate the Version.h file, either by doing a complete rebuild, or just deleting that single file from your build folder and letting the make system recreate it.

**Comment by luzpaz** [comment]
Do you know where the upstream ninja ticket is perhaps ?

**Comment by adrianinsaval** [comment]
No but this specific file not getting updated was discussed before: https://github.com/FreeCAD/FreeCAD/discussions/9606
