### ISSUE TITLE
[Problem] Sketcher segfault on latest master

### ISSUE THREAD

**Issue by qewer33** [FreeCAD/FreeCAD#10424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Fedora Linux 38 (KDE Plasma) (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34071 (Git)
Build type: Release
Branch: startpage-housekeeping
Hash: 932fd4638ba80671115fb2aa871ab3a273b6f673
Python 3.11.4, Qt 5.15.10, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Glass
  * lattice2 1.0.0
  * kicadStepUpMod 10.19.4
  * Manipulator 1.5.0
  * Assembly4.backup1691951820.225657 0.50.2
  * Assembly4
  * Behave-Dark-Colors 0.1.1
  * Curves 0.6.13
  * DynamicData 2.46.0
  * fasteners 0.4.59
  * Freecad-Built-in-themes-beta 1.2.2
  * freecad.gears.backup1692223246.5590403 1.0.0
  * freecad.gears
  * ExtremeProLight 1.6.0
  * A2plus 0.4.60n
  * ExplodedAssembly
  * FreeCAD_DarkPreferencePAck 0.0.1
```

### Subproject(s) affected?

Sketcher

### Problem description

1. Open the example file provided below in a latest master build (unzip first):
[PartDesignExample.zip](https://github.com/FreeCAD/FreeCAD/files/12465220/PartDesignExample.zip)

2. Try to open Sketch001 or Sketch003
3. FreeCAD crashes with a segfault

### Anything else?

Terminal output on crash:

<details>
<summary>Terminal Output</summary>
<pre>
FreeCAD 0.22.0, Libs: 0.22.0devR34071 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Failed to read /home/qewer/.local/share/FreeCAD/Mod/ExtremeProLight/package.xmlThe `.FCStd#` backup format is deprecated as of v0.21 and may be removed in future versions.
To update, check the 'Preferences->General->Document->Use date and FCBak extension' option.
Program received signal SIGSEGV, Segmentation fault.
#0  /lib64/libc.so.6(+0x3db70) [0x7f6775a5fb70]
#1  0x7f670a4e7efa in Part::Geometry const* Sketcher::GeometryFacade::getGeometry<Part::Geometry, void>() const from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/Sketcher.so+0xc
#2  0x7f670a4e6fc8 in Sketcher::GeoListModel<std::unique_ptr<Sketcher::GeometryFacade const, std::default_delete<Sketcher::GeometryFacade const> > >::getGeometryFromGeoId(std::vector<std::unique_ptr<Sketcher::GeometryFacade const, std::default_delete<Sketcher::GeometryFacade const> >, std::allocator<std::unique_ptr<Sketcher::GeometryFacade const, std::default_delete<Sketcher::GeometryFacade const> > > > const&, int) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/Sketcher.so+0x70
#3  0x7f670a4e6ebe in Sketcher::GeoListModel<std::unique_ptr<Sketcher::GeometryFacade const, std::default_delete<Sketcher::GeometryFacade const> > >::getGeometryFromGeoId(int) const from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/Sketcher.so+0x20
#4  0x7f655ea6ec97 in SketcherGui::EditModeConstraintCoinManager::processConstraints(Sketcher::GeoListModel<std::unique_ptr<Sketcher::GeometryFacade const, std::default_delete<Sketcher::GeometryFacade const> > > const&) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/SketcherGui.so+0x4d03
#5  0x7f655ea4f322 in SketcherGui::EditModeCoinManager::processGeometryConstraintsInformationOverlay(Sketcher::GeoListModel<std::unique_ptr<Sketcher::GeometryFacade const, std::default_delete<Sketcher::GeometryFacade const> > > const&, bool) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/SketcherGui.so+0x96
#6  0x7f655ea979ff in SketcherGui::ViewProviderSketch::draw(bool, bool) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/SketcherGui.so+0xbd
#7  0x7f655ea97d67 in SketcherGui::ViewProviderSketch::updateData(App::Property const*) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/SketcherGui.so+0x15d
#8  0x7f677b94669a in Gui::ViewProvider::update(App::Property const*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x64
#9  0x7f677b96410c in Gui::ViewProviderDocumentObject::update(App::Property const*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0xee
#10  0x7f677b377534 in Gui::Document::slotChangedObject(App::DocumentObject const&, App::Property const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x6e
#11  0x7f677b3c6e54 in void std::__invoke_impl<void, void (Gui::Document::*&)(App::DocumentObject const&, App::Property const&), Gui::Document*&, App::DocumentObject const&, App::Property const&>(std::__invoke_memfun_deref, void (Gui::Document::*&)(App::DocumentObject const&, App::Property const&), Gui::Document*&, App::DocumentObject const&, App::Property const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x95
#12  0x7f677b3c0923 in std::__invoke_result<void (Gui::Document::*&)(App::DocumentObject const&, App::Property const&), Gui::Document*&, App::DocumentObject const&, App::Property const&>::type std::__invoke<void (Gui::Document::*&)(App::DocumentObject const&, App::Property const&), Gui::Document*&, App::DocumentObject const&, App::Property const&>(void (Gui::Document::*&)(App::DocumentObject const&, App::Property const&), Gui::Document*&, App::DocumentObject const&, App::Property const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x67
#13  0x7f677b3baf1c in void std::_Bind<void (Gui::Document::*(Gui::Document*, std::_Placeholder<1>, std::_Placeholder<2>))(App::DocumentObject const&, App::Property const&)>::__call<void, App::DocumentObject const&, App::Property const&, 0ul, 1ul, 2ul>(std::tuple<App::DocumentObject const&, App::Property const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0xa0
#14  0x7f677b3b3440 in void std::_Bind<void (Gui::Document::*(Gui::Document*, std::_Placeholder<1>, std::_Placeholder<2>))(App::DocumentObject const&, App::Property const&)>::operator()<App::DocumentObject const&, App::Property const&, void>(App::DocumentObject const&, App::Property const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x58
#15  0x7f677b3ac24d in boost::detail::function::void_function_obj_invoker2<std::_Bind<void (Gui::Document::*(Gui::Document*, std::_Placeholder<1>, std::_Placeholder<2>))(App::DocumentObject const&, App::Property const&)>, void, App::DocumentObject const&, App::Property const&>::invoke(boost::detail::function::function_buffer&, App::DocumentObject const&, App::Property const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x33
#16  0x7f6779b54d46 in boost::function2<void, App::DocumentObject const&, App::Property const&>::operator()(App::DocumentObject const&, App::Property const&) const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x62
#17  0x7f6779b4767c in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (App::DocumentObject const&, App::Property const&)>, 0u, 1u, App::DocumentObject const&, App::Property const&>(boost::function<void (App::DocumentObject const&, App::Property const&)>&, boost::signals2::detail::unsigned_meta_array<0u, 1u>, std::tuple<App::DocumentObject const&, App::Property const&> const&, boost::enable_if<boost::is_void<boost::function<void (App::DocumentObject const&, App::Property const&)>::result_type>, void>::type*) const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x48
#18  0x7f6779b2d35b in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (App::DocumentObject const&, App::Property const&)>, App::DocumentObject const&, App::Property const&, 2ul>(boost::function<void (App::DocumentObject const&, App::Property const&)>&, std::tuple<App::DocumentObject const&, App::Property const&> const&, mpl_::size_t<2ul>) const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x2d
#19  0x7f6779b0ee2c in boost::signals2::detail::void_type boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > const&) const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x46
#20  0x7f6779af4f12 in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> >::dereference() const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x54
#21  0x7f6779ae2db2 in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> >::reference boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x18
#22  0x7f6779acc684 in boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x20
#23  0x7f6779ab27e9 in void boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> >) const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x17
#24  0x7f6779a9af84 in void boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, App::DocumentObject const&, App::Property const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (App::DocumentObject const&, App::Property const&), boost::function<void (App::DocumentObject const&, App::Property const&)> >, boost::signals2::mutex> >) const from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x68
#25  0x7f6779a88428 in boost::signals2::detail::signal_impl<void (App::DocumentObject const&, App::Property const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (App::DocumentObject const&, App::Property const&)>, boost::function<void (boost::signals2::connection const&, App::DocumentObject const&, App::Property const&)>, boost::signals2::mutex>::operator()(App::DocumentObject const&, App::Property const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x244
#26  0x7f6779a7a994 in boost::signals2::signal<void (App::DocumentObject const&, App::Property const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (App::DocumentObject const&, App::Property const&)>, boost::function<void (boost::signals2::connection const&, App::DocumentObject const&, App::Property const&)>, boost::signals2::mutex>::operator()(App::DocumentObject const&, App::Property const&) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x3a
#27  0x7f6779a54a5e in App::Document::onChangedProperty(App::DocumentObject const*, App::Property const*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x32
#28  0x7f6779b7931f in App::DocumentObject::onChanged(App::Property const*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x601
#29  0x7f670e2b1947 in Part::Feature::onChanged(App::Property const*) from /home/qewer/Desktop/Git/freecad-build/Mod/Part/Part.so+0x1e3
#30  0x7f670a2a2e37 in Sketcher::SketchObject::onChanged(App::Property const*) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/Sketcher.so+0x489
#31  0x7f6779d08c25 in App::Property::hasSetValue() from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADApp.so+0x59
#32  0x7f670e2f30be in Part::PropertyGeometryList::setValues(std::vector<Part::Geometry*, std::allocator<Part::Geometry*> >&&) from /home/qewer/Desktop/Git/freecad-build/Mod/Part/Part.so+0x1b2
#33  0x7f670e2f2edd in Part::PropertyGeometryList::setValues(std::vector<Part::Geometry*, std::allocator<Part::Geometry*> > const&) from /home/qewer/Desktop/Git/freecad-build/Mod/Part/Part.so+0xb5
#34  0x7f670a2732a6 in Sketcher::SketchObject::solve(bool) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/Sketcher.so+0x324
#35  0x7f655ea987f1 in SketcherGui::ViewProviderSketch::setEdit(int) from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/SketcherGui.so+0x8db
#36  0x7f677b945a51 in Gui::ViewProvider::startEditing(int) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x2d
#37  0x7f677b96dced in Gui::ViewProviderDragger::startEditing(int) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x2f
#38  0x7f677b374a32 in Gui::Document::setEdit(Gui::ViewProvider*, int, char const*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x15be
#39  0x7f655ea96e87 in SketcherGui::ViewProviderSketch::doubleClicked() from /home/qewer/Desktop/Git/freecad-build/Mod/Sketcher/SketcherGui.so+0x37
#40  0x7f677b6d029d in Gui::TreeWidget::mouseDoubleClickEvent(QMouseEvent*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x3a5
#41  0x7f6776ff43b1 in QWidget::event(QEvent*) from /lib64/libQt5Widgets.so.5+0xfa1
#42  0x7f67770a4bc7 in QFrame::event(QEvent*) from /lib64/libQt5Widgets.so.5+0x27
#43  0x7f67762b3f36 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /lib64/libQt5Core.so.5+0x96
#44  0x7f6776faeb65 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQt5Widgets.so.5+0x75
#45  0x7f6776fb7456 in QApplication::notify(QObject*, QEvent*) from /lib64/libQt5Widgets.so.5+0x1206
#46  0x7f677b419b21 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0xff
#47  0x7f67762b4188 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib64/libQt5Core.so.5+0x128
#48  0x7f6776fb56a4 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /lib64/libQt5Widgets.so.5+0x1d4
#49  /lib64/libQt5Widgets.so.5(+0x20d1a9) [0x7f677700d1a9]
#50  /lib64/libQt5Widgets.so.5(+0x21072f) [0x7f677701072f]
#51  0x7f6776faeb75 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQt5Widgets.so.5+0x85
#52  0x7f677b419b21 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0xff
#53  0x7f67762b4188 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib64/libQt5Core.so.5+0x128
#54  0x7f677676cbf8 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /lib64/libQt5Gui.so.5+0x828
#55  0x7f677674acfc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQt5Gui.so.5+0xac
#56  /lib64/libQt5XcbQpa.so.5(+0x714d6) [0x7f676460f4d6]
#57  /lib64/libglib-2.0.so.0(g_main_context_dispatch+0x14c) [0x7f677331348c]
#58  /lib64/libglib-2.0.so.0(+0xba648) [0x7f6773371648]
#59  /lib64/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f6773310b13]
#60  0x7f6776306729 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQt5Core.so.5+0x69
#61  0x7f67762b2b4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQt5Core.so.5+0x13b
#62  0x7f67762baddb in QCoreApplication::exec() from /lib64/libQt5Core.so.5+0x9b
#63  0x7f677b2b4d9f in Gui::Application::runApplication() from /home/qewer/Desktop/Git/freecad-build/lib/libFreeCADGui.so+0x2c75
#64  ./FreeCAD() [0x42652d]
#65  /lib64/libc.so.6(+0x27b4a) [0x7f6775a49b4a]
#66  /lib64/libc.so.6(__libc_start_main+0x8b) [0x7f6775a49c0b]
#67  ./FreeCAD() [0x425725]
</pre>
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grubertechnic** [comment]
Confirmed. Newer files have no issue. Tried some older files, they crash also. Would be interesting, on which version of file it starts to crash.

**Comment by chennes** [comment]
Here's the relevant part of the backtrace:
```
Sketcher::GeometryFacade::getGeometry<…>() const GeometryFacade.h:242
Sketcher::GeoListModel::getGeometryFromGeoId(const std::vector<…> &, int) GeoList.cpp:107
Sketcher::GeoListModel::getGeometryFromGeoId(int) const GeoList.cpp:134
SketcherGui::EditModeConstraintCoinManager::processConstraints(const Sketcher::GeoListModel<…> &) EditModeConstraintCoinManager.cpp:829
SketcherGui::EditModeCoinManager::processGeometryConstraintsInformationOverlay(const Sketcher::GeoListModel<…> &, bool) EditModeCoinManager.cpp:741
SketcherGui::ViewProviderSketch::draw(bool, bool) ViewProviderSketch.cpp:2990
SketcherGui::ViewProviderSketch::updateData(const App::Property *) ViewProviderSketch.cpp:3064
Gui::ViewProvider::update(const App::Property *) ViewProvider.cpp:308
Gui::ViewProviderDocumentObject::update(const App::Property *) ViewProviderDocumentObject.cpp:383
Gui::Document::slotChangedObject(const App::DocumentObject &, const App::Property &) Document.cpp:795
```

**Comment by chennes** [comment]
Running a recompute object before loading the sketch seems to prevent the issue.
