### ISSUE TITLE
[Problem] Data at point clip filter leaves point symbols after being deleted

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#10438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33992 (Git)
Build type: Release
Branch: master
Hash: 90bafb3a069468455d8c65d030ef8750b510c39b
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
[/code]
```

### Subproject(s) affected?

FEM

### Problem description

The Data at point clip filter leaves white dot/sphere symbols at the selected points. After the filter is deleted, those symbols are still displayed on the model:

![after](https://github.com/FreeCAD/FreeCAD/assets/59876896/a7f96563-d0db-4b66-9047-1baf9f0f6ce4)

Moreover, they are still shown even when everything related to the analysis is deleted:

![symbols](https://github.com/FreeCAD/FreeCAD/assets/59876896/e8bea04d-a1f8-4396-955d-33b0da3801f8)

They disappear only when the file is reloaded.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Can someone locate this in the source and post here ?
