### ISSUE TITLE
[Problem]Issue display hides description

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FreeCAD#10448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
any
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

a) When viewing Issues, the description of the problem is hidden on initial presentation and requires scrolling before it is visible.  The description is a more significant piece of information than the data ahead of it in the current template.

b) When creating a new Issue, the text "File an problem report" is too cryptic and does not provide any guidance.  

### Anything else?

Forum discussion: https://forum.freecad.org/viewtopic.php?t=80789

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kadet1090** [comment]
I've created PR assuming that we description that I proposed in the forum. I also moved the description field to be secon in the form because this is only way to reoder fields in rendered template - or at least I was not able to find any better solution.
