### ISSUE TITLE
[Feature] Custom CSS option for StartPage

### ISSUE THREAD

**Issue by qewer33** [FreeCAD/FreeCAD#10451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Fedora Linux 38 (KDE Plasma) (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34071 (Git)
Build type: Release
Branch: startpage-housekeeping
Hash: 932fd4638ba80671115fb2aa871ab3a273b6f673
Python 3.11.4, Qt 5.15.10, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Glass
  * lattice2 1.0.0
  * kicadStepUpMod 10.19.4
  * Manipulator 1.5.0
  * Assembly4.backup1691951820.225657 0.50.2
  * Assembly4
  * Behave-Dark-Colors 0.1.1
  * Curves 0.6.13
  * DynamicData 2.46.0
  * fasteners 0.4.59
  * Freecad-Built-in-themes-beta 1.2.2
  * freecad.gears.backup1692223246.5590403 1.0.0
  * freecad.gears
  * ExtremeProLight 1.6.0
  * A2plus 0.4.60n
  * ExplodedAssembly
  * FreeCAD_DarkPreferencePAck 0.0.1
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

There are many power users who want to customize the StartPage for their own use cases. Preference packs might also want to customize the StartPage. Currently pref packs can do this with a stylesheet if "Use FreeCAD stylesheet" option under Start WB preferences is checked. There's also a "Custom template" option for power users. 

But I feel like adding a "custom CSS" option to Start preferences would make this significantly easier for power users and preference packs. It'll ideally be a text area where you can paste your custom CSS in and the StartPage will apply it on top of it's default CSS. And honestly if this is implemented, the custom template option can be removed. I have never heard of anyone in the community using it (please mention if you have) and never seen any alternative templates online.

I can open a PR for this myself, this is just a discussion issue in-case someone opposes it or suggests something more/else.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
The idea of the template is that a company, or for ex a school, could provide their own start page with their own custom stuff in it. Indeed I've never heard of anyone using it, but that does not mean nobody outside the community is using it or that it's not useful.

I agree it can be useful too to let users provide a custom css, though.

**Comment by qewer33** [comment]
> The idea of the template is that a company, or for ex a school, could provide their own start page with their own custom stuff in it. Indeed I've never heard of anyone using it, but that does not mean nobody outside the community is using it or that it's not useful.

Oh alright, that use case does make sense. Didn't think about it.

**Comment by qewer33** [comment]
Also @yorikvanhavre I think you're one of the people who handle the wiki accounts. I've made quite a few Start changes and would like to document my changes for the Release Notes and Start WB docs. Can I get a wiki account (username: qewer, email: qewer33@proton.me)

Sorry if this is the wrong place to ask

**Comment by yorikvanhavre** [comment]
> Can I get a wiki account?

Done! Check your email!

**Comment by qewer33** [comment]
> Done! Check your email!

It arrived. Thanks a lot!
