### ISSUE TITLE
[Problem] App::PropertyPythonObject is not saving data 

### ISSUE THREAD

**Issue by Serince** [FreeCAD/FreeCAD#10460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.11.4, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * aa.qrc
  * FEMbyGEN 1.5.0
  * Plot 2022.4.17
  * Ship 2022.4.11
  * CfdOF 1.19.4
[/code]
```

### Subproject(s) affected?

None

### Problem description

I use App::PropertyPythonObject to store some data in an object. When I save the file and open it again, no data comes with the created PropertyPythonObject  in 0.21 version. When I try the same process in version 0.20.2, it works fine.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@Serince can you demonstrate the bug ?

**Comment by Serince** [comment]
Sorry, I checked several times before I posted the error and there was indeed such a bug. Now when I try it on another computer to show it I don't have this problem, I think there is something wrong with my configuration. Let me reinstall freecad. I apologize for opening an issue without investigating the bug in more detail.

**Comment by Serince** [comment]
Hello,

I catch the error again. The problem comes with python 3.11 . I have installed two conda environment to test it. The data is storing freecad 0.21.1 Python 3.10. But freecad 0.21.1 Python 3.11 has the bug. Not storing data in object as ProperyPythonObject. I add a small macro to store data. After running it, save the file and close / reopen the file. When you call the stored data it will return None.

import FreeCAD as App
doc=App.newDocument()
obj=doc.addObject("Part::Box","Box")
doc.recompute()
obj.addProperty("App::PropertyPythonObject", "Dictionary")
obj.Dictionary={"Stored data": [3,5,7]}
print(obj.Dictionary)

![before](https://github.com/FreeCAD/FreeCAD/assets/10951891/a98c1164-89ff-475e-9498-a9ad1639dc69)
![After_Reopen](https://github.com/FreeCAD/FreeCAD/assets/10951891/fee0dee2-64e9-4969-9cd9-60993aefab56)

**Comment by Syres916** [comment]
Confirmed using Python 3.8.10 and Python 3.11.2


```
OS: Debian GNU/Linux 12 (bookworm) (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34020 (Git)
Build type: Release
Branch: master
Hash: 6200150fac0e311cefb4c4a2c3122455d2856251
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
```

**Comment by Syres916** [comment]
If it's of use to the devs, extracting the Document.xml from each file created exactly the same way gives:

Python 3.11

```
<Property name="Dictionary" type="App::PropertyPythonObject" group="" doc="" attr="0" ro="0" hide="0" status="2097152">
<Python value="bnVsbA==" encoded="yes" json="yes"/>
</Property>
```

Python 3.8

```
<Property name="Dictionary" type="App::PropertyPythonObject" group="" doc="" attr="0" ro="0" hide="0" status="2097152">
<Python value="eyJTdG9yZWQgZGF0YSI6IFszLCA1LCA3XX0=" encoded="yes" json="yes"/>
</Property>
```

BTW, `value="bnVsbA=="` translates to `Null`

I checked the json library version on both and they are the same version: 2.0.9. Could this be yet another encoding issue??

**Comment by Syres916** [comment]
If the PR is accepted then I'll raise a backport PR so 0.21.2 has the fix.

**Comment by wwmayer** [comment]
File created with FreeCAD using Py3.10:
[issue_10460_Py310.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/12539795/issue_10460_Py310.FCStd.zip)

**Comment by s-quirin** [comment]
I'd like to point out that people have to implement the methods `dumps` and `loads` to avoid errors since the release of FreeCAD 0.21.2 and keep `__getstate__` and `__setstate__` (for FreeCAD < 0.21.2). Was this intended for this minor realease?

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * FEMbyGEN 2.0.0
```

@Serince: issue addressed in PR

**Comment by Syres916** [comment]
@s-quirin add-on PRs are being dealt with piecemeal, see https://forum.freecad.org/viewtopic.php?p=729512#p729512
There was a minor backport that didn't make it into 0.21.2 but will be in 0.21.3
