### ISSUE TITLE
[Problem] Draft Move, wrong selection after task finished

### ISSUE THREAD

**Issue by benj5378** [FreeCAD/FreeCAD#10469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34091 (Git) Snap 758
Build type: Release
Branch: master
Hash: a2735416e1189566329b327d99f115ced7071b86
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
Installed mods: 
  * Help 1.0.3
```

### Subproject(s) affected?

Draft

### Problem description

I want to move object1. I start by selecting object1 in the hierachy, then click the Draft Move tool, I click a reference point and then a point on object2 as the destination. After the move have finished, the selected object is now that of the destination, object2's padding.

This is really inconvenient, because if I want to move object1 again, I now need to go through the hierachy, find the object and select it again.

It would be both convenient and expected, that after the Draft Move task have finished, the selection before the task started would be preserved.

[Screencast from 2023-09-01 00-24-08.webm](https://github.com/FreeCAD/FreeCAD/assets/12400097/756191cc-2852-4228-a4e4-bf5e2b3c83f6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Wrong video?

**Comment by benj5378** [comment]
> Wrong video?

yes, updated with new vid

**Comment by Roy-043** [comment]
Confirmed. AFAICT one of the edges of the target object has to have been highlighted for the problem to occur.

In my initial test with 2 Draft_Circles and only using center snap, the problem did not occur as I snapped to the center of the face of the target and moved there without its edge being highlighted.

**Comment by Roy-043** [comment]
Related forum topic:
https://forum.freecad.org/viewtopic.php?t=75617
