### ISSUE TITLE
[Assembly] User can't move/rotate parts easily

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#10479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
Latest 0.22
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

In most CADs when you are working on an assembly, you can move parts of the assembly by clicking and dragging. This let you :
- easily position parts roughly at the beginning
- Move parts in a constrained assembly to make 'real' motions.

short video from OnShape (3:04), I think it will make it clearer what I mean : https://www.onshape.com/en/resource-center/videos/build-your-first-assembly

It is also usual to be able to rotate parts by holding ctrl while clicking and moving mouse.

Forum discussion :
https://forum.freecad.org/viewtopic.php?t=80773

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
This should also include "natural" boundaries or constraints like:

- no intersection of solid bodies
- prevent bodies from being stretched or compressed when linked to other objects (e.g. hinges)

**Comment by PaddleStroke** [comment]
That would be ideal but it's probably be pretty difficult to implement.
