### ISSUE TITLE
[Problem] Exporting a link array object gives an incorrect result

### ISSUE THREAD

**Issue by atlast-50** [FreeCAD/FreeCAD#10545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When exporting a part made with the draft array tool to either stl or 3mf format, upon importing the object into another tool it's as if the array tool was not applied at all. 

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.2
[/code]
```

### Subproject(s) affected?

Core

### Anything else?

Applying a compound or connect operation after the array tool then exporting gives the result I would expect from just exporting the array object. Importing an exported 3mf of an array object into prusa slicer shows the array subelements are placed directly on top of each other, so possibly the array intervals are not being applied on export to the subelements?

Test case of a 3x3 array of cubes, exporting the part called "failure" gives an incorrect result, the two "success" parts work as expected.
[arrayexportbug.zip](https://github.com/FreeCAD/FreeCAD/files/12517045/arrayexportbug.zip)

Result of importing the failure and success parts exported as 3mf into prusa slicer, with the 9 stacked failure subelements selected.
![image](https://github.com/FreeCAD/FreeCAD/assets/144068262/1e6e6542-0971-40d7-9dbd-9ed8b6bfb729)

Result when importing exported stl's for the same parts.
![image](https://github.com/FreeCAD/FreeCAD/assets/144068262/027d11da-a7a3-4dcb-bbaa-2ce8c8598c30)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Confirmed. It has to do with the fact that you have created a link array. An easier way to avoid the issue is to uncheck the "Link array" checkbox when creating the array.

The problem also occurs with an array created from a Link, so it is not a Draft issue.

**Comment by bgbsww** [comment]
This also happens in the .ast ( Ascii STL ) format, which is great because it makes it really clear what is happening here:  The multiple elements are in fact being exported, but every element in the array has the exact same position; the array element positioning is not being applied during the export.

**Comment by bgbsww** [comment]
Here's the issue.  Two problems:  the last parm of getLinkedObject should be true to allow population of the transformation matrix, and the meshCache doesn't know to recompute and use that matrix on subsequent loops.

Disabling the cache makes it work, but that's a lousy solution, so rework of the cache is in order.

https://github.com/FreeCAD/FreeCAD/blob/ba95a534d5e622721db45b48d20b933e85f01138/src/Mod/Mesh/App/Exporter.cpp#L110-L112

**Comment by Montaire** [comment]
I have the same issue with the 35176-2023-11-23 development version as well.

In FreeCad it looks like this:
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/97aa12e4-8e79-4fe1-aeba-da9936851d58)

Exported from 21.1 release:
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/e32f84d5-b966-478e-8b17-c37de7bf440d)
As you see from the support only one element is exported

Exported from 22  35176-2023-11-23 release:
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/ec284f8d-7d76-4643-8dff-08e74dad6296)

And here is my model, I am not sure if I did anything wrong here:
[battery_holder_v3.6.zip](https://github.com/FreeCAD/FreeCAD/files/13464191/battery_holder_v3.6.zip)

**Comment by bgbsww** [comment]
At first glance, I think this is a different issue.  The link array is being followed, but the underlying mirror isn't right.  I'm suspicious that it has to do with the (lack of) depth setting in the getLinkedObject call, but I haven't started looking in earnest yet.  Thanks for the example file!  It's clearly an issue.
