### ISSUE TITLE
[Problem] SystemDllWrite violation reported by Cylance Protect

### ISSUE THREAD

**Issue by gilmiz** [FreeCAD/FreeCAD#10588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Cylance Protect identify **SystemDllWrite** as threat and block it.
No apparent influence on the way Freecad operate other than these notifications.

![image](https://github.com/FreeCAD/FreeCAD/assets/16917848/f24ac8ca-d072-4b80-98ee-50cbafb393c8)

![image](https://github.com/FreeCAD/FreeCAD/assets/16917848/6a46d0d7-f172-49aa-8f99-0d5359307a83)

Description as for why can be found in the [Cylance API / User API Guide](https://docs.blackberry.com/content/dam/docs-blackberry-com/release-pdfs/en/cylance-products/api-and-developer-guides/Cylance_User_API_Guide.pdf) (page 76), described as: 

> systemdllwrite (System DLL Overwrite) - Windows only: An attempt to overwrite a system DLL has been detected.

The issue was not notice on the 0.20 version.

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Danish/Denmark (da_DK)
Installed mods: 
  * Assembly4 0.50.2
  * fasteners 0.4.64
  * sheetmetal 0.3.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Needs to be flagged as false positive

**Comment by wwmayer** [comment]
The function `SystemDllWrite` isn't used anywhere in the FreeCAD code base.

**Comment by luzpaz** [comment]
@gilmiz where did you download FreeCAD from ?

**Comment by gilmiz** [comment]
It was downloaded form the freecadweb.org site

**Comment by luzpaz** [comment]
Weird, is it coming from one of the addons ?? 
CC @shaise and @Zolko-123 have you seen this before ? (`SystemDllWrite`)

**Comment by Zolko-123** [comment]
Assembly4 is Python only, no DLL involved

**Comment by wwmayer** [comment]
Each FreeCAD add-on is Python only, so no DLL involved. The only theoretical possibility is that a 3rd party library uses this function. But I don't think this is the case because if you google for "SystemDllWrite" then there are altogether only three hits and one of them is this ticket.

**Comment by luzpaz** [comment]
@gilmiz what is the exact download link that you used ? 

(Can the issue be coming from one of the Window installers, for example the libpack related windows installer ?)

**Comment by shaise** [comment]
> Weird, is it coming from one of the addons ?? 
> >  * Assembly4 0.50.2
> >  * fasteners 0.4.64
> >  * sheetmetal 0.3.0
> 
> CC @shaise and @Zolko-123 have you seen this before ? (`SystemDllWrite`)
> 

Did not encounter this issue. But then again I do not use Cylance Protect.

**Comment by luzpaz** [comment]
@gilmiz any follow-up to this ? we haven't heard of any other reports of this btw.

**Comment by gilmiz** [comment]
Apologies. 
It was downloaded from the www.freecadweb.org (https://www.freecad.org/thankyou.php?url=https%3A%2F%2Fgithub.com%2FFreeCAD%2FFreeCAD%2Freleases%2Fdownload%2F0.21.1%2FFreeCAD-0.21.1-WIN-x64-installer-1.exe)

**Comment by luzpaz** [comment]
Can you send Cylance feedback on this, @gilmiz ? This looks like a false positive. We haven't heard of any other issues since.

I'm closing ticket for now. Please feel free to re-open it.
