### ISSUE TITLE
Sketcher angle dimensions between two lines/axis must switch to supplementary angle

### ISSUE THREAD

**Issue by 69Piero** [FreeCAD/FreeCAD#10608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

currently the angular constraint between a line and axis is fixed and pften gives back the "unwanted angle". the tool should switch to supplementary angle value according to user's need 

### Full version info

```shell
[code]
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34198 (Git)
Build type: Release
Branch: master
Hash: e401e203af7ec9924de5174d5e2f63d2dc52fc2f
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Italian/Italy (it_IT)
Installed mods: 
  * 3DfindIT 1.2.0
  * CurvedShapes 1.0.4
  * Curves 0.6.13
  * dxf-library
  * fasteners 0.4.63
  * fasteners.backup1693551082.0742238 0.4.62 (Disabled)
  * freecad.gears 1.0.0
  * QuickMeasure 2022.10.28
  * Silk 0.1.4
[/code]
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by howie-j** [comment]
As said on the forum, there is an existing issue for this: https://github.com/FreeCAD/FreeCAD/issues/10603
Please close this one as a duplicate.
