### ISSUE TITLE
[Problem] ladybug in requirements.txt is the wrong package

### ISSUE THREAD

**Issue by eye942** [FreeCAD/FreeCAD#10625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The ladybug package in [requirements.txt](https://github.com/FreeCAD/FreeCAD/blob/577004c1eba55641e92ea085fa6a078d36f49a06/requirements.txt#L6) is incorrect.

It should either be changed to `ladybug-core` ([github](https://github.com/ladybug-tools/ladybug), [pypi](https://pypi.org/project/ladybug-core/)) or removed. 

The current ladybug package [pypi](https://pypi.org/project/ladybug/) doesn't do anything assumed by the [code](https://github.com/FreeCAD/FreeCAD/blob/577004c1eba55641e92ea085fa6a078d36f49a06/src/Mod/Arch/ArchSite.py#L314)

### Full version info

```shell
N/A - more of a code review.
```

### Subproject(s) affected?

Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
I think this can be closed now?
