### ISSUE TITLE
[Problem] 

### ISSUE THREAD

**Issue by gebze52** [FreeCAD/FreeCAD#10647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When you make a double helix in the gear module, the surfaces do not give the exact value. Can you fix it?
![dubble helix](https://github.com/FreeCAD/FreeCAD/assets/143847377/4cc5029a-5f8c-463e-85af-a4031cb92ff9)

### Full version info

```shell
[code]
OS: Windows 10 build 10240
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Turkish/Turkey (tr_TR)
Installed mods: 
  * A2plus 0.4.60n
  * fasteners 0.4.63
  * freecad.gears 1.0.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Wrong repo. Please open a ticket on https://github.com/looooo/freecad.gears
