### ISSUE TITLE
[Problem] Failed cutting operation between a thread and a cilindre

### ISSUE THREAD

**Issue by Nosnahc** [FreeCAD/FreeCAD#10682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello
I'm trying to create a thread on a cylinder using the Fastener plugin. 
I generated a ScrewDie 
![filetage](https://github.com/FreeCAD/FreeCAD/assets/123942344/d1a2c1f5-72b7-4a0a-94b0-be2b2545599a)

and I try to make a "cut" operation but the result is unexpected.
![cut](https://github.com/FreeCAD/FreeCAD/assets/123942344/aa95d6cb-c86b-43fe-b7d9-c7a8147e69fb)

### Full version info

```shell
OS: KDE Flatpak runtime (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at f670854)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * fasteners 0.4.66
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@Nosnahc Please open a ticket at  https://github.com/shaise/FreeCAD_FastenersWB
