### ISSUE TITLE
[Assembly4] Mirrored objects are always in black

### ISSUE THREAD

**Issue by bjnobre** [FreeCAD/FreeCAD#10685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I can't change the color of a a mirrored object on assembly 4.
See the image bellow
[https://gitlab.com/bjnobre/shared2web/-/raw/main/WhatsApp_Image_2023-09-11_at_13.36.00.jpeg?ref_type=heads](url)

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (qtile)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at f670854)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Installed mods: 
  * A2plus 0.4.60n
  * Assembly4 0.50.2
  * sheetmetal 0.3.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by howie-j** [comment]
Please create an issue here instead: [https://github.com/Zolko-123/FreeCAD_Assembly4/issues](https://github.com/Zolko-123/FreeCAD_Assembly4/issues)
