### ISSUE TITLE
[Problem] command groups in toolbars are too small in Dark/ProDark.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#10694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

On linux : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/e818fdaa-40b1-4fd1-b140-7592c8a09225)
On windows : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/e7a4f65f-abd0-4b76-87cc-4f902fb3af5f)

It is now very tedious to select tools. Even worse on windows.

In the dark theme it's even worse : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/d3a2d0ab-ee6c-4986-80b0-2c6e5b176410)

I think this has been recently introduced. @MisterMakerNL is it part of your rework on the stylesheet?
If so can this be reverted ?

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34301 +3 (Git)
Build type: Release
Branch: move_box_datumLabel
Hash: e3bc1ce92429bf5b25b5c5f52578fd1853a8c86f
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk , OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.60k
  * Assembly3 0.12.0
  * Assembly4 0.50.2
  * Curves 0.6.8
  * ExtremeProLight 1.5.0
  * FreeCAD - Shortcut.lnk
  * FreeCAD_FastenersWB-master 0.4.56
  * Ondsel 2023.8.23.02
  * ProDarkThemePreferencePack 1.0.0
  * sheetmetal 0.2.63
[/code]
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
Issue here is the vast amount of icons freecad has and the old solution losing lots of screenspace. And the layout of the toolbars are not aligned.
Furter this option has been tested in linkstage without any complaints. I personally think it works great.
But nevertheless we can try a optimize it. I know there is an issue with icon size and the size if the pull down icon.

**Comment by kadet1090** [comment]
Personally I really like this behavior because when the toolbar is placed on the side it does not waste space and it nicely align icons. But a little bit more clicking space would be welcome.

![image](https://github.com/FreeCAD/FreeCAD/assets/747404/bc0e6ea4-c781-49c5-817f-d426d8c4cb75)

**Comment by adrianinsaval** [comment]
I talked of this before too, at least a minimum amount of padding should be present. No need to go exactly to what we had before, but at least a middle ground. In any case if you really want a stylesheet like this it could be provided as a compact variant.
