### ISSUE TITLE
[Problem] Missing API documentation for `src/Mod/Part/App/HLRBRep`

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#10728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently the https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/Part/App/HLRBRep XML files show no documentation about said HLRBRep functionality. Discovered in #10726 & #10727

https://github.com/FreeCAD/FreeCAD/blob/4293c4a65b0e69975dcdbbf68c80d8019a4f850d/src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPy.xml#L15-L106

https://github.com/FreeCAD/FreeCAD/blob/4293c4a65b0e69975dcdbbf68c80d8019a4f850d/src/Mod/Part/App/HLRBRep/HLRBRep_PolyAlgoPy.xml#L15-L114

https://github.com/FreeCAD/FreeCAD/blob/4293c4a65b0e69975dcdbbf68c80d8019a4f850d/src/Mod/Part/App/HLRBRep/HLRToShapePy.xml#L15-L87

https://github.com/FreeCAD/FreeCAD/blob/4293c4a65b0e69975dcdbbf68c80d8019a4f850d/src/Mod/Part/App/HLRBRep/PolyHLRToShapePy.xml#L15-L81

### Full version info

```shell
v0.22.x master branch
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pieterhijma** [comment]
I haven't had time yet, Is it time critical? If so, I could increase its priority, if you prefer.

**Comment by luzpaz** [comment]
Not critical.

**Comment by RohanMishra315** [comment]
Hey @luzpaz should I work on it. Already make the changes just need to do PR.

**Comment by luzpaz** [comment]
@RohanMishra315 yes please. Thanks!

**Comment by pieterhijma** [comment]
@RohanMishra315, great that you could work on it! Looks like a great start, but there are other files that lack documentation as well as @luzpaz mentioned above. Next week I will have time to take a look as well, if you want, we can work on it together. Otherwise, I will build on your changes.
