### ISSUE TITLE
[Assembly] Card 1 : JCS are ugly

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#10745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Following the introduction of https://github.com/FreeCAD/FreeCAD/pull/10611 : 
The created JCS are fairly ugly.
@qewer33 the mockup you posted seems good to me. Do you want to attempt to implement it in coin or do you want me to jump in ?
Mockup : ![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/8209d99d-2387-4eb4-96f4-a56b9909d5cf)

### Full version info

```shell
0.22 after https://github.com/FreeCAD/FreeCAD/pull/10611
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qewer33** [comment]
> Following the introduction of #10611 : The created JCS are fairly ugly. @qewer33 the mockup you posted seems good to me. Do you want to attempt to implement it in coin or do you want me to jump in ?

I can give it a shot but I need some pointers. What classes/files do I need to modify, or do I need to create a brand new class? Python or C++?

Also here are new mockups (with a circle alternative) with the plane on the center:

![image](https://github.com/FreeCAD/FreeCAD/assets/69015181/f6703f14-49ea-4433-b520-3ee763d8142e)

**Comment by PaddleStroke** [comment]
It's python.
The coin code is in the JointObject.py ViewProviderJoint class

attach() is the function that creates the coin objects. and assign it to the display mode. In this function you can see : 
`self.switch_JCS1 = self.JCS_sep(obj, self.transform1)`
This is one joint coordinate system. So you can see its made in JCS_sep function
This function creates JCS = coin.SoAnnotation() this is basically the JCS coin object. You can see that the axis get added to this.
The axis themselves are create in the line_sep function.

The line thickness is a property, so it is actually defined in __init__.
The line lengths are applied by the self.axisScale. So its determined in get_JCS_size. Basically if you want to make them shorter you need to change this line : camera.height.getValue() / 10.
replace 10 by 20 and length will halve.
For the rectangle, you will need to create a soFaceSet (I seem to recall that's the name) And you will want to create it in a similar fashion as the lines are created.

**Comment by howie-j** [comment]
The circle one looks nice :100: 
It will also help visually to make sure the JCS is placed correctly, e.g in the center of a hole.

**Comment by PaddleStroke** [comment]
Alternate idea. Dunno what its worth.
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/a71ca5e6-cd18-4d49-9821-090f5ca29d8f)

**Comment by qewer33** [comment]
Got something working! I'll also attempt to implement the view scaling for JCS's (https://github.com/FreeCAD/FreeCAD/issues/10746) and try to make it a circle somehow (is there like a helper function to calculate vertices from a circle w/ radius or something for SoFaceSet or do I have to write one myself? or use like NURBS node perhaps? or maybe even a really thin cylinder, not sure) 

![image](https://github.com/FreeCAD/FreeCAD/assets/69015181/cae22933-8df6-49fe-8923-90f6c81ec9d3)

**Comment by PaddleStroke** [comment]
Great that's nice !
You can perhaps ask chatgpt he might have some ideals how to draw a circle.
Awesome if you can pick up the scaling as well !
