### ISSUE TITLE
[Regression] Sketcher angle constraint expression handling

### ISSUE THREAD

**Issue by howie-j** [FreeCAD/FreeCAD#10742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The new complementary angle functionality introduced in #10657 does not handle expressions correctly.

Test expression: 60
Complementary: 180 - 60
Back to original: 180 - (180 - 60)

Test expression 2: 60,00 °
Complementary: 180 - 60 ° _(Should be: 180 ° - 60 °)_

This gives an error:
`<class 'ArithmeticError'>: Quantity::operator -(): Unit mismatch in minus operation
in expression: 180 - 60 °
in property binding 'Unnamed#Sketch.Constraints'`

[angle_expr.webm](https://github.com/FreeCAD/FreeCAD/assets/82042580/6e353a66-c17a-425a-96d0-52d8740b100d)

### Full version info

```shell
[code]
OS: Fedora Linux 38 (Workstation Edition) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34352 (Git)
Build type: Release
Branch: master
Hash: ab4abab53d6cc81ffe834d7a34620f8fae4f3c6e
Python 3.11.5, Qt 5.15.10, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Sketcher

### Anything else?

@PaddleStroke 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
For the first case, it seems that the expression is simplified automatically. It should become '180 - (60)' which would then be reverted back to '60'. But the expression is automatically simplified to '180 - 60'.
