### ISSUE TITLE
[Assembly] Card 6 : In Joint taskbox, deleting an element in the list should unselect it. 

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#10750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Following the introduction of https://github.com/FreeCAD/FreeCAD/pull/10611 :

In the create Joint taskbox, pressing delete when an element in the list is selected should unselect it.
Currently, even if the QListWidget has the focus, Delete press event is handled by the current selection. So if you click Delete, it deletes the selected element. Which is of course unwanted.

### Full version info

```shell
0.22 after 10611
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
I gave this one a go yesterday and got stuck.

My approach was to install an event filter in TaskAssemblyCreateJoint __init__
`        self.form.featureList.installEventFilter(self)`
or directly on the form as well : 
`        self.form.installEventFilter(self)`

```
    def eventFilter(self, watched, event):
        print(event.type())
        
        if watched == self.form and event.type() == QtCore.QEvent.KeyPress:
            if event.key() == QtCore.Qt.Key_Delete:
                selected_indexes = self.form.featureList.selectedIndexes()

                for i in selected_indexes:
                    if i < len(self.current_selection) :
                        selection_dict = self.current_selection[i]
                        Gui.Selection.removeSelection(selection_dict["doc_name"],selection_dict["obj_name"],selection_dict["sub_name"])

                return True  # Consume the event
        return super().eventFilter(watched, event)
```
But the problem is that because the user currently has a selection (as we are using greedy selection), the event is consumed before we receive it, and it is used to delete the selection. Then an event QtCore.QEvent.ShortcutOverride is emited.

So on top of the unwanted behavior of deleting the selection, we do not receive the KeyPress event as it is consumed.

So after thinking about it, I wonder if we don't want to drop the greedy selection, and do as PartDesign Fillet tool is doing : manually highligthing manually (see ViewProviderDressUp::highlightReferences). Or alternatively, as A3 is doing, ie creating subshape binders.

**Comment by PaddleStroke** [comment]
@wwmayer Could you please weight in on this issue? Do you know how to prevent the 3dview selection from grabing the delete event when the QListWidget has the focus so that I can delete the item instead?

**Comment by maxwxyz** [comment]
additionally you should be able to add or remove references in the joint task dialog.

**Comment by wwmayer** [comment]
Usually if you want to override a key event that otherwise is handled by another instance you override the event() (keyEvent() may work too but don't know for sure) method and check for the type QEvent::ShortcutOverride. Then you check if the shortcut is what you want to handle. If yes, then either handle it directly or accept() it so that Qt sends a QKeyEvent that you must handle in keyEvent().

**Comment by PaddleStroke** [comment]
@wwmayer Thanks that solved it
