### ISSUE TITLE
[Feature request] Conveniently streamlined Transparency toggle

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#10770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It would be nice to have a transparency toggle, when activated it switch a part between 0 and 63 transparency (63 is a 'good' value).
This way it would enable user to toggle transparency easily, without having to right click, appearance ... Which is too long if someone just want to quickly check what is behind a part.

Forum discuss : https://forum.freecad.org/viewtopic.php?t=81275

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Is there a possibility to integrate this with the concept of a show/no show space (or group of objects with currently 63% or hidden objects [maybe identified with 0% transparency]). Then switch the visibility between all visible objects and all hidden objects.
https://forum.freecad.org/viewtopic.php?p=665961

Reference from CATIA: http://catiadoc.free.fr/online/intug_C2/intugrf0220.htm

**Comment by adrianinsaval** [comment]
alternatively, the view toolbar could have a combobox with a transparency slider. Or it could be in the status bar.

**Comment by maxwxyz** [comment]
Currently when selecting an object in the 3D view and hitting space bar - the last Part Design Feature is hidden, not the body or part. This makes it hard to see in the collapsed tree view, which items are visible or not. Changing visibility ob the body does not toggle the last feature of the body.

Can this be tackled in this approach to toggle the visibility of the whole body, not the last Part Design feature of the selected body?

**Comment by adrianinsaval** [comment]
I would consider that a separate issue, if you like you can check the issue tracker if there is an existing report and create one if there isn't.

**Comment by maxwxyz** [comment]
Thanks, I have created a separate issue for that: https://github.com/FreeCAD/FreeCAD/issues/11132
