### ISSUE TITLE
[Problem] FEM naming fix part 2

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#10786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After resolving #10134 with the help of @kaktusus, there are still a few names with "constraint" left where they shouldn't be present. I will try to clean this up. On this occasion, I will also consider removing "FEM" from some names where it's unnecessary.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34367 (Git)
Build type: Release
Branch: master
Hash: e36e16de59dece2d67caf478d25e3a6b825102c6
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
[/code]
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
"constraint" occurrences left to be removed:
- Constraint fixed
- Constraint displacement
- Constraint force
- Constraint pressure
- Constraint temperature

**Comment by luzpaz** [comment]
Thanks for doing this good work @FEA-eng!

**Comment by FEA-eng** [comment]
> Thanks for doing this good work @FEA-eng!

Yeah, I'm trying to improve the FEM workbench as much as possible but I will probably need help with this issue as well. I can change the names without "FEM_" for now but the latter will be much more tricky to replace.

**Comment by FEA-eng** [comment]
Ok, I think that I will leave those functions/files with "FEM_" and take care of the first group for now.

**Comment by FEA-eng** [comment]
Crowdin strings for the first group for our reference:
https://crowdin.com/translate/freecad/559/en-pl#6593161
https://crowdin.com/translate/freecad/559/en-pl#6593157
https://crowdin.com/translate/freecad/559/en-pl#6498312
https://crowdin.com/translate/freecad/559/en-pl#6593187
https://crowdin.com/translate/freecad/559/en-pl#6593203

**Comment by kaktusus** [comment]
Suggestions for new labels ?

**Comment by FEA-eng** [comment]
> Suggestions for new labels ?

Added :-)
