### ISSUE TITLE
[Problem] Assembly workbench should also recognize Part WB objects/solids

### ISSUE THREAD

**Issue by macdroid53** [FreeCAD/FreeCAD#10815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Tinkering with it I notice that it does not see Part workbench solids a linkable.

If the source file has a Body, it shows it available for linking.
If the source file has a Part (Std_Part), it shows it available for linking.
If the source file has a Part Cut, Extrude, etc., it is not available for linking.

I realize it is very early in development, but figured I'd point this out.

Posted about this in the forum: [https://forum.freecad.org/viewtopic.php?t=81311](url)

### Full version info

```shell
[code]
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34410 (Git)
Build type: Release
Branch: master
Hash: 836c237d3c40d925a5447d1f52841cbb9c25986f
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * MnesarcoUtils 0.2.2
  * ZolkoBase 0.0.1
  * lattice2 1.0.0
  * Curves 0.6.13
  * Nodes 0.1.36
  * Help 1.0.3
  * QuickMeasure 2022.10.28
  * Manipulator 1.5.0
  * Assembly
  * Assembly4 0.50.2
  * freecad.gears 1.0.0
  * sheetmetal 0.3.0
  * Silk 0.1.5
  * kicadStepUpMod 10.19.4
  * A2plus 0.4.60n
  * DynamicData 2.47.0
  * workfeature-macro
  * fasteners 0.4.66
  * ExtremeProDark 2.9.0
  * Defeaturing 1.2.0
  * CurvedShapes 1.0.4
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macdroid53** [comment]
I see that most issues have tags, but i missed how to set the tags before creating the issue. Now I can't figure out how to add them after the fact.

**Comment by howie-j** [comment]
The maintainers can add tags, add issues to projects etc. @luzpaz perhaps add this issue to the assembly project?

@macdroid53 what solids can the part workbench create, is there a list (or could you make one)?

**Comment by PaddleStroke** [comment]
Yes for now only part design bodies and App::Parts could be added. But there's no strong reason for this limitation so we can also accept Part wb objects directly.

**Comment by mno13** [comment]
Shouldn't it be other way around? Assembly should accept only Parts (App:Part), but inside part there could be anything? Part design bodies; Part solids, surfaces; some imported mesh from 3d scaned object; even single Draft wire as placeholder (example - some linking rod in mechanism) etc.

Ability to asemble anything with anything (Bodies with Parts and so on) leads to chaos and creating BOM seems imposible. BOM shouldn't be simple list of assembled... "things" but there are also important properties to be extracted. In that case there should be single type of object to be assembled, so every asembled object has the same properties.

**Comment by macdroid53** [comment]
@mno13 
I disagree. I shouldn't need a Part (Std_Part) to add nuts, bolts, etc. to an assembly. What you describe, I think is more of a sub-assembly. A solid created in the Part workbench is a valid line item in a BOM. A nut created with Fasteners workbench is a line item (there may be ten of the same nut and that should end up as a count on the line item). A gear made with the Gear workbench is also a valid line item. etc. Properties to be extracted are a property of the object, so there shouldn't be any confusion.

**Comment by mno13** [comment]
Fasteners are IMO great example of using Part properties. In this case, there should be standard property called something like "source" with value like "Purchased" or "Standard" ("Standard" as in "according to ISO/DIN... Standard").  

Ultimately, there should be option for predefined property values using templates. In this example - "source" could be "Purchased" or "Manufactured" , or for other user "Purchased COTS", "Standard", "Machined", '3D Printed" etc. Depends on user workflow, but basically is range constant for given workflow.

Moving to production documentation logic and keeping things simple:
- assembly -> assembly drawing & BOM made from parts and subassemblies*
- part -> manufacturing drawing  of (to be) physical object
- bodies, solids and surfaces - are just abstract things in model, they are not "parts". They are not manufacturable 
- sub-assembly is still an assembly, but when inserted into assembly could act as single part (or be fully transparent in other cases)

I don't fully get your idea about sub-assembly. Could you explain what you have on your mind?

**Comment by macdroid53** [comment]
The original intent of the the Part (Std_Part) container is just that a container. It is a container that happens to have an Origin object and anything put in it references that Origin object. And, it _can_ contain a Part WB solid, a PD Body, etc. If the Part (Std_Part) is moved it's contents move with reference to the Origin object. The Part (Std_Part) has been a pseudo viewed as a sub-assembly or even top assembly since it was introduced.

**Comment by mno13** [comment]
Part it's a perfect container that can contain anything. But on "real" assembly level IMO we should assemble more "physical" things. And from end user point of view that sould be as simple as  "we can assemble only parts, everything that is going to be assembled should go inside part".

There  is an instance where line between part and sub-assembly is blurred - inseparable assembly. 
- assembled purchased parts, like gearmotors or electronic components - work best as multibody part, so Part is used as  "pseudo-assembly".
- welded components - simpler things are achievable as multibody parts, but more advanced frames should be made as assembly.  It's non trivial topic, because welded structure could be an assembly  with additional features. It requires BOM,  but also often assembly-level features for finishing operations.

One sidenote about fasteners etc. On one hand that would mean a need to modify current workbench to add fasteners inside new Part. But on other hand,  the long term solution should be more universal, and standard part catalog shoud have ability to store any custom parametric part.

**Comment by macdroid53** [comment]
I disagree. There is no particular need for a container. IMO, it is just adding a wrapper to something that can stand alone. Especially for fasteners.
Also, if it is indeed a wrapper for a sub-assembly, then it should definitely NOT be called a Part. There is far too much confusion in FC about the term "part" already.

**Comment by mno13** [comment]
I forgot about "Part" naming confusion in FC. Using name "Part" for this container is unfortunate in this context, using something other, for example: "component" would maybe be more appropriate.

But my main remark still stands. There should be universal wrapper so Assembly structure is straightforward. Even more - there IS a universal wrapper (std:part) so why we won't use it?

Situation, where user can assemble anything with anything is unmanagable in long term (maybe with good PDM, but PDM can be pain itself). I'm thinking about large projects with multiple designers.

It's an industry standard. Assembling only subassemblies and parts. Why reinventing wheel?

Assembly shouldn't be only about "putting things together". It's also about manageability of design. 

Side note: in Catia, there is only posiblity to assemble (sub)assemblies, because part is a special case of assembly file cointaing single part. I din't wanted to bring any specific CAD as example before, but it's one of few examples where things are done a bit diferently than in mainstream CAD aplications, at least from user POV.

**Comment by macdroid53** [comment]
I just don't see the issue. I should be able to put 10 fasteners, 10 gears, etc. into an assembly without having to add each to a container. It can contain properties that define it's details like name, source, material, etc.

**Comment by macdroid53** [comment]
I just don't see the issue. A general purpose, extensible, BOM object is defined. Anything that gets added to an assembly gets a BOM object activated/added. The user needs to do nothing unless they want to add BOM details to the item being added to the assembly.

**Comment by mno13** [comment]
Why anyone would want to define additional "BOM object" ? And why create new object type when anything placed in assembly should be "BOM-able" by default?  When "part" (Std:part) will have all the properties needed for BOM ? 

On BOM activation topic - it should be a mere "Part" property - "exclude from BOM"

**Comment by macdroid53** [comment]
Add it to a Std_Part or add it to any other object. A developer creates it once. The data about the component has to be entered at some point.
Why can't a Part workbench Extrusion have a BOM info object? That should be a mere property. Why must it have a Std_Part wrapper, to include BOM info?
If the Std_Part has a BOM object, why can't anything else?

**Comment by mno13** [comment]
BOM info should be extracted directly from Part (stdpart) properties. That's all.

But is there even a real world use case for your example? Extrusion object as "item"? Extrusion is not an item, it's just a mere model feature (yes, i know - a part, not part_design feature, but still). It leads to bom like this:

No | Name                        | Material |  [ ...]  | Qty 
1    | Welded bracket         |  S235JR  |  [ ...]  | 2
2    | ISO 4762 - M6 x 20   |  A2-70   |  [ ...]  | 10
3    | Hole 5                        |  ???       | [...]  | 2

See a problem? Not everything is BOM-able and list of things that could be assembled should be restrited to some common object type.

What about imported STL for mockup? Proper way is to put this into container with "real" LCS and not to try use just Mesh object in assembly.

@PaddleStroke  should this be discussed in larger group? Maybe on FC forum? I think  question "what could be assembled" is quite important one.

**Comment by macdroid53** [comment]
I would agree that this should be discussed by a larger audience.
What I hear you saying is if I make ten different  components in Part Design, each with a single revolve feature, and add them to an assembly they each can have a BOM object.
But, if I make the same 10 components, each with a single Part workbench revolve, they can't have a BOM object.
But, a component made with Fastener or Gear workbench can have a BOM object.
I'm not suggesting a hole, which is not a solid, be given a BOM object. And, no one would add a hole to an assembly.
Look at the very last image in the example at the end of this link. The Body in the left image can be added to an assembly. If I've designed Cut001 on the right, why should I be precluded from having BOM information and use in an assembly?
[https://wiki.freecad.org/Part_and_PartDesign](url)

**Comment by mno13** [comment]
Example with hole was exargated to the extreme, to show where it's going when we're able to assemble anything with anything.

I'm against assembling bodies. In given example neither element (Body vs Boolean result) should be element of assembly.

Catia structure example:

https://4.bp.blogspot.com/-GjXVAqZWuIs/WJyyj-924kI/AAAAAAAARqk/V-XBsXq7EjYgxI81y2KmW2BlAgEgJbCXACLcB/s1600/Fig.2.png

Solid Edge structure example:

https://community.sw.siemens.com/sfc/servlet.shepherd/version/renditionDownload?rendition=THUMB720BY480&versionId=0684O00000E1OZS&operationContext=CHATTER&contentId=05T4O00000wpDmH

Inventor, Solidworks etc works in similar manner. STEP file structure is similar.

There is always some common container where all the modelling takes place, and just after that these 'containers' are assembled (assembly features aside)

**Comment by macdroid53** [comment]
So, you don't want the integrated assembly bench to work as it apparently does?
![Screenshot_20231117_134936](https://github.com/FreeCAD/FreeCAD/assets/6831752/305f0b69-9eb5-4566-9f73-0c7bb9602913)
Am I using it wrong?

**Comment by mno13** [comment]
Not really. Here is an example of assembly structure that is mostly on par with other systems:

![obraz](https://github.com/FreeCAD/FreeCAD/assets/150608426/d64572a8-3234-42bf-b1a5-f0f4d622670b)


Making this example I found out that there is currently no posibility to put assembly into assembly :/. Also instance naming is not great.

**Comment by PaddleStroke** [comment]
- As there are no technical limitations to prevent the user to use solids directly I am not enthust to add a limitation to force the user to use Parts containers. I understand both positions, but one is asking to limit capabilities that are not hurting. Say if you want to include all your solids in parts you can.
I guess it is possible to add a preference like 'Allow only Parts in assembly' that would prevent user from using solids directly. Or alternatively that would create Parts containers automatically when the user insert solids.

- Nested assemblies need a bit more work.

**Comment by mno13** [comment]
@PaddleStroke 

At least preference for allowing only parts in assembly would be nice to have. Work on larger projects with multiple designers require a way to enforce way of building assembly on whole team.

 Automatic creation of Part container during solid creation is de-facto a standard way of working for most of the CAD systems on the market. Part containers are separate files, but still - each assembled component is inside some kind of container (mostly shown to user as separate file).

@macdroid53 

Adding BOM property vs "Universal Part container" -  I think main flaw with BOM property is in object hierarchy. Container > Property. Assembly is build from "parts" not from "everything but only when this thing have this special property".

What about compatibility with STEP and basically all other CAD systems? Export to STEP will convert everything to "parts", import from STEP should create part container for every separate solid.

We can enforce "industry standard" hierarchy and make it transparent for user, or do it behind closed doors on import/export.

And without at least good STEP (and DXF, but it is out of scope of assembly) support, every CAD is useless for any professional use.

Some links on assembly structure handling:

https://analysissitus.org/features/features_asm-code-architecture.html

https://analysissitus.org/features/features_asm-xde-document.html

I would suggest also to look into STEP / JT / 3D XML documentation, how its done elsewhere. Scripting tutorials from other CAD packages also could work as benchmark how things are handled.

**Comment by macdroid53** [comment]
As noted, there are no technical limitations that would require this limitation. How a company chooses to architect their BOM system is up to them. The tool should provide for the possible desires of the company.

IMO, what you propose, is to arbitrarily impose limits.  Building a solid that represents a line item in a BOM should not be limited to a Part Design Body.
