### ISSUE TITLE
[Problem] Solver CalculiX (new framework) seems to be unnecessary

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#10823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Apart from the default _Solver CalculiX Standard_, there's also _Solver CalculiX (new framework)_ available. However, it seems to be rather useless and the documentation even suggests using the default solver:

_The Solver CalculiX (new framework) command creates a SolverCalculix object, which uses the same framework as Elmer and Z88 solvers (the code is not visible for the user). It is preferred to use the original framework Solver CalculiX Standard because it contains extra checks, e.g. showing the elements with nonpositive Jacobian which might cause solution difficulties._

I don't see any use cases for that "new framework" so it might be better to remove it or at least hide it from GUI.

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34387 (Git)
Build type: Release
Branch: master
Hash: d95b26dfb5dd23eaee004b4af3cf5cf4766e7f9c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
It looks like the "new framework" is the result of some refactoring work but isn't a different solver integration. It's probably not finished and for the time being the command shouldn't be added to the menu.
