### ISSUE TITLE
[Problem] FEM Solver job control and Run solver calculations icons are unintuitive

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#10824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Current icons for "Solver job control" and "Run solver calculations" are IMO highly unintuitive:

![icons](https://github.com/FreeCAD/FreeCAD/assets/59876896/d2a8070b-f849-42ee-83e6-8d41da36b376)

I would suggest something simple and actually symbolizing solver controls/analysis submission. Maybe just a play arrow symbol for "Run solver calculations" and the same symbol but with a small gear icon for "Solver job control".

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34387 (Git)
Build type: Release
Branch: master
Hash: d95b26dfb5dd23eaee004b4af3cf5cf4766e7f9c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@FEA-eng Can you please post a request in the UI/UX subforum and link to this ticket (+  vice-versa)

**Comment by FEA-eng** [comment]
> @FEA-eng Can you please post a request in the UI/UX subforum and link to this ticket (+ vice-versa)

Done: https://forum.freecad.org/viewtopic.php?t=81586
