### ISSUE TITLE
[Problem] FreeCAD crash when clicking on invalid fillet edge in side panel

### ISSUE THREAD

**Issue by Anthony-Gaudino** [FreeCAD/FreeCAD#10843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a part which contains a fillet that results in an invalid shape. This happened from refactoring features.
If I double click on the fillet, and right click or left click on the edge that is listed in the selected list FreeCAD crashes.
<img width="549" alt="Screenshot 2023-09-27 at 12 31 12" src="https://github.com/FreeCAD/FreeCAD/assets/2439728/8fbdb97b-db88-48a2-8dfa-9547a81cdc48">

File: [crash.zip](https://github.com/FreeCAD/FreeCAD/files/12738070/crash.zip)

### Full version info

```shell
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38079 (Git)
Build type: Release
Branch: main
Hash: de508e437d13e7eb35baffceea496fb9107888cb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * Launcher
  * Nodes 0.1.36
  * InventorLoader 1.4.0
  * Assembly4.backup1719958896.85335 0.50.12 (Disabled)
  * Render.backup1719959316.120863 2024.6.5 (Disabled)
  * woodworking 0.21.2.33771
  * ThreadProfile.backup1719959316.6397839 1.90.0 (Disabled)
  * MeshRemodel.backup1719959315.871541 1.9.23 (Disabled)
  * Silk 0.1.5
  * Defeaturing 1.2.2
  * Pyramids-and-Polyhedrons
  * Curves.backup1719958901.528519 0.6.36 (Disabled)
  * fasteners.backup1719958901.808955 0.5.20 (Disabled)
  * nurbs
  * sheetmetal.backup1719959316.3711638 0.4.21 (Disabled)
  * A2plus.backup1719958896.309429 0.4.64a (Disabled)
  * Manipulator 1.5.7
  * lattice2 1.0.0
  * CurvedShapes 1.0.9
  * toSketch 1.0.1
  * Curves 0.6.40
  * Assembly4 0.50.15
  * Assembly3 0.12.2
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
I cannot reproduce it on Linux and Windows. FreeCAD writes, instead of crashing:

```java
13:09:40  Unhandled unknown exception caught in GUIApplication::notify.
13:09:40  Unhandled unknown exception caught in GUIApplication::notify.
13:10:07  top_block_front_fillet: Failed to create fillet
```



```ruby
OS: Ubuntu 22.04.3 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34438 (Git)
Build type: Debug
Branch: master
Hash: 247df9939108ebe6cf398868e59f49d965c3e381
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: Russian/Russia (ru_RU)
```


----


On Windows:

```java
13:11:48  Unhandled unknown exception caught in GUIApplication::notify.
13:11:48  Unhandled unknown exception caught in GUIApplication::notify.
13:11:55  Recompute failed!
```


```ruby
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Russian/Russia (ru_RU)
```

**Comment by Anthony-Gaudino** [comment]
Updated Full version info as it still happens on 0.22.0dev.

**Comment by maxwxyz** [comment]
No crash but warning on Windows with the stable version:
![grafik](https://github.com/user-attachments/assets/1ff61c09-233b-4cb2-88b0-e2437b2f9344)
```
[code]
OS: Windows 11 build 26100
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.27.10
  * Curves 0.6.48
  * dodo 1.0.1
  * fasteners 0.5.29
  * fasteners.backup1721936159.7542229 0.5.24 (Disabled)
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.24
  * Rocket 3.3.0
  * sheetmetal 0.4.26
  * Silk 0.1.5
  * Silk.backup1727166062.7227929 0.1.5 (Disabled)
[/code]

Same on latest dev:
![grafik](https://github.com/user-attachments/assets/c7fde442-f5a6-426b-946b-87c74de151a9)

```
OS: Windows 11 build 26100
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CfdOF 1.27.10
  * Curves 0.6.48
  * dodo 1.0.1
  * fasteners 0.5.29
  * fasteners.backup1721936159.7542229 0.5.24 (Disabled)
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.24
  * Rocket 3.3.0
  * sheetmetal 0.4.26
  * Silk 0.1.5
  * Silk.backup1727166062.7227929 0.1.5 (Disabled)

```
```

**Comment by wwmayer** [comment]
In the meantime we know that if an event handler or a slot function doesn't handle exceptions they go through Qt code. On macOS this usually leads to a crash while on Windows or Linux only a warning is printed.
