### ISSUE TITLE
[Problem] Preferences dialog is space-inefficient and inflexible

### ISSUE THREAD

**Issue by kadet1090** [FreeCAD/FreeCAD#10886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Navigation in the Preferences dialog is currently done via ListBox with huge icons which takes a lot of space making it hard to navigate around. Users also have to navigate using two styles of navigation - first user needs to pick category from the listbox on the left, and then pick proper tab from the main content window. It is space inefficient and creates a lot of unnecessary scrollable areas and truncated text.

![image](https://github.com/FreeCAD/FreeCAD/assets/747404/a51c59f1-8a87-40a9-bad3-f3b273745448)

Many programs nowadays solve this problem using tree structure for selecting preferences page, this is done mainly for programs with lot of configuration pages. A good example from IntelliJ:

![image](https://github.com/FreeCAD/FreeCAD/assets/747404/deb06aae-762c-44c1-91f8-3843f9a65c75)

### Full version info

```shell
0.22 dev
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kadet1090** [comment]
I've created prototype on Figma with how this could work in FreeCAD: [https://www.figma.com/community/file/12 ... 1131468166](https://www.figma.com/community/file/1289973521131468166)

<img src="https://github.com/FreeCAD/FreeCAD/assets/747404/4acb9d0d-3f3c-4cab-8f3b-88647a560a77" width="500"/>

**Comment by maxwxyz** [comment]
@kadet1090 could I close this issue with your implementation?

**Comment by maxwxyz** [comment]
I'll close this as your PR was merged.
