### ISSUE TITLE
[Problem] Materials FEM workbench migration

### ISSUE THREAD

**Issue by davesrocketshop** [FreeCAD/FreeCAD#10907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Update the FEM workbench to use the new materials system

### Full version info

```shell
Any
```

### Subproject(s) affected?

None

### Anything else?

Part of https://github.com/FreeCAD/FreeCAD/issues/10174
Forum thread https://forum.freecad.org/viewtopic.php?t=81668

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@davesrocketshop could this issue be closed?

**Comment by davesrocketshop** [comment]
Yes. There's still work to be done but nothing before 1.0. Closing
