### ISSUE TITLE
[Problem] Appearence materials

### ISSUE THREAD

**Issue by davesrocketshop** [FreeCAD/FreeCAD#10904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Integrate appearance with the updated materials system

- update Part:Material property
 - Use new material cards for appearance property descriptions
 - Remove hard coded appearance values
- add texture/image support. Currently this can be done from "View"->"Texture Mapping..." but the feature doesn't work correctly and is not integrated

### Full version info

```shell
Any
```

### Subproject(s) affected?

None

### Anything else?

Part of https://github.com/FreeCAD/FreeCAD/issues/10174

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
> * add texture/image support. Currently this can be done from "View"->"Texture Mapping..." but the feature doesn't work correctly and is not integrated

That would be awesome. Proper support for textures is much needed in FreeCAD. Hopefully, more advanced rendering will let us make full use of the appearance properties in the future.

Do you plan to add default appearances reflecting the type of material like in commercial CAD software ?

![appearances](https://github.com/FreeCAD/FreeCAD/assets/59876896/8e726518-79e4-434e-adc0-4e8bb2cc5ae7)

![appearances 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/b8129622-f431-4bb9-a4e3-36b03e6c8764)

**Comment by davesrocketshop** [comment]
That would be the goal. I'll need a lot of help to get there though

**Comment by luzpaz** [comment]
Maybe ropping in @howetuft from Render WB in on this discussion ?

**Comment by howetuft** [comment]
Thank you @luzpaz . Indeed, I've already implemented shader management, including textures, for Render WB and I've based it on FC materials. It would be convenient to converge, IMHO.

Please note also that one shouldn't implement textures standalone as, in physical based rendering (PBR), textures do not exist without shaders. Also note that efficient texture implementation for PBR should allow to apply several textures to the same shader, to its various channels (color, metal, normal, ambient occlusion... see for instance https://www.cgbookcase.com/).

**Comment by maxwxyz** [comment]
please consider https://github.com/FreeCAD/FreeCAD/issues/11113
All glossy reflecting materials currently appear white when you view the face from their normal direction. This is annoying especially in sketches when you cannot differentiate different colors or materials as all appear white. Maybe the default light position/direction can be changed or even be set in the preferences

**Comment by maxwxyz** [comment]
@davesrocketshop could this issue be closed?

**Comment by davesrocketshop** [comment]
Yes. Closing
