### ISSUE TITLE
[Problem] Authoring and Licence, Empty Licence URL breaks

### ISSUE THREAD

**Issue by kroko** [FreeCAD/FreeCAD#10910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If _Default license_ is set to `Other` and  _License URL_ is left empty, it is impossible

to create new document, throws

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'Base.FreeCADError'>: array::at
```

or open existing one, throws

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: Invalid project file /Users/path/to/doc.FCStd: array::at
```

Expected - Probably should ignore empty field.

<img width="659" alt="Screenshot 2023-10-02 at 23 01 32" src="https://github.com/FreeCAD/FreeCAD/assets/720976/4780a350-9481-4c3f-851c-a4cc04ab6ea8">

### Full version info

```shell
OS: macOS 13.6
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Confirmed.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34387 (Git)
Build type: Release
Branch: master
Hash: d95b26dfb5dd23eaee004b4af3cf5cf4766e7f9c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

**Comment by pitch-circle** [comment]
Mentioned on the forum here:

https://forum.freecad.org/viewtopic.php?p=703544
