### ISSUE TITLE
[Problem] TechDraw WeldSymbol icon is unintuitive

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#10916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The current TechDraw WeldSymbol icon represents a welding helmet but it's rather confusing for new users. There was a discussion about changing it to something more intuitive some time ago and @WandererFan agreed to change the icon but the OP didn't provide a proper svg file. I'd like to bring this topic back. I think that the icon should be similar to what the OP suggested but without the small details. So either a fillet weld symbol similar to this:

![weld 1](https://github.com/FreeCAD/FreeCAD/assets/59876896/3da56bfb-2e2c-4914-b20d-3d0105b9bc8a)

or a weld annotation symbol like this:

![weld 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/26a64af1-acbc-4507-9ec3-a6e43c3cda1d)

Not both at the same time to avoid small details.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34506 (Git)
Build type: Release
Branch: master
Hash: 3ce68745dc3aa3b02de0df2d5e4409bf3e286c49
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Because of this, I wanted to check the FreeCAD icon palette mentioned in the wiki but there seems to be an issue with access: https://forum.freecad.org/viewtopic.php?t=81649

**Comment by WandererFan** [comment]
I can't fix the permissions, but I have a copy.  Remove the junk at the end of the file name.

[FreeCAD-Tango.gpl.not.txt](https://github.com/FreeCAD/FreeCAD/files/12792502/FreeCAD-Tango.gpl.not.txt)

**Comment by WandererFan** [comment]
Found this in my files, too.

![TechDraw_WeldSymbol](https://github.com/FreeCAD/FreeCAD/assets/3587161/dc840a95-a41a-4b2e-b267-cd0a30fc0934)

**Comment by FEA-eng** [comment]
@WandererFan I'm definitely not an artist so I just modified the icon for the surface finish symbols tool:

![TechDraw_WeldSymbols](https://github.com/FreeCAD/FreeCAD/assets/59876896/cf1a42b6-8e81-444c-82f5-62ad3990897c)

Is it ok ? It should fulfill the requirements since it's based on an existing icon.

**Comment by WandererFan** [comment]
This is what it looks like in a toolbar at large (32px) and medium (24px) sizes.  Not sure I'd recognize what it is at the smaller size, but I don't make drawings for welders.

![WeldIcon_32px](https://github.com/FreeCAD/FreeCAD/assets/3587161/d77c655d-a859-438d-a035-8b47d434df32)
![WeldIcon_24px](https://github.com/FreeCAD/FreeCAD/assets/3587161/9353087f-b4fe-4d2b-8178-8eb26953ee2b)

**Comment by WandererFan** [comment]
I'm no artist either as you can see: 

![TechDraw_WeldSymbol_candidate](https://github.com/FreeCAD/FreeCAD/assets/3587161/56b99030-c251-49e8-b493-6a9883396bff)

**Comment by FEA-eng** [comment]
> This is what it looks like in a toolbar at large (32px) and medium (24px) sizes. Not sure I'd recognize what it is at the smaller size, but I don't make drawings for welders.

It should look better with smaller sizes now:

![weld_icon_1](https://github.com/FreeCAD/FreeCAD/assets/59876896/54cc47ea-334e-43c7-b27d-966f9462cdc1)

I think that it's pretty recognizable for those who need it (and thus easily recognize the typical weld annotation symbol) but here's an alternative:

![weld_icon_2](https://github.com/FreeCAD/FreeCAD/assets/59876896/4e69fe7e-fe58-448e-8f61-665572181e88)

I think that it should show a simplified representation and hence the triangle (your icon is nice but the arc can be confusing since it's not a typical symbol of a fillet weld)

Still, I prefer the first variant. It's similar to surface finish symbol and thus easier to find (after all, those annotations are quite similar in drawings).

**Comment by WandererFan** [comment]
Here is your latest in a toolbar at medium:
![WeldSymbol_v02_24px](https://github.com/FreeCAD/FreeCAD/assets/3587161/62bf4bc1-9fc0-4bb0-b52e-e828fac9bb62)

AFAIK, the fillet symbol is supposed to be hollow.  This is yours with hollow fillet and with margins and lines thicknesses adjusted.  I like it better, but I'm not passionate about it.  
![WeldSymbol_v03_24px](https://github.com/FreeCAD/FreeCAD/assets/3587161/97087e5a-1f60-44df-9d8c-20b9ee0749b6)

I'll update with whichever one you prefer.

**Comment by FEA-eng** [comment]
Strange, the arrow disappears for some reason. Do you know what can be the cause ? It was created as a type of line end marker in Inkscape.

Can you try this one ? I drew the arrow manually here.

![weld_icon_mod](https://github.com/FreeCAD/FreeCAD/assets/59876896/efc3511b-41d8-4094-a46d-041153ab9257)


> AFAIK, the fillet symbol is supposed to be hollow.

I know but I just thought that it looked better as filled ;-) However, I will keep it hollow now.

**Comment by WandererFan** [comment]
![TechDraw_WeldSymbol_candidate3_24px](https://github.com/FreeCAD/FreeCAD/assets/3587161/9cb5b597-2faf-4c7c-a55f-53535e3d19a5)

I'm going to go with this one.

**Comment by WandererFan** [comment]
Completed by PR #10936

**Comment by luzpaz** [comment]
Anyone volunteering to update the docs ?

**Comment by FEA-eng** [comment]
> Anyone volunteering to update the docs ?

Wiki is already updated: https://wiki.freecad.org/File:TechDraw_WeldSymbol.svg
