### ISSUE TITLE
[Problem] STL-exported object looks differently from displayed on screen

### ISSUE THREAD

**Issue by Fedr** [FreeCAD/FreeCAD#10948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Open this STEP file in FreeCAD:  [eMG-100-G60.zip](https://github.com/FreeCAD/FreeCAD/files/12830360/eMG-100-G60.zip)
2. It is displayed more or less correctly:
![image](https://github.com/FreeCAD/FreeCAD/assets/3136125/3ec07628-78a4-4370-a866-f6e959c3954b)
3. Export it to STL file
4. Open STL file
Observe unexpected loss of data in one place:
![image](https://github.com/FreeCAD/FreeCAD/assets/3136125/14e36278-d18c-46a4-a7db-d39f675e833b)

Could you please explain how to export the same triangles as shown on step 2., or how to export with no such big losses?

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Please start a topic in the [FreeCAD forum](https://forum.freecad.org).

Closing this.
