### ISSUE TITLE
[Problem] FreeCAD does not compile as C++20 (invalid template arguments on constructor declaration)

### ISSUE THREAD

**Issue by mwoehlke** [FreeCAD/FreeCAD#10952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FreeCAD does not compile:
```
In file included from freecad/src/CXX/Objects.hxx:42,
                 from freecad/src/Base/PyObjectBase.h:56,
                 from freecad/src/Base/BaseClass.cpp:31:
freecad/src/CXX/Python3/Objects.hxx:1336:21: error: expected unqualified-id before ‘const’
 1336 |         SeqBase<T>( const Object &ob )
      |                     ^~~~~
```

Although the constructor declarator `class_name<T>(...)` is accepted by many compilers, it is not valid C++. It's unclear whether it was *ever* valid C++ (or intended to be valid, at least), but it is explicitly invalid in C++20. GCC ≥ 11 in `-std=c++20` mode or later rejects it (albeit with a rather confusing error message, as above).

See also [CWG Issue 2237](https://cplusplus.github.io/CWG/issues/2237.html).

### Full version info

```shell
master circa 2023-10-04
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mwoehlke** [comment]
I'll try to provide a PR for this in the next few days (it's a relatively easy fix, although a number of places in that file are affected), however, it's unclear if this file is hand-written or generated. If it's generated, I don't know where the code generation happens. (I'll also try to remember to update the issue description with the affected SHAs; my checkout is on a different computer...)

**Comment by wwmayer** [comment]
> it's unclear if this file is hand-written or generated

It's hand-written. It's part of the PyCXX project which is hosted on Sourceforge: sourceforge.net/projects/CXX

**Comment by wwmayer** [comment]
In upstream it's already fixed: https://sourceforge.net/p/cxx/code/449/tree//trunk/CXX/CXX/Python3/Objects.hxx?diff=517694e95fcbc9797b11d5c7:448

**Comment by mwoehlke** [comment]
Slightly better link: https://sourceforge.net/p/cxx/code/449/

...and, yup, that looks like exactly the changes I made. Is it useful if I submit that as an independent PR, or do you have a better handle than I do how to go about updating that particular code?

**Comment by wwmayer** [comment]
If you have it ready you can make a PR. Otherwise I will do it in the next couple of days.
