### ISSUE TITLE
[Overlay] 'Auto Mouse Wheel pass through' doesn't work on techdraw

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#11015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

On windows.

'Auto Mouse Wheel pass through' doesn't work.

The mouse clicks are passing through, but the wheel event doesn't seem to pass through.

@realthunder 

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34642 +15 (Git)
Build type: Release
Branch: asm_card9
Hash: 9cf8885ec1ab18b8d7fdc838ac0b8180ebb7bb21
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk , OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.60k
  * Assembly3 0.12.0
  * Assembly4 0.50.2
  * Curves 0.6.8
  * ExtremeProLight 1.5.0
  * FreeCAD - Shortcut.lnk
  * FreeCAD_FastenersWB-master 0.4.56
  * Ondsel 2023.8.23.02
  * OpenDark 2023.10.6
  * ProDarkThemePreferencePack 1.0.0
  * sheetmetal 0.2.63
[/code]
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kadet1090** [comment]
I could try to fix that and refactor this part of code as it was mentioned in the CR if I remember correctly.

**Comment by adrianinsaval** [comment]
I can confirm this too. I tried playing around with the delay value for mouse wheel pass through but didn't find anything that worked

**Comment by realthunder** [comment]
Probably broken by [this](https://github.com/realthunder/FreeCAD/commit/bdf7af1380c932371f4d01dab243c832dd2c68ec). My Windows build machine is broken at the moment. Please revert this commit, and give it a try.

**Comment by kadet1090** [comment]
Yup, it indeed fixes the mentioned issue. I reverted only part of this commit as it was enough to fix the issue, I don't want to break other stuff by accident and change that I reverted is isolated to wheel events.

**Comment by adrianinsaval** [comment]
The issue has been mostly solved but there is a remaining problem with techdraw

**Comment by WandererFan** [comment]
a) what is [Overlay]?
b) TD processes wheel events in the NavStyle implementation.  Maybe TD is eating an event before Overlay gets it?

**Comment by WandererFan** [comment]
void QGVPage::wheelEvent(QWheelEvent* event)
{
    m_navStyle->handleWheelEvent(event);
    event->accept();  // <<<< if somebody else needs this event, they will not get it.
}

**Comment by adrianinsaval** [comment]
> a) what is [Overlay]? 

see https://github.com/FreeCAD/FreeCAD/pull/7888

**Comment by kadet1090** [comment]
> void QGVPage::wheelEvent(QWheelEvent* event) { m_navStyle->handleWheelEvent(event); event->accept(); // <<<< if somebody else needs this event, they will not get it. }

Hmm, I placed debug log on this line and it never got executed, it does not even go into it. The address of `QGVPage` is also correct (logged from `wheelEvent` that is handled correctly and before `sendEvent`). For some reason, the widget is not processing event sent by the 
```
        QApplication::sendEvent(lastIntercept, &wheelEvent);
```

What is interesting is that if we target specifically `scrollArea->viewport()` it works fine for TechDraw and breaks for the 3D View.

#11077 targets the 3D view specifically and fixes the issue, but I don't feel that this is good solution, feels hacky to me.
