### ISSUE TITLE
[Overlay] Overlay stylesheet should be set by preference pack/theme.

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD#11023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am not sure if it is broken or it is not implemented, but I cannot set the overlay stylesheet with the preference packs.
Which would be recommended as the preference pack sets the background color and some Qsint colors have overlap. 
Tried adding: 
`        <FCParamGroup Name="MainWindow">
          <FCText Name="OverlayStyleSheet">Dark.qss</FCText>
        </FCParamGroup>`

### Full version info

```shell
Latest dev
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by obelisk79** [comment]
from my user config file it looks like the user.cfg line we need to add looks more like this compared to what you have above: <FCText Name="OverlayActiveStyleSheet">OpenDark_Overlay.qss</FCText>

however, I cannot get my overlay stylesheet to even register in freecad at all. I've tried a few different approaches in my package.xml to register the file but none seem to work.

**Comment by obelisk79** [comment]
@chennes is something that would fall under your purview?

**Comment by chennes** [comment]
Yes. The way it is *supposed* to work as that any QSS file in your mod's directory is found (you don't need to set anything in package.xml). It sounds like that isn't working, so I will have to look into it.
