### ISSUE TITLE
[Problem] The G-code post-processor seems to be broken.

### ISSUE THREAD

**Issue by ORCA316957** [FreeCAD/FreeCAD#11022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The G-code post-processor seems to be broken.

### Full version info

```shell
The G-code post-processor seems to be broken.
```

### Subproject(s) affected?

PartDesign

### Anything else?

![image](https://github.com/FreeCAD/FreeCAD/assets/147809134/c17e13a5-6308-4752-bf1b-7585059a445c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This issue lacks just about everything to make it in any way actionable.

Before creating a next GitHub issue please consider consulting the [FreeCAD forum](https://forum.freecad.org/) first.

Closing this.
