### ISSUE TITLE
[Problem] `During initialization the error "No module named 'Assembly_rc'" occurred...`

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#11034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Upon running FreeCAD, report view shows 

```shell
During initialization the error "No module named 'Assembly_rc'" occurred in /tmp/.mount_FreeCACDuV2e/usr/Mod/Assembly/InitGui.py
Please look into the log file for further information
```

This has been reported in the forum but has stagnated, see thread: https://forum.freecad.org/viewtopic.php?t=80902

Per @chennes in the forum thread:
> we're probably missing an installation step for that RC file, I'll give the cMake setup a look.

I think it may be from this import statement:  
https://github.com/FreeCAD/FreeCAD/blob/74c236f9477430af411c067c1ec0ef7dfd3f3545/src/Mod/Assembly/InitGui.py#L24

Here is the Assmebly subdirectory cmake file:

https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Assembly/CMakeLists.txt

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34651 (Git) AppImage
Build type: Release
Branch: main
Hash: aa5bea4e2e8089bf00f61075a0860dacda42dc8b
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Freecad-Built-in-themes-beta 1.2.2
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

Currently I have no access to the forum so can someone x-post this ticket to said forum thread? TIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/11041
