### ISSUE TITLE
[Problem] Background color on formula editor options is not readable

### ISSUE THREAD

**Issue by sdifru** [FreeCAD/FreeCAD#11098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The background color on formula editor options is not readable. I can't see the options. On the **preference packs** I choose light theme and on the **style sheet** I use light-blue.

![2023-10-19_08-10-1697678921](https://github.com/FreeCAD/FreeCAD/assets/123437835/f49a6bd6-9282-4f77-b611-fc436dfa3541)

### Full version info

```shell
[code]
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: makepkg
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.11.5, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FreeCAD_assembly3 0.12.0
  * FreeCAD_FastenersWB 0.4.66
  * FreeCAD_SheetMetal 0.3.1
  * Lattice2 1.0.0
  * freecad.gears 1.0.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
Did you do a reboot?
Some colors need a reboot?

**Comment by sdifru** [comment]
> Did you do a reboot?

Yes.

I've change it and used Classic theme with light-blue. The black background color still exists. The previous freecad version doesn't have this.

I use sway compositor, not KDE or GNOME if it helps.

**Comment by MisterMakerNL** [comment]
Hmm normally on linux this would happen if the background color isn't set, but on windows this has an gray background.
Which means it is set.
I also tested it with Fusion style which is often used in Linux. And I had the same results.
Could you run this macro and post the output from console?
```
class Qtprintstyles:
    from PySide import QtWidgets
    print(QtWidgets.QStyleFactory.keys())

```
This is how light looks on windows:
![image](https://github.com/FreeCAD/FreeCAD/assets/29804962/db13758c-a726-4d44-8505-8ecdcdc01bd6)

**Comment by sdifru** [comment]
I use the beta stylesheets you mentioned https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta and it works! Thanks mate @MisterMakerNL!
