### ISSUE TITLE
[Problem] The end mill doesn't cut the stock/workpiece in CAM simulator (path workbench)

### ISSUE THREAD

**Issue by sdifru** [FreeCAD/FreeCAD#11106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I was working with path workbench. I ran CAM simulator. It was working fine. After modifying the operation and running CAM simulator again, the endmill moved like it is intended to but it didn't cut the stock.

![2023-10-20_05-10-1697754348](https://github.com/FreeCAD/FreeCAD/assets/123437835/3d045a4a-8045-4465-9313-f20a9b95baac)

### Full version info

```shell
[code]
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: makepkg
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.11.5, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FreeCAD_assembly3 0.12.0
  * FreeCAD_FastenersWB 0.4.66
  * FreeCAD_SheetMetal 0.3.1
  * Lattice2 1.0.0
  * freecad.gears 1.0.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
We're migrating away from an in-house simulator to routing through a 3rd party FLOSS called [camotics](https://github.com/CauldronDevelopmentLLC/CAMotics/issues/404). See https://forum.freecad.org/viewtopic.php?p=547266

This is a "won't fix" ticket due to that reason.
