### ISSUE TITLE
[Problem] Adjust Default Main Light Position

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Either let the user adjust the global position of the main light / illumination of the environment or adjust the default position so that is not directly coming from the direction of the viewing plane / angle.

I use a lot of material and color variations for different bodies and faces and when they are glossy and face directly the view, they all appear white (reflection of the environment lightning). It would be beneficial to rotate the global light source to an angle that when drawing on standard planes, it is possible to distinguish different parts and faces.

When looking at the object you cannot see which faces or edges are selected or hovered/highlighted - simply everything appears white.
Especially when doing sketches I cannot differentiate between different color faces because of this behavior, all just appear white.

As Syres mentioned, it is currently only possible to adjust the position with Python but that has to be done at every restart, here is the code from @wwmayer: https://forum.freecad.org/viewtopic.php?p=146925#p146925

Simple demo:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/234a6f71-5c54-431a-b1a9-b97ff876c1b4)

Viewing from top:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/a3b0c9b8-5352-4793-9d04-29ba1087ca6a)

### Full version info
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34667 (Git)
Build type: Release
Branch: main
Hash: https://github.com/FreeCAD/FreeCAD/commit/af5b8714a8371162addb97dd25c29250fcecf7ad
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods:

    Curves 0.6.13
    OpenDark 2023.10.20a
    sheetmetal 0.3.1
    [/code]

### Subproject(s) affected?

Core

### Anything else?

https://forum.freecad.org/viewtopic.php?p=676725
https://forum.freecad.org/viewtopic.php?p=146925

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Here is a demonstration. Simple model but you cannot distinguish the colors/faces or features you want to see, when viewing it directly from the normal direction of the faces. All appear white. 
You can take alook in the file and edit the first sketch: 
[environment_light_view-from-top.zip](https://github.com/FreeCAD/FreeCAD/files/13061634/environment_light_view-from-top.zip)

![glossy-face-is-white](https://github.com/FreeCAD/FreeCAD/assets/6246609/4fbc0456-dbb2-4e0f-a6de-108fb151e2b9)

**Comment by maxwxyz** [comment]
Thanks, great description: http://catiadoc.free.fr/online/basug_C2/basugbt1701.htm
If [this ](https://forum.freecad.org/viewtopic.php?f=10&t=9663&start=60#p394930)is implemented in the @realthunder fork, can this be implemented in main with a PR?

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/11146

**Comment by xtemp09** [comment]
Has this issue been solved with #11146?

**Comment by maxwxyz** [comment]
I hope, but cannot build FC myself so I'm waiting for the next weekly build.

**Comment by maxwxyz** [comment]
Works flawlessly, thanks!
