### ISSUE TITLE
[Problem] Network Manager Error

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#11120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Network Manager Error: __reply_finished not called by a Qt signal" error while trying to run the addon manager 

>Traceback (most recent call last):
File "/tmp/.mount_FreeCAja2QAS/usr/Mod/AddonManager/addonmanager_connection_checker.py", line 80, in cancel_network_check
self.connection_checker.success.disconnect(self._check_succeeded)
RuntimeError: Failed to disconnect signal success()

### Full version info

```shell
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Addon Manager

### Anything else?

https://forum.freecad.org/viewtopic.php?t=82060

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Direct link to source: https://github.com/FreeCAD/FreeCAD/blob/d529193f751e212fa5e6f08374e2cb452ea82b3a/src/Mod/AddonManager/addonmanager_connection_checker.py#L80

**Comment by luzpaz** [comment]
What's the solution here ?
