### ISSUE TITLE
[Feature Request] PartDesign: Pad UpTo multiple faces

### ISSUE THREAD

**Issue by FlachyJoe** [FreeCAD/FreeCAD#11135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

PartDesign_Pad only allow to select one face to end to. In cases of the base's projection is partially out of one face it's not sufficient (see #11111 and #10538).

### Full version info

```shell
[code]
OS: Debian GNU/Linux trixie/sid (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34594 (Git)
Build type: Unknown
Branch: main
Hash: 3d9e3fa809e7dbc3ec60ed23195759b5aff4ed54
Python 3.11.6, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
[/code]
```

### Subproject(s) affected?

PartDesign

### Anything else?

OCC take a shape as limit:
`BRepFeat_MakePrism::Perform (const TopoDS_Shape& Until)`
but we provide a face:
```
void FeatureExtrude::generatePrism(TopoDS_Shape& prism,
                                   const std::string& method,
                                   const TopoDS_Shape& baseshape,
                                   const TopoDS_Shape& profileshape,
                                   const TopoDS_Face& supportface,
                                   const TopoDS_Face& uptoface,
                                   const gp_Dir& direction,
                                   PrismMode Mode,
                                   Standard_Boolean Modify)
// […]
        BRepFeat_MakePrism PrismMaker;
// […]
            PrismMaker.Perform(uptoface);
```

We should create a TopoDS_Shape from selected faces and provide it to generatePrism.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
what's the next step @FlachyJoe ? from a UX perspective I think it would be ideal to unify up to face and up to shape into just one mode where we can select either an entire shape or a group of faces. I can help out with the UI when we're settled on the App side

**Comment by maxwxyz** [comment]
is up to shape now also integrated into up to last and up to first, when the profile is intersecting multiple faces (https://github.com/FreeCAD/FreeCAD/issues/11111#issuecomment-1772432318)?

**Comment by FlachyJoe** [comment]
@maxwxyz No, uptolast and uptofirst still use faces and IMHO this behavior shouldn't changed. With these two modes the prism ends at the face **continuity** and this feature is required. The uptoshape mode use all the faces of the base shape and doesn't extend them.
@adrianinsaval 
UpToShape could become the default mode for sketch which doesn't belong a face of the base shape.
UpToShape could allow another shape selection, not only the base shape. UptoFace could use multiple faces. But I think we can't merge them because UpToShape can't deal with offset.

**Comment by adrianinsaval** [comment]
If we get multiple faces working, will there be any remaining usecase for up to shape? I don't think so.

**Comment by FlachyJoe** [comment]
@adrianinsaval In fact I don't see a case where multiple faces are needed but not the full shape.

**Comment by adrianinsaval** [comment]
> @adrianinsaval In fact I don't see a case where multiple faces are needed but not the full shape.

if you need to select any intersected set of faces besides the first ones, a pocket up to shape would be pretty pointless too

**Comment by maxwxyz** [comment]
> @adrianinsaval In fact I don't see a case where multiple faces are needed but not the full shape.


what about the following example file: 
[pad.zip](https://github.com/FreeCAD/FreeCAD/files/13347904/pad.zip)


If I extrude a profile which would intersect multiple faces. What would happen when I select up to shape? I need multiple faces to constrain it to either the first shell walls (inner or outside) or the last shell wall (inner or outside) or the wall in the middle. To first and to last currently does not work at all in this situation.
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/ffca625b-bb7f-4379-834d-e03c179a99bc)

**Comment by FlachyJoe** [comment]
@maxwxyz I agree it's a use case. Solved by #11392 
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/41ff9235-4893-41d7-b276-8a3992535aba)
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/289adf92-ab76-4934-ac1a-f4050098a3c9)
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/37f9cbcb-95b0-478c-94fe-e82ef52014ad)
One face selection conserves the previous behavior:
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/9199062e-f72a-4fc5-bc38-d7e8c77398a3)

**Comment by maxwxyz** [comment]
@FlachyJoe and what is the result with up to shape? through all or to the first? In this example to last and to first does not work.

**Comment by FlachyJoe** [comment]
@maxwxyz When you select a full shape it ends at the first intersection for Pad and at the last for Pocket (see https://github.com/FreeCAD/FreeCAD/pull/11392#issuecomment-1809974237).

I think I can make a switch for this and base UpToFirst and UpToLast to shape and not face. But it will break the backward compatibility as the face extension won't occurs. Do we need an UpToLastFace and UpToFirstFace? I open [a forum thread](https://forum.freecad.org/viewtopic.php?t=82724).

**Comment by FEA-eng** [comment]
Perhaps this issue could be closed as Up to Shape is fully merged now and allows face selection in GUI.

**Comment by FlachyJoe** [comment]
Buggy (#14663) but done :smiling_face_with_tear:
