### ISSUE TITLE
[Problem] Missing API documentation for `src/Mod/Part/App/ShapeFix/ShapeFix_EdgePy.xml`

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#11182]
Currently the XML files show missing documentation for said ShapeFix functionality.

https://github.com/FreeCAD/FreeCAD/blob/410d4f9f6acb56cf84f1117dd39a595bcd551f15/src/Mod/Part/App/ShapeFix/ShapeFix_EdgePy.xml#L15-L52

CC @RohanMishra315

**Comment by shivam200446** [comment]
I want to work on it assign me!

**Comment by RohanMishra315** [comment]
I'll do it

**Comment by RohanMishra315** [comment]
I'll do it @luzpaz

**Comment by luzpaz** [comment]
Closing. Thanks @RohanMishra315!

**Comment by RohanMishra315** [comment]
Hey @luzpaz Sorry for all delay, it's been a hectic month . I'll start working on all issues right away.

**Comment by luzpaz** [comment]
All good, no pressure mate
