### ISSUE TITLE
[Problem] Subvolume property unset when cloning or linking a door with a substraction volume

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#11186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When cloning a door which has the Subvolume property set to a solid to be substracted from the host wall, the resulting clone has an empty Subvolume property, thus the substraction volume is in fact never substracted from the host wall.

[Related forum discussion](https://forum.freecad.org/viewtopic.php?p=714994#p714994), which contains [an attached file to reproduce the bug](https://forum.freecad.org/download/file.php?id=240667).

![Captura de pantalla de 2023-10-25 22-53-54](https://github.com/FreeCAD/FreeCAD/assets/148809153/f6d8e92d-bc11-4553-b8e9-594d8c4cf922)

### Full version info

```shell
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git) Snap 759
Build type: Release
Branch: tag: 0.21.1
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Installed mods: 
  * BIM 2021.12.0
```

### Subproject(s) affected?

Arch

### Anything else?

1. If instead of cloning, a link or a copy is made, this behaviour is not exhibited
2. Both for cloning and linking, the resulting door needs to be manually added to the wall. That is, their Hosts property needs to be set, otherwise the resulting doors are unattached to the wall where the original door is.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by paullee0** [comment]
Also great to know it is already fixed ! :D
