### ISSUE TITLE
[Problem] Substraction volume slightly off when door added to wall at an angle to X axis

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#11185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating a door with the Subvolume property set to a volume that is to be substracted to the host wall, the substracted volume is slightly off if the wall is not parallel to the X direction.

[Related forum discussion](https://forum.freecad.org/viewtopic.php?p=714994#p714994), which contains [an attached file reproducing the bug](https://forum.freecad.org/download/file.php?id=240667).

![Captura de pantalla de 2023-10-25 22-45-23](https://github.com/FreeCAD/FreeCAD/assets/148809153/bf671124-8cfe-4aa9-802f-0c21ba61bcac)

### Full version info

```shell
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git) Snap 759
Build type: Release
Branch: tag: 0.21.1
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Installed mods: 
  * BIM 2021.12.0
```

### Subproject(s) affected?

Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
CC @yorikvanhavre
