### ISSUE TITLE
[Problem] Can't edit PropertyLinkSubList from GUI

### ISSUE THREAD

**Issue by FlachyJoe** [FreeCAD/FreeCAD#11192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When clicking the three dot button of a PropertyLinkSubList the user is able to select (sub)elements but the property doesn't reflect the choice.

### Full version info

```
OS: Debian GNU/Linux trixie/sid (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34792 (Git)
Build type: Release
Branch: main
Hash: 6c47e4d647fd9d2cb71feaabb78db19ead296f7a
Python 3.11.6, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
This is a regression, right ?

**Comment by FlachyJoe** [comment]
Problem occurs with PartDesign features but not with Part ones.
