### ISSUE TITLE
[Regression] Mesh WB does not export Links to STL or DAE

### ISSUE THREAD

**Issue by bjnobre** [FreeCAD/FreeCAD#11200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I've realized any 2nd links to a part on assembly4 don't be exported. See it bellow.

source:
![pen-full-source](https://github.com/FreeCAD/FreeCAD/assets/20462223/5af8cd0c-6123-47ad-8c98-4a5457f58728)
output:
![pen-stl](https://github.com/FreeCAD/FreeCAD/assets/20462223/a8921834-015e-49ca-a537-f1c5c9ec4104)

I've tried also on every other formats, and the same issue occurs. I've tried with another project, with more simple shapes and the the errors still there.

souce:
![a4-error-1](https://github.com/FreeCAD/FreeCAD/assets/20462223/55795cd4-933d-44ea-9572-bfc73efca4fd)
output:
![a4-error-2](https://github.com/FreeCAD/FreeCAD/assets/20462223/af28889d-fdf4-4fd5-a4d8-59cd50084390)

Even on draft 2d drawings, linked objects are not exported:

source:
![image](https://github.com/FreeCAD/FreeCAD/assets/20462223/ff53c2cd-b977-47f4-b9e4-14f5a2f3e48f)

output:
![image](https://github.com/FreeCAD/FreeCAD/assets/20462223/255cd899-1047-49b4-844a-9883e09a4bb5)

So, I assume that it's a issue with exporting module. I am using 0.22 dev version, but it occurs on 0.21 version.

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34789 (Git)
Build type: Release
Branch: main
Hash: 41503d63ebc3de96d156e6eb0cdb889ebb150bd4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Portuguese/Brazil (pt_BR)
Installed mods: 
  * Assembly4 0.50.2
  * fasteners 0.4.62
  * sheetmetal 0.2.63
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Have you reported to Assmebly4 repo ?  
Can you also include the the file (zip it and drag-drop in to gitihub textbox)

**Comment by Roy-043** [comment]
No need for a file. The Mesh WB does not export Links.

**Comment by luzpaz** [comment]
@Roy-043 thanks. Can you update the ticket title then, if you don't mind ?

**Comment by Roy-043** [comment]
This a regression. The problem does not occur in V0.20.
Forum post reporting the same issue:
https://forum.freecad.org/viewtopic.php?t=82289

**Comment by bjnobre** [comment]
I've tested an assembly4 export on fc 020 abd on fc 022. I've got the expected result on the older version.

on fc 022
![image](https://github.com/FreeCAD/FreeCAD/assets/20462223/5a23c2ee-af34-4a9d-971f-13438006ca3d)

on fc 020
![image](https://github.com/FreeCAD/FreeCAD/assets/20462223/ebaf7f94-4464-447b-8b01-c6f49c69924f)

the files on both version:
[A4-test-in-fc0200.zip](https://github.com/FreeCAD/FreeCAD/files/13208660/A4-test-in-fc0200.zip)
[A4-test-in-fc0220.zip](https://github.com/FreeCAD/FreeCAD/files/13208661/A4-test-in-fc0220.zip)

**Comment by Montaire** [comment]
I have the same issue with the **35176-2023-11-23** development version as well.

In FreeCad it looks like this:
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/97aa12e4-8e79-4fe1-aeba-da9936851d58)

Exported from 21.1 release:
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/e32f84d5-b966-478e-8b17-c37de7bf440d)
From the supports only one side element is exported but nothing more.

Exported from 22  35176-2023-11-23 release:
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/ec284f8d-7d76-4643-8dff-08e74dad6296)
Here all the left side elements are exported.

And here is my model, I am not sure if I did anything wrong here:
[battery_holder_v3.6.zip](https://github.com/FreeCAD/FreeCAD/files/13464191/battery_holder_v3.6.zip)
The side element is using mirroring, and its in the same object as the front element.

I may accidentally created the file which has all the problems and symptoms that's possible, "the veterinarian's horse".

**Comment by bgbsww** [comment]
See https://github.com/FreeCAD/FreeCAD/issues/10545#issuecomment-1826325891  It is a bug, but not this bug; it exists independently of links.

**Comment by Montaire** [comment]
Hey @bgbsww 

Thank you for your feedback.
I created a new version, and it seems removing the elements from the extra object wrapper, and instead putting them into a compound object does help! And also I used a link for the left side of the support, and mirrored that.

[battery_holder_v3.6.zip](https://github.com/FreeCAD/FreeCAD/files/13464508/battery_holder_v3.6.zip)

Now with version **21.1** I get the first support as it should be.
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/4fd1668c-5c01-4290-991d-94ad91d05053)

With the dev version 22 **35176-2023-11-23** the rotation is all around the place, but the core issue is fixed well with your commit!
![image](https://github.com/FreeCAD/FreeCAD/assets/9551575/655b0e18-8863-49d8-ac52-558a754905c2)

**Comment by bgbsww** [comment]
Thanks for the additional file, @Montaire !  I haven't found it yet, although I'm suspicious of https://github.com/FreeCAD/FreeCAD/blob/7561b90eb8bdbb0e692651d98d853da605e4deef/src/Mod/Mesh/App/Exporter.cpp#L51, its cache, and its interaction with https://github.com/FreeCAD/FreeCAD/blob/7561b90eb8bdbb0e692651d98d853da605e4deef/src/Mod/Mesh/App/Exporter.cpp#L104-L111 which loops twice when processing "Support" in the original file.

Since the support_face does not export, I'm more suspicious of the mesh content than the looping, but I need to step away and it will probably be a day before I get to digging deeper.

**Comment by bgbsww** [comment]
This isn't related to the links or lack thereof, and thus a different bug.  It is related to the precise structure of the "battery_holder_v3_6#Part" labeled as "support".  Creating a new Part with a Body inside and a Mirror does not duplicate the bug, but it also does not have exactly the same structure as the broken one.

I think it may be related to using a list of subobjects as opposed to the Group objects inside the Part, and if this is the case, it's a substantial change to how Exporter::addObject functions.

I'm going to try to duplicate the process of creating a broken Part to narrow this down.

**Comment by bgbsww** [comment]
OK!  So, bodies without Tips are not exported, and Mirrors do not export both the source and the mirror.

If you take support_front (the body ) in the example and add a Tip of SupportFront ( the pad ) then the support starts showing up in the export.  I'm not sure this is really a bug, as when I create bodies and place things in them, the Tip is set.
Any idea how this was created?  Maybe there's a bug in there not setting this value.

However, the screwy positioning is related to the fix in this bug, and the latest PR corrects that.

Should we open a separate bug for "Mirrored objects do not appear in exports to STL or DAE"?

And maybe a bug for "Bodies without Tips do not appear in exports to STL or DAE?"  if the consensus is that this is an incorrect behavior?

**Comment by Montaire** [comment]
@bgbsww, its a good question, I fiddled around a lot with the support for the resin print. Should I try to replicate how I did it? I can do it in the afternoon. Probably it was introduced by dragging in and out the lofts, but I am not entirely sure. Thank you again for your help!
