### ISSUE TITLE
[Problem] 

### ISSUE THREAD

**Issue by sebaras** [FreeCAD/FreeCAD#11242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FC Info

### Full version info

```shell
[code]
OS: Windows 10 build 19042
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods: 
  * A2plus 0.4.60n
  * Assembly4 0.50.2
  * CADExchanger
  * ExplodedAssembly
  * fasteners 0.4.60
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Anything else?

How to get a Volume and wight out from a Part Design without any Macro FCInfo?
FCInfo doesn't work any more in Freecad 21.1. How can i solve this Problem?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
This is not a help page, please post your question at the [FreeCAD Forums](https://forum.freecad.org) or one of the social media platforms linked to on the FreeCAD homepage.
