### ISSUE TITLE
Freecad 0.21.1 doesn't start on Windows 10

### ISSUE THREAD

**Issue by Tecorauto** [FreeCAD/FreeCAD#11274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have installed Freecad 0.21.1 stable on windows 10 X64 and it does not open

Freecad 0.21.1 does not start on Windows 10 X64, only the boot presentation appears but does not open the program
### Full version info

```shell

```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Bug rewritten in english. Please populate the ticket with appropriate information. 

1. Full [about](https://wiki.freecad.org/About) info
2. Any output that you see. please add to ticket
3. Step-by-step way for us to reproduce
4. The location name of the place you installed FC to

**Comment by Roy-043** [comment]
Please check this forum post:
https://forum.freecad.org/viewtopic.php?t=30573

**Comment by luzpaz** [comment]
@Tecorauto please respond

**Comment by luzpaz** [comment]
No response from OP. Closing
