### ISSUE TITLE
[Problem] UI: Treeview element not readable with dark theme

### ISSUE THREAD

**Issue by arkadesOrg** [FreeCAD/FreeCAD#11270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The treeview element for parts looks like this and is not readable.

![comboview](https://github.com/FreeCAD/FreeCAD/assets/6597386/3f1bd97d-2bbf-4bcd-99d5-4678b151673b)

### Full version info

```shell
[code]
OS: Archlinux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: makepkg
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.11.5, Qt 5.15.11, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment]
Already reported here: https://github.com/FreeCAD/FreeCAD/issues/7623#issuecomment-1287544999

**Comment by arkadesOrg** [comment]
oh how did you find that? I tried... :( sorry

**Comment by luzpaz** [comment]
Keep this ticket opened. I've moved #7623 to a discussion format because it was difficult to read and became unmanageable. The direct link to the discussion is https://github.com/FreeCAD/FreeCAD/discussions/11276#discussioncomment-7478894

**Comment by MisterMakerNL** [comment]
You tried turning it on and off again? ;)
This color is set by preference pack and needs a reboot to be applied.

**Comment by luzpaz** [comment]
We don't prompt the user to reboot FC, right ?

**Comment by arkadesOrg** [comment]
> We don't prompt the user to reboot FC, right ?

I was prompted to reboot after installing a preference pack, yes.

**Comment by luzpaz** [comment]
And you rebooted ?

**Comment by luzpaz** [comment]
...

**Comment by luzpaz** [comment]
@arkadesOrg ping. Clarrifying if you infact rebooted FC after making the change ?

**Comment by luzpaz** [comment]
Closing as no response from OP
