### ISSUE TITLE
[Problem] Sketcher: Offset rectangle sould be parallel

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The offset lines should be parallel to the original rectangle (are at creation but can be moved freely):
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/d02e718c-d1c8-4b06-a09e-e1fd2667ee8d)

### Full version info

```shell
[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34873 (Git)
Build type: Release
Branch: main
Hash: 889c8c49f1bbc0910c8dc32a512f4c6fbedeb8b9
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * BIM 2021.12.0
  * CfdOF 1.24.7
  * CurvedShapes 1.0.4
  * Curves 0.6.14
  * Defeaturing 1.2.1
  * fasteners 0.4.68
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.10.30
  * sheetmetal 0.3.1
  * Silk 0.1.5
[/code]
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Thanks for the report. 2 missing parallels it seems then.
