### ISSUE TITLE
[Feature Request] Sketcher: Add on OVP / tool widget for other tools

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11290]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Add on view parameters for other sketcher tools:

- [x] ellipses
- [x] circles / arcs
- [ ] polyline
- [ ] dimension tool to see current mode
- [x] slot / arc slot (maybe group them in one tool and toggle through them all)
- [ ] arcs of ellipse, hyperbola, parabola
- [ ] fillet tools with toggle between them
- [ ] b-splines

@PaddleStroke I hope it is okay to create a FR for multiple tools as otherwise I would be spamming new issues.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34873 (Git)
Build type: Release
Branch: main
Hash: 889c8c49f1bbc0910c8dc32a512f4c6fbedeb8b9
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * BIM 2021.12.0
  * CfdOF 1.24.7
  * CurvedShapes 1.0.4
  * Curves 0.6.14
  * Defeaturing 1.2.1
  * fasteners 0.4.68
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.10.30
  * sheetmetal 0.3.1
  * Silk 0.1.5
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke if possible, the Polyline could also use the tool widget in the task dialog to display and change the current mode (line, arc, tangent, ...) of the Polyline (M). Additionally, the OVP should be displayed (line: angle, length (+maybe toggle for height/width); arc: radius + angle,...)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/803f4f98-d21d-4cb1-9fc2-7bdaa68f7e2a)

I've looked in the code but the LineSet seems very different from line or rectangle :D

**Comment by PaddleStroke** [comment]
If you know python or other language, you should be able to navigate enough I think :) Just following patterns of other DSHs.
If you need some help don't hesitate to reach out

**Comment by maxwxyz** [comment]
@PaddleStroke 
> If you're willing to tackle the missing tools OVP implementation, I would suggest starting with arc of ellipse. Because you can use other DSH as reference.

I struggle with this arc of ellipse with OVP or am I missing something:
- currently the ellipse tool has OVP but does not create a constraint for them (you enter all but no dimension constraints are created)
- it has more inputs than arc of circle or ellipse
- considering the length of the ArcOfEllipse: should this also be in degree (like arc of circle)? If so, there currently is no constraint for an angle using an ellipse

**Comment by maxwxyz** [comment]
also noticed that
- 3-point-circle creates no constraints when entering all OVP
- 3-point-arc is not fully constrained (no radius constraint / third point)
- polygon tool creates no angle constraint from OVP angle
- arc slot is not fully constrained when entering all OVP. No constraint for the starting angle

**Comment by PaddleStroke** [comment]
I don't remember precisely for ellipse, but the idea is that if no
constraints can be added, then none are. For instance for 3 point circles,
many OVP can't be converted to constraint.
For ellipse I don't remember precisely I need to check.

Arc of ellipse need more steps and more OVP than arc or ellipse indeed.

**Comment by maxwxyz** [comment]
I've also created individual issues to keep track of the remaining ones. That's why I'm closing this one here.

**Comment by MiqCG** [comment]
> I've also created individual issues to keep track of the remaining ones. That's why I'm closing this one here. And I've stolen your screenshot to demo OVP/widget, I hope that's ok @PaddleStroke

Dear, @maxwxyz ,

I have searched the individual issues derived of this one and I was able to find the Polyline one #12462 and Arc of Ellipse, Hyperbola, Parabola #12463.
I think is specially interesting the one about Chamfers and Fillets. Is there an issue created?
