### ISSUE TITLE
[Problem] (Additive) Loft may failed because cross surface, it's depend on draw sequence.

### ISSUE THREAD

**Issue by sppmg** [FreeCAD/FreeCAD#11331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

(Additive) Loft may failed because cross surface, and it's depend on draw sequence.

Reproduce:

1. Draw concentric circles in 2 sketch, always outside first.
2. Change attachment of a sketch, move it 1 mm in Z axis.
3. Additive Loft
4. Now, change a sketch, inside circle first. (Just delete outside and draw again outside)
5. Additive Loft again, and you will see cross surface in preview, nothing when finish create.

### Full version info

```shell
[code]
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34836 (Git) AppImage
Build type: Release
Branch: main
Hash: 862eef57eb4aa042f87d9f19dc768a017b17dae6
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Chinese/Taiwan (zh_TW)
Installed mods: 
  * DynamicData 2.46.0
  * Assembly4 0.11.12
  * CfdOF 1.16.7
  * fasteners 0.4.53
  * A2plus 0.4.60k
  * Curves 0.6.8
[/code]

ver 0.21 same problem.
```

### Subproject(s) affected?

None

### Anything else?

Cross surface (Loft failed) : 

![screenshot65](https://github.com/FreeCAD/FreeCAD/assets/6098465/bbbe733e-4f7f-4e66-99b2-8806a0cde791)

Normal:

![screenshot66](https://github.com/FreeCAD/FreeCAD/assets/6098465/1c3e337c-c83e-4956-bdaa-56fec3b1c967)

Demo file:
[bug demo.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/13310363/bug.demo.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
That is pretty much how it works. RTM:
https://wiki.freecad.org/PartDesign_AdditiveLoft#Notes
