### ISSUE TITLE
[Problem] Techdraw view does not consider body placement coordinates when positionning elements on the view.

### ISSUE THREAD

**Issue by slalancette** [FreeCAD/FreeCAD#11333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you create two bodies extruding from sketches in global xy plane,  and you move one body with the move command from draft bench, this changes the placement coordinates. So in model viewer, the object changes its location.

However, when using the "insert View" command for the objects, the moved object is still in the original sketch location, as if it is not considering the placement parameters of the body.

### Full version info

```shell
[code]
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * BIM 2021.12.0
[/code]
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can you provide a file where this happens?

**Comment by slalancette** [comment]
Yes sure, just rename the file to bug.FCStd
[bug11333.zip](https://github.com/FreeCAD/FreeCAD/files/13320082/bug11333.zip)

**Comment by slalancette** [comment]
I just see that the file was created with an older version of freecad cannot reproduce the bug.

**Comment by WandererFan** [comment]
This is not a bug.

Positioning on the page is controlled by a views X,Y properties.   You have two separate views, each positioned appropriately.

If you want a view of multiple objects, with their relative position intact, you have to include all the objects in the same view. 
![bug11333_ViewPositions](https://github.com/FreeCAD/FreeCAD/assets/3587161/df690f8b-6e65-40e8-81bf-9636140949de)
[bug11333_mod.zip](https://github.com/FreeCAD/FreeCAD/files/13320265/bug11333_mod.zip)

**Comment by slalancette** [comment]
That it is my selection method that was bad.  I was selecting the pad inside object that is why.  Check this:
![image](https://github.com/FreeCAD/FreeCAD/assets/127478271/ef2cc3de-9d29-4822-a10d-37bd703d406b)
![image](https://github.com/FreeCAD/FreeCAD/assets/127478271/2774b776-7659-4998-a46f-6fe24e9ad109)

**Comment by slalancette** [comment]
and the upodated file.  Correct view on page 1, buggy view on page 2: 
[bug11333_2.zip](https://github.com/FreeCAD/FreeCAD/files/13320351/bug11333_2.zip)

**Comment by slalancette** [comment]
Thank you very much for your support, that was quick.
