### ISSUE TITLE
[Problem] Sketcher: Cursor Icons are different from Toolbar Icons

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Sketcher mouse cursor overlay icons (when a tool is selected) are different than the corresponding toolbar icons (for almost all tools).
In general, they are also overlapping with the displayed coordinates / dimensions next to the cursor.

A few examples for the cursor icons:
- PolyLine Tool: displays the old toolbar icon
- Arc: displays a mirrored icon of the toolbar icon
- Sketcher fillet: displays a chamfer cursor (not even a feature in sketcher), toolbar is a fillet
- 3-point circle: displays the arc toolbar icon
- Line/Splines/Circle/Rectangle: some completely different icons
- Rectangle options: Icon is squared, mouse pointer not. Rounded rectangle does not show the points. 3 corners & center ´+ 3 corners: not an own icon

A few examples from above:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/c97110fd-0ca7-4be0-af9c-f7d8a5865136)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/8b2c834a-c0c0-4545-a518-eecc304cb2c5)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/690a3019-40a3-4a32-9bb3-9f062f512d79)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/e2a7f517-2fef-4415-9f23-e2ab851838ab)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/88a5009b-1fcf-408d-8b5d-5ec091dcec37)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34959 (Git)
Build type: Release
Branch: main
Hash: 640018bfa7878a79e1b3c220ddd488d66464dc70
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * BIM 2021.12.0
  * CfdOF 1.24.7
  * CurvedShapes 1.0.4
  * Curves 0.6.14
  * Defeaturing 1.2.1
  * fasteners 0.4.68
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.10.30
  * sheetmetal 0.3.1
  * Silk 0.1.5
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
I think they are png files.

**Comment by luzpaz** [comment]
Who wants to tackle this ?

**Comment by maxwxyz** [comment]
> Who wants to tackle this ?

created a PR
