### ISSUE TITLE
When editing a sketch, it scrambles other sketches that use it as external geometry

### ISSUE THREAD

**Issue by buteomont** [FreeCAD/FreeCAD#11369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am making a lipped box for an electronic project. You know, the kind where the wall thickness is split for about 1/4 inch so that the top and the bottom overlap. I'm using a profile sketch for both the top and bottom and sweeping it around a rectangle.

I decided that the overlap part needed a small ridge on the lid part and a small valley on the bottom part, so that they would stay together more securely.  I added a 0.3mm half-circle indentation to the bottom sketch, split the line it was on, and fixed up the constraints.  Then I went to the lid sketch to add the matching bump and it was all scrambled. I tried fixing it up but was unsuccessful. Luckily, I had not yet saved it and was able to revert back to the non-scrambled version.

I'm probably doing something wrong but I feel that editing one sketch should _**never**_ scramble other sketches for any reason, hence this bug report.

### Full version info

```shell
[code]
OS: Ubuntu 20.04.6 LTS (GNOME-Flashback:GNOME/gnome-flashback-metacity)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.4
  * A2plus 0.4.60n
  * sheetmetal 0.3.0
  * fasteners 0.4.66
  * fcgear
  * ExplodedAssembly
[/code]
```

### Subproject(s) affected?

None

### Anything else?

[elevationatorCase.zip](https://github.com/FreeCAD/FreeCAD/files/13330016/elevationatorCase.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I think this is because of the TNP
