### ISSUE TITLE
[Feature request] Improve Draft Fillet to also work with arcs

### ISSUE THREAD

**Issue by Preeti19694** [FreeCAD/FreeCAD#11435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Fillet tool of draft workbench is not working with circular object. It is working fine with two straight lines but if there is one straight line meeting circular part at a point then this function is not working

### Full version info

```shell

```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Draft_Fillet is indeed very limited.

```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35024 (Git)
Build type: Release
Branch: main
Hash: 4ff00ef99869e35295a5a17b8f486901504c655b
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
```
