### ISSUE TITLE
[Problem] New assembly module - problem to show in ModernUX

### ISSUE THREAD

**Issue by marcin86junior** [FreeCAD/FreeCAD#11432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

https://forum.freecad.org/viewtopic.php?p=719547#p719547

I just hashed PreferencesPage - and its working

        #from Preferences import PreferencesPage
        #FreeCADGui.addPreferencePage(PreferencesPage, QT_TRANSLATE_NOOP("QObject", "Assembly"))

it's in Mod \ Assembly \

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35046 (Git)
Build type: Release
Branch: main
Hash: 6a66034ce27290e7b385a933d77375f55492d194
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods:
* fasteners 0.4.27
* InventorLoader 1.3.0
* ModernUI
* MOOC 2022.4.21
* ProDarkThemePreferencePack 1.0.0
* Render 2022.3.0
* sheetmetal 0.2.59
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
ModernUI addon is abandoned. Ribbon UI is the replacement. See https://github.com/geolta/FreeCAD-Ribbon please test on it and see if you can reproduce. If so, open a ticket there.
