### ISSUE TITLE
Python import fails when HOME directory does not exist, cannot override because calling `getpwuid_r()`? 

### ISSUE THREAD

**Issue by sgundry** [FreeCAD/FreeCAD#11547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

On Ubuntu 22.04, FreeCAD 0.19.2 apt install, python cannot be imported in environments without a home directory: 

```
>>> import FreeCAD
Initialization of FreeCAD failed:
While initializing FreeCAD the following exception occurred: 'Application data directory /home/testuser does not exist!'
```

Version: 
```
$ apt-get -s install freecad | grep version
freecad is already the newest version (0.19.2+dfsg1-3ubuntu1)
```

To reproduce, simply try import into python when the home directory does not exist. 

I have tried setting `FREECAD_USER_HOME`, `FREECAD_USER_DATA` and `FREECAD_USER_TEMP` environment variables but either Python import or FreeCAD are not using them.  I don't know if the Python import is ignoring these, or if during FreeCAD skips this code path for when being imported into python.  

I am not familiar with FreeCAD code base but believe the calling code is  `Application.cpp:getUserHome()`: https://github.com/FreeCAD/FreeCAD/blob/main/src/App/Application.cpp#L2987-L3005

If you check the HOME environment variable first before `getpwuid_r()`, users have the opportunity to change the home directory.  I am using an environment where I do not control the user and `/home/<user>` does not exist.

Edit:  [Looking at the 0.19.2 source](https://github.com/FreeCAD/FreeCAD/blob/7b5e18a0759de778b74d3a5c17eba9cb815035ac/src/App/Application.cpp#L2782-L2794), its unclear why `FREECAD_USER_DATA` isn't working for me. It could be how Python import environment is behaving. Sorry if that's the case. I'll keep updating. 

### Full version info

```shell
apt-get -s install freecad | grep version
freecad is already the newest version (0.19.2+dfsg1-3ubuntu1)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by plaes** [comment]
Are any of the `$XDG_...` variables defined? For example:
* `$XDG_DATA_HOME`
* `$XDG_CONFIG_HOME`

FreeCAD might need to be updated to properly handle XDG Base Directory Specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
