### ISSUE TITLE
[Wiki] Add cd before mkdir build

### ISSUE THREAD

**Issue by superbonaci** [FreeCAD/FreeCAD#11567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Replace this line:
https://wiki.freecad.org/index.php?title=Compile_on_Linux&oldid=1330049#:~:text=%23%20from%20the%20base%20of%20your%20freecad%20source%20folder%3A
```
# from the base of your freecad source folder:
```
With these two (the folder name `freecad-source` is usually the default when following the wiki):
```
# from the base of your freecad source folder:
cd freecad-source
```

### Full version info

```shell
not applicable.
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
`# from the base of your freecad source folder:` already means that you are in `freecad-source`. Therefore this does not make much sense IMO.

Also please do not use GitHub for Wiki related stuff. Next time start a forum topic instead.

**Comment by superbonaci** [comment]
@Roy-043 is it possible to create a wiki account? I didn't find the option.

**Comment by Roy-043** [comment]
Please start a forum topic first. I am not convinced that your suggestion makes sense.

**Comment by robbie-mac** [comment]
> @Roy-043 is it possible to create a wiki account? I didn't find the option.

"Create an account" has been disabled on the wiki. Go to the main page. It tells you how to participate.

**Comment by luzpaz** [comment]
@superbonaci looks like it's been fixed in the wiki, right ?

**Comment by superbonaci** [comment]
No idea maybe, thanks.
