### ISSUE TITLE
[Problem] PartDesign: Can't Specify a Plane Using MultiTransform Tool 

### ISSUE THREAD

**Issue by GITMuniac** [FreeCAD/FreeCAD#11571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This ticket explains my experience using the Multitransform tool which is now working differently than the older RT version of FreeCAD. The steps are as follows in V21.1:
1. Activate Part Design WB 
1. File->New 
1. Create a Body
1. Create a plate 30mm L x 30mm W x 5mm H using the Additive Primitive icon. Reference plane is XY. This will locate the primitive in the 1st quadrant.
1. Click on Create MultiTransform icon.
1. Properties opens up. Box should appear under Add Feature button. In Transformations box, right click to display a selection menu.
1. Click on Add mirrored transformation to select it. (Note, can't specify a mirror plane at this time.)

The following errors occur:
> No mirror plane reference specified
11:28:44 (qt.xkb.compose) failed to create compose table
11:37:41 Recompute failed!

Also the plane selection menu button appears which wasn't present above.

Work around... If you remove the feature Box before selecting the mirror transformation the error does not occur. It will allow selecting a mirror plane. Click on OK to exit and edit the MultiTransform from the model tree. Add the Box feature back in and the mirror transformation occurs without errors.

Instead of creating the plate with the Additive Primitive icon you instead make a sketch and pad that to 5mm, the Multitransform allows a mirror plane to be specified. The mirror will occur fine as expected. This "problem" happens with Mirror and Polar transformations but not Add Linear Pattern. It also appears you can't mirror something that's already mirrored using the dedicated icons. For example, if you wanted to place four holes in the corners of the plate above. The MultiTransform tool does allow this with the above caveat of removing the feature, adding a transformation then adding the feature back in.

### Full version info

```shell
OS: Linux Mint 20.3 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods:
* Assembly3 0.12.0
* sheetmetal 0.3.12
```

### Subproject(s) affected?

PartDesign

### Anything else?

Note: 
@PLChris  suggested I make a ticket on this.  The details on the situation are on the FreeCAD forum thread https://forum.freecad.org/viewtopic.php?t=83053

Hope this helps the developers.  Thanks for a great modeling tool.  Enjoy your day!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bgbsww** [comment]
At step 7, I used the plane selection menu to select a plane ( XY ). 

 I also tried XZ, XZ, and specifying a plane.  All of this seems to work in terms of showing the preview.  If I click the 'OK' at the bottom and then the 'OK' at the top, everything is fine.

However, if I right-click on the resulting 'Mirrored' transformation and delete it, the entire application crashes.

If save it however, from that point I cannot make it crash, no matter how I edit, or delete and try to recreate it.

There are lots of "MultiTransform: No mirror plane reference specified" whenever I have a mirror and have not yet specified a plane.  But the crash only happens the very first time through.

So, overall I suspect we need to go for a default option in this case, and preselect "XY plane" instead of nothing in the plane selection button, and track down the crash if it still happens then.

**Comment by GITMuniac** [comment]
Hi - I did play around with trying to crash the program via deleting transformations.  I couldn't get it to crash so that isn't a problem on this.  Glad you found this underlying issue and fixing it means adding minimal code.  I do a fair amount of coding myself in C so I try to be sensitive to others trying to find and fix problems.  The devil is always in the details.  Many hands make light work.  Enjoy your day and thanks for the development efforts.

Best - Scott

**Comment by GITMuniac** [comment]
Hi - I did check the weekly build 35370-2023-12-11 and it works as expected with a default plane filled in.  I donated some bread to your development efforts.  Thanks for the fast fix and making FreeCAD available for those in need.  Enjoy your day!

Best - Scott
