### ISSUE TITLE
[Problem] Sketcher: Std ViewFitAll not working if grid is on

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD#11570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The `Std ViewFitAll` function (shortcut: `V, F`) does not work in sketcher.
If executed, it first scales the sketch to fit, but then returns to the previous scaling undoing the function.

[Bildschirmaufnahme.webm](https://github.com/FreeCAD/FreeCAD/assets/13178920/30cdc616-f467-4eaf-9963-18b83915e110)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35240 +2 (Git)
Build type: Release
Branch: Meins
Hash: 9fce0b996c11c616c94aedb71c3dbb7f624ca7df
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.14
  * Assembly4 0.50.4
  * Pyramids-and-Polyhedrons
  * sheetmetal 0.3.12
  * Silk 0.1.5
  * CurvedShapes 1.0.5
  * DynamicData 2.54.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * ExplodedAssembly
  * fasteners 0.4.70
  * Render 2023.8.18
  * A2plus
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Do you use custom shortcuts? With a default setup `V, F` does not work as `V` is a shortcut in the Sketcher WB. Try assigning a unique shortcut to Std ViewFitAll.

**Comment by berberic2** [comment]
> Do you use custom shortcuts? With a default setup `V, F` does not work as `V` is a shortcut in the Sketcher WB. Try assigning a unique shortcut to Std ViewFitAll.

I have no custom shortcuts, but for some reasons it works sometimes nontheless (maybe a bug by itself?).
but you can execute `ViewFitAll` via menu too, with the exact same effect.

[Bildschirmaufnahme_2.webm](https://github.com/FreeCAD/FreeCAD/assets/13178920/81d9de90-3d4f-4c38-ba19-d0f5f85c934b)

I have not custom shortcuts, but for some reasons it works sometimes nontheless (maybe a bug by itself?).
but you can execute `ViewFitAll` via menu too, with the exact same effect.
