### ISSUE TITLE
[Problem] Assembly4 Asm4_variablesCmd Add Integer

### ISSUE THREAD

**Issue by GitUserVoLTRA** [FreeCAD/FreeCAD#11587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Adding Integer variable creates a variable with value '0' (zero) althougth a value > 0 entered in 'Add Variable' dialog
This problem still exists in latest weekly build

### Full version info

```shell
[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * Assembly4 0.50.4
  * Behave-Dark-Colors 0.1.1
  * BOLTSFC
  * Curves 0.6.14
  * DynamicData 2.54.0
  * ExplodedAssembly
  * fasteners 0.4.71
  * Help 1.0.3
  * kicadStepUpMod 10.21.7
  * Render 2023.8.18
  * sheetmetal 0.3.12
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This should be reported here instead:
https://github.com/Zolko-123/FreeCAD_Assembly4

Closing this.
