### ISSUE TITLE
[Feature request] Sketcher: double-click to select a chain of geometry

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#11605]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

In a complex sketch, where there are several closed ant non-closed shapes, that can overlap each other, it can be difficult to select one of them. The rectangular selection is too broad and it is often necessary to select individual segments, which can be quite long for complex shapes.

The problem exists in every CAD program (design or drafting). QCAD provides a very easy way to select only the desired shape: you double-click on one of the segment, and the connected geometry is automatically selected in a chain of reaction.

### Full version info

```shell
OS: Ubuntu 23.04 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35249 (Git) AppImage
Build type: Release
Branch: main
Hash: 94ca51b7799b2ac60a2a56d7e6e753bb97a73671
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * Render 2023.8.18
  * OpenDark 2023.10.30
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by M4xTheMan** [comment]
Are you aware of the filters in Sketcher WB? It's good practice to keep your Sketches simple by the way. It's not always possible but most of the time you shouldn't have such problems.

**Comment by pierreporte** [comment]
@M4xTheMan Do you mean the following?

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/24b2f311-43f7-4d6e-a530-417b1e065ec3)

It allows you to narrow down the list to various types of geometry. If I know how to use it correctly, it doesn’t filter shapes. Say you have a slot (two lines and to arcs), you can filter arcs and lines in general but not the ones precisely you want to edit.

I know that sketches should be kept simple. We are talking about the case where it cannot.

**Comment by M4xTheMan** [comment]
You could select the elements which you'd like to filter atm.

**Comment by pierreporte** [comment]
Yes, so you can’t filter by shape. You need to select it manually, segment by segment, one way or another.

Granted, it’s not the most important feature that FreeCAD needs at the moment.

**Comment by maxwxyz** [comment]
I think this could be done. What is the use case where this would be needed? Could you provide an screenshot of an example? What should be selected when the chain is not closed (open loop)? What should happen at T or Star intersections (a point on the loop where more than 2 edges meet)?

**Comment by pierreporte** [comment]
This for cases like these:

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/74664e87-39f0-4b2b-8875-5ec7c4f68765)

How do you easily select the biggest shape? You must manually click on each segment. No rectangular selection is possible because it would the rectangular shape inside and the triangle. Thankfully, hitting Shift or Caps Lock once is enough because it is remembered, which is a very good thing I just discovered.

Here is a screenshot from QCAD:

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/31af8163-7c21-4ac3-bad9-9fc31ef6a10f)

Double-clicking on an edge of the square or of the triangle selects the whole house.

Double-clicking on the stick figure torso selects this and its legs.

Double-clicking on the circle or the arms selects only that.

I don’t know what should happen for construction lines. There are arguments for selecting them with connected geometry and arguments against. Maybe allow both depending on an option, keystroke or something?

**Comment by ninao-xyz** [comment]
we have a tool in the path workbench that does that. but instead of double click, we select a edge (or multiple edges) and click on the button, and it will try to select the full edge loop. the tool can be used in the sketch workbench as well, I use it all the time. In my opinion, that functionality shouldn't be tied in a specific workbench, i see it as a more general tool to be used across workbenches. (not sure if the double click is the best option as suggested by op, blender3d uses a shortcut/menu item for it) 
![Screenshot from 2024-01-05 21-24-02](https://github.com/FreeCAD/FreeCAD/assets/10292929/982233be-fbd4-46ca-8019-639333cf24d5)

**Comment by pierreporte** [comment]
@ninao-xyz How does it work? It says “Closed loop detection failed” with a simple rectangle.

@obelisk79 What do you think about having `Path_SelectLoop` in the sketcher toolbars?

**Comment by ninao-xyz** [comment]
@pierreporte I've recorder a small gif that shows how I use it. (I'm using the latest weekly builds of freecad, but current stable release should be the same)
![Peek 2024-01-05 21-45](https://github.com/FreeCAD/FreeCAD/assets/10292929/62798d98-7d9d-454a-a784-d3c41e137160)

**Comment by pierreporte** [comment]
I found the issue: I had to exit the sketch and re-enter it. To select a shape, you need to exit the sketch first, even if the sketch existed before the edition that added the shape. It ignores construction lines when a normal line is selected first. The command has bugs and needs refining but it seems viable.

@PaddleStroke Do you think that `Path_SelectLoop` can be could be fixed and extended for the sketcher worbench? I don’t know who usually works for Path WB.

**Comment by PaddleStroke** [comment]
I think this feature request is good, and I would rather use double click than a tool. My reason is that double click to select all the connected edge feels natural (it is the same in text editors, double click select the whole chain of character) and does not add a tool to the toolbar.
Also it is probably easy to implement.
