### ISSUE TITLE
Assembly: Creating and using datum outside PartDesign is not practical

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#11607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Datum planes, axis, points, and LCS are veru useful for a wide range of applications. However, they are implemented for the PartDesign worbench. As such, creating them with the toolbar buttons automatically create a Body when one isn’t active.

For example, the Assembly container accepts datum elements and they can be used. However, there are serious issues: 

1. `PartDesign_Point`, `PartDesign_Line`, and `PartDesign_Plane` are not available from the Assembly worbench.
2. It is necessary to create a body to create datum elements. Only then they can be dragged in the assembly container.
3. When editing a datum plane at the assembly level to position it relative to base planes, its size becomes infinite and it is impossible to determine if it worked.
4. When creating a joint, selecting a datum inside a part or body shows that the JCS symbol is always at the center of the part or body and not on the plane or along the line. Surprisingly, it works for sketches (see #11606).

It would be better if datum elements were implemented as more generic tools so that they could be integrated better by the workbenches that could make use of them.

### Full version info

```shell
OS: Ubuntu 23.04 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35249 (Git) AppImage
Build type: Release
Branch: main
Hash: 94ca51b7799b2ac60a2a56d7e6e753bb97a73671
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * Render 2023.8.18
  * OpenDark 2023.12.1
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment]
The problem reported in #12106 also exist for `PartDesign_Point`, `PartDesign_Line`, `PartDesign_Plane`, and `PartDesign_CoordinateSystem`. They could be more generic and available in the assembly workbench.

**Comment by Syres916** [comment]
> it is necessary to create a body to create datum elements. Only then they can be dragged in the assembly container.

I genuinely don't know where this is coming from:

```
App.ActiveDocument.addObject('PartDesign::Point','PartDatumPoint')

App.ActiveDocument.addObject('PartDesign::Line','PartDatumLine')

App.ActiveDocument.addObject('PartDesign::Plane','PartDatumPlane')
```

all the above works without any body existing.

**Comment by pierreporte** [comment]
@Syres916 Try to do it with the GUI. Like sketches created with `PartDesign_NewSketch`, a body appears to contain datum elements. It may be because the PartDesign workbench needs to be opened. They can be dragged in an assembly container and re-attached to assembly origin planes but you can’t exactly call this a streamlined workflow.

**Comment by pierreporte** [comment]
Interesting forum post about this: https://forum.freecad.org/viewtopic.php?p=742525#p742525

**Comment by Zolko-123** [comment]
> First, `PartDesign_Point`, `PartDesign_Line`, and `PartDesign_Plane` are not available from the Assembly worbench

Don't worry, Ondsel will copy that from Assembly4 too. Alternatively, you could simply use Assembly4 : select a container and click on "_Insert Datum_" and HOP! the datum is created inside the container (Body, Part or Assembly)

**Comment by maxwxyz** [comment]
ad 4: https://github.com/FreeCAD/FreeCAD/issues/12446

**Comment by pierreporte** [comment]
@maxwxyz this is related to the following complain at Brussels this year:  “Reference objects such as datum planes, axes lines and axis systems should be available globally to all workbenches.”

**Comment by maxwxyz** [comment]
Could this be merged into: https://github.com/FreeCAD/FreeCAD/issues/12584

**Comment by pierreporte** [comment]
I don’t think so. #12584 is about appearance of planes and interaction with them. This one is about creating them outside of PartDesign. What can be done though is extending #11607 to take other workbenches into account.

**Comment by pierreporte** [comment]
@maxwxyz @PaddleStroke
