### ISSUE TITLE
[Problem] PartDesign features are ejected from part when moving sketch with external geometry

### ISSUE THREAD

**Issue by Anthony-Gaudino** [FreeCAD/FreeCAD#11662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If I have two PartDesign parts **A** and **B**, if on **A** I have different features and one sketch which contain external geometry referencing some edge from **A**, if I try moving the sketch to part **B** all features of **A** are moved to root.
<img width="185" alt="Screenshot 2023-12-05 at 19 39 51" src="https://github.com/FreeCAD/FreeCAD/assets/2439728/eba40d66-7c18-4a9b-9bbe-ee5cfaea3dfe">

Minimal example: [bug.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/13572151/bug.FCStd.zip)
Try moving `Sketch001` to `Body001`

### Full version info

```shell
OS: macOS 13.5.2
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * MeshRemodel 1.8919.0
  * ThreadProfile 1.89.0
  * Launcher
  * InventorLoader 1.4.0
  * Render 2023.8.18
  * Silk 0.1.5
  * Defeaturing 1.2.1
  * A2plus 0.4.61
  * Manipulator 1.5.0
  * fasteners 0.4.70
  * lattice2 1.0.0
  * sheetmetal 0.3.1
  * toSketch 1.0.1
  * Curves 0.6.14
  * Assembly4 0.50.4
  * Assembly3 0.12.0
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This has already been fixed.

**Comment by M4xTheMan** [comment]
Before reporting a potential big, please try to reproduce it using the latest Dev version.
