### ISSUE TITLE
[Problem] PartDesign_hole inconsistency with a grid of circles

### ISSUE THREAD

**Issue by aavogt** [FreeCAD/FreeCAD#11672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I use the hole tool with a sketch containing a 4x4 grid of circles. One hole is blocked with an extra face.

### Full version info

```shell
The copy to clipboard button does not affect either selection/clipboard. See the screenshot.
```

### Subproject(s) affected?

None

### Anything else?

![image](https://github.com/FreeCAD/FreeCAD/assets/93006/17a71b0f-ac78-46d3-a922-8cfcd506e81f)
http://aavogt.github.io/hole_bug.FCStd

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
@aavogt it is no wonder it produces an additional face, excluding the external geometry circle, there are 17 geometric circles with two on the same location where the 'error' is being shown, purely a user error IMHO. Maybe the code could be enhanced to highlight the error to the user.
