### ISSUE TITLE
[Problem] Some labels use hardcoded colors making them illegible

### ISSUE THREAD

**Issue by Beep6581** [FreeCAD/FreeCAD#11698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Some labels seem to use hard-coded colors, making them difficult or impossible to see depending on the color scheme (style sheet).

![screenshot_20231210_163203](https://github.com/FreeCAD/FreeCAD/assets/5844619/bbc720cc-48c4-46cd-ab40-54aa69a226ff)

This "DoF(s)" label is very difficult to see in most dark stylesheets. The example screenshot uses the "Behave-dark" style sheet.

The color should not be hard-coded but theme dependent.

### Full version info

```shell
[code]
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.6, Qt 5.15.11, Coin 4.0.1, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.71
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
This has been fixed in the 0.22dev builds https://github.com/FreeCAD/FreeCAD/commit/c6eb321f5403c8b50818d766f263515ea0e7a449 so you can manually overwrite your copy in 0.21.2

**Comment by Beep6581** [comment]
I assumed it was hard-coded in the Qt source code based on the familiar blue color, but that commit shows it can just be styled - good. However, it seems the fix applies only to the `Behave-dark` style?

On a related note, does Qt have something similar to Gtk's [Inspect](https://wiki.gnome.org/Projects/GTK/Inspector) tool?

**Comment by Beep6581** [comment]
btw. fix confirmed for `Behave-dark` style.

**Comment by adrianinsaval** [comment]
@MisterMakerNL is this still a problem in any of our other current stylesheets?

**Comment by luzpaz** [comment]
Thanks for the heads up beep6581

bump @MisterMakerNL

**Comment by MisterMakerNL** [comment]
It's been changed to a less full blue, although it is still blue. It's better readable
![image](https://github.com/FreeCAD/FreeCAD/assets/29804962/1d5f8c7f-4972-4c97-b2dc-baa05959bb94)
