### ISSUE TITLE
[Problem] Transparent menu background when using Light/Dark/Darker style sheets

### ISSUE THREAD

**Issue by Beep6581** [FreeCAD/FreeCAD#11700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Menu items have a transparent background when using any of the Light/Dark/Darker style sheets, making it difficult to see the menu contents.

![screenshot_20231210_213517](https://github.com/FreeCAD/FreeCAD/assets/5844619/a7caaf50-3016-4f96-8c33-a80d685178b2)
![screenshot_20231210_213546](https://github.com/FreeCAD/FreeCAD/assets/5844619/2da32f30-cca1-4233-a259-da7170b06d62)

Behave-dark, ProDark and No Style Sheet do not exhibit this problem.

![screenshot_20231210_213619](https://github.com/FreeCAD/FreeCAD/assets/5844619/519c2a29-43b2-4fa3-896e-8318b6555f6a)

Manjaro/KDE.

Using KDE global theme Breath Dark, application style Breeze.

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.6, Qt 5.15.11, Coin 4.0.1, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.71
```

**Comment by adrianinsaval** [comment]
@MisterMakerNL any clue?

**Comment by MisterMakerNL** [comment]
This was already reporter and fixed. Although I would think it should be in already fixed in 21.2. So that is a bit weird.

**Comment by adrianinsaval** [comment]
Can you link to the fix?

**Comment by maxwxyz** [comment]
is this still relevant?

**Comment by MisterMakerNL** [comment]
Since I have not heard any others complaining it should have been fixed here https://github.com/MisterMakerNL/FreeCAD_MisterMaker/commit/125406a7641452c3882b6eeddb09d1efd74b4185

**Comment by maxwxyz** [comment]
@MisterMakerNL was this merged in main?
