### ISSUE TITLE
[Problem] PartDesign: Revolution - Selection of Reference Axis not possible

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

PartDesign Revolution feature allows to select a reference axis in the viewport. The reference is selected / displayed correctly in the preview, but I cannot confirm the task dialog.
In the following example I've selected the X-Axis by clicking on Axis: Select Reference > and clicked on the X-axis in the viewport.
The dropdown menu still shows Select reference but nothing else can be selected and the X-axis is used for the preview. 
Clicking ok results in the following error. It seems to have set the selection for the preview but not for the feature itself.

![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/b065462b-3707-45c3-a49b-0f7cb933ce54)

### Full version info

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35370 (Git)
Build type: Release
Branch: main
Hash: 1066bb54ceec8f4f8376b5149253acda5677651d
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * Assembly4 0.12.6
  * Curves 0.6.8
  * Defeaturing 1.2.0
  * fasteners 0.4.56
  * OpenDark 2023.10.22
  * sheetmetal 0.2.63
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment]
I have the same problem. Whatever you select in the 3D view, the dialog appears: sketch line, datum axis, even the base axis. It only works if the axis combo box is used.

**Comment by Syres916** [comment]
@AjinkyaDahale it looks as though there has been a regression in the recent changes, up-to-date 0.21 branch works as I would expect using a DatumLine as a reference axis. Using the main brnach, if I copy the Python code into the Console, then it corrects the model for example:

```
App.ActiveDocument.getObject('Revolution').Angle = 360.000000
App.ActiveDocument.getObject('Revolution').ReferenceAxis = (App.getDocument('RevolveTest').getObject('DatumLine'), [''])
App.ActiveDocument.getObject('Revolution').Midplane = 0
App.ActiveDocument.getObject('Revolution').Reversed = 0
App.ActiveDocument.recompute()
```
But doesn't work through the Gui as it should.

**Comment by Syres916** [comment]
I'll be concentrating my efforts on this https://github.com/FreeCAD/FreeCAD/commit/2cef4cfdbe1a6b9ebf50a85c04fbe99f23cd3829

Also if I get the chance the tests for Revolution/Groove obviously need reviewing to stop this kind of error in future.

**Comment by Syres916** [comment]
@Roy-043 could I be a pain and ask that the _Bug_ label please be swapped out for _Regression_

**Comment by Syres916** [comment]
OK, I _think_ I've got to the root cause of the issue, `selectionFace` is set to `true` on starting the Revolution gui but the `Face mode` isn't in use at this time so I'm submitting a PR to add the mode to the condition. While this fixes the regression, I'm really at a loss as to the goal of the original PR so I do not know whether I'm just creating another regression elsewhere.

**Comment by AjinkyaDahale** [comment]
> OK, I _think_ I've got to the root cause of the issue, `selectionFace` is set to `true` on starting the Revolution gui but the `Face mode` isn't in use at this time so I'm submitting a PR to add the mode to the condition. While this fixes the regression, I'm really at a loss as to the goal of the original PR so I do not know whether I'm just creating another regression elsewhere.

@Syres916 I'll check this sometime this week to figure out the meaning behind this. Meanwhile, could you confirm whether or not this couls have been caused by #7193? If it can be cleanly reverted it maybe easy to find the reason. Otherwise (and if the PR didn't cause this) we will have to dig deeper.

**Comment by Syres916** [comment]
@AjinkyaDahale the regression was definitely caused by #7193 but I can't get a clean git revert to work locally.
