### ISSUE TITLE
[Problem] Sketcher: UI - Task Dialog 

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The task dialog in sketcher is displaying constraints and geometry in two lists.
The constraints icons are huge in comparison to the geometry icons and the text seems not aligned.
Also the checkboxes seem different of the two lists. I am using the OpenDark theme but this is a general issue of the dialog.
The selection highlight color in both lists is also different, also in classic theme, but only when selecting in the 3d view.

![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/fb28d2e5-568a-4e0f-9cc0-7f2829e48c90)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/63b1bd84-ed70-4cc5-a11b-fd0ba145ec37)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35407 (Git)
Build type: Release
Branch: sketcher_cursor_icons
Hash: 00aefca95bb2cca0f501e0cb5a92e75854f2a649
Python 3.11.7, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.24.9
  * CurvedShapes 1.0.5
  * Curves 0.6.16
  * Defeaturing 1.2.1
  * fasteners 0.4.74
  * FEMbyGEN 2.0.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.1
  * sheetmetal 0.3.13
  * woodworking 0.21.1.33694
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Checkboxes look the same here. I suspect that issues is related to the stylesheet.

I think the icons have (almost) the same size (15-16px), but the icons in the Elements list contain more details, and should therefore probably be bigger.

I don't see misalignment of texts.

**Comment by maxwxyz** [comment]
@obelisk79 then it seems to be in the theme?

**Comment by obelisk79** [comment]
Does the icon size change if you change theme?

**Comment by maxwxyz** [comment]
it is also a different size and highlight color with other themes:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/1102e4d7-b602-44b0-801e-7a3330bc08e4)

![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/e895c550-3975-44be-bf89-7a2a4b15b922)

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35449 (Git)
Build type: Release
Branch: main
Hash: f3fa2ba9c9b1999e5c32d3ae544481b6e17553bb
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.24.9
  * CurvedShapes 1.0.5
  * Curves 0.6.19
  * Defeaturing 1.2.1
  * fasteners 0.4.75
  * FEMbyGEN 2.0.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.3.13
  * woodworking 0.21.1.33694
```

**Comment by maxwxyz** [comment]
I'll close this as this is not a real bug but personal preference

**Comment by obelisk79** [comment]
I'd reopen this, the issue of the different styled checkboxes is definitely real. The reason some people see check boxes that look the same in a classic or no-stylesheet theme configuration is because the element list checkboxes follow the system theme. So if your OS theme is light, and you apply a dark theme the checkboxes will mismatch.
