### ISSUE TITLE
[Problem] [Sketcher] Exiting a tool with ESC sometimes exits Sketcher. 

### ISSUE THREAD

**Issue by Palmstroemen** [FreeCAD/FreeCAD#11762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

You select a constraint-tool like parallel or tangential. When you're done, you'd like to exit the tool to continue working. So you push the ESC button. But sometimes (not always) this exits and closes Sketcher. 

Maybe it's kind of too fast. ESC closes the tool - ESC is still pressed - closes Sketcher. 
Maybe after closing a tool, ESC should be released by the user at least once before closing Sketcher can be activated. So pressing ESC twice would close the tool first and close Sketcher then. But holding ESC for too long would just close the tool but not close Sketcher.

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * A2plus 0.4.60h
  * CADExchanger
  * ExtremeProDark 2.7.0
  * fasteners 0.4.54
  * lattice2 1.0.0
  * MakerWorkbench
  * pluginloader
  * RemBench
  * sheetmetal 0.2.61
  * Silk 1.0.0
  * WebTools
  * workfeature
  * workfeature-macro
[/code]
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
You can end a command with two right-clicks. There is also a preference to prevent Esc from exiting the sketch.

Closing this.
