### ISSUE TITLE
Sketcher radius constraint draws over circle arc

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD#11777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Sketcher radius constraint draws over the circle-arc it constraints. It did not do this in the past.
It’s distracting, annoying and absolutely useless.
![Screenshot_20231219_205321](https://github.com/FreeCAD/FreeCAD/assets/13178920/9deb05cb-1249-4e65-b1a9-d2dc7f54a762)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35391 +2 (Git)
Build type: Release
Branch: Meins
Hash: 576701c9356a4ffc5eadd19f6ef0015ee28b9e3a
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.15
  * Assembly4 0.50.4
  * Pyramids-and-Polyhedrons
  * sheetmetal 0.3.12
  * Silk 0.1.5
  * CurvedShapes 1.0.5
  * DynamicData 2.54.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * ExplodedAssembly
  * fasteners 0.4.72
  * Render 2023.8.18
  * A2plus
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by berberic2** [comment]
The problem seems to shows only after at least one radius-constrain as reference is added. 
[radius_constraint.FCStd.gz](https://github.com/FreeCAD/FreeCAD/files/13720181/radius_constraint.FCStd.gz)

**Comment by pierreporte** [comment]
Confirmed with the following version:
 
```
OS: Ubuntu 23.04 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35370 (Git) AppImage
Build type: Release
Branch: main
Hash: 1066bb54ceec8f4f8376b5149253acda5677651d
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * OpenDark 2023.12.1
```

It appears for all kind of dimensions, not just references dimensions.

It looks like the dimensions it attached to one of the starting point instead of the arc itself in a similar way as lines, as reported in #11603.

**Comment by berberic2** [comment]
Seems to already been fixed in 
```
Version: 0.22.0dev.35420 +2 (Git)
```
