### ISSUE TITLE
[Problem] Property view headers are useless.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#11794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/881031ab-a377-45a1-838b-f5641ef4061e)

The headers do not bring useful information as the view is self-explanatory. They just add a small clutter. Besides when used with overlay it's ugly : 

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/8a13965e-b6d1-4340-8571-09284c732721)

I propose to hide/remove them. The only issue to be solved is resizing the columns as it is currently only possible with the header.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by obelisk79** [comment]
When you do this there may also be an issue of the floating dots for the panel resize. Not just resizing the columns.

**Comment by MisterMakerNL** [comment]
Totally agree with this!
