### ISSUE TITLE
Odd filet issue causing problems in 3d print slicer

### ISSUE THREAD

**Issue by greggjaskiewicz** [FreeCAD/FreeCAD#11831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Filet is causing STL to be all mangled , confusing slicers 
<img width="450" alt="Screenshot 2023-12-25 at 13 04 25" src="https://github.com/FreeCAD/FreeCAD/assets/553583/7d58b81a-6498-452b-837e-5ccdd1fe65ee">
<img width="517" alt="Screenshot 2023-12-25 at 13 04 18" src="https://github.com/FreeCAD/FreeCAD/assets/553583/095bade4-c0e8-498e-95d8-fc445389f1ea">

Basically the last Filet operation, Filet002 is causing odd issue in STLs. It looks all good in FreeCAD. 

See attached files. 
[uszker.zip](https://github.com/FreeCAD/FreeCAD/files/13766125/uszker.zip)
Issue exists both in 0.21.1 and latest nightly build

### Full version info

```shell
[code]
OS: macOS 14.2.1
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * AnimationFreeCAD 1.0.0 (Disabled)
  * A2plus 0.4.61
  * sheetmetal 0.3.13
  * freecad_metal_workbench 0.0.1
  * Curves 0.6.19
[/code]
```

### Subproject(s) affected?

File formats

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by greggjaskiewicz** [comment]
It's actually Fillet001 , not 002

**Comment by Roy-043** [comment]
Fillet001 produces an invalid shape. I am not surprised by that. You need to revise you model. I suggest you lower the bottom of the conical shape. You can then make a fillet for tops of the beams and a separate fillet for the bottom of the conical shape. See the attached image (where only 3 edges have been filleted).

This is an [OCC](https://wiki.freecad.org/OpenCASCADE) (FreeCAD's geometry kernel) issue and not something that FreeCAD can fix. I am therefore closing this.

![odd-fillet](https://github.com/FreeCAD/FreeCAD/assets/70520633/703b407b-de41-460a-8bf6-191883567268)
