### ISSUE TITLE
[Problem]  DraftGeomUtils.is_planar is broken for wires

### ISSUE THREAD

**Issue by thwd** [FreeCAD/FreeCAD#11859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

```
wire = Draft.make_wire([App.Vector(1,2,0), App.Vector(2,3,0)])
print(DraftGeomUtils.is_planar(wire.Shape))
```
prints `False`.

### Full version info

```shell
OS: Ubuntu 23.10 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.2.
Build type: Release
Python 3.11.4, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Anything else?

Coincidentally, `Draft.make_sketch()` checks for `is_planar`. In consequence, it is currently impossible to make a sketch that has a wire in it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
Hi,
Shape is null until the object is computed.
```
>>> wire1 = Draft.make_wire([App.Vector(1,2,0), App.Vector(2,3,0)])
>>> DraftGeomUtils.is_planar(wire1.Shape)
False
>>> App.ActiveDocument.recompute()
1
>>> DraftGeomUtils.is_planar(wire1.Shape)
True
>>> 
```

Fix #11860 too.
