### ISSUE TITLE
[Feature Request] Add option to set the current project name in the window title

### ISSUE THREAD

**Issue by astrolemonade** [FreeCAD/FreeCAD#11858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hey!
I really enjoy using FreeCAD. One issue I found is that I can't really track the time I spend in the application. While I do know that adding custom telemetry in FreeCAD for users to know how much time they spent in a project I request a minimal change: add the current project name in the window title.
![image](https://github.com/FreeCAD/FreeCAD/assets/35623921/ead6d8af-2e1a-4bb5-94ff-43507b0aa0fe)
The window title can be used by other applications such as https://activitywatch.net (FOSS time tracking application) to track how much time one spent on a project:
![image](https://github.com/FreeCAD/FreeCAD/assets/35623921/d5d605bb-3e9e-4bd1-8cd4-268c3f9dc254)
It could be something like:
`FreeCAD 0.22.0dev ~ /home/user/something/visionfive2-case.FCStd`

### Full version info

```shell
OS: Solus 4.5 Resilience (Budgie:GNOME/budgie-desktop)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35477 (Git)
Build type: Release
Branch: main
Hash: 1a59b5846caaf903e23917dd1f4081fd698ab2d2
Python 3.10.13, Qt 5.15.11, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * IconThemes
  * Render 2023.8.18
  * Assembly3 0.12.0
  * fasteners 0.4.75
  * OpenDark 2023.12.17
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Would be great if the current window name of the active document could be set for the main window, including the `*`indicator if you have unsaved changes.
Here is what I mean when using tiled or cascaded document windows:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/0a7b4546-b36a-49e8-80b9-ce25d3222321)


@kadet1090 do you know how to do this?

**Comment by maxwxyz** [comment]
I've found this discussion of the same change in Blender: https://projects.blender.org/blender/blender/pulls/111998
Takeaways: 
- display unsaved changes indicator "*" as first character to see it in the taskbar when hovering
- display the document name after that
- display the file path in brackets after the document name
- display " - FreeCAD <<version>>" at the end.

So for an unsaved document it would show:
`* testdoc [C:\\Users\\User1\testdoc.FCStd] - FreeCAD 0.22.0dev`

**Comment by adrianinsaval** [comment]
I usually see apps using a long dash separator —
