### ISSUE TITLE
[Problem] DraftGeomUtils.are_coplanar broken for wires

### ISSUE THREAD

**Issue by thwd** [FreeCAD/FreeCAD#11860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

```
wire1 = Draft.make_wire([App.Vector(1,2,0), App.Vector(2,3,0)])
wire2 = Draft.make_wire([App.Vector(3,4,0), App.Vector(4,5,0)])
print(DraftGeomUtils.are_coplanar(wire1.Shape, wire2.Shape))
```
prints `False`.

### Full version info

```shell
OS: Ubuntu 23.10 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.2.
Build type: Release
Python 3.11.4, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Anything else?

Coincidentally, `Draft.make_sketch()` checks for `are_coplanar`. In consequence, it is currently impossible to make a sketch that has a wire in it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Please consult the [FreeCAD forum](https://forum.freecad.org/) before creating future GitHub issues.
