### ISSUE TITLE
[Problem] During C++ DXF import, objects within a BLOCK are merged to a single object

### ISSUE THREAD

**Issue by kpemartin** [FreeCAD/FreeCAD#11872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

During DXF import, objects such as lines and arcs within a BLOCK are merged into a single shape, even if the import options are selected to not merge shapes. This perforce loses their individual colours and line types.

Also, related to this, the resulting compound object is coloured only based on the layer and colour of the INSERT entity, not those of the individual entities within the block.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35389 +97 (Git)
Build type: Debug
Branch: Issue11394
Hash: fcbd1105d64a945f242b8356fd72119f388b4747
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Canada (en_CA)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
#11873
