### ISSUE TITLE
[Problem] Preference not working on 0.21.1 Italian Mac Version

### ISSUE THREAD

**Issue by andreaderoni** [FreeCAD/FreeCAD#11882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Select:
Feecad menu iten on menu bar
Then Select:

Preference 

see it points to 4 sub items:
Predefinito
Trasforma
Taglio
Colore

No "normal" preference window appears

### Full version info

```shell
[code]
OS: macOS 10.15
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@andreaderoni can you test on the latest development release ? https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
