### ISSUE TITLE
[Problem] PartDesign default "shape color" or random color doesn't work

### ISSUE THREAD

**Issue by pgilfernandez** [FreeCAD/FreeCAD#11903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When you set a "shape color" or check "random color" under **Preferences > Part/Part Design > Shape appearance > Default shape view properties**, it is not applied when you create a new body.
Restarting FreeCAD doesn't work so I guess it's just a bug...

Cheers

### Full version info

```shell
OS: macOS 12.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35485 (Git)
Build type: Release
Branch: main
Hash: a662fbb2ff267fb8dd56fcc3d1ec55a5968b7f5a
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * PieMenu 1.2.7
  * PabloAccents 1.0.0
  * ProDarkThemePreferencePack 1.0.0
  * Nodes 0.1.36
  * Dracula 0.0.5
  * Silk 0.1.5
  * PabloModern 1.0.0
  * SelectorToolbar
  * ExtremeProDark 2.9.0
  * MeshRemodel.backup1701781077.769602 1.8919.0 (Disabled)
```
```


### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This regression has recently been fixed:
https://github.com/FreeCAD/FreeCAD/pull/11866
