### ISSUE TITLE
[Problem] Auto-constraint operation crashes when interrupted by undo

### ISSUE THREAD

**Issue by chennes** [FreeCAD/FreeCAD#11904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When inserting an auto-constraint, FreeCAD will crash if the operation is interrupted by the user attempting to undo.

To reproduce:
1. Create a sketch
2. Insert two lines
3. Select the lines and click the auto constraint button
4. Without completing the auto-constraint insertion, use Ctrl-Z to undo
5. Move the mouse over the 3D view

Expected result:
The auto-constraint insertion is cancelled, and FreeCAD continues running.

Actual result:
Crash

### Full version info

```shell
OS: macOS 13.3.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34836 (Git)
Build type: Release
Branch: main
Hash: 862eef57eb4aa042f87d9f19dc768a017b17dae6
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.5.3
Locale: English/United States (en_US)
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
@PaddleStroke can you take a look at this when you have a minute?

**Comment by PaddleStroke** [comment]
What do you mean by auto-constraint button? Do you talk about sketcher_dimension tool? If so I cannot reproduce the bug. Can you make a video please?

**Comment by chennes** [comment]
Sure - in the attached video, I hit Ctrl-Z at about 16 seconds in, without clicking to insert the constraint.

https://github.com/FreeCAD/FreeCAD/assets/216920/f4e1b7a6-06d0-47c3-88fc-70886546ed7f
