### ISSUE TITLE
[Problem] Non-construction points are hard to distinguish

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#11919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This issue is about points seen from inside the sketch and from outside the sketch

### Inside the sketch

In the sketcher WB, construction points are red and normal points are white. When they are fully constrained, they both turn to a lighter color with a very low contrast which makes them hard to distinguish, even more if you are red/green colorblind. See the screenshot below:

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/fac6461d-3423-4c0e-8a78-e3a06dd4607e)

With dimensions not masked, it is even harder to see the difference:

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/287ff60b-26ad-4d72-9b6a-60394a93b3a9)

### Outside the sketch

From outside the sketch, points appear way smaller than they are in the sketch, even relatively to the lines. (Construction points that are extremities of shapes are like this as well but it is not problematic.) As you can see in the screenshots below, normal points are visible when there is only the sketch on screen, but they are harder to see when there is something behind and this isn’t a very complex part.

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/96f734eb-aebf-477d-8100-b7c0d28646d9)

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/dde9dcd3-8156-43df-bc9f-1dbb08b82f18)

### Proposed solution

Normal points could have a different shape and be larger. I propose a cross: + or ×.

### Full version info

```shell
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35510 (Git) AppImage
Build type: Release
Branch: main
Hash: da05f7c8e8b25ff783cc6c4eb3b73b640f134519
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * OpenDark 2023.12.1
```

### Subproject(s) affected?

Sketcher

### Anything else?

Catia screenshots. Note that points are displayed as a + in sketches and as a × in the 3D view. It would be best for FreeCAD to keep the same one in all situations.

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/e54da197-ad29-4a9a-adf8-0aeae4707879)

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/ed177402-49ee-4df4-83e0-73dd39394462)

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/e820584a-0265-461e-9e8b-105355e9083d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
I'm always a little reticent to just adopt another commercial product's design features, what about giving users the option in Preferences to change (for now) just the Sketcher symbols for geometry Point and what I believe are called 'handles'  (the ends of lines, curves etc). To give you an idea of what symbols are currently available, see https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/Inventor/MarkerBitmaps.cpp#L60-L1252
Then if this is found to be acceptable then the main 3D View could have Vertex/Point option for the symbol, the size of which is controlled by a different parameter to `MarkerSize` used in Sketcher, it's called `DefaultShapeVertexSize`

**Comment by pierreporte** [comment]
Catia was presented as a real world example only. Of course the users should be able to customize it. Catia does as well.

**Comment by adrianinsaval** [comment]
@PaddleStroke after dashed construction lines are done this could be a nice follow up improvement.

**Comment by PaddleStroke** [comment]
In edit mode I'm against introducing yet another differentiating concept.

White points are well explanatory and easy to differentiate. The only issue is when points are constraints the colors are very similar.
To me the solution is to drop the red color of points and use blue as other construction geometries. This way even constrained the blue color is significantly different. And it makes more sense to use blue than red which is the constraint color.

Now regarding outside the edit mode, either making points bigger or using X symbols seems fine to me.

**Comment by adrianinsaval** [comment]
I'm ok with going in that direction but then we're falling on the same trap of using only color to differentiate, which was the whole reason why we wanted dashed construction lines.

**Comment by pierreporte** [comment]
I agree with @adrianinsaval. If we are going to code status by color and type by pattern, then the points should follow this as well (with the semi-exception of external geometry). Blue points are better than red points but the light blue of constrained construction geometry is still quite close to the light green of fully constrained points.

Also, when it will be possible to automatically constrain to center points, it could be useful to show a temporary point when hovering nearby and it would benefit in having a different style (hollow circle for example), which means implementing points styles.

**Comment by FlachyJoe** [comment]
@pierreporte :+1: 
What about drawing point as cross or dot or 45° square or something else, depending on its status ?

**Comment by pierreporte** [comment]
@FlachyJoe What do you mean exactly? Do you want to change the shape when a non-construction point is constrained, while keeping construction points round? I think that the best thing for point is:

* construction points are round,
* non-construction points are a cross,
* unconstrained points are white,
* constrained points are green,
* shape does not change with degrees of freedom.

**Comment by pierreporte** [comment]
The datum points are displayed as yellow diamonds. Since they appear to be functionally equivalent to sketch points (construction or not from outside the sketch), they could all have a similar style (or exactly the same, as Catia). Then the proposition of @FlachyJoe could make sense: datum points as ×, normal sketch points as +.

**Comment by pierreporte** [comment]
@PaddleStroke what’s your current opinion on this?

Proposed default for sketches and 3D view: construction points stay round, geometry points are diamond (slightly larger) like datum points.

**Comment by pierreporte** [comment]
This issue is not resolved, as explained in my comments in #13098. It is still very hard to distinguish the nature of two fully-constrained points, and normal points remain very small from outside the sketch. I maintain that a different shape is necessary.

**Comment by pierreporte** [comment]
Here is the proposed solution:

* Inside edit mode:
  * construction points are round like today,
  * normal points have a different shape,
  * unconstrained construction geometry is blue, including construction points,
  * constrained construction geometry is green, including construction points,
  * unconstrained normal geometry is white, including normal points,
  * constrained normal geometry is green, including normal points,
  * external construction points have the same shape as other construction point,
  * external normal points have the same shape as other normal points.
* Outside edit mode:
  * lines are the same as today,
  * construction points, including external points, between segments are the same as today,
  * normal points, including external points, have a different shape,
  * color is white for everything like today.

**Comment by maxwxyz** [comment]
and how to indicate coincident points, e.g. edges of a rectangle? What color or shape is a coincident point of a construction line and a circle midpoint?

**Comment by pierreporte** [comment]
As said in #13098, I think that allowing points to belong to several geometric entities (lines, circles, etc.) will greatly reduce the need of coincident points. This way, rectangles, polylines, slots, and other custom shapes can have normal vertex. A rectangle would then have 4 points instead of 8. Likewise, extending to geometric entities that are going to have an intersection wouldn’t make a coincident constraint but make the intersection a common point of the two (this feature does not exist yet, it would be similar to `Sketcher_Extend`) The coincidence constraint would be used for everything else: a circle center on a rectangle vertex for example. In this situation, there would be an icon near the point like other constraints. This is likely linked to #11920.

This would create the need to have new tools: one to split a common point into two coincident points, one for the inverse operation.

Midpoints constraints could have an icon of their own. Currently it’s the symmetry icon. A new point style could be useful as a helper (see #11414). A hollow circle could appear when the zone around a mid-point is hovered. When a point is created there, it would be shown accordingly to the list above.

**Comment by pierreporte** [comment]
@obelisk79 What is your opinion on this?
