### ISSUE TITLE
[Problem] DraftCloning a mesh silently fails

### ISSUE THREAD

**Issue by Scafir** [FreeCAD/FreeCAD#11923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Draft mode, cloning a mesh object correctly creates a clone in the Model list, but does not produce a object that can be seen in 3D view.
I would expect it to either create a proper clone that can be visualized, or to throw an error like "Meshes cannot be cloned". 
Please note that I am quite new to the project: I hope that this issue is valid and not an oversight due to my limited knowledge.

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (GNOME/gnome-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Draft

### Anything else?

It seems that this issues has been raised two years ago on reddit: https://www.reddit.com/r/FreeCAD/comments/pz4q24/clone_doesnt_show_up/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Indeed this is a valid point
