### ISSUE TITLE
[Problem] [Feature] VSCode-like command palette

### ISSUE THREAD

**Issue by anandijain** [FreeCAD/FreeCAD#11949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am learning CAD/FreeCAD as a total beginner and I am very appreciative of how much amazing work has gone into FreeCAD. 

One thing that frustrates me with picking up software tools is the lack of a tool to search through commands, like VSCode has with the https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

I know that this is a very big ask, but I think it would make it easier to learn since it minimizes needing to look through menus and icons.

Thank you

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment]
This is a duplicate of #8290.

**Comment by anandijain** [comment]
thanks
