### ISSUE TITLE
[Problem] PartDesign Mirrored should mirror everything given an empty .Originals

### ISSUE THREAD

**Issue by aavogt** [FreeCAD/FreeCAD#11947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Starting with the [box_pad_pocket.zip](https://github.com/FreeCAD/FreeCAD/files/13890630/box_pad_pocket.zip), the result depends on the order of the selection.

```
>>> # Gui.Selection.clearSelection()
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Box.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pad.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pocket.')
>>> ### Begin command PartDesign_Mirrored
```
![image](https://github.com/FreeCAD/FreeCAD/assets/93006/00af700e-f262-4b89-8833-b314eba51faf)

```
>>> # Gui.Selection.clearSelection()
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pocket.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Box.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pad.')
>>> ### Begin command PartDesign_Mirrored
```

![image](https://github.com/FreeCAD/FreeCAD/assets/93006/0eab25a7-84fa-46c1-b500-6c95544167a1)

When the PartDesign_Mirrored Originals attribute is empty, it adds nothing due to [this](https://github.com/FreeCAD/FreeCAD/blob/d3049deaa9786817b829733fff1dddcf02675b06/src/Mod/PartDesign/App/FeatureTransformed.cpp#L169) (?). When Originals happens to be empty, Mirrored should instead behave as if `obj.Originals = obj.OutList[:-1][1:]` ie `obj.Originals = [<PartDesign::AdditiveBox>, <PartDesign::Pad>, <PartDesign::Pocket>]` for the box_pad_pocket example. This would be consistent with the other tools that have no Originals and transform the result of the prior tools. #8900 is due to `.Originals` being Fillet001 instead of everything (` [Pad ... Fillet001]`). With other PartDesign tools, "Pocket" refers to the result whereas for Originals, "Pocket" is the operation. If an empty `obj.Originals` was interpreted as `obj.OutList[:-1][1:]`, Mirrored would usually be easier to understand and use.

![Screenshot from 2024-01-10 12-50-43](https://github.com/FreeCAD/FreeCAD/assets/93006/0ae22a43-7b97-4bb6-b20c-44b7c498a254)

### Full version info

```shell
See screenshot above because the "Copy to Clipboard" button doesn't work.
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
related to #8439
