### ISSUE TITLE
[Problem] Some of the checkboxes in Tasks pane inside Sketch editing view are not scaled properly

### ISSUE THREAD

**Issue by grudir** [FreeCAD/FreeCAD#11942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The checkboxes in Constraints and Elements lists in Tasks pane inside Sketch editing view are not displayed properly when using Windows Display scale percentage different from 100%. Additionally the arrows used to expand and collapse the sections inside the Tasks pane as well as the icons in Edit > Preferences are not displayed properly.

Pre-requisites:
- Right click Windows Desktop and choose Display Settings. Set Scale to 125%.

Steps to reproduce:
1. Start FreeCAD 0.21.1.
2. Click File > New.
3. Click Part Design > Create Body.
4. Click Sketch > Create Sketch.
5. Choose XY-plane (and click OK).
6. Draw a rectangle.

Actual result:
The checkboxes in Constraints and Elements lists inside Tasks pane are a bit jagged (probably due to scaling).

Expected result:
The checkboxes in Constraints and Elements lists inside Tasks pane are clear similar to the checkbox on the left of the Filters button.

Example screenshot:
![image](https://github.com/FreeCAD/FreeCAD/assets/24936746/84407b26-f412-40be-9727-88405d58e036)

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Bulgarian/Bulgaria (bg_BG)
Installed mods: 
  * Assembly4 0.50.6
  * CurvedShapes 1.0.5
  * fasteners 0.4.75
  * freecad.gears 1.0.0
  * InventorLoader 1.4.0
  * Manipulator 1.5.5
  * Pyramids-and-Polyhedrons
  * QuickMeasure 2022.10.28
  * Render 2023.8.18
  * workfeature
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Related?: #11766

**Comment by grudir** [comment]
They are in similar areas, but the issues are separate. This one is related to Windows text scaling feature that is used for higher density displays (for example 27" display with 2560 x 1440 or 4K resolution).

**Comment by grudir** [comment]
Thank you for the fix @kadet1090! I checked against weekly build 36082 and the checkboxes are drawn as expected.
