### ISSUE TITLE
[Problem] TechDraw: Unknown escape sequence in QGISVGTemplate.cpp

### ISSUE THREAD

**Issue by chennes** [FreeCAD/FreeCAD#11959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

During compilation, the compiler issues the following warning:
```
src/Mod/TechDraw/Gui/QGISVGTemplate.cpp:200:79: warning: unknown escape sequence '\.' [-Wunknown-escape-sequence]
            QRegularExpression rxFontSize(QString::fromUtf8("font-size:([0-9]*\.?[0-9]*)px;"));
```
It's not immediately obvious to me if that is intended to be a literal backslash, or is a mistaken escape character.

### Full version info

```shell
Testing compilation with 158ef7e
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
missing a '\'.  should be fixed by 3ba0c3d795
