### ISSUE TITLE
[Problem] Text in navigation tooltips is missing for some themes

### ISSUE THREAD

**Issue by Rexbas** [FreeCAD/FreeCAD#11964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Compare the screenshots below, in the light modern theme the tooltip shows some text above the mouse icons like "Rotate". In most other themes there is no text and looks like the screenshot made with the darker theme. I think someone who knows a lot about stylesheets/themes should take a look and make sure the text is visible in all themes.

Light modern theme:
![image](https://github.com/FreeCAD/FreeCAD/assets/14298143/1972d9a5-cf1c-49ae-8939-e6b64aa1643f)

Darker theme:
![Screenshot_20240112_222322](https://github.com/FreeCAD/FreeCAD/assets/14298143/4dc598dd-619d-4711-a5c5-16bf9cb3820a)

### Full version info

```shell
OS: KDE neon 5.27 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35033 (Git)
Build type: Release
Branch: main
Hash: 8b6d133c26857363bedec2ba31bacbecb2a9bf89
Python 3.11.6, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

**Comment by Syres916** [comment]
I'm putting together the same fix for 0.21 branch but there's a lot more stylesheets!!
