### ISSUE TITLE
[Feature Request] Sketcher: Add helpers to arcs for angle and distance constraints rendering

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Following https://github.com/FreeCAD/FreeCAD/pull/11507 with respective PR https://github.com/FreeCAD/FreeCAD/pull/11926 to add helpers in Sketcher WB for radius and line angle, additional helpers for arcs would be useful:
- arc to other geometry: distance
- arc: angle

current implementation:
![296455565-5f3c72d8-8306-4ffd-a3f1-6adfb8242893](https://github.com/FreeCAD/FreeCAD/assets/6246609/5e905155-6531-4d0c-b2f4-92ddbc41707b)

New issue from:
https://github.com/FreeCAD/FreeCAD/pull/11926#issuecomment-1890750085

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Doesn't [Sketcher_ArcOverlay ](https://wiki.freecad.org/Sketcher_ArcOverlay) already answer part of this feature request?

**Comment by maxwxyz** [comment]
only some part
