### ISSUE TITLE
3MF export to Prusa with clone = open edge warnings on clone

### ISSUE THREAD

**Issue by ecosky** [FreeCAD/FreeCAD#11985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a scene that has a fairly simple part and a clone of that part.
I select the "Part" object containing both and export it with 3MF, and import into Prusa slicer.

The original object imports fine, however the clone (bottom left) has warnings about open edges.

I don't think this issue is specifically related to clones as I have previously seen this happen with another objects built with a simple rectangular sketch, pad, thickness and pocket directives (very similar to the "Simple Part" in the included scene). When I use Prusa's mesh correction feature, it fixes it (so far) but I'd have expected the clone to export the same way as the original.

This feels like an issue with the 3MF exporter. Importing the same parts that were exported with STL produces objects without this error.

Note the attached project is a slightly simplified version of the one in the screenshots, and produces the same problem.

[OpenEdgeBug.zip](https://github.com/FreeCAD/FreeCAD/files/13932704/OpenEdgeBug.zip)

Forum thread: https://forum.freecad.org/viewtopic.php?p=732643#p732643

The FreeCAD setup:
![FreeCADConfig](https://github.com/FreeCAD/FreeCAD/assets/8033250/8149e1b2-4aa1-42e5-b6d7-f5adbdf73d6e)

Import of the 3MF with edge warnings on the clone:
![OpenEdgeWarning](https://github.com/FreeCAD/FreeCAD/assets/8033250/aebad00a-95fd-4049-bc2e-37c885462864)

Here's a screenshot of the STL import, which has no edge warnings:
![NoWarningSTL](https://github.com/FreeCAD/FreeCAD/assets/8033250/05fb5f60-bfec-4fba-8d86-8d300db1ccc4)

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35554 (Git)
Build type: Release
Branch: main
Hash: 8e2ab9f76888ac4da971f9d5069cec7bcc2b572f
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * Assembly4 0.50.6
  * Curves 0.6.21
  * fasteners 0.4.75
  * OpenDark 2023.12.17
  * parts_library
  * Pyramids-and-Polyhedrons
  * woodworking 0.21.1.33694
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
https://forum.freecad.org/viewtopic.php?p=738731#p738731
