### ISSUE TITLE
[Problem] V0.22 scroll issue when switching pages in the Preferences Editor

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#11981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you switch between two scrollable pages in the Preferences Editor and you have scrolled to the bottom of the 1st page, the 2nd page is opened in a scrolled down state. This is confusing IMO.

Expected behavior: New pages should be opened scrolled to the top.

@kadet1090 Is this something you can look at?

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35554 (Git)
Build type: Release
Branch: main
Hash: 8e2ab9f76888ac4da971f9d5069cec7bcc2b572f
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kadet1090** [comment]
Sure thing, should be fixed in linked PR.
