### ISSUE TITLE
[Problem] Part transparency of parts ignored in views

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#11988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a window assembly where the glass panels are made transparent by setting the Object style > Transparency property to 85, which works as expected in the 3D view.

However, when I add that view to a TechDraw page, the transparency value seems to be ignored and the glass appears as opaque:

![Captura de pantalla de 2024-01-10 12-59-54](https://github.com/FreeCAD/FreeCAD/assets/148809153/ae33e453-93ac-4f5d-9e66-eb3bd06e1686)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35578 (Git) Snap 895
Build type: Release
Branch: main
Hash: ce1a43ed2cdc3e7688feecfedd49df26e4234043
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * BIM 2021.12.0
  * ExplodedAssembly
  * Assembly4 0.50.6
```

### Subproject(s) affected?

Techdraw

### Anything else?

[File to reproduce](https://www.dropbox.com/scl/fi/kgf77zkrcos0hdp1q29ho/Exploded_transparency.FCStd?rlkey=a35tgau31k91coa8cam4xpe4x&dl=1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
TechDraw does not consider the View properties of an object. As a workaround you can select the edges of the transparent object, create a [PartDesign_SubShapeBinder](PartDesign_SubShapeBinder) and use that for the view.

**Comment by Roy-043** [comment]
I don't think the current behavior should change. Transparency is also use to help with modeling. It need not mean the object is actually transparent.

@WandererFan Should this be closed?

**Comment by furgo16** [comment]
Thanks for looking into this and for offering a workaround, really appreciated.

> I don't think the current behavior should change. Transparency is also use to help with modeling.

At the point of modeling though, if a non-transparent object is made transparent, would that not be a temporary measure to help modeling and thus not necessarily need to be transferred to the drawing? That is, before a PDF with the drawing is exported, I would imagine the designer would set transparency of non-transparent objects back to 0.

Or is it customary to not represent transparency in 2D drawings and for glass to be shown as opaque?

**Comment by Roy-043** [comment]
> Or is it customary to not represent transparency in 2D drawings and for glass to be shown as opaque?

I don't know.

**Comment by luzpaz** [comment]
@WandererFan would you mind weighing-in on this issue ?
