### ISSUE TITLE
[Problem] sketcher: radius arc helpers not drawn correctly in all situation

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/84f5889c-b98a-4789-bb0a-b8cb41182b2f)

Discussed here https://forum.freecad.org/viewtopic.php?t=84319
if startpoint is before 0deg then it does this.
Working on it

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
can this be combined to fix https://github.com/FreeCAD/FreeCAD/issues/11976 or is this separate?

**Comment by PaddleStroke** [comment]
I will check if I can solve 11976 at the same time
