### ISSUE TITLE
Treeview doesn't work if not in combo view mode (0.22dev)

### ISSUE THREAD

**Issue by thpqx** [FreeCAD/FreeCAD#12043]
Hi,

The treview doesn't show anything when I change the tree view mode from "combo view" to "tree view and property view".
(version : FreeCAD_weekly-builds-35510-2024-01-05-conda-Windows-x86_64-py310)
![Freeecad_0-22_treeview](https://github.com/FreeCAD/FreeCAD-Bundle/assets/146922388/92d17a51-bc66-4a82-b745-faf8b94c4b2b)

Is this a bug a just me doing something wrong?

Thanks.

**Comment by adrianinsaval** [comment]
@wwmayer

**Comment by wwmayer** [comment]
This creates a new TreeWidget instance and destroys the old one. The new instance isn't aware of existing documents and that's why it's empty.
