### ISSUE TITLE
[Feature Request] PD: add a Passthrough boolean property to allow to disable a feature

### ISSUE THREAD

**Issue by FlachyJoe** [FreeCAD/FreeCAD#12073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

We currently can't disable a feature without remove it.
I propose to add a Passthrough boolean property: when true the feature Base shape is copied as the result of the operation, when false the feature compute its own result.

### Full version info

```shell
OS: Debian GNU/Linux trixie/sid (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35649 (Git)
Build type: Release
Branch: main
Hash: 35e09e233c4fadb6194c82164ece25d5043d23fe
Python 3.11.7, Qt 5.15.10, Coin 4.0.2, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
@realthunder's Link Daily calls it _Surpress_ and as a Blender user it would be called _Mute_

**Comment by kadet1090** [comment]
The RT's branch as mentioned does it - but we probably should wait for the TNP mitigation to implement such features as it would cause many problems without it, rendering it very hard to use and error prone. If the mitigation would not be on the way already I'd say that the proposed solution is quite good as this would UX-wise quite hidden option and hence used only by advanced users. However assuming that the TNP fix would be merged soon we can probably wait for it and then implement this.

**Comment by FlachyJoe** [comment]
I made a draft PR.

@Syres916 the name I propose come from audio I think. It will be easy to change it.

@hkienle zero diameter circle is certainly harder to implement because of constraints which can reference the circle.

@kadet1090 I don't know how the TNP fix will change the feature internals. Will my code still be usable?

**Comment by kadet1090** [comment]
> Will my code still be usable?

Sure, simply we should not expose it to users in the UI to be easily accessible and cause confusion with braking models due to naming issues.

PR looks good, I'd however name this "Surpress" as this is how LinkStage so we don't cause more confusion for users. "Passthrough" is also quite technical term based on how features works, and users probably don't want to "Passtrough" but "Temporarily disable" some feature like hole for example

**Comment by adrianinsaval** [comment]
I agree passthrough seems like a terrible name for this. +1 on Supress

**Comment by FlachyJoe** [comment]
I though _Suppress_ was a synonym of _Delete_ or _Remove_. It's not what this property do. And shouldn't the property's name be a state and not a verb?
Isn't _Disabled_ better?

**Comment by hkienle** [comment]
Or `Suppressed` then?

I imagine this functionality will become even more useful when PD will allow multiple solids, otherwise it will be probably pretty easy to break a model and pretty hard to debug what is going on.

**Comment by FlachyJoe** [comment]
Can also be _Avoided_ or _Shorted_.

> pretty hard to debug what is going on

GUI will have to show this state in the tree.

**Comment by Syres916** [comment]
Surpressed similar:
censor
redact
keep secret
conceal
hide
keep hidden
hush up

**Comment by kadet1090** [comment]
So, F360 calls it "Suppress", Inventor calls it "Suppress", OnShape calls it "Suppress", LinkStage calls it "Suppress".

Let's not reinvent the wheel and call it like it is in other popular CAD packages and in existing fork of FreeCAD.

**Comment by FlachyJoe** [comment]
Ok, let's go for _Suppressed_ for the property and so the menu action would be _Suppress_.

**Comment by hkienle** [comment]
> GUI will have to show this state in the tree.
Meaning a new overlay icon!? https://wiki.freecad.org/Tree_view#Overlay_icons

**Comment by FlachyJoe** [comment]
> Meaning a new overlay icon!? 

I'm afraid yes :sob: unless we find another way.

**Comment by kadet1090** [comment]
Making them semi-transparent should also work fine

**Comment by FlachyJoe** [comment]
> Making them semi-transparent should also work fine

Isn't it hard to distinguish to greyed hidden items?

**Comment by kadet1090** [comment]
Yes it may, and it may cause contrast issues, crossing items out looks nice and should be indeed quite obvious.
