### ISSUE TITLE
Three lines 

### ISSUE THREAD

**Issue by yukihundo** [FreeCAD/FreeCAD#12150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

[hen.zip](https://github.com/FreeCAD/FreeCAD/files/14072285/hen.zip)
![nagasa](https://github.com/FreeCAD/FreeCAD/assets/155275392/5537710c-3a75-4ff4-b36e-36254816fdef)
Set diameter to 30. Pocket: Resulting shape is not a solid.(直径を30にしてOKして、閉じると、Pocket: Resulting shape is not a solidになります。)
![3lines](https://github.com/FreeCAD/FreeCAD/assets/155275392/9ff561ae-2537-4857-ad07-f2e0e6a021fc)
Three lines no error.
Bug?  I think it would be good to have some warning in advance.(バクだろうか?　事前におかしいことが分かるとよいと思います。)

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.Unknown
Locale: Japanese/Japan (ja_JP)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
There are some errors in your model. The first sketch contains duplicate lines. You need to removed those. The 2nd sketch is attached to Face11 of the Pad, after fixing the previous error there is no longer a face with that number, the Pad has only 9 faces. So you need to reattach that sketch, please then consider following the advice from https://wiki.freecad.org/Topological_naming_problem.

Before created a future GitHub issue please consult the [forum](https://forum.freecad.org/) first.

Closing this as a user error.
