### ISSUE TITLE
[Problem] Assembly: the name of `Assembly_InsertLink` is not self-explanatory

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#12165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

“Insert link” is what the program does internally to achieve the insertion of objects in the current assembly. The end user wants to insert a part or a sub-assembly. It should be named for what typical users should expect the feature does, not how it does it.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
What name do you suggest? "Insert Part" would be kind of misleading imo. Perhaps just "Insert"

**Comment by pierreporte** [comment]
The competition uses “insert component”, which suits both parts and sub-assemblies.
