### ISSUE TITLE
[Problem] Assembly: non-ASCII characters are not always supported

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#12164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

First, create a part with PartDesign. Name the Part container with non-ASCII characters like accented letters of Greek letters. Save the file with non-ASCII characters in the name.

Second, create an assembly then use `Assembly_InsertLink` to fetch the part. In the Tasks panel, you’ll notice that the Part container’s name is displayed correctly while the file name in parentheses has two underscores when each non-ASCII characters is supposed to be. After the part is inserted into the assembly, you’ll notice that the Part container’s name has the underscores replacements, while it was displayed correctly in the list.

### Full version info

```shell
0.22 with PR #10764
Tested width Ondsel ES 2024.1
```

### Subproject(s) affected?

Assembly

### Anything else?

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/881c8839-da9f-4f87-bf21-5314b08e52cf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Somehow createdLink = self.assembly.newObject("App::Link", selectedPart.Label) is failing.
But if you create a Link, then it gets the name correctly. I'll investigate

**Comment by wwmayer** [comment]
> Works correctly, but doing this :

The passed string for the internal name is changed to fulfill the rules of a Python identifier and this modified string is also assigned to the Label property.

Anyway, like in RT branch we will make the change to allow any unicode string because since version 3 this is also supported in Python.
