### ISSUE TITLE
[Problem] Assembly: `Assembly_InsertLink` opens the parts in tabs

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#12168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

To insert parts in an assembly, they need to be loaded in the session. This is why `Assembly_InsertLink` opens them in tabs when the files are selected. These tabs, that can be quite numerous when building an assembly, get in the way of normal work: they bury actual working tabs below parts that are not going to be edited right now. It is necessary to close them all by hand.

Is it possible to make `Assembly_InsertLink` close them after clicking OK or Cancel, to make the tabs phantom, or just load the parts in the background? When loading a complete assembly, the parts are not loaded in separate tabs: only the assembly is there.

### Full version info

```shell
0.22 with PR #10764
Tested width Ondsel ES 2024.1
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Ok I see what is the issue here. So what we need is to do a 'partial opening' of the file, the same way realthunder implemented for links. So yes after clicking OK we should close the documents and do a partial opening.
