### ISSUE TITLE
pROBLEM OF DIMENSION IN TECHDRTAW

### ISSUE THREAD

**Issue by ricou1** [FreeCAD/FreeCAD#12246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

the dimensions of tech draw are wrong, but those of part design are good.
[PARTDESIGN.pdf.zip](https://github.com/FreeCAD/FreeCAD/files/14151496/PARTDESIGN.pdf.zip)
[TECHDRAW.pdf.zip](https://github.com/FreeCAD/FreeCAD/files/14151497/TECHDRAW.pdf.zip)

### Full version info

```shell
After a verication with a caliber, dimension given in part design are good 0, 100,11 instead 100 and 20,03 instead 20. those given on the same object are wrong 9,6 instead 10 and 18,89 instead PARTDESIGN.pdf.zip
TECHDRAW.pdf.zip
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This is a duplicate. I have to close this. Please go back to the previous issue you have created (#12244). Note that we need FCStd files not PDFs.
