### ISSUE TITLE
[Problem] Unable to fillet symmetrical side

### ISSUE THREAD

**Issue by YosypC** [FreeCAD/FreeCAD#12258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When created individually, it works. With both, it gives me an error. Before I was able to fillet both without a significant model update (the vertex at the bottom had 4 edges just like this case). By selecting all sides, it completes fine. Even by selecting the lowest edge that connects everything, it still yields an error.

EDIT: I selected the top edge of the "hook" that contacts the major face (coplanar to the holes) and it works. I wouldn't consider this a bug, rather a usability issue. Shouldn't be able to fillet them without selecting the top edge? We can close this if it's not deemed important.

### Full version info

```shell
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35315 (Git) AppImage
Build type: Release
Branch: main
Hash: 09f67f2f6bff1c57ac8019a5ba2f4a2c41025ee6
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
```

### Subproject(s) affected?

PartDesign

### Anything else?

[Forum discussion](https://forum.freecad.org/posting.php?mode=reply&t=84985)
![1](https://github.com/FreeCAD/FreeCAD/assets/50027752/fa046969-5c7b-413d-b4d1-82a17361ab52)
![2](https://github.com/FreeCAD/FreeCAD/assets/50027752/332c7762-571d-4b22-8376-e9bc6c392963)
![3](https://github.com/FreeCAD/FreeCAD/assets/50027752/05c5f8d8-f2b2-40ce-a774-49283a474f10)
![4](https://github.com/FreeCAD/FreeCAD/assets/50027752/b673b59a-1a32-455b-8439-83d392ca4bae)
![5](https://github.com/FreeCAD/FreeCAD/assets/50027752/f200da9e-eb53-42c6-b9b7-288b547d9e84)
[Desk (copy).zip](https://github.com/FreeCAD/FreeCAD/files/14157133/Desk.copy.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Will close this as you've mentioned. This is also depending on OCC.

**Comment by YosypC** [comment]
Alright. Maybe attaching OCC tag would be useful?
