### ISSUE TITLE
[Problem] V0.22 Sketcher_ToggleDrivingConstraint assigns wrong icons

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#12264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Sketcher_ToggleDrivingConstraint command assigns the wrong icons. See image.
![Sketcher_ToggleDrivingConstraint-assigns-wrong-icons](https://github.com/FreeCAD/FreeCAD/assets/70520633/4dcd3559-0c67-4f0c-96d9-324904a7d6e0)

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35803 (Git)
Build type: Release
Branch: main
Hash: 90c90f705bec20faf4b8bb419574134c33c7d4b5
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
Confirmed
```
OS: Debian GNU/Linux trixie/sid (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35822 (Git)
Build type: Release
Branch: main
Hash: c57a83cb4f7f8bc8840ebbfc9aba97c15a502bd9
Python 3.11.7, Qt 5.15.10, Coin 4.0.2, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
```
