### ISSUE TITLE
[Problem] Wrong created external geometry

### ISSUE THREAD

**Issue by YosypC** [FreeCAD/FreeCAD#12267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/50027752/7fbba93a-dfcc-495f-bdaf-21a9dffe3d7e)

I selected the blue line but it projected the remaining, non drawn part of the circumference.

### Full version info

```shell
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35315 (Git) AppImage
Build type: Release
Branch: main
Hash: 09f67f2f6bff1c57ac8019a5ba2f4a2c41025ee6
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
```

### Subproject(s) affected?

Sketcher

### Anything else?

[Desk (copy).zip](https://github.com/FreeCAD/FreeCAD/files/14158481/Desk.copy.zip) (rename format), Sketch005

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
can reproduce. @PaddleStroke maybe this can be tackled together with https://github.com/FreeCAD/FreeCAD/issues/11824

**Comment by drew585** [comment]
I have what seems like the same issue.
I'm sketching on XZ plane. I selected the left side radius. The line created does not have a point on the far left of the part.
Looks like its shifted to the right of where it should be.
![image](https://github.com/user-attachments/assets/d111d995-7043-4657-9dda-6399b98a88f4)
Problem is on FC 0.22 38334.
Linux mint 22 64 bit.

I tried it in FC 0.21.2 and it works correctly there.

**Comment by maxwxyz** [comment]
@bgbsww @PaddleStroke @AjinkyaDahale any idea how this regression came into dev?

**Comment by drew585** [comment]
I just tested this in the new build 38385 and it seems to be working correctly now.

**Comment by maxwxyz** [comment]
@YosypC can you confirm with today's weekly?

**Comment by drew585** [comment]
I just now tested it with new sketches on the same model in both software versions.

38334
![image](https://github.com/user-attachments/assets/b3425546-6c43-478b-86ea-e5000c6342b4)


38385
![image](https://github.com/user-attachments/assets/b9144460-e3ba-4692-bef1-94e90d3f9b8c)

THANK YOU!!!!
