### ISSUE TITLE
[Problem] V0.22 Sketcher: positional OVP buggy for Center and 2 corners rectangle

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#12297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Set the On-View-Parameters preference to "All".
2. Create a new sketch and start Sketcher_CreateRectangle.
3. Select Mode "Center and 2 corners".
4. Enter all OVP values except the last. Values as per the image: 24; 19; 67; 39; 41.
5. Observer that the indicated 67.00mm makes no sense, the edge will change length as you move the mouse while the dimension value stays the same.
6. Enter 68 as the last value.
7. Result: The shape changes relative to the preview, the 67 dim is now attached to a different edge and the 39 dim (entered as a y coord) has become an angle.
![rect-cen-2c-ovp-issue](https://github.com/FreeCAD/FreeCAD/assets/70520633/68591a51-f57c-46f2-b875-e31e552ff70f)

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35803 (Git)
Build type: Release
Branch: main
Hash: 90c90f705bec20faf4b8bb419574134c33c7d4b5
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
@PaddleStroke Is this something you can look at?

**Comment by PaddleStroke** [comment]
Thanks for the report. I will check this case.
