### ISSUE TITLE
[Problem] Freecad FEM workbench pipe diameter inner or outer

### ISSUE THREAD

**Issue by G0rocks** [FreeCAD/FreeCAD#12302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When you use the pipe cross section in the FEM workbench you need to put in the pipe diameter and thickenss. However there is no way of telling if it is the inner diameter or the outer diameter.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Sweden (en_SE)
Installed mods: 
  * Assembly4 0.50.7
  * Manipulator 1.5.7
  * Render 2024.1.23
[/code]
```

### Subproject(s) affected?

FEM

### Anything else?

A suggestion to solve this is to change the "Beam section parameter" window from saying "Diameter" like it currently says:
![image](https://github.com/FreeCAD/FreeCAD/assets/44577486/cec6ed34-0def-43ff-93ac-8f565fcd2ebb)

To saying either "Inner diameter" or "Outer diameter" (depending on which diameter is used.
Also needs an update on the wiki ([https://wiki.freecad.org/FEM_ElementGeometry1D](https://wiki.freecad.org/FEM_ElementGeometry1D)) page under the properties section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
From the CalculiX documentation:

> A pipe cross section is defined by its outer radius (first parameter) and its thickness (second parameter).

FreeCAD takes the diameter, but divides it by two, and enters the radius into the CalculiX input file.

I updated the FreeCAD documentation chapter. I will try to add this in GUI too.

I've noticed that there's an error about incorrect element type when submitting CalculiX analysis with pipe section. Have you encountered it too?
