### ISSUE TITLE
Curves - BlendSurface not working as expected

### ISSUE THREAD

**Issue by oo-pp-oo** [FreeCAD/FreeCAD#12356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Building BlendSurfaces from identical edges connected to identical horizontal planes at different heights does not always give the same result.

See example [here](https://forum.freecad.org/viewtopic.php?t=85161&sid=a18705b4bd8c763168cb8ce8d36504a1).
In this example, the expected result would be 4 surfaces with some degree of lateral continuity. This happens with 3 of the four generated BlendSurfaces.
However, the result for the 4th BlendSurface is weird.

The same happens with quarter circles generated from a polar array, as shown in the figure below.

### Full version info

```shell
OS: Ubuntu 18.04.6 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods:
* Curves 0.6.22
```

### Subproject(s) affected?

None

### Anything else?

This issue has been discussed in the forum and somebody has identified is as a bug
https://forum.freecad.org/viewtopic.php?t=85161&sid=a18705b4bd8c763168cb8ce8d36504a1

The same issue, this time using faces and edges from a PartDesign element repeated with a polar array:
![BlendSurface_Fail](https://github.com/FreeCAD/FreeCAD/assets/26509620/49621b9c-1ced-4e13-82dc-d2c5e1245990)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@oo-pp-oo from the description this should be an issue in the Curves WB? Is so, please open the issue at: https://github.com/tomate44/CurvesWB

**Comment by oo-pp-oo** [comment]
That's right. I have opened it [here](https://github.com/tomate44/CurvesWB/issues/115).
