### ISSUE TITLE
[Problem] Miscreation of geometric entities on projected geometry 

### ISSUE THREAD

**Issue by ab0v3g4me** [FreeCAD/FreeCAD#12355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After projecting a desired face while using the sketcher workbench and creating geometry on top of the projected line it always snaps to a specific point. Different projected faces will have a different fixed point where the geometry will be attached to. 

Constraints work as they should but directly clicking on the projected edge gives annoying results.

This might not be a problem with the sketcher but it is happening within it.

Here's a video of what's going on:

https://github.com/FreeCAD/FreeCAD/assets/150863236/1313d72c-3a48-4c2d-9734-147daf9455d5

I would like to note that this has been happening with previous development versions as well. I can't guarantee for 0.21 since i don't really remember.

### Full version info

```shell
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35858 (Git) AppImage
Build type: Release
Branch: main
Hash: 3a73f916ddab6a0af75265acef7cc87e44e4664a
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.12.4
  * OpenDark 2023.9.30
  * fasteners 0.4.55
  * Dracula 0.0.4
  * A2plus 0.4.60n
  * Behave-Dark-Colors 0.1.1
  * fcgear 1.0.0
  * IconThemes
  * ProDarkThemePreferencePack 1.0.0
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Duplicate https://github.com/FreeCAD/FreeCAD/issues/11824
