### ISSUE TITLE
[Problem] TechDraw doesn't have a 'smart dimension' tool

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

- Length
- Horizontal length
- Vertical length
- Radius
- Diameter
- Angle

Could all be replaced by a smart dimension tool like the sketcher one.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by obelisk79** [comment]
I think there is a place for this. Of course it would have to be optional like in sketcher. It should also behave using the same logic as the sketcher version for consistency.

**Comment by WandererFan** [comment]
We did have all the dimension tools divided into distance, radial, angular and reference-fixing groups.  The users complained bitterly, so we went back to a button for each tool.

**Comment by PaddleStroke** [comment]
@WandererFan I don't mean grouping the tools into one command group. I mean making one tool that does all the dimensions

**Comment by maxwxyz** [comment]
To add: currently the tools need a selection before starting the command. The unified tool should be active without a preselection and then the features should be selectable (like Sketcher_Dimension)
