### ISSUE TITLE
[Problem] TechDraw Move view should be done by drag and drop in the tree.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Move View tool should be removed and moving should be done by drag and drop in the tree.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@WandererFan can you weigh-in at your convenience ?
