### ISSUE TITLE
[Problem] TechDraw : Insert SVG/picture should not have tools

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Insert SVG/picture should not have tools. They should use the core import feature.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
And do we have a core import function that will add an svg image to a TechDraw page?  I have never come across one.  

File > Import would need to know that you intend to import the svg for TechDraw and not for the 3D window.
