### ISSUE TITLE
[Problem] TechDraw 'share view' is a duplication of App::Link

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Why do we have a 'share view' tool that creates what looks like Links ?
On the other hands, links of views cannot be used / put inside pages.

Suggestion is that 'share view' is killed and Link is made to work in pages.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
ShareView might have come along before Links?  If and when Links can handle things like Spreadsheets or Pages or Views, we can look at deprecating ShareView.

TBH, I've never really understood the use case for ShareView.  I've only ever used it while testing.
