### ISSUE TITLE
[Problem] TechDraw : "Add view to clip group" should not be a tool.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

"Add/Remove view to clip group" should not be a tool. It should be done by drag and drop.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
The only time I ever use clip group is when there is a bug report for clip group.   I'm not sure what it does that couldn't be done with detail view (which didn't exist when clip group was ported from DrawingWB).

Should get some user f/b on this.  I'll post a link in the forum.

**Comment by WandererFan** [comment]
forum link:  https://forum.freecad.org/viewtopic.php?t=86362
