### ISSUE TITLE
[Problem] TechDraw: Dimensions are those of projected geos.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Am I missing something? Dimensions tools write the dimension of the projected geos. So if the view is not normal it is wrong.

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/dff217d3-d614-45be-9195-51526844f760)

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
That's the overall behavior of TD. For axonometric views there is the axonometric dimension tool. You can also link the dimensions to 3D objects or overwrite them manually.

**Comment by obelisk79** [comment]
I agree with paddle. This is a reasonable address where some modest automation can be applied.

**Comment by WandererFan** [comment]
You can't get a 3d ref from a 2d ref.  Projection is not an invertible operation.   

At best, you could scan every 3d vertex (or edge as the case may be), project it, then compare each to the 2d ref.   In the general case, this will give a list of potential matches. You would still need manual intervention to pick the right match. 

There is nothing stopping the user from creating dimensions directly from 3d model geometry.   This will create a True dimension, rather than a Projected dimension

**Comment by WandererFan** [comment]
This issue should be closed.

**Comment by maxwxyz** [comment]
I will close this then

**Comment by PaddleStroke** [comment]
I disagree that this should be closed. The user can litteraly shoot himself in the foot by creating non-sensical dimensions, no warning. It is very misleading.
I don't think other CAD softwares enable you to create such non-sense dimensions. I don't know for all but in catia for example : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/609ca15b-443b-410f-a61a-930d056bdb21)
I would be surprise solidworks let you do it either.
Please re-open the issue

**Comment by maxwxyz** [comment]
@WandererFan is it possible to distinguish from the view if the view is axonometric or not to automatically choose the right dimension?

**Comment by WandererFan** [comment]
You can use the the view direction to try to determine if the view seems to be axonometric (ex (1,1,1)) but the orientation of the subject object may mean that what looks like an axonometric view according to the direction is actually orthogonal due to the alignment of the subject.

If you insist on choosing your dimension points on the drawing instead of selecting 3d geometry you are going to get projected dimensions. 

There is no way to convert a projected point back to its unprojected source.

**Comment by WandererFan** [comment]
This is dead easy in Sketcher since sketcher views are 2 dimensional and nothing is projected.

**Comment by PaddleStroke** [comment]
There is no way to convert projected back to original, but it is possible
to store a map of projected-original edge.

**Comment by PaddleStroke** [comment]
With a map of projected-original edges, it should be no problem.

**Comment by howie-j** [comment]
Onshape for reference:
![Screenshot from 2024-02-24 17-26-14](https://github.com/FreeCAD/FreeCAD/assets/82042580/b0970949-4d9e-4c6e-8eda-b43bb15aea06)

**Comment by pieterhijma** [comment]
> You can't get a 3d ref from a 2d ref. Projection is not an invertible operation.
> 
> At best, you could scan every 3d vertex (or edge as the case may be), project it, then compare each to the 2d ref. In the general case, this will give a list of potential matches. You would still need manual intervention to pick the right match.
> 
> There is nothing stopping the user from creating dimensions directly from 3d model geometry. This will create a True dimension, rather than a Projected dimension

> There is no way to convert projected back to original, but it is possible to store a map of projected-original edge.

I would like to react on these two comments from @WandererFan (the first) and @PaddleStroke (the second). I tried to modify OCCT to maintain a mapping between the offered 3D model and the returned 2D projection. I don't think it can be solved in general, but I think there is potential to do much better than what is possible right now. See [this forum post](https://forum.freecad.org/viewtopic.php?p=697345#p697345).

**Comment by WandererFan** [comment]
IDK, but I'm told that dimensions starting as the projected value is the way other CAD programs work.  @howie-j  picture seems to bear this out.

**Comment by maxwxyz** [comment]
I think how other programs handle this is that you define the dimensions in the 3D view (e.g. annotations) before deriving the projected drawing. Then the dimensions get projected also on the sheet and could be linked. If you then change them, they are also changed in the 3D view. I know that's possible in SolidEdge and here are some Inventor references [1-3].

This would in a far future be great for a real GD&T implementation, as they are defined also in the 3D space as annotations on the corresponding features of the model and can then be derived into the 2D drawing.


[1] https://help.autodesk.com/view/INVNTOR/2022/ENU/?guid=GUID-597185E4-F39C-4CE7-9CC7-EA69533BACB2
[2] https://www.cadforum.cz/en/controlling-size-of-3d-model-by-changing-drawing-dimensions-tip10521

**Comment by WandererFan** [comment]
just as documentation...

discussion on dimensions in axo views: https://www.eng-tips.com/threads/is-dimensioning-detailing-in-isometric-view-acceptable.157995/

a google search for "dimension axonometric view" is also informative wrt how other CADs handle axo dims.

getting the 3d measurement onto the page seems to require an additional step in most cases.

**Comment by FEA-eng** [comment]
May I ask why this was closed as completed?
