### ISSUE TITLE
[Problem] Duplicate options offered in dialog when attempting to import STEP file 

### ISSUE THREAD

**Issue by Rugous** [FreeCAD/FreeCAD#12401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When we import the STEP files, the dialogue box show two times de same option

![image](https://github.com/FreeCAD/FreeCAD/assets/160024491/872e95ab-fdbb-4a2e-88e1-7c69471551c5)

### Full version info

```shell

```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Full [about](https://wiki.freecad.org/About) info please. Please edit the OP and  paste it into the relevant placeholder.

**Comment by maxwxyz** [comment]
@Rugous I cannot reproduce. Please add more info, otherwise I'll close this in a few weeks.
Please also test with the weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
