### ISSUE TITLE
[Problem] Changing grid preferences doesn't update the view

### ISSUE THREAD

**Issue by Vanuan** [FreeCAD/FreeCAD#12432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

As you can see here, changing preferences doesn't update the view: https://www.youtube.com/watch?v=U5wqPO8aSbs
You need to update the view somehow after applying the preference.

Also, it isn't clear if this preference is stored globally, inside the document or in the current session.

### Full version info

```shell
[code]
OS: Ubuntu 22.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This has already been fixed in V0.22.
Closing this.
