### ISSUE TITLE
[Problem] Sketcher_CreateBSplineByInterpolation Unhandled unknown C++ exception if grid snap is on

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#12480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Enable grid snap.
2. Call Sketcher_CreateBSplineByInterpolation or Sketcher_CreatePeriodicBSplineByInterpolation.
3. Pick a point, no need to actually snap.
4. Move the cursor.
5. Result: Unhandled unknown C++ exception

Full error message:
```
21:36:15  Unhandled unknown C++ exception in ViewProvider::eventCallback 
(Event type: SoLocation2Event, object type: SketcherGui::ViewProviderSketch)
```

### Full version info
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35994 (Git)
Build type: Release
Branch: main
Hash: 69097667df47b2cc86d8688d2dbb545319e33e68
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
> Enable grid snap.

Where and how? I cannot find this option any more.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/12999
