### ISSUE TITLE
[Problem] Automatic naming is confused/wrong with the grounded Symbol of the Assembly Workbench

### ISSUE THREAD

**Issue by tobiasfalk** [FreeCAD/FreeCAD#12546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

While testing the Assembly workbench in the latest Weekly Build I created two cubes("Cube" and "Cube001" as normal) and then grounded one, after that I created a third cube which was not named "Cube002" but just "Cube". I assume this is because of the Lock symbol in the name of the first cube.
![Unbenannt](https://github.com/FreeCAD/FreeCAD/assets/56540480/a5a5d088-a9ea-446a-90bf-bc10d587d39c)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36082 (Git)
Build type: Release
Branch: main
Hash: 7a025e4e60a607bdbdd1599627ce13bb8eeda071
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * A2plus 0.4.56a
  * AirPlaneDesign 0.4.0
  * Assembly3 0.12.0
  * Assembly4 0.11.10
  * CADExchanger
  * cadquery_module
  * CurvedShapes 1.0.5
  * dxf-library
  * DynamicData 2.46.0
  * ExplodedAssembly
  * fasteners 0.5.2
  * fcgear 1.0.0
  * FeedsAndSpeeds 0.5.0
  * FEM_FrontISTR 0.1.0
  * FreeCAD_Electric
  * FreeCAD_Schematics
  * GDML 2.0.0
  * kicadStepUpMod 10.11.7
  * Plot 2022.4.17
  * pyrate
  * Render 2022.2.0
  * sheetmetal 0.2.56
  * Ship 2022.4.11
  * SteelColumn
  * ThreadProfile 1.82.0
  * timber
  * trails 2022.1.0
```
```


### Subproject(s) affected?

Assembly

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke

**Comment by PaddleStroke** [comment]
Yes the lock is in the label. So it's the same as if you create one cube, rename it to 'Banana' then create a new cube. The second cube will be called 'Cube' because the name is free.
So this is not really a bug, and in real life I'm not sure it would be a real annoyance.
Besides I don't see an easy fix here.

**Comment by tobiasfalk** [comment]
I like the Lock but I do not like it to be part of the lable, I think this will confuse some in the future.
There are multiple ways to solve this

- Adding the Lock to the Symbol(on top.of it), this way the Lock has nothing to do with the lable

- Adding the Lock only when the TreeView is created, this way the lable remains the lable and the Lock is a separated part of the Text in the TreeView

- Check for the lock in the automating code and everywhere the lable is changed(not my favourite)

**Comment by pierreporte** [comment]
@PaddleStroke Then it sounds like to be related to #12139. The problem of names in the tree is wider (see also #12141).

**Comment by PaddleStroke** [comment]
Yes it's not ideal that the lock is in the label indeed.
Maybe it should be an icon. Linkstage has a ton of icons, but to the point where it is confusing. The icon on the right side seemed nice.

When you say 'on top of the symbol' you mean on top of the object icon?

**Comment by PaddleStroke** [comment]
@wwmayer is there a way to overlay an icon on top of any object icon? So that the lock icon can be overlayed on top of other icons : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/a9fec9c5-54e2-467d-8d10-8ac6d437ba53)

I had a look at how bodies are doing the tip indicator, but they are using the PartDesign::ViewProvider class that reimplement the mergeColorfulOverlayIcons function.

The thing is that here I want to add an overlay to any kind of VP so I'm not sure how to handle this.

**Comment by PaddleStroke** [comment]
Having said that there is already a lot of overlayed icons (recompute mark, external, link) so adding one more is maybe not so great in terms of visibility.

**Comment by tobiasfalk** [comment]
> @wwmayer is there a way to overlay an icon on top of any object icon? So that the lock icon can be overlayed on top of other icons :
> ![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/503dc3c9-9b28-4e1b-9ed0-7a38101405e1)
> 

Yes that's pretty much what I meant, but why not get the Icon, than overly the Lock and than put this in the TreeView.

**Comment by pierreporte** [comment]
Solidworks displays the grounded status with text at the beginning of the tree-view text:

* `(f)` for fixed parts,
* `(-)` for non-fixed parts.

This text is before the formatted string explained in https://github.com/FreeCAD/FreeCAD/issues/12141#issuecomment-1965347181.

Basecally it’s as if there was an icon but more discreet.

Also considering #12141, the text could be quite long so the symbol should be at the beginning not at the end.

A small lock over the icon would be hard to see.

**Comment by tobiasfalk** [comment]
> Solidworks displays the grounded status with text at the beginning of the tree-view text:
> 
> * `(f)` for fixed parts,
> * `(-)` for non-fixed parts.
> 
> ...

Also sounds like a good solution, this with a modification to the Auto naming code so that it is ignored and it should work perfectly.
I would also add a (j) fo parts that are joined in a way so that one can see witch parts are completely free.

**Comment by furgo16** [comment]
Also note that the lock as a character (as opposed to an icon), might render differently on different platforms and/or different fonts. On Linux for instance, it is not even recognisable as a lock and it adds extra vertical padding to the tree. See the screenshot in the (related?) issue https://github.com/FreeCAD/FreeCAD/issues/12788

**Comment by obelisk79** [comment]
I like the lock symbol here. But not overlayed like the tip indicator. There much be a way to align it to the right of the label with it modifying the label itself. The behavior currently is inconsistent and will generate lots of unwanted feedback due to the unexpected behavior.

**Comment by PaddleStroke** [comment]
@wwmayer I'm still not sure how to handle this problem could you please weight in?
The thing is that to indicate in the tree that an object is grounded, we need (I think) to store this information in one of the ViewProviderDocumentObject.
Currently it is done so by adding the lock character to the object label. But this has many issues so we can't keep this.

Is it acceptable to add a 'Locked' bool property to ViewProviderDocumentObject ?

Then my idea was that if Locked is true, then either : 
- Overlay a lock icon on the existing icon. Pro : easy and don't clutter more the tree. Cons: Many overlays already: link, external, recompute, tip... Though not many would interfer
- Add an icon next to main icon. Pro : clearer. cons: starts cluttering the tree with icons.
- Add an icon to the right side of the label (where currently the icon appears). Pro : best solution imo. Cons : hard because how do we draw icon on the right side?

Thoughts?

**Comment by PaddleStroke** [comment]
Another possible solution is that we do not show anything in the tree. Instead we draw a 'ground' in the 3d view : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/4bc1ae93-3d79-4d16-8be9-4707e2e54de4)

This is perhaps the easier and less intrusive thing. Thoughts?

**Comment by maxwxyz** [comment]
@PaddleStroke I don't like the ground. What about a small lock icon at the center of mass in the 3D view? I think in general it would be god to display the joint type alongside the JCS in the 3D view as it gets crowded when multiple joints are visible.

**Comment by PaddleStroke** [comment]
Lock symbol why not, but if it's draw in 2d then when you rotate it's not ideal. Ideally it should rotate with the camera. Like in sketcher. But I'm not sure how this is implemented.

**Comment by maxwxyz** [comment]
@PaddleStroke maybe like the 3D annotations of the unified measurement tool (GSoC) https://github.com/FreeCAD/FreeCAD/pull/9750 

Found also: 
- https://github.com/FreeCAD/FreeCAD/pull/11602
- https://forum.freecad.org/viewtopic.php?p=659500
- https://forum.freecad.org/viewtopic.php?style=10&t=4780

**Comment by maxwxyz** [comment]
@PaddleStroke 
There is a fixed placed annotation: 
```
obj=App.ActiveDocument.addObject("App::Annotation","Label")
obj.LabelText="Annotation"
```
 or a movable Annotation label: 
```
obj2=App.ActiveDocument.addObject("App::AnnotationLabel","Label")
obj2.LabelText="Annotation colour test"
```


https://github.com/FreeCAD/FreeCAD/assets/6246609/8a25646c-c063-4e5f-ad18-d096e85c9cba



Data and View Tab in the property editor allows for styling. This would be nice to see all joint locations and types!

**Comment by PaddleStroke** [comment]
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/f2e2d793-1767-4ef8-b245-466bfaf6dd56)
So I killed the lock icon in the label and replaced it with a lock symbol on the 3d view like so

**Comment by wwmayer** [comment]
> Is it acceptable to add a 'Locked' bool property to ViewProviderDocumentObject ?

I am not a fan of adding stuff to a base class that is only needed in a sub-class. It would be acceptable for me to extend the ViewStatus enum from ViewProvider.h because this at least doesn't require more memory.

**Comment by maxwxyz** [comment]
> So I killed the lock icon in the label and replaced it with a lock symbol on the 3d view like so.
> 

Looks good. Is it always visible, or only when the joint is visible? It could also just become visible if you try to drag this item or have the create/edit joint dialog open so you see which one is the grounded part(s).

**Comment by PaddleStroke** [comment]
only when the joint is visible.
Yes become visible when trying to drag the item would be ideal.
