### ISSUE TITLE
Dashed construction lines in Sketch for better perceptibility

### ISSUE THREAD

**Issue by luisDias89** [FreeCAD/FreeCAD#12563]
### Original PR

https://github.com/FreeCAD/FreeCAD/pull/4246

### Description and Justification

The construction lines are not easily perceivable when multiple drawings are present simultaneously. I have experience with other CAD software and I notice that in all of them, construction lines have a different color (already implemented here) and are dashed. Additionally, there should be a small icon in the small menu on the left side indicating that it is a construction line.

A dashed pattern like this one:
![Construct Line](https://github.com/FreeCAD/FreeCAD/assets/48370099/e736daef-4470-46f1-9c6d-677fe90973c2)

More Info:
![image](https://github.com/FreeCAD/FreeCAD/assets/48370099/fb1682b1-095c-49f0-87bf-3b998d2c0e49)

**Comment by FEA-eng** [comment]
It's already implemented and available in weekly builds: #11996

**Comment by maxwxyz** [comment]
@luisDias89 please try the lates builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
I'll close this as implemented.

**Comment by luisDias89** [comment]
Thank you, you guys are fantastic. I've already given you two donations, this year I hope to give more. It's becoming fantastic
