### ISSUE TITLE
[Problem] Sketcher: UI/UX - Point is construction geo by default and non-construction when toggled

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#12582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The create point command is the only geometry command which works opposite to all other create geometry tools (e.g. line).
By default, you create *real* geometry (non-construction). The point tool creates by default a construction point. You have to manually select the point and toggle construction geometry to turn it into a *real* point. Also, when toggling the construction method, the point tool does not change. It always creates construction points, which are unusable outside the sketch.

Here is a little demo:

https://github.com/FreeCAD/FreeCAD/assets/6246609/67db1802-98ec-44f3-a8ab-217cc627df40

The issue is when placing a default point its actually a construction point which is displayed in the active sketch 3D view as a normal point (red) but in the task view geometry elements list it is displayed blue.
When you toggle it it will become a real point and is displayed white in the 3D view but red in the geometry elements list (as all other points).
![WhatsApp Bild 2024-01-28 um 21 49 16_47effdd3](https://github.com/FreeCAD/FreeCAD/assets/6246609/2230baac-b073-41a7-8f46-b617fe37da6b)

### The proposal is:

1. switch the behavior of the point tool to be in line with all other create-tools: default point is no construction point and displayed red (like line start/end point)
2. construction points should then be displayed blue (or use the new preference for construction geo). internal points (like circle or arc centerpoints) should then be displayed blue as they are construction points and also cannot be selected outside of the sketch

The only use case I can think of when you would need a single construction point is if you want to create a point symmetry not around the origin of the sketch but on a defined point, but real points can be used in other WB and maybe later for hole definitions and patterns.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36082 (Git)
Build type: Release
Branch: main
Hash: 7a025e4e60a607bdbdd1599627ce13bb8eeda071
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.1
  * CurvedShapes 1.0.5
  * Curves 0.6.23
  * Defeaturing 1.2.2
  * fasteners 0.5.11
  * FEMbyGEN 2.1.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.1
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@obelisk79 maybe something for DWG discussion?

**Comment by macdroid53** [comment]
Just for historical context. There was a time when the point could not be used outside the sketch in Part Design. But, when it was noted that you could Extrude to points in Part workbench it was reworked in Part Design.

**Comment by obelisk79** [comment]
Ok, after some lengthy debate within the DWG. I'm going to recommend this default behavior be changed to match the suggestions of the initial issue report.

**Comment by maxwxyz** [comment]
Could benefit: https://github.com/FreeCAD/FreeCAD/issues/6884

**Comment by maxwxyz** [comment]
@PaddleStroke FYI

**Comment by PaddleStroke** [comment]
Imo it should be :
Blue point for construction points.
White point for normal points.

Why using red? Red is the color of constraint. If we use it it should be for coincident points.

**Comment by maxwxyz** [comment]
yes, excellent proposal

**Comment by pierreporte** [comment]
@PaddleStroke I agree completely, plus it’s better for colorblinds once there is constrained geometry (green). Though they will still look the same when fully constrained, hence #11919.

**Comment by PaddleStroke** [comment]
@maxwxyz do you want to give this a go? It should be pretty straight forward as you just want to change the preference colors of the point and update the sketcher icons if necessary.
The only issue is that edges start/endpoints have the same color as construction point. But as you show in your video, they are actually real points. So you would need to find and change the color used by edges in coin managers.

**Comment by PaddleStroke** [comment]
@pierreporte they look the same when constrained, but that's because the colors of constraint construction and normal is similar. Perhaps the colors can be improved a bit. Changing the shape of points is much more work. Besides if edges end/start are displayed as real point, it would look bad imo if they have a different shape than arc center for instance.

**Comment by pierreporte** [comment]
I don’t think that a different shape would look bad. Have a look on this Catia screenshot. Besides, color differences are a problem already reported and this could solve it.Le 18 mars 2024 à 10:09, PaddleStroke ***@***.***> a écrit :﻿
@pierreporte they look the same when constrained, but that's because the colors of constraint construction and normal is similar. Perhaps the colors can be improved a bit. Changing the shape of points is much more work. Besides if edges end/start are displayed as real point, it would look bad imo if they have a different shape than arc center for instance.

**Comment by maxwxyz** [comment]
> @maxwxyz do you want to give this a go? It should be pretty straight forward as you just want to change the preference colors of the point and update the sketcher icons if necessary. The only issue is that edges start/endpoints have the same color as construction point. But as you show in your video, they are actually real points. So you would need to find and change the color used by edges in coin managers.

not sure if I'm capable. Base creation would be easy, color too, but what about to check if they have a coincident constraint or are start/end points for line. Also no idea about the centerpoints, internal and external points.

**Comment by PaddleStroke** [comment]
@pierreporte let's first handle colors and see how it goes before going into shape.

**Comment by pierreporte** [comment]
@PaddleStroke That’s ok for me.

**Comment by maxwxyz** [comment]
@PaddleStroke yes it's correct. And the point command should create a real point by default, and a construction one when toggled.
If a line is construction geo, their end points should also be construction points.
What's the situation if a construction point is coincident? I think it should still be blue as it's construction geo.
BSpline control points should also be blue.

Thanks for picking this up, I can send you the updated icons if they are needed.
@obelisk79 what is your opinion on the red dots as *all* points just in the icons?
It would be colorful if the normal point is white, the bspline points in the icon are blue, the corner points of rectangle is white,... (just considering the icons)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/7652bd26-e0c2-4ffc-8a6f-35f8cfdaaca5)

**Comment by PaddleStroke** [comment]
Yes please send me the updated icons.
As to how to handle the icons, it is a good question to which I cannot say for sure what is the best.

**Comment by maxwxyz** [comment]
@PaddleStroke we'll leave the icons as is and can decide at a later point to update them if necessary. Same as with the dashed construction line, no icons were changed. I think for visibility it's also better to see the points in the icons at smaller scale as they are currently implemented.

**Comment by PaddleStroke** [comment]
1 to 4 done : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/82a5dad0-0098-498f-a677-f19ba4179ea8)

Now looking into how to do 5.

**Comment by maxwxyz** [comment]
@PaddleStroke nice, is the color linked to the line color setting (normal, construct,..)?

**Comment by PaddleStroke** [comment]
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/ad111aad-883e-433a-a1b3-48dce3342e5f)
That's it.

**Comment by maxwxyz** [comment]
@PaddleStroke looks good!
I think this would also solve https://github.com/FreeCAD/FreeCAD/issues/11919 and partly help https://github.com/FreeCAD/FreeCAD/issues/11799

Is the color hardcoded or using the line color in the preferences (or a new preference as for the constrained ref points)?
