### ISSUE TITLE
Grouping of Parts in the Assembly

### ISSUE THREAD

**Issue by tobiasfalk** [FreeCAD/FreeCAD#12615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It would be nice if one could create Groups/Folders inside the Assembly so that one could group and organize parts.
One common thing that would be nice to group are Fasteners, so that they do not clouder the Tree View too much.
Yes one will say why not do just Sub Assemblies when they are available but even then it would be nice for things like Fasteners and co.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36082 (Git)
Build type: Release
Branch: main
Hash: 7a025e4e60a607bdbdd1599627ce13bb8eeda071
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * A2plus 0.4.56a
  * AirPlaneDesign 0.4.0
  * Assembly3 0.12.0
  * Assembly4 0.11.10
  * CADExchanger
  * cadquery_module
  * CurvedShapes 1.0.5
  * dxf-library
  * DynamicData 2.46.0
  * ExplodedAssembly
  * fasteners 0.5.2
  * fcgear 1.0.0
  * FeedsAndSpeeds 0.5.0
  * FEM_FrontISTR 0.1.0
  * FreeCAD_Electric
  * FreeCAD_Schematics
  * GDML 2.0.0
  * kicadStepUpMod 10.11.7
  * Plot 2022.4.17
  * pyrate
  * Render 2022.2.0
  * sheetmetal 0.2.56
  * Ship 2022.4.11
  * SteelColumn
  * ThreadProfile 1.82.0
  * timber
  * trails 2022.1.0
```
```


### Subproject(s) affected?

Assembly

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Related: https://github.com/FreeCAD/FreeCAD/issues/12142

**Comment by tobiasfalk** [comment]
> Related: https://github.com/FreeCAD/FreeCAD/issues/12142

Sorry didn't find this in my search🤦‍♂️

**Comment by PaddleStroke** [comment]
You can already use group inside assembly : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/95156b53-55e4-411f-8bbe-3a7207a10ada)
Did you find cases where it was not working as expected? If no then this should be closed. If yes please give me a sample file to debug it.

**Comment by tobiasfalk** [comment]
I do not know if I am blined but I do not find it, I even downloaded the newest Weekly Build

**Comment by tobiasfalk** [comment]
Ok, found it. For some reason Structure Toolbar was disabled

**Comment by tobiasfalk** [comment]
But I do get This dialog for every part i move in to a group, a checkbox to select "do for all" would be nice.
![A](https://github.com/FreeCAD/FreeCAD/assets/56540480/18f4a32e-5273-41a5-b763-8677adc82446)

**Comment by PaddleStroke** [comment]
This message should not appear in this case. I'll work on it

**Comment by maxwxyz** [comment]
@PaddleStroke I think it is the same problem as https://github.com/FreeCAD/FreeCAD/issues/15111 but cannot confirm.

**Comment by PaddleStroke** [comment]
No it's not the same. This was about grouping parts. Which is actually working. But there was still the small issue that when you moved a part to a group, it would prompt you to delete the joints. Which should not be mandatory as the object stays in the assembly.

Anyway this is going to be fix by https://github.com/FreeCAD/FreeCAD/pull/15012
