### ISSUE TITLE
[Problem] Addon Manager page scroll skips one row

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#12627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If the Workbench list in the Addon Manager is scrolled by clicking below the slider in the vertical scroll bar, one row is skipped.

1. Open the AM.
2. Check which row comes after the last visible row.
3. Scroll back to the top.
4. Click below the vertical slider.
5. Result: Row checked in step 2 has been skipped.

### Full version info

```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36117 (Git)
Build type: Release
Branch: main
Hash: 8a3407aee6dff8218282d9cdc3f4e32e7ad958d4
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

```
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35803 (Git)
Build type: Release
Branch: main
Hash: 90c90f705bec20faf4b8bb419574134c33c7d4b5
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Addon Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Are you experiencing this only in Expanded view, or also in Compact?

**Comment by Roy-043** [comment]
In both. If you use the PgDn keyboard key the list scrolls with a certain overlap. I would expect the same behavior when cliking below the vertical slider.

**Comment by chennes** [comment]
Me too -- so PgDn is working correctly, but not clicking the scrollbar?
