### ISSUE TITLE
[Problem] Assembly : Using transform tool unset edition of the active Assembly

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When you trigger the transform tool while editing an assembly, it will unset the edit of the assembly. Which is very confusing.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Will I be able to use the transform tool if the assembly stays active or will the transform tool *fight* with the joint constraints if I try to temporarily move the part aside?

**Comment by luisDias89** [comment]
Why don't they perform a look-ahead on the constraints and make inaccessible the planes/rotations/directions that are not available in the transform tool?
