### ISSUE TITLE
External thread making

### ISSUE THREAD

**Issue by pok00** [FreeCAD/FreeCAD#12663]
### Original PR

https://github.com/FreeCAD/FreeCAD

### Description and Justification

I have a problem that making external threads is quite complicated and I would like to see feature in part design for external metric threads since we already have feature for internal threads with hole feature and is easy to use and uncomplicated, so I would love to also have this feature for external threads.

**Comment by luzpaz** [comment]
Needs more specificity. And please don't ignore the Feature request template. Talk to forum or discord for orientation on how to make a Feature Request.
