### ISSUE TITLE
[Problem] Support Import/Export of .stpx STEP format

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#12678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently it is not possible to import or export .stpx files into FreeCAD

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@Roy-043 no? I cannot import or open these files. stp**X** not stp**Z**_

**Comment by maxwxyz** [comment]
Thanks, happens to me too :) I thought I was doing something wrong not being able to open these files.

**Comment by luzpaz** [comment]
I can't locate the `.stpx` format documentation online. Anyone else have better success ?

**Comment by maxwxyz** [comment]
I think its from STEP AP242 and has BOM information in it, maybe STEP+XML as https://en.wikipedia.org/wiki/ISO_10303-28 
I currently have no access to the latest version of that standard. 

Related info:
https://en.wikipedia.org/wiki/ISO_10303#Coverage_of_STEP_Application_Protocols_.28AP.29
https://en.wikipedia.org/wiki/ISO_10303-21

**Comment by dpasukhi** [comment]
Hello, OCCT plan to implement STPX extensions.
We already working on it And partially implemented internally.
But the point about will it be opensource or commercial not resolved.

_
There are a lot of  STPX documentation, it is "Business" or "Domain model" named.

**Comment by maxwxyz** [comment]
@pierreporte I guess this should be on the mechanical board somewhere, to be able to import and export new STEP formats, incl. metadata and annotations

**Comment by pierreporte** [comment]
Is this P2 or P3?

**Comment by maxwxyz** [comment]
P3 IMO but if it is implemented in OCCT maybe it could be ported over sooner.
@dpasukhi is there a timeline?

**Comment by dpasukhi** [comment]
@maxwxyz unfortunately there are no timeline for that activity. That is a "open-time" task for breaks between tasks.
I'm not sure when it will be published. For now only about 20% import/export is ready.

And additionally, I'm not sure about licence. It can be a commercial or open source. That topic on discussion (I'm voting for open source for sure).

**Comment by maxwxyz** [comment]
maybe the newest ISO/DIS 10303-242 https://www.iso.org/standard/84300.html can be taken into account, but also information like mates and kinematics for assemblies inside FreeCAD @PaddleStroke 

@pierreporte the STEP standard seems to incorporate even more information now, like version info, dependencies, quality and manufacturing info,... (latest one: https://www.iso.org/standard/84667.html) Is this worth putting on the mechanical list? IMO supporting good import and export for the industry standard format is important for wider adoption of FreeCAD.

**Comment by pierreporte** [comment]
Yes it would be good if FreeCAD was fully compliant to newer STEP standard, even though it doesn’t have all the features yet. Do you want to create a new issue? If so I’ll put it in the board.

**Comment by maxwxyz** [comment]
@pierreporte finally done

**Comment by maxwxyz** [comment]
according to https://dev.opencascade.org/node/88020#comment-26960 it should be available this quarter, @pieterhijma

**Comment by dpasukhi** [comment]
STPX is already available for import/export as a commercial component.
The full list:https://occt3d.com/data-exchange-formats/
Soon we start delivery as planned non-commercial binary delivery.
