### ISSUE TITLE
[Problem] Sketcher: no way to add intersection geometry

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#12670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

`Sketcher_External` only projects selected geometry in the sketch plane. The only intersections it can make are with datum geometry, which is very limited. Intersections in sketches are very useful when working with surfaces and wireframe geometry to build-up features.

I would suggest dropping `Sketcher_External` from the UI (not from code) and replace it with `Sketcher_ProjectExternal` as a fixed version (no intersection of datum planes and other reported problems) and `Sketcher_IntersectionExternal` for the intersections.

### Full version info

```shell
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36166 (Git) AppImage
Build type: Release
Branch: main
Hash: a5ea8023a29b6d7bbf1ebd57b5ed31dd27c5947b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * CosmeticThread3D
  * TabBar (Disabled)
  * sheetmetal 0.4.0
  * OpenDark 2023.12.1
  * OpenLight 2023.12.17
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TomaszSzt** [comment]
Just for your information and from an end user point of view who doesn't look into coding details:

![image](https://github.com/FreeCAD/FreeCAD/assets/87855864/73b203be-1326-4610-875a-3111309901d0)

If something like that is what you are looking for, then check the LinkBranch https://github.com/realthunder/FreeCAD

**Comment by pierreporte** [comment]
I know that the Link branch can do it but it is not the official FreeCAD. The goal isn’t just the feature but official support.Le 12 mars 2024 à 16:50, TomaszSzt ***@***.***> a écrit :﻿
Just for your information and from an end user point of view who doesn't look into coding details:
image.png (view on web)
If something like that is what you are looking for, then check the LinkBranch https://github.com/realthunder/FreeCAD

**Comment by pierreporte** [comment]
@realthunder Could you indicate where this is implemented so that the person willing to implement the feature can get inspiration from your work?

**Comment by pierreporte** [comment]
Interesting feature: when selected geometry doesn’t intersect with the sketch plane, it could be asked to extend it to compute an intersection. It would be only for easily extendable geometry: planar surfaces (so it isn’t necessary to add a datum plane), straight edges (so no datum line necessary). Surfaces fully normal to the sketch plane could also be extended but it would be equivalent to a projection.

@maxwxyz

**Comment by realthunder** [comment]
It is very difficult to isolate this function in my branch. It is interwind with topo naming code I added to Sketcher. I would say wait until topo naming code is merged. External geometry is not reliable without it anyway.

**Comment by AGluk** [comment]
Hello.

Does anyone know,
Why there is no macOS x64 version of the latest release 2024.10.03 in the LinkBranch?
Only Arm64 version for macOS.

Thanks.

**Comment by tarman3** [comment]
Please close this issue and create new in LinkBranch repository.
