### ISSUE TITLE
[Problem] v0.22.0 Sketcher Automatic constraint creates 0 length when click center point (sometimes crashes)

### ISSUE THREAD

**Issue by iAmVaeVictus** [FreeCAD/FreeCAD#12684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Video attached of steps, but 
1. In Sketch, draw a square
2. Click the new Dimension tool icon (or click "D")
3. Click center point. 0mm dimension is drawn. 
4. Sometimes when trying to click to delete that erroneous dimension, crash (MacOS). Can't get it to replicate reliably. 

This shouldn't be allowed or a guiding message should say, click the other point first you idiot. 

https://github.com/FreeCAD/FreeCAD/assets/7082654/a19ed9fd-ced8-4443-9a53-3bcc5380ebd1

### Full version info

```shell
OS: macOS 13.6.4
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35994 (Git)
Build type: Release
Branch: main
Hash: 69097667df47b2cc86d8688d2dbb545319e33e68
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I guess this happens because the origin cannot be a non-driven dimension but is handled like any other point and should not be able to be dimensioned on its own without another selection.
