### ISSUE TITLE
[Problem]  Syntax Error creating Helix primitive, Unit system 'Building US'

### ISSUE THREAD

**Issue by willrabbermann** [FreeCAD/FreeCAD#12779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Using Unit system: "Building US (ft-in, sqft, cft)"
Can not create Helix primitive with:

Pitch 1/2" 
Height 18"
Radius 1/4" 
Angle 0 
Right-handed coordinate system

Report view
```
09:37:42  <class 'SyntaxError'>: ('unterminated string literal (detected at line 3)', ('<string>', 3, 41, 'App.ActiveDocument.Helix001.Height=\'1\' 6"\'', 3, 41))
```

Works using the "Standard" unit system but not "Building US".

### Full version info

```shell
OS: KDE Flatpak runtime (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.63
  * Assembly4 0.50.7
  * fasteners 0.5.12
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by willrabbermann** [comment]
I am switching to standard units from now on. It just makes more sense.

**Comment by luzpaz** [comment]
Similar error as  #9396 and #12713

**Comment by benj5378** [comment]
Using `Building US (ft-in, sqft, cft)` set in preferences, the helix was made with
```
App.ActiveDocument.Helix.Height='1\' 6\"'
```
No syntax error. It seems that the issue have been solved at some point. @luzpaz, can you close this?
