### ISSUE TITLE
Extra padding between grounded part and rest of parts in the document tree

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#12788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There appears to be some extra padding between the assembly part that has been marked as grounded and the rest of the parts in the document tree. This seems to be due to the additional pictogram added as a character at the end of the grounded part's name, as removing the character restores the expected padding. But note that removing the character results in https://github.com/FreeCAD/FreeCAD/issues/12789.

![Padding](https://github.com/FreeCAD/FreeCAD/assets/148809153/597d979b-8257-430d-bc75-e2909b952dd6)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36285 (Git) Snap 946
Build type: Release
Branch: main
Hash: b7a46805040662019c54089a96b3f43caf008e16
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * BIM 2021.12.0
  * Curves 0.6.23
  * ExplodedAssembly
  * BillOfMaterials 0.0.5.6
  * Ondsel-Lens 2024.1.22.01
  * Assembly4 0.50.7
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Related: https://github.com/FreeCAD/FreeCAD/issues/12546
