### ISSUE TITLE
FEM simulation on assembly (FreeCAD)

### ISSUE THREAD

**Issue by MatheoBARRIER** [FreeCAD/FreeCAD#12781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello,

I have to do some FEM simulations on a complex assembly, I just want to start with a very simple assembly like that:
![Capture](https://github.com/FreeCAD/FreeCAD/assets/159763189/44c09db0-1b22-4643-a943-5b3804c7a3de)
The cylinder and the cube is two different solids, I put a constraint tie on the 2 faces in contact and there is materials and meshes for each parts:
![image](https://github.com/FreeCAD/FreeCAD/assets/159763189/101a0969-5bc4-47bb-ba89-993be893c5d0)
The problem is that the solver says: "no mesh defined in the analysis".

I want to know if this is the only problem to solve or I have to do this simulation in other ways.
I seen that there is the A2plus addon to make assemblys but I can't do simulations.

Btw there is the Gmsh error "list index out of range" almost every time I execute a mesh.

Thanks for helping me.

### Full version info

```shell
FreeCAD 0.21.2
windows 10
64-bits
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I'll close this as this is more like a help request and not an issue with FreeCAD.
