### ISSUE TITLE
[Problem] "ERROR: list index out of range" in Gmsh generating in assembly

### ISSUE THREAD

**Issue by MatheoBARRIER** [FreeCAD/FreeCAD#12791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello,

I tested Gmsh and Netgen for the two parts independently and there is no solver errors, but when I put them together in an assembly, Gmsh has the error "list index out of range" and with Netgen the solver has the error "FEM Mesh has no volume element"
![image](https://github.com/FreeCAD/FreeCAD/assets/159763189/019960d7-9863-4dd3-8775-642c543478fc)

I'm doing my assembly by fitting them together with the tool "transform" and I use the tool "boolean fragment" with the mode CompSolid. I seen this tutorial: https://www.youtube.com/watch?v=T-ggqH3tXHs and I used the tool CompoundFilter.

![image](https://github.com/FreeCAD/FreeCAD/assets/159763189/4038bd81-8814-4358-9464-7e55c9bd9917)

Thanks in advance for the help.

### Full version info

```shell
FreeCAD 0.21.2
Windows 10 64-bit
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Try again - delete the whole Analysis container with all objects. Remove the CompoundFilter and Boolean Fragments and add only [Part Compound](https://wiki.freecad.org/Part_Compound). Then add a new Analysis container (making sure that it's below the geometry operations in the tree), select the Compound and try to mesh it.

Next time please ask such questions on the forum: https://forum.freecad.org/viewforum.php?f=18
GitHub repository is meant for confirmed bugs and feature requests.

**Comment by MatheoBARRIER** [comment]
When I generate the mesh with Gmsh, there is an error that mean that there is missing the Compound_Mesh.unv in my Temp folders.

**Comment by maxwxyz** [comment]
I'll close this as this is again a help request.

**Comment by MatheoBARRIER** [comment]
It's not a help request it's a bug, if I'm meshing a compound there miss Compound_Mesh.unv and if I'm meshing a fusion there miss Fusion_Mesh.unv, I updated Gmsh and FreeCAD and it doesn't works

**Comment by FEA-eng** [comment]
> It's not a help request it's a bug, if I'm meshing a compound there miss Compound_Mesh.unv and if I'm meshing a fusion there miss Fusion_Mesh.unv, I updated Gmsh and FreeCAD and it doesn't works

Let's continue the discussion on the forum: https://forum.freecad.org/viewtopic.php?t=85921
We need to check if you are doing everything correctly and try it ourselves before we can confirm a bug.
