### ISSUE TITLE
[Problem] UI/UX: Freeze function issues

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#12829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

@FlachyJoe implemented a great feature to *freeze* the current state and exclude from recompute: https://github.com/FreeCAD/FreeCAD/pull/12580

As @FEA-eng mentioned in the PR https://github.com/FreeCAD/FreeCAD/pull/12580#issuecomment-1978531015 it is currently not available in the PartDesign WB.
I've played a bit with this feature and have some troubles which should be easy to fix:

1. Frozen state does not persist on save and opening a file. If I freeze an object, alter it and save it, the alteration is not displayed. When reopening, the modified object is visible and the object is not frozen anymore (recompute at opening). The last modification before closing is now irreversible and lost, although the object was frozen and shouln't be altered.
3. If a PartDesign body is frozen, all nested features can be changed and alter the frozen body.
4. A frozen body can be chamfered in the PartWB. After that it cannot be unfrozen again.
5. A frozen sketch can be activated but is displayed empty in the Sketcher WB
7. The visibility eye icon does not change its state when clicked but the visibillity in the 3D view is toggled (reproduced with a nested sketch in a PartDesign Pad feature) https://github.com/FreeCAD/FreeCAD/issues/12822
Also reproduceable with nested object which are frozen inside of a group (e.g. walls in an arch group)
8. Frozen command does not register with undo/redo
9. If you use a part of a frozen object to create a new feature it throws an error (tried to pad a face of the frozen feature: Index out of bound)
10. If you undo and redo and the body is frozen, all redone features are now outside of the body and cannot be moved inside of the body
11. You can edit frozen features (e.g. draft objects). They wont change but the edit is permanent. On unfreezing, the edit will be applied. 
12. Transform commands move the object, even when frozen. When using Draft WB move, they don't move
13. Placement command moves the frozen object.
14. Non-reversable operations could be applied to frozen objects (e.g. smooth a frozen mesh). If this is done by accident it is not noticed, as there is no feedback to the user. If the mesh is later unfrozen, the smoothed, decimated shape is visible.
15. The freeze icon is not optimal. It covers the entire icon of the feature, body or object. It is not clear if you want to unfreeze something if this is a body or part container, a spreadsheet or PartDesign features. Maybe it can also be combined with the eye icon as the appearance of the object is *frozen*
6. Could it be placed in the context menu section at the bottom, where "Mark to recompute" and "Recompute" is located, as I understand it's related to that?
7. Could it be renamed? I did not figure out what this is doing and had to look through the PRs. 
Proposals: Exclude from recompute, Lock current state, 
8. Could it have a checkbox like "Active body" (at the top of the context menu), like: [ x ] Locked to see the current state in the context menu

Maybe this is all just my personal preference, @obelisk79 maybe ask DWG about this.

![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/9c7f792e-cc95-4210-a660-861e11f8b0a9)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/fa2253d5-37fb-48f3-8a96-7441f9c45b4e)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36277 (Git)
Build type: Release
Branch: main
Hash: 9e1903d46112b3660bf10c6a4537d728101d560b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.23
  * Defeaturing 1.2.2
  * fasteners 0.5.12
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
@maxwxyz thank you very much for these tests :+1:

**Comment by leoheck** [comment]
This is still an issue @maxwxyz @FlachyJoe. Can we reopen this issue?

After freezing an object... there is no way to unfreeze it or even freeze others.
The context menu item disapears.

Also, can we have the same item on the Edit menu since the feature does not show up in the context menu? 
![image](https://github.com/user-attachments/assets/89265518-7496-42cb-9605-7a20c83e5cf4)

Also, updating info here would be required if this feature is added to the Edit menu.
https://wiki.freecad.org/Std_ToggleFreeze

```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git) AppImage
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
```

**Comment by leoheck** [comment]
Here is the evidence... 
[Screencast from 2024-10-26 11-58-34.webm](https://github.com/user-attachments/assets/a6e46967-eaaa-4a40-b5bf-86e6007924a3)

**Comment by leoheck** [comment]
After restarting FreeCad I cannot find the Freeze function anymore. Is there a specific way to enable this function somehow?

**Comment by FEA-eng** [comment]
> After restarting FreeCad I cannot find the Freeze function anymore. Is there a specific way to enable this function somehow?

Aren't you in Part Design by any chance? There this feature is not accessible.

**Comment by maxwxyz** [comment]
this issue was never closed...

**Comment by leoheck** [comment]
> > After restarting FreeCad I cannot find the Freeze function anymore. Is there a specific way to enable this function somehow?
> 
> Aren't you in Part Design by any chance? There this feature is not accessible.

hm, I was using part design WB. Why is it not accessible with the PD selected? The freeze doesn't work with Bodies?

**Comment by FEA-eng** [comment]
> hm, I was using part design WB. Why is it not accessible with the PD selected? The freeze doesn't work with Bodies?

It works on Bodies but there's a known issue with this option not being shown in PD. So you can apply it to Bodies from another workbench like Part.
