### ISSUE TITLE
[Problem] Addon manager: Python update packages are not installing

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#12834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

From: https://forum.freecad.org/viewtopic.php?p=745923
The Python update packages are not updated. Having started the procedure through "Addon Manager", using the update for a single package or for all packages, it seems to be successful, but restarting "Manage Python Dependencies" always offers to update the same packages even after restarting FreeCAD. 

### Full version info

```shell
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36331 (Git) AppImage
Build type: Release
Branch: main
Hash: eb5a1b333946ce4ac8a4ead835cba8bdcf602a87
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
```

### Subproject(s) affected?

Addon Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gareth8118** [comment]
Also seeing this behaviour on the 0.21.1 64-bit Windows build, fwiw.
