### ISSUE TITLE
[Problem] Addon manager: Readme links reveal blank page

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#12832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you click on the links in a readme a blank page appears. Either the page should be displayed or opened in the default web browser.
Also, items like the translation status (icons on GitHub) are displayed as lists with links. Users might misclick as they expect a translated version of the readme but they also get a blank page 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/894e9adc-1716-40d3-b26e-ba864551bb07)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36277 (Git)
Build type: Release
Branch: main
Hash: 9e1903d46112b3660bf10c6a4537d728101d560b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.23
  * Defeaturing 1.2.2
  * fasteners 0.5.12
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2
```

### Subproject(s) affected?

Addon Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
I cannot reproduce -- when I click on a link in the README it correctly loads in my system browser.

**Comment by APEbbers** [comment]
Hi,

I can reproduce the problem however not every link is a problem. For example the link "user instructions" in Assembly 4 result in a blank page. However the link "quick assembly from scratch" opens in my browser.

**Comment by chennes** [comment]
Is "user instructions" a link to an anchor?

**Comment by APEbbers** [comment]
I'm not sure what you mean by anchor but in the picture below I've marked the hyperlinks:
![image](https://github.com/FreeCAD/FreeCAD/assets/10145631/f2c271ab-564c-45f9-94a9-e7013caad247)

**Comment by chennes** [comment]
I get it -- it's a relative URL, for some reason that's not opening correctly. I'll try writing a processor that makes all of those absolute.

**Comment by maxwxyz** [comment]
@chennes relative URLs are the only one working on my side inside the Addon manager. It does not open external ones.

**Comment by chennes** [comment]
@maxwxyz so I believe what you mean is that internal (anchor) links are working and simply scroll the page, but relative links to other pages are not working, they load a blank page in the addon manager. And presumably full-url links are working correctly and open in an external browser. Is that the case?

**Comment by maxwxyz** [comment]
@chennes yes, internal anchors work. relative (GitHub internal pages) reveal blank pages. Some other external links also show a blank page. Try the AeroFoil macro readme page and click on the `Addon manager` link. This is a link to the wiki but a blank page appears.
