### ISSUE TITLE
Model > (Object) > Set colors yields unexpected tabbed window switch

### ISSUE THREAD

**Issue by shutterfreak** [FreeCAD/FreeCAD#12866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Calling Model > (Object) > Set colors can result in an accidental tab switch.

Steps to reproduce:

1. On the Start page, click "Create new...".
2. In the new project, open the Part workbench
3. Add a Cube
4. Select the Cube in the Model tree, right-click and select "Set colors".

The UI now switches to the Start page tabbed window, which is the first open tabbed window.

Is it possible that the index of the active tabbed page is sometimes accidentally lost or overwritten?

Remarks:
1. this sometimes also happens when toggling object visibility.
2. Is this a macOS-only issue? See e.g. https://github.com/FreeCAD/FreeCAD/issues/10589

### Full version info

```shell
[code]
OS: macOS 14.3.1
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I cannot reproduce on
<details><summary>Windows 11 0.22dev</summary>
<p>

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35758 (Git)
Build type: Release
Branch: sketcher-offset-external-geometry
Hash: 7e8265fb10269566c01bf11d8b1600a5dd81aaa2
Python 3.11.7, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.24
  * Defeaturing 1.2.2
  * fasteners 0.5.13
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2

``` 

</p>
</details>

**Comment by maxwxyz** [comment]
@shutterfreak is this problem still persistent in the latest weekly build: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by shutterfreak** [comment]
> @shutterfreak is this problem still persistent in the latest weekly build: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

I tried to reproduce the steps on the latest weekly build but the user interface has changed. There's no setting to select the Cube in the Model tree, right-click and select "Set colors".
