### ISSUE TITLE
Lockup while loading document/model (CPU 100%, memory 5+GB, Disk 0%, GPU 0% )

### ISSUE THREAD

**Issue by aaronfhamilton** [FreeCAD/FreeCAD#12896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Successfully opened relatively simple model in FreeCAD 19.1, adjusted model display setting, then saved and closed. When attempting to re-open same model several minutes later, FreeCAD locks up. Attempted uninstalling and re-installing, without success. Same behavior on this file, yet others seem to open file.

When loading file, UI shows all white screen with window title bar show "FreeCAD 0.21.2 (Not Responding)".

Followed instruction on FAQ including:

1. Clearing PC cache and contents of FreeCAD %APPDATA% folder
2. Verified correct operation with other files

Attached PDF is export of file/model immediately before saving file.

[FreeCAD Export.pdf](https://github.com/FreeCAD/FreeCAD/files/14569245/FreeCAD.Export.pdf)
[FreeCAD.log](https://github.com/FreeCAD/FreeCAD/files/14569447/FreeCAD.log)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * sheetmetal 0.4.3
[/code]
```

### Subproject(s) affected?

None

### Anything else?

[A-21.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/14569255/A-21.FCStd.zip)
[FreeCAD.log](https://github.com/FreeCAD/FreeCAD/files/14569451/FreeCAD.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Could you also open it without a problem in FC 0.19? I've tried it in 0.22dev and its also not responding.

**Comment by aaronfhamilton** [comment]
No, that's what prompted me to uninstall 0.19 and try 0.21. It opened just fine before I tried adjusting some model surfaces to use white for a display color.

**Comment by xtemp09** [comment]
I tried 0.22dev build on Linux. _FreeCAD_ hangs at `ViewProviderPartExt::updateVisual()`.

https://github.com/FreeCAD/FreeCAD/blob/9140327832b94ea4325dfcf185e2e68659875e47/src/Mod/Part/Gui/ViewProviderExt.cpp#L959


Perhaps an older version of OCCT can open the file correctly.

<details><summary>OCC 7.5.1</summary>

```ruby
OS: Ubuntu 22.04.3 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36338 (Git)
Build type: Debug
Branch: master
Hash: 5b5be480a3a14963cbdefe2e7a3923f9136af6a9
Python 3.10.12, Qt 5.15.12, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/United States (en_US)
```

</details>

<details><summary>OCC 7.6.2</summary>

```ruby
OS: Ubuntu 22.04.3 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20.1)
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
```

</details>

**Comment by wwmayer** [comment]
> When loading file, UI shows all white screen with window title bar show "FreeCAD 0.21.2 (Not Responding)".

This is because the Deviation property of all objects is set to a super tiny value. In your GuiDocument.xml the value is set to ~0.01 while the default is 0.5.

Because of this tiny value the OCC kernel tries to generate a very fine display mesh which is extremely time- and memory-intensive.

A crude workaround is to simply remove the GuiDocument.xml from your project file. This can be done with any zip application.

If you want to keep your GuiDocument.xml then an alternative is to use the Project utility function that allows you to unzip the archive to a destination directory. Fix the GuiDocument.xml file manually by replacing all Deviation values. Then use the function to re-zip the project.

**Comment by aaronfhamilton** [comment]
I keep getting an "invalid document structure" message when trying to open the zipped application again. Tried both removing GuiDocument.xml and modifying it. Are there particular zip settings the app wants?

12:30:22  Fatal Error at file G:/My Drive/Engineering/Antennas/A-21.FCStd, line 1, char 1
12:30:22  Exception message is: 
12:30:22  invalid document structure
12:30:22  <Exception> Error reading compression file: G:/My Drive/Engineering/Antennas/A-21.FCStd
12:30:22  Exception while processing file: G:/My Drive/Engineering/Antennas/A-21.FCStd [Error reading compression file: G:/My Drive/Engineering/Antennas/A-21.FCStd]

**Comment by wwmayer** [comment]
Important for a FCStd file is that Document.xml is the very first file.
Removing the GuiDocument.xml out of it shouldn't change the file order.

To be on the safe side you can use the function from Tools > Document utility
1. Select the FCStd file
2. Select a directory where to extract the file
3. Press the big button labelled "Extract"
4. Open a file explorer and go to the destination directory. Fix the GuiDocument.xml or delete it
5. Go back to FreeCAD and select the path to the Documnet.xml
6. Select a directory where to create your new project file. It can be the same directory as above
7. Press the big button labelled "Create"
8. In the destination directory you should find a file "project.fcstd"

**Comment by benj5378** [comment]
Is this really a bug? Or just a realization of having wrong settings in FreeCAD and a compute intensive model?

**Comment by luzpaz** [comment]
> Is this really a bug? Or just a realization of having wrong settings in FreeCAD and a compute intensive model?

The latter. Closing.
