### ISSUE TITLE
New file format incompatible with previous FreeCAD version

### ISSUE THREAD

**Issue by Zolko-123** [FreeCAD/FreeCAD#12894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Some recent modifications in FreeCAD make new files created with the latest weekly builds of FreeCAD incompatible with previous FreeCAd versions. Is this incompatible change of file format for the upcoming v0.22 release discussed and documented somewhere ?

How to reproduce:

With the latest built (tried with 0.22.0dev.36277)

- create a new document
- in the PartDesign workbench, create a new Body
- create a new sketch, along plane XY for example (sketch is attached to plane XY)
- draw something on sketch
- close
- update model
- close and exit

open stable FreeCAD version 0.21.2 (0.21.2R33771) and open previous file : the sketch is not attached anymore. When doing the same with a more realistic part, all the sketches are un-attached, and there are many errors:

![attachment_error](https://github.com/FreeCAD/FreeCAD/assets/46596542/7dd8f854-4ba0-486f-8412-3e64d0babebd)

Seems to be related to https://github.com/FreeCAD/FreeCAD/pull/12714

### Full version info

```shell
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36277 (Git) AppImage
Build type: Release
Branch: main
Hash: 9e1903d46112b3660bf10c6a4537d728101d560b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US) [ OS: English/United Kingdom (en_GB) ]
Installed mods: 
  * A2plus 0.4.56a
  * CurvedShapes 1.0.3
  * fcgear 1.0.0
  * sheetmetal 0.2.50
  * TabBar
  * Render 2022.2.0
  * Curves 0.5.1
  * fasteners 0.4.75
  * Assembly4_GitHub 0.50.10-dev
  * BillOfMaterials-WB-main.zip
  * BillOfMaterials 0.0.3




OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US) [ OS: English/United Kingdom (en_GB) ]
Installed mods: 
  * A2plus 0.4.56a
  * CurvedShapes 1.0.3
  * fcgear 1.0.0
  * sheetmetal 0.2.50
  * TabBar
  * Render 2022.2.0
  * Curves 0.5.1
  * fasteners 0.4.75
  * Assembly4_GitHub 0.50.10-dev
  * BillOfMaterials-WB-main.zip
  * BillOfMaterials 0.0.3
```

### Subproject(s) affected?

File formats

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
The lack of the SuppressibleExtension doesn't break the model: a Suppressed feature is unsuppressed and shown correctly **after a recompute**.

I confirm Sketch Support disappear.

In any case, backwards compatibility is not a target for 0.22… 😐

**Comment by FlachyJoe** [comment]
@maxwxyz I think the Regression label is for the current dev state, not for a 0.21 backport request.

**Comment by Zolko-123** [comment]
actually ... an incompatible file format is a very good reason for a fork. Please continue like this

**Comment by FlachyJoe** [comment]
@Zolko-123 forward compatibility is a target, not backward. Else we can't improve the soft.

**Comment by yorikvanhavre** [comment]
It's not a change in the file format. The file format does not specify property names. Also, the current master code can break, it's even written on the splash screen, do not use for production.

But there is a point here nevertheless, people might need to get back to previous versions for some reason. it might be a good idea to indeed offer people a possible fix or workaround. Any idea @adrianinsaval ?

**Comment by yorikvanhavre** [comment]
Yes I'm not sure it's worth it, specially that I'm not sure we'll have many more 0.21 point releases... Maybe we could have a small macro ready when we publish a new release, that users could run to backport their file when needed...

**Comment by FlachyJoe** [comment]
Or a "0.21 compatible" file type for export?

**Comment by yorikvanhavre** [comment]
> Or a "0.21 compatible" file type for export?

Probably most users won't need this anyway... Better no to impose something to everybody.

I'll prepare a macro

**Comment by yorikvanhavre** [comment]
Done: https://wiki.freecad.org/Macro_Convert_021

**Comment by Zolko-123** [comment]
That macro is useless for assemblies with linked files

**Comment by FlachyJoe** [comment]
@Zolko-123 with some modifications you can select multiple files

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ***************************************************************************
# *                                                                         *
# *   Copyright (c) 2024 Yorik van Havre <yorik@uncreated.net>              *
# *                      Florian Foinant-Willig <ffw@2f2v.fr>               *
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU General Public License (GPL)            *
# *   as published by the Free Software Foundation; either version 3 of     *
# *   the License, or (at your option) any later version.                   *
# *   for detail see the LICENCE text file.                                 *
# *                                                                         *
# *   This program is distributed in the hope that it will be useful,       *
# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
# *   GNU General Public License for more details.                          *
# *                                                                         *
# *   You should have received a copy of the GNU Library General Public     *
# *   License along with this program; if not, write to the Free Software   *
# *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *
# *   USA                                                                   *
# *                                                                         *
# ***************************************************************************

"""This macro opens a file dialog to allow to choose a FreeCAD file
and converts it to 0.21 format (replace AttachmentSupport property to Support).
A new file with extension .021.FCStd is created so the original file is not modified"""
import os
import zipfile
from PySide import QtGui

filenames = QtGui.QFileDialog.getOpenFileNames(None,
                                             "Open FreeCAD file",
                                             None,
                                             "FreeCAD Files (*.FCStd *.fcstd)")
for filename in filenames[0]:
    print("Processing", filename, "...")
    spl = os.path.splitext(filename)
    filename021 = spl[0] + ".021" + spl[1]
    with zipfile.ZipFile(filename) as inzip, zipfile.ZipFile(filename021, "w") as outzip:
        for inzipinfo in inzip.infolist():
            with inzip.open(inzipinfo) as infile:
                if inzipinfo.filename == "Document.xml":
                    content = infile.read()
                    content = content.replace(b"AttachmentSupport", b"Support")
                    outzip.writestr(inzipinfo, content)
                else:
                    outzip.writestr(inzipinfo, infile.read())
    print(filename021, "successfully written")

print ("All done!")
```

**Comment by komoricodrutz** [comment]
Hi all,
I submitted the bug #13178 yesterday. Sorry, somehow I didn't find this bug here.
I just tested the macro mentioned here, but the behaviour is exactly the same as the one I had in the original bug report.
Getting spammed with the following errors in 0.21 after converting the file using this macro:
`No extension found of type 'App::SuppressibleExtension'`
`No extension found of type 'Gui::ViewProviderSuppressibleExtension'`

And to further address the necessity of some way of switching between different versions of FreeCad:
I've been using the daily build for years now. It always has more and better features, even if it sometimes unstable. Although the recommendation is clear, to NOT use the daily build as a daily driver because it is unstable, it is actually the best way for people to test it and provide bug reports and only switch to the stable build if there is a bug which seriously affects one's work. If one "normal" user only tests the daily build once in a while, the probability of finding and submitting bugs will be a lot lower. And here is the main reason why either an update to the 0.21 version, to accept 0.22 files or a good conversion option becomes critical. We should have the chance to keep working on our projects in the stable version while the bugs from the daily build are ironed out.

<details>
<summary>Stable version Build Details</summary>

```

OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * BOLTSFC 2022.11.5
  * A2plus 0.4.64
  * Lithophane
  * Assembly4 0.50.12
  * Glass
  * fasteners 0.5.15
  * fcgear 1.0.0


```

</details>

<details>
<summary>Daily version Build Details</summary>

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36633 (Git)
Build type: Release
Branch: main
Hash: 360e280c64c56f1a083645f566cc4125330703f8
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * BOLTSFC 2022.11.5
  * A2plus 0.4.64
  * Lithophane
  * Assembly4 0.50.12
  * Glass
  * fasteners 0.5.15
  * fcgear 1.0.0

```

</details>

**Comment by FlachyJoe** [comment]
> `No extension found of type 'App::SuppressibleExtension'`
> `No extension found of type 'Gui::ViewProviderSuppressibleExtension'`

These errors don't break the model and can be ignored. If features as been suppressed a document recompute (RMB the document in the tree, Mark to Recompute and then recompute) unsuppress them and the model is fully usable.
