### ISSUE TITLE
App::Part: Random color not working

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#12891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Assigning a random color to App::Part containers does not work:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/caeeaff8-a538-4e99-904c-b3490c8fc533)

Ideally, all sub objects should get a random color.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35758 (Git)
Build type: Release
Branch: sketcher-offset-external-geometry
Hash: 7e8265fb10269566c01bf11d8b1600a5dd81aaa2
Python 3.11.7, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.24
  * Defeaturing 1.2.2
  * fasteners 0.5.13
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
This is not an assembly issue, it's a App::Part issue. (assembly object derives from app::part)

**Comment by maxwxyz** [comment]
thanks, updated title and description.
