### ISSUE TITLE
Cloned objects misplaced in .stl exports

### ISSUE THREAD

**Issue by SnowmanPacha** [FreeCAD/FreeCAD#12903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Draft_Clone parts with modified placement appear at the right place on screen, but when exported in a .stl or .3mf file the cloned parts are misplaced, as if the placement modifiers were applied twice (90° rotation becomes 180°, 10mm translation becomes 20mm...)

### Full version info

```shell
[code]
OS: macOS 14.3.1
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

Draft

### Anything else?

<img width="2056" alt="Capture d’écran 2024-03-12 à 15 43 50" src="https://github.com/FreeCAD/FreeCAD/assets/87668163/40eb851d-9105-4c91-9d60-b10c1f5e6203">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@SnowmanPacha is the PartContainer transformed or rotated? Could you share a demo file?

**Comment by SnowmanPacha** [comment]
@maxwxyz Hello !
Here is a brand new demo file with the resulting .stl. 
Only the 2 clones are translated or rotated. The englobing Part and the original Cube and Cone are unmodified. In the stl though the clones are translated/rotated of twice the amount.
[ClonePlacementBug.zip](https://github.com/FreeCAD/FreeCAD/files/14576791/ClonePlacementBug.zip)

**Comment by maxwxyz** [comment]
How do you export that .stl? If I select the part container and export as .stl and import it again, it is exactly the same as the part.
[ClonePlacementBug-Part.zip](https://github.com/FreeCAD/FreeCAD/files/14576866/ClonePlacementBug-Part.zip)

**Comment by SnowmanPacha** [comment]
I select the Part, Select File/Export, option STL mesh(*.stl *.ast)

Until today this would work fine.

**Comment by SnowmanPacha** [comment]
But when I re-import it, or visualise it with MacOS Finder or with Prusa slicer, I get this:
![Capture d’écran 2024-03-12 à 19 16 50](https://github.com/FreeCAD/FreeCAD/assets/87668163/7a31bfc1-7433-4a29-8dc1-1a2ac22a59d0)

**Comment by SnowmanPacha** [comment]
I have tried with an old Intel Mac (FreeCAD 0.19-24291), it works fine.
The issue seems linked to this version of FreeCAD (0.21.2-33771), or to this installation on a Mac with M3Pro chipset.
I removed FreeCAD and its Library/ApplicationSupport files, and downloaded again (same software version as previously unfortunately), it didn't solve anything.

**Comment by maxwxyz** [comment]
Could you try it with the current weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by wwmayer** [comment]
It was working fine with older v0.21 releases:
```
OS: Ubuntu 22.04.4 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33702 (Git)
Build type: Unknown
Branch: releases/FreeCAD-0-21
Hash: 4d98082de01dc6a5ea563265ffd1f8c1963857c6
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
```

The regression was caused with https://github.com/FreeCAD/FreeCAD/commit/9d03a07005de7b4bf88b9f4dde981263cbefa98e
In v0.22 we had the same regression that was fixed but not in v0.21: https://github.com/FreeCAD/FreeCAD/commit/b1a96bde5ff66adbb371cdbf58f470b60b9af8f4

**Comment by wwmayer** [comment]
Fixed with https://github.com/FreeCAD/FreeCAD/commit/3aa6e37bb2c76e07ac68f42dfecf2a92b4c32aa9

**Comment by SnowmanPacha** [comment]
Yes, this version corrects the bug !
Many thanks for the solution and for the explanations.
