### ISSUE TITLE
DirectWrite: CreateFontFaceFromHDC() failed

### ISSUE THREAD

**Issue by Manuelzwei** [FreeCAD/FreeCAD#12915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Error after new installation, when starting, before opening an existing file:
![FreeCAD Font missing Error](https://github.com/FreeCAD/FreeCAD/assets/127152437/5d9492bc-b044-4fd2-95b3-1f4ab0b4d8ff)

Where is the 8514oem font located on my PC? 

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Luxembourg (de_LU)
Installed mods: 
  * kicadStepUpMod 10.17.1
  * offline-documentation 1.0.0-alpha
  * sheetmetal 0.3.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Manuelzwei** [comment]
Thank you for reply.
I see this error by an upgrade. So I deinstall FreeCAD, reboot and install it new. The same error was shown.

**Comment by Manuelzwei** [comment]
FreeCAD 0.22.0dev: same situation.

I'm getting a new Windows 11 PC this weekend. Then I reinstall everything and try it again

**Comment by luzpaz** [comment]
Related to #10555 ?

**Comment by Manuelzwei** [comment]
> Related to #10555 ?

Yes, I have 125% DPI. So I think it was the same as #10555.
I to set my DPI to 100% and it was all right.

Thank you.
