### ISSUE TITLE
Suppressed features are still transformed by pattern features

### ISSUE THREAD

**Issue by NomAnor** [FreeCAD/FreeCAD#12914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

A suppressed feature is transformed normally when used in a pattern feature. Suppressed features should be ignored.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36338 +18 (Git)
Build type: Debug
Branch: integration
Hash: 65582efdd0d9407951a6fc996cb36662efb7b2c9
Python 3.11.8, Qt 5.15.12, Coin 4.0.2, Vtk 9.3.0, OCC 7.3.0
Locale: German/Germany (de_DE)
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.60.0
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.0.0
  * Assembly3 0.11.3
  * QuickMeasure 2022.10.28
  * fasteners 0.4.21
```

### Subproject(s) affected?

PartDesign

### Anything else?

I think there are two solutions:
1. Check for suppression in the pattern code
2. Set the AddSubShape to a Null shape.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FlachyJoe

**Comment by FlachyJoe** [comment]
@maxwxyz please assign me

**Comment by NomAnor** [comment]
In my dev branch I just added a check to the FeatureTransformed (based on #12537) between these lines:
https://github.com/FreeCAD/FreeCAD/blob/b2c47a2a1933ae451f425539286ca5133b836df1/src/Mod/PartDesign/App/FeatureTransformed.cpp#L268-L270

So far this seems to work fine.

A more general solution, that does not require special handling in other features would be better, but for now I think this is reasonable.

**Comment by FlachyJoe** [comment]
@NomAnor if your fix allow to

- Create a new pattern of a suppressed feature with no change on geometry
- Update a pattern of an unsuppressed feature with the good changes
- Suppress a pattern

then I won't look further and let you do a PR.

**Comment by FlachyJoe** [comment]
@NomAnor you can already open a draft PR that fails to compile with the "require #12537" mention so the code can be discussed.
