### ISSUE TITLE
FEM MaterialFluid doesn't show fluid materials at all

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#12933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the current weekly builds, [FEM MaterialFluid](https://wiki.freecad.org/FEM_MaterialFluid) doesn't show any fluid materials, Those should be Air, Argon, Carbon_dioxide, Nitrogen, Water (from 0.21.2). Possibly, only fluid materials should be shown.

Forum discussion: https://forum.freecad.org/viewtopic.php?t=86085

@davesrocketshop 

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davesrocketshop** [comment]
Looking into it
