### ISSUE TITLE
Qt6 build failed - src/Mod/Drawing/Gui/Command.cpp requires QRegExp missing in qt6

### ISSUE THREAD

**Issue by mark-herbert42** [FreeCAD/FreeCAD#12953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Trying to build freecad with qt6 on Gentoo linux and get failure because of QRegExp missing.  The only place where this thing remains is here
src/Mod/Drawing/Gui/Command.cpp 

and this destroys the build.
 

### Full version info

```shell
Tried 21.2 and git snaphot.   All the same.
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/12976
