### ISSUE TITLE
CAM: Path/Dress UP/Lead IN/OUT .... in 0.22.0 dev breaks GCode Simulation

### ISSUE THREAD

**Issue by ShamanTcler** [FreeCAD/FreeCAD#12951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Created simple block, applied a profile toolpath. Added lead in/out. Get this error than hangs.

07:49:43  Traceback (most recent call last):
07:49:43    File "C:\FreeCadBeta\Mod\Path\Path\Main\Gui\Simulator.py", line 397, in PerformCut
07:49:43      self.PerformCutVoxel()
07:49:43    File "C:\FreeCadBeta\Mod\Path\Path\Main\Gui\Simulator.py", line 343, in PerformCutVoxel
07:49:43      dz = (cmd.z - self.curpos.Base.z) / n
07:49:43  TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

Doing the same operation in Version 0.21 has no issues.

Test file is LeadInTest.zip for LeadInTest.FCStd

### Full version info

```shell
OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36277 (Git)
Build type: Release
Branch: main
Hash: 9e1903d46112b3660bf10c6a4537d728101d560b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Curves 0.6.23
```

### Subproject(s) affected?

None

### Anything else?

[LeadinTest.zip](https://github.com/FreeCAD/FreeCAD/files/14601714/LeadinTest.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shaise** [comment]
The file seems to work well with the new simulator. As the old one is being deprecated soon, I think this issue can be closed
