### ISSUE TITLE
[Feature Request] Part Design --> Measure Linear tool does not measure Circular Edges

### ISSUE THREAD

**Issue by HarrisonLeece** [FreeCAD/FreeCAD#12971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Measure Linear tool does not measure circular (arc) edges, it would be useful for the measure tool to indicate the diameter or radius of a curve.

### Full version info

```shell
Using 0.21.1
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@HarrisonLeece I think this will be solved with https://github.com/FreeCAD/FreeCAD/issues/8561
Please check out https://forum.freecad.org/viewtopic.php?t=78147 and confirm
