### ISSUE TITLE
Curves WB doesnt run on FreeCad 0.22 Dev snap verrsion (probaly due to old numpy libray in snap package)

### ISSUE THREAD

**Issue by projectcad** [FreeCAD/FreeCAD#12988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Curves WB doesnt run on FreeCad 0.22 Dev snap verrsion .....probaly due to old numpy libray in snap package

thanks in advance....

![FreeCad_022_CurvesWB_Problem](https://github.com/FreeCAD/FreeCAD/assets/68682837/a7bdf656-7b9c-4277-ae55-cc9092b67fa6)

### Full version info

```shell
OS: Ubuntu Core 22 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36442 (Git) Snap 957
Build type: Release
Branch: main
Hash: bcf54d3153fe4cad841ff7c0b692506eaa802103
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
Installed mods: 
  * Curves 0.6.28
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
is this related to the main FreeCAD or shouldn't this be fixed in the Curves WB repo?

**Comment by luzpaz** [comment]
...or https://github.com/FreeCAD/FreeCAD-snap ?

**Comment by projectcad** [comment]
i dont what actually was corrrected but it is ok after last update today

**Comment by projectcad** [comment]
maybe this one corrected  ....https://github.com/FreeCAD/FreeCAD/commit/655d5e4fbd71053ebf3e37345d5c33e9cbee9f52
