### ISSUE TITLE
Qt6 build failing ‘class QStyleOptionButton’ has no member named ‘init’

### ISSUE THREAD

**Issue by mark-herbert42** [FreeCAD/FreeCAD#12997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description
First issue 

src/Tools/plugins/widget/customwidgets.cpp:1836:9: error: ‘class QStyleOptionButton’ has no member named ‘init’

Second issue  - there are several  lines with code like this in the same file 

src/Tools/plugins/widget/customwidgets.cpp:298:44: error: use of deleted function ‘constexpr void Qt::operator+(QFlags<Modifier>::enum_type, int)’
  298 |             QKeySequence keyseq(Qt::CTRL + key);

### Full version info

```shell
Seems like API has changed. This file is the only place wheere QStyleOptionButton is used in FreeCAD. 

Used git snapshot for compile
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@mark-herbert42 could you provide more info? On what system and how did you try building?

**Comment by mark-herbert42** [comment]
Gentoo, ebuild freecad-9999, loading the git snaphot directly before build. Before todays patches fixing QRegExp it was failing before reaching this point.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/13004
