### ISSUE TITLE
CMake Error:  Could not find a package configuration file provided by "Shiboken"

### ISSUE THREAD

**Issue by joe9** [FreeCAD/FreeCAD#13]
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found OpenGLU: /usr/lib64/libGLU.so
-- Found Spnav: /usr/lib64/libspnav.so  
CMake Error at CMakeLists.txt:466 (find_package):
  By not providing "FindShiboken.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Shiboken",
  but CMake did not find one.
  Could not find a package configuration file provided by "Shiboken" with any
  of the following names:
    ShibokenConfig.cmake
    shiboken-config.cmake
  Add the installation prefix of "Shiboken" to CMAKE_PREFIX_PATH or set
  "Shiboken_DIR" to a directory containing one of the above files.  If
  "Shiboken" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!

**Comment by chennes** [comment]
Closing pending migration of bugs from Mantis.
