### ISSUE TITLE
Sketcher: Tool parameters focus issue (see transform tool)

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There is a severe focus bug in sketcher's tool widgets, where clicking on the spinboxes have erratic results.
It is especially visible in transform tool when you try to interact with the spinboxes.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
related to https://github.com/FreeCAD/FreeCAD/issues/12495 ?

**Comment by PaddleStroke** [comment]
I think #12495 is probably fixed by my opened PR. Though I am not sure I
can't test right now.

**Comment by FEA-eng** [comment]
Is this still relevant? What are the exact steps to reproduce?
