### ISSUE TITLE
Better Surface with Edges mode of the FEM results pipeline

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#13017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The _Surface with Edges_ mode of the FEM results pipeline shows this:

![mesh](https://github.com/FreeCAD/FreeCAD/assets/59876896/e41fd6b9-2822-4d31-8acb-10e28055879b)

I really don't like the poorly visible gray element edges. In ParaView, the edge color can be changed:

![edge color](https://github.com/FreeCAD/FreeCAD/assets/59876896/a5607fbf-1a46-49e3-9bcc-e482c36317fb)

But you may also notice that ParaView shows the actual solid mesh which was generated and used for FEM analysis:

![mesh 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/78dbcabe-171d-4d9a-8664-1812810787b2)

while FreeCAD displays a mesh with more triangles. This can be really misleading. It might be related to this: https://forum.freecad.org/viewtopic.php?t=78598 and thus hard to fix but maybe it's a less complex issue.

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FEA-eng I think they are currently not grey but the color of the label (changing color in your example). I think there is a way of displaying only edges and then you could not see the color if they are all black.

**Comment by FEA-eng** [comment]
> @FEA-eng I think they are currently not grey but the color of the label (changing color in your example). I think there is a way of displaying only edges and then you could not see the color if they are all black.

Right, I mentioned grey because of this _None_ field mode:

![mesh](https://github.com/FreeCAD/FreeCAD/assets/59876896/df4b8154-1ee4-47b2-b4c8-c7dda82dfc3c)

But in contour plots, the edges somehow blend with the contours. They are way too thin and poorly visible.The edge-only (_Wireframe_) mode looks like this:

![mesh 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/adce1ffa-04cf-45bc-bb10-b3d5d9cff68a)

It shouldn't be black indeed. But in ParaView, the edge color setting applies only to the _Surface with Edges_ mode, the _Wireframe_ one looks like in FreeCAD and doesn't even have this setting displayed.

**Comment by FEA-eng** [comment]
> We can add options to set wireframe line width, node point size, and a boolean 'PlainColorEdgeOnSurface' with the associated color property.

That would be ideal. But it would have to be added for all filters that can belong to the pipeline as well since they have the same rendering modes.

Do you know if it's possible to display the surface mesh properly (without additional triangles)?

**Comment by marioalexis84** [comment]
>  But it would have to be added for all filters that can belong to the pipeline as well since they have the same rendering modes.

Do you mean that all the objects in the pipeline change the mode automatically according to the mode of the currently displayed object? Or that the proposed properties are available for all types of filters?

> Do you know if it's possible to display the surface mesh properly (without additional triangles)?

I'll try to solve it.

**Comment by FEA-eng** [comment]
> Do you mean that all the objects in the pipeline change the mode automatically according to the mode of the currently displayed object? Or that the proposed properties are available for all types of filters?

The latter. Not for all filters but at least for most of them. Perhaps they should use the same settings as their parent pipeline by default. And maybe even the pipeline or the previous filter should be hidden automatically when a new filter is added. Because currently, you have to set the mode and field for each new filter and hide the previous ones to make it visible. But that's another topic.

> I'll try to solve it.

Thanks, that would be nice. It's nothing urgent but could improve postprocessing.

**Comment by marioalexis84** [comment]
Properties added to the FemPostObject base class are inherited by all filters. Then we can discuss the default values.

**Comment by marioalexis84** [comment]
That's another topic because Field values are specific to the solver and type of analysis. The core Fem objects should not know anything about the solver used.
I have a solution in mind for that, but I still have to implement the code.
