### ISSUE TITLE
Material editor input fields show zero and non-editable values for non-zero properties

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#13020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I open the material editor, select some material and double-click on one of its defined properties, the input field shows zeros even though the property is non-zero. If I enter a value, nothing changes.

![zero properties](https://github.com/FreeCAD/FreeCAD/assets/59876896/0d274ec8-5eb2-4464-ad6a-47bc386603e5)

@davesrocketshop FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davesrocketshop** [comment]
There were several issues here, not just one. Hence the longer than expected time frame. The following are fixed:

- Incorrect display of Quantity items (NaN)
- Editing and updating quantity items
- Editing and updating items on the first row.

There are still issues with editing lists, but these were known issues at the time of initial merge. This has been split out into issue #13435
