### ISSUE TITLE
Inconsistent chamfer generation in Sketcher

### ISSUE THREAD

**Issue by prokoudine** [FreeCAD/FreeCAD#13049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Every time you click on a point with the new Chamfer tool, you get a different result.

https://github.com/FreeCAD/FreeCAD/assets/57467/1af32eb2-3fb3-4b64-a11a-22b92b7efb6e

### Full version info

```shell
OS: Ubuntu 23.10 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36487 (Git)
Build type: Unknown
Branch: main
Hash: f5baef888c25937026ee50001a4fe4293a9f11ee
Python 3.11.6, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * ExtremeProDark 2.9.0
  * DynamicData 2.60.0
  * Assembly4 0.50.6
  * ExplodedAssembly
  * sheetmetal 0.3.15
  * BIM 2021.12.0
  * A2plus 0.4.61
  * Render 2023.12.28
  * Rocket 3.2.4
  * Curves 0.6.21
  * freecad.gears 1.2.0
  * Assembly3 0.12.0
  * boltsfc 2022.11.5
  * OpenDark 2023.12.17
  * dodo 1.0.0
  * Ondsel-Lens 2023.12.13.01
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
I think the problem comes from 
https://github.com/FreeCAD/FreeCAD/blob/cf37713fc661583c48d60c515df2ce427ff15c3f/src/Mod/Sketcher/App/SketchObject.cpp#L2142

Changing to `p1 = arc->getStartPoint(true);` probably fix the issue.

I will test and PR as soon as I checkout.
