### ISSUE TITLE
TechDraw: Double clicking on a page does not switch workbench to TechDraw

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In sketcher double clicking on a sketch changes the active workbench to sketcher.
Similarly double clicking on an assembly switch active workbench to assembly.
Double clicking a body opens PD.

For consistency we could have the same behavior when double clicking on a page, switch to techdraw.
Thoughts on this?

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Sketcher is the only place this happens (at least out of the pieces of FC that I use).  It doesn't happen for TD, Spreadsheet or Draft.  So I'm not sure this advances the cause of consistency.

I like the idea, though.  I've wasted lots of time looking at a spreadsheet, thinking I'm in SpreadsheetWB, pressing keys and not getting the expected response.

**Comment by PaddleStroke** [comment]
Perhaps then it would be good to implement that in spreadsheet as well. In draft I'm not sure in which context that could happen. It's not like there is a main 'draft object'.

**Comment by PaddleStroke** [comment]
https://github.com/FreeCAD/FreeCAD/issues/13136
