### ISSUE TITLE
TechDraw: Radius/Diameter of Ellipses are approximates

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/52956c55-f5cb-4aa0-ae34-80961b49c719)
When you try to apply a radius or a diameter to an ellipse it gives you an approximate value.
I would say that ellipses in techdraw are almost allways circles viewed from an angle. So it would make more sense to show by default the major radius rather than an approximation.
I don't think there is any usecase in showing an approximation rather than the major radius.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I guess we need more discussion to this topic.

**Comment by WandererFan** [comment]
The major radius of the ellipse is not necessarily the radius of the original circle.
