### ISSUE TITLE
FEM element geometry icons should be improved

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#13143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Likely the last set of FEM icons needing improvement:

1. [Element geometry 1D](https://wiki.freecad.org/FEM_ElementGeometry1D)

![FEM_ElementGeometry1D](https://github.com/FreeCAD/FreeCAD/assets/59876896/26a93332-17af-46f3-9f3f-ab62e8185549)

It's supposed to represent beam cross-section but it doesn't really look like one. I would suggest a rectangular (maybe partially transparent if possible) or pipe section with a visible centerline:

![beam](https://github.com/FreeCAD/FreeCAD/assets/59876896/2f709941-14a9-4ab2-beca-1f02cae6ef37)

2. [Element rotation 1D](https://wiki.freecad.org/FEM_ElementRotation1D)

![FEM_ElementRotation1D](https://github.com/FreeCAD/FreeCAD/assets/59876896/cc57de45-f23d-4fca-9033-6ac7168f4260)

It should be the same as the first one but with an arrow showing rotation like now. If rectangular section is chosen for the first icon then this one can actually show it rotated:

![beam 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/02a517e9-3426-4d44-a132-5f921cf7b8db)

3. [Element geometry 2D](https://wiki.freecad.org/FEM_ElementGeometry2D)

![FEM_ElementGeometry2D](https://github.com/FreeCAD/FreeCAD/assets/59876896/707e83c1-9486-4862-a44e-b69d4b6f14d5)

It's not bad but could be simpler - it should only show 2D element thickness definition. And the red area seems misplaced. If it's supposed to indicate the geometry to which thickness is assigned then it would make more sense at the top (but then the top face should be more visible).

4. [Element fluid 1D](https://wiki.freecad.org/FEM_ElementFluid1D)

![FEM_ElementFluid1D](https://github.com/FreeCAD/FreeCAD/assets/59876896/64d78413-78a6-4d6e-8b24-94d255fbcfe4)

This is for 1D flow sections. The "1D" text is IMO unnecessary and the arrows are poorly visible. It could be just a line with 2 arrows (entering and exiting it):

![flow 1D](https://github.com/FreeCAD/FreeCAD/assets/59876896/6ae20fef-93ea-4709-89dc-b8c02f830173)

Maybe with some indication that it's a fluid flow.

@maxwxyz FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FEA-eng I've added them to the same PR

**Comment by FEA-eng** [comment]
> @FEA-eng feedback: 

Thanks a lot, I have some suggestions here if you don't mind:
- ElementFluid1D could have blue arrows (more associated with a flow), I would also get rid of the lines showing the mesh here and leave only the outer edges of the cylinder itself
- ElementGeometry1D and ElementRotation1D symbols should have a circular red bar inside indicating a thick line, maybe they could be also made longer
- ElementGeometry2D should have the red surface in the middle of the transparent cuboid (better than at the top or bottom because it's modeled as mid-surface like centerline in the 1D case)

**Comment by maxwxyz** [comment]
@FEA-eng better: 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/92175bea-e7c5-4c74-9874-f3906ec1508e)
