### ISSUE TITLE
TechDraw: 'Insert spreadsheet view' could not need a tool.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/503a105c-76b0-465d-9d77-89b63c2c8ba4)

In TechDraw we have a tool called 'Insert Spreadsheet view'. This tool could be removed.

The 'Create view' tool should check object type when triggered, and if the selected object is a spreadsheet, then it creates a 'sheet view' object.

I have not tested yet but perhaps the same is true for 'Draft view' and 'arch view'.

@WandererFan thoughts?

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Very good idea to reduce the toolbar clutter if only the "Create view" tool can handle such versatility and switch to proper mode without having to rewrite it completely. This would eliminate the need for 3 tools (I'm pretty sure that if "Insert Spreadsheet View" can be replaced this way then its equivalents for Draft and Arch objects can be treated like that too).
