### ISSUE TITLE
Some FEM mesh icons should be improved

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#13141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Following #13125, there are 3 FEM mesh icons that should IMO be improved:

1. [Mesh group](https://wiki.freecad.org/FEM_MeshGroup)

![FEM_MeshGroup](https://github.com/FreeCAD/FreeCAD/assets/59876896/d15ce4ac-3abd-428f-bf0a-40421229acfb)

This tool creates groups of mesh entities based on geometric entities (nodes on this face belong to this group, on that face to that group and so on). The icon shows this but I think that it could be shown on a single mesh object (big cube) - as a similar red outline including some elements.

2. [Mesh region](https://wiki.freecad.org/FEM_MeshRegion)

![FEM_MeshRegion](https://github.com/FreeCAD/FreeCAD/assets/59876896/0b1c3642-56ee-45aa-8116-3fd916c9dfd4)

This tool is used for mesh refinement. The icon doesn't show it. The red color should cover elements along the whole edge and possibly include changing mesh density (more elements in that red region). Something like the next icon.

3. [Mesh boundary layer](https://wiki.freecad.org/FEM_MeshBoundaryLayer)

![FEM_MeshBoundaryLayer](https://github.com/FreeCAD/FreeCAD/assets/59876896/d424d037-972d-4ad8-a89e-3208ba703f78)

This one is not bad but too similar to what Mesh region should represent. IMO the icon should show that it's meant for flows. I would choose a simple 2D case like a square pipe:

![boundary layer](https://github.com/FreeCAD/FreeCAD/assets/59876896/cbf6582c-53f1-4ce7-9019-b3918375ae88)

@maxwxyz FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FEA-eng feedback for the first 2: 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/d7e37dc8-1a88-41c9-91a9-9abdeb9051ab)

**Comment by FEA-eng** [comment]
> @FEA-eng feedback

Looks really great, thank you. Just one small thing - the FEM_MeshRegion icon should have the refinement and red highlight only on the two main rows surrounding that vertical edge:

![316523342-75bbe16c-a141-4761-8957-19010e6f1370](https://github.com/FreeCAD/FreeCAD/assets/59876896/cb22b58d-4cc7-402b-b41c-d7d92fb6265b)

**Comment by maxwxyz** [comment]
@FEA-eng better?
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/cc5d6885-8447-410f-bc3d-db6eb6d54550)

**Comment by FEA-eng** [comment]
> @FEA-eng better? 

Sure, perfect 👍
