### ISSUE TITLE
HTML export fails if document contains Draft arrays: 'Gui.ViewProviderLink' object has no attribute 'ShapeColor'

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This seems related to #[6516](https://github.com/FreeCAD/FreeCAD/issues/6516). Other users reported it in the forum: https://forum.freecad.org/viewtopic.php?t=85078

Steps to reproduce:

1. Open attached file
2. Select "Project" in the tree
3. Go to the "File > Export..." menu
4. On the export dialog, select the "WebGL file (*.html)" option in the "Files of type" dropdown
5. Press "OK"
6. Export fails with the following traceback:

```python traceback
09:26:45  pyException: Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/snap/freecad/966/usr/Mod/Arch/importWebGL.py", line 696, in export
    color = Draft.getrgb(obj.ViewObject.ShapeColor, testbw = False)
<class 'AttributeError'>: 'Gui.ViewProviderLink' object has no attribute 'ShapeColor'
```

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36534 (Git) Snap 966
Build type: Release
Branch: main
Hash: d5b90e50af6a758af748179f289bb8f09e357266
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * BIM 2021.12.0
  * Assembly4 0.50.12
  * ExplodedAssembly
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36534 (Git) Snap 966
Build type: Release
Branch: main
Hash: d5b90e50af6a758af748179f289bb8f09e357266
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * BIM 2021.12.0
  * Assembly4 0.50.12
  * ExplodedAssembly
```

### Subproject(s) affected?

Draft

#### Files
File to reproduce: [Columns.zip](https://github.com/FreeCAD/FreeCAD/files/14755112/Columns.zip)

#### Workaround

1. Select the array in the document
2. In the Draft workbench use the "Modification > Downgrade" menu option or the associated toolbar button
3. Once the individual array elements are downgraded to solids, the export works 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by m1cha1** [comment]
There are other objects where HTML export does not work, such as Part and Assembly containers (maybe also others). You can test it with the assembly example from Freecad. 
With #13162 there will be no error message but the exported file will be empty.
