### ISSUE TITLE
TechDraw: 'Template' object brings nothing to be stand-alone

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/25b6afac-771e-42da-a83c-7d7b5c46576e)
In techdraw when you click on insert default page, you get a page and a child template object.

I do not see why page and template and made separate objects. It brings no functionality and just clutter the tree.
Suggestion : 
Merge the template properties inside the page object.
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/2d2d39b8-8cf1-42d7-8e7b-51c0e55da88f)

Forum discussion : https://forum.freecad.org/viewtopic.php?t=86271

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Is it possible to copy the template object to another page or FC document?

**Comment by PaddleStroke** [comment]
But that wouldn't make much sense to do so. As the template is basically a link to the SVG file. You can just set the link to the same.

**Comment by WandererFan** [comment]
Maybe it is my background, but I would not spend scarce devel resources on this.  It works, doesn't cause any real problems, why change it?

**Comment by PaddleStroke** [comment]
I don't say it's a priority, but a small unecessary complexity.

Of course it is not a big thing and doesn't cause problem. But it's useless and clutters hence increasing software complexity, even if a little bit. And small streams make big rivers.

So if it's not hard to fix, why not doing it? If it's very big or annoying then indeed it may not be worth the hassle.

**Comment by maxwxyz** [comment]
Maybe related if you use an editor to edit the page:
- https://github.com/FreeCAD/FreeCAD/issues/13577
