### ISSUE TITLE
Python interface to Part can be used to crash the application

### ISSUE THREAD

**Issue by bgbsww** [FreeCAD/FreeCAD#13208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

```
import Part
box = Part.makeBox(1,2,3)
cs = Part.CompSolid()
#cs.add(box)   # This will crash the app
comp = Part.Compound()
#cs.add(box)   # Or this
shell = Part.Shell()
shell.add(box.Faces[0])  # Or this.
```
The issue here is that it is possible to create initialized Python Objects with no OCCT shapes defined inside them (null), and then to call OCCT with that null shape pointer leading to the crash.  The solutions could be: add defense c++ code inside the add() methods that checks to see if there is a shape and raises an exception, or to put dummy shapes in the Python Objects ( probably bad side effects ), or to block the use of the empty constructor ( tricky, might break existing code or addons ).

Also, there may be other methods that make the invalid assumption that there is a shape, and other Part object types like Wire and BuildPlateSurface.  This needs a full survey to locate the affected code, at which point the changes should be straightorward.

### Full version info

```shell
At least 0.20.2, 0.21.0, 0.21.1, current daily, current weekly, and builds from the HEAD.  Probably every version of FC.
```

### Subproject(s) affected?

Part

### Anything else?

Wish I wasn't busy with Toponaming to hunt this down.  It is a good, easy intro to coding the C++ to Python interface.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/13675
