### ISSUE TITLE
Path->CAM Leftovers in Customize menu

### ISSUE THREAD

**Issue by chrisb-github** [FreeCAD/FreeCAD#13207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Customize Dialog still show a Path entry:
![SnipScreenshot-dde076](https://github.com/FreeCAD/FreeCAD/assets/11750017/9a7f8d25-d173-41e9-894b-992c6a91983c)

### Full version info

```shell
OS: macOS 13.0
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FC_SU
  * freecad.gears 1.2.0
  * FeedsAndSpeeds 0.5.0
  * dxf-library
  * fasteners 0.5.13
  * sheetmetal 0.4.2
  * ExplodedAssembly
  * Curves 0.6.24
```

### Subproject(s) affected?

CAM/Path

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@sliptonic this was left out of the bit Path->CAM PR
