### ISSUE TITLE
Navigation with overlays keeps orbit active

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

@Rexbas FYI

Using CAD navigation style around window center with transparent overlays enabled keeps the orbit action alive after releasing the mouse buttons.
This is reproducible:
1. enable overlays and transparency of the overlay panels (e.g. tree view)
2. move mouse over an emtpy, transparent area of the tree view and start rotation (MMB + RMB)
3. move mouse (while orbit mode is active) out of the tree view and over the model in the 3D view
4. release MMB + RMB
5. Sometimes the context menu is triggered, but the navigation orbit rotation continues when moving the mouse. You have to cancel the motion / active tool with another RMB click.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.11.8, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.3
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * Defeaturing 1.2.2
  * fasteners 0.5.15
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.6
  * sheetmetal.backup1710961794.9712274 0.4.3 (Disabled)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rexbas** [comment]
Thanks, when I was working on some navigation problems I also experienced similar behavior but I could never reproduce it. I can reproduce it using the steps you described so now I can finally try to fix it.

**Comment by maxwxyz** [comment]
Same, it bothered me for weeks and now I found out :D
