### ISSUE TITLE
Addon Manager Github Page Display

### ISSUE THREAD

**Issue by JamesHabben** [FreeCAD/FreeCAD#13220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When clicking on one of the addons in the list, it takes me to the Github page for that addon. The first rendering is showing the Github headers, but a blank page below that. When I click on the `code` tab, it re-renders the page and flashes the main content area where the readme would normally display, but then goes blank though it leaves the right sidebar info. Clicking the `issues` tab renders just fine. Seems to only be an issue with the `code` tab.

First render:
![image](https://github.com/FreeCAD/FreeCAD/assets/6327329/11ddefb0-6f0f-4f0e-96d0-e0d8294c77f1)

After clicking 'code' tab
![image](https://github.com/FreeCAD/FreeCAD/assets/6327329/6316271f-d209-4d5f-8e66-90dc0769f108)

### Full version info

```shell
[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Defeaturing 1.2.2
  * InventorLoader 1.4.0
  * sheetmetal 0.4.9
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@JamesHabben the addon manager is currently being overhauled, you can test it in the current weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
@chennes FYI
I'll close this as I guess it won't be implemented or backported for 21.2.
