### ISSUE TITLE
Issues with TabBar workbench selector

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#13286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I really like the idea of the new TabBar workbench selector introduced by #12270 but when I selected the Left corner position of the TabBar, I ended up with this:

![tab bar](https://github.com/FreeCAD/FreeCAD/assets/59876896/fef7a139-764b-4568-a598-83024c61235b)

It's still at the top for some reason, doesn't show all the workbenches (shouldn't it automatically scroll to the right when hovering next to the end of the bar if there are more workbenches?) and, most importantly, I can't access the menu bar to go to Preferences to restore the old selector.

The same happens on two different Windows computers.

@PaddleStroke Can you fix it?

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36731 (Git)
Build type: Release
Branch: main
Hash: ac1d887336826c59321352f49a195bf1ef8be2f0
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
'Left corner position' is a special setting to put the widget in the menubar corner widget. Not to dock the toolbar on the left side.

In your situation it's kind of 'you get what you asked for' in the sense that if shows the widget in the left corner widget, pushing out the menu as you have so many workbenches.

Now the fact that you cannot access the menu is indeed an issue. However you can actually still access the preferences because clicking on the '+ more' tab you have a link to Preferences where you can disable a proper amount of workbench to get it to a reasonable size (or disable this corner widget option).

Note that this 'corner widget' option is likely going to be removed soon anyway as RT said he will implement docking areas instead. See https://github.com/FreeCAD/FreeCAD/issues/12979.
So the confusion you had if any will be removed.

**Comment by FEA-eng** [comment]
Ok, I accessed the preferences with `Gui.runCommand("Std_DlgPreferences")`. Changing to Icon (instead of Icon & Text) made me realize that the menu bar is on the right from the TabBar selector (previously outside of the screen). I thought that the Left corner position would move the TabBar automatically to the right side of the screen but that apparently requires the Toolbar position and moving the toolbar to the left manually. So only the issue with too long non-scrollable TabBar when there are many workbenches is left.

**Comment by FEA-eng** [comment]
> However you can actually still access the preferences because clicking on the '+ more' tab you have a link to Preferences where you can disable a proper amount of workbench to get it to a reasonable size (or disable this corner widget option).

This button is also outside of the screen when both icon and text are shown. But ok, I admit that it's a fault of having too many workbenches to fit in such a bar. So maybe this should be turned into a feature request to add some automatic or manual scrolling. Perhaps even the toolbar position could use it.

**Comment by FEA-eng** [comment]
Now I got this:

![tabbar](https://github.com/FreeCAD/FreeCAD/assets/59876896/271b167f-6394-4ece-aa80-d142cff33224)

No idea what happened here :P

**Comment by PaddleStroke** [comment]
Let me know if you can find how to reproduce please

**Comment by FEA-eng** [comment]
> Let me know if you can find how to reproduce please

Setting what I showed there in Preferences (TabBar, Toolbar, Icon & Text) and restarting does this for me.

**Comment by PaddleStroke** [comment]
At least one solution wuold be to put the + as the first entry. So that even if list is too long you can easily access preferences.

**Comment by FEA-eng** [comment]
> At least one solution wuold be to put the + as the first entry. So that even if list is too long you can easily access preferences.

Right, that would make sense. But workbenches going outside of the screen don't look good so maybe in the future the code could automatically put the workbenches that don't fit on the screen under the More (+) button. Or the aforementioned scrolling could be added.

There's still that issue with the whole window getting covered by toolbars though. Do you know what can be causing it?

**Comment by PaddleStroke** [comment]
I don't know what can cause this and I cannot reproduce. You are stuck in this situation?

**Comment by FEA-eng** [comment]
> I don't know what can cause this and I cannot reproduce. You are stuck in this situation?

It still happens on some of my Windows computers:

![tabbar 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/8c880692-dbb3-4034-b20f-4a540cb398f8)

No idea why only on some, maybe it's due to a specific screen resolution. The number of active workbenches is similar on all of them. Preference settings should be similar too.
