### ISSUE TITLE
Regression while exporting a Body in version 0.21.2 compared to 0.20.2. Body orientation is ignored in exported .stl file.

### ISSUE THREAD

**Issue by bigi111** [FreeCAD/FreeCAD#13295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Before exporting a Body in .stl format, I sometimes want to rotate the Body by 180°. This works fine in FreeCAD version 0.20.2, but in version 0.21.2, the body rotation is ignored in the generated .stl file. I tested this regression with some freeCAD files.

### Full version info

```shell
[code]
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: French/Switzerland (fr_CH)
Installed mods: 
  * symbols_library
  * ExplodedAssembly
  * Curves 0.6.5
  * fasteners 0.4.56
  * MeshRemodel 1.8919.0
  * Lithophane
[/code]
```

### Subproject(s) affected?

PartDesign

### Anything else?

[F_puz_CouvercleA_TEST.zip](https://github.com/FreeCAD/FreeCAD/files/14863701/F_puz_CouvercleA_TEST.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Confirmed. This has already been fixed in the V0.22 dev version.
