### ISSUE TITLE
Materials: Unable to open an older material that is not part of a library

### ISSUE THREAD

**Issue by davesrocketshop** [FreeCAD/FreeCAD#13302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Previous versions of FreeCAD could open a material by specifying its path. The current version finds a library based on the path and marks the material as not found if it's not in a library.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36461 (Git)
Build type: Release
Branch: issue13019
Hash: 60f0ba3e5922a257be63d54aed10d3a89bbf0ae3
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * CfdOF 1.25.9
  * MaterialTest
  * Render 2024.1.23
  * Rocket 3.3.0
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

https://forum.freecad.org/viewtopic.php?p=751729

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hassansaleh31** [comment]
Not sure if this is the same issue but I'm getting the following error on Ubuntu 22.04.4 LTS using the latest daily build

```
libyaml-cpp.so.0.7: cannot open shared object file: No such file or directory
Unknown command 'Std_SetAppearance'
Unknown command 'Std_SetMaterial'
libyaml-cpp.so.0.7: cannot open shared object file: No such file or directory
```
