### ISSUE TITLE
TechDraw: Projection Group: Changing Spacing X/Y do not update on value changed.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In a Projection Group, changing Spacing X/Y do not update the views as one would expect.

The spinboxes are connected to update the value of `spacingX/Y` of the projection group. Which itself triggers the `DrawProjGroup::onChanged`.

But there it does only : 

```
    if (prop == &spacingX || prop == &spacingY) {
        updateChildrenEnforce();
        return;
    }
```

I tested to change it to : 
```
    if (prop == &spacingX || prop == &spacingY) {
        if (AutoDistribute.getValue()) {
            for (const auto it : Views.getValues()) {
                auto view(dynamic_cast<DrawProjGroupItem*>(it));
                if (!view) { return; }
                view->autoPosition();
            }
        }
        return;
    }
```

But it is laggy. I think that the views are getting completely recomputed on each value change in the spinboxes. However dragging a view directly in the viewport is not laggy. So there must be a way to update the positions without recomputing.

@WandererFan any ideas ?

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Is AutoDistribute turned on?  If not, the X/Y spacing values are ignored in favour of manual positioning.

**Comment by WandererFan** [comment]
Spacing X/Y works if autodistribute is true.

**Comment by PaddleStroke** [comment]
I did not say it doesn't work at all. The issue is that the views are not moving when you change the spinbox value. You need to click on Apply to have the views updating their position.

The view positions should update when you change the spinboxes values without needing to click on Apply.

So this issue should not be closed.

**Comment by PaddleStroke** [comment]
After working on the snapping, I think the correct way of solving this is to set the position of the QGIViews directly.
