### ISSUE TITLE
TechDraw: Hatching clip path functionality is missing from svg export

### ISSUE THREAD

**Issue by dov** [FreeCAD/FreeCAD#13338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

What I did:

1. Create new empty document
2. Switch to the Sketcher workbench, create sketch in the xy plane and add a rounded rectangle to it. Close sketcher
3. Switch to top view (2)
4. Switch to the TechDraw workbench
5. Add default page
6. Select the Sketch in the model tree and press Insert View
7. Select the rounded rectangle in TechDraw view. Then press "Hatch a file using image file". Change color to black and press ok.
8. Choose view tab and change the Face color to white (for better visibility)
9. Choose export svg 
10. Open the svg in an internal viewer

What I got:

Here is the resulting svg file, where the hashing flows outside the chosen face:

![bad-hashing-in-svg](https://github.com/FreeCAD/FreeCAD/assets/338235/22dd18ec-72cd-4563-89e2-dfe0ee9cdd51)

What I expected:

The hashing should be clipped to the face like in the TechDraw view:

![good-hashing-in-techdraw](https://github.com/FreeCAD/FreeCAD/assets/338235/2915e27a-a130-4142-8d5d-187ec93b8f38)

I'm also attaching the resulting FCstd file in a zip file:

[bad-hashing-export.zip](https://github.com/FreeCAD/FreeCAD/files/14894739/bad-hashing-export.zip)

### Full version info

```shell
OS: Fedora Linux 39 (Workstation Edition) (fvwm)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36442 (Git)
Build type: Unknown
Branch: main
Hash: bcf54d3153fe4cad841ff7c0b692506eaa802103
Python 3.12.2, Qt 6.6.2, Coin 4.0.2, Vtk 9.2.6, OCC 7.8.1.dev
Locale: C/Default (C)
Installed mods: 
  * Curves 0.6.21
  * MyWorkbench
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dov** [comment]
I'm attaching here an example svg file created with inkscape illustrating how clipping can be done with svg.

[svg-clip-example.zip](https://github.com/FreeCAD/FreeCAD/files/14894769/svg-clip-example.zip)

**Comment by maxwxyz** [comment]
Does https://wiki.freecad.org/TechDraw_GeometricHatch function produce the same outcome?

**Comment by dov** [comment]
> Does https://wiki.freecad.org/TechDraw_GeometricHatch function produce the same outcome?

No, I just tested it. It does not! It's svg output renders ok.

![geometric-hatching-rendering](https://github.com/FreeCAD/FreeCAD/assets/338235/e6538500-088a-4d50-b855-10b240696acf)


Note however, that the neither svg, through Image File or GeometricHatch, makes use of the svg clipPath feature.

(Alltogether the svg output is extremely redundant, with e.g. setting the font-family element for every path element drawn)

**Comment by maxwxyz** [comment]
@WandererFan FYI

**Comment by WandererFan** [comment]
QtSvg only supports Svg-Tiny.  According to Adobe Illustrator Help -- Saving artwork: Save in SVG format, SVG Tiny does not support gradients, transparency, clipping, masks, symbols, patterns, underline text, strike through text, vertical text, or SVG filter effects.

This works in v0.20.2 but not in v0.21.2 or v0.22dev, so it is an old regression.

**Comment by dov** [comment]
Yikes. Pixmaps for svg is ugly. :-(

How hard would it be to parse (a subset of) svg in the SVG tiles and then use libclipper for the clipping? E.g. using the first path statement only and then transform and clip by libclipper?

**Comment by WandererFan** [comment]
What is libclipper?  I found this https://packages.debian.org/sid/libclipper-dev which doesn't sound like what we want.

Also this https://angusj.com/clipper2/Docs/Overview.htm, but it only works on straightline segments.

**Comment by WandererFan** [comment]
I know how to parse Svg path, rect and line elements into QPainterPaths, but the paths don't get clipped on export.

Might need to convert the Svg into OCC edges and then use a boolean intersection with the face to be hatched.  This is how the PAT hatches work.

**Comment by WandererFan** [comment]
related issue: Hatch not correctly exported to PDF #14027

**Comment by WandererFan** [comment]
This is fixed:
![bad-hashing-export_svg](https://github.com/user-attachments/assets/0a01024d-d65f-48ef-bc46-0ceab0e3fb1b)
![bad-hasing_export_svg](https://github.com/user-attachments/assets/37f4c530-b14d-427d-b925-ba6697ce99f2)
