### ISSUE TITLE
Transform manipulator sometimes not selectable

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The arrows of the transform tool manipulator seem not selectable at random occasions. I first noticed that I cannot grab them and move the object when they are beneath the transparent overlay panels but sometimes it worked. I now experience the same behavior also in the plain 3D view.
In 0.21.2 stable there is no such issue.
I've using CAD navigation around window center and tried different navigation styles as well, not sure if the navigation style is related but it seems to be less buggy with the Blender navigation style - but I have no steps to reproduce it seems to break randomly (@Rexbas FYI).

Demo:

https://github.com/FreeCAD/FreeCAD/assets/6246609/68662864-2fd8-4515-bccb-c74e0e0c8a56

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36784 (Git)
Build type: Release
Branch: main
Hash: d1930fc7e6fc35c413f9f39d22f2ea28fca827c7
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.10
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * Defeaturing 1.2.2
  * fasteners 0.5.16
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * kicadStepUpMod 11.1.0
  * lattice2 1.0.0
  * OpenDark 2023.12.17
  * Rocket 3.3.0
  * sheetmetal 0.4.10
  * Silk 0.1.5
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qewer33** [comment]
I'm not sure but from my testing, this seems like a double click issue. I can consistently select the dragger if I leave enough time between clicks but if I try rapidly multi clicking, it doesn't select after the first click.

**Comment by maxwxyz** [comment]
I'll close this then, in the latest weekly I cannot reproduce either. If it happens again I'll reopen.
