### ISSUE TITLE
Part Design: Datum Plane Shape Color the same as body

### ISSUE THREAD

**Issue by jos-3d** [FreeCAD/FreeCAD#13376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If I select a "Datum Plane", it is displayed in the selected body color.
![DatumPlane](https://github.com/FreeCAD/FreeCAD/assets/155159023/05d1155c-ae1e-4f7b-83b2-ae818ebf0efd)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36784 (Git)
Build type: Release
Branch: main
Hash: d1930fc7e6fc35c413f9f39d22f2ea28fca827c7
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * A2plus 0.4.60h
  * Assembly3 0.12.2
  * Assembly4 0.50.4
  * Curves 0.4.3
  * fasteners 0.3.40
  * Help 1.0.3
  * Lithophane
  * nurbs
  * nurbs.backup1665220441.337504
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
It's a known temporary issue. Should be fixed once #13332 is merged.
