### ISSUE TITLE
Assembly: Define Limit for Joints / Mates

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It should  be possible to insert limits for joints and mate connections /relations. For example specify a max/min range a object could move and rotate.
It should be possible to define a minimum and maximum limit for a rotation and translation depending on the joint type. Either this should be set in the initial joint, or in the relation mate connector.
@PaddleStroke FYI

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Is that different from https://github.com/FreeCAD/FreeCAD/issues/12792?

**Comment by maxwxyz** [comment]
No, I didn't find my own issue... thanks!
