### ISSUE TITLE
FEM: Failure of several unit tests

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#13383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

* Run FreeCAD with a clean config
* Open the preferences and activate the Test workbench. Save the settings
* Go to the Test workbench and run TestFemApp
* All tests pass. So far so good.
* Leave the test dialog open and go to the preferences. Click OK to save the settings
* Rerun the TestFemApp
* 26 tests will fail now

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git)
Build type: debug
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

FEM

### Anything else?

So, apparently the user config has an impact on the result of the FEM unit tests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
@FEA-eng at the very least the maximum iterations of _2000_ as specified in https://github.com/FreeCAD/FreeCAD/commit/b04fd4021569b073588b268c87f866ed2e7f01da is being expected to be _200_ in the tests (that's the way I read the error report anyway):

```
-*STEP, INC=200
+*STEP, INC=2000
```

**Comment by FEA-eng** [comment]
@Syres916 Ok, that should be fixed with #13397

**Comment by wwmayer** [comment]
No, it only fixed partially the problem. There are still 12 failing tests with this difference of the created inp files:
```
@@ -95 +95 @@
-*NODE FILE, OUTPUT=3d
+*NODE FILE, OUTPUT=2d
```

**Comment by FEA-eng** [comment]
> No, it only fixed partially the problem. There are still 12 failing tests with this difference of the created inp files:
> 
> ```
> @@ -95 +95 @@
> -*NODE FILE, OUTPUT=3d
> +*NODE FILE, OUTPUT=2d
> ```

Is it still with a clean config? There was a PR that changed the default from 2d to 3d (for a very good reason) and all the tests were updated to reflect this change.

**Comment by wwmayer** [comment]
> Is it still with a clean config?

No, I use my standard config. 

> There was a PR that changed the default from 2d to 3d (for a very good reason) and all the tests were updated to reflect this change.

A properly written test code must not depend on any user settings and if does directly or indirectly then the test is worthless.

Where in the code base is the 2d vs. 3d affected by a user parameter?

**Comment by FEA-eng** [comment]
> Where in the code base is the 2d vs. 3d affected by a user parameter?

Here's the preference: https://github.com/FreeCAD/FreeCAD/blob/0119b7c90183d5d09b239999febdf818de3032d9/src/Mod/Fem/Gui/DlgSettingsFemCcx.ui#L526

and here's the property: https://github.com/FreeCAD/FreeCAD/blob/5edcfc367dd7ff6b63cac84e72d96f788375fbbc/src/Mod/Fem/femsolver/calculix/solver.py#L371

**Comment by wwmayer** [comment]
OK, thanks for the links.

Making a feature class directly depending on user parameters is bad practice because it adds mutable global state to this class. This is as bad as working with global variables because they can be changed from outside that can lead to unexpected behaviour -- like the failing unit tests in this case.

To make the code working more reliably you should change the class Proxy.
Remove all the code to access user parameters, i.e. `__init__`, onDocumentRestored, on_restore_of_document and add_attributes. Replace the user parameters with hard-coded default values.

This guarantees that every Proxy instance after its creation is identical on all systems independent of any user settings.

Now write a helper class that has the attributes you want to customize of the Proxy instance.
```
class ProxyParameters:
    def __init__(self):
        ccx_prefs = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/Fem/Ccx")
        self.AnalysisType = ccx_prefs.GetInt("AnalysisType", 0)
...
```

To the Proxy class add the method setParameters(param : ProxyParameters) and set the values you want to override.

Now you must check where in the GUI the Proxy is instantiated. I guess this must happen somewhere in a command or dialog or so. There you can instantiate ProxyParameters and assign it to the Proxy.

**Comment by FEA-eng** [comment]
@marioalexis84 Can you take a look at this and consider implementing the enhancements suggested by Werner at some point? IMO it's not urgent and can be done in the next release cycle (after all, those properties have always been implemented in this non-optimal way) but I have to ask you because it seems to be beyond my skills and I don't want to mess it up even more.
