### ISSUE TITLE
TechDraw: refactor TD/Gui/TaskDetail.h with proper enum 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#13409]
https://github.com/FreeCAD/FreeCAD/blob/cc96f2718e139d670e08c4226bdea9955a102ed6/src/Mod/TechDraw/Gui/TaskDetail.h#L32-L36

**Comment by luzpaz** [comment]
@FarleyRunkel have at it!

**Comment by FarleyRunkel** [comment]
Thanks
