### ISSUE TITLE
TechDraw: Broken view lines could be customizable

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#13405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently, the Broken view tool can use only zig zag break lines. Straight and curved (spline) styles could also be useful. Maybe they could even inherit the style of the sketched lines used by the tool to define the break.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git)
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
3 simple options added by #14367.
