### ISSUE TITLE
Can't open STL file with Part module

### ISSUE THREAD

**Issue by PeterBan11** [FreeCAD/FreeCAD#13412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I can't open STL file with Part module. My code:

```python
import FreeCAD
import Part

self.path = "back_leg5.STL"

self.shape = Part.Shape()
print(self.path)
self.shape.read(self.path)
self.boundBox = self.shape.BoundBox
print(self.boundBox)
```

*Edit:* example file used in script: [back_leg5.zip](https://github.com/FreeCAD/FreeCAD/files/14948840/back_leg5.zip)

### Full version info

```shell
FreeCAD_0.21.2-2023-12-17-conda-Windows-x86_64-py310
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
can you please provide full about info? Are you using FreeCAD headless?

**Comment by M4xTheMan** [comment]
Below you can find details regarding the scripting. Is this what you're looking for? https://wiki.freecad.org/Mesh_FromPartShape

**Comment by Roy-043** [comment]
This is indeed something that belongs in the forum. `shape.read` cannot read STL files:

```
>>> help(shape.read)
Help on built-in function read:

read(...) method of Part.Shape instance
    Read in an IGES, STEP or BREP file.
    read(filename)
```

Code that works:
```
import Mesh
import Part

path = "C:/Downloads/back_leg5.STL"

mesh = Mesh.Mesh()
mesh.read(path)
shape = Part.Shape()
shape.makeShapeFromMesh(mesh.Topology, 0.1)
Part.show(shape)
```

See also https://wiki.freecad.org/Part_ShapeFromMesh
