### ISSUE TITLE
TechDraw: use c++11 compatible code in TechDraw/App/DrawUtil.cpp

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#13410]
https://github.com/FreeCAD/FreeCAD/blob/cc96f2718e139d670e08c4226bdea9955a102ed6/src/Mod/TechDraw/App/DrawUtil.cpp#L122-L123

**Comment by WandererFan** [comment]
The comment looks like a cut and paste error from getIndexFromName.  getGeomTypeFromName returns a string, so there is no conversion to integer required.

**Comment by luzpaz** [comment]
@WandererFan should i delete the comment then ?

**Comment by WandererFan** [comment]
Yes please.
