### ISSUE TITLE
Std RandomColor isn't working / Not able to assign color to a body by using the random color function

### ISSUE THREAD

**Issue by M4xTheMan** [FreeCAD/FreeCAD#13420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

From the [wiki](https://wiki.freecad.org/Std_RandomColor/en):

> The Std RandomColor command applies a random ViewShape Color to selected objects. 

**Expected behavior**
The bodies color changes in the 3D-view

**Current behavior**
Nothing happens (including the report view).

This is a very useful function when working with multiple bodies within one FreeCAD file or regarding assemblies.

I assume this has something to do with the new material system.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git) AppImage
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * LCInterlocking
  * kicadStepUpMod 11.1.0
  * Lithophane
  * lattice2 1.0.0
  * Defeaturing 1.2.2
  * Manipulator
  * fasteners 0.5.16
  * Assembly3 0.12.2
  * sheetmetal 0.4.10
  * InventorLoader 1.4.0
  * Assembly4
  * Curves 0.6.29
  * POV-Ray-Rendering
  * OpenDark 2023.12.17
  * 3DfindIT 1.2.0
  * Gridfinity 0.3.0
  * Freecad-Built-in-themes-beta 1.2.2
```

### Subproject(s) affected?

Part
PartDesign

### Anything else?

Probably linked to #13332

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
@maxwxyz It's fixed by #13332 in the newest weekly so the issue can be closed.
