### ISSUE TITLE
Sketcher: Copy/Paste of Constraints

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

From the FreeCAD Day 2024 Complaint Session:
**You cant propagate constraints from one item to another in sketcher**
1. _As far as I know, we don't have a good way to copy constraints automatically. Like if I have something that I want to have in the sketch an. I can do the mirror command and then I need to redo all the constraints, so I end up using like symmetry lines to…
Yeah. So you cannot copy constrained  items in the sketcher._ --> solved by new symmetry tool.
2.  You cannot propagate constraints from one item to another in the sketcher: It is not possible to select and copy constraints in sketcher from one geometry to another geometry, e.g. a dimension, angle or horizontal, vertical constraint.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git)
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.10
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * Defeaturing 1.2.2
  * fasteners 0.5.16
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * OpticsWorkbench 1.0.15
  * sheetmetal 0.4.11
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke could you add your opinion on this?
1. is solved with the symmetry tool
2. is very hard from a UI point I guess. It is easy to copy a horizontal constraint and paste it to another selection but it is as quick and easy to just create a new horizontal constraint. Constraints which rely on 2 or more geometry is tricky, how should they be pasted, depending on your new selection, I think this is not intuitive. Dimensions like diameter or length could use the equal constraint instead.

I'm in favor of closing this as not planned as this just adds more complexity and one half of the request is already solved.

**Comment by PaddleStroke** [comment]
+1
