### ISSUE TITLE
Auto refine to reduce unnecessary edges

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

From the FreeCAD Day 2024 Complaint Session:
**When you have an edge appear due to order of operations, that edge is represented in geometry when it shouldn't be, Refine is needed.**
Sometimes edges are shown depending on the order of operation and a manual part refine is needed as these edges in order to get rid of them in the geometry. Not always it is possible to completely remove additional but unnecessary edges.

Related:
- https://github.com/FreeCAD/FreeCAD/issues/13217
- https://github.com/FreeCAD/FreeCAD/issues/9133

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git)
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * Curves 0.6.29
  * fasteners 0.5.16
  * OpenDark 2023.12.17
  * sheetmetal 0.4.11
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by howie-j** [comment]
The feature freeze for 1.0 is closing in fast. Have there been any discussion regarding setting Refine = True as the default? It's a common complaint for very many users on the forum, and i would guess most users have it enabled.
