### ISSUE TITLE
CAM - 'tuple' object has no attribute 'DiffuseColor'

### ISSUE THREAD

**Issue by boboxx** [FreeCAD/FreeCAD#13498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Unable to run the path simulator

### Full version info

```shell
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git)
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

CAM/Path

### Anything else?

![Screenshot 2024-04-16 at 4 02 29 PM](https://github.com/FreeCAD/FreeCAD/assets/15091037/1c1db52f-3ebd-4c34-8bc4-69c8e2d0da87)

Here is the file:
[ME_cabinet_v3.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15001523/ME_cabinet_v3.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I guess related to materials @davesrocketshop FYI

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/13520

**Comment by Russ4262** [comment]
Instead of setting the 'DiffuseColor' attribute directly, call the following set function, or similar, after making it available.  Works on my end.

`
def setDiffuseColor(vObj, diffuse, transparency=None):
    """setDiffuseColor(vObj, diffuse, transparency=None)
    Sets DiffuseColor and optional Transparency of vObj"""
    if (isinstance(diffuse, tuple) or isinstance(diffuse, list)) and len(diffuse) == 3:
        m = vObj.ShapeAppearance[0]  # get current material attributes
        if transparency is not None and transparency >= 0.0 and transparency <= 100.0:
            t = transparency
        else:
            t = m.Transparency
        vObj.ShapeAppearance = FreeCAD.Material(
            DiffuseColor=(diffuse[0] / 255.0, diffuse[1] / 255.0, diffuse[2] / 255.0),
            AmbientColor=m.AmbientColor,
            SpecularColor=m.SpecularColor,
            EmissiveColor=m.EmissiveColor,
            Shininess=m.Shininess,
            Transparency=t,
        )
`
Just an idea.

**Comment by shaise** [comment]
This file seems to work in the latest version. @boboxx can you check and close?
