### ISSUE TITLE
There are errors in the text layout on the project description page

### ISSUE THREAD

**Issue by bms-2015** [FreeCAD/FreeCAD#13526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There are errors in the text layout on the page 

https://www.freecad.org/features.php?lang=ru

See screenshots

### Full version info

```shell
-
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

![Clipboard_04-18-2024_03](https://github.com/FreeCAD/FreeCAD/assets/12142979/eddbdbdd-d2fe-466d-9b27-38102d8f455f)
![Clipboard_04-18-2024_02](https://github.com/FreeCAD/FreeCAD/assets/12142979/469f82b7-1dee-446f-87bf-edc1f6edbca7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Could you please create the issue here: https://github.com/FreeCAD/FreeCAD-Homepage
