### ISSUE TITLE
QSvgWidget is not a child of QtSvg in PySide6

### ISSUE THREAD

**Issue by dov** [FreeCAD/FreeCAD#13533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The source used QtSvg.QsvgWidget, but this class does not exist in PySide6.

The code needs to be ported to use QtSvgWidgets.QSvgWidget instead. See: https://doc.qt.io/qtforpython-6/PySide6/QtSvgWidgets/QSvgWidget.html#PySide6.QtSvgWidgets.QSvgWidget

### Full version info

```shell
OS: Fedora Linux 39 (Workstation Edition) (fvwm)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36442 (Git)
Build type: Unknown
Branch: main
Hash: bcf54d3153fe4cad841ff7c0b692506eaa802103
Python 3.12.2, Qt 6.6.2, Coin 4.0.2, Vtk 9.2.6, OCC 7.8.1.dev
Locale: C/Default (C)
Installed mods: 
  * Curves 0.6.21
  * MyWorkbench
```

### Subproject(s) affected?

Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
related or duplicate to?
- https://github.com/FreeCAD/FreeCAD/issues/13303
- https://github.com/FreeCAD/FreeCAD/issues/13427

if so, please comment there

**Comment by dov** [comment]
@maxwxyz Wouldn't it make sense to separate between Qt6 compilation errors, and PySide6 run time errors? Also, do you really want to group all issues together? E.g. this issue is a specific measurable problem. If you group them alltogether, how do you measure whether it is done or not?

**Comment by maxwxyz** [comment]
It's ok for me as is, I'm no expert in these issues

**Comment by wwmayer** [comment]
Fixed with https://github.com/FreeCAD/FreeCAD/pull/13554
