### ISSUE TITLE
TechDraw: 'Position section view' should not need a tool.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

'Position section view' should not need a tool.

When dragging the view, there should be a snapping to correct positions when close enough. It would be more intuitive and would not require a tool.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Let me just clarify here that snapping in TechDraw is implemented (with #13659) but doesn't work for oblique section views so the TechDraw_ExtensionPositionSectionView was left and the issue is not fully resolved yet.

**Comment by WandererFan** [comment]
AFAIK, oblique section snapping works now.  This can be closed.
