### ISSUE TITLE
TechDraw: Position chain dimensions should not need a tool.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#13566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/fa2578ee-b293-4f79-94e8-5e5061d52b0e)

Techdraw has 2 tools that let you align correct dimensions.
These tools are not necessary. If we had a snapping when dragging dimensions we could make it simple to align dimensions.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke if possible, take into account:
- https://github.com/FreeCAD/FreeCAD/issues/11636


    Create dimensions with an equal (defined) spacing to the model (e.g. all 15mm from the model edge outwards)
    Snap the text on the dimension to the center of the dimension arrows (default, when moving snap text/value too)
    Align the dimension (arrows) while moving to other dimensions (snapping) (this tool you've mentioned in this your issue)
    Move the dimension without changing the local (relative) position of the dimension text (so it stays in the center)

**Comment by PaddleStroke** [comment]
Ah yes it's more or less a duplicate of your issue

**Comment by maxwxyz** [comment]
Yes but I've not mentioned the removal of the tool

**Comment by WandererFan** [comment]
What is really needed here is a DimensionGroup so that the dimensions would continue to behave as a group after creation.  The current tool aligns the dimensions once, then if the dimension text or dimension points change, you have to do the alignment again.
