### ISSUE TITLE
Light sources improvement suggestions

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Under <kbd>Edit</kbd> > <kbd>Preferences</kbd> > <kbd>Light Sources</kbd>:

![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/b736be2f-2ecc-4581-878b-e357846f1996)

1. It is not obvious that the image of the light source is interactive. There is no indication or explanation that it is. You can click on any point of the image and nothing will happen until you click what I understand now to be a handle => A small note under the image (e.g. `Use the handle to adjust the light source position`) would quickly sort this out.
2. Once the direction is changed, there is no way to reset it because there is no visual feedback of the exact original position => Either a Reset button or text boxes/labels that would show the changed parameters could help here.
3. There is no way to precisely or repeatably set the direction => A possible solution could be the same as above (editable text boxes)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36915 (Git) Snap 995
Build type: Release
Branch: main
Hash: 1f9be3f9ed44f7a3f4a453ef4761eea2d96a3dc0
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * BIM 2021.12.0
  * Curves 0.6.34
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.1
  * Ondsel-Lens 2024.4.16.01
  * Assembly4 0.50.12
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Related: #11166

Reset would indeed be needed.

Ideally, it should be moved to the actual 3D model viewport like in Link Branch or other CAD software but for now, the existing implementation can be enhanced.
