### ISSUE TITLE
TabBar wrongly activates the last tab when loading a new workbench

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. With the TabBar enabled¹, click on the `+` (plus sign) at the beginning of the workbenches tabs.
2. Choose a workbench from the context menu shown
3. **Actual**: the workbench is loaded (without a tab as per issue #13630. The tab of the last workbench in the existing tabs is activated (in my case, the Assembly tab)
4. **Expected**: the workbench is loaded (with or without a tab is a pending design decision). The tab of the last workbench should not be arbitrarily activated.

[1] Edit > Preferences... > Available Workbenches > Workbench selector type => TabBar

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36961 (Git) Snap 996
Build type: Release
Branch: main
Hash: c4c453312d148fd67bd893366c42b559e28a85e6
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * Curves 0.6.35
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.4.16.01
  * Assembly4 0.50.12
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can confirm on Windows

**Comment by furgo16** [comment]
> It was intended that the deactivated workbench do not add themselves to the tabs in order to keep a fixed size for the tabbar. Some others argued it should be as you describe. It is up for discussion.
> 

Given that there are already navigation arrows that appear to scroll through tabs e.g. in small screens, could the fixed size not be maintained and yet load the new tabs?

> I have just tested and found there is an issue. Activating a workbench that is deactivated should set the active tab to the '+' tab. Not to the latest active workbench.
> 
> Since I moved the + button to the beginning there is an issue, as its the last tab that gets activated. So not the + tab anymore.

Thanks for confirming. Yes, that's the behavior on step 4 of the issue description.

**Comment by PaddleStroke** [comment]
I created a PR that fix the described issue.
Regarding the feature request of having tabs added to the tab bar when you click on a deactivated perhaps it is best to discuss with the DWG about it and then create an issue that describes the required changes in details.

**Comment by furgo16** [comment]
Thanks, I repurposed this issue to match the PR, as it already mentioned it. I split the original topic into https://github.com/FreeCAD/FreeCAD/issues/13630

@PaddleStroke @maxwxyz is there a GitHub handle to summon the DWG to look at a particular issue?

**Comment by maxwxyz** [comment]
> @PaddleStroke @maxwxyz is there a GitHub handle to summon the DWG to look at a particular issue?


DWG can only be summoned through a mystical ritual at full moon.
Jokes aside, @chennes have you already successfully completed the quest to create such a group 😀

**Comment by chennes** [comment]
@FreeCAD/design-working-group

**Comment by furgo16** [comment]
I wish I had known this before sacrificing 16 goats to the design gods... Thanks! :-)

**Comment by furgo16** [comment]
@pierreporte thanks for the input. Would you mind adding your comment to https://github.com/FreeCAD/FreeCAD/issues/13630? I had to rewrite this issue so that it matched the `fixes` commit message in the linked PR. The one for loading workbenches is now #13630

**Comment by obelisk79** [comment]
I'm just curious, what was the rationale for moving the + button to the beginning of the tabs list? Such placement is illogical. Especially considering the potential for the other issue spawned from this one changing behavior further.

**Comment by furgo16** [comment]
The rationale was https://github.com/FreeCAD/FreeCAD/pull/13508 as far as I could tell.

**Comment by obelisk79** [comment]
While not a significant issue, this a psychologically unusual placement for that, I don't support this placement change.

**Comment by PaddleStroke** [comment]
@obelisk79 I agree it looks better on the right, which is why I've put it there in the first place.
However the problem is that then the '+' can become hidden in cases where the tabbar is crowded. Which makes it very annoying to access the '+'. It was argued that an easy access to the + is essential and so it would be better at the beginning.

We could have a preference for the position but that feels a bit overkill.

**Comment by kadet1090** [comment]
While the issue is clear I simply don't think that it is valid solution. The + (more) button should not be one of tabs,  but it should be normal button positioned just after the tabs even if they are overflowed and scrollable. This is the behavior that people are used to from browsers and many other software with similar mechanisms.

**Comment by PaddleStroke** [comment]
As mentioned before, I initially used a button and changed to a tab after. If the '+' adds the workbench tab, then a button is possible.
While I don't think it's ideal that the tabbar size gets dynamic I'm just one person. If you want to see this changed you know how to proceed : issue/discussion then PR ;)

**Comment by furgo16** [comment]
Indeed, I think we're veering off-topic here. The `+` button might deserve its own issue/discussion. Happy to file it unless someone else wants to instead.
