### ISSUE TITLE
Right-clicking a document in the tree view activates it directly and folds other items before executing the selected command.

### ISSUE THREAD

**Issue by farleyrunkel** [FreeCAD/FreeCAD#13628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Based on the user's intuition, only the right-click menu will appear When a right-click is made.
![rightmenuissue](https://github.com/FreeCAD/FreeCAD/assets/162782461/59dbf057-1b3f-4f16-917a-95eb9d86f230)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36916 (Git)
Build type: Release
Branch: refractor_tracker
Hash: 31f5ca51dae6ae11343e639eb253b6e31f608379
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Chinese/China (zh_CN)
Installed mods: 
  * nurbs
```

### Subproject(s) affected?

Core

### Anything else?

Suggesstion:
- Disable document activation when right-click
- Add a Qt-like command "Set current document as active document" in right-click menu?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Related: https://wiki.freecad.org/Std_TreeMultiDocument.

**Comment by farleyrunkel** [comment]
Thanks for your reply. This is a minor issue, but it seems not necessary to activate a document when right-clicking it.

**Comment by wwmayer** [comment]
Can this be closed?

**Comment by farleyrunkel** [comment]
sure
