### ISSUE TITLE
TabBar workbench selector does not add tabs for workbenches not already loaded

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. With the TabBar enabled¹, click on the `+` (plus sign) at the beginning of the workbenches tabs.
2. Choose a workbench from the context menu shown
3. **Actual**: the workbench is loaded, but there is no tab for it. The tab of the last workbench in the existing tabs is activated (in my case, the Assembly tab, issue https://github.com/FreeCAD/FreeCAD/issues/13602)
4. **Expected**: the workbench is loaded, and a new tab for that workbench is added. The tab for the newly loaded workbench is activated.

https://github.com/FreeCAD/FreeCAD/issues/13602#issuecomment-2074640900 mentions that this is intended behavior to be able to keep the tab list from growing, and thus it is fixed. While I understand the screen real state concern, I feel having tab-orphaned workbenches has a negative impact on usability and is not consistent with the existing tab navigation.

[1] Edit > Preferences... > Available Workbenches > Workbench selector type => TabBar

### Proposal <a href="#user-content-proposal" id="proposal" />

- Keep tab list as fixed width
- When an additional workbench is loaded, it should have a tab as the rest
- As the list of tabs grows beyond the original list's width, leverage the existing tab scroll arrows already present in the code. These are shown when the list cannot be displayed in smaller screens. Effectively it's the same principle Firefox uses to be able to access additional tabs (Chrome uses the opposite principle, whereby it squeezes all tabs until they become unreadable. I would not recommend this).

![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/e77ea870-bd8d-4145-bc22-a668d6748599)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36961 (Git) Snap 996
Build type: Release
Branch: main
Hash: c4c453312d148fd67bd893366c42b559e28a85e6
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * Curves 0.6.35
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.4.16.01
  * Assembly4 0.50.12
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
So you mean: Just display the current WB on a fresh start and add new tabs if you want to change a WB?

**Comment by furgo16** [comment]
Not exactly (unless I haven't understood it correctly)

Currently:
- The tabs list contains only the auto-loaded workbenches
- The `+` sign opens a list of the rest of installed workbenches
- Choosing a workbench from the list loads it, it displays it, but it does not create a tab for it

This proposal:
- The tabs list contains only the auto-loaded workbenches
- The `+` sign opens a list of the rest of installed workbenches
- Choosing a workbench from the list loads it, displays it, and creates a tab for it. If the list of tabs exceeds the list's fixed width, the scrolling arrows are shown.

At the end of the day, this issue is about not having orphaned workbenches without tabs.

I hope this clarifies things.

**Comment by maxwxyz** [comment]
Why not use it like a tab in the file browser / terminal / web browser?

- Just load the defined WB which is set as default/start WB.
- If you create a sketch or double click a sketch or spreadsheet it automatically opens/adds the Sketcher WB (like you can open a link in a new tab in a web browser).
- You can manually open tabs with the `+` and choose from all active but not opened WB and these stay open as tabs.

**Comment by furgo16** [comment]
That covers the essence of the proposal, which is not having tab-less workbenches, so I'd be fine with that too. A quick note:

- I still think it's useful to have a set of auto-loaded workbenches that are opened as tabs at startup. It's useful for quick access: you cannot always double click on an element and open the desired workbench. E.g. if I'm on the BIM workbench and I need to convert wires to a face to build a wall, I'll quickly switch to Part > Make face from wires.

**Comment by furgo16** [comment]
Trying to mention @FreeCAD/design-working-group for input does not seem to work, although it's the convention described at https://github.blog/2012-05-09-introducing-team-mentions. Does that team already exist? Is it mentionable only by members of the FreeCad organization on GitHub?
