### ISSUE TITLE
Crash in 3Dconnexion NavLib -- bad iterator

### ISSUE THREAD

**Issue by chennes** [FreeCAD/FreeCAD#13635]
The code here:
https://github.com/FreeCAD/FreeCAD/blob/b509511f44c7ed4b6b16d31a85d7de74fc4d0662/src/Gui/3Dconnexion/navlib/NavlibCmds.cpp#L116-L119

is incorrect. Calling `insert()` on a `std::string` invalidates any iterators, so `markupBegin` and `markupEnd` cannot then be used in the call to `text.erase`. An example of a failing input is:
```
"<p>\n\nInsert a component into the active assembly. This will create dynamic links to parts, bodies, primitives, and assemblies. To insert external components, make sure that the file is <b>open in the current session</b></p><p><ul><li>Insert by left clicking items in the list.</li><li>Remove by right clicking items in the list.</li><li>Press shift to add several instances of the component while clicking on the view.</li></ul></p>"
```

Heads-up @pskowronskiTDx

**Comment by pskowronskiTDx** [comment]
I see, it was wrong. Sorry for missing that. The issue has been just addressed.
