### ISSUE TITLE
Freecad crashes on selecting a sketch in the "Reference Axis" UI of a Pad

### ISSUE THREAD

**Issue by wolfgangr** [FreeCAD/FreeCAD#13656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

the problem is reported on the forum.
I've pinned it down to a simple reproducible case:
https://forum.freecad.org/viewtopic.php?p=755459#p755459

in short:
I tried to change the sketch attached to a PD pocket.
ignorant of the details, I selectet my new sketch in the "Reference Axis" property field of the pocket.
The pocked is marked for recompute.
upon recompute, FreeCAD crashes

example files and console log of the crash are in the forum link given above.

Expected behaviour:
- UI might not only offer the sketch, but also the axis as obviously required there
- or automagically change to N_Axis
- and even if it does not work, It might supply error message or just silently ignore wrong selection

Problem was reported by @chrisb-github as present in current dev version as well

### Full version info

```shell
[code]
OS: Debian GNU/Linux 10 (buster) (LXDE/LXDE)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * fasteners 0.5.17
  * slic3r-tools
  * Pyramids-and-Polyhedrons
  * A2plus 0.4.64
  * Assembly3 0.12.2
  * Assembly4 0.50.12
  * FeedsAndSpeeds 0.5.0
  * dodo 1.0.1
  * frame 0.1.1
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * MOOC 2022.4.21
  * Help 1.0.3
  * ose-piping
  * QuickMeasure 2022.10.28
  * sheetmetal 0.4.11
  * ThreadProfile 1.89.0
  * SteelColumn
  * Estimate 0.1.2
  * DynamicData 2.60.0
  * parts_library
  * btl 0.9.9
  * AnimationFreeCAD 1.0.0 (Disabled)
  * CurvedShapes 1.0.8
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/13669
