### ISSUE TITLE
TechDraw: Autofill - add the Current Sheet Number and the Total Sheet number as seperate option

### ISSUE THREAD

**Issue by tobiasfalk** [FreeCAD/FreeCAD#13661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With #13005 Autofill was introduced, but it would be nice if the current Sheet number and the total number of sheet could be accessed separate from each other and not only as on, as it currently is.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36958 (Git)
Build type: Release
Branch: main
Hash: a041129090b8dcbb8367636840d3c668ef30a933
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * DynamicData 2.60.0
  * fasteners 0.5.15
  * kicadStepUpMod 11.1.0
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@tobiasfalk can you test https://github.com/FreeCAD/FreeCAD/commit/9bd19ff43a1c984d9d241f85c31c3d30be876d06 and report back ?

**Comment by tobiasfalk** [comment]
Since can not Compile FreeCAD, I will need to wait until the next WeeklyBuild but if what I saw in the Pull Request #1366, it is now solved.

**Comment by tobiasfalk** [comment]
Yes works, thx

**Comment by luzpaz** [comment]
Thanks @pavltom for the contribution!
