### ISSUE TITLE
FEM: Data along line - orbit cancels selection of points

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using the DataAlongLine filter in a results pipeline it is possible to select the two points in the 3d view.
If you orbit the camera, the operation is cancelled, either before you've placed the first point or also after you've placed the first point.
You should be able to navigate the model when selecting the points.

@FEA-eng FYI

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36958 (Git)
Build type: Release
Branch: main
Hash: a041129090b8dcbb8367636840d3c668ef30a933
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * CfdOF 1.25.11
  * Curves 0.6.35
  * dodo 1.0.1
  * fasteners 0.5.20
  * fcVM-WB
  * freecad.gears 1.2.0
  * OpenTheme 2024.4.20
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
I can confirm this, it indeed can be quite annoying.

@marioalexis84 FYI

**Comment by marioalexis84** [comment]
@maxwxyz @FEA-eng Which navigation style are you using?

**Comment by maxwxyz** [comment]
CAD, orbit around window center.

**Comment by FEA-eng** [comment]
Panning with CAD style also causes it.
