### ISSUE TITLE
www.freecad.org 502 Bad Gateway

### ISSUE THREAD

**Issue by SerhiiK** [FreeCAD/FreeCAD#13693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Site return 502 Bad Gateway

### Full version info

```shell
Site return 502 Bad Gateway
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please create the issue in the related repository: https://github.com/FreeCAD/FreeCAD-Homepage
