### ISSUE TITLE
Measurement: Add measurement result to tree label / change when updated

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently, all saved/annotated measurements in the tree display only their name, e.g. "Distance".
To find the right Distance, they should additionally display their value, e.g. "Distance: 5 mm" or "Angle: 5°", ideally the labels update when the model/measurement is updated.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37063 (Git)
Build type: Release
Branch: main
Hash: 680792030fd664c94829e2c1b78b21788e8d9879
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * CurvedShapes 1.0.9
  * Curves 0.6.35
  * fasteners 0.5.20
  * OpenTheme 2024.4.20
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.13

```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
This is implemented now:

![measurements](https://github.com/FreeCAD/FreeCAD/assets/59876896/7858d052-5fc9-4c30-acfe-c85959d8969b)

and they update when the model changes so I think that the issue can be closed.
