### ISSUE TITLE
Draft WB UI: inconsistent temporary Object creation in the Tree View

### ISSUE THREAD

**Issue by marcuspollio** [FreeCAD/FreeCAD#13700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating Drafting Objects (via Toolbar, Shortcuts or Menu), the Line, Polyline, B-Spline and Bézier curve Tools create a temporary "Part_3D_object" icon in the Tree View, while the other Tools (such as Arc, Circle, Rectangle, etc.) do not.
When the Task is finished (e.g. your Line is fully drawn), the icon in the Tree View changes to either Wire (N-Linear), Curve or Polygon.

How to recreate:

- Launch FreeCAD and in the Start page choose 2D Draft. Make sure the Tree View is visible.
- Create a Line (LI shortcut) and see a new Part icon being added in the Tree View under your Document. See the upper part of the screenshot below.
- Cancel the action (Esc), the Part icon in the Tree View disappears.
- Create a Circle (CI shortcut) and see that no Part icon is added in the Tree View, until you finish your Task (e.g. set the center and the radius), then a Curve icon is added in the Tree View. See the lower part of the screenshot below.

<details><summary>Screenshots</summary>

![Draft_Tree](https://github.com/FreeCAD/FreeCAD/assets/131592747/14793a71-daf8-4b80-9578-55b9a297e2e7)

</details>

Proposed solution:

- Make all Draft Tools consistent and do not add a temporary Part_3D_object icon in the Tree View until the task is finished. Many Draft Tools already perform that way (see above the list). Arch WB and Sketcher WB perform that way.
- Or: make all Draft Tools consistent and add the right icon (Wire/N-Linear for Line, Polyline, etc.) as soon as the Tool is called. Part Design WB and TechDraw WB perform that way.

### Full version info

```shell
OS: GNU/Linux Ubuntu 22.04 LTS based distro (DE: GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36997 (Git)
Build type: Release
Branch: main
Hash: bff1efd665dc2f553ac57e5bef35c44a879999c2
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk , OCC 7.5.1
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farleyrunkel** [comment]
Hello, @marcuspollio , could you please add more images.

**Comment by marcuspollio** [comment]
Hi @farleyrunkel just added some screenshots in the collapsed section of the first post.

**Comment by yorikvanhavre** [comment]
That temporary object was there basically so the tool could snap to itself. Which I think is still a good thing. But indeed the temp object is annoying. Two possibilities:

1. We remove the temp object and adapt the snap system so it can work with a non-existing object (the polyline being drawn) - long path
2. We make the temp object invisible - short path

I'm inclined to the short path. What do you think @Roy-043 ?

**Comment by Roy-043** [comment]
I agree.

**Comment by marcuspollio** [comment]
@yorikvanhavre and @Roy-043

Thank you for having a look !

With PR 13778 (or commit b45bf9b) applied, it only fixes this issue for the Line and the Cubic Bézier Curve tools.

For the Polyline, the B-Spline and the Bézier Curve, now there is an even more odd item in the tree when using the Tool :

![Draft-bug](https://github.com/FreeCAD/FreeCAD/assets/131592747/ef422a6c-c2ca-483b-8f3c-8d76e3ca4eeb)

How to reproduce:

- Launch FreeCAD and in the Start page choose 2D Draft. Make sure the Tree View is visible.
- Create a Polyline, a B-Spline or a Bézier Curve, click the base point in the 3D view (n°0 on the screenshot above), nothing happens, set a second point (n°1), this odd icon appears in the Tree View, then continue (n°2,3 and so on) until your Object is fully set. When double-clicking (or closing in the Task panel), the icon in the Tree View changes into a Wire or BSpline.

Any clue why is it the case ?
