### ISSUE TITLE
Measurement: Support of individual picking points for distance

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently when selecting two lines, surfaces or features in the new unified measurement tool, the points to calculate a distance are selected automatically by the tool, it seems to choose the closest ones.
It should be possible to select individual picking points that are on the selected features, e.g. select the point on a line or surface from which the distance should be calculated.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37063 (Git)
Build type: Release
Branch: main
Hash: 680792030fd664c94829e2c1b78b21788e8d9879
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * CurvedShapes 1.0.9
  * Curves 0.6.35
  * fasteners 0.5.20
  * OpenTheme 2024.4.20
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.13

```

### Subproject(s) affected?

Core

### Anything else?

https://github.com/FreeCAD/FreeCAD/pull/9750#issuecomment-2042250708

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlorus** [comment]
Isn't this the same as #13708?

**Comment by maxwxyz** [comment]
@hlorus no, this issue here is meant to pick a random, user chosen point, like the current Std_MeasureDistance tool can do, which is the last to replace.

**Comment by hlorus** [comment]
Thanks for clarifying!
