### ISSUE TITLE
Measurement: Annotation is fixed and not moved with the referenced object

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When a measurement (https://github.com/FreeCAD/FreeCAD/pull/9750) is saved as annotation the location of the displayed position in the 3D view is fixed and won't update if the referenced object / geometry is moved.
The issue also persists if the underlying geometry is modified, e.g. change the side length of the cube or the depth of a pad: the dimension value is updated, but not the position of the dimension (Elements not rendered correctly if source object changes).

![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/538558f7-3f38-45f4-aebc-9ee1f6d14aea)

The expected behavior would be, that the measurement needs an update/recompute and will be displayed at the new location of the reference points.

Maybe this is an issue, as the annotation label has no attachment support:
- https://github.com/FreeCAD/FreeCAD/issues/13717

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Core

### Anything else?

- https://github.com/FreeCAD/FreeCAD/issues/13537
- https://github.com/FreeCAD/FreeCAD/issues/13717

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlorus** [comment]
This seems to be a missing recompute. For me it updates if i trigger it manually. That being said it seems to work in simple cases e.g. a measurement on a part Box.

**Comment by hlorus** [comment]
The problem seems to be that we only get signals of our subject but not from it's container (e.g. PD Body). @WandererFan maybe you have an idea how we could solve this?

**Comment by maxwxyz** [comment]
@wwmayer could you support here?

**Comment by wwmayer** [comment]
The measurement object has some kind of caching problem.
1. Create a part box
2. Add a distance measurement
3. Select Vertex1 and Vertex5 of the cube
4. Save the distance measurement
5. Set the length of the cube to 20 mm and recompute the document
6. The label shows the correct value but its length is 10 mm
7. Change the length of the cube back to 10 mm
8. The label shows the correct value but its length is now 20 mm

**Comment by maxwxyz** [comment]
any news on this issue?

**Comment by hlorus** [comment]
Sorry for the silence. AFAIK this is an issue with the distance measurement only, should be solved with #15874.
