### ISSUE TITLE
[Feature Request] Expose DimExtent Value in Python 

### ISSUE THREAD

**Issue by husman2012** [FreeCAD/FreeCAD#13728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The DimExtents are great for measuring the size of the object but the actual output value is not exposed as a property in Python. The Caption property is currently not utilized and this would be perfect to expose the value with. Without this exposed property, we cannot programmatically scale, adjust the location of the view, etc. since we don't know the actual size of the object on the TechDraw page. If this was exposed as a value, we would have greater control over algorithms that dynamically position the views on the page.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by edi271** [comment]
Hopefully solved by PR [https://github.com/FreeCAD/FreeCAD/pull/13976](url)
