### ISSUE TITLE
Measurement: Annotate button is unclear

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#13734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

An action called “annotate” can be understood as adding an annotation to something, for example a comment or icon. Measurements can be considered as annotations, and in a way they are, but saving them in the tree is not the most obvious use for the word. I suggest to rename the button to “Save” and edit the tooltip accordingly.

### Full version info

```shell
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37063 (Git) AppImage
Build type: Release
Branch: main
Hash: 680792030fd664c94829e2c1b78b21788e8d9879
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * BillOfMaterials-WB 0.0.7
  * CosmeticThread3D
  * OpenTheme 2024.4.20
  * Curves 0.6.35
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
This issue can be closed. The button was renamed to Save.
