### ISSUE TITLE
Tool path leak

### ISSUE THREAD

**Issue by KR-Huck** [FreeCAD/FreeCAD#13745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Tool path briefly cuts outside of pocket with adaptive profiling. 

### Full version info

```shell
[code]
OS: Pop!_OS 22.04 LTS (LXDE/LXDE)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Anything else?

![Screenshot from 2024-04-30 21-35-32](https://github.com/FreeCAD/FreeCAD/assets/168589045/a300422c-64a4-407c-930d-cfcdc7f78e10)
[arleft.zip](https://github.com/FreeCAD/FreeCAD/files/15172671/arleft.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Could you try this with the latest weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by KR-Huck** [comment]
Thanks for such a fast response. This fixed the problem, no more tool path leaks! FreeCad is a great program.
