### ISSUE TITLE
Exporting "RobotExample" as .glb or .gltf is missing the robot

### ISSUE THREAD

**Issue by hybridherbst** [FreeCAD/FreeCAD#13753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Expected: 
<img width="1351" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2693840/d14c1137-fc90-4c39-b079-9e2f7dcdd618">

Actual in resulting glb:
<img width="799" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2693840/54f37cfb-8769-4dbb-b9bf-8c5b41c4b344">

### Full version info

```shell
[code]
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

File formats

### Anything else?

Expectation would be that exporting as GLB contains what's visible in the scene view and/or what's selected. My guess is that referenced files are not exported somehow.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
The robot itself is not real geometry, just a helper reference. You can ask on the forum if it is somehow possible to get the dummy robot from the source files.
