### ISSUE TITLE
Arch: error when setting the Terrain property: gp_GTrsf::Trsf() - non-orthogonal GTrsf

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Open attached file
2. In the tree view, choose the Site component
3. Set the Site's Terrain property to the Terrain solid
4. The following error is shown, and the Site component displays a warning icon:

![Captura de pantalla de 2024-05-01 07-40-07](https://github.com/FreeCAD/FreeCAD/assets/148809153/ef0cdd64-aa65-4d7e-a013-f87b15d2a0e0)

```python
07:39:24  pyException: Traceback (most recent call last):
  File "/snap/freecad/1002/usr/Mod/Arch/ArchSite.py", line 678, in execute
    shape = shape.transformGeometry((shape.Placement * pl).Matrix)
<class 'Part.OCCError'>: gp_GTrsf::Trsf() - non-orthogonal GTrsf
07:39:24  Site: gp_GTrsf::Trsf() - non-orthogonal GTrsf
```

Forum discussion: https://forum.freecad.org/viewtopic.php?p=756278#p756278. I've also been pointed out to https://github.com/FreeCAD/FreeCAD/issues/9651 as a possible cause, but I cannot tell whether it applies.

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36999 (Git) Snap 1002
Build type: Release
Branch: main
Hash: ed77603af999525b65dcfc4a41337f15a052c9ef
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * Curves 0.6.35
  * ezydxf
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.4.16.01
  * Assembly4 0.50.12
```

### Subproject(s) affected?

Arch

### Anything else?

1. File to reproduce: [Site-loft.zip](https://github.com/FreeCAD/FreeCAD/files/15174094/Site-loft.zip)
1. I see that https://github.com/yorikvanhavre/FreeCAD-BIM-examples/blob/main/casa%20pela.FCStd uses a solid as Terrain and no errors are shown. This might hint at a regression: this property was working at some point in the past
2. If I copy and paste that example file's terrain to my test file, and then I link it to the Site's Terrain property, I'm getting the same error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
When I have encountered error before, it was because the shape as not "triangulated".   Making a copy of the shape seems to restore/create the triangulation.

            // copying the shape prevents "non-orthogonal GTrsf" errors in some versions
            // of OCC.  Something to do with triangulation of shape??
            // it may be that incremental mesh would work here too.
            BRepBuilderAPI_Copy copier(shape);
            ts = Part::TopoShape(copier.Shape());

**Comment by Roy-043** [comment]
The code already creates a copy of the shape. This is truly a duplicate. Closing it as such.

**Comment by furgo16** [comment]
Thanks. I assume a duplicate of https://github.com/FreeCAD/FreeCAD/issues/9651.

**Comment by furgo16** [comment]
I can no longer reproduce this issue, even though the OCCT version has stayed the same (7.7.1)

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38126 (Git) Snap 1074
Build type: Release
Branch: main
Hash: ac2b65c37b18617101822e5ece06f3c9b21375cd
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

**Comment by likettly** [comment]
i am on OCC 7.7.x ，by using BRepBuilderAPI_GTransform encountering this problem,
