### ISSUE TITLE
FreeCAD version 0.21 STL export object with placement not working properly, seems like moed distance is multiplied by 2

### ISSUE THREAD

**Issue by LubomirJagos42** [FreeCAD/FreeCAD#13785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Reproduced on: 0.21.2

Reproduction steps:
1. add 4 cubes with default settings
2. set for first cube in Base > Placement > Position x to 10mm
3. set for second cube position in y to 10mm
4. set for third cube position in z to 10mm
5. in tree view select all cubes and choose File > Export > STL Mesh .stl
6. create new document
7. import exported mesh

Actual result:
    Cubes are not aligned they are moved each by 20mm in X, Y, Z there is space between them.

Expected result:
    Cubes should be touching each other and should be moved by 10mm.

I tried this same steps in 0.20 and there is STL working fine, can you please look what changed in STL export and why distances in Placement > Position during STL export seems to be multiplied by 2, thanks.

### Full version info

```shell
[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Mesh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LubomirJagos42** [comment]
This is STL after export and import:
![image](https://github.com/FreeCAD/FreeCAD/assets/147299357/8451ecdb-9624-4534-b042-4167a74364ca)

This is what it should looks like:
![image](https://github.com/FreeCAD/FreeCAD/assets/147299357/261ae88c-dcea-484d-b3c5-6ed067537a8e)

**Comment by maxwxyz** [comment]
Can you please try if this is also happening in the latest dev version: weehttps://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by LubomirJagos42** [comment]
hi, tried it on windows version which you sent and there it's running OK

OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37083 (Git)
Build type: Release
Branch: main
Hash: 502f78e111c761cb92c51222605b26b8701fcbca
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)

**Comment by maxwxyz** [comment]
then I'll close this as it's fixed in the new version
