### ISSUE TITLE
3Dconnection Space Pilot stopped working

### ISSUE THREAD

**Issue by ShamanTcler** [FreeCAD/FreeCAD#13801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

My Space Pilot worked and then did not work. Now granted this is an older device. The failure mode is, it is just not recognized by Freecad, I can run the working version, stop, load the non-working, and repeat. As the machine is not rebooted seems isolated to the application.

My guess is it is from this change noted in the blog.

WIP Wednesday 17 April 2024: "pskowronskiTDx contributed code to better support 3Dconnexion devices such as SpaceMouse on Windows using Navlib."

Works:
OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36731 (Git)
Build type: Release
Branch: main
Hash: ac1d887336826c59321352f49a195bf1ef8be2f0
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * btl 0.9.9
  * Curves 0.6.35
* lattice2 1.0.0

Fails:

OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37083 (Git)
Build type: Release
Branch: main
Hash: 502f78e111c761cb92c51222605b26b8701fcbca
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * btl 0.9.9
  * Curves 0.6.35
  * lattice2 1.0.0

### Full version info

```shell
Works:
OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36731 (Git)
Build type: Release
Branch: main
Hash: ac1d887336826c59321352f49a195bf1ef8be2f0
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * btl 0.9.9
  * Curves 0.6.35
* lattice2 1.0.0




Fails:

OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37083 (Git)
Build type: Release
Branch: main
Hash: 502f78e111c761cb92c51222605b26b8701fcbca
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * btl 0.9.9
  * Curves 0.6.35
  * lattice2 1.0.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@pskowronskiTDx could you have a look of this is related to your PR?

**Comment by pskowronskiTDx** [comment]
@maxwxyz Please take a look on the initial thread where similar issue has been already reported:  https://github.com/FreeCAD/FreeCAD/pull/12929#issuecomment-2068927980

**Comment by ShamanTcler** [comment]
I have known these were old, I have had it since it was new. But it still works.

I gave ordered a new one should be here in a week. Cost was about $150  US

**Comment by pskowronskiTDx** [comment]
@ShamanTcler Have you tried with installing the latest 3dxWare (min. v10.5.6) ?

**Comment by ShamanTcler** [comment]
I played around with their drivers for a couple of weeks about 2 years ago. Finally got something to work on ONE machine I have two Win 11 machines. 

![image](https://github.com/FreeCAD/FreeCAD/assets/30176093/30df904b-b0b5-4cf4-8c42-da465eb7d6b3)

This is what ended up working. Anything else did not.

I will try the newer drivers and try to swap back and forth.... 

Nobody really competes with 3DConnexion

**Comment by maxwxyz** [comment]
I'll close this then as related to outdated hardware/drivers.

**Comment by andreymrt** [comment]
@pskowronskiTDx I'm running into this problem too, but with recent hardware.
I was previously on 3dx 10.8.12 and I updated to 10.8.20 after seeing this post, that didn't resolve the problem

![image](https://github.com/FreeCAD/FreeCAD/assets/1222366/bf10b78e-0217-48b1-b639-2f6e9b99a0e7)

**Comment by pskowronskiTDx** [comment]
@andreymrt This is expected. SpaceMouse settings are no longer available in FreeCAD preferences. You can reach these settings in 3dxWare SmartUI now (by going to "Advanced Settings" in the window with SpaceMouse image).

**Comment by pskowronskiTDx** [comment]
@andreymrt Thank you for the suggestion. We will update these tabs.
@chennes What is your preferred way of introducing the changes into Preferences window? Would you like us to remove these tabs on Windows or we should left one just for the information where to find the settings now?
