### ISSUE TITLE
Measurement: label distance placed too far or too close to the model

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The distance between the measured element and the measurement label appears to be fixed to ca. 15-20mm: i.e. it does not adapt to the scale of the model. As such, the default works well for mm-scale models (Part, Part Design, etc.), but the label appears right next to the measured element for m-scale models (Arch).

When the cube's edges are 10 mm the label appears at a reasonable distance to the edges or faces:
![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/a1310cdb-a406-49ca-b01d-742f2402bb7e)

When the cube's edges are 1000 mm the label appears stuck to the edges or faces (it's not, it just appears so as the element to label distance is small in comparison to the model):
![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/1a9b45c8-a86a-40db-a0a3-a2b3880567d7)

Reportedly, the labels can be dragged around. That did not work for me, the labels are not draggable. For what is worth, I'm using the Gesture navigation scheme.

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37085 (Git) Snap 1005
Build type: Release
Branch: main
Hash: c7c07f28c639e82a6d2c58f4aaef5b42cddcc83c
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * Curves 0.6.35
  * ezydxf
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.4.16.01
  * Assembly4 0.50.12
```

### Subproject(s) affected?

Measurement

### Anything else?

Files to reproduce:

1. [Measure - cube 10mm.zip](https://github.com/FreeCAD/FreeCAD/files/15197406/Measure.-.cube.10mm.zip)
1. [Measure - cube 1000mm.zip](https://github.com/FreeCAD/FreeCAD/files/15197408/Measure.-.cube.1000mm.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
the labels should be able to be dragged closer to the model. Each time I try to move it closer, it goes further away.

**Comment by furgo16** [comment]
Closing this as fixed by #13848 . Note: for those using the Gesture navigation mode, labels can be dragged by holding the <kbd>Alt</kbd> key and then dragging with the mouse's left button.

**Comment by maxwxyz** [comment]
The measurement is placed way off and cannot be moved closer to the model. It seems to be dependent of the model scale. This is the BIM example file:

https://github.com/user-attachments/assets/df8bd6fb-ae48-43b0-adfb-3a98e0c64fc1


```
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.25
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.23
  * Curves 0.6.42
```

**Comment by maxwxyz** [comment]
I'll label this as blocker as this is a regression from the old measurement tool where the result is displayed at the location of the measurement.

**Comment by hlorus** [comment]
> The measurement is placed way off and cannot be moved closer to the model. It seems to be dependent of the model scale. This is the BIM example file:
> 
>  measurement-placement.mov 
> ```
> OS: macOS 13.6.7
> Word size of FreeCAD: 64-bit
> Version: 0.22.0dev.38314 (Git)
> Build type: Release
> Branch: main
> Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
> Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
> Locale: C/Default (C)
> Installed mods: 
>   * freecad.gears 1.2.0
>   * OpenTheme 2024.7.3
>   * CfdOF 1.27.4
>   * Defeaturing 1.2.2
>   * Manipulator 1.5.7
>   * fasteners 0.5.25
>   * CurvedShapes 1.0.9
>   * sheetmetal 0.4.23
>   * Curves 0.6.42
> ```

I'm failing to find this example file, could you give me the link or send the file over discord?

**Comment by maxwxyz** [comment]
It's right on the start page Help > Start under the example files at the bottom:
![grafik](https://github.com/user-attachments/assets/d7c87906-15cb-47ca-bc37-bba4123e6126)
