### ISSUE TITLE
On-View-Parameter inputs show at the wrong coordinates

### ISSUE THREAD

**Issue by jwueller** [FreeCAD/FreeCAD#13827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It seems that depending on the attachment settings, the values sometimes refer to the wrong axis, which leads to very strange behavior.

![image](https://github.com/FreeCAD/FreeCAD/assets/388308/f8dd8f4e-0d1e-4186-84a5-e335d3099d88)

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36996 (Git) AppImage
Build type: Release
Branch: main
Hash: d92f74ef019fcedbdcdc32055ab2437c950ac23b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2024.3.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
can you provide a demo file or video? It is unclear how to reproduce.

**Comment by jwueller** [comment]
I'm still trying to isolate what causes this. I'll upload a minimal reproduction when I figure it out.

**Comment by jwueller** [comment]
Here we go: [FreeCAD-On-View-Parameter-Coordinate-Bug.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15212738/FreeCAD-On-View-Parameter-Coordinate-Bug.FCStd.zip)

It only contains a few elements, and the sketch projection clearly differs from the one used to draw the parameter UI.

To me, this suggests that there is more than one way to get from viewport coordinates to world coordinates and back, which is probably a more fundamental issue, but this might be a good way to get to the bottom of it.

**Comment by maxwxyz** [comment]
thank you, I can reproduce:
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/f22257bc-5376-4d15-b4e8-78882a81c817)

@PaddleStroke FYI, there seems to be an issue with the OVPs.

**Comment by jwueller** [comment]
If you rotate the camera in sketch view, you can see that it's not even in the same plane as the sketch sometimes:
![image](https://github.com/FreeCAD/FreeCAD/assets/388308/742a0805-0d02-428a-8a96-6f03ce56c97c)
