### ISSUE TITLE
UI: Transform dragger rendered to large / DPR respect

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The transform dragger is rendered too large on bigger screens (compare with mouse cursor).
Is there a setting to reduce it's size or disable it?
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/ffaf5203-958a-445d-9ddc-519e12b67b02)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37213 (Git)
Build type: Release
Branch: main
Hash: 20e7deb86a8c6c2cd2378f09f8313760933f3a5c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes 1.0.9
  * Curves 0.6.35
  * fasteners 0.5.20
  * OpenTheme 2024.4.20
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qewer33** [comment]
@maxwxyz I can quickly tackle this. Would making it smaller suffice or should there also be a parameter or preference?

**Comment by maxwxyz** [comment]
@obelisk79 what is your opinion on this?

**Comment by obelisk79** [comment]
I think a parameter would suffice

**Comment by maxwxyz** [comment]
@qewer33 any news on this?
