### ISSUE TITLE
Subtle Defect in My FreeCAD Design

### ISSUE THREAD

**Issue by AverageDwarfGiant** [FreeCAD/FreeCAD#13888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Something isn't right in a design I've created in FreeCAD. It's  actually nothing major but it is there. I don't know if I'm in the correct forum for this but here it is:
![FreeCADAnomaly](https://github.com/FreeCAD/FreeCAD/assets/126213957/d3c2a5a3-327c-4e9f-b51a-09339c055128)
[MyFreeCADDesign.zip](https://github.com/FreeCAD/FreeCAD/files/15241679/MyFreeCADDesign.zip)

### Full version info

```shell
[code]
OS: Ubuntu Core 20 (LXQt/Lubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) Snap 908
Build type: Release
Branch: tag: 0.21.2
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * CurvedShapes 1.0.5
  * Curves 0.6.23
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please use the forum for help requests.
