### ISSUE TITLE
Part Design UI - NewSketch Plane attachment/orientation selection widget issue

### ISSUE THREAD

**Issue by marcuspollio** [FreeCAD/FreeCAD#13945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating a new Sketch in Part Design, the user has to choose a plane attachment/orientation either in the task panel or using the "widget" in the 3D view. While it works ok, the widget in the 3D view has an inconsistent behaviour: when doing a first sketch in a Body, the size of the widget is set depending on the zoom level of the 3D view, but adding further sketches display a different size with the former and between planes of different orientations.

To reproduce:
- Start FreeCAD and in Start choose Parametric Part (Part Design).
- In a Body, create a NewSketch. See the planes in the 3D view (first screenshot below).
- Finish your sketch and add features if you want to.
- Select the same body or the previous sketch and add a second NewSketch. See the size of the planes and how the YZ one is not matching the others in the 3D view now (second screenshot).

 
![PD1](https://github.com/FreeCAD/FreeCAD/assets/131592747/61db5e99-9c39-42d8-9d73-309d19a50ca0)

![PD2](https://github.com/FreeCAD/FreeCAD/assets/131592747/da77ca7f-0f31-4846-87de-5637c04354a9)

### Full version info

```shell
OS: GNU/Linux Ubuntu 22.04 LTS based (DE:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37243 (Git)
Build type: Release
Branch: main
Hash: 0095e52466c79c2135fce860a341554f3f51156c
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk , OCC 7.5.1
```

### Subproject(s) affected?

PartDesign

### Anything else?

Not related to this issue, but what do you think of the "Select feature" name in the Task panel of this Part Design NewSketch ?
When using the Sketcher Workbench and doing NewSketch, the naming seams more appropriate :

![Sketch1](https://github.com/FreeCAD/FreeCAD/assets/131592747/758256d6-9cf4-4299-a298-a6b0c2be40e8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I guess this issue is a combination from:
- https://github.com/FreeCAD/FreeCAD/issues/11133
- https://github.com/FreeCAD/FreeCAD/issues/12106
- https://github.com/FreeCAD/FreeCAD/issues/12584

I'll close this, please let me know otherwise.

**Comment by marcuspollio** [comment]
@maxwxyz No worries =D
This issue was more about the orientation planes size differences tough, but if it's reworked, it will probably be solved.
