### ISSUE TITLE
Sketcher: arc length higher than half diameter looks bad

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#13954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In a sketch, draw an arc then constrain its length making sure it is longer than half the perimeter of a circle having the same radius. It looks like this:

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/dedb36d3-2b1d-476a-9238-9ec90e49f263)

While the result is rather clear when you think about it, it’s not optimal, if only because the longer the arc, the shorter the dimension look. It could be improved by making the dimension go around the arc, like angle constraints, while keeping the two lines parallel. Here is a proposal:

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/6effecf0-92cd-4442-892b-754be0154402)

### Full version info

```shell
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37249 (Git) AppImage
Build type: Release
Branch: main
Hash: 3acbc561f299b4cddea8215c387a52f3d5132cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * BillOfMaterials-WB 0.0.7
  * CosmeticThread3D
  * OpenTheme 2024.4.20
  * Curves 0.6.35
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment]
@FlachyJoe @PaddleStroke

**Comment by FlachyJoe** [comment]
@maxwxyz you can assign me.

**Comment by FlachyJoe** [comment]
@FreeCAD/design-working-group can you define the requested dimension display?

**Comment by pierreporte** [comment]
@FlachyJoe the proposal is the right display.

**Comment by Reqrefusion** [comment]
<img width="752" height="577" alt="Image" src="https://github.com/user-attachments/assets/b432ed2a-be74-469c-b1d6-f59094d163f6" />


It seems this problem has returned. Also, the label and line are moving in the opposite direction. @FlachyJoe @maxwxyz 
```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.2.0dev.20260324 (Git shallow)
Build date: 2026/03/24 17:14:33
Build type: Release
Branch: (HEAD detached at 1bc5980a7)
Hash: 1bc5980a7ff302a55c617181e774cd5cd2a9443a
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: SiemensNX/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
```
