### ISSUE TITLE
Please read before posting issues here

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FreeCAD#14]
This github repository is only a mirror of the official FreeCAD Git repository at http://sourceforge.net/p/free-cad/code/ci/master/tree/ and it is not monitored by the FreeCAD community and developers.

We kindly ask you to report issues either on the FreeCAD forum at http://forum.freecadweb.org (recommended), or directly on the FreeCAD issues tracker at http://www.freecadweb.org/tracker/ . Issues posted here might not receive an answer.

You can also consult the FAQ and more documentation on the wiki at http://www.freecadweb.org/wiki/

**Comment by chennes** [comment]
Closing pending migration of bugs from Mantis.
