### ISSUE TITLE
TechDraw: Hatch not correctly exported to PDF

### ISSUE THREAD

**Issue by mpfusion** [FreeCAD/FreeCAD#14027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The PDF export lacks the 2nd hatch in the following example:

TechDraw window:
![missinghatch-td](https://github.com/FreeCAD/FreeCAD/assets/698973/ebd9d204-80c3-481b-b286-63529776f313)

SVG export:
![missinghatch-svg](https://github.com/FreeCAD/FreeCAD/assets/698973/dcaf5527-6df8-4a28-a37b-38f5277f8cfd)

PDF export:
![missinghatch-pdf-export](https://github.com/FreeCAD/FreeCAD/assets/698973/ed479237-21d3-4d9a-9b15-600e003b5a73)

To reproduce:

- open attached file
  [missinghatch.tar.gz](https://github.com/FreeCAD/FreeCAD/files/15319511/missinghatch.tar.gz)
- open TD
- Export PDF or Print All Pages

Forum: https://forum.freecad.org/viewtopic.php?t=87667

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37303 (Git)
Build type: Release
Branch: main
Hash: 869cb1f83b5f92ee134dafde46c9c5e0dceb8889
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/Ireland (en_IE)
Installed mods: 
  * BOLTSFC
  * kicadStepUpMod 11.1.5
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mpfusion** [comment]
Seems related, indeed. However, I couldn't find an open bug report for that issue.

**Comment by maxwxyz** [comment]
could this be related to an older issue (closed) https://github.com/FreeCAD/FreeCAD/issues/11088

**Comment by WandererFan** [comment]
related issue: TechDraw: Hatching clip path functionality is missing from svg export #13338

**Comment by mpfusion** [comment]
As I noted in the OP the SVG export is fine, it's the _PDF_ export that's having an issue. But that issue might still be related, though.
