### ISSUE TITLE
Sketcher: Dimension arrows missing

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#14049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the current weekly either all or one dimension arrow is missing from the constraints:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/1069fe21-5332-447f-a0b0-39b906ff2bc7)

Not sure which PR caused this regression https://github.com/FreeCAD/FreeCAD/pull/13966, https://github.com/FreeCAD/FreeCAD/pull/13844, ...?

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37302 (Git)
Build type: Release
Branch: main
Hash: 0e24e121eb3e5708c380596e0a9fd583befac977
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes 1.0.9
  * Curves 0.6.35
  * fasteners 0.5.20
  * OpenTheme 2024.5.3
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FlachyJoe @PaddleStroke @bgbsww  FYI

**Comment by FlachyJoe** [comment]
Found, a PR is coming.

**Comment by furgo16** [comment]
I can confirm. I noticed this a couple of days ago, and I thought that that was a design decision. Glad to hear it's a bug.

**Comment by maxwxyz** [comment]
@FlachyJoe is this related to:
- https://github.com/FreeCAD/FreeCAD/issues/13557
The arrow tips also seem to change side when viewing from behind.
Demo:

https://github.com/FreeCAD/FreeCAD/assets/6246609/5fc2c8ca-2be9-4e43-a6a9-0ac0906e2722
