### ISSUE TITLE
Missing things at dxf import

### ISSUE THREAD

**Issue by hw-schrauber** [FreeCAD/FreeCAD#14055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I import the attached dxf only the outline contour is imported. The two inside objects are not imported. A work a round is to open the dxf in a different cad program, export to dwg and import the dwg in FreeCAD. Dxf-direct-import shows 121 items. Via dwg the same shows 171 items.
[GB 76.zip](https://github.com/FreeCAD/FreeCAD/files/15335115/GB.76.zip)

### Full version info

```shell
[GB 76.zip](https://github.com/FreeCAD/FreeCAD/files/15335115/GB.76.zip)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please provide full about info of the version you are using. Did you try this in the latest weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by luzpaz** [comment]
@hw-schrauber please add full [About](https://wiki.freecad.org/About) info

**Comment by yorikvanhavre** [comment]
Looks ok to me. Can you try a development build?

![image](https://github.com/user-attachments/assets/03935765-a816-4bb3-85ce-ae0c712eecc5)

**Comment by luzpaz** [comment]
No response from OP. Closing. Please re-open if develpment build shows incorrect behavior.
