### ISSUE TITLE
Problem obtaining ebook

### ISSUE THREAD

**Issue by Whomsonever** [FreeCAD/FreeCAD#14073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

7:23:44  (js) A cookie associated with a cross-site resource at http://outbrain.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
07:23:44  (js) Unrecognized feature: 'attribution-reporting'.
07:23:46  (js) Uncaught (in promise) NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
07:24:01  (js) Uncaught SyntaxError: Unexpected token '='

### Full version info

```shell
7:23:44  (js) A cookie associated with a cross-site resource at http://outbrain.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
07:23:44  (js) Unrecognized feature: 'attribution-reporting'.
07:23:46  (js) Uncaught (in promise) NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
07:24:01  (js) Uncaught SyntaxError: Unexpected token '='
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
How is this related to FreeCAD?
