### ISSUE TITLE
[Feature Request] Ability to set a different "tip" for a clone

### ISSUE THREAD

**Issue by alpdigitech** [FreeCAD/FreeCAD#14108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It would be great to have a variable for a clone that indicates what "tip" it should use. Blank means whatever the tip of the original body will also be the clone's tip. The clone tip, when set, can be any valid tip from the original body.

This will help a lot in further organizing multiple bodies that have lots of similar features.

### Full version info

```shell
OS: macOS 14.4.1
Version: 0.22.0dev.37249 (Git)
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@alpdigitech I guess what you are looking for is already possible. 
When you clone a body you can define the base feature.
I've made a quick demo for you:

https://github.com/FreeCAD/FreeCAD/assets/6246609/e24f58b1-6cb5-4d04-82af-5ed042124e01


and the file:
[demo-tip.zip](https://github.com/FreeCAD/FreeCAD/files/15355773/demo-tip.zip)
