### ISSUE TITLE
BIM: NativeIFC import-export prefs page changes indices of subsequent pages causing errors

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#14137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The new NativeIFC import-export preference page is inserted before the DXF page. This changes the indices all subsequent pages. If the "Show this dialog when importing and exporting" checkbox on the DXF page is checked, the NativeIFC page now opens instead.

It may also be a good idea to look at the order of all import-export pages.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37358 (Git)
Build type: Release
Branch: main
Hash: 3a0152b076dd7791c9724c286963d74b5814e24f
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

BIM/Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Good point.

Maybe the NativeIFC pref dialog should go to Arch (to be renamed to BIM) instead of I/O... I'll do that together with #14121
