### ISSUE TITLE
FEM: Constraint rigid body should use bigger spheres for reference point symbols

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#14133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The sphere showing the location of the rigid body reference point should be bigger because it may get covered by the other symbols representing this constraint:

![ref point](https://github.com/FreeCAD/FreeCAD/assets/59876896/1693ce24-4858-4e62-b6bf-2bf421d4bacc)

IMO it should be bigger than those spheres on the sticks.

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37358 (Git)
Build type: Release
Branch: main
Hash: 0e24e121eb3e5708c380596e0a9fd583befac977
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/2048ecf0-8c70-4b31-b999-85f5336c73d3)

**Comment by marioalexis84** [comment]
We can also use another symbol. Maybe three orthogonal crossed lines?
![rigid_body-symbol](https://github.com/FreeCAD/FreeCAD/assets/53127171/ff2908b3-181f-4d9b-bce7-0295da0c0b86)

**Comment by FEA-eng** [comment]
> We can also use another symbol. Maybe three orthogonal crossed lines?

Or a cross, maybe even with label like in Abaqus (just way bigger):

![RP](https://github.com/FreeCAD/FreeCAD/assets/59876896/a22405d5-3d66-41ea-be62-892cf4bbe7e0)

But I prefer a sphere. 

A classic spider as a way to represent the whole constraint would be ideal but probably also hard to implement:

![RB spider](https://github.com/FreeCAD/FreeCAD/assets/59876896/ebe8c412-b1b6-48c2-b091-6181e3ffbc80)
