### ISSUE TITLE
Part Design pocket won't open holes

### ISSUE THREAD

**Issue by theosib** [FreeCAD/FreeCAD#14149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Since Part Design can't handle multiple bodies, I decided to work around it by making a partial pocket, filling in struts that would connect parts into one body, and then shaving off the bottom to open up the holes. But when I try to do that, I get a totally non-specific error about "Cut out of base feature failed."

To see what I'm talking about, go into Pocket003 and change the thickness from 0.199 to 0.2.

### Full version info

```shell
[code]
OS: macOS 13.6
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

None

### Anything else?

[zeromark-bookmark-title2.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15369920/zeromark-bookmark-title2.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
The models seems poorly constructed I get errors when trying to refine the model. Please consult the forum for help requests. If there still seems to be a bug come back to this one.
