### ISSUE TITLE
Sketch elements completely different in Part Design workbench

### ISSUE THREAD

**Issue by theosib** [FreeCAD/FreeCAD#14151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This bug is hard to describe clearly. I have some small sketch elements that I want to pad. They look fine in the Sketcher, but when I return to the Part Design workbench, the 3D geometry of those elements is completely different. You'll have to see the images to get what I mean.

In the screenshot from the sketcher, you can see that there are some vertical bars I've put across the letter "k" as support for a 3D print.
<img width="546" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/5619995/2e44c1e7-d2d1-41c0-aad6-af3dc2749550">

But when I return to the Part Design workbench, geometry near one of those bars is completely different, in all three dimensions.
<img width="686" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/5619995/2c787d52-ff26-45e2-b961-c3c7540b0e09">

The sketch you need to look at is vstripes. And the corresponding pad is Pad004.

I've also tried all sorts of things to work around this. But any time I have a bar that crosses that lower right leg of the 'k', it messes up.

### Full version info

```shell
[code]
OS: macOS 13.6
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

None

### Anything else?

[zeromark-bookmark-buggy.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15370190/zeromark-bookmark-buggy.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
YOu can only have closed profiled not overlapping ones. Please consult the forum for such help requests and not file a GitHub issue everytime. TIA.
