### ISSUE TITLE
FreeCAD craches when using ruler tool 

### ISSUE THREAD

**Issue by Amnolystos-Dev** [FreeCAD/FreeCAD#14170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I import an image on in FreeCAD and then I try to measure a distance with the ruler tool it crashes. 
I tried with multiple images and the problem is the same. 

### Full version info

```shell
[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
I can't confirm it but please try in the 0.22 dev version (available as weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds). In fact, the ruler tool should soon be replaced by the new unified measurement tool: #13810

**Comment by Amnolystos-Dev** [comment]
Hello, 
Yeah it works with the weekly build.
