### ISSUE TITLE
BIM: error in BIM workbench for "Number format=Operating system" in General Preferences Settings

### ISSUE THREAD

**Issue by balrobs** [FreeCAD/FreeCAD#14208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. start FreeCAD
2. goto Edit\Preferences...\General\Language and number format and set Language=English, Number format=**Operating system**
3. open an IFC-file with the comand _File\Open..._ e.g. this one [my_Test.ifc.txt](https://github.com/FreeCAD/FreeCAD/files/15403561/my_Test.ifc.txt)
4. use the option _Locked (IFC objects only)_
5. change from _Part Design_ workbench to _BIM_ workbench
6. notice following error:
```
15:22:18  Imported my_Test.ifc ( 0.0 Mb ) in 00:00
15:22:31  Traceback (most recent call last):
15:22:31    File "C:\Program Files\FreeCAD_weekly-builds-37436-conda-Windows-x86_64-py311\Mod\BIM\bimcommands\BimViews.py", line 183, in update
15:22:31      building, _ = getTreeViewItem(obj)
15:22:31                    ^^^^^^^^^^^^^^^^^^^^
15:22:31    File "C:\Program Files\FreeCAD_weekly-builds-37436-conda-Windows-x86_64-py311\Mod\BIM\bimcommands\BimViews.py", line 445, in getTreeViewItem
15:22:31      lvH = round(float(lvHStr.split(" ")[0]), 2)
15:22:31                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:22:31  ValueError: could not convert string to float: '0,00'
```
Steps to bypass error:

1. as before
2. goto Edit\Preferences...\General\Language and number format and set Language=English, Number format=**Selected language**
3. as before
4. as before
5. as before
6. this time no error

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37436 (Git)
Build type: Release
Branch: main
Hash: 040502280fc9637fb3aada037523283168b81a02
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
```

### Subproject(s) affected?

BIM/Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@yorikvanhavre FYI
