### ISSUE TITLE
BIM Setup - 'Default size of a grid square' value does not work

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#14215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Changing the value in the 'Default size of a grid square does not work' box in the BIM Setup dialogue does not change the grid size in the projects.

Tested in version 0.22 and 0.21.2

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37436 (Git)
Build type: Release
Branch: main
Hash: 040502280fc9637fb3aada037523283168b81a02
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * QuickMeasure 2022.10.28
```

### Subproject(s) affected?

BIM/Arch

### Anything else?

Relevant forum thread: https://forum.freecad.org/viewtopic.php?t=87680

![daefault-size](https://github.com/FreeCAD/FreeCAD/assets/149316569/51904fe5-8c34-4e1f-8ba1-2e3eeec8826a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@yorikvanhavre can confirm
