### ISSUE TITLE
Dev - Sketcher - Pasted circle is arbitrarily constrained .

### ISSUE THREAD

**Issue by GAZ082** [FreeCAD/FreeCAD#14233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I copy and when I paste a circle it gets coincident constrained on an arbitrary entity. I have auto-constrains disabled.

https://github.com/FreeCAD/FreeCAD/assets/100194/c49878fe-84e4-4444-949d-2183c1179bcd

### Full version info

```shell
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37436 (Git) AppImage
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke FYI

**Comment by PaddleStroke** [comment]
It appears that the circle you copy has a point on object constraint with an axes. I think the problem is here, the axes has a geoId of -1 if I recall correctly. It is likely that I did not handle separately the case of axes geoIds.
