### ISSUE TITLE
on master branch of freecad there are some include missing

### ISSUE THREAD

**Issue by Tarot67** [FreeCAD/FreeCAD#14245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

some include are missing in file 
in file FreeCAD/src/Mod/TechDraw/App/LineGenerator.h
after
#include <QPen>
+#include <map>

and in file 
FreeCAD/build/src/Mod/CAM/PathSimulator/AppGL/CAMSimulator_autogen/EWIEGA46WW/../../../../../../../../src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.h

-#include <QtGui/qopenglpaintdevice.h>
+#include <QtOpenGL/qopenglpaintdevice.h>

And after that it building 

### Full version info

```shell
I use FreeCAD on master branch with Qt6
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tarot67** [comment]
the text between '<' abd '>"=' hasbeen remove Grrr

After QPen
add
'#include <map>'

**Comment by Tarot67** [comment]
map

**Comment by Tarot67** [comment]
after QPen include add include map

**Comment by maxwxyz** [comment]
@WandererFan can you confirm?

**Comment by obelisk79** [comment]
confirmed issue, adding the missing include resolved the issue
