### ISSUE TITLE
Draft Facebinder produces no display, but creates a Facebinder in the tree view.

### ISSUE THREAD

**Issue by macdroid53** [FreeCAD/FreeCAD#14242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Facebinder produces nothing in the 3D view.
(Same result if the face is a face of an imported step/iges file)

Create a Part Cube
Select a face of the cube
In Draft workbench click Facebinder
A Facebinder is shown in the tree view but nothing in the 3D view
![Screenshot_20240523_112752](https://github.com/FreeCAD/FreeCAD/assets/6831752/a1f1b089-887e-401b-89df-5e36a3cc1016)

[NoFacebinder.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15419094/NoFacebinder.FCStd.zip)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37462 (Git)
Build type: Release
Branch: main
Hash: d12635246f86947031776a42714028b236bd05ed
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * MnesarcoUtils 0.2.5
  * lattice2 1.0.0
  * Curves 0.6.37
  * ArchTextures
  * Nodes 0.1.36
  * OpenTheme 2024.5.16
  * Help 1.0.3
  * QuickMeasure 2022.10.28
  * Manipulator 1.5.7
  * freecad.gears 1.2.0
  * sheetmetal 0.4.14
  * Silk 0.1.5
  * kicadStepUpMod 11.1.5
  * DynamicData 2.62.0
  * workfeature-macro
  * fasteners 0.5.21
  * Defeaturing 1.2.2
  * CurvedShapes 1.0.9
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@Roy-043 FYI

**Comment by Roy-043** [comment]
Confirmed. This issue may be caused by #14169.
