### ISSUE TITLE
BIM: some Tools are not greyed out with no active Document, leading to errors

### ISSUE THREAD

**Issue by marcuspollio** [FreeCAD/FreeCAD#14250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using the BIM workbench but without any Document (the Start elements are shown instead), some tools are falsly available in the Toolbars and Menus, leading to errors in the Report/Notifications.

These tools are:
- BIM_Project
- BIM_Setup
- BIM_ProjectManager
- BIM_Windows
- BIM_Layers
- BIM_Material
- BIM_Preflight
- BIM_Text
- BIM_SimpleCopy
- BIM_Compound
- BIM_Offset2D
- BIM_Extrude
- BIM_Cut
- BIM_Fuse
- BIM_Common
- BIM_Rewire
- IFC Explorer/Diff.../Expand/

![BIM](https://github.com/FreeCAD/FreeCAD/assets/131592747/8ac2a73f-cce8-4c15-8ade-05c832122228)

The Draft Workbench does not suffer this issue :

![Draft](https://github.com/FreeCAD/FreeCAD/assets/131592747/541efd80-55f0-4301-bf4e-d19d8191798a)

### Full version info

```shell
OS: GNU/Linux Ubuntu 22.04 LTS based distro (DE:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37463 (Git)
Build type: Release
Branch: main
Hash: b71c2a3278228f8af0093ef23d97e9dda093d473
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk , OCC 7.6.3
```

### Subproject(s) affected?

BIM/Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This is the same issue as #14061.
PR  #14207.

Closing this as a duplicate.
