### ISSUE TITLE
BIM: Error when entering measurements to walls before creating them

### ISSUE THREAD

**Issue by gianlucafiore** [FreeCAD/FreeCAD#14283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/db2adaf6-7cf3-4f45-a105-dd1705606474)
![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/053e71e6-0b46-4791-8883-147d32a2e83d)
The steps to follow are: 
- Click the Wall tool to start drawing one from scratch. 
- Enter wall height and width measurements.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git)
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Argentina (es_AR)
Installed mods: 
  * Dracula 0.0.5
  * OpenDark 2024.3.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can confirm.
@yorikvanhavre FYI

**Comment by yorikvanhavre** [comment]
Confirmed too. Preparing a PR
