### ISSUE TITLE
CAM: preference card needs revision [AppImage]

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD#14298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

if you use a language other than English in the GUI, the layout of the text is incorrect. The text overlaps the boxes.

https://forum.freecad.org/viewtopic.php?style=4&t=87357

### Full version info

```shell
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git) AppImage
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
There seems to be a lot of white space to the right, is this only for the CAM settings?

**Comment by kaktusus** [comment]
Yes, and only this one preference card.
I have not noticed such an anomaly in the other workbenches.

**Comment by maxwxyz** [comment]
@sliptonic FYI

**Comment by xtemp09** [comment]
I cannot reproduce.

<details><summary>Polska</summary>

![KUbuntu 64-bit-2024-05-28-17-52-38](https://github.com/FreeCAD/FreeCAD/assets/9303235/628d424e-694e-45ad-ab1d-70daa57084c6)


![KUbuntu 64-bit-2024-05-28-17-52-56](https://github.com/FreeCAD/FreeCAD/assets/9303235/29d8d3d0-e596-4428-91d4-2096d9853c56)



</details>

<details><summary>Portuguesa</summary>


![KUbuntu 64-bit-2024-05-28-17-53-46](https://github.com/FreeCAD/FreeCAD/assets/9303235/d13b80b7-f457-41b6-b2c7-98f158722df3)



</details>

<details><summary>Ubuntu 22.04.3 LTS (KDE/plasma)</summary>


```ruby
OS: Ubuntu 22.04.3 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git)
Build type: Debug
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.10.12, Qt 5.15.12, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: Polish/Poland (pl_PL)
```


</details>

@kaktusus, do stable and oldstable versions of _FreeCAD_ show the same behavior?

**Comment by kaktusus** [comment]
Yes this "design" I have had for a long time.
I do not use the stable version.

**Comment by kaktusus** [comment]
problem solved:
https://github.com/FreeCAD/FreeCAD/pull/14343

**Comment by kaktusus** [comment]
xtemp09 
thank you for your efforts.
