### ISSUE TITLE
DRAFT: Error Shape2DView

### ISSUE THREAD

**Issue by gianlucafiore** [FreeCAD/FreeCAD#14312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/197b233d-a085-4127-8f50-0c13af50a892)
![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/8b76854a-cd7e-4990-8035-34ed29add80d)
### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git)
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Argentina (es_AR)
Installed mods: 
  * Dracula 0.0.5
  * OpenDark 2024.3.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Are there any steps to reproduce? Does it work in the stable version?
@Roy-043 FYI

**Comment by gianlucafiore** [comment]
https://drive.google.com/file/d/11YBxG2j8rRH4YZv7gNK0Y38-0bpRjdnr/view?usp=drive_link
I append test file

From the BIM workbench select a Building Level, click on the section tool, then select that created section and go to the Draft workbench, click on the Shape2DView tool and the aforementioned error arises

![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/e8943cb6-5e95-4444-a871-3e4d521971ee)

**Comment by Roy-043** [comment]
This issue is presented in a very confusing manner. The images show a different model than the file. And the file does not produce the "This object is immutable" error, which is the main issue I think. The linked PR does fix that error however.

The images show several other errors. These should be addressed in separate issues.

**Comment by gianlucafiore** [comment]
@Roy-043  Sorry for my mistake in the file link, I took another one from the folder that uploaded the tests for the issues.

Now I correct the link
