### ISSUE TITLE
UI: Classic theme transparent overlays still have borders

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#14339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With the current Classic theme the panels with activated overlay mode and transparency enabled still show white borders around them:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/ad561e81-d2eb-4a2f-8c75-44a118b746ee)

There should not be borders when they are transparent.
@MisterMakerNL FYI, is this fixed also in https://github.com/FreeCAD/FreeCAD/pull/13772 ?

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37543 (Git)
Build type: Release
Branch: main
Hash: 3eb45b045cdda9d5bfe11baba2567a1df90f064c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.25.16
  * Curves 0.6.37
  * dodo 1.0.1
  * fasteners 0.5.21
  * freecad.gears 1.2.0
  * OpenTheme 2024.5.16
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.14
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

Related: https://github.com/FreeCAD/FreeCAD/issues/12424

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krushia** [comment]
There is no overlay stylesheet for classic theme. What stylesheet are you using?

**Comment by MisterMakerNL** [comment]
I changed the defaults here https://github.com/FreeCAD/FreeCAD/pull/13772/commits/15c4f104d79c351df9f64bc14faba01fae3e11ab
But I'm not sure if this also applies too no-stylesheets.

**Comment by maxwxyz** [comment]
The problem is it does not switch back to `Auto` Overlay stylesheet if you had a different theme applied and switch back to Classic.
When I manually switch it to auto and restart FreeCAD it looks like this:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/4a7b1ae1-8290-4d28-aef5-f0b25ce21195)

Various issues:
- Selected tree item is not legible
- Property view is dark and not legible
- Task dialog has a weird mixed appearance (light+dark)
- The text of buttons in the task dialog are not readable

**Comment by MisterMakerNL** [comment]
> The problem is it does not switch back to `Auto` Overlay stylesheet if you had a different theme applied and switch back to Classic. When I manually switch it to auto and restart FreeCAD it looks like this: ![grafik](https://private-user-images.githubusercontent.com/6246609/334707258-4a7b1ae1-8290-4d28-aef5-f0b25ce21195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzU0NzUsIm5iZiI6MTcxNjk3NTE3NSwicGF0aCI6Ii82MjQ2NjA5LzMzNDcwNzI1OC00YTdiMWFlMS04MjkwLTRkMjgtYWVmNS1mMGIyNWNlMjExOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDkzMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE1NDljZWU5YzlkNmVjYTUyY2U3NmU4N2I0ZTRkMzI0YmQyYjZlZWU2ZmYyYTRmZjkzMTFlYjA1NGY2N2I4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OPynhRGrleS8ViVrc787d7cSo_hjnzyI-YHNo7iZ5xU)
> 
> Various issues:
> 
>     * Active Body/Object in the tree is not legible
> 
>     * Property view is dark and not legible
> 
>     * Task dialog has a weird mixed appearance (light+dark)
> 
>     * The text of buttons in the task dialog are not readable
> 
>     * Task dialog / panel has still a white border

This needs some work. Maybe we can pull the stylesheet from the code and just apply a stylesheet and add it too classic.cfg.
I only see that the code uses some pallet(dark) that I never used. Not sure if this works in a qss file.

**Comment by MisterMakerNL** [comment]
Fixed it in https://github.com/FreeCAD/FreeCAD/pull/13772 please try it!

**Comment by pierreporte** [comment]
I still have borders with the latest weekly, that has #13772 merged in.

![image](https://github.com/FreeCAD/FreeCAD/assets/2029853/85c75444-e59b-475e-be74-1d1bf774d305)

```
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 (Git) AppImage
Build type: Release
Branch: main
Hash: 30f7f2688921e6e5242beaa9d71e0fdd844b20e3
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * BillOfMaterials-WB 0.0.7
  * CosmeticThread3D
  * OpenTheme 2024.5.16
  * Curves 0.6.39
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.18
```

**Comment by MisterMakerNL** [comment]
@pierreporte I can see on the lower corners of the task windows that you have not set the correct Overlay-stylesheet or it isn't working properly, as the bottom corners should be rounded off.
Can you check which Overlay stylesheet you have set? Maybe press on the style in the first run settings.

**Comment by pierreporte** [comment]
It used to be OpenLight or OpenDark. Now after testing your new themes it’s “Dark Theme + Dark Background” and there is no borders anymore. Why is this a separate setting and why is it not updated when the theme was changed from Open*** back to classic?

I did a new test: set the overlay theme as Auto and FreeCAD with OpenDark theme, restart, and change app theme back to Classic. Overlay theme is OpenDark.

**Comment by MisterMakerNL** [comment]
Aha yeah, it could be so that classic doesn't change the overlay when it is already set.
I think it only sets it when nothing is set.

This could be an easy fix by adding it too the classic.cfg file!

Auto only works when dark or light is in the stylesheet name.
It might all be a bit overly complicated and unnecessary, I think the idea was that with auto you don't have to change the overlay. But the issue is auto is based of if there is dark or light in the stylesheet name. But that doesn account for the background color, which is kinda important for overlay.
