### ISSUE TITLE
Problem: New Start page [AppImage]

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD#14347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The layout of the icons looks incorrect. The text of the icons cannot be read.

https://forum.freecad.org/viewtopic.php?style=4&p=761903#p761903

https://github.com/FreeCAD/FreeCAD/issues/13991#issuecomment-2109434675

related topic:
https://github.com/FreeCAD/FreeCAD/pull/14279

### Full version info

```shell
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37543 (Git) AppImage
Build type: Release
Branch: main
Hash: 3eb45b045cdda9d5bfe11baba2567a1df90f064c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.37
  * OpenDark 2024.3.13
  * Render 2024.1.23
  * Alternate_OpenSCAD 1.0.0
  * Plot 2022.4.17
  * kicadStepUp 10.23.2
  * dodo 1.0.1
  * Reinforcement
  * Rocket 3.3.0
  * pcb 6.2023.1
  * freecad.gears 1.2.0
  * woodworking 0.21.2.33771
  * Marz 0.1.5
  * kicadStepUpMod 11.1.5
  * Movie.backup1716816115.789322 2024.2.15 (Disabled)
  * Movie 2024.2.15
  * fasteners.backup1716822852.9058104 0.5.21 (Disabled)
  * fasteners 0.5.21
  * sheetmetal.backup1716822856.2948024 0.4.14 (Disabled)
  * sheetmetal 0.4.14
```

### Subproject(s) affected?

None

### Anything else?

The following releases:

![obraz](https://github.com/FreeCAD/FreeCAD/assets/39754351/76eee51c-20b3-43ad-a54f-cf71b8f1c850)

![obraz](https://github.com/FreeCAD/FreeCAD/assets/39754351/4145d8c4-1367-47cf-bb91-f9aab246a318)

![obraz](https://github.com/FreeCAD/FreeCAD/assets/39754351/9aebc9f6-d2bb-4bbf-be39-23689f30df7b)

Such an abnormal condition exists until now.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I cannot reproduce on Windows with the latest weekly, even when resizing the window.
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/ceee6801-ff9e-4e9c-8cca-d2a184c8acd6)

**Comment by kaktusus** [comment]
Are you using OpenDark?

**Comment by JohnOCFII** [comment]
> Are you using OpenDark?

Not currently, no.  Just using the Classic (default) theme for now.  (I got myself all tangled up so used the nuclear option of deleting my user.cfg to get back to a known starting point).

**Comment by maxwxyz** [comment]
I'm using OpenTheme as OpenDark was depreciated.
Does it only happen to you with OpenDark? Could you uninstall and test with OpenDark in OpenTheme?

**Comment by kaktusus** [comment]
This seems to have helped but the problem is not completely solved.
I have the impression that the button text uses light ink. When I switch the theme in OpenLight everything is visible.

![obraz](https://github.com/FreeCAD/FreeCAD/assets/39754351/d964f945-e692-42a4-8473-761bdf9da92e)

![obraz](https://github.com/FreeCAD/FreeCAD/assets/39754351/a59db868-7362-4c30-929c-e066e88508e3)

**Comment by maxwxyz** [comment]
Then this seems to be an issue of the theme, not FreeCAD. You can copy the issue to https://github.com/obelisk79/OpenTheme/

**Comment by MisterMakerNL** [comment]
> I cannot reproduce on Windows with the latest weekly, even when resizing the window. ![image](https://private-user-images.githubusercontent.com/6246609/334928525-ceee6801-ff9e-4e9c-8cca-d2a184c8acd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjE4NTMsIm5iZiI6MTcxNzA2MTU1MywicGF0aCI6Ii82MjQ2NjA5LzMzNDkyODUyNS1jZWVlNjgwMS1mZjllLTRlOWMtOGNjYS1kMmExODRjOGFjZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDkzMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdlYjBlYjUxN2UyMjc3ZTI4YTRjMWNiOGY2Y2JjZmI3MjhiODIyNzdlNmFlOWM3YzYwMjA1ZjYyN2MxMjk2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZUcMq6Tz7DXnVSl1w9-KHZ5J2UJ9F7s6rdw0dYo1dx8)

Switch between stylesheets a couple of times and it will break.

**Comment by MisterMakerNL** [comment]
> I cannot reproduce on Windows with the latest weekly, even when resizing the window. ![image](https://private-user-images.githubusercontent.com/6246609/334928525-ceee6801-ff9e-4e9c-8cca-d2a184c8acd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjE4NTMsIm5iZiI6MTcxNzA2MTU1MywicGF0aCI6Ii82MjQ2NjA5LzMzNDkyODUyNS1jZWVlNjgwMS1mZjllLTRlOWMtOGNjYS1kMmExODRjOGFjZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDkzMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdlYjBlYjUxN2UyMjc3ZTI4YTRjMWNiOGY2Y2JjZmI3MjhiODIyNzdlNmFlOWM3YzYwMjA1ZjYyN2MxMjk2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZUcMq6Tz7DXnVSl1w9-KHZ5J2UJ9F7s6rdw0dYo1dx8)

Switch between stylesheets a couple of times and it will break.

**Comment by 80avin** [comment]
Happens with me on Linux when I've installed freecad as snap.
Switching themes is breaking the dimensions of start tiles, colors are also off and no thumbnails for the example projects. 
I tried clearing up everything and reinstalling but no gains.

**Comment by JohnOCFII** [comment]
I've seen this on macOS as well.  I see this when switching between various themes (Class, light, OpenLight, etc.). Sometimes I just hit apply (and/or OK) sometimes I restart FreeCAD.  Long and short of it is I think something in the UI-related themes or overlays or something slams on top of some other settings that shouldn't be related...

```
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git)
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * OpenTheme 2024.6.22
```

<img width="710" alt="Screenshot 2024-06-30 at 5 00 30 PM" src="https://github.com/FreeCAD/FreeCAD/assets/7844212/d94dd68d-7661-4701-ba75-65d908c28488">
