### ISSUE TITLE
AddonManager: Redirects not handled properly

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#14340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

For me (for other users it appears to work), redirects are not handled properly, resulting the addon manager to block. It appears the addon manager is in an infinite loop because the items that have a redirect are not popped from the "requests" map.

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37548 +2 (Git)
Build type: DEBUG
Branch: fix-addon-manager-regression
Hash: 1399531a85809f9854c8e4d96c1dd059693b853a
Python 3.12.3, Qt 6.7.0, Coin 4.0.2, Vtk , OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenTheme 2024.5.16
  * ondsel-lens 2024.5.6.01
```

### Subproject(s) affected?

Addon Manager

### Anything else?

This issue is triggered by the conversation on the just merged PR https://github.com/FreeCAD/FreeCAD/pull/14168. I cannot reproduce the behavior that @Syres916 is reporting, but the above behavior is something I notice and it is independent of PR #14168.

Below some relevant logs. These indices get a response code of 301 or 302:
```
17:25:20  __reply_finished: 98
17:25:20  redirect: 98 PySide6.QtCore.QUrl('https://github.com/MariwanJ/Design456/raw/main/package.xml')
17:25:20  __reply_finished: 17
17:25:20  redirect: 17 PySide6.QtCore.QUrl('https://github.com/KeithSloan/OpenSCAD_Alt_Import/raw/master/package.xml')
17:25:20  __reply_finished: 47
17:25:20  redirect: 47 PySide6.QtCore.QUrl('https://github.com/Simturb/Beltrami/raw/main/package.xml')
17:25:20  __reply_finished: 95
```

These indices remain in the `requests` map, causing the addon manager to be in an infinite loop.
```
17:25:31  len(requests): 106, 13 # (requests that are not popped)
17:25:32    request: 8
17:25:32    request: 11
17:25:32    request: 14
...
17:25:32    request: 17
17:25:32    request: 47
17:25:32    request: 95
17:25:32    request: 98
...
```

I notice this behavior both on Qt 5 and Qt 6. 

The branch [`fix-addon-manager-regression`](https://github.com/Ondsel-Development/FreeCAD/tree/fix-addon-manager-regression) contains relevant debugging code.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pieterhijma** [comment]
I have more information: Running it in a virtual machine with only 1 core, I don't have the problems in the above branch. When I give it 20 cores, I have the above issue, so it seems to be a concurrency bug.

**Comment by Jookia** [comment]
Is this fixed in dev?

**Comment by pieterhijma** [comment]
@Jookia, it has! I'm curious now. What made you think it was fixed? @chennes, you seem to have done some fixes into this direction. Any idea? Can be closed from my perspective.

**Comment by Jookia** [comment]
Chennes recently pushed a fix for this :)

**Comment by chennes** [comment]
I didn't even see this bug report, I fixed it when I got the Qt6 build working on Windows and I could finally test for myself. I think it is actually a bug in Qt -- the documentation is quite clear about one particular technique for handling redirects, and that was the one I was using (since Qt5). It stopped working in Qt6, so I just used a different technique.

**Comment by pieterhijma** [comment]
Interesting, I noticed the behavior in Qt 5 as well.
