### ISSUE TITLE
Freecad YAML parsing error all - if it is in a subfolder with a special name

### ISSUE THREAD

**Issue by Superbobo75** [FreeCAD/FreeCAD#14352]
If Freecad is unpacked and started from a subfolder with a special name - e.g. in Czech "_3D tiskárny" anything in Freecad stops working after starting with a YAML parsing errors:

```
YAML parsing error: 'D:/Data/_3D tiskárny/software/Freecad Dev/data/Mod/Material/Resources/Materials/Appearance/Aluminum.FCMat'
'bad file: D:/Data/_3D tiskárny/software/Freecad Dev/data/Mod/Material/Resources/Materials/Appearance/Aluminum.FCMat'
```

If I move the Freecad folder to root, it works fine.

This happens from FreeCAD_weekly-builds-37249-conda-Windows-x86_64-py311.7z

**Comment by adrianinsaval** [comment]
@davesrocketshop

**Comment by davesrocketshop** [comment]
I'll look into it. It's possible the string handling in the Material code has an issue. That wouldn't relate to the TopoNaming issue though. That may be an unrelated but similar issue.
