### ISSUE TITLE
BIM: Problem creating stairs using guide lines

### ISSUE THREAD

**Issue by gianlucafiore** [FreeCAD/FreeCAD#14377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The steps to follow are: 
1. Create a line with the slope of the climb 
2. Select it 
3. Use the "Stairs" command and the following error appears:

![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/1acfd31d-f39c-4c69-ab42-ea94b507668a)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37543 (Git)
Build type: Release
Branch: main
Hash: 3eb45b045cdda9d5bfe11baba2567a1df90f064c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Argentina (es_AR)
Installed mods: 
  * Dracula 0.0.5
  * OpenDark 2024.3.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@yorikvanhavre FYI

**Comment by yorikvanhavre** [comment]
No problem here, doing this works with no error:

1. switch to front view
2. create a daft line with a slope
3. switch to top view
4. select the line
5. press the stairs button

If you can reproduce the error, could you paste here the contents of the python window? (ie. the commands that create the line and the stairs). Does it give the same problem when you paste those lines again in the python window?

**Comment by gianlucafiore** [comment]
![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/a7f1cec6-fc50-4095-9995-3e237d27f8bf)

![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/85631786-33cb-4cd5-b5cd-ef70e157b7f6)
It happens to me again

test file: https://drive.google.com/file/d/11YBxG2j8rRH4YZv7gNK0Y38-0bpRjdnr/view?usp=drive_link

**Comment by Roy-043** [comment]
The problem is caused by the direction of the wire. The failure occurs if the wire starts at the top of the stairs.
