### ISSUE TITLE
 [BUG] Using a loft with holes in the sketch causes the loft to have erroneous faces and any fusion of it doesn't have the loft

### ISSUE THREAD

**Issue by Monniasza** [FreeCAD/FreeCAD#14394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I can't fuse the loft properly, doing that causes the loft and the hopper top to disappear.
The loft has overlapping faces

To reproduce:
Open the included file and fuse `hoppertop`, `hopperbottom`, `entrance` and `hoppermid`

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Gridfinity 0.5.0
  * fasteners 0.5.14
  * parts_library
[/code]
```

### Subproject(s) affected?

PartDesign

### Anything else?

[pellet hopper.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15503261/pellet.hopper.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This is a user error. Please read this:
https://wiki.freecad.org/PartDesign_AdditiveLoft#Notes

Start a topic in the FreeCAD forum if you need more help.

Closing this.
