### ISSUE TITLE
Measurement: Reactivating the old Measurement Tools until the new one works correctly

### ISSUE THREAD

**Issue by nexx512** [FreeCAD/FreeCAD#14419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The new Measurement Tool has several Bugs like #14332, #14411
This makes it completely unusable for me because I heavily use it together with the assembly4 workbench that uses linked objects.
That means I have no precise function for measurements right now.
Could you please reactivate the old measurement tools until the new implementation works correctly?

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37472 (Git) Snap 1031
Build type: Release
Branch: main
Hash: d4f780782dae8d849caf30ae65885e32ff3fa635
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: German/Germany (de_DE)
Installed mods: 
  * Assembly4 0.50.12
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Known issue.

@hlorus FYI, I hope the new one is ready in about a month.
