### ISSUE TITLE
[Assemlby] : Double-clicking on an assembly should switch the workbench to the assembly workbench

### ISSUE THREAD

**Issue by luisDias89** [FreeCAD/FreeCAD#14440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

For better interaction during development, a double-click on the assembly should switch the workbench to the assembly workbench. This is my suggestion.

![image](https://github.com/FreeCAD/FreeCAD/assets/48370099/5f82c5db-2c5c-455e-97a2-a4493762edc8)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37573 (Git)
Build type: Release
Branch: main
Hash: 91aac05021023c946dc1545f2b13512ccf326550
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Portuguese/Portugal (pt_PT)
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by howie-j** [comment]
It already does, but not when the Assembly object it active in the tree view.

Steps to reproduce:
- Right click assembly, uncheck `Active object`
- Switch to another workbench
- Double click assembly, and you are back in the Assembly workbench.

Another way of going back to Assembly workbench and the assembly object is active, is to just double click twice on the assemvbly object.

**Comment by luisDias89** [comment]
@howie-j Yes, I managed to reproduce it. But I found it so unintuitive that it's better to remove the functionality. Nobody is going to be opening and closing and changing workbenches for this to work
