### ISSUE TITLE
Erreur au lancement

### ISSUE THREAD

**Issue by Pjoud30200** [FreeCAD/FreeCAD#14478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Liste des erreurs lors de l'ouverture de Freecad sans aucun fichier chargé :

17:36:21  Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: Access violation
17:36:22  Unhandled std::exception caught in GUIApplication::notify.
The error message is: invalid string position
17:36:22  Unhandled std::exception caught in GUIApplication::notify.
The error message is: invalid string position
17:36:22  Unhandled std::exception caught in GUIApplication::notify.
The error message is: invalid string position
17:36:33  Unhandled std::exception caught in GUIApplication::notify.
The error message is: invalid string position
17:36:34  Unhandled std::exception caught in GUIApplication::notify.
The error message is: invalid string position

Ma configuration : 
PC DELL Latitude E5410
Pocesseur Intel Core I3 350M
8Go DDR3 PC3 10700 (667MHz) 2x4Go

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please create issues in English.
Can you try this with the latest dev build: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
