### ISSUE TITLE
[ASSEMBLY] :  ADD LimitDistance FEATURE

### ISSUE THREAD

**Issue by luisDias89** [FreeCAD/FreeCAD#14484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Add a new feature in the workbench assembly to limit linear movement between two configurable distances
I provide one video with this feature:

https://github.com/FreeCAD/FreeCAD/assets/48370099/44129bdd-681a-45de-a0a5-9110f1af7fec

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37573 (Git)
Build type: Release
Branch: main
Hash: 91aac05021023c946dc1545f2b13512ccf326550
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Portuguese/Portugal (pt_PT)
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Limits are already implemented.
https://github.com/FreeCAD/FreeCAD/issues/12792
