### ISSUE TITLE
Inconsistent Placement of PartDesign_Boolean elements after PartDesign_MoveFeature

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#14517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Moving a PD Boolean to another Body can result in a seemingly random Placement of the elements (Bodies) of the Boolean. This is a regression that may have been introduced in #11321.

Forum topic:
https://forum.freecad.org/viewtopic.php?t=88184

File:
[Unnamed1.FCStd.zip](https://github.com/user-attachments/files/15586229/Unnamed1.FCStd.zip)

Steps:
1. Remove the zip extension and open the file.
2. Right click on Boolean in Body and "Move to other body" to Body004.
3. Works, so far so good.
4. Change the X coordinate of Body004 to 1 mm.
5. Works, so far so good.
6. For comparison: using Part_ElementCopy create copies of the top face of the box, and a cylindrical face of each of the 2 other shapes.
7. Right click on Boolean in Body004 and "Move to other body" to Body.
8. Works, so far so good.
9. Now right click on Boolean in Body and "Move to other body" to Body004 again.
10. Result: does not work properly, 2 of the Bodies in the Boolean now have an unexpected position.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37645 (Git)
Build type: Release
Branch: main
Hash: fc714933a7e2423d5fa4db640af549814061c42e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bgbsww** [comment]
I've tried the instructions above many times, reviewed the forum topic, and stared at the images.  I don't see the problem.  Is there an example that shows a changed placement value?  

Mine aren't changing at all.  I note that the forum says move it by 1mm and this doesn't.

How much is this supposed to be changing?

I assume from the description that something obvious should happen, and it isn't.

**Comment by Roy-043** [comment]
After the steps two of the copies of the faces do not match those of the Boolean, one does.

See attached [file](https://github.com/user-attachments/files/16216437/Unnamed1-after-steps.FCStd.zip) (remove the zip extension).

![Unnamed1-after-steps](https://github.com/user-attachments/assets/b00dd33b-5d29-4970-a4a4-cf143e8ca19a)

```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38127 (Git)
Build type: Release
Branch: main
Hash: 9868533d8d0ef1f569cbde538b7a31350db503bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

**Comment by bgbsww** [comment]
Well that second file certainly shows a problem, and turning off the UsePlacement switch that was added makes it go away.

But when I open the original file:
Step 2:   Works but warns " PartDesign::Body: Link(s) to object(s) 'Boolean' go out of the allowed scope 'Body'. Instead, the linked object(s) reside within 'Body004 Body004'."
Step 7:   Works, but warns "PartDesign::Body: Link(s) to object(s) 'Boolean' go out of the allowed scope 'Body004'. Instead, the linked object(s) reside within 'Body Body'."
Body position is at 0,0,0  and Body004 position is at 1,0,0
Step 9:  Still works,  same warning as Step 2.
Body position is at 0,0,0  and Body004 position is at 1,0,0

I cannot replicate this given the example and instructions above.  Can we either get a third party replicating according to the instructions above, or revised instructions?  I simply cannot see this bug happening.

**Comment by maxwxyz** [comment]
I get the same result as @Roy-043 but the same warnings as @bgbsww 
What exactly is the issue?

**Comment by bgbsww** [comment]
The same result, meaning that you actually see the offset, and not just the original object - as the second file shows?  What values do you end up with for the Position in Body and Body004 at each step?  Does it change, and if so, after precisely which action, and what's your UsePlacement value at the time?

**Comment by maxwxyz** [comment]
Starting point:
1.All positioned at 0,0,0. Use placement: true. : ![image](https://github.com/user-attachments/assets/41689931-7c16-421d-834a-fffec2518cf7)
2.All positioned at 0,0,0. Use placement: true. Warning ![image](https://github.com/user-attachments/assets/fa9e7626-6c11-496a-8edb-566601cbe6d9)

4.Body at 0,0,0. Body004 at 1,0,0. Works, no error, use placement: true

7.Body at 0,0,0. Body004 at 1,0,0. Works, same warning, use placement: true ![image](https://github.com/user-attachments/assets/5def9ab1-3f44-4fc1-b4fd-83b183a499ce)

9.Body at 0,0,0. Body004 at 1,0,0. Works, same warning, use placement: true ![image](https://github.com/user-attachments/assets/5152127f-6a61-474f-9bcb-fef32ce121aa)

@bgbsww when now changing the boolean UsePlacement to false, it is displayed at the correct location but also has a warning: 
![image](https://github.com/user-attachments/assets/d00f52e5-deb2-4ba0-ae46-a38b89dba13b)

**Comment by bgbsww** [comment]
@Roy-043 can you clarify your expectations here?  After going back and reviewing the PR and original issue, it looks like everything is working as expected:  The original issue was about whether or not to apply placement in boolean operations, and after discussion it was decided to put the original functionality behind the non-default setting of UsePlacement for legacy files.  In this example, if you switch that back to the legacy setting, you get the legacy behavior.

Whereas if you leave it on, then the placement is taken into account when you set in Body004, and the resulting move brings it along.  That isn't inconsistent, it's exactly what the user asked for.

I'm not sure I see a path forward here since I can't see the target.

@maxwxyz is this classified as a blocker because of the alleged regression?

**Comment by maxwxyz** [comment]
@bgbsww yes that was the intention, as I cannot reproduce this issue in the stable version. Let me know if I misunderstood.

**Comment by bgbsww** [comment]
21.2 tagged on Nov 13;  #11321 went in on Nov 27.  So it isn't in that release, no?  No UsePlacement in that code or available as an option [I can't test this right now, because latest ubuntu updates have broken all the old AppImages, likely due to a c++ library update].

If we don't like this approach,  #11321 can certainly be reverted and the associated bug reopened.  There is the proposal there to use ShapeBinders that I don't like, but somebody could implement it.  See conversations in the related PR, original issue, and forums.

Right now, this looks to me like it is operating as designed.

**Comment by maxwxyz** [comment]
@Roy-043 what should be done with this issue then? Does it work as designed because on the linked forums hread it was mentioned that "the use placement property does not work."?

**Comment by Roy-043** [comment]
The issue seems to have been solved somehow. A least I can't reproduce with the version listed below. I'll close this then.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```
