### ISSUE TITLE
New CAM Simulator, not possible to display only selected operations.

### ISSUE THREAD

**Issue by jkvfc** [FreeCAD/FreeCAD#14513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Regardless of which operations are selected, all operations are always displayed.
![TestPlateScreenshotOperations](https://github.com/FreeCAD/FreeCAD/assets/136894212/ad993f7f-dc40-4ae1-90ad-3279eff0af4e)

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37649 (Git)
Build type: Unknown
Branch: main
Hash: 681e8c9d2f95d4341e48cec629267182b2f7e586
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * MyScripts
```

### Subproject(s) affected?

CAM/Path

### Anything else?

[TestPlateManufacturing.zip](https://github.com/user-attachments/files/15576144/TestPlateManufacturing.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shaise** [comment]
Bug confirmed. working on it.

**Comment by shaise** [comment]
Thanks. A fix PR is pending
