### ISSUE TITLE
Feature: Add template methods `Color::asValueF()`/`Color::setValueF()`

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#14515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently the Color class has the template method asValue() to create an object with three integers. The internal floating point numbers are multiplied by 255.

It would be good to have the methods asValueF()/setValueF() to create an object directly passing the three floats. This will allow it to more conveniently convert between the SbColor and Color classes.

### Full version info

```shell
Not needed
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DeniseBryson** [comment]
I had a look and do not fully understand your idea.
Isn't the [Color::set()](https://github.com/FreeCAD/FreeCAD/blob/main/src/App/Color.cpp#L62) function already doing the same operation than the [setValue()](https://github.com/FreeCAD/FreeCAD/blob/main/src/App/Color.h#L122) function expect that Color::set() takes floats as arguments. Both functions do not create a new object but change the object from which the function is called, as far as I understand it.

If the creation of the object is the important part. We would just have to rewrite a asValueF function taking three or for floats and returning a Color object. Very similar to the asValue function as you already mentioned.

Is this correct or could you explain a little more what you had in mind I would be happy to implement it.
