### ISSUE TITLE
[Assemlby] : Algorithm for collision detection of constraints

### ISSUE THREAD

**Issue by luisDias89** [FreeCAD/FreeCAD#14528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

@PaddleStroke Continuation of the topic https://github.com/FreeCAD/FreeCAD/issues/14488

The problem is as follows: when you have an assembly of just a few parts, you can easily find which collisions occurred. Now, when the assembly has 1000 parts with potentially more than 10 joints between each of them and other parts, the software must detect that adding a joint will affect the rest, and therefore should prompt the user to make a decision.

The example I'll show in FreeCAD of what's wrong (what I did wrong, and broke the assembly):
https://github.com/FreeCAD/FreeCAD/assets/48370099/e2901bfa-4268-4bfd-bef9-6c9bb496c81e

There should be a routine that checks if adding a new Joint was breaking the previous ones, and a window would appear with the question: Is there a collision between Constraints? Do you want to add this and Suppress the broken Constraints, or cancel the addition?

Example of the behavior:
https://github.com/FreeCAD/FreeCAD/assets/48370099/feacd894-cd02-4ede-9723-9e7a62a65635

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37645 (Git)
Build type: Release
Branch: main
Hash: fc714933a7e2423d5fa4db640af549814061c42e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Portuguese/Portugal (pt_PT)
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Related to https://github.com/FreeCAD/FreeCAD/issues/12883
