### ISSUE TITLE
Edge selection not shown in CAM model

### ISSUE THREAD

**Issue by Anga23** [FreeCAD/FreeCAD#14521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I try to select multiple edges only the first one is highlighted.
You can reproduce it also if you use "CAM_SelectLoop".
This happend only in the CAM workbench on the model, in the part design workbench everything is working fine.

![image](https://github.com/FreeCAD/FreeCAD/assets/74612588/77eaa466-20a9-4137-83ad-719f19fa34b3)

### Full version info

```shell
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37573 (Git) AppImage
Build type: Release
Branch: main
Hash: 91aac05021023c946dc1545f2b13512ccf326550
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * fasteners 0.4.70
  * FeedsAndSpeeds 0.5.0
  * MakerWorkbench 1.0.1
  * sheetmetal 0.3.1

```

### Subproject(s) affected?

CAM/Path

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
Confirmed, educated guess based on feedback from Sheetmetal Wb, is that https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/CAM/Path/Op/Gui/Selection.py needs updating to be TNP output aware, this could affect quite a few addons IMHO.

**Comment by bgbsww** [comment]
Selection.py is exactly the same in LS3, and it works there.

Since the selection box clearly shows the selection is happening, this is a display issue, which I think angles towards the ViewProviders and not the python, no?  What's the feedback from Sheetmetal WB?

**Comment by Syres916** [comment]
@bgbsww the fixes that have been made to Sheetmetal Wb are https://github.com/shaise/FreeCAD_SheetMetal/commit/9b8e2cd18653c2f3017fbf66e3e183fd41db7112 and https://github.com/shaise/FreeCAD_SheetMetal/commit/b070c508bfe015eedaded13b3b25a88e66972f04
@shaise mentioned that realthunder's branch alongside FreeCAD 0.21.x and 0.22dev worked fine with Sheetmetal Wb (therefore for many months) prior to these very recent changes made to work with 0.22dev with TNP activated. To be certain I'm running a _git bisect_ and will report my findings, I'm currently down to 90 commits but sleep beckons. The CAM issue only gets triggered once a job is created for the geometry in question, it's not just activating the workbench.

**Comment by bgbsww** [comment]
Thanks!  I can chase from there.
