### ISSUE TITLE
Examples file thumbnails display old logo

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#14533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It might be worth re-saving the example files shipped in the examples folder to use the new FreeCAD logo, all in the same size.

![Captura de pantalla de 2024-06-06 13-24-18](https://github.com/FreeCAD/FreeCAD/assets/148809153/b7776530-d9f6-40ed-b02c-64ba906d9151)

As an additional consideration, I'd argue that the logo should be removed from the example files. It does not add any particular value to the examples displayed within FreeCAD, and it rather obscures the thumbnail. But others might not agree, so it might be better to discuss it separately.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37578 +9 (Git)
Build type: Unknown
Branch: Draft_Grid_Observer_clean
Hash: 01b2b370e9b7538eb20ab07dd20ff036e36f51e5
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Installed mods: 
  * OpenTheme 2024.5.3
  * parts_library
```

### Subproject(s) affected?

File formats

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I'd propose to get rid of the thumbnail icon file, because at least on windows it is rendered on top of the image in the file explorer so it's twice there.

**Comment by pierreporte** [comment]
I’m in favor of removing the icon from the preview. However, I think that an indication of the file type is still useful. The screenshot shows a step file in the tree. If a preview is eventually implemented (same for STLs and other formats), some sort of marker could help distinguish file types. It could be an icon in the label.

**Comment by furgo16** [comment]
Related forum thread: https://forum.freecad.org/viewtopic.php?t=81005

**Comment by luzpaz** [comment]
Should this be in 1.0 ?

**Comment by maxwxyz** [comment]
If possible, the logo integration in the thumbnail would be removed.

**Comment by luzpaz** [comment]
Hot take: this should be a UI blocker because it is a the first thing a user sees when firing up FreeCAD. So we either add the new logo or remove the logo as an overlay for the thumbnail.

**Comment by maxwxyz** [comment]
My proposal is disable the icon implementation by default (can be enabled in the preferences) and save all example files without the embedded logo (as on Windows it's rendered on top and then appears twice).
