### ISSUE TITLE
Update file thumbnail logo to new FreeCAD logo

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#14532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently saving a document with option "Preferences > General > Document > Add the program logo to the generated thumbnail" adds the old FreeCAD logo, where it should be adding the new FreeCAD logo instead.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37578 +9 (Git)
Build type: Unknown
Branch: Draft_Grid_Observer_clean
Hash: 01b2b370e9b7538eb20ab07dd20ff036e36f51e5
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Installed mods: 
  * OpenTheme 2024.5.3
  * parts_library
```

### Subproject(s) affected?

File formats

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This has already been fixed.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37645 (Git)
Build type: Release
Branch: main
Hash: fc714933a7e2423d5fa4db640af549814061c42e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

**Comment by furgo16** [comment]
Indeed it has, I was looking at an older build, apologies.

![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/280e312c-1f2b-49a9-af3b-4c72c6dd9adc)
