### ISSUE TITLE
add on assembly joint fixesd, rotate and mover all axis

### ISSUE THREAD

**Issue by Vincenzoferrara** [FreeCAD/FreeCAD#14552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

 I described the problem here #14546

but since I didn't specify assembly they closed it, and they gave me back the bin for the bim workbench.

I would like to add that maybe it would be useful when you report a bug a field to insert the workbench

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37573 (Git) AppImage
Build type: Release
Branch: main
Hash: 91aac05021023c946dc1545f2b13512ccf326550
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT) [ OS: Italian/Italy (it_IT) ]
Installed mods: 
  * AutoOpenSpreadsheet
  * ProDarkThemePreferencePack 1.0.0
  * CommandPanel
  * IconThemes
  * fasteners.backup1715436808.37841 0.5.16 (Disabled)
  * FeedsAndSpeeds 0.5.0
  * ExplodedAssembly
  * OpenTheme 2024.5.16
  * Freecad-Built-in-themes-beta 1.2.2
  * fasteners 0.5.21
  * TabBar
  * Assembly4 0.50.12
  * CubeMenu
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
You can specify the subprojct in the issue template.
What you are trying to achieve is the placement tool or the move tool from draft. Assembly has not such a feature.
