### ISSUE TITLE
[Problem] The new Align to selection view tool doesn't work properly in the Integrated Assembly WB

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#14576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Checking the new align to selection view tool I have realized that it has a weird behaviour in an assembly situation. See videos and files attached. 

I think that it orients the view as the original position, before the assembly and/or before the assembled movement of the parts. 

In video GH_Align_2 you can see that sometimes even flips the view like front to rear. In that video I haven't moved the grounded part (blueish) so the tool works well on that part. 

On the other hand, a Macro I have been using for the same purpose (that includes the fit to selection (V,S) that in my opinion is very useful) works correctly in the assembly situations. I attach the macro too, if it helps.

**Note**: Although video 1 and 2 look very similar, they are different assemblies of same parts.

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37668 (Git) AppImage
Build type: Release
Branch: main
Hash: ea68c5e88cdc80044ede482f6ad908820f4c1c82
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * Movie 2024.2.15
  * FreeCAD-motion-workbench-master
  * dodo 1.0.1
  * PieMenu 1.2.7
  * fasteners 0.5.22
```

### Subproject(s) affected?

Assembly

### Anything else?

[Align to selection test Github.FCStd.zip](https://github.com/user-attachments/files/15754375/Align.to.selection.test.Github.FCStd.zip)

https://github.com/FreeCAD/FreeCAD/assets/18265355/b32518d9-f590-46dd-aa1f-7c5807d01e72

https://github.com/FreeCAD/FreeCAD/assets/18265355/65a08206-a948-49de-8d00-32c5acc4fac9

[Align to selection test Github_2.FCStd.zip](https://github.com/user-attachments/files/15754394/Align.to.selection.test.Github_2.FCStd.zip)

[Normal_View.FCMacro.zip](https://github.com/user-attachments/files/15754408/Normal_View.FCMacro.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
I think this is because the align to tool is using the placement of the object and not its global placement.
