### ISSUE TITLE
Measurements of sketches don't save

### ISSUE THREAD

**Issue by Jookia** [FreeCAD/FreeCAD#14593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Create a cube
2. Create a sketch
3. Import the geometry of the cube
4. Create a rectangle based on the geometry
5. Exit sketcher moder
6. Measure the length of a sketch edge
7. It will look correct:

![An edge on a wireframe showing 10mm](https://github.com/FreeCAD/FreeCAD/assets/185275/fd3da976-2a83-49b5-b967-96acbe422130)

8. Save and load the file again
9. The measurement is broken

![The measurement of the edge is gone, measuring 0mm](https://github.com/FreeCAD/FreeCAD/assets/185275/5c88f6da-9c5d-4c5c-9749-8201e0650bfe)

Changing the measurement's linked object to the sketch before saving seems to cause it to save and load fine, despite having an identical name.

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37669 (Git)
Build type: Release
Branch: main
Hash: 3b4598ce04d7aaec69feeb560c29ae18f0236e0c
Python 3.12.3, Qt 6.7.1, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.67
  * Help 1.0.3
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@hlorus FYI

**Comment by maxwxyz** [comment]
@hlorus In the latest weekly I cannot measure sketches at all, the distance and length of simple sides of a rectangle is always 0
