### ISSUE TITLE
assembly Do not remove connected joints when deleting a component

### ISSUE THREAD

**Issue by Vincenzoferrara** [FreeCAD/FreeCAD#14597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

when i remove a component from an assembly it should also remove its joints, but i get the warning

![freecad_assembly_error](https://github.com/FreeCAD/FreeCAD/assets/64591523/27ca5678-1061-4715-a8ef-474e3dc904e7)

it should ask if you want to remove the joints

I use the Italian language

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37668 (Git) AppImage
Build type: Release
Branch: main
Hash: ea68c5e88cdc80044ede482f6ad908820f4c1c82
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT) [ OS: Italian/Italy (it_IT) ]
Installed mods: 
  * AutoOpenSpreadsheet
  * ProDarkThemePreferencePack 1.0.0
  * CommandPanel
  * IconThemes
  * fasteners.backup1715436808.37841 0.5.16 (Disabled)
  * FeedsAndSpeeds 0.5.0
  * ExplodedAssembly
  * OpenTheme 2024.5.16
  * Freecad-Built-in-themes-beta 1.2.2
  * fasteners 0.5.21
  * TabBar
  * Assembly4 0.50.12
  * CubeMenu
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
This is a reasonable request.

**Comment by PaddleStroke** [comment]
The error message is a general message due to the links. Here it is in english : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/5fac260c-7e82-470a-8c6f-f88bbbeb0b7e)

I'm actually not sure how to solve this problem.
@wwmayer could you please weight in? Is it possible to trigger deletion of the related joints when a component is deleted ? I'm not sure how to handle this.

**Comment by wwmayer** [comment]
It's up to your view provider class to override the method `canDelete`. If it handles the deletion it must return true.

**Comment by PaddleStroke** [comment]
Thanks @wwmayer ! It works to delete the joints as same time as components by implementing `ViewProviderAssembly::canDelete`

However I still have the 'Object dependency' warning box that appears before attempting the deletion. Is there a way to prevent this message ?

**Comment by wwmayer** [comment]
If you look at the code then the dialog pops up if canDelete() returns false. Which view provider class is called there?
