### ISSUE TITLE
Light source position sub-window is displayed quite small

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#14617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the Edit > Preferences > Display menu, adjusting the position / direction of the light source can be challenging (in small screens) because the subwindow is smaller than it could be. It almost doesn't use any of the available space below. 

Attached images taken with a 15'' screen (laptop). Looks like the vertical growth of the subwindow is not proporcional to the growth of the Preferences window (see video). Screen captures and screencast taken with FreeCAD in full screen.

Is in some way related to #13591 as this issue won't be as relevant as the light adjustment hasn't to be done hand moving the ball and the stick.

I have searched in Github with keywords [is:issue is:open light source display] with no more relevant results.

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37669 (Git) AppImage
Build type: Release
Branch: main
Hash: 3b4598ce04d7aaec69feeb560c29ae18f0236e0c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * Movie 2024.2.15
  * FreeCAD-motion-workbench-master
  * dodo 1.0.1
  * PieMenu 1.2.7
  * fasteners 0.5.22
```

### Subproject(s) affected?

None

### Anything else?

![Captura de pantalla_2024-06-11_18-22-56](https://github.com/FreeCAD/FreeCAD/assets/18265355/fa217cea-270a-4e8a-a956-92a4fa56fbe5)

![Captura de pantalla_2024-06-11_18-23-24](https://github.com/FreeCAD/FreeCAD/assets/18265355/bc72700a-6834-497e-9522-7924c5e741a7)

https://github.com/FreeCAD/FreeCAD/assets/18265355/2986f1fe-3933-44a0-97f4-19269d3b09c4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I cannot reproduce on Windows.
@kadet1090 FYI

**Comment by benj5378** [comment]
@MiqCG, is this still an issue on the newest version?

**Comment by MiqCG** [comment]
No, it is rendering big and nice in my 15" laptop screen with 1.0.0RC2.38806 .
Thanks for the reminder. I will close this issue.


![Captura de pantalla_2024-10-08_12-27-48](https://github.com/user-attachments/assets/98241c8b-2a04-4581-9cb9-c1e3a5295d9f)
