### ISSUE TITLE
New CAM Simulator, ToolBit Shapes not displayed properly

### ISSUE THREAD

**Issue by jkvfc** [FreeCAD/FreeCAD#14613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The picture below shows the tool paths for tapping and slitting. The toolbit for tapping is self-generated and that for slitting is FreeCAD's default slitting saw.

![TestToolsPaths](https://github.com/FreeCAD/FreeCAD/assets/136894212/db8a9b34-4610-4a70-8560-480e5f523728)

With the **old simulator** the toolbit shape for the tapping tool is **ok**.

![TestToolsPathsTappingOldSimulator](https://github.com/FreeCAD/FreeCAD/assets/136894212/98d4fc5f-5fbb-4785-813c-9930af5a76bf)

With the **new simulator** the shape is **wrong**.

![TestToolsPathsTappingNewSimulator](https://github.com/FreeCAD/FreeCAD/assets/136894212/72eebfa1-3825-4ebe-8070-ffc58b169e2e)

With the **old simulator** the toolbit shape for the slitting saw is **ok**. But the **reference point** is **wrong**. It should be on the underside of the saw blade.

![TestToolsPathsSawSlittingOldSimulator](https://github.com/FreeCAD/FreeCAD/assets/136894212/4be02a99-f322-4226-a9ec-17343a0b717f)

With the **new simulator** the output for the slitting operation fails. The error message below is displayed. 
 
![ErrorMessage](https://github.com/FreeCAD/FreeCAD/assets/136894212/e4daed4b-7d91-4eac-b72a-c710b083d09c)

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37649 (Git)
Build type: Unknown
Branch: main
Hash: 681e8c9d2f95d4341e48cec629267182b2f7e586
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * MyScripts
```

### Subproject(s) affected?

CAM/Path

### Anything else?

[TestToolsTappingSlitting.zip](https://github.com/user-attachments/files/15787216/TestToolsTappingSlitting.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@shaise FYI

**Comment by shaise** [comment]
Thank you.
Taking a look.

**Comment by jkvfc** [comment]
@shaise,
fix successfully tested, thank you very much for the quick solution.
