### ISSUE TITLE
`pythonopen` does not become defined because of unexpected value of `open.__module__`

### ISSUE THREAD

**Issue by Mikael-Lovqvist** [FreeCAD/FreeCAD#14620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using for instance `importSVG.py` an exception happens because `pythonopen` is not defined.

The problem code is
```python
# Save the native open function to avoid collisions
if open.__module__ in ['__builtin__', 'io']:
    pythonopen = open
```
In `Python 3.12.3` (and possibly other python versions) `open.__module__` is `_io`.
I do not really know why it is done this way so I'll provide two options for workarounds.

Specifically import open from builtins
```python
from builtins import open as pythonopen
```

Conditionally define `pythonopen` if not already defined
```python
if 'pythonopen' not in vars():
    pythonopen = open
```

### Full version info

```shell
[code]
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.12.3, Qt 6.7.0, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * ThreadProfile 1.89.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This has already been fixed. See #13337.
