### ISSUE TITLE
Comparison between integers and StandardButton fails for Python task dialogs with PySide6

### ISSUE THREAD

**Issue by marioalexis84** [FreeCAD/FreeCAD#14639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With PySide6, comparison between integers and StandardButton fails for Python task dialogs.
For example, in the Gmsh task panel, to make the button ` Apply` works again, I need to change:
```
 def clicked(self, button):
 if button == QtGui.QDialogButtonBox.Apply:
 ...
```
to:
```
 def clicked(self, button):
 if button == QtGui.QDialogButtonBox.Apply.value:
 ```

@wwmayer, maybe some relation with https://github.com/FreeCAD/FreeCAD/pull/13902? 

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37710 (Git)
Build type: Unknown
Branch: (HEAD detached at a6937d8d26)
Hash: a6937d8d2677594f548af218cc92f797d9a475d9
Python 3.12.3, Qt 6.7.1, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.5.17
  * OpenTheme 2024.4.20
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
It seems to be a problem for newer PySide versions. With my Qt 6.2.4 and corresponding PySide version it works without problems.
`if button == QtGui.QDialogButtonBox.Apply.value:`
The `value` attribute doesn't exist for older PySide versions. To make it working for all PySide versions you should try:
```
def clicked(self, button):
    if button == int(QtGui.QDialogButtonBox.Apply):
```

**Comment by marioalexis84** [comment]
it does not work:
`<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'StandardButton'`

**Comment by wwmayer** [comment]
OK, then the alternative is to modify `TaskDialogPython::clicked(int i)` where the int should be converted into a QtGui.QDialogButtonBox.StandardButton and passed to the clicked() method of the Python wrapper.

Does this code snippet work for you?
```
from PySide import QtGui
QtGui.QDialogButtonBox.StandardButton(33554432)
```

**Comment by marioalexis84** [comment]
The code snippet works.

With:
```
    def clicked(self, button):
        b=QtGui.QDialogButtonBox.StandardButton(button)
        if b == QtGui.QDialogButtonBox.Apply:
```
the button works normally.

**Comment by wwmayer** [comment]
OK, I will prepare a PR to handle this and https://github.com/FreeCAD/FreeCAD/issues/14156

**Comment by marioalexis84** [comment]
With https://github.com/FreeCAD/FreeCAD/issues/14156#issuecomment-2124518817 buttons are not even added and there is an error generated when executing `Gui.Control.showDialog`.
```
<input>(1)<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'StandardButton'
```
![image](https://github.com/FreeCAD/FreeCAD/assets/53127171/441c4e67-5df4-4fac-810d-4416916038f2)

**Comment by wwmayer** [comment]
Thanks for testing. Yes, according to the docs PyNumber_Long in C is equal to int() in Python and will fail in your case. So, I have to additionally check if the passed object has the attribute `value` and do the cast on that.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/14648
