### ISSUE TITLE
 "Crop To Width" and "Crop To Height" should be disabled if "Crop Image" is not checked

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#14641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using the [TechDraw_ActiveView](https://wiki.freecad.org/TechDraw_ActiveView) command from the TechDraw workbench, the  "Crop To Width" and "Crop To Height" input boxes in the Tasks panel dialog are always enabled. They should only be enabled if the "Crop Image" checkbox is checked.

![Captura de pantalla de 2024-06-12 13-44-22](https://github.com/FreeCAD/FreeCAD/assets/148809153/938373dd-551c-4850-bbe9-96d0ebed8e1e)

Forum discussion: https://forum.freecad.org/viewtopic.php?t=88393

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37710 (Git)
Build type: Release
Branch: main
Hash: a6937d8d2677594f548af218cc92f797d9a475d9
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
should be fixed by #14666.
