### ISSUE TITLE
Insert View results in: “OCC error - GC_MakeCircle::Value() - no result - while making spline”

### ISSUE THREAD

**Issue by mpfusion** [FreeCAD/FreeCAD#14677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When clicking “Insert View” I get the following error message:

````
10:50:00  Geom::baseFactory - OCC error - GC_MakeCircle::Value() - no result - while making spline
10:50:00  Geom::baseFactory - OCC error - GC_MakeCircle::Value() - no result - while making spline
````
![no-result](https://github.com/FreeCAD/FreeCAD/assets/698973/05894dcd-eb4f-48df-bfa9-8e2ee71e8dbf)

To reproduce:

- open attached file
- open TD workbench
- insert Default Page
- select sketch
- click “Insert View”
→ error

[td-no-result-while-making-spline.tar.gz](https://github.com/user-attachments/files/15835808/td-no-result-while-making-spline.tar.gz)

https://forum.freecad.org/viewtopic.php?t=88439

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37709 (Git)
Build type: Release
Branch: main
Hash: dd816a635ccacc39f29b1761c6ccfed21a90b646
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/Ireland (en_IE)
Installed mods: 
  * BOLTSFC
  * kicadStepUpMod 11.1.8
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I get no error on Windows but the view is empty:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/997913d0-1952-44ca-a42f-1692db584dc2)

**Comment by WandererFan** [comment]
The spurious error messages are fixed:  https://forum.freecad.org/viewtopic.php?p=765933#p765933.

The no result seems to be from using the Body as the source instead of the Sketch.  Apparently if the body has no Tip, it's shape is empty, even though there is a non-null object in the body (the sketch).
