### ISSUE TITLE
Windows configuration and compiling is very difficult or straight up impossible

### ISSUE THREAD

**Issue by YosypC** [FreeCAD/FreeCAD#14689]
### Problem description

[FREECAD_LIBPACK_USE unchecks everytime I configure](https://forum.freecad.org/viewtopic.php?t=88453)
[Can't configure on Windows](https://forum.freecad.org/viewtopic.php?t=88454)

Selecting any available preset on CMake GUI makes the FREECAD_LIBPACK_USE always unchecked after every configuration.
Also some directories seem not to be syncronized correctly for the libpack.
For instance, it can't find the Qt5 not Qt6 dirs, nor SMESH (is this even necessary?). Overall the compiling experience seems to be tailored to Linux users with little out of the box functionality for Windows users, and Wiki is so straighforward that doesn't account for any of these problems.

Another instance:

```
CMake Error at cMake/FindOCC.cmake:101 (file):
  file STRINGS file
  "C:/Users/Yosyp/Documents/Git/FreeCAD/FreeCAD/.conda/freecad/Library/include/opencascade/Standard_Version.hxx"
  cannot be read.
Call Stack (most recent call first):
  cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
  CMakeLists.txt:64 (SetupOpenCasCade)
```

(I've found the file "Standard_Version.hxx" in "..\LibPack-0.21-V2.11\inc" rather than the default directory, but I am unsure if it's correct. After manually pointing it, the configuration proceeds.) Back to the same error trail:

```
CMake Error at cMake/FindOCC.cmake:104 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
  CMakeLists.txt:64 (SetupOpenCasCade)


CMake Error at cMake/FindOCC.cmake:105 (file):
  file STRINGS file
  "C:/Users/Yosyp/Documents/Git/FreeCAD/FreeCAD/.conda/freecad/Library/include/opencascade/Standard_Version.hxx"
  cannot be read.
Call Stack (most recent call first):
  cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
  CMakeLists.txt:64 (SetupOpenCasCade)


CMake Error at cMake/FindOCC.cmake:108 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
  CMakeLists.txt:64 (SetupOpenCasCade)


CMake Error at cMake/FindOCC.cmake:109 (file):
  file STRINGS file
  "C:/Users/Yosyp/Documents/Git/FreeCAD/FreeCAD/.conda/freecad/Library/include/opencascade/Standard_Version.hxx"
  cannot be read.
Call Stack (most recent call first):
  cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
  CMakeLists.txt:64 (SetupOpenCasCade)


CMake Error at cMake/FindOCC.cmake:112 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
  CMakeLists.txt:64 (SetupOpenCasCade)
```

This is for SMESH:

```
CMake Error at cMake/FindSMESH.cmake:49 (message):
  SMESH include directories not found!
Call Stack (most recent call first):
  cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake:127 (find_package)
  CMakeLists.txt:71 (SetupSalomeSMESH)
```

Even after correctly generating, after the compilation I get thousend of errors and plenty of warnings. I have no idea how to diagnose the issue, as I have no knowledge on CMake and I am still studying the inner workings of FreeCAD (again, never heard of SMESH, for example).
Compiling on Linux will always be faster, more straightforward (as much as I've had issues on Mint), and less problematic, but I had to come back to Windows for many reasons.

### Anything else?

Open discussion: [Why choosing Visual Studio for a compiler on Windows?](https://forum.freecad.org/viewtopic.php?t=88464)

edit: this is my second time failing compilation after my previous, still failed, attempts last year before I ditched Windows in favour of Mint.

**Comment by maxwxyz** [comment]
Closing this in favor of https://github.com/FreeCAD/FreeCAD/issues/13460
