### ISSUE TITLE
new icon for sketch

### ISSUE THREAD

**Issue by Vincenzoferrara** [FreeCAD/FreeCAD#14703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

information on the current as it is on [https://wiki.freecad.org/Tree_view](url)
these images are taken from google, only for demonstration purposes

I would like to propose new icons in the Treeview for sketch:
-when the sketch is fully constrained, 
![icona ceck riuscita](https://github.com/FreeCAD/FreeCAD/assets/64591523/622aa6ed-d634-41d3-83dc-d05fc74bdff0)

-error 
![error icon](https://github.com/FreeCAD/FreeCAD/assets/64591523/eb5bc4c3-3bba-4359-a655-54f8fbb573d0)

-reload
![reload](https://github.com/FreeCAD/FreeCAD/assets/64591523/2b2b5a20-07e1-4237-9b05-f48d6300a618)

-error reload
![reload error](https://github.com/FreeCAD/FreeCAD/assets/64591523/7ad626d4-fb36-44f0-be57-e0cc01843b76)

### Full version info

```shell
beta version
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
There is no concise problem described in the issue.
