### ISSUE TITLE
Hard to add geometry in create sub-object(s) shape binder

### ISSUE THREAD

**Issue by nazar-pc** [FreeCAD/FreeCAD#14705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using "Create sub-object(s) shape binder" there are multiple usability issues:
* when geometry from non-selected object is clicked nothing happens (I'd expect notification of some sort saying it doesn't belong to selected object)
* adding/removing geometry from selected object is very confusing/inconvenient
    * it is not possible to select multiple external geometries and click "Add Geometry" to add them all at once, in fact nothing happens when I do this, it expects me to click exactly one external geometry after this, from this mode there is no "exit"
    * it is not possible to click "Add Geometry" and select multiple geometries, button needs to be clicked again after every single selection to add one more
    * there is a list of geometries, but they are just names, there is no highlighting to see which one is where
    * selecting geometries in the list and clicking "Remove Geometry" does nothing, it expects to click exactly one external geometry on the screen to remove it just like with addition

All of this makes it very tedious, time-consuming and frustrating to use this tool.

### Full version info

```shell
OS: Ubuntu 24.04 LTS (Custom/custom)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37709 (Git) AppImage
Build type: Release
Branch: main
Hash: dd816a635ccacc39f29b1761c6ccfed21a90b646
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I'm closing this in favor of https://github.com/FreeCAD/FreeCAD/issues/13044
