### ISSUE TITLE
Problem with partialy selected sketch

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD#14711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

How to reproduce
1. Select external outline of Sketch001.
![Знімок екрана з 2024-06-16 09-57-25](https://github.com/FreeCAD/FreeCAD/assets/1382812/69255529-b254-42ab-b659-bae32ff2740b)
2. Make Pad
3. Save and exit. No error shown in tree
4. Open file again.
5. Now it shown error
![Знімок екрана з 2024-06-16 09-58-16](https://github.com/FreeCAD/FreeCAD/assets/1382812/13812a29-f47d-413a-bcbc-d883c832fa2d)
[test.FCStd.gz](https://github.com/user-attachments/files/15857341/test.FCStd.gz)

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 (Git)
Build type: Debug
Branch: master
Hash: 30f7f2688921e6e5242beaa9d71e0fdd844b20e3
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1.dev
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 
  * sheetmetal 0.4.18
  * fasteners 0.5.22
  * OpenTheme 2024.5.16
  * Assembly3 0.12.2
  * addFC 0.3.1
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Ideally you use one profile to extrude in a sketch, not several connected closed loops.
@bgbsww could this be TNP related or just a bad sketch?

**Comment by maxwxyz** [comment]
The error is the same as in https://github.com/FreeCAD/FreeCAD/issues/14602

**Comment by Kuzma30** [comment]
Its not external geometry

**Comment by Kuzma30** [comment]
May be will be useful.
Original sketch has 3 connected line.
![Знімок екрана з 2024-06-17 18-04-21](https://github.com/FreeCAD/FreeCAD/assets/1382812/df669fa2-f0b5-4be6-95d3-384f5217fa2b)

When apply Pad command this lines converted to one

![Знімок екрана з 2024-06-17 18-05-39](https://github.com/FreeCAD/FreeCAD/assets/1382812/56aa611f-463a-4eef-a10e-31c482d37eaf)

**Comment by bgbsww** [comment]
This could be related to the TNP changes to cleanup Wire creation that @CalligaroV was working on, which would make it tangentially related.  However, I'm at a loss as to what the padded behavior of such a sketch would be other than undefined, and thus not really a bug to address.

Maybe there is an expected behavior here that I don't understand?  Squashing that outer wire makes sense to me, and then at that point any cleanup/fix operation is liable to wipe out the insides.  I don't know where that's happening, though.

**Comment by Kuzma30** [comment]
The goal was to create the following detail from the master sketch
![Знімок екрана з 2024-06-17 19-16-24](https://github.com/FreeCAD/FreeCAD/assets/1382812/bf1f1432-f7a2-401e-8520-49847b4f08fe)

**Comment by bgbsww** [comment]
@maxwxyz  this isn't a Topic: Toponaming.  It's a bad sketch.  It's interesting from a TNP perspective, but there's nothing to do.

**Comment by maxwxyz** [comment]
ok I'll close then

**Comment by Kuzma30** [comment]
> @maxwxyz this isn't a Topic: Toponaming. It's a bad sketch. It's interesting from a TNP perspective, but there's nothing to do.

What is a "good" sketch for https://github.com/FreeCAD/FreeCAD/issues/14711#issuecomment-2174243583?
