### ISSUE TITLE
[Problem] "Measure" tool icon doesn't update on changing from old "Measure distance" tool

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#14734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Part Design, if you select the (old) "Measure distance" tool and then (you change your mind and) select the new "Measure" tool, the task panel activates for the new "Measure" tool but the 3D View icon remains of the old "Measure distance" tool.
See screencast.

I have searched in Github FreeCAD [is:issue measure icon ]

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 (Git) AppImage
Build type: Release
Branch: main
Hash: 30f7f2688921e6e5242beaa9d71e0fdd844b20e3
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * Movie 2024.2.15
  * FreeCAD-motion-workbench-master
  * dodo 1.0.1
  * PieMenu 1.2.7
  * BillOfMaterials 0.0.8.5
  * fasteners 0.5.22
```

### Subproject(s) affected?

PartDesign

### Anything else?

https://github.com/FreeCAD/FreeCAD/assets/18265355/5478b5b0-69b9-41dc-902b-7de597426830

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Old measure tool is now removed. Will be in tomorrows weekly.
