### ISSUE TITLE
Checkbox state not visible in new Dark/Light themes

### ISSUE THREAD

**Issue by dapetcu21** [FreeCAD/FreeCAD#14747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Using the Dark/Light themes in the weekly build (on macOS ARM64), the checkbox visuals look the same for both the checked and unchecked states, so it's impossible to tell if a checkbox is checked or not.

Additionally, there are a few non-critical issues with the theme that make it awkward to visually parse (see the notes in the below screenshot).

<img width="1440" alt="Screenshot 2024-06-17 at 21 59 11" src="https://github.com/FreeCAD/FreeCAD/assets/428060/7cd17b3c-32a3-4eb9-8928-87376302cd0e">

### Full version info

```shell
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 (Git)
Build type: Release
Branch: main
Hash: 30f7f2688921e6e5242beaa9d71e0fdd844b20e3
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@MisterMakerNL FYI

**Comment by MisterMakerNL** [comment]
Yeah, it's not only the state it are all images! Maybe we can rebuild the weekly, so this isn't going to be posted a gazzilion times? :)

**Comment by maxwxyz** [comment]
@dapetcu21 is this still an issue for you?

**Comment by dapetcu21** [comment]
Hi! The icons and checkboxes are indeed fixed in the latest nightly. All the other minor issues I pointed out in the above screenshot are still present.

**Comment by MisterMakerNL** [comment]
> Hi! The icons and checkboxes are indeed fixed in the latest nightly. All the other minor issues I pointed out in the above screenshot are still present.

What? really? I though most of them where caused by missing images. Could you post a new screenshot?

**Comment by dapetcu21** [comment]
<img width="1440" alt="Screenshot 2024-07-01 at 21 03 29" src="https://github.com/FreeCAD/FreeCAD/assets/428060/f83fe489-1356-40de-8837-74423e8e9d64">

**Comment by MisterMakerNL** [comment]
You DPI settings seem to cram everything together. How does it look with no-stylesheet?

**Comment by dapetcu21** [comment]
These are the default DPI settings on a 13" macbook air. I assume that by no-stylesheet you mean the "Classic" theme:

(Also something I forgot to add, in the dark theme screenshot, setting rows that have a checkbox are not aligned with the labels of the other entries in the settings menu)

<img width="1440" alt="Screenshot 2024-07-01 at 21 34 34" src="https://github.com/FreeCAD/FreeCAD/assets/428060/211a7b19-5e4a-4bdb-ac1a-06d2cc6b15cc">

**Comment by dapetcu21** [comment]
Would you prefer I make separate issues for each one of these?

**Comment by maxwxyz** [comment]
If they still exist and have no issue, yes please.

**Comment by MisterMakerNL** [comment]
It could use some improvements, but there are currently bigger fish to fry than optimization for a 13" screen!

**Comment by dapetcu21** [comment]
Fair enough. I just plugged in a 4k screen. The scrollbar in settings issue did actually resolve itself. I'll close this and open separate issues for everything that's left.
