### ISSUE TITLE
Extruding one circle instead of two

### ISSUE THREAD

**Issue by kotovasia5120** [FreeCAD/FreeCAD#14800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I select two circles and want to extrude them at the same time, but in the end only one is extruded.
If you squeeze out one at a time there are no problems.

1.Adopt the form
2. Select circles
3. extrude

Also encountered when extruding from sketches.

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 (Git)
Build type: Release
Branch: main
Hash: 30f7f2688921e6e5242beaa9d71e0fdd844b20e3
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Installed mods: 
  * 3DfindIT 1.2.0
  * CurvedShapes 1.0.9
  * Curves 0.6.39
  * fasteners 0.5.22
  * Help 1.0.3
  * LCInterlocking
```

### Subproject(s) affected?

PartDesign

### Anything else?

![Снимок экрана 2024-06-19 195055](https://github.com/FreeCAD/FreeCAD/assets/76496357/a18f724a-0733-49c1-97e4-5103bd561ce3)

![Снимок экрана 2024-06-19 195039](https://github.com/FreeCAD/FreeCAD/assets/76496357/29468ada-7a7a-4520-82c5-90cb48db5e99)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kotovasia5120** [comment]
I came to the conclusion that this is due to the fact that in partdesing it is impossible to create 2 objects not connected by a body

**Comment by kotovasia5120** [comment]
I came to the conclusion that this is due to the fact that in partdesing it is impossible to create 2 objects not connected by a body

**Comment by MiqCG** [comment]
@kotovasia5120 , have you tried to enable the option for multiple olids in Part design?

Edit menu > Preferences > Part/Part design > Experimental 

![Captura de pantalla_2024-06-19_22-26-36](https://github.com/FreeCAD/FreeCAD/assets/18265355/485c9938-b72c-44c5-b8f7-8f0b63f6e4fd)

**Comment by kotovasia5120** [comment]
> have you tried to enable the option for multiple olids in Part design?

I tried it, it doesn't help with this operation.
