### ISSUE TITLE
Part editing instant side panel (great quality of life)

### ISSUE THREAD

**Issue by MRiabov** [FreeCAD/FreeCAD#14811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I expect that sketch workflow should be triggered through the part editor window - directly at where we create the part 90% of the time.
Right now, when I want to edit a sketch I have to look it up in the tree view. And when I have three dozens of features in my part, tracking a sketch for each is simply wasteful and overly difficult
![image](https://github.com/FreeCAD/FreeCAD/assets/108194191/a079b6a3-4487-4cf9-8c7a-30e32d85233a)

### Full version info

```shell
OS: Windows 11 build 22000
Word size of Ondsel: 64-bit
Version: 2024.2.1.37226 (Git)
Build type: Release
Branch: (HEAD detached at 2024.2.1)
Hash: 1a1bd7290494aef925a026c87b808ac58d53c3b0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * A2plus 0.4.65
  * ModernUI (Disabled)
  * Ondsel-Lens 2024.5.6.01
```

### Subproject(s) affected?

PartDesign

### Anything else?

![image](https://github.com/FreeCAD/FreeCAD/assets/108194191/c7166b7e-3cd4-4b61-994d-08921f3308e6)
Here's how good software allows to edit features: I don't have to remember the tree connection, or remember the feature names, or remember the sketches; just create, modify sketches, and modify parts near-instantly!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Duplicate issue
