### ISSUE TITLE
Start: "Don't show start page" option should be relocated or removed and put into preferences

### ISSUE THREAD

**Issue by kinghat** [FreeCAD/FreeCAD#14817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

the "dont show start page" option needs to be moved or removed and put into preferences.

![image](https://github.com/FreeCAD/FreeCAD/assets/16073360/bed5183a-425c-4bec-8181-db9d5a45487b)

in the image you could move it to the bottom left or right.

i think it could be removed all together because its like the loading image preference. you either want the start page or you dont. having it at the top where it is currently is essentially asking for interaction. if you want to keep the start page then you keep seeing this option.

a list of options from best to worst imo:
- remove this option from the start page and put it in preferences and continue to default to show the start page.
- move it to the bottom right or left.
- leave as is.

### Full version info

```shell
OS: Fedora Linux 40 (KDE Plasma) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37819 (Git) AppImage
Build type: Release
Branch: main
Hash: 2ca9b6ef8036d5fd808f01205b66eb0424059e21
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenTheme 2024.5.16
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
@chrisb-github Could this small change still be made? This option should indeed be moved (possibly to the Preferences) if such changes are still possible while improving the Start page for 1.0.
