### ISSUE TITLE
BIM Box is always built in the -Z direction

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#14823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The box object is always constructed downwards from the working plane (-Z). Even if a positive direction was given.
Video demonstration.

https://github.com/FreeCAD/FreeCAD/assets/32273833/31fd9068-6b83-4f7d-ac67-00861442bb5f

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37819 (Git) AppImage
Build type: Release
Branch: main
Hash: 2ca9b6ef8036d5fd808f01205b66eb0424059e21
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Installed mods: 
  * OpenTheme 2024.5.16
  * PitchedRoof
```

### Subproject(s) affected?

BIM/Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Indeed there is something wrong with the placement (it's rotated 180˚)
The problem seems to be from `WorkingPlane.getPlacementFromPoints([p1, p2, p3])` at https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/BIM/bimcommands/BimBox.py#L187
