### ISSUE TITLE
Draft: Strange behavior of the Trimex tool

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#14826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Trimex tool extrudes a plane normal to the surface. But to work correctly, you always need to monitor the direction of the working plane. Why?
In most cases, we need extrusion along the normal to the surface and unnecessary actions only complicate the process.

Maybe it would be correct to disable the work plane dependency and make such a dependency as an option.
This will make working with this tool easier.

Perhaps you just need another extrusion tool that would work like a regular extrusion, but could take data from mouse movement (including with snaps).

Demonstration of strange behavior on video. Note that the correct result (which seems obvious) requires switching planes. For comparison, the behavior in Blender.

https://github.com/FreeCAD/FreeCAD/assets/32273833/4013d927-6995-426c-bda2-795da847dfbc

### Full version info

```shell
any
```

### Subproject(s) affected?

BIM/Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
The tool does use the mouse movement and can also use snaps. For this tool it is an issue that 'random' points in Draft are always projected on the current working plane.

**Comment by kaiwas** [comment]
> The tool does use the mouse movement and can also use snaps. For this tool it is an issue that 'random' points in Draft are always projected on the current working plane.

Yes. I know this.

I assumed that it was possible to modify the extrusion tool (BIM_extrude) so that it would understand mouse movement and snaps, but now you can only enter values ​​into the fields.

In this case, Trimex could be left untouched and left for working with flat elements (lines, etc.)

**Comment by yorikvanhavre** [comment]
I'm also wondering if this "Extrude" tool shouldn't be separated from Trimex... It does not make much sense to have it there
