### ISSUE TITLE
No instant Sketch position updates when position values are changed

### ISSUE THREAD

**Issue by EarlJay1** [FreeCAD/FreeCAD#14837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I noticed that in actual dev versions, sketches don't move while you alter the position values. Only after pressing Enter and recalculating the model the position gets updated. That was different in 0.21, where you could see the movement immediately, which is crucial for careful placement. 
For example: make a sketch in 0.21, go to the tree view, select it and alter the position (using the mousewheel for example)
In 0.22, I can alter the values, but the sketch sits in its old position until I hit enter or click in the 3D view

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37819 (Git) AppImage
Build type: Release
Branch: main
Hash: 2ca9b6ef8036d5fd808f01205b66eb0424059e21
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.39
  * fasteners 0.5.24
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
could you add a video demonstrating the issue, I cannot reproduce but not sure if I'm doing the same

**Comment by EarlJay1** [comment]
Don't know how to do a video about it, but simply create a new file, create a sketch, draw something in it.Then in the tree view go to the sketch, attachment offset, position and alter any value, e.g. increase Z by 1mm. The sketch in the 3dView only changes after clicking outside the value filed or hitting enter.
Before that you could see the sketch move instantly the moment you changed the position value without having to press enter. That was a far better workflow in some use cases.

**Comment by maxwxyz** [comment]
I cannot reproduce, it works as expected on Windows 11. I can even scroll with the wheel and the sketch moves instantly.

**Comment by maxwxyz** [comment]
Ah I got it now, you mean in PartDesign. It actually works in Part with the Placement dialog.
Is this related to https://github.com/FreeCAD/FreeCAD/issues/14436
@Syres916 @FlachyJoe @bgbsww FYI

**Comment by EarlJay1** [comment]
Well when I create a part in the part WB, there are instant position updates as ususal.
But when I create a sketch in Part Design, that can't be moved like that no matter what WB here.

**Comment by FlachyJoe** [comment]
AttachementOffset is not updated in real time but Placement is. It's the case for every geometry with MapMode not Desactivated.

**Comment by maxwxyz** [comment]
@FlachyJoe was this never possible, OP said it was possible before? Is there a reason for the offset being different?

**Comment by EarlJay1** [comment]
When I open the same file with 0.21 it works, when I open it with current dev snapshot, it doesn't.

**Comment by FlachyJoe** [comment]
AttchementOffset is updated at real time with 0.21.2. I confirm the regression.
I don't know more.

**Comment by AjinkyaDahale** [comment]
So what seems to be happening is `AttachmentOffset` eventually changes `Placement`, but until that doesn't happen the update isn't visible. `Placement` of `SketchObjectPy` is not editable when it's part of a Body, but is when it's used by itself in Part, even when it's used to create features.

**Comment by bgbsww** [comment]
I've noticed that effect too.  That implies a missing call to do the update
earlier.

**Comment by AjinkyaDahale** [comment]
`Part::AttachExtension` is defined twice depending on whether `FC_USE_TNP_FIX` is defined or not. That might be the problem.

**Comment by AjinkyaDahale** [comment]
My current guess is this: 84ae6b9b7bab0897f2a30428e832f2b9ac058aa6 added toponaming fixes, but missed out on some other changes that were added, possibly a8ae56e06ab0c45205f1f185523c23fe99d5ce44.

**Comment by bgbsww** [comment]
Ajinkya hunted this down; we collaborated and agreed I'd submit final PR.
