### ISSUE TITLE
Part Design: Error when circle sketch pad intersects a previous helical substraction

### ISSUE THREAD

**Issue by Ro3Deee** [FreeCAD/FreeCAD#14836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

the sketch contains just a circle (shown bellow with white). When padding it, it does not produce a cylinder (but a weird cut one, like  a pie). I think the subtractive helical above it messes things up: 
![image](https://github.com/FreeCAD/FreeCAD/assets/124100239/acf97197-1b45-450c-b64a-c243bd4b75b0)

### Full version info

```shell
OS: Ubuntu Core 22 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37839 (Git) Snap 1057
Build type: Release
Branch: main
Hash: 9b547bb90fbdf5f9e6df17fee640566cbe2ab37e
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
```

### Subproject(s) affected?

PartDesign

### Anything else?

here is the project file [project2.zip](https://github.com/user-attachments/files/15929529/project2.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FlachyJoe FYI
