### ISSUE TITLE
Part Design - creating a feature hides the previous model

### ISSUE THREAD

**Issue by petrubecheru** [FreeCAD/FreeCAD#14831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a cylinder. I create simple sketch on XZ plane. The, I pad it . The pad works, but hides the cilinder (the issue appears in the stable version (0.21.2) but also on the latest edge
Here is the file [project.zip](https://github.com/user-attachments/files/15927890/project.zip)

**Before padding the sketch:**
![image](https://github.com/FreeCAD/FreeCAD/assets/124100239/5c3b8f57-42db-4356-a5cd-d844840d90aa)

**After padding it:**
![image](https://github.com/FreeCAD/FreeCAD/assets/124100239/6dcd9dd4-95c0-475a-9959-fa3d7b2f8d4a)

### Full version info

```shell
OS: Ubuntu Core 22 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37839 (Git) Snap 1057
Build type: Release
Branch: main
Hash: 9b547bb90fbdf5f9e6df17fee640566cbe2ab37e
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
```

### Subproject(s) affected?

PartDesign

### Anything else?

none of the subtractive/addictive features work. All hide the cylinder

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
because it would create two solids in a body. In 0.22 you can activate in the preferences that part design bodies can have multiple solids

**Comment by FlachyJoe** [comment]
I can not reproduce. A full recompute of the document do the job.
Right click on the doc in the tree, Mark to recompute then recompute.
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/1d00f00a-0a2f-4aba-8bfc-d68ac05cf302)
