### ISSUE TITLE
CAM: Missing "SpecificCuttingForce" in machinability material model

### ISSUE THREAD

**Issue by davesrocketshop** [FreeCAD/FreeCAD#14867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

New machining materials describe a property "SpecificCuttingForce" which is not part of the Machinability material model. This shows in the report view as

`23:02:43  	Property 'SpecificCuttingForce' is not described by any model. Ignored
`

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 +113 (Git)
Build type: Release
Branch: issue_14779
Hash: 932c73f0de2d1e9ba3f60ae14d199cfe77255c3a
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * CfdOF 1.25.11
  * MaterialTest
  * OpenTheme 2024.5.3
  * Render 2024.1.23
  * Rocket 3.3.0
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

CAM/Path

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sliptonic** [comment]
Removed the offending files in PR #15930
