### ISSUE TITLE
FEM: Warnings about linked objects when meshing

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#14897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There is the following warning when meshing the last feature of a Body instead of the Body itself with Gmsh:

`Fem::FemMeshObjectPython: Link(s) to object(s) 'Pad' go out of the allowed scope 'FEMMeshGmsh'. Instead, the linked object(s) reside within 'Body Body'.`

An equivalent warning can occur when meshing with Netgen but apparently only when confirming with OK instead of Apply:

`Fem::FemMeshShapeNetgenObject: Link(s) to object(s) 'Pad' go out of the allowed scope 'FEMMeshNetgen'. Instead, the linked object(s) reside within 'Body Body'.`

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37841 (Git)
Build type: Release
Branch: main
Hash: 5f761c758e2a0164b00a7183b9c0cbe32688e123
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@marioalexis84 is this on your radar ?
