### ISSUE TITLE
Core: Selection of Part sub-object in tree highlight whole Part (Regression)

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#14905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you select one object within a App::Part in the tree, then the whole App::Part highlight:

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/c954a6a4-b608-4a87-a5ab-7682fd59f654)

It has been introduced recently, I think at last monday's merge meeting.
@chennes any idea which PR could have introduced this?

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
Does this still happen for you? For me it doesn't.
It looks like a duplicate of https://github.com/FreeCAD/FreeCAD/issues/14789 that was fixed with https://github.com/FreeCAD/FreeCAD/pull/14813

**Comment by PaddleStroke** [comment]
Indeed its fixed now.
