### ISSUE TITLE
Clipping view

### ISSUE THREAD

**Issue by malutanpetronel** [FreeCAD/FreeCAD#14904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The clipping view is not displaying the view in it

### Full version info

```shell
0.21.2
Rev 33771
```

### Subproject(s) affected?

None

### Anything else?

![before 2024-06-24_09-32](https://github.com/FreeCAD/FreeCAD/assets/5830216/e9ee1e61-ed8f-4618-bd6f-92665f3eb6b1)
![after 2024-06-24_09-31](https://github.com/FreeCAD/FreeCAD/assets/5830216/c4fbe2cc-1a99-4bf2-802b-f402487bab16)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please add:
- full about info
- demo file
- steps to reproduce

If possible please also test with the weekly version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by maxwxyz** [comment]
@malutanpetronel until no further info is provided this issue is closed
