### ISSUE TITLE
Sketcher Elements display broken

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#14932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the newest Windows weekly, the Sketcher Elements display looks broken:

![sketcher elements](https://github.com/FreeCAD/FreeCAD/assets/59876896/c6933bee-c7fc-4943-ab46-b4b12adbbd34)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Duplicate: #12265.
