### ISSUE TITLE
DAE mesh files imported as meshes, subsequently rotated, and exported as STL files appear to be rotated at double the angle

### ISSUE THREAD

**Issue by Emucde** [FreeCAD/FreeCAD#14936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Dear FreeCAD devoloper,

Thank you for developing such a valuable tool! I'm writing to report a potential bug I encountered while exporting DAE files to STL format in FreeCAD. When I import a DAE file (such as the included [shoulder.dae](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/blob/rolling/meshes/ur5e/visual/shoulder.dae) file) and rotate it around one or more axes, the exported STL file seems to have doubled rotation angles. **Update:** The issue of doubled transformations affects both rotations and translations when exporting to STL.

**Reproduction of the Issue:**

<details>

<summary> 1. import the <a href="https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/blob/rolling/meshes/ur5e/visual/shoulder.dae">shoulder.dae</a> file into new FreeCAD draft.</summary>

![screenshot1](https://github.com/FreeCAD/FreeCAD/assets/51852471/8fce18b0-4cd2-4310-8e88-7f32207a31f3)

</details>

<details>
<summary> 2. Rotate all parts along the X-axis by 45 degrees.</summary>

![screenshot2](https://github.com/FreeCAD/FreeCAD/assets/51852471/9e714d8f-7503-4912-ae1a-27166d8ef5d8)

</details>

<details>
<summary> 3. Export the rotated mesh as an STL file.</summary>

![screenshot3](https://github.com/FreeCAD/FreeCAD/assets/51852471/1ff6df24-5af7-42e8-878f-e09e2e7cf5bc)

</details>

<details>
<summary> 4. Import the exported STL file back into FreeCAD.</summary>

![screenshot4](https://github.com/FreeCAD/FreeCAD/assets/51852471/8c6efbe3-8791-4bac-bd24-8c7b00d8f36e)

</details>

### Full version info

```shell
[code]
OS: Fedora Linux 40 (Workstation Edition) (GNOME/gnome-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
[/code]
```

### Subproject(s) affected?

Mesh

### Anything else?

<details>

<summary> Related Issues / Forum</summary>

- As reported by a user on the forum: [Transformation doubles in exported stl](https://forum.freecad.org/viewtopic.php?t=87825)
- (not really) https://github.com/FreeCAD/FreeCAD/issues/13785
- (not really) https://github.com/FreeCAD/FreeCAD/issues/7304

</details>

[files_for_reproduction_freecad.zip](https://github.com/user-attachments/files/15968810/files_for_reproduction_freecad.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This already has been fixed in the current dev version.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37841 (Git)
Build type: Release
Branch: main
Hash: 5f761c758e2a0164b00a7183b9c0cbe32688e123
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
```
