### ISSUE TITLE
Invalid "Download" link on web site

### ISSUE THREAD

**Issue by hyperglitch** [FreeCAD/FreeCAD#14948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The download and some other links on the main site point to pages ending in .phpen where it should be .php. For example  https://www.freecad.org/downloads.phpen or https://www.freecad.org/sponsor.phpen

### Full version info

```shell
N/A
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
Kurt submitted a fix https://github.com/FreeCAD/FreeCAD-Homepage/commit/4e90896b61e7355f1f4088b598fd7bfb41ff057c and I've just tested the Download button successfully.
