### ISSUE TITLE
Loading a project file can be extremely slow

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#14952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Loading this [project file](https://forum.freecad.org/viewtopic.php?p=767830#p767830) takes several minutes to finish while with v0.21 it's only around 5 seconds.

The culprit is #14100 that tries to validate a shape within PropertyPartShape::setValue(). Doing this is wasted time in 99% of all cases.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37901 (Git)
Build type: debug
Branch: main
Hash: f310d2bd67e901c3cfdf57580770076ca0aff26b
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@bgbsww FYI
