### ISSUE TITLE
Std_VarSet has no documentation

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#15006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The new VarSet feature implemented with https://github.com/FreeCAD/FreeCAD/pull/12135 needs documentation.

This issue is simply to keep track of it and of some existing material that could be used as a source (these videos are mentioned within PR comments and are not easy to find):

- [Custom Data Elements, Variants, Modularity - Part 1](https://github.com/FreeCAD/FreeCAD/assets/5336482/0c425b24-2874-411f-8512-e73cbdc4d1d6)
- [Custom Data Elements, Variants, Modularity - Part 2](https://github.com/FreeCAD/FreeCAD/assets/5336482/2659a2f6-ee5b-4fb1-8961-073edd25fb12) <= not yet fully implemented.

There is also a third party tutorial video:

[![Tutorial: Ondsel VarSet](https://img.youtube.com/vi/KRqzeRxjkcw/0.jpg)](https://www.youtube.com/watch?v=KRqzeRxjkcw)

The wiki has some information on how to get a documentation page started for commands:

---

_This documentation is not finished. Please help and contribute documentation._

_[GuiCommand model](https://wiki.freecad.org/GuiCommand_model) explains how commands should be documented. Browse [Category:UnfinishedDocu](https://wiki.freecad.org/Category:UnfinishedDocu) to see more incomplete pages like this one. See [Category:Command Reference](https://wiki.freecad.org/Category:Command_Reference) for all commands._

_See [WikiPages](https://wiki.freecad.org/WikiPages) to learn about editing the wiki pages, and go to [Help FreeCAD](https://wiki.freecad.org/Help_FreeCAD) to learn about other ways in which you can contribute._

---

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37915 (Git)
Build type: Release
Branch: main
Hash: 8d3f07c1f73ef5b1829760db251b9524094aeea2
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Installed mods: 
  * OpenTheme 2024.5.16
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Initial version of the documentation:
https://wiki.freecad.org/Std_VarSet
