### ISSUE TITLE
FEM: Manual range specification for the color legend stopped working

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#15013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I've noticed the following regression (it works in 0.21.2) - it's not possible to manually specify the range for the color legend anymore - just nothing happens and the values are reset.

0.21.2:
![legend range 0 21 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/71d6d525-4f39-4f0e-91ed-fbb923c11f01)

0.22:
![legend range 0 22](https://github.com/FreeCAD/FreeCAD/assets/59876896/70d307a6-88af-4a51-a304-5d48e551c071)

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
Confirmed.

But it only happens for FEM stuff while for the curvature plot of a surface mesh (mesh workbench) it still works correctly.

**Comment by wwmayer** [comment]
The regression is caused by https://github.com/FreeCAD/FreeCAD/pull/13820 because in ViewProviderFemPostObject::OnChange() true is passed to WriteColorData to always override the value range.

**Comment by FEA-eng** [comment]
> The regression is caused by #13820 because in ViewProviderFemPostObject::OnChange() true is passed to WriteColorData to always override the value range.

@marioalexis84 Could you have a look at this?

**Comment by marioalexis84** [comment]
@wwmayer  thanks for noticing the regression.
