### ISSUE TITLE
TechDraw: No default page template

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#15045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

A quite important regression (with respect to 0.21.2) regarding TechDraw is that there's no default drawing template and the page is initially empty. Many users will (and already do) find it undesirable. Also, this renders #13005 much less relevant. IMO there should be a default template like in the previous versions instead of a confusing empty page. That's also how it works in other CAD software.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git)
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
While I agree that perhaps a blank A4 landscape page might not be to some/many users' taste, the default template is specified but not until the user clicks the 'Template' link:

![Screenshot from 2024-06-29 18-46-28](https://github.com/FreeCAD/FreeCAD/assets/46537884/1f7f0ace-68c7-4e1a-9391-8baa7e106bc3)

and then it gives (on Linux) the template as _/home/username/freecadbuildlocation/share/Mod/TechDraw/Templates/Default_Template_A4_Landscape.svg_

I'm guessing it's nolonger hard coded in _Preferences_ due to the AppImage builds having a constantly changing folder structure.

**Comment by FEA-eng** [comment]
@Syres916 On Windows, when I choose _Default_Template_A4_Landscape_, I get an empty page (unlike with other templates).

@WandererFan

**Comment by maxwxyz** [comment]
This blank page template was added intentionally a few weeks ago. Which should be the default, I guess it depends on locale and used standard so this cannot be hardcoded? Maybe just rename the default one to 'A4 empty' to avoid confusion.

**Comment by WandererFan** [comment]
There is a default template.  It is a blank page, like Ax_Landscape_blank.svg or ANSIx_Landscape_blank.svg, etc.

**Comment by FEA-eng** [comment]
> There is a default template. It is a blank page

Yes, but I consider it a regression since in previous versions the default template had a drawing table and it was useful.

**Comment by PaddleStroke** [comment]
I agree it's a regression.
imo the new page tool needs a taskbox instead of the 2 tools we now have, where you can select the size and standard of page. That requires quite some work as it needs to implement translation of template files and reorganisation of templates.

**Comment by luzpaz** [comment]
> I agree it's a regression.

 Should I remove the 'Feature' tag in that case ?

**Comment by maxwxyz** [comment]
IMO it's a feature as currently an empty page without border and title block is the default template. In the stable version its a ISO style template A4. I think depending on the preferences (ISO, ASME,...) a default page template should be set, for those who don't work with ISO or A4 size. Anyone can manually set a different template as default.

**Comment by benj5378** [comment]
I also agree that it's a regression. I think the ISO should be default.

Just because some people work with ASME, it should be blank? So it works for neither ASME or ISO people? Nah

**Comment by WandererFan** [comment]
Not a regression, just a change.  Nothing to do with ISO/ASME.

I use the blank one more that the ones with fields, but I suspect I am not a typical user.

The default template is "Default_Template_A4_Landscape.svg".  If anybody wants to do a PR that copies, say "A4_Landscape_TD.svg", to the default file spec, I have no objections.

There is also the preference for default template on the General tab.

**Comment by FEA-eng** [comment]
Shouldn't this stay open for now? The change below could be done to fix it:

> If anybody wants to do a PR that copies, say "A4_Landscape_TD.svg", to the default file spec, I have no objections.

**Comment by maxwxyz** [comment]
IMO the blank one is ok as there is no default template depending on the used standard and projection method. Maybe the default template should sometimes be linked to the ISO/ASME preference
