### ISSUE TITLE
Cannot find Polar transform in sketcher workbench

### ISSUE THREAD

**Issue by smaug-ravenhill** [FreeCAD/FreeCAD#15043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I wanted to rotate a shape (series of lines) about a point on a sketch, I could not find the Polar Transform function on any drop down menu, esp the sketcher menu, I could not find Polar Transform on the toolbar either.

### Full version info

```shell
[code]
OS: Linux Mint 20.3 (MATE)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/Australia (en_AU)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
will be present in the next version.
