### ISSUE TITLE
STEP Export going wrong

### ISSUE THREAD

**Issue by Anga23** [FreeCAD/FreeCAD#15056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I export a design to a STEP, the file includes an additional object.

Original FreeCAD:
![Original](https://github.com/FreeCAD/FreeCAD/assets/74612588/1dc3f0bf-915c-45b4-8e58-5edceea151c9)

STEP File: 
![Result](https://github.com/FreeCAD/FreeCAD/assets/74612588/f5d16602-7e30-4be6-ac7b-8633c29f4a62)

### Full version info

```shell
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git) AppImage
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * fasteners 0.5.21
  * FeedsAndSpeeds 0.5.0
  * MakerWorkbench 1.0.1
  * sheetmetal 0.4.17
```

### Subproject(s) affected?

None

### Anything else?

[Winkel.zip](https://github.com/user-attachments/files/16043750/Winkel.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
how did you export this file, I cannot reproduce. The STEP export looks exactly the same.
Maybe you have exported hidden objects.

[test.zip](https://github.com/user-attachments/files/16043999/test.zip)

**Comment by Anga23** [comment]
@maxwxyz Sorry for the inconvenience, now I try it again with following settings and it's fine: 

![Bildschirmfoto vom 2024-06-30 17-36-38](https://github.com/FreeCAD/FreeCAD/assets/74612588/ebc991e5-655f-4580-b6c6-722730d95e9b)

I was confused by the 2nd object witch I coldn't see it in the original FC file....
Thanks for Your time and support. Have a nice weekend!
