### ISSUE TITLE
Model tree : Disable delete from context menu for non-deleteable items.

### ISSUE THREAD

**Issue by hooperbloob** [FreeCAD/FreeCAD#15071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Some items in the model tree properly cannot be deleted, like the Origin node. 

In the attached screenshot, the disabled Cut option in the context menu reflects this but the Delete option still shows as enabled.  I guess as a general rule, if the Cut function is disabled then the Delete one should be as well.

<img width="311" alt="Screenshot 2024-06-30 at 12 32 22 PM" src="https://github.com/FreeCAD/FreeCAD/assets/1541370/7944552c-1441-4b87-b70c-92d08b7bbfc8">

### Full version info

```shell
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * sheetmetal 0.4.12
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Duplicate to https://github.com/FreeCAD/FreeCAD/issues/13194 https://github.com/FreeCAD/FreeCAD/issues/12826
