### ISSUE TITLE
AddonManager: self.package_cache wrong initial value.

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#15081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the `__init__` function `self.package_cache` is set to `None`. The `cache_package` function fails because of this. See warning text below. I suppose a similar issue exists for `self.macro_cache`.

```
10:59:51  Traceback (most recent call last):
10:59:51    File "D:\BKG_Tmp\FreeCAD_0.22\Mod\AddonManager\AddonManager.py", line 403, in reject
10:59:51      self.cache_package(repo)
10:59:51    File "D:\BKG_Tmp\FreeCAD_0.22\Mod\AddonManager\AddonManager.py", line 543, in cache_package
10:59:51      self.package_cache[repo.name] = repo.to_cache()
10:59:51      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
10:59:51  TypeError: 'NoneType' object does not support item assignment
```

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Addon Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Fixed by https://github.com/FreeCAD/FreeCAD/commit/2d2b6a31c7bcb062b27854afe8dc1943c769f59c
