### ISSUE TITLE
Cannot change font of a ShapeString after creating it

### ISSUE THREAD

**Issue by John-SC077** [FreeCAD/FreeCAD#15098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating a shapestring the software allows you to scroll through the windows/fonts directory to select the font you want to use. If at any time later you want to change your selection, click on the 3 dots next to the font field and navigate to that same fonts directory, the software pops up a warning that says "Fonts You don't have permission to open this file. Contact the owner or an administrator to obtain permission." This occurs even when running as administrator.

### Full version info

```shell
Version 0.21.2
Revision number 33771 (Git)
Release date 2023/11/14 build 22621
word size 64
branch releases/FreeCAD-0-21
Hash  b9bfa5c
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
What you are saying is not correct. You can definitely change the font. It is just that the Windows OS makes it a little harder.

For more information see:
https://wiki.freecad.org/Draft_ShapeString#Font_file_selection_on_Windows

Please start a [forum](https://forum.freecad.org/) topic if you need more help.

Closing this.
