### ISSUE TITLE
"Settings / General / Import profile" ok, but export not possible

### ISSUE THREAD

**Issue by EmEiBee** [FreeCAD/FreeCAD#15108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It doesn't seem possible to export all settings in order to provide the same working environment on a second FC instance.
Under "Settings / General / Import profile" there is a "Save new" button, but it only generates an entry in the field above, not an export file that I could import into the second FC instance.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git)
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

None

### Anything else?

![img-2024-07-02-11-43-22](https://github.com/FreeCAD/FreeCAD/assets/30090331/eaedf2c4-20d2-4cae-bd8d-8bbcd7a135f0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Royalty252** [comment]
Hi, I would like to contribute to this issue as part of the FOSS hackathon. I hope you find this request.

**Comment by Chin2202** [comment]
i would liketo contribuite to this issue

**Comment by luzpaz** [comment]
Please present your proposals

**Comment by maxwxyz** [comment]
Fixed by https://github.com/FreeCAD/FreeCAD/pull/15235
