### ISSUE TITLE
TechDraw: Snapping vertical dimensions - text is not aligned to the center

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Dimension text of vertical dimensions is snapping but not centered:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/3cc5b74d-f17a-4c37-ac4e-44e454e5f670)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git)
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke any news on this?

**Comment by benj5378** [comment]
How should over under tolerance labels be handled? 

![image](https://github.com/user-attachments/assets/f73437d7-ae68-4e30-b4e3-c5b16c52b3d6)

**Comment by maxwxyz** [comment]
@benj5378 should be considered, so not like above image but centered overall
@pierreporte FYI

**Comment by pierreporte** [comment]
@benj5378 The below right one, written vertically, is the right one. The whole content of the text (including prefixes, suffixes, and everything else) should be centered, not just the value. Note that the arrow length should be the same on both sides in this case, so strangely enough they look better on the above left.

**Comment by benj5378** [comment]
> Note that the arrow length should be the same on both sides in this case, so strangely enough they look better on the above left.

Thanks for the feedback. The arrow cut off is due to screenshot cropping ;)

**Comment by benj5378** [comment]
@PaddleStroke could you please help explain what is going on here? I get the first couple of lines with p1, p2, mid, normal, toCenter, but the posV and pos throws me off completely, and the following logic. Thanks.

https://github.com/FreeCAD/FreeCAD/blob/73cb5bafe0c32c178d9b594a6ca03124483d305f/src/Mod/TechDraw/Gui/QGIViewDimension.cpp#L187-L197

**Comment by PaddleStroke** [comment]
pos is the mouse position of the label. But the origin of the label, which is around one of its corner.
posV is a vector2d of pos + toCenter. So basically the position of the center of the label.

projPnt is a projection of posV onto the normal (passing by mid)

Then you check if projPnt and posV are close enough and if so you update the value of pos, which will be used to update the position of the label.

**Comment by benj5378** [comment]
@PaddleStroke Thanks, this helped a lot. I don't hope you mind if I rename the variable, and split up the functions

**Comment by PaddleStroke** [comment]
No problems of course

**Comment by WandererFan** [comment]
This LGTM.   No crashes or unexpected behaviour.  Thanks @benj5378.

I'll leave it to the experts to raise a new issue on how to treat the blue dim in the picture.
![DimTextSnap_regvsTheoCorrect](https://github.com/user-attachments/assets/dca21284-88dc-4ffb-a065-e9951b991fc6)
