### ISSUE TITLE
curves WB - cannot join curves a blend curve it's 2 curves

### ISSUE THREAD

**Issue by thecoolsundar** [FreeCAD/FreeCAD#15109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I try to join a blend curve to the 2 curves it was generated from, the operation fails with 'unknown exception while reading attribute 'curve' of object 'toposhape'

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37839 (Git) Snap 1057
Build type: Release
Branch: main
Hash: 9b547bb90fbdf5f9e6df17fee640566cbe2ab37e
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/India (en_IN)
Installed mods: 
  * CurvedShapes 1.0.9
  * Curves 0.6.37
```

### Subproject(s) affected?

None

### Anything else?

![image](https://github.com/FreeCAD/FreeCAD/assets/164626224/0ccc9342-1333-4e39-8907-191c3e3564c5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
please create the issue in the addon repo: https://github.com/tomate44/CurvesWB
