### ISSUE TITLE
Assembly: Dragging Part wants to delete joints

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Using this file from https://github.com/FreeCAD/FreeCAD/issues/14706#issuecomment-2173468569 trying to drag a part for reorder wants to delete all joints. Mouse is not clickable you have to press yes/no with the keyboard.

Demo:

https://github.com/FreeCAD/FreeCAD/assets/6246609/b8e1f024-541e-457e-aff8-0a2597cbbec0

@PaddleStroke is this related to https://github.com/FreeCAD/FreeCAD/issues/14991 ?

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git)
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.26.2
  * Curves 0.6.40
  * dodo 1.0.1
  * fasteners 0.5.24
  * freecad.gears 1.2.0
  * OpenTheme 2024.6.22
  * OpticsWorkbench 1.0.18
  * Rocket 3.3.0
  * sheetmetal 0.4.21
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
This bug is fixed by https://github.com/FreeCAD/FreeCAD/pull/15012
