### ISSUE TITLE
New dark theme: Text selection is not rendered/discernible

### ISSUE THREAD

**Issue by dapetcu21** [FreeCAD/FreeCAD#15129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

For example, the "mm" in the first text field is selected and can be edited, but it's impossible to see. All text inputs behave the same.

<img width="367" alt="Screenshot 2024-07-02 at 21 31 40" src="https://github.com/FreeCAD/FreeCAD/assets/428060/71641163-19dd-4ea7-8b39-a25db5a19a6c">

### Full version info

```shell
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hooperbloob** [comment]
I'm seeing the same thing, thanks for noting it.

**Comment by MisterMakerNL** [comment]
Is fixed here!
https://github.com/FreeCAD/FreeCAD/pull/14749

**Comment by dapetcu21** [comment]
Confirmed as fixed
