### ISSUE TITLE
Measure framework violates the software architecture of FreeCAD

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#15125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FreeCAD uses the classical plug-in architecture that is split into two main parts: the core system and the plug-ins (aka extension modules).
The core implements the most important basics and defines the interfaces. The plug-ins implement the interfaces to extend the application with new functionality.

Important is that the core doesn't know any details of the plug-ins.

Starting with https://github.com/FreeCAD/FreeCAD/pull/9750 this rule was violated. The core (FreeCADGui) includes the header `Mod/Measure/App/MeasureBase.h` of the Measure plug-in.
This may cause further problems because this header itself includes further headers from other plug-ins.

The result of this violation is that building the binaries may break as it can be seen here: https://github.com/FreeCAD/FreeCAD/pull/15122

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38016 (Git)
Build type: debug
Branch: main
Hash: 04cc890fd0685bc4143de1a8000e92dce0580d28
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@hlorus FYI
