### ISSUE TITLE
New dark theme: In settings menu, checkboxes are misaligned

### ISSUE THREAD

**Issue by dapetcu21** [FreeCAD/FreeCAD#15136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The checkboxes don't align with other text labels in the same column. 

New theme:

<img width="271" alt="Screenshot 2024-07-03 at 00 19 46" src="https://github.com/FreeCAD/FreeCAD/assets/428060/4cdf153a-4b37-4bcf-ac0e-d554f7179a57">

Classic:

<img width="264" alt="Screenshot 2024-07-03 at 00 23 18" src="https://github.com/FreeCAD/FreeCAD/assets/428060/c20b4975-13ac-4619-a6d4-e37688942b17">

### Full version info

```shell
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git)
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
I re-did the checkboxes here https://github.com/FreeCAD/FreeCAD/pull/15471
After merge need to test this.

**Comment by luzpaz** [comment]
@dapetcu21 please test most up to date dev version that includes these fixes and report back pls. TIA

**Comment by dapetcu21** [comment]
Still misaligned in 3fa339e9
(also related to this, I know it might be subjective, but I think there should be about 2px more padding between checkboxes and their label)

<img width="691" alt="Screenshot 2024-07-24 at 21 16 55" src="https://github.com/user-attachments/assets/ca810c14-f917-4147-bfcf-c457bf91ec0f">

**Comment by luzpaz** [comment]
@MisterMakerNL any idea for a solution going forward ?

**Comment by MisterMakerNL** [comment]
Did some googling found out you can add   "spacing:8px;" to checkboxes.
This seems to work perfectly, as it leaves out any single used checkbox and any text.

**Comment by MisterMakerNL** [comment]
I btw made it 8px but the radio button already had 4px, so maybe 8 is overkill?

**Comment by FEA-eng** [comment]
It seems that today's Windows weekly has more space between each checkbox and text but the checkboxes are aligned in the same way as they were before.

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38385 (Git)
Build type: Release
Branch: main
Hash: 58241e027e7187a1ecaeeb75668ef9a497437c68
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

**Comment by MisterMakerNL** [comment]
Could you be more specific what alignment you mean?

**Comment by FEA-eng** [comment]
> Could you be more specific what alignment you mean?

I'm referring to the original issue description. From what I understand, it's about the checkboxes not being in line with the first letter of each preference text without a checkbox:

![theme alignment](https://github.com/user-attachments/assets/78834bb4-d095-4012-8b65-643491933db9)

**Comment by MisterMakerNL** [comment]
Ah this is pretty easy fix, seems to be Qlabel having 2px padding!
