### ISSUE TITLE
New dark theme: Overlay panel header is white text on a white background

### ISSUE THREAD

**Issue by dapetcu21** [FreeCAD/FreeCAD#15133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

<img width="416" alt="Screenshot 2024-07-02 at 22 49 24" src="https://github.com/FreeCAD/FreeCAD/assets/428060/b3a63be8-6c18-4f9a-a17e-b79dc258dc55">

### Full version info

```shell
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
Yeah I wanted to make an issue about this, I also get this. You need to reboot Freecad and it should be fixed.

**Comment by dapetcu21** [comment]
Hmm, rebooting didn't do anything for me.

**Comment by MisterMakerNL** [comment]
Was indeed not a restart:
But I fixed it here:
https://github.com/FreeCAD/FreeCAD/pull/14749

**Comment by luzpaz** [comment]
Can we close this ticket ?

**Comment by dapetcu21** [comment]
Yup. It's fixed!
