### ISSUE TITLE
Part Design : Thickness value Task panel issue

### ISSUE THREAD

**Issue by marcuspollio** [FreeCAD/FreeCAD#15140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Part Design WB, the field for Thickness (dimensions value) in the Task panel of the Thickness tool has issues:
sometimes it does not allow greater dimensions that 9cm, sometimes freezes or even leads to a crash.

![PD-Thickness](https://github.com/FreeCAD/FreeCAD/assets/131592747/f9a3696d-d446-4be1-9c6f-50f467c6d328)

How to reproduce:
1) Open FreeCAD and in the Start dialog, choose the parametric Part (Part Design WB)
2) Create a simple base Sketch (say a circle or a rectangle on the XY plane with dimensions around 50cm)
3) Create a Pad from the previous sketch (length around 50cm)
4) Select the upper face and create a Thickness. The thickness input field does not allow to write e.g. 10cm. Trying to type certain values, changing the unit or use the +/- arrows to increase/decrease the value also lags.

`Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x76f5c2c42520]
#1  0x76f5c3223c88 in typeinfo for std::basic_streambuf<char, std::char_traits<char> > from /lib/x86_64-linux-gnu/libstdc++.so.6+0`

### Full version info

```shell
OS: GNU/Linux Ubuntu 22.04 LTS (DE: Gnome/pop)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38025 (Git)
Build type: Release
Branch: main
Hash: 04cc890fd0685bc4143de1a8000e92dce0580d28
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk , OCC 7.6.3
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
The thickness control has a hard-coded limit of 89.99 mm. See https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp

**Comment by marcuspollio** [comment]
Thanks Werner for having a look.
Is there a reason why the maximum value is hard-coded, instead of e.g. half of the smallest dimension of the selected face for inwards thickness and almost infinite for outwards thickness ?

**Comment by wwmayer** [comment]
> Is there a reason why the maximum value is hard-coded, instead of e.g. half of the smallest dimension of the selected face for inwards thickness and almost infinite for outwards thickness ?

When looking at the file history it's like this from the very beginning on. I guess it's a copy & paste issue where in the original code 89.99 was used for an angle.

**Comment by marcuspollio** [comment]
I wasn't expecting a tool refactor, but seeing as you're already there... thank you ! =D
