### ISSUE TITLE
Gui: Various property types in the VarSet dialog have unexpected results.

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#15156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The dialog to add properties to VarSets (command `Std_VarSet`) presents the user with a list of properties. Other than the standard dialog to add properties, this dialog allows users to directly add values. Some of the properties in the list do not allow directly adding a value or should not be user facing.

I propose to remove from the list the properties below because these are more internal properties and they cause an exception for the user:
- App::Property
- App::PropertyComplexGeoData
- ExpressionContainer
- ExpressionEngine
- Geometry
- IntegerSet
- LinkBase
- LinkListBase
- Lists
- XLinkContainer
- Sketcher::PropertyConstraintList

The following properties should not have an editor in this dialog (so they should be edited in the property view):
- Direction
- Placementlist
- Position

The reason for this is that these properties require a "compound" editor for multiple value input.

The following property type does not work properly:
- Font

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38025 (Git)
Build type: DEBUG
Branch: main
Hash: 04cc890fd0685bc4143de1a8000e92dce0580d28
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk , OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenTheme 2024.5.16
  * ondsel-lens 2024.7.2.01
```

### Subproject(s) affected?

Core

### Anything else?

Reported [here](https://github.com/Ondsel-Development/FreeCAD/issues/58#issuecomment-2204805080)

I've tested all property types.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
Perhaps also related to https://github.com/FreeCAD/FreeCAD/issues/15031?

**Comment by krushia** [comment]
These can still be used fine after creation, so don't remove them please. Even when there is no literal input method in the property view (which is another set of bugs to file), most can be given a value using expressions without touching the console.

Here is my list of "Partially" supported parameter types from testing VarSet dialog:
```
App::PropertyMaterial
PropertyPlacement
PropertyPlacementList
PropertyPythonObject
PropertyRotation
PropertyUUID
PropertyVector
PropertyVectorDistance

Material::PropertyMaterial

Part::PropertyGeometryList
PropertyPartShape
PropertyShapeCache
PropertyShapeHistory
PropertyTopoShapeList

Sketch::PropertyConstraintList
```

IMHO **there is no such thing as a "should not be user facing" property**. FreeCAD projects break all the time, and it would be extremely frustrating to have parts of the document hidden away when trying to fix things.

**Comment by pieterhijma** [comment]
@krushia, thanks, but for none of the ones on your list I propose to remove right?

**Comment by krushia** [comment]
If you're only removing `App::Property` and `App::PropertyLinkBase` from creation dialog(s), that seems reasonable. They can exist in Document.xml but I haven't found any utility yet (mostly just cause weird crashes).

**Comment by pieterhijma** [comment]
See, my [comment here](https://github.com/FreeCAD/FreeCAD/issues/15159#issuecomment-2217235180), I think the filtering that @wwmayer's PR achieves, should be used in the VarSet dialog as well. I will be adapting #15172 to that.
