### ISSUE TITLE
QtStyle is not reset after switching back from OpenTheme to Classic

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#15163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Initially, I reported this in the OpenTheme repo: https://github.com/obelisk79/OpenTheme/issues/84 but it seems to be an issue with FreeCAD itself. Apparently, QtStyle is not reset after switching back to the Classic theme.

Classic (before applying OpenLight):

![before](https://github.com/FreeCAD/FreeCAD/assets/59876896/00064dc2-e216-4538-bfa6-bcbbb1d719cc)

OpenLight:

![openlight](https://github.com/FreeCAD/FreeCAD/assets/59876896/67c957d3-80f4-474e-9357-04475874a1ed)

Classic (after switching back from OpenLight and restarting FreeCAD):

![classic back](https://github.com/FreeCAD/FreeCAD/assets/59876896/89015e6b-b1fd-4a0a-b725-c39a5248a8dc)

Manually removing the QtStyle key removes those remaining changes and brings back the default appearance.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git)
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
@FEA-eng just a suggestion, possibly add the Python code to remove the key to https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/PreferencePacks/Classic/post.FCMacro
Not sure if it'll need another restart though.

**Comment by FEA-eng** [comment]
@Syres916 Thank you, it's working.
