### ISSUE TITLE
PERCAGE METRIQUE DEFECTUEUx

### ISSUE THREAD

**Issue by Turban-dominique** [FreeCAD/FreeCAD#15166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Bonjour,
Pouvez vous revoir les dimension des taraudages ou filetages les diamètre sont erronés. 
Ex si je demande M6 >> me met 5.5mm alors que cela doit être 5 mm.
Merci
Dominique 

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git)
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * A2plus 0.4.62
  * fasteners 0.5.2
  * frame 0.1.1
  * Manipulator 1.5.7
  * sheetmetal 0.2.63
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please use the forum for help requests. If there is a bug, add steps how to reproduce it and create issues in English please.
