### ISSUE TITLE
Graphviz is expected to be at /usr/bin by default instead of anywhere in PATH

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD#15224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is not good for the appimage (and potentially other packaging formats) as it can't find the bundled binary by default and the user can't properly configure the path for the bundled binary since it changes on every launch. 
https://github.com/FreeCAD/FreeCAD/blob/561e521817034ea7660de987d8ab7183ad583595/src/Gui/GraphvizView.cpp#L286-L290

Instead this should look for the binaries in PATH by default

### Full version info

```shell
OS: Arch Linux (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git) AppImage
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: English/United Kingdom (en_GB) ]
Installed mods:
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
not a release blocker but would be nice to have this fixed before 1.0

**Comment by leoheck** [comment]
This is a regression, I never seen such an issue.
![image](https://github.com/FreeCAD/FreeCAD/assets/1277920/8b732004-75d9-4cdb-afc4-0e644383631c)

**Comment by adrianinsaval** [comment]
do you have graphviz installed on your system?

**Comment by leoheck** [comment]
we don't know the message is not clear.

**Comment by leoheck** [comment]
Yes, I do have it.
![image](https://github.com/FreeCAD/FreeCAD/assets/1277920/1285c319-7270-440c-9c1c-84e8a127b710)

**Comment by luzpaz** [comment]
Can you share the output of `whereis graphviz` pls ?

**Comment by leoheck** [comment]
I Will check this later when on my computer... but why does this matter. You should use tools that are on PATH. Doesn't matter where they are.

**Comment by luzpaz** [comment]
Just trying to cover all bases

**Comment by onekk** [comment]
> I Will check this later when on my computer... but why does this matter. You should use tools that are on PATH. Doesn't matter where they are.

Yes and no, as on some cases you could have different versions, it however a development choice, probably adding the ability to set "binary search path" or "non essential" tools path in preferences should be a good move.

If auto detection fails (or as example detect two version) a simple message could tell to set a "preference" to specify a desired location.

If autodetect is succeding this variables should be correctly set at first startup.

Similar solution is adopted by some softwares around at least in Linux world.

Regards

Carlo D.

**Comment by luzpaz** [comment]
bump @leoheck

**Comment by leoheck** [comment]
?

It should use the tools from the PATH. If a version is required, then Freecad should check the tool version and indicate that the current version is not good... and the user can still make a wrap script to tweak the version to use the tool he has.

**Comment by luzpaz** [comment]
> I Will check this later when on my computer... 

Please post output for `whereis graphviz` nonetheless. Thank you.

**Comment by leoheck** [comment]
Sorry dude, it doesn't matter. It is on $PATH.

**Comment by leoheck** [comment]
This is still an issue, Freecad is failing and I cannot use this tool to check what is going on. Nothing is working anymore. Yesterday it was all good.

**Comment by luzpaz** [comment]
@wwmayer do you have a suggestion perhaps ? :pray:

**Comment by adrianinsaval** [comment]
@leoheck can you test if this is fixed for you when the next weekly is available?
