### ISSUE TITLE
Label (translation?): Persistent Section Cut

### ISSUE THREAD

**Issue by depthoffocus** [FreeCAD/FreeCAD#15233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The menu item for "Persistent Section Cut" leads to a dialogue titled "Permanent Section Cutting". 

"Persistent" seems the better word than "Permanent", which implies unchangeability.

Mac, system region is "United Kingdom".

<img width="737" alt="Screenshot 2024-07-06 at 13 51 35" src="https://github.com/FreeCAD/FreeCAD/assets/813093/75c888e0-262f-4ab1-a8e0-80760244337a">

### Full version info

```shell
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38043 (Git)
Build type: Release
Branch: main
Hash: 561e521817034ea7660de987d8ab7183ad583595
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * ThreadProfile 1.90.0
  * freecad.gears 1.2.0
  * OpenTheme 2024.6.22
  * fasteners 0.5.24
  * Curves 0.6.40
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Good point. I made a PR to change it: #15237
