### ISSUE TITLE
[Feature Request] Add an option to Hole tool to create collar around a hole with different properties.

### ISSUE THREAD

**Issue by simrim1** [FreeCAD/FreeCAD#15234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is not a problem per se but it is when you have to create multiple holes with collars. You have create collars separately for every hole especially when holes are on different planes. These collars are required for different purposes like mounting a bearing on the bolt and prevent the outer revolving ring from touching the surface. This feature can be added to Hole toll with different properties like height of collar, width of collar, draft angle, inside, outside, both sides etc. Please refer to image attached what I mean.
![Screenshot 2024-07-05 154804](https://github.com/FreeCAD/FreeCAD/assets/13056546/77dcd2bc-cab9-4aaa-8480-8e3eb8f3823c)

### Full version info

OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * CurvedShapes 1.0.4
  * Curves 0.6.5
  * Design456 0.0.1
  * MeshRemodel 1.8919.0
  * workfeature-macro

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
You should be able to create them with the hole tool. Optional would be to chamfer them all.

**Comment by simrim1** [comment]
@maxwxyz Thanks for your response. I actually tried to find it in hole tool properties but I couldn't find this option. Will you please guide me to any tutorial/resourse where I can find it? Thanks
