### ISSUE TITLE
Visibility icon default state (active) is not shown in Preferences / Setting reset has wrong default values

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#15244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With a fresh Appimage (deleted .config .local/share and .cache folders), the Visibility icon is shown by default in the Tree as expected for merged PR #14393 but if you look into the Edit > Preferences > Display > UI , the "Show visibility icon" check box is inactive. See video attached.

The expected condition is that it is checked by default.

I have previously searched in Github with [is:issue is:open visibility icon]

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38043 (Git) AppImage
Build type: Release
Branch: main
Hash: 561e521817034ea7660de987d8ab7183ad583595
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
```

### Subproject(s) affected?

None

### Anything else?

https://github.com/FreeCAD/FreeCAD/assets/18265355/8e1a473c-c375-49a1-b9be-23c40c37ad74

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@NomAnor FYI

**Comment by NomAnor** [comment]
It looks like this concerns all options on the Display -> UI page (e.g. HideScrollBar, HideHeaderView). 

@kadet1090 changed the preferences in https://github.com/FreeCAD/FreeCAD/commit/05aaf0ed48bf81007bf85684eb6a07425bc56323 to a proper ui file but it seems he missed the https://github.com/FreeCAD/FreeCAD/blob/99d63a9693316bad118740dc8ee86098cca5e16b/src/Gui/TreeParams.py file that previously (and currently?) defines the list of options and their defaults.

I don't think other preferences use a similar file, so this file should propably be removed and its usage in the code replaced with whatever the other preferences use.

**Comment by kadet1090** [comment]
I'll sync up this manually, getting rid of that file is not easy :/

**Comment by luzpaz** [comment]
Any progress here ?

**Comment by maxwxyz** [comment]
It still resets all wrong on that page. Reset shows all columns in the tree view, even the internal names, hides the visibility icon,...

**Comment by Syres916** [comment]
@maxwxyz please double-check my investigation, is this what you believe a new user should see in Preferences>Display>UI  :

![Pref_Display_UI](https://github.com/user-attachments/assets/b8a7dfba-c21f-4b38-b2ed-704ce9671c52)

**Comment by maxwxyz** [comment]
@Syres916 Hide description also checked by default.

**Comment by Syres916** [comment]
@maxwxyz thanks, sorted and PR #15622 created.
