### ISSUE TITLE
Classic Theme: Tree view without transparency not legible on hover

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Using classic stylesheet with overlay on but transparency disabled renders the tree view and property view background white on hover, making it not legible:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/c7a00568-2494-4821-abfd-948b6e8ce997)

![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/e6b12f97-9726-4724-9525-0dd7b2d82aa1)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38043 (Git)
Build type: Release
Branch: main
Hash: 561e521817034ea7660de987d8ab7183ad583595
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.27.3
  * Curves 0.6.40
  * dodo 1.0.1
  * fasteners 0.5.24
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * OpticsWorkbench 1.0.18
  * Rocket 3.3.0
  * sheetmetal 0.4.21
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
Should be fixed here:
https://github.com/FreeCAD/FreeCAD/pull/14749
