### ISSUE TITLE
There is no seamless way to add new themes to the "Themes" drop-down list

### ISSUE THREAD

**Issue by raindropsfromsky** [FreeCAD/FreeCAD#15280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

We can apply a new theme from **Edit >Preferences...** menu.

However, if the available themes are not satisfying, a user will look for new themes. 
However, these themes are available from a totally different menu (**Tools > Addon Manager**).

There is no easy linkage between these two controls. 
As a result, the user sees a discontinuity here.

Instead, we should have an additional control (say, a + button to imply "add new themes" functionality) next to the **Themes** drop-down list.

If the user clicks there, it should open the **Addon Manager**'s themes list.
That way, the user will be taken from the **Edit > Preferences** to **Tools > Addon Manager** seamlessly.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of Ondsel: 64-bit
Version: 2024.2.0dev.38021 (Git)
Build type: Release
Branch: flavor
Hash: a34043c4fa4efa3c871e376a4e1536dcdeb86ebc
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/India (en_IN)
Installed mods: 
  * 3DfindIT 1.2.0
  * Behave-Dark-Colors 0.1.1
  * fasteners 0.5.24
  * Freecad-Built-in-themes-beta 1.2.2
  * FreeCAD-themes 2024.7.24
  * Ondsel-Lens 2024.3.26.01
  * OpenDark 2024.3.13
  * OpenTheme 2024.7.3
  * PieMenu 1.7.0
  * ProDarkThemePreferencePack 1.0.0
  * SearchBar 1.0.2
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
This has recently been implemented in the weekly builds: https://github.com/FreeCAD/FreeCAD/pull/15051
