### ISSUE TITLE
Freecad doesn't launch on Debain 12 (Sid)

### ISSUE THREAD

**Issue by dener3id** [FreeCAD/FreeCAD#15316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I try to run the Appimage on Debian 12 and splash screen runs then hard crash.

### Full version info

```shell
'FreeCAD-0.21.2-Linux-x86_64.AppImage' Won't open to get to that dialog. IDK if core is right sub-project just assuming core is the core of the app and not a workbench.
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
could you please try if the weekly AppImage works: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by luzpaz** [comment]
ping @dener3id

**Comment by dener3id** [comment]
I'm testing now Seems to work ok so far
