### ISSUE TITLE
Part_ColorPerFace: menu text needs to be updated

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#15327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The menu text of the Part_ColorPerFace command (in the View menu if the Part or PartDesign WB is active) is "Color per face" it should be "Appearance per face". Similar to the related Tree view context menu option "Set Appearance per face...". Maybe the command needs to be renamed as well.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38043 (Git)
Build type: Release
Branch: main
Hash: 561e521817034ea7660de987d8ab7183ad583595
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
moved to post 1.0 milestone per yorik in https://github.com/FreeCAD/FreeCAD/pull/15338#issuecomment-2228897133
