### ISSUE TITLE
sketching

### ISSUE THREAD

**Issue by bumble834** [FreeCAD/FreeCAD#15334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

cannot get an immediate response to whatever i draw, noticed that the opening screen takes a while to open also, i am using 21.2 ,i have searched within it for any conflicts didn't see anything 

### Full version info

```shell
there is nothing i can produce because it takes a while to get whatever I want on screen to show up and that's after moving the mouse to a location
```

### Subproject(s) affected?

None

### Anything else?

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
We cannot do anything without more info.
