### ISSUE TITLE
Assembly: exploded views do not work well with non-single-solid sub-assemblies

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#15344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I'm trying to create an exploded view of a model which contains sub-assemblies. Some, not all of the sub-assemblies should also be exploded. The attached file is a very simplified version of the model I'm working with. The goal is to have only one of the glass assemblies exploded.

I encountered many strange issues when trying to do this, some of which I cannot easily reproduce (parts disappearing, focus jumping from one document to another). Here's a video of the ones I could reproduce.

Notice, when the checkbox `Parts as single solid` is unchecked on the Exploded view's Tasks view:

1. Even though only one sub-assembly is selected, the other one always moves along with it. Inserted sub-assemblies of the same type cannot be independently moved
2. When exiting the Exploded Views object, the model needs to be manually recomputed to bring the components to their original location (I'm not sure if this is intended)
3. Moving a sub-assembly component affects the position of other sub-assembly components. See at around 1:07 s in the video how moving the glazing bead component "pushes" the previously moved glass component. 

[AsParts.webm](https://github.com/FreeCAD/FreeCAD/assets/148809153/731245d1-a075-446e-85b0-ea9a0ba1e892)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38095 (Git) Snap 1072
Build type: Release
Branch: main
Hash: af1f7385d47b9887e758794afdc3b1f69b406b96
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Assembly

### Anything else?

- File to reproduce: [Frame_exploded_bug.zip](https://github.com/user-attachments/files/16161691/Frame_exploded_bug.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
So the problem here is that you are using links to assemblies. Because of that the objects within are not links but the external objects themselves.
So when one moves, the other moves as well because it's the same object.

If we want to make this work we need to fix the following issue as I describe in this comment https://github.com/FreeCAD/FreeCAD/issues/15208#issuecomment-2211150976

**Comment by furgo16** [comment]
Related forum thread: https://forum.freecad.org/viewtopic.php?p=772142#p772142

**Comment by furgo16** [comment]
Same behavior after merging https://github.com/FreeCAD/FreeCAD/pull/15629

**Comment by PaddleStroke** [comment]
Have you replaced the App::Links with AssemblyLinks?
