### ISSUE TITLE
Measure: Memory leak in MeasureDistanceInfo

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#15349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The class MeasureDistanceInfo has a pointer to TopoDS_Shape.

In MeasureDistanceHandler an instance of MeasureDistanceInfo is created where a pointer to TopoDS_Shape is passed but this won't be destroyed by the destructor of MeasureDistanceInfo.

Since TopoDS_Shape itself works with a handle to the actual TopoDS_TShape (this is where the BRep structure is kept) there is no need to work with pointers of TopoDS_Shape.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38112 (Git)
Build type: debug
Branch: main
Hash: fb6c84b717765066a4ba796c1b1c09f38702fd43
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@hlorus FYI
