### ISSUE TITLE
Material: PartDesign feature does not get DiffuseColor attribute

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#15364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In V0.21 PD features have a DiffuseColor property. In V0.22 I would expect this property to be handled by an attribute of the ViewObject. Same as has been done for other objects.

### Full version info

```shell
V0.22
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@davesrocketshop FYI
