### ISSUE TITLE
Preferences: Apply button cannot set MSAA 4x option

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#15369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Open <kbd>Edit</kbd> > <kbd>Preferences...</kbd> > <kbd>Display</kbd> > <kbd>3D View</kbd>
2. Select <kbd>Rendering</kbd> > <kbd>Anti-Aliasing</kbd> > <kbd>MSAA 4x</kbd>
3. Click the <kbd>Apply</kbd> button
4. **Expected**: MSAA 4x is set
5. **Actual**: : MSAA 8x is set

https://github.com/FreeCAD/FreeCAD/assets/148809153/7dd0af5e-28ff-450b-b1d0-f37a0e8ab034

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38120 (Git) Snap 1073
Build type: Release
Branch: main
Hash: 9eeca1f6ad50cea9fa2d30d1a4fbb8b6e8fb4bbd
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Core

### Anything else?

- This used to work as expected on 0.21
- The OK button works as expected, it's just the Apply button
- Unrelated, but as a note: 0.21 used to have an MSAA 2x option too, which is gone in the developer version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
This is fixed with https://github.com/FreeCAD/FreeCAD/pull/15376

> Unrelated, but as a note: 0.21 used to have an MSAA 2x option too, which is gone in the developer version

That's actually correct because on your system MSAA 2x apparently is not supported. In v0.21 the modes None, Line smoothing, MSAA 2x, MSAA 4x and MSAA 8x were hard-coded while in v0.22 it's checked whether it's supported.
