### ISSUE TITLE
BIM: NativeIFC IFC_Save does not prompt for filename or IFC version

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#15362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After starting a new document and switching to "strict IFC" in the statusbar, IFC_Save does not prompt for a filename or for an IFC version.

Steps:
1. Start FreeCAD.
2. Switch to the BIM WB.
3. Switch ON "strict IFC" in the statusbar.
4. Answer "Yes" in the popup to create a default structure.
5. Select the "Save IFC file" menu option.
6. Result: no prompt.
7. Add an Arch Column.
8. Use "Save IFC file" again.
9. Close the file.
10. Result: document seems to be lost?

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38079 (Git)
Build type: Release
Branch: main
Hash: de508e437d13e7eb35baffceea496fb9107888cb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
```

### Subproject(s) affected?

BIM/Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Confirmed indeed. The "Save" option should divert to "Save as" if no file exists yet
