### ISSUE TITLE
External links have an oversized overlay icon

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#15372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When adding external links (e.g. nested assemblies) to an assembly, the overlay icons on the tree view that indicate that they are a link are oversized and clipped in comparison to the same [overlay icons](https://wiki.freecad.org/Tree_view#Overlay_icons) from other components (compare e.g. `Assembly001` with `Muntin bar002` in the screenshot below) 

![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/d0d1b14a-1763-48f5-9923-5402b87f02f3)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38120 (Git) Snap 1073
Build type: Release
Branch: main
Hash: 9eeca1f6ad50cea9fa2d30d1a4fbb8b6e8fb4bbd
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
I chose Assembly as the affected Subproject, but I think this is more of a global issue. Observing this somewhere else, it seems the issue applies to links to external files only.

**Comment by maxwxyz** [comment]
Related: https://github.com/FreeCAD/FreeCAD/issues/6765
On some systems they appear too small

**Comment by furgo16** [comment]
This is marked as https://github.com/FreeCAD/FreeCAD/labels/Good%20first%20issue, but is the actual cause and the steps to fix it known?

Looking at the related issue, it seems that there are a number of xpm files that need to be removed from git and from a resource file, but simply for tidying up purposes. If I understand it correctly, their .svg counterparts are already being used, but the size is still an issue?

**Comment by furgo16** [comment]
Can someone knowledgeable with this issue perhaps summarize what's needed to do to fix it? I'd try to give a go to a fix once I understand it better. Thanks!

**Comment by furgo16** [comment]
I'm looking at how it was fixed in https://github.com/FreeCAD/FreeCAD/commit/a93997df64e1401a0e89ec180b6222ff57e87bc0

These are the remaining XPM bitmaps

```
find -name *.xpm
./src/Gui/Icons/button_right.xpm
./src/Gui/Icons/bulb.xpm
./src/Gui/Icons/button_up.xpm
./src/Gui/Icons/LinkArrayOverlay.xpm
./src/Gui/Icons/LinkSubElement.xpm
./src/Gui/Icons/LinkOverlay.xpm
./src/Gui/Icons/freecad.xpm
./src/Gui/Icons/button_left.xpm
./src/Gui/Icons/button_down.xpm
./src/Gui/Icons/LinkSubOverlay.xpm
```

I would think that the overlay in question is one of `LinkSubElement`, `LinkOverlay` or `LinkSubOverlay`. However, it seems their SVG counterparts are already being loaded:

```
git grep "LinkSubElement"
src/Gui/Icons/LinkSubElement.svg:   sodipodi:docname="LinkSubElement.svg"
src/Gui/Icons/LinkSubOverlay.svg:   sodipodi:docname="LinkSubElement.svg"
src/Gui/Icons/resource.qrc:        <file>LinkSubElement.svg</file>
src/Gui/Icons/resource.qrc:        <file>LinkSubElement.xpm</file>
src/Gui/ViewProviderLink.cpp:        return BitmapFactory().pixmapFromSvg("LinkSubElement", QSizeF(px,px));
```

```
git grep "LinkOverlay"
src/Gui/Icons/LinkArrayOverlay.svg:   sodipodi:docname="LinkOverlay.svg"
src/Gui/Icons/LinkOverlay.svg:   sodipodi:docname="LinkOverlay.svg"
src/Gui/Icons/resource.qrc:        <file>LinkOverlay.svg</file>
src/Gui/Icons/resource.qrc:        <file>LinkOverlay.xpm</file>
src/Gui/Tree.cpp:                pxExternal = Gui::BitmapFactory().pixmapFromSvg("LinkOverlay",
src/Gui/ViewProviderLink.cpp:        return BitmapFactory().pixmapFromSvg("LinkOverlay", QSizeF(px,px));
```

```
git grep "LinkSubOverlay"
src/Gui/Icons/resource.qrc:        <file>LinkSubOverlay.svg</file>
src/Gui/Icons/resource.qrc:        <file>LinkSubOverlay.xpm</file>
src/Gui/ViewProviderLink.cpp:        return BitmapFactory().pixmapFromSvg("LinkSubOverlay", QSizeF(px,px));
```

**Comment by maxwxyz** [comment]
@furgo16 thank you! Would be great for 1.0!

**Comment by furgo16** [comment]
WIP...

| XPM icon name | XPM icon | SVG icon name | SVG icon |
| --- | --- | --- | --- |
| button_right.xpm  | ![button_right xpm](https://github.com/user-attachments/assets/ed7cd36f-71d7-4de7-85a8-47f4bab73196) | button_right.svg | ![button_right](https://github.com/user-attachments/assets/378296b4-85a0-47d0-a7b8-f2c94e9a0ff9) |
| bulb.xpm | ![bulb xpm](https://github.com/user-attachments/assets/d79be946-1db9-4b06-a26b-60a1ff888d83) | bulb.svg | ![bulb](https://github.com/user-attachments/assets/7a460a57-7845-463d-901f-b2e5071c48b6) |
| button_up.xpm | ![button_up xpm](https://github.com/user-attachments/assets/a2e1a28d-02bf-44d0-8328-08641f50a288) | button_up.svg | ![button_up](https://github.com/user-attachments/assets/e662e3c6-a604-4dbd-aa23-3b47bb7687b3) |
| LinkArrayOverlay.xpm | ![LinkArrayOverlay xpm](https://github.com/user-attachments/assets/3690d52f-f11e-4eb4-a9e6-5e571f77c6a0)  |  |  |
| LinkSubElement.xpm | ![LinkSubElement xpm](https://github.com/user-attachments/assets/9dd3fa2f-4daf-4d81-a992-539c6b67a73d)  |  |  |
| LinkOverlay.xpm |![LinkOverlay xpm](https://github.com/user-attachments/assets/2398a0f0-d164-4d73-bc5e-4e96ed415830) | LinkOverlay.svg | ![LinkOverlay](https://github.com/user-attachments/assets/6cc4c28c-ca24-4de1-8f7f-f50b79a21b7e) |
| freecad.xpm | ![freecad xpm](https://github.com/user-attachments/assets/12085e8f-6ea7-47a3-8ab7-d0d2c233412a) |  |  |
| button_left.xpm | ![button_left xpm](https://github.com/user-attachments/assets/ae8eb47e-bb33-4014-bac9-c3309c9ae26d) |  |  |
| button_down.xpm | ![button_down xpm](https://github.com/user-attachments/assets/50582510-bdc1-4779-912f-39f372e8441e) |  |  |
| LinkSubOverlay.xpm  | ![LinkSubOverlay xpm](https://github.com/user-attachments/assets/5668051a-1793-496b-9469-ae9ecf5b0c23)  |  |  |

**Comment by maxwxyz** [comment]
@furgo16 do you need some svgs? I can provide them but I think they should be all in GUI

**Comment by furgo16** [comment]
Thanks! It should be fine, the SVGs seem to be all there, it's just that the table is WIP and I come back to it when I have a few spare minutes.

In any case, I think the XPM icons are not the cause. If I understand it correctly, there seems to be a difference in how the size of the overlay icons is calculated in local links vs external links:

https://github.com/FreeCAD/FreeCAD/blob/a9bff78974f301100134a13c636e23aa91be5bcf/src/Gui/ViewProviderLink.cpp#L1727-L1735

https://github.com/FreeCAD/FreeCAD/blob/a9bff78974f301100134a13c636e23aa91be5bcf/src/Gui/Tree.cpp#L5421-L5422
