### ISSUE TITLE
TechDraw: Line style preferences not translated

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The TechDraw line style preferences in the drop down menu are not displayed with the translated strings. On Crowdin, all these line style strings have approved translations.
![grafik](https://github.com/user-attachments/assets/f4d96e3e-00bc-4e20-8279-d3e3ae05dc05)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38079 (Git)
Build type: Release
Branch: main
Hash: de508e437d13e7eb35baffceea496fb9107888cb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.27.4
  * Curves 0.6.40
  * dodo 1.0.1
  * fasteners 0.5.24
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * OpticsWorkbench 1.0.18
  * Rocket 3.3.0
  * sheetmetal 0.4.22
```

### Subproject(s) affected?

Techdraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Should be fixed by PR #15460.
![NomsDesLinges](https://github.com/user-attachments/assets/e83da5f4-c994-431b-858f-cc998d7bafcf)
