### ISSUE TITLE
PPA for Ubuntu does not include release for the current LTS of Ubuntu (24.04, Noble Numbat))

### ISSUE THREAD

**Issue by Hellmark** [FreeCAD/FreeCAD#15410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The PPA has support for 18.04, 20.04, 22.04, and 23.10, but not 24.04, which is the current LTS. This is especially a problem as the appimage release will not run if you're using Mesa ( FreeCAD/FreeCAD-Bundle#270 )

### Full version info

```shell
FreeCAD 0.21.2, Libs: 0.21.2R33771 (Git)
```

### Subproject(s) affected?

None

### Anything else?

In reference to https://launchpad.net/~freecad-maintainers/+archive/ubuntu/freecad-stable and https://launchpad.net/~freecad-maintainers/+archive/ubuntu/freecad-daily

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
I started now a build of the stable package for 24.04, should be available soon. For the daily package it'll take a little longer as I want to make that one using qt6
