### ISSUE TITLE
FEM: FEM_CreateElementsSet.svg has a white background, is illegible, and is not a proper SVG

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#15416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The FEM_CreateElementsSet.svg has a white background and is a pixel image encapsulated in an SVG. The red E in the image is pretty much illegible.

Using FEM_MeshGroup.svg as the basis a better icon should be created. 

### Full version info

```shell
V0.22
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
@maxwxyz I think that it can be treated as a bug since the current icon doesn't follow basic standards and shouldn't be there.
