### ISSUE TITLE
In [export]-[Wavefront OBJ-Arch module(*.obj)] menu, it doesn't export with color

### ISSUE THREAD

**Issue by IamDDOL** [FreeCAD/FreeCAD#15429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I can expert to *.obj with color in version 0.21.2
But I can not expert to *.obj with color in version 0.22.0 dev. 3817
It's only expert with gray scale.
I'm checking the color of *.obj in powerpoint.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38127 (Git)
Build type: Release
Branch: main
Hash: 9868533d8d0ef1f569cbde538b7a31350db503bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Korean/South Korea (ko_KR)
Installed mods: 
  * dodo 1.0.1
  * Help 1.0.3
```

### Subproject(s) affected?

None

### Anything else?

[TestColor.zip](https://github.com/user-attachments/files/16232160/TestColor.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
This to me is showing that the accompanying `.mtl` file is not being produced alongside the `.obj` file. The last working build I have is:

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git) AppImage
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
```

and the first failing build I have is:

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git) AppImage
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
```
