### ISSUE TITLE
Failed to edit a PD Feature and access an external geometry

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#15439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am trying to access the black line above the horizontal sketch on top.
![image](https://github.com/user-attachments/assets/020bc966-80b3-495b-8e52-4d576e4e1c4c)

When creating a sample file to share it here I could not see this issue again.

The report view shows this
![image](https://github.com/user-attachments/assets/7d875699-4715-498d-819e-4d169106458a)

So my question is: How do I locate and fix objects that has the name starting with `?`?

The popup could also have the object name. Or a tip to locate the issue.

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38127 (Git) AppImage
Build type: Release
Branch: main
Hash: 9868533d8d0ef1f569cbde538b7a31350db503bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.22
  * InventorLoader 1.4.0
  * ose-piping
  * OpenTheme 2024.7.3
  * fasteners 0.5.24
  * asm4_disable_version_check_popup
  * OpticsWorkbench 1.0.18
  * lattice2 1.0.0
  * kicadStepUpMod
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leoheck** [comment]
Closing and opening the file fix this.

**Comment by leoheck** [comment]
Is this already fixed?

**Comment by maxwxyz** [comment]
is this still an issue for you? Please provide a demo file then.

**Comment by leoheck** [comment]
After closing and launching a file the problem gone. 
But this is not a fix. 

How do I locate and fix objects that has the name starting with `?`?
