### ISSUE TITLE
[Feature] PartDesign Pad: add offset, symmetric and reversed for up to shape / up to face

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#15461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The `Up to face` type on PD Pad has a `Reversed` option that does not change anything. 

Also, it does not have the `Symmetric` that will be handy.

This is also on `Up to shape`.
`Up to shape` could also have the `Offset` property. 

![image](https://github.com/user-attachments/assets/482dabd4-abd2-4279-922f-344561c9cce7)

![image](https://github.com/user-attachments/assets/9735c0ee-d6ec-4850-bf9d-84b01e5538ac)

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38127 (Git) AppImage
Build type: Release
Branch: main
Hash: 9868533d8d0ef1f569cbde538b7a31350db503bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
What would be the result of up to shape with symmetry and reversed? IMO it makes only sense in the direction where the extrusion would touch the shape.
@FlachyJoe FYI

**Comment by pierreporte** [comment]
This is actually 3 issues, so new ones should be opened

1. **The Up to face type on PD Pad has a Reversed option that does not change anything.** → “Reverse” option is allowed even when it doesn’t make sense, thus should be disabled in these situations.

2. **Also, it does not have the Symmetric that will be handy.** → New feature request that has a workaround.

3. **Up to shape could also have the Offset property.** → New feature request.

**Comment by leoheck** [comment]
Ok, I am going to create these 3 new issues, and after that, close this one @pierreporte

**Comment by pierreporte** [comment]
Symmetry is available:

![image](https://github.com/user-attachments/assets/1c9df767-8382-4550-bef4-20c01ea0e65b)

**Comment by leoheck** [comment]
> * **Also, it does not have the Symmetric that will be handy.** → New feature request that has a workaround.
> *

The Pad type should be Up-to-face. Move this discussion to this new issue, please. https://github.com/FreeCAD/FreeCAD/issues/15461#issuecomment-2322911102
