### ISSUE TITLE
Switch Sketcher Create Fillet into Sketcher Create Chamfer mode does not work

### ISSUE THREAD

**Issue by meggamer** [FreeCAD/FreeCAD#15470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In no case mentioned in https://wiki.freecad.org/Sketcher_CreateChamfer/en description the tool switches into Sketcher Create Chamfer mode.
No dialog box appears in Combo View. Please advice.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
In the Wiki page you quote, on the right-hand side is **Introduced in version** and it does state 1.0 hence why in 0.21.2 it is not available.
