### ISSUE TITLE
Material: Child ignoring parent material

### ISSUE THREAD

**Issue by davesrocketshop** [FreeCAD/FreeCAD#15503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When modifying a part, the resulting child ignores the parent material.

Steps to reproduce:
1. In Part WB create a Box
2. Set the material to something other than default
3. Create a chamfer
4. The resulting piece has been reset to the default material

Part Design WB has similar problems

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38259 (Git)
Build type: Release
Branch: main
Hash: c8046b1c60c786caca3050cf51f853454ffb5388
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * ArchTextures
  * CfdOF 1.25.11
  * fasteners 0.5.17
  * fcgear 1.0.0
  * FeedsAndSpeeds 0.5.0
  * GDML.backup1701064072.5104816 2.0.0 (Disabled)
  * kicadStepUpMod 11.1.2
  * LCInterlocking
  * MaterialTest
  * OpenTheme 2024.5.3
  * render 2024.6.11
  * Rocket 4.0.0
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should this issue be fixed for the 1.0 release?

**Comment by davesrocketshop** [comment]
Yes

**Comment by maxwxyz** [comment]
@davesrocketshop any news on this issue? Is it ok for you if we remove the blocker tag?

**Comment by davesrocketshop** [comment]
> @davesrocketshop any news on this issue? Is it ok for you if we remove the blocker tag?

Yes. I'm working on it but a fix may take a while

**Comment by maxwxyz** [comment]
so really not necessary for a 1.0 release?

**Comment by FEA-eng** [comment]
IMO it should be a blocker for 1.0, unless it's too hard to fix in time. That's a really nasty bug.

**Comment by davesrocketshop** [comment]
It is a very difficult fix. I have no clear solution yet, but I'll update if I get close

**Comment by maxwxyz** [comment]
Could somebody help with this issue? New duplicate issues coming in regularly now.

**Comment by davesrocketshop** [comment]
It is being actively worked on

**Comment by bgbsww** [comment]
I'm sure I don't fully understand the nuances here, so feel free to just discard this.

This addresses only the Part Fillets and Chamfers, and it is rough with corner cases, not sure if it's the right direction:

```
App::DocumentObjectExecReturn *Feature::execute()
{
    // belongs in FeatureBase::execute that doesn't exist.
    auto base = dynamic_cast<Part::FilletBase *>(this);
    if ( base ) {
        App::DocumentObject *link = base->Base.getValue();
        if (!link)
            return new App::DocumentObjectExecReturn("No object linked");
        auto mat = Materials::MaterialManager::defaultMaterial();
        auto feature = dynamic_cast<Part::Feature *>(link);
        if (ShapeMaterial.getValue().getName() != feature->ShapeMaterial.getValue().getName())
            if (ShapeMaterial.getValue().getName() == mat->getName())
                ShapeMaterial.setValue(feature->ShapeMaterial.getValue());
    }
    this->Shape.touch();
    return GeoFeature::execute();
}
```

If there's a conversation somewhere I can help with, let me know.

**Comment by davesrocketshop** [comment]
> I'm sure I don't fully understand the nuances here, so feel free to just discard this.
> 
> This addresses only the Part Fillets and Chamfers, and it is rough with corner cases, not sure if it's the right direction:
> 
> ```
> App::DocumentObjectExecReturn *Feature::execute()
> {
>     // belongs in FeatureBase::execute that doesn't exist.
>     auto base = dynamic_cast<Part::FilletBase *>(this);
>     if ( base ) {
>         App::DocumentObject *link = base->Base.getValue();
>         if (!link)
>             return new App::DocumentObjectExecReturn("No object linked");
>         auto mat = Materials::MaterialManager::defaultMaterial();
>         auto feature = dynamic_cast<Part::Feature *>(link);
>         if (ShapeMaterial.getValue().getName() != feature->ShapeMaterial.getValue().getName())
>             if (ShapeMaterial.getValue().getName() == mat->getName())
>                 ShapeMaterial.setValue(feature->ShapeMaterial.getValue());
>     }
>     this->Shape.touch();
>     return GeoFeature::execute();
> }
> ```
> 
> If there's a conversation somewhere I can help with, let me know.

There are a lot of nuances that I'm trying to track down. This helps.

**Comment by bgbsww** [comment]
If there's a section I can hack down some of the weeds in, let me know - I can try to generalize the above and then apply to other part operations if appropriate, or go over and try to play with PD.

**Comment by maxwxyz** [comment]
@davesrocketshop is there some state to test or anything other I could help with (not coding unfortunately).

**Comment by maxwxyz** [comment]
@davesrocketshop in today's developer meeting it was decided that this should not be a blocker for 1.0
IMO it's a really annoying issue, which is also seen in the multiple duplicate issues which were created. Any chance you could get a fix in 1.0?

**Comment by davesrocketshop** [comment]
> @davesrocketshop in today's developer meeting it was decided that this should not be a blocker for 1.0 IMO it's a really annoying issue, which is also seen in the multiple duplicate issues which were created. Any chance you could get a fix in 1.0?

Didn't realize there was a developers meeting today. I should check the calendar more often. I'm almost done with a fix. I hope to have it ready for merge by the end of tomorrow.

**Comment by davesrocketshop** [comment]
PR submitted and building #17360

**Comment by JDMils** [comment]
It's been a while and it seems this is still an issue. I just posted about it on the forums here:
https://forum.freecad.org/viewtopic.php?t=98852

Link to demo video:
https://youtu.be/AoZa4YnJQDE

[Custom_Colours_Lost_JDMils.zip](https://github.com/user-attachments/files/21587448/Custom_Colours_Lost_JDMils.zip)

I'm using one of the latest FC versions:
`OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.42780 (Git)
Build date: 2025/07/28 17:17:34
Build type: Release
Branch: main
Hash: 8dc6397fc4433785f73f8a1958ff11243c348376
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/Australia (en_AU)
Navigation Style/Orbit Style/Rotation Mode: TinkerCAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/106.57/1.5
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.68
  * Assembly4 0.50.18
  * Curves 0.6.62
  * fasteners 0.5.38
  * Gridfinity 0.11.9
  * lattice2 1.0.0
  * Manipulator 1.6.0
`

Very simple sample file included.

**Comment by knacky34** [comment]
@davesrocketshop, I confirm the issue is still present when using per face appearance in Part WB.

```
OS: KDE Flatpak runtime (GNOME/gnome/wayland)
Architecture: x86_64
Version: 1.1.0rc1.44348 (Git)
Build date: 2025/11/25 17:53:08
Build type: Release
Branch: (HEAD detached at 1.1rc1)
Hash: 53767601ea65de7cd9f6590e7d5856afc0841635
Python 3.13.9, Qt 6.10.1, Coin 4.0.3, Vtk 9.3.1, boost 1_84, Eigen3 3.4.1, PySide 6.10.1
shiboken 6.10.1, SMESH 7.7.1.0, xerces-c 3.3.0, IfcOpenShell 0.0.0, OCC 7.8.1
Locale: French/France (fr_FR)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/129.483/1
Installed mods: 
  * sheetmetal 0.7.60
  * fasteners 0.5.43
  * FrameForge 0.1.6
```

**Comment by maxwxyz** [comment]
@davesrocketshop so it is basically the request to consider element history for color / material:
- https://github.com/FreeCAD/FreeCAD/issues/11210

**Comment by luzpaz** [comment]
Is this still relevant ?
