### ISSUE TITLE
VarSet: Cannot enter exisiting prop name as prefix for new prop name

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#15551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The "Add a property" dialog box of the Std_VarSet command does not allow the use of an existing property name as the prefix for a new property name. If there is a property named "Length" you are prevented from entering "LengthTotal" for example. "Length" is simply deleted from the input box. You have to use a workaround. Not very user-friendly.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38231 (Git)
Build type: Release
Branch: main
Hash: 29889bfd9a7ba0f0496f2e2699d454ea5fb5a05a
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pieterhijma** [comment]
Yes, this is not userfriendly indeed. I think it is a regression introduced as a result of https://github.com/FreeCAD/FreeCAD/pull/15171. I would even call it a bug, I think.
