### ISSUE TITLE
UX: Acknowledge copies to clipboard (via Report View)

### ISSUE THREAD

**Issue by hooperbloob** [FreeCAD/FreeCAD#15561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the FreeCAD About box you're able to copy the configuration to the clipboard but when the user clicks the button, nothing confirms that this happened. Most applications I've used will acknowledge this with a quick popup message: 'Copied to clipboard'.  We need the same thing.

There could be similar copy-to-clipboard facilities in FreeCAD that have the same deficiency.

### Full version info

```shell
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38261 (Git)
Build type: Release
Branch: main
Hash: 51789ae8a1a0b1ed20317eaedcd190baac734e3d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * BIM021 2021.12.0
  * fasteners 0.5.24
  * sheetmetal 0.4.12
  * Assembly4 0.50.15
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
What about a message appearing in the Report View instead ? Popups get some users upset because they don't like it (considered spam)

**Comment by hooperbloob** [comment]
It doesn't need to be a full blown popup.  Heck, even if you just change the button label from 'Copy to clipboard'  to 'Copied!'  for two seconds and then revert that'd be enough.

**Comment by furgo16** [comment]
> What about a message appearing in the Report View instead ?

Or in the notification area

**Comment by yashathwani** [comment]
Can I work on this issue ?

**Comment by luzpaz** [comment]
Sure! Feel free to propose a fix. Note: it will probably be postponed till post 1.0 release since we're in a feature freeze, but nevertheless, have at it!

**Comment by luzpaz** [comment]
@yashathwani ping

**Comment by BMaxV** [comment]
@hyarion recommended I take this one as a first issue, so I will have a go at it. :)

**Comment by hyarion** [comment]
> Or in the notification area

The notification area is only shown when the main window is focused. When about window is opened, the user needs to click the button at the bottom to see it.

> It doesn't need to be a full blown popup. Heck, even if you just change the button label from 'Copy to clipboard' to 'Copied!' for two seconds and then revert that'd be enough.

This could work.
