### ISSUE TITLE
Assembly: Distance joint doesn't solve correctly - moves grounded part instead

### ISSUE THREAD

**Issue by tibfel** [FreeCAD/FreeCAD#15582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am making a simple table project. I have a table top and a leg. 
![image](https://github.com/user-attachments/assets/2bcbb45e-d693-4ef0-8f1b-f953c73d6e03).
Table top is grounded. 
![image](https://github.com/user-attachments/assets/ed3e90d3-ec81-45f3-a4ff-7a1842a612d4)
The grounded part should remain its position and the table leg should mate the table top. However the joint changes the orientation of the grounded part to this:
![image](https://github.com/user-attachments/assets/5ae593e7-192e-4e7e-919a-b2d0b7219874)
![image](https://github.com/user-attachments/assets/bc0da6a4-a4b0-4482-afb6-bc1b08aaea23)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Slovak/Slovakia (sk_SK)
Installed mods: 
  * FreeCAD-themes 2024.7.24
  * OpenTheme 2024.7.3
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@tibfel did you try this with the latest dev version from https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
There were some recent fixes iirc.
If the issue still persists in the latest weekly, please provide a demo file.

**Comment by tibfel** [comment]
@maxwxyz Yes, I have used the latest weekly build. 

Here are the files. 
[Issue.zip](https://github.com/user-attachments/files/16358244/Issue.zip)
When you remove the distance joint, the tabletop reverts into the correct horizontal position. Then when you add the distance joint again, it aligns itself with the unconstrained leg. The correct solution would be the other way around. The unconstrained leg should align with the grounded tabletop.

**Comment by maxwxyz** [comment]
@tibfel I cannot reproduce.
The grounded part dows not move, the distance joint is always correct and removing the distance joint does not change the orientation of the grounded part.

```
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.24
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.22
  * Curves 0.6.41

```

**Comment by tibfel** [comment]
@maxwxyz I have tried to investigate further and I have found out that the selection order matters. If you want to apply a distance joint and you first select grounded object and then unconstrained object, it solves correctly. However, when you first select unconstrained object and then grounded object, the grounded object aligns according to the current orientation of unconstrained object. 

See video:
1. Correct selection order : grounded object, then unconstrained object
![CorrectOrder](https://github.com/user-attachments/assets/6a15ea61-38a2-400e-9185-c1f728d5461f)

3. Incorrect selection order: unconstrained object, then grounded object
![IncorrectOrder](https://github.com/user-attachments/assets/b4e4b9e2-f809-4671-b17b-d718d062cae9)

**Comment by maxwxyz** [comment]
@PaddleStroke FYI

**Comment by PaddleStroke** [comment]
Thanks for the report.
There's a big change around the corner in assembly's internal. (https://github.com/FreeCAD/FreeCAD/pull/15384)
So this bug may be gone since this PR is changing just so much.

I will test your file with this new branch and see if the bug is still there. And will address it.

**Comment by luzpaz** [comment]
@PaddleStroke did you get a chance test on new branch ?

**Comment by tibfel** [comment]
I have tested it on the newest build at it does the same strange behaviour as before. You can download Issue.zip file from the first post and try it yourself, too. When I select the grounded part first, the joint solves correctly, but when I select the free part first, then both of them rotate in a weird way. 


OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38467 (Git)
Build type: Release
Branch: main
Hash: 87e73967da5734e100d5ac4b2fd5af1648a02572
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Slovak/Slovakia (sk_SK)
Installed mods: 
  * OpenTheme 2024.8.15
  * Render 2024.8.4
  * sheetmetal 0.4.24

**Comment by tibfel** [comment]
I have also found out that those original parts become black when I insert them into the assembly (maybe some internal colour coding for bad/old files). When I insert other parts created in a newer dev version, the same behaviour persists :(

**Comment by tibfel** [comment]
I can confirm that the issue is fixed in today's version (38506).
