### ISSUE TITLE
ERROR: NO Material was assigned to element

### ISSUE THREAD

**Issue by LHY19990707** [FreeCAD/FreeCAD#15598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi all, 
I am using freecad to calculate the problem of composite materials, using part > split > booleanFragments between the two materials/bodies, but the following error occurs at runtime: ERROR in calinput: no material was assigned to element.

But when I distributed the materials, I assigned the materials to all the bodies, so I'm not quite sure what went wrong. The grid was generated by Netgen.

I have tried to manually add elements without assigned materials by modifying the inp file, but there is no output analysis result.

Any advice would be greatly appreciated! 

### Full version info

```shell
[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Chinese/China (zh_CN)
[/code]
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@LHY19990707 for support please ask on the [forum](https://forum.freecad.org/viewforum.php?style=1&f=18). In general for FEM + Material related issues you want to be using the latest development version where many FEM and Material related advancements have occurred.
