### ISSUE TITLE
Window cuts off section header text with latest weekly release on Dark and Light themes only

### ISSUE THREAD

**Issue by DoubleStrike** [FreeCAD/FreeCAD#15591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The preferences dialog has section headings on the right that cutoff on Windows 10 (using a standard, not a high DPI display).  This is a with a clean from-scratch install.

Look at all the section headings under the word "Navigation" on the right pane.

![image](https://github.com/user-attachments/assets/26bece5e-fdd2-4b8c-9e63-ee7f9a09317c)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DoubleStrike** [comment]
Note that this does not occur with the "Classic" theme, but that theme generally looks pretty ancient, and the newer, nicer looking themes both have this problem.

**Comment by maxwxyz** [comment]
It is not just in the preferences but all dialog windows. Can reproduce on Windows 10 and 11 with HiDPI and normal DPI monitor.
Here e.g. the STEP import dialog:
![grafik](https://github.com/user-attachments/assets/5fb917df-50c9-4558-b8b3-df8ec8fad10f)


```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7

```

**Comment by MisterMakerNL** [comment]
This is some QT bug. Have not seen it in 6 so hooe it's fixed there.

**Comment by luzpaz** [comment]
@maxwxyz can you test on a Qt6 build ?

**Comment by jag45** [comment]
Hi
Try the following in the relevent Dark/Light.css file. It works for me in Windows 10.

![Preferences problem in original Freecad Dark QSS file](https://github.com/user-attachments/assets/f0dbc213-8a8f-4e1f-ac3b-9caceb5c2fc3)

Replace the ex with em as shown here.

![Preferences solution in Freecad Dark QSS file](https://github.com/user-attachments/assets/fddcbdd8-2588-405c-9203-40f237625c8e)

Hopefully ths is ok.

**Comment by MisterMakerNL** [comment]
So I don't have this issue and adding 3em results to this:
![image](https://github.com/user-attachments/assets/a43ce7aa-9ceb-4002-a214-16a2e43c045e)

**Comment by MisterMakerNL** [comment]
@jag45 Could you test if 15px works instead of using 3ex?

**Comment by jag45** [comment]
@MisterMakerNL  I actually set it to 3em which I agree gives too much space.

15px appears to work OK as in this screen shot.
![Preferences screen - 15px](https://github.com/user-attachments/assets/34bb7f03-f8b5-4162-8a05-d1e29cd90b24)

Personally I think it looks better with 20px - gives a bit more seperation from the box above the header

![Preferences screen - 20px](https://github.com/user-attachments/assets/63b5cc20-c0a9-40f6-8c09-fbed1b931918)

Also something like 6ex seems to work nicely. 
Am I right in thinking that as 'ex' is related to the height of the font this would automatically adjust for different font sizes rather than having a fixed pixel size?

**Comment by MisterMakerNL** [comment]
3ex as was should indeed be 3 times the font, but the setting is in groupbox and the text is in the title. So this is probably an issue. Hopefulle setting it to somethine fixed like 18px would solve this issue.

**Comment by jag45** [comment]
OK here is a screenshot with an 18px setting. Looks fine.

![Preferences screen -18px](https://github.com/user-attachments/assets/4854fcba-8ebe-461e-874c-9bc612f10889)

Jon
