### ISSUE TITLE
Stylesheet: Light theme has white borders on menu items

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The latest light theme has white borders around the menu items:
![grafik](https://github.com/user-attachments/assets/ba7b9d9c-24b9-46e9-b1cc-07c7db14ae6a)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
I don't see this in today's Windows weekly. Can you recheck?

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38385 (Git)
Build type: Release
Branch: main
Hash: 58241e027e7187a1ecaeeb75668ef9a497437c68
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

**Comment by maxwxyz** [comment]
Fixed, thanks.
