### ISSUE TITLE
Stylesheet: Rename text input fields cut off text

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Renaming tree view elements cut off text with the default themes (light/dark). Classic theme is ok. This also happens in other views where text is entered (property panel, task panel,..)
macOS: 
![grafik](https://github.com/user-attachments/assets/e17a7e41-0097-4eef-a404-318634462333)

Windows:
![grafik](https://github.com/user-attachments/assets/5721c774-3d30-4875-9d54-726fa4cb0d88)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jag45** [comment]
Hi
I noticed the same thing in the parameter editor as here
![Param Editor bad](https://github.com/user-attachments/assets/c16711e9-ed4a-4fa6-bcb8-847d66f8b0d0)

I have managed to get round it by making the following change to the dark.qss file

![Text clipping problem](https://github.com/user-attachments/assets/f718f8c9-1bec-4514-a4fa-d83deee45151)

Add the 0 into line 

![Text clipping solution](https://github.com/user-attachments/assets/97c62237-f540-48ed-88bd-6774c410b94d)

![Param Editor Sorted](https://github.com/user-attachments/assets/ac38e3c3-01cc-48d0-a4a7-9503a847b609)

Don't know if this is correct way to do it but it seems to work.
Jon

**Comment by MisterMakerNL** [comment]
Hey Jag45
It makes no sense tho, you removed padding from left and right and only do it on top and bottom.
What you are saying is you added padding by removing padding.
To be honest QT doesn't always make sense. ;)

**Comment by jag45** [comment]
Yeah, it does seem strange. What it is doing is the following,

QAbstractItemView QLineEdit {
/*JON padding: 2px; JON*/      This is setting the padding at 2pixels all
round (top, bottom and sides) causing it to shrink the content.
  padding: 0 2px;                       This is now setting the padding to
be 0 pixels top and bottom and 2pixels at the sides.
/*JON ADDED NEXT LINE */
  margin: -2px 0;                       This makes it look better by
setting the margin 2 pixels larger top and bottom thus giving a slight
space top and bottom
}                                                  like this.
[image: image.png]     It doesn't seem to make any difference if you make
it larger than two pixels, there must be some constraint on size elsewhere.
                                                    but you can make the
side padding smaller if you want to.

The box model is explained quite well here:-
https://doc.qt.io/qt-6/stylesheet-customizing.html#the-box-model
and also in examples for padding and border etc.
