### ISSUE TITLE
Stylesheet: FreeCAD Dark "more" arrows on toolbar not visible

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The "more" arrows in the toolbar are not visible until hovered (dark icon on dark background):
![grafik](https://github.com/user-attachments/assets/ab6e637b-1cfe-4ff1-a491-26a6abfeb8ab)

![grafik](https://github.com/user-attachments/assets/2c9cefaa-6a98-46eb-bb0c-00a4e6e55cd4)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by depthoffocus** [comment]
They look a little unusual/low-res on the Mac, too:

<img width="409" alt="Screenshot 2024-07-27 at 00 06 28" src="https://github.com/user-attachments/assets/f32a3413-e15a-4e0d-8e2c-0b39d4a431e2">

OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * ThreadProfile 1.90.0
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * fasteners 0.5.24
  * Curves 0.6.42

**Comment by MisterMakerNL** [comment]
These icons aren't themable, i can only change the background.
Which I did long ago but because of a QT 6 bug it got removed.

**Comment by MisterMakerNL** [comment]
https://forum.qt.io/topic/119988/qtoolbar-extension-button-stylesheet/2
I'll change the background to something light for now./
