### ISSUE TITLE
Stylesheet: Link color not legible with light theme

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The orange link color is not legible with the light theme in the preferences or the property view.
![grafik](https://github.com/user-attachments/assets/6bba0c7b-7e98-4f88-81d8-6f83b4a8c724)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
Should be fixed in stylesheet pr, both theme's ahve blue links, dark a bit lighter and light well darker..duh.
