### ISSUE TITLE
Stylesheet: Addon manager has alternate row coloring and no selection / preselection indication

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The addon manager has an alternate row coloring (white and very dark grey) which has a very high contrast and the dark color has not a good contrast to the black text color. 
The rows have no color indication or highligh for the selected addon or preselection:
![grafik](https://github.com/user-attachments/assets/435fec41-95b2-463b-9e0c-2576c9d1001d)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Still the case in today's Windows weekly.

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38385 (Git)
Build type: Release
Branch: main
Hash: 58241e027e7187a1ecaeeb75668ef9a497437c68
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```
