### ISSUE TITLE
Stylesheet: FreeCAD Light has dark background color on about info

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FreeCAD Light has dark background color on about info:
<img width="620" alt="Bildschirmfoto 2024-07-25 um 19 11 44" src="https://github.com/user-attachments/assets/204e2e12-cb8c-4bf7-94e7-030ae865155b">

### Full version info

```shell
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.24
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.22
  * Curves 0.6.41
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
Fixed by https://github.com/FreeCAD/FreeCAD/pull/15586/commits/00b200517df3b78d6a8782d4e37c34a4c144beac
