### ISSUE TITLE
Non reproducible crash when changing Preferences > Display > Colors > background color

### ISSUE THREAD

**Issue by scandey** [FreeCAD/FreeCAD#15647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

- Open FreeCAD (weekly build for ARM Mac) with no project loaded. 
- Open Preferences > Display > Colors and change Background Color from default of Simple Color to Radial Gradient. 
- Click OK, get crash. Crash log from Console is attached. 

After reloading FreeCAD, I cannot replicate the crash. 

[freecad-2024-07-27-105259.ips.txt](https://github.com/user-attachments/files/16401076/freecad-2024-07-27-105259.ips.txt)

### Full version info

```shell
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * Defeaturing 1.2.2
  * QuickMeasure 2022.10.28
  * Manipulator 1.5.7
  * kicadStepUpMod 11.1.8
  * fasteners 0.5.21
  * sheetmetal 0.4.16
  * Curves 0.6.37
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I cannot reproduce. If you figure out how to reproduce this, please reopen. Could maybe also be a config file conflict.
