### ISSUE TITLE
Measure angular freezes FreeCAD

### ISSUE THREAD

**Issue by Anthony-Gaudino** [FreeCAD/FreeCAD#15677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using measure angular on the two edges shown FreeCAD freezes performing the action:
<img width="212" alt="Screenshot 2024-07-29 at 10 47 09" src="https://github.com/user-attachments/assets/b7d8c54a-b1e9-4a00-87aa-10f072a68799">

[measure_angular.brep.zip](https://github.com/user-attachments/files/16410885/measure_angular.brep.zip)

### Full version info

```shell
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Launcher
  * Nodes 0.1.36
  * InventorLoader 1.4.0
  * Assembly4.backup1719958896.85335 0.50.12 (Disabled)
  * Render.backup1719959316.120863 2024.6.5 (Disabled)
  * woodworking 0.21.2.33771
  * ThreadProfile.backup1719959316.6397839 1.90.0 (Disabled)
  * MeshRemodel.backup1719959315.871541 1.9.23 (Disabled)
  * Silk 0.1.5
  * Defeaturing 1.2.2
  * Pyramids-and-Polyhedrons
  * Curves.backup1719958901.528519 0.6.36 (Disabled)
  * fasteners.backup1719958901.808955 0.5.20 (Disabled)
  * nurbs
  * sheetmetal.backup1719959316.3711638 0.4.21 (Disabled)
  * A2plus.backup1719958896.309429 0.4.64a (Disabled)
  * Manipulator 1.5.7
  * lattice2 1.0.0
  * CurvedShapes 1.0.9
  * toSketch 1.0.1
  * Curves 0.6.42
  * Assembly4 0.50.15
  * Assembly3 0.12.2
```

### Subproject(s) affected?

None

### Anything else?

On 0.22, the measure angular seems to have been replaced by another measure tool, and the issue doesn't happen with it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
> On 0.22, the measure angular seems to have been replaced by another measure tool, and the issue doesn't happen with it.

Closing as a won't fix since Measurements have be re-written for 0.22 by @hlorus
