### ISSUE TITLE
Daily snap builds need to be reenabled

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#15680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It appears that the snap daily builds were disabled yesterday due to the repo not being active in the last 60 days. I'm not sure if this is a new GitHub policy, but daily testers would benefit from reenabling the builds.

![image](https://github.com/user-attachments/assets/2c504c34-9598-4228-a0ce-f11c43080032)

Reporting it here, as issues at https://github.com/FreeCAD/FreeCAD-snap/ don't seem to be monitored

### Full version info

```shell
N/A
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
I;'ll take a look

**Comment by luzpaz** [comment]
Renabled. Thanks for the heads up
