### ISSUE TITLE
Undo/redo doesn't impact display options (view tab)

### ISSUE THREAD

**Issue by nazar-pc** [FreeCAD/FreeCAD#15683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I really tried to find an open issue, but there doesn't seem to be any on this topic.

Basically there are many properties in Display Options (View tab of an element) like visibility and colors, which are persisted in the file like many other things, but changing them doesn't add history entry, so there is no Undo/Redo for them.

If I picked wrong color for something and just want to go back to the previous one, I can't without closing and reopening the file, which may not be an option if I have done other changes since last save point.

### Full version info

```shell
OS: Ubuntu 24.04 LTS (Custom/custom)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38334 (Git) AppImage
Build type: Release
Branch: main
Hash: 61c964caa9a7e5bbc7a8d5f7d8914505d365113e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: C/Default (C) ]
Installed mods: 
  * OpenTheme 2024.7.3
  * fasteners 0.5.25
  * parts_library
  * Curves 0.6.42
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This is by design. But there is the AutoTransactionView [fine-tuning](https://wiki.freecad.org/Fine-tuning) parameter that you can set to change this behavior.
