### ISSUE TITLE
deepinV23   Failed to create OpenGL context for format

### ISSUE THREAD

**Issue by 652436962** [FreeCAD/FreeCAD#15705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

```
 ./FreeCAD-0.21.2-Linux-x86_64.appimage 
FreeCAD 0.21.2, Libs: 0.21.2R33771 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: 无法打开共享对象文件: 没有那个文件或目录 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: 无法打开共享对象文件: 没有那个文件或目录 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: 无法打开共享对象文件: 没有那个文件或目录 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
/tmp/.mount_FreeCAlaX8hh/AppRun: 第 43 行：12306 已放弃               ${MAIN} "$@"
```

### Full version info

```shell
./FreeCAD-0.21.2-Linux-x86_64.appimage 
FreeCAD 0.21.2, Libs: 0.21.2R33771 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: 无法打开共享对象文件: 没有那个文件或目录 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: 无法打开共享对象文件: 没有那个文件或目录 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: 无法打开共享对象文件: 没有那个文件或目录 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
/tmp/.mount_FreeCAlaX8hh/AppRun: 第 43 行：12306 已放弃               ${MAIN} "$@"
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Please elaborate how you triggered this bug 
Can you reproduce this on the development version 
(https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds) ?

**Comment by 652436962** [comment]
> Please elaborate how you triggered this bug Can you reproduce this on the development version (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds) ?

It's  ok   thanks

**Comment by luzpaz** [comment]
@652436962 What do you mean ?

**Comment by jaxter184** [comment]
Hopefully this is beneficial, but I was also running into this error message on stable (0.21.2), but the weekly build loads fine. I unfortunately wasn't able to figure out the exact steps needed to reproduce it, but I'm on Arch Linux with an AMD Radeon GPU, and have had that error since 0.21.0

**Comment by ruffson** [comment]
I have the same issue on Fedora 40 with a freshly downloaded 0.21.2 AppImage. FreeCAD immediately crashes on start.

```
╰─❯ ./FreeCAD-0.21.2-Linux-x86_64.AppImage
FreeCAD 0.21.2, Libs: 0.21.2R33771 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####
  #                    #      # #   #   #
  #     ##  #### ####  #     #   #  #   #
  ####  # # #  # #  #  #     #####  #   #
  #     #   #### ####  #    #     # #   #
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

MESA-LOADER: failed to open radeonsi: /usr/lib64/dri/radeonsi_dri.so: undefined symbol: amdgpu_va_get_start_addr (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open zink: /usr/lib64/dri/zink_dri.so: undefined symbol: amdgpu_va_get_start_addr (search paths /usr/lib64/dri, suffix _dri)
MESA-LOADER: failed to open radeonsi: /usr/lib64/dri/radeonsi_dri.so: undefined symbol: amdgpu_va_get_start_addr (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: undefined symbol: amdgpu_va_get_start_addr (search paths /usr/lib64/dri, suffix _dri)
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
/tmp/.mount_FreeCAemeMte/AppRun: line 43: 125859 Aborted                 (core dumped) ${MAIN} "$@"
```

**Comment by symdeb** [comment]
Why is this closed ? Upgraded to Ubuntu 24.04 and got this error. 0.20 doesn't work anymore. but 0.18 does.

MESA-LOADER: failed to open nouveau: /usr/lib/dri/nouveau_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: nouveau
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 

and per wiki:

sudo apt-get install freecad

no install candidate.

**Comment by luzpaz** [comment]
@symdeb can you try the RC2 AppImage (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/1.0rc2) ?

**Comment by symdeb** [comment]
All these three worked. Without LD_PRELOAD it doesn't.
Using Wayland BTW. 

LD_PRELOAD=/usr/lib/x86_64-linux-gnu/dri/iris_dri.so ./FreeCAD-0.21.2-Linux-x86_64.AppImage
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so ./FreeCAD-0.21.2-Linux-x86_64.AppImage
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/dri/i915_dri.so ./FreeCAD-0.21.2-Linux-x86_64.AppImage

**Comment by symdeb** [comment]
I did follow to install the dialy, but it removed Kicad, which I have no idea how to recover from  to install it again (yet)

ibocct-data-exchange-7.8 : Breaks: libocct-data-exchange-7.6
 libocct-draw-7.8 : Breaks: libocct-draw-7.6
 libocct-foundation-7.8 : Breaks: libocct-foundation-7.6
 libocct-modeling-algorithms-7.8 : Breaks: libocct-modeling-algorithms-7.6
 libocct-modeling-data-7.8 : Breaks: libocct-modeling-data-7.6
 libocct-ocaf-7.8 : Breaks: libocct-ocaf-7.6
 libocct-visualization-7.6 : Depends: occt-misc (= 1:7.6.3+dfsg1-8~ubuntu24.04.1) but 1:7.8.1+dfsg1-3~ubuntu24.04.1 is to be installed
 libocct-visualization-7.8 : Breaks: libocct-visualization-7.6
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by luzpaz** [comment]
@johnocfii or @concretedog not sure if it was one of you who made the obersavtion that kicad and freecad are using different versions of OpenCascade (OCCT). Maybe we should better coordinate with the KiCAD folk about this so users don't run into unnecessary dependency incompatibilities like the above?

**Comment by JohnOCFII** [comment]
> @JohnOCFII or @concretedog not sure if it was one of you who made the obersavtion that kicad and freecad are using different versions of OpenCascade (OCCT). Maybe we should better coordinate with the KiCAD folk about this so users don't run into unnecessary dependency incompatibilities like the above?

Makes sense - but it wasn't me.
