### ISSUE TITLE
Part: Sketcher_NewSketch tool does not have fixed place in Part toolbar

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#15717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Start-up WB is PartDesign.
2. Start FreeCAD.
3. Switch to the Part WB.
4. The Sketcher_NewSketch tool comes 1st in the "Part tools" toolbar.
5. Switch back to PartDesign and then to Part again.
6. Result: Sketcher_NewSketch comes last in the mentioned toolbar.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38375 (Git)
Build type: Release
Branch: main
Hash: fe702349e848571802c01659668cc4bee519f4c6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FEA-eng in your PR https://github.com/FreeCAD/FreeCAD/pull/14318 you've mentioned the same behavior as this issue.
@kadet1090 @Roy-043 did https://github.com/FreeCAD/FreeCAD/pull/15933 maybe solve this too?

**Comment by Roy-043** [comment]
Still present in this version:
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38555 (Git)
Build type: Release
Branch: main
Hash: 73cb5bafe0c32c178d9b594a6ca03124483d305f
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

**Comment by luzpaz** [comment]
@mwganson any chance you can tackle this ?

**Comment by mwganson** [comment]
It appears already to be fixed in the latest main branch.  It's always the last time in the toolbar for me.

**Comment by FEA-eng** [comment]
> It appears already to be fixed in the latest main branch. It's always the last time in the toolbar for me.

I still have the issue. The button should be first as it is initially.

![part_sketch](https://github.com/user-attachments/assets/92bb5eb5-b03c-4a0b-86f1-3e63ca3b9517)

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38843 (Git)
Build type: Release
Branch: main
Hash: d519f24df9931e4a98d19ee39cdcd6124ae6a7bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

**Comment by mwganson** [comment]
I am able to reproduce the issue now.  I will look into it.
