### ISSUE TITLE
Stylesheet: Base plane selection could have more contrast

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#15746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It's not a big deal but I think that the selected base plane could have more contrast in Light and Dark themes.

Classic:
![classic](https://github.com/user-attachments/assets/04de9667-10a1-48fa-89ef-958c0d0a8728)

Light:
![light](https://github.com/user-attachments/assets/87174b96-d627-4d0e-93ec-a038a9a83ed6)

Dark:
![dark](https://github.com/user-attachments/assets/299be9cc-1248-4a35-9a52-09d66b8c6b10)

Maybe different colors should be used. In Dark mode, there's also a problem with the visibility of the selected plane's name.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38385 (Git)
Build type: Release
Branch: main
Hash: 58241e027e7187a1ecaeeb75668ef9a497437c68
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Even worse with simple geometry behind:
<img width="563" alt="Bildschirmfoto 2024-08-04 um 18 11 48" src="https://github.com/user-attachments/assets/d5106870-c6e7-4b64-9c3c-c44b2c7cf7f0">

**Comment by maxwxyz** [comment]
IMO https://github.com/FreeCAD/FreeCAD/pull/16675 will fix this issue too.

**Comment by crazyelectron-io** [comment]
With Freecad 1.0.0RC2 (arm64) on MacOS Sequoia 15.1 using the Light Theme with default settings (except for some font sizes) I can hardly see the difference when selecting a base plane by hovering the mouse over the text label. The blue text and rectangle get ever so slightly lighter blue, but the rectangle is not filled with any visible shade or color.
<img width="520" alt="image" src="https://github.com/user-attachments/assets/543315bb-ced4-4215-81a5-8b4a88a966af">
I selected the XZ plane; can you tell? :o)

**Comment by MisterMakerNL** [comment]
The same selection color is used in sketches which pretty much defined this color. 
It is probably wise to change the default plane color to black in light theme and white in dark theme.
Reasoning is that sketch lines are also white and black in those theme's and making them the same color would solve this conflict.

**Comment by crazyelectron-io** [comment]
So the `Enable preselection` color is used here. I'll experiment a bit.
Thnx

**Comment by MisterMakerNL** [comment]
The general stance here from the @FreeCAD/design-working-group is we want less color in general. I think everyone would agree that if we could remove the blue from the planes it would be the best action to take.

**Comment by crazyelectron-io** [comment]
> The general stance here from the @FreeCAD/design-working-group is we want less color in general.

Fully agree to that! To be honest, I didn't really like the Classic Theme when I started using FreeCAD 0.21 recently.
That's why I start using the Light Theme now that I switched to 1.0.0RC2. Haha, just like the old days when designs where made on paper...

**Comment by MisterMakerNL** [comment]
This pr changed them into green red and blue.
https://github.com/FreeCAD/FreeCAD/pull/16675#issuecomment-2466666599
