### ISSUE TITLE
Stylesheet: Selection color on white has low contrast to the background

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Related to: https://github.com/FreeCAD/FreeCAD/issues/15746 and https://github.com/FreeCAD/FreeCAD/issues/15749

The selection color and preselection color has no great contrast against the fully white background:
<img width="1680" alt="Bildschirmfoto 2024-08-04 um 18 17 26" src="https://github.com/user-attachments/assets/3bc770b4-c8e8-4ef8-be17-8931ae9dcad7">

### Full version info

```shell
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36908 (Git)
Build type: Release
Branch: main
Hash: eb842aadffa2615037c45101ac2575fc79438850
Python 3.11.8, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.30
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.25
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.23
  * Curves 0.6.42
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
same as https://github.com/FreeCAD/FreeCAD/issues/15746#issuecomment-2267593532

**Comment by maxwxyz** [comment]
is it the same color?

**Comment by luzpaz** [comment]
is this a dupe of #15746  ?

**Comment by maxwxyz** [comment]
Seems similar but I guess both will be fixed by the new core datums anyways.
