### ISSUE TITLE
Qt error message on startup macOS

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

On every startup I get this error message, only on macOS:
![grafik](https://github.com/user-attachments/assets/004c150b-7881-4584-88a2-20b431943b94)

@JohnOCFII could you confirm this?

### Full version info

```shell
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.30
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.25
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.23
  * Curves 0.6.42
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by depthoffocus** [comment]
No message on:

OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * ThreadProfile 1.92.0
  * OpenTheme 2024.7.30
  * fasteners 0.5.25
  * Curves 0.6.42

@maxwxyz are you using more than one monitor/display? I ask because:
https://ccp4serv7.rc-harwell.ac.uk/tracker/index.php?func=detail&aid=3045&group_id=21&atid=176

**Comment by maxwxyz** [comment]
Yes, but FreeCAD launches on the MBP monitor.

**Comment by depthoffocus** [comment]
I wonder if you would get the error message with that display turned off, regardless.

I don't think I have a way to test this myself as I have no proper second display, I just tried with an iPad as a Sidecar display but didn't see the error.

**Comment by maxwxyz** [comment]
There is no error when I just use the MBP screen and the external monitor is not plugged in.
When FreeCAD is open and I plug it in, there is also no error, even when opening other files afterwards.

**Comment by depthoffocus** [comment]
I also found this:

**Comment by luzpaz** [comment]
@JohnOCFII do you mind confirming this ?

**Comment by JohnOCFII** [comment]
> @JohnOCFII do you mind confirming this ?

It appears to only be an issue with an external monitor attached to the MacBook Pro.  I have a monitor on a shelf that I can hook up and try later today.

**Comment by JohnOCFII** [comment]
Ok -- I attached a Sceptre 22" (diagonal) monitor via HDMI to my 2021 16" M1 MacBook Pro.  I restarted the Mac.  I then launched FreeCAD to my MacBook Pro built-in display.  No error messages.  I am on macOS 14.6 where as I noted Max on 13.6.7 in case that is relevant. 

<img width="499" alt="Screenshot 2024-08-07 at 10 56 33 AM" src="https://github.com/user-attachments/assets/9f17e9ee-520e-4df8-9acc-c4ab854f1050">

```
OS: macOS 14.6
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * OpenTheme 2024.7.30
```

**Comment by luzpaz** [comment]
Thanks JohnOCFII :+1:   
CC @ipatch do you have an external monitor you could test with ? TIA

**Comment by ipatch** [comment]
unfortunately i do not have a way of testing this issue. 🤦‍♂️

**Comment by goleon69** [comment]
Not sure helps, I downloaded the 38506 and tried to start with a Mac Pro from 2016, unfortunately it doesn't start as require the MacOs version that cannot be installed on this Mac .
<img width="290" alt="Screenshot 2024-08-25 at 11 30 06" src="https://github.com/user-attachments/assets/3e6776b7-e9d0-4602-a7b5-db9b47aa06cc">

**Comment by luzpaz** [comment]
@oursland would you have a moment to reproduce ?

**Comment by goleon69** [comment]
Yes, how can I help?

**Comment by oursland** [comment]
@luzpaz I am unsure which issue you are asking to reproduce.  @goleon69's issue is unrelated to this bug.

I cannot reproduce @maxwxyz's message with multiple monitor's attached.

    OS: macOS 14.6.1
    Word size of FreeCAD: 64-bit
    Version: 0.22.0dev.38498 (Git)
    Build type: Release
    Branch: main
    Hash: 7e311ed4b96299c8b9909d86cda2410a53cbd498
    Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
    Locale: English/United States (en_US)
    Installed mods: 
      * OpenTheme 2024.8.10
      * A2plus 0.4.65
      * kicadStepUpMod 11.2.7
      * fasteners 0.5.26
      * freecad.cross 0.4.0
      * Assembly4 0.50.15

![image](https://github.com/user-attachments/assets/b7adb28d-c16e-40d2-9c9b-d39cb2abfe50)

**Comment by luzpaz** [comment]
@oursland apologies, yes I meant max's original ticket which you answered. It seems you can't reproduce.

**Comment by oursland** [comment]
@goleon69 The macOS version issue is being tracked as https://github.com/FreeCAD/FreeCAD-Bundle/issues/294.

**Comment by goleon69** [comment]
Thanks guys, indeed the problem is related to the opening with an older
version of the Mac OS. Unfortunately I have the old 0.22 de. That was
working  and now isn’t 🤔

**Comment by maxwxyz** [comment]
Still have the issue on macOS 13.7.1 (latest I can get on Intel MBP). Closing this as no one can reproduce though.
