### ISSUE TITLE
Stylesheet: Different selection colors in tree view for active document, part and body

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There seems to be a different background color for active document, active part and active body in FreeCAD Classic:

<img width="423" alt="Bildschirmfoto 2024-08-06 um 20 23 50" src="https://github.com/user-attachments/assets/0fd26643-aa47-4501-bcda-02c03ffeba54">

### Full version info

```shell
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.30
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.25
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.23
  * Curves 0.6.42
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
owh woops wrong issues.
Ah well this one seems to be fixed in my qt build, but not in my older QT 6 build...
