### ISSUE TITLE
Stylesheet: Classic has dark background in task dialog

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#15831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With FreeCAD Classic some element selection boxes have a dark background in the task dialog, compared to the other light shades. Here an example of Part Scale:
<img width="649" alt="Bildschirmfoto 2024-08-08 um 20 34 50" src="https://github.com/user-attachments/assets/b31f4511-d003-4c28-878b-138d64ba21b6">

### Full version info

```shell
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.30
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.25
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.23
  * Curves 0.6.42
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
is fixed

**Comment by luzpaz** [comment]
@MisterMakerNL if possible, would you link to the PR or commit that provides the fix ? Or you can even auto-remotely close tickets by referencing them in your commit messages https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue  
(Apologies if you already know about this feature)
