### ISSUE TITLE
Fillet at corner is malformed on specific radius

### ISSUE THREAD

**Issue by hasecilu** [FreeCAD/FreeCAD#15840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Shape is malformed when trying to make an $8 [mm]$ fillet at a corner.

4 corners were selected but only one went bad, specifically at $8 mm$, even entering $8.0001$ fix the geometry.

**Workaround**: don't use $8mm$.

**Edit**: Starting again from previous version of file doing same operations in same order now corner fillet is OK. Could be hard to reproduce/find what causes problem.

### Full version info

```shell
OS: Arch Linux (Hyprland/hyprland)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git) AppImage
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * ThreadProfile 1.91.0
  * FreeCAD-Movie 2024.2.15
  * freecad.gears 1.2.0
  * PieMenu 1.7.6
  * freecad_metal_workbench 0.0.1
  * Ship 2022.4.11
  * OpenTheme 2024.7.30
  * FreeGrid 2.0.0
  * FreeCAD-Reinforcement
  * Defeaturing 1.2.2
  * FreeCAD_SheetMetal 0.4.16
  * FreeCAD-Pyramids-and-Polyhedrons
  * yaml-workspace 0.1.2
  * woodworking 0.21.2.33771
  * Assembly4 0.50.10
  * FastenersWB 0.5.25
  * lattice2 1.0.0
  * Rocket 3.3.0
  * dodo 1.0.1
  * FreeCAD-motion
  * Profiles 0.0.1
  * Alternate_OpenSCAD 1.0.0
  * osh-autodoc-workbench 0.2.3
  * CfdOF 1.27.4
  * A2plus 0.4.64a
  * kicadStepUpMod 11.2.4
  * frame 0.1.1
  * FreeCAD_assembly3 0.12.2
  * Render 2024.7.4
```

### Subproject(s) affected?

PartDesign

### Anything else?

Running _Part_CheckGeometry_ don't trigger errors or warnings.
![image](https://github.com/user-attachments/assets/51fbf260-971b-4d53-a744-cd839f24ea83)
File: [Bad_corner_fillet.zip](https://github.com/user-attachments/files/16565606/Bad_corner_fillet.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
If it cannot be reproduced it is hard to narrow this down. I'll close this then.
Feel free to reopen when you can reproduce this again. If possible, record a macro when recreating this.
