### ISSUE TITLE
Assembly4 saving data

### ISSUE THREAD

**Issue by ukrcr** [FreeCAD/FreeCAD#15861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

11:42:24  Initializing Assembly4 workbench (0.50.15) ............................. done.
11:42:42  Traceback (most recent call last):
11:42:42    File "/Users/robertcrane/Library/Application Support/FreeCAD/Mod/Assembly4/./AnimationLib.py", line 496, in onSave
11:42:42      import AnimationExportLib
11:42:42    File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
11:42:42      return original_import(name, *args, **kwargs)
11:42:42    File "/Users/robertcrane/Library/Application Support/FreeCAD/Mod/Assembly4/./AnimationExportLib.py", line 13, in <module>
11:42:42      from PIL.ImageQt import ImageQt
11:42:42  ImportError: cannot import name 'ImageQt' from 'PIL.ImageQt' (/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/PIL/ImageQt.py)

### Full version info

```shell
[code]
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Movie 2024.2.15
  * AnimationFreeCAD 1.0.0
  * Render 2024.8.4
  * A2plus 0.4.65
  * fasteners 0.5.26
  * 3D_Printing_Tools
  * ExplodedAssembly
  * Help 1.0.3
  * Curves 0.6.43
  * Assembly4 0.50.15
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Hi @ukrcr  
Assembly4 is an external FreeCAD addon. Bugs related to it should be reported in its exclusive repository: https://github.com/Zolko-123/FreeCAD_Assembly4  

Closing.
