### ISSUE TITLE
Freecad 0.220dev curvesworkbench

### ISSUE THREAD

**Issue by SEVolker0815** [FreeCAD/FreeCAD#15866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Curves workbench v.06.40
Sketch on surface doesn't work

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38429 (Git)
Build type: Release
Branch: main
Hash: 362cf1c80edb89957d81c0dbe6e50ce35daaa6db
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * A2plus 0.4.65
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * QuickMeasure 2022.10.28
  * sheetmetal 0.4.23
  * slic3r-tools
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please pen an issue in the Curves WB repo: https://github.com/tomate44/CurvesWB/tree/master/freecad/Curves
