### ISSUE TITLE
CAM: Error on CNC file import pre-processor selection + unclear UI

### ISSUE THREAD

**Issue by alexfacciorusso** [FreeCAD/FreeCAD#15909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The GCode import function introduced by https://tracker.freecad.org/view.php?id=3455 is not working. The GCode is not pre-processed properly and an error is displaying when trying to select GCode preprocessor from the dialog. 

In addition, the dialog is not very clear to the final user and contains "example" preprocessors in the release folder.

When trying to import/open GCode and pre-process it via one of the pre-defined pre-processors, an error is 
displayed.

### Full version info

```shell
OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38459 (Git)
Build type: Release
Branch: main
Hash: 58729b3ab0060a1525fc45c87beabfd4b3d5e22e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
```

### Subproject(s) affected?

CAM

### Anything else?

https://tracker.freecad.org/view.php?id=3455

### Step 1 - open the file
![image](https://github.com/user-attachments/assets/1fb09938-dc05-4189-86e3-c0b33ef2eb3b)

### Step 2 - dialog displayed

You can see the dialog having code-friendly names instead of user-friendly ones. Also, no description on what each script does.

![image](https://github.com/user-attachments/assets/623e777b-ab36-483e-89df-da2540566fe7)

### Step 3 - select gcode_pre

![image](https://github.com/user-attachments/assets/515e485e-74a4-4d3d-98d7-24cfffaef402)

### Step 4 - Code not imported and error displayed

![image](https://github.com/user-attachments/assets/6bd29b60-9b79-4356-ad5c-ede0b6d3b717)

```
11:11:14  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\freecad\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'ModuleNotFoundError'>: No module named 'gcode_pre'
11:11:14  pyException: Traceback (most recent call last):
  File "<string>", line 5, in <module>
<class 'RuntimeError'>: No module named 'gcode_pre'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Need full [About](https://wiki.freecad.org/About) info please

**Comment by alexfacciorusso** [comment]
> Need full [About](https://wiki.freecad.org/About) info please

Added to the main bug data
