### ISSUE TITLE
save as always adds *.FCStd, even if it already has the correct extension

### ISSUE THREAD

**Issue by Panda631** [FreeCAD/FreeCAD#15908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Just a little something.
Every “Save as” action adds its FCStd. extension, no matter if it already has it.
This leads to names like “noname.FCStd.FCStd.FCStd”.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38467 (Git)
Build type: Release
Branch: main
Hash: 87e73967da5734e100d5ac4b2fd5af1648a02572
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * EM 2.1.1
  * fasteners 0.5.21
  * Help 1.0.3
  * kicadStepUpMod 10.17.1
  * Pyramids-and-Polyhedrons
  * Render 2024.1.23
  * sheetmetal 0.2.61
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Related: #15838

Forum thread: https://forum.freecad.org/viewtopic.php?t=89791

@maxwxyz This might be blocker, right?
