### ISSUE TITLE
Measurment: Can't measure center to center

### ISSUE THREAD

**Issue by macdroid53** [FreeCAD/FreeCAD#15916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Can't measure the center to center distance of circles/shafts, or center to edge, etc

### Full version info

```shell
0.22
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Also kind of a duplicate of https://github.com/FreeCAD/FreeCAD/issues/13708
Maybe add all relevant modes there in the comment.
