### ISSUE TITLE
Measurement: user selectable snapping

### ISSUE THREAD

**Issue by macdroid53** [FreeCAD/FreeCAD#15917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The tool needs to have user selectable snapping for center points, midpoint, end vertex, etc.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by obelisk79** [comment]
To add some detail to this issue: The measurement utility lacks the ability to snap measurements to key points between certain geometry elements. A key problem is the ability to measure center-to-center between circles/holes. An example of a viable approach to managing this is demonstrated by the "manipulator" workbench addon.

**Comment by macdroid53** [comment]
As well as the Manipulator workbench Caliper tool, other examples exist in Assembly4 and Quick Measure.

**Comment by maxwxyz** [comment]
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13708

**Comment by macdroid53** [comment]
It was said that the lacking functionality of this tool had not been reported.

As noted above, it has been, in #13708  and in that issue there is a link to the forum thread where these were reported.
