### ISSUE TITLE
[TNP] Breaks on a simple operation

### ISSUE THREAD

**Issue by shaise** [FreeCAD/FreeCAD#15969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is a TNP issue I was experiencing also in realthunder's branch, so I first placed an issue there.
In response, @realthunder have made a fix to the TopoShape sources. See [here](https://github.com/realthunder/FreeCAD/commit/aa1aa00ae4784ebfae85407e8bdc932c456858cf)
Reproducing the problem is as follows:
Load the attached file, click the 'Bend' feature in the tree, and change length to 15. This breaks the model.

[Std-test-sm.zip](https://github.com/user-attachments/files/16661998/Std-test-sm.zip)

Hopefully realthunder's fix will work here as well.

EDIT: this is a very simple change, in Ver21 freecad, this works without a problem since it does not disturb the edges/faces numbering. 

shai

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38429 (Git)
Build type: Release
Branch: main
Hash: 362cf1c80edb89957d81c0dbe6e50ce35daaa6db
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * BIM_Workbench 2021.12.0
  * fasteners 0.5.27
  * Manipulator 1.5.7 (Disabled)
  * OpenTheme 2024.7.3
  * PieMenu 1.7.4 (Disabled)
  * Render 2024.6.5
  * SelectorToolbar (Disabled)
  * sheetmetal 0.4.24
  * TabBar (Disabled)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@bgbsww FYI, any chance this works?

**Comment by bgbsww** [comment]
Thanks!  The corresponding refactored code is in TopoShapeMapper.cpp and refactored into just one ShapeMapper::populate.  After a recalculate ( hasher table didn't read cleanly - you can see that error ), this fix appears to solve the problem.

**Comment by shaise** [comment]
Thank you!

**Comment by shaise** [comment]
@chennes how do i reopen it? it seems the fix did not work. 
The operation here is very simple that used to work on v21 but breaks now.

**Comment by maxwxyz** [comment]
@shaise done

**Comment by bgbsww** [comment]
Open that file.   Recompute the Fillet and the Bend.  Recompute the file.

No remaining bug.   ( Or, you'l let me know :)

**Comment by bgbsww** [comment]
Aha!  That makes sense, can duplicate, let's see if can fix.  Also, turns out one of the changes from that patch was hiding in an include file.

**Comment by bgbsww** [comment]
@shaise can you confirm this one gets it?  I think following that video it is okay, but not sure.

**Comment by shaise** [comment]
@bgbsww ,
Sorry, I have copied the revised h file, made a clean build, yet repeating the steps in the video I still get an error:
```
20:37:05  <PropertyLinks> PropertyLinks.cpp(463): Unnamed#Fillet.Base missing element reference Unnamed#Bend ;Edge52;D6d8;:H:5,E;:H,E.Edge62
20:37:05  <Exception> FeatureDressUp.cpp(209): Invalid edge link: ;Edge52;D6d8;:H:5,E;:H,E.Edge62
20:37:05  Fillet: Invalid edge link: ;Edge52;D6d8;:H:5,E;:H,E.Edge62
```

**Comment by bgbsww** [comment]
I just tried it again, click for click with no failure on this local build:

OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38501 (Git)
Build type: Debug
Branch: bgbsww-toponamingRevolution
Hash: 4ea2a0162d2acf74679864d2ce865e7fdd672f1b
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Locale: English/United States (en_US)
Installed mods: 
  * sheetmetal 0.4.24
  * Curves 0.6.45
  * DynamicData 2.62.0
  * BIM021 2021.12.0
  * parts_library

But this daily fails:

OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38555 (Git)
Build type: Release
Branch: main
Hash: 73cb5bafe0c32c178d9b594a6ca03124483d305f
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Locale: English/United States (en_US)
Installed mods: 
  * sheetmetal 0.4.24
  * Curves 0.6.45
  * DynamicData 2.62.0
  * BIM021 2021.12.0
  * parts_library

I could have selected the edges for the fillet in a different order between the two tries...  doesn't seem to be it.  Let me try a local release build.

**Comment by shaise** [comment]
Sorry for causing so much issues....

**Comment by bgbsww** [comment]
This will be a good find eventually.  The subtle ones always are, thanks for hanging in with the bug reports.

**Comment by bgbsww** [comment]
@shaise can you please double check that you are using a release version of the LS3 with the changes in it?  I just want to rule out this being a debug build only fix on all variants.

**Comment by shaise** [comment]
@bgbsww , To tell you the truth, I did not check if the fix really worked on LS3, I just counted on realthunder that he fixed it. I wanted to test it but I dont know how to since I did not find where are the LS3 weekly builds. Do you know where I can find it?

**Comment by bgbsww** [comment]
@shaise  <laugh>  I could not find such a thing either, I might have to make my own build to test the hypothesis then.

**Comment by shaise** [comment]
Closing as complete
