### ISSUE TITLE
Draft: Error message when trying to change line width

### ISSUE THREAD

**Issue by APOS80** [FreeCAD/FreeCAD#16029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Klicking to set line width results in error message.

![image](https://github.com/user-attachments/assets/3a76b0ce-2ec8-4485-8db3-28c3a2e4635f)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Swedish/Sweden (sv_SE)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
could you try this in the weekly build https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by Roy-043** [comment]
Under normal circumstances it should be impossible to start Draft_SetStyle if another task panel is still active. So steps to reproduce are essential here.

**Comment by APOS80** [comment]
It’s strange, I don’t get it now. 

Don’t know why.

**Comment by maxwxyz** [comment]
I'll close this issue then. Please comment if you are able to reproduce it again and we can reopen
