### ISSUE TITLE
Save As and Export keep adding new extensions to the filenames

### ISSUE THREAD

**Issue by theosib** [FreeCAD/FreeCAD#16031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Say I have filename "knotplate3.FCStd".  If I go to File > Save As, the filename it defaults to is "knotplate3.FCStd.FCStd".

There's a similar problem for Export. I exported first as "knotplate3-Compound.step", but the export didn't work right in my slicer, so I went back to export and changed the export type to "stl", and the filename it defaulted to was "knotplate3-Compound.step.stl", rather than the "knotplate3-Compound.stl" that I would have expected.

This seems to be a very recent regression, since I didn't notice this in older dev builds.

### Full version info

```shell
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38459 (Git)
Build type: Release
Branch: main
Hash: 58729b3ab0060a1525fc45c87beabfd4b3d5e22e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US) [ OS: C/Default (C) ]
Installed mods: 
  * Curves 0.6.44
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Should be fixed in 8913b84f60a7cb43d9f945fdd183dc70c9f94303
