### ISSUE TITLE
Sheetmetal add base shape uses Qpushbuttons as Qradiobuttons

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD#16032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The sheet metal add base shape uses a grid of Qpushbuttons as Radiobuttons.
This conflicts with the stylesheets since it is recommended to give pushbuttons a minimum width.
![image](https://github.com/user-attachments/assets/c832e2ca-fe43-4c72-af01-18bdc4cd10c8)
It is also just weird once you see it :)

### Full version info

```shell
NA
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Move to https://github.com/shaise/FreeCAD_SheetMetal ?
