### ISSUE TITLE
PartDesign: Issue when changing Pad from dimension to two dimensions

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#16072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating a pad, checking "symmetrical" and then changing type from dimension to two dimension, changing one of both dimensions still changes them both symmetrical.
You have to go back to dimension, uncheck symmetrical and then go back to two lengths.

![grafik](https://github.com/user-attachments/assets/fd5492ab-fab3-417c-8b0a-08f1ed2b4c89)

Demo:

https://github.com/user-attachments/assets/608525f9-c416-4d39-bed3-f46b560813c5

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38506 (Git)
Build type: Release
Branch: main
Hash: ebf02483af225b502fccfa7111499dfde33999fd
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.42
  * fasteners 0.5.25
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FlachyJoe FYI

**Comment by FlachyJoe** [comment]
@maxwxyz it's an UI issue, I can't help.

**Comment by maxwxyz** [comment]
@kadet1090 maybe?

**Comment by Syres916** [comment]
@maxwxyz I can't believe this is too difficult but what I need to test is whether Pocket, etc need fixing as well.
it should be as simple as adding `ui->checkBoxMidplane>setChecked(false);` to each case mode where appropriate. It'll be tomorrow before I can do some proper testing and submit a PR.

**Comment by maxwxyz** [comment]
Added the blocker label as this is a regression and could break old models as mentioned in
https://github.com/FreeCAD/FreeCAD/issues/16868

**Comment by maxwxyz** [comment]
@chennes who could help out here?

**Comment by maxwxyz** [comment]
@FlachyJoe do you want to take a look at this?

**Comment by kadet1090** [comment]
I'll tackle that, should be done this week

**Comment by chennes** [comment]
Noting that @kadet1090 is eligible to claim the bounty from the FPA. To claim, please send an email to fpa@freecad.org referencing this issue, and your preferred method of payment.
