### ISSUE TITLE
PartDesign: Malformed Helices

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#16081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am experiencing malformed addictive Helices. I found some issues reported but I am not sure if they are related so I am creating the new one.

I made a file with examples to test and show what I am experiencing. It is attached here.
[additive_helix_tests.zip](https://github.com/user-attachments/files/16755105/additive_helix_tests.zip)

There is a cylinder with diameter 50 mm (radius 25 mm) and a Sketch of a triangle with the thread profile on ZX axis.

When the thread profile is placed on the external face of a cylinder, the thread is malformed and does not appear. 

![image](https://github.com/user-attachments/assets/69490cde-34ab-402d-af07-c856a60edc8c)

In the past it could be fixed by placing this thread on the `radius - 0.01`. But now, this results on a broken operation with the message `Removing splitter failed`.

![image](https://github.com/user-attachments/assets/debafdbf-d76c-4e00-b6ab-31c534c2dfc2)

Modifying the Sketch a bit, making the triangle on Z=1 instead of Z=0, (while the keeping the Attachment offset Z=0), results on a malformed operation which kind of works, but it creates the helix upwards, AND a bit downwards.

![image](https://github.com/user-attachments/assets/a38cba7d-cdcc-41e2-be15-e041146dfd2b)

The only way to make a valid additive thread is to change the attachment offset to z > 0 (in this example of course, since the cylinder grows from Z=0 to Z=20) and also place the thread profile on the distance <= external wall radius.

![image](https://github.com/user-attachments/assets/abc57dab-14c4-4694-b80a-4d0a2a7b62ec)

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38506 (Git) AppImage
Build type: Release
Branch: main
Hash: ebf02483af225b502fccfa7111499dfde33999fd
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leoheck** [comment]
However here, in this second example, where I have 2 stacked cylinders (lets say a bottle with a neck), I could not make it work at all. When the height of the profile is set within the Sketch, the operation does not render anything but works. When the Attachment offset is set and the profile is sketch on Z=0. The operation fails with the `Removing splitter failed.` issue. 

[additive_thread_neck_failed.zip](https://github.com/user-attachments/files/16755271/additive_thread_neck_failed.zip)

**Comment by leoheck** [comment]
Ah, there is one new weekly from today. Well, the same issues persist on this one too. 
```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git) AppImage
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

**Comment by maxwxyz** [comment]
@FlachyJoe another HELLix
maybe related https://github.com/FreeCAD/FreeCAD/issues/15353

**Comment by FlachyJoe** [comment]
@leoheck do you know if it worked a day? Have you test with 0.21?

**Comment by leoheck** [comment]
@FlachyJoe I ported the fcstd file with a  existing macro to 0.21 and the first file behaves equal with the same issues. However the second file where the Sketch is not close to Z=0 it works fine on 0.21 while on 0.22 it doesn't.

**Comment by leoheck** [comment]
Even the old way of creating a thread with a Thread profile and a Part Helix does not work.
[thread_part_helix.zip](https://github.com/user-attachments/files/16767430/thread_part_helix.zip)

![image](https://github.com/user-attachments/assets/62e08d7c-9d93-4b53-858f-ea2ecce1cd80)

**Comment by leoheck** [comment]
In this example I made the thread in a Body, and using the Clone I tried to add a cylinder.
The operation fails if the Cylinder grows up from z=0, but it works if it grows symmetrically. 

[thread_thread_body.zip](https://github.com/user-attachments/files/16767604/thread_thread_body.zip)

![image](https://github.com/user-attachments/assets/cec066ac-4b89-4a23-87cb-566db304000b)

Here the thread and the external face of the cylinder are placed at the same distance (25 mm)

**Comment by leoheck** [comment]
Another try.

Creating the Thread as a Body, and then fusing it with the Neck as another Body with the Part Design Boolean.
This does not work either. 

[thread_part_design_workbench_boolean.zip](https://github.com/user-attachments/files/16767753/thread_part_design_workbench_boolean.zip)

![image](https://github.com/user-attachments/assets/be5faf11-f9c6-4e53-b7a7-400bad172184)

**Comment by leoheck** [comment]
I could find a way to work around this issue. 

I could make a Cylinder with the Thread (following the known tricks - overlapping thread profile with the cylinder, and also moving it off the z=0) an then, using this to make a Part Design Boolean fusion with another Body, this way you can place the Thread where you want. 

[thread_workaround.zip](https://github.com/user-attachments/files/16786803/thread_workaround.zip)

**Comment by alfrix** [comment]
if i revert 74e5c3fafba7b0307c6b75e57ef648baae32f971
the "broken" model from OP starts working again
calling the autor @FlachyJoe to see if he can help

**Comment by leoheck** [comment]
I could fix my threads buy intercepting more material with the base cylinder. on my examples, the thread profile and the cylinder has a bit of overlap (0.1). Maybe this is not always enough.

**Comment by FlachyJoe** [comment]
Your broken case is fixed by switching its Refine property to False (it fails to remove the single vertex on the cylinder bottom).
The third malformed is fixed by #16226
Aren't the other cases common boolean failure with coincidence with face or seam edge?

**Comment by leoheck** [comment]
> Your broken case is fixed by switching its Refine property to False 

Hm, interesting, I did not think about this since now the default is true. 
That is a good observation.

**Comment by leoheck** [comment]
Here is an example where I could fix my issues above, but there is two other examples where one is broken and one is malformed

[additive_helix_tests_2.zip](https://github.com/user-attachments/files/16986952/additive_helix_tests_2.zip)


New problems arrise when the thread is put on a bottle neck.
![image](https://github.com/user-attachments/assets/dd13e885-ebad-40dc-84b2-a65910d81681)

**Comment by FlachyJoe** [comment]
No problem here
![image](https://github.com/user-attachments/assets/2bb3fa4a-2c70-4d36-858b-b3bea5ce21dc)

> OS: Debian GNU/Linux trixie/sid (XFCE/xfce)
> Word size of FreeCAD: 64-bit
> Version: **1.0.0RC1.38702** (Git)
> Build type: Release
> Branch: main
> Python 3.12.6, Qt 6.6.2, Coin 4.0.2, Vtk 9.3.0, **OCC 7.8.2.dev**
> Locale: English/United States (en_US) [ OS: French/France (fr_FR) ]
> Stylesheet/Theme/QtStyle: /Classic/

Please give your system information.

**Comment by mendberg** [comment]
1.0.0RC2 still has issues w/ additive helix:

1. sketch a centered circle on XY plane, diameter 60 mm
![image](https://github.com/user-attachments/assets/fd829315-5cf4-4aca-8d93-34ac897e1e44)

2. pad it to a height of 70 
![image](https://github.com/user-attachments/assets/3ba7445a-48f9-4834-a880-09c7d1b3831b)

3. sketch a circle on XZ plane, 30 mm on X, diameter 1 mm
![image](https://github.com/user-attachments/assets/626f1b5b-8f20-4532-ac81-4481a16ff248)

4. take second sketch and make it an additive helix with any parameters, hit [OK] and **FAIL:** "Removing splitter failed"
![image](https://github.com/user-attachments/assets/85d93a91-3ef5-45fa-ae05-8d9001ec76f4)

**Comment by FlachyJoe** [comment]
The **removing splitter** error come from the refinement, please disable the Refine property.

**Comment by mendberg** [comment]
I read about that but did only turn off refinement for the pad. I had to disable refinement globally in Preferences/Part Design/General.

Thanks for the hint.

**Comment by leoheck** [comment]
> The **removing splitter** error come from the refinement, please disable the Refine property.

Can this feature defaults to `Refine = False`?

**Comment by FlachyJoe** [comment]
@leoheck IMHO the auto-refine preference should be removed and the user should choose when he wants to refine.

Refinement could also emit a warning and not an error it could be considered not to be a critical feature.

**Comment by leoheck** [comment]
I see. It was like that in the past. They used to say it was due to the performance. But in this case it is about the features not being able to resolve well. I was a bit of surprised they changed this for this 1.0 version.
