### ISSUE TITLE
[Materials] Prefs - User directory cannot be set via prefs gui.

### ISSUE THREAD

**Issue by spanner888** [FreeCAD/FreeCAD#16098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Attempting to set this directory in FC materials prefs, does open a file browser dialog and allows user to navigate directories, but you come to a dead end and cannot actually set the directory, see image & note the disabled Open button.

![Materials-prefs-UserDirectory](https://github.com/user-attachments/assets/f8689b7a-ead8-4356-908e-1829b07ae2c7)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git)
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Australia (en_AU)
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
This should be an easy fix, just needs:

```
            <property name="mode">
             <enum>Gui::FileChooser::Directory</enum>
            </property>
```

adding to the UI file, I'll test and submit a PR when I've proven it's working.
