### ISSUE TITLE
BIM: Obj importer is missing function

### ISSUE THREAD

**Issue by NomAnor** [FreeCAD/FreeCAD#16137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I tried to import an obj file with the BIM importer, but it does not work, because the `pythonopen` function gets not defined on my system:
https://github.com/FreeCAD/FreeCAD/blob/73cb5bafe0c32c178d9b594a6ca03124483d305f/src/Mod/BIM/importers/importOBJ.py#L309

It is conditionally defined here:
https://github.com/FreeCAD/FreeCAD/blob/73cb5bafe0c32c178d9b594a6ca03124483d305f/src/Mod/BIM/importers/importOBJ.py#L53-L54

Changing the call to `builtins.open` and importing the `builtins` module fixed it. Not sure why that if statement is there, there is no fallback and it is cleaner to use the builtins module directly.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38513 (Git)
Build type: Release
Branch: main
Hash: 7c797b5a10c19ae55e317c4ff9a02823a4b4dc0b
Python 3.12.5, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.1, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.62.0
  * Assembly3.backup1715897154.0970206 0.11.3 (Disabled)
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.2.0
  * fasteners 0.5.27
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@Roy-043 do you mind weighing-in ?
