### ISSUE TITLE
CAM: LeadInOut does not work with Slot

### ISSUE THREAD

**Issue by firebladed** [FreeCAD/FreeCAD#16142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When trying to add a [leadinout ](https://wiki.freecad.org/CAM_DressupLeadInOut )to a [Slot](https://wiki.freecad.org/CAM_Slot) operation,  get an error and no path is generated

1. Create Object, needing slot
2. Create Cam Job
3. Create Slot Operation ( from bottom of slot) [experimental enabled]
4. Add LeadInOut (Menu->Path->Path Dressup->LeadInOut)
5. Get Error 

Error
```
17:38:57  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.21\Mod\Path\PathPythonGui\simple_edit_panel.py", line 100, in clicked
    self.updateModel()
  File "C:\Program Files\FreeCAD 0.21\Mod\Path\PathPythonGui\simple_edit_panel.py", line 129, in updateModel
    self.obj.Proxy.execute(self.obj)
  File "C:\Program Files\FreeCAD 0.21\Mod\Path\Path\Dressup\Gui\LeadInOut.py", line 181, in execute
    obj.Path = self.generateLeadInOutCurve(obj)
  File "C:\Program Files\FreeCAD 0.21\Mod\Path\Path\Dressup\Gui\LeadInOut.py", line 549, in generateLeadInOutCurve
    and curCommand.z < currLocation["Z"]
<class 'TypeError'>: '<' not supported between instances of 'NoneType' and 'float'
```

Slot operation before add LeadinOut
![Slot operation](https://github.com/user-attachments/assets/005ad6e5-f3c4-4bcc-8572-f59f9d82db2f)

attached example [Freecad CAM Slot LeadInOut Bug.zip](https://github.com/user-attachments/files/16802734/Freecad.CAM.Slot.LeadInOut.Bug.zip)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.65
  * Assembly4 0.50.15
  * Assembly4.backup1714492159.8689911 (Disabled)
  * boltsfc 2022.11.5
  * btl 0.9.9
  * EM 2.1.1
  * fasteners 0.5.25
  * Help 1.0.3
  * kicadStepUpMod
  * OpticsWorkbench 1.0.18
  * OpticsWorkbench.backup1714492175.9109938 (Disabled)
[/code]
```

### Subproject(s) affected?

CAM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by firebladed** [comment]
Seems Possibly Related #9936

**Comment by maxwxyz** [comment]
Could you please test this in the dev version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by firebladed** [comment]
have checked dev version and this appears to have been corrected
