### ISSUE TITLE
Stylesheet: Change to classic does not set "No stylesheet" / Line between views.

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#16150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

@obelisk79 as  requested on Discord, here the issue:

When changing to the Classic theme from a different theme, the stylesheet is not reset to "no stylesheet".
![grafik](https://github.com/user-attachments/assets/d371717b-dcdf-4fa2-a16f-39894a836024)
![grafik](https://github.com/user-attachments/assets/a6aa4321-9202-445f-8f0e-318efaa7d32b)

When changing to no stylesheet, there is a line between the tree view and property view when using transparent overlays, only when they are set as combined (=default) in the preferences. When set to separate, there is no line between the views.
@kadet1090 FYI

![grafik](https://github.com/user-attachments/assets/03b6ff23-e29c-4939-93ac-895b660b2913)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git)
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.27.4
  * Curves 0.6.42
  * dodo 1.0.1
  * fasteners 0.5.25
  * fasteners.backup1721936159.7542229 0.5.24 (Disabled)
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * OpenTheme 2024.7.30
  * OpticsWorkbench 1.0.19
  * Rocket 3.3.0
  * sheetmetal 0.4.23
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by obelisk79** [comment]
So, conducting a local test, when I set FreeCAD Classic via preferences, it properly resets FreeCAD to no stylesheet. I'm actually unable to recreate the issue you are seeing on my Linux machine.

**Comment by maxwxyz** [comment]
@MisterMakerNL can you confirm on Windows?

**Comment by Syres916** [comment]
@obelisk79 try cutting the post.FCMacro down to just the first 8 lines.

**Comment by obelisk79** [comment]
> @obelisk79 try cutting the post.FCMacro down to just the first 8 lines.

Thanks for the hint. I actually found removing the macro entirely provided satisfactory results. If others are able to confirm, I'll submit a PR to remove it later today.

**Comment by JohnOCFII** [comment]
> @JohnOCFII could you confirm this in the latest weekly?

I find testing the stylesheet issues that are dependent on HOW you change to the stylesheet to be very difficult to test properly.  I never know if I'm getting to the situation in the required fashion.  I was previously set to OpenLight, and used the Preference window to switch to FreeCAD Classic.  Nothing crazy wrong to me, other than (standard?) tiny little separation bar (circled)  on the left that most won't see.

Overall, I do think the combination of transparency and overlay toggles - while powerful, can be confusing.

<img width="1621" alt="Screenshot 2024-08-30 at 9 57 05 AM" src="https://github.com/user-attachments/assets/a2347a6a-f952-4e2a-b55c-e8f0cfc03040">

```
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git)
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * OpenTheme 2024.8.17
  * fasteners 0.5.27
```

**Comment by maxwxyz** [comment]
@JohnOCFII when switching to classic, what does the stylesheet preference say under Display UI? "No stylesheet"?
@MisterMakerNL in above screenshot the header bars in the task dialog are also missing (https://github.com/FreeCAD/FreeCAD/issues/15802)

**Comment by MisterMakerNL** [comment]
The headers are from the stylesheet, which pulls the colors from the accent colors. So seems like the stylesheet is still there but the accent colors are removed.

**Comment by JohnOCFII** [comment]
> @JohnOCFII when switching to classic, what does the stylesheet preference say under Display UI? "No stylesheet"?

When switching from OpenLight to FreeCAD Classic under `Preferences --> General` (and hitting `Apply` then `OK`) if I switch to `Preferences --> Display --> UI` it shows stylesheet as `OpenLight.`
<img width="1515" alt="Screenshot 2024-08-30 at 12 32 43 PM" src="https://github.com/user-attachments/assets/3d13f597-860c-470b-bfff-6e208a479adb">

**Comment by maxwxyz** [comment]
ok thanks. @obelisk79 so confirmed for Windows and macOS

**Comment by maxwxyz** [comment]
Should be resolved by https://github.com/FreeCAD/FreeCAD/pull/16169
