### ISSUE TITLE
[Feature] Draft: sort Draft AutoGroup dropdown menu alphabetically

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#16191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Priority: Low

When working with draft layers, they are ordered alphabetically in the layer manager. Thy are also sorted alphabetically in the model tree view.

When choosing active layer from the Draft AutoGroup dropdown menu, the layers are ordered by the order they were created. This makes it hard to find the correct layer when working with large number of layers.

The proposed solution is to order layers in the Draft AutoGroup dropdown menu alphabetically, the same way they are ordered in the layer manager. This would lead to greater consistency and also make it easier to find the correct layer in the dropdown menu.

See attached pictures.

Related forum discussion: https://forum.freecad.org/viewtopic.php?t=90215&sid=c153b504ff11201c67905948a2f0a116

Layer manager: layers sorted alphabetically:
![01_layer-manager_ordering](https://github.com/user-attachments/assets/ba0d1aca-6306-4526-b78c-400b350dcdfe)

Draft AutoGroup dropdown menu: layers sorted by the time of their creation:
![02_active-layer-ordering](https://github.com/user-attachments/assets/7f520f36-2b5a-4655-9d33-b434ee77ccea)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git)
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
It's indeed a good idea. It's pretty simple to achieve, I think the Layer container's Group property needs to be sorted each time it's touched
