### ISSUE TITLE
Sketcher: grid spacing should be saved with the file

### ISSUE THREAD

**Issue by tigert** [FreeCAD/FreeCAD#16202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When you adjust the grid spacing to help align things on sketches, and later load the file again, you expect the grid spacing to persist and be saved in the file.

However the grid is reset to the default setting (10mm in my Preferences it seems) whenever a file is opened again.

As a user I would expect the grid size to be part of the sketch metadata, as this is quite common feature in other applications that grid size is stored with the file, as it relates to the file in question, some other file might require a different size grid. 

Grid visibility and the snap-to-grid toggle might be a user preference thing, and thus could also be global settings, independent of the file.

### Full version info

```shell
OS: Windows 11 build 22623
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git)
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Finland (en_FI)
Installed mods: 
  * fasteners 0.5.27
  * FeedsAndSpeeds 0.5.0
  * InventorLoader 1.4.0
  * OpenDark 2024.3.13
  * sheetmetal 0.4.24
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Grid spacing and grid visibility are stored per sketch. Are you aware of that?

**Comment by Syres916** [comment]
Yep, the _GuiDocument.xml_ holds for each sketch: GridAuto, ShowGrid (both Booleans) and the size as per:

```
<Property name="GridSize" type="App::PropertyLength" status="1">
<Float value="50.0000000000000000"/>
```

The issue is that the reading back in when opening the file even with the exact same build doesn't appear to be working, here's the what the Property Editor is showing for the above when opening the same file:

![SketchGridInfo](https://github.com/user-attachments/assets/1af33a6a-fce2-4351-88f0-bdcc3b7433fe)

Hopefully it won't take too much investigation to establish whether it ever worked and if so, what to do to fix it.

**Comment by Syres916** [comment]
This is definitely a regression not a feature req, last working build I have is:

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37302 (Git) AppImage
Build type: Release
Branch: main
Hash: 0e24e121eb3e5708c380596e0a9fd583befac977
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
```

first failing build I have is:

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git) AppImage
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
```

So another between mid May and the end of June this year. Could it be https://github.com/FreeCAD/FreeCAD/pull/14322/commits/c7aa698648ac085e84c9452e8fbf1b9b9710a727 as StartRestoring and FinishRestoring didn't exist and I'd hazard a guess it was handled by the Document->OnRestoring beforehand.

**Comment by Syres916** [comment]
I got the correct [PR](https://github.com/FreeCAD/FreeCAD/pull/14322), here's the actual [commit](https://github.com/FreeCAD/FreeCAD/commit/8def94e6f811e9babdb1cd41437a785a1c5aae1c)
Now I'll have a go at a fix and raise a PR ensuring I don't break the reason for the original line coloring PR.

@Roy-043 could you please remove label _Type: Feature_ and replace with _Type: Regression_

**Comment by Syres916** [comment]
@kadet1090 do you mind having a look at what is needed to get the three properties _ShowGrid_, _GridAuto_ and _GridSize_ to be read in from an existing file again please? I noticed in [commit](https://github.com/FreeCAD/FreeCAD/commit/8def94e6f811e9babdb1cd41437a785a1c5aae1c) you moved _SketchEdgeColor_ and _SketchVertexColor_ and created the `startRestoring` and `finishRestoring` functions which I guess stopped the 'normal' restoring of the grid properties.

**Comment by kadet1090** [comment]
@Syres916 Thanks for heads up and bisecting the commit, I appreciate it much! Could you test fix that I provided in linked PR?
