### ISSUE TITLE
Measurement: Hiding does not hide Deltas

### ISSUE THREAD

**Issue by Murmele** [FreeCAD/FreeCAD#16213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating a measurement and turning on the delta after hiding the measurement, the deltas are still visible
1) Create measurement
2) Save the measurement
3) Close measurement tool
4) Enable delta for measurement
5) Hide measurement

## Expected

The direct distance and the deltas get invisible

## Observed

The direct distance is anymore visible, but the deltas are **still** visible

**Measurement Visible:**

![grafik](https://github.com/user-attachments/assets/5e43d9e4-1680-4fde-bbfc-f8fed5ac7ff7)

**Measurement Hidden:**

![grafik](https://github.com/user-attachments/assets/edf77e80-e352-4e52-8e6a-9c214ed0acfa)

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38555 (Git)
Build type: Release
Branch: main
Hash: 73cb5bafe0c32c178d9b594a6ca03124483d305f
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@hlorus

**Comment by maxwxyz** [comment]
@chennes would you consider this a blocker? Once measurements with delta are created, they cannot be hidden. Only way to remove them, is to delete the measurement object.

**Comment by chennes** [comment]
@maxwxyz can you please confirm that #16819 resolves the issue for you?

**Comment by maxwxyz** [comment]
can confirm, it fixes the issue
