### ISSUE TITLE
Toolbar items has needless paddings for built-in non-classic themes

### ISSUE THREAD

**Issue by YohDeadfall** [FreeCAD/FreeCAD#16211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I noticed a while ago that a newer versions of FreeCAD has weird paddings after each tool bar button like if there should be arrows, but these just usual buttons. The problem applies to light and dark themes, and cannot be reproduced with the classic theme or without style sheets.

![Some toolbar buttons has paddings on the left](https://github.com/user-attachments/assets/3bf22cb5-d804-4e5d-a46d-0d406f9bc3b3)

### Full version info

```shell
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.1, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * sheetmetal 0.3.12
  * A2plus 0.4.60n
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
please test the dev version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by luzpaz** [comment]
Yea, this should be a non-issue on dev. Closing.
