### ISSUE TITLE
FreeCAD doesn't compile from source (solution for missing submodules if no internet access ?)

### ISSUE THREAD

**Issue by Zolko-123** [FreeCAD/FreeCAD#16253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I've downloaded the latest FreeCAD source archive from GitHub as ZIP (date 2024.09.03) and tried to configure it with cmake, but there are always errors at the end: 

`cmake ../FreeCAD-main_2024.09.03` 

`-- Configuring incomplete, errors occurred!`

```
CMake Error at src/3rdParty/CMakeLists.txt:11 (message):
The OndselSolver git submodule is not available
...
Add the installation prefix of "Microsoft.GSL" to CMAKE_PREFIX_PATH or set
"Microsoft.GSL_DIR" to a directory containing one of the above files.  If
"Microsoft.GSL" provides a separate development package or SDK, be sure it
has been installed.

CMake Error at src/Mod/Start/CMakeLists.txt:31 (message):
The C++ Guidelines Support Library (GSL) submodule is not available.
...
CMake Error at tests/CMakeLists.txt:9 (message):
The Google Test submodule is not available.
```

but that build computer doesn't have "git" and is not connected to Internet, and the 3 missing packages refer to 3 commercial companies (Microsoft, Ondsel and Google) of which I'm not allowed to blindly include unknown files. It is therefore not possible to build FreeCAD from source. 

I was able to remove the dependencies on _Ondsel_ and _Google_ (with `cmake -DBUILD_ASSEMBLY=OFF -DENABLE_DEVELOPER_TESTS=OFF ../FreeCAD-main_2024.09.03` although that's not documented anywhere) but didn't find how to get rid of dependencies on _Microsoft_. 

Can you please provide accurate instructions how to compile FreeCAD from source without the need of unknown external packages please ? 

> run `git submodule update --init` 

is not an option because 1) no git, 2) no Internet, 3) don't know what files it would download 4) from where

### Full version info

```shell
Source ZIP archive downloaded from GitHub on 2024.09.03
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rmu75** [comment]
To me it looks like the generated source code archive doesn't include git submodules. Maybe relevant: https://github.com/dear-github/dear-github/issues/214

**Comment by xtemp09** [comment]
_FreeCAD_ cannot be compiled without _Microsoft GSL_.


The source ZIP file does not include submodules, they can be downloaded using _git_ or some other tools.

**Comment by Zolko-123** [comment]
> The source ZIP file does not include submodules, they can be downloaded using _git_ or some other tools

did you read the LGPL ?

**Comment by chennes** [comment]
The GSL dependency is in Start, so to get your compilation running you can disable that. 

Unfortunately we have no control over how GitHub generates those Zip distributions: our official distribution mechanism for the source code is via git. As the LGPL does not specify that any particular mechanism must be used for the source distribution, I don't believe this is a problem (though I am not a lawyer, so consult yours, etc. etc.). Regardless, to obtain the source code for FreeCAD in any form you need internet access. 

If you'd like to use Zip downloads for each of the submodules they are currently:
* https://github.com/Ondsel-Development/OndselSolver/archive/64e546fe807043d4cdc33be023e521ac0f6449e9.zip
* https://github.com/google/googletest/archive/f8d7d77c06936315286eb55f8de22cd23c188571.zip
* https://github.com/microsoft/GSL/archive/b39e7e4b0987859f5b19ff7686b149c916588658.zip

**Comment by rmu75** [comment]
> > The source ZIP file does not include submodules, they can be downloaded using _git_ or some other tools
> 
> did you read the LGPL ?

This has nothing to do with licenses and no rights are harmed just by inconveniencing people building from zip archives. After all, you can get zips of the missing submodules yourself.

**Comment by luzpaz** [comment]
> After all, you can get zips of the missing submodules yourself.

Maybe we can specify this somewhere in the docs ?

**Comment by adrianinsaval** [comment]
github auto generated zip files don't include submodules but at the FreeCAD-Bundle repo you'll find tars with submodules, we use those for the conda builds. I can publish them to the main github release when we make one too. https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/freecad_source.tar.gz

> As the LGPL does not specify that any particular mechanism must be used for the source distribution,

even if it did, this is a thrid party dependency not our code. There is no responsibility from us to distribute this code. I would say it would be nice if there was an easy way to point cmake to a local copy for compilation, because many build systems don't have access to internet when compiling, meaningful example being debian and the ppa

**Comment by adrianinsaval** [comment]
> this is a third party dependency not our code. There is no responsibility from us to distribute this code

quoting myself so you don't miss it. You might as well ask us to include the source code for qt, occt, etc

**Comment by Zolko-123** [comment]
> There is no responsibility from us to distribute this code

of course it is if it's necessary to build the executable. Since the software doesn't compile without it you're violating the LGPL.

**Comment by chennes** [comment]
> so your argument is that FreeCAD doesn't provide the source code and I have to find it myself somewhere ?

"FreeCAD" *is* the source code. FreeCAD's *developers* provide the source code via the git instructions you cite above. There are other ways of obtaining the source code that may be more or less supported by various individuals and/or companies. Zip downloads of the individual components via GitHub's auto-generated Zip mechanism is one such possibility.

**Comment by adrianinsaval** [comment]
> > There is no responsibility from us to distribute this code
> 
> of course it is if it's necessary to build the executable. Since the software doesn't compile without it you're violating the LGPL. 

We don't include qt's source code in our zip either, is that a violation of LGPL too?

**Comment by Zolko-123** [comment]
> > so your argument is that FreeCAD doesn't provide the source code and I have to find it myself somewhere ?
> 
> "FreeCAD" _is_ the source code. 

... which doesn't compile, so no it's not, please stop lying

> FreeCAD's _developers_ provide the source code via the git instructions you cite above

any proof of that ? What's the proof that the git instruction really downloads the stuff you pretend ? What's the license of the downloaded code ? What's the proof that it doesn't contain binary blobs ? 

What part of "open source" don't you understand ?

**Comment by rmu75** [comment]
> > After all, you can get zips of the missing submodules yourself.
> 
> so your argument is that FreeCAD doesn't provide the source code and I have to find it myself somewhere ?

I'm not going to split hairs. You did get your other dependencies somewhere, and you did get FreeCAD source from github, not from FreeCAD, so it is reasonable that you can download other dependencies also from github.

**Comment by Zolko-123** [comment]
> via the git instructions you cite above.

doesn't work :

```
$ git submodule update --init
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

even though:

```
$ more .gitmodules
[submodule "src/3rdParty/OndselSolver"]
    path = src/3rdParty/OndselSolver
    url = https://github.com/Ondsel-Development/OndselSolver.git
[submodule "tests/lib"]
    path = tests/lib
    url = https://github.com/google/googletest
[submodule "src/3rdParty/GSL"]
    path = src/3rdParty/GSL
    url = https://github.com/microsoft/GSL
```

is there. 

> though I am not a lawyer, so consult yours

if that's your choice ...

**Comment by adrianinsaval** [comment]
to use git submodule you must use a git repo, you can also manually download zipfiles for those projects and place them in the corresponding directories listed there if you are adamant about not using git. Or as I mentioned before:

> github auto generated zip files don't include submodules but at the FreeCAD-Bundle repo you'll find tars with submodules, we use those for the conda builds. I can publish them to the main github release when we make one too. https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/freecad_source.tar.gz

**Comment by luzpaz** [comment]
@adrianinsaval is there some sort of tool that can turn a source.tar.gz in to a git repo perhaps ?

**Comment by yorikvanhavre** [comment]
> please stop lying

I would have to ask you to respect the [FreeCAD code of conduct](https://github.com/FreeCAD/FreeCAD/blob/main/CODE_OF_CONDUCT.md), @Zolko-123 , and be respectful to other people. Nobody here is "lying".

FreeCAD **does** provide access to all of its source code, as required by the LGPL. You know we are doing all we can to do that as perfectly as possible Zolko, come on, you didn't arrive yesterday. The fact that FreeCAD uses gitmodules for some dependencies and dynamic libraries linking for other dependencies has nothing to do with that question. FreeCAD code is only FreeCAD code, the git modules are external dependencies. You cannot build FreeCAD without any of its external dependencies, gitmodule or not. That's how 99% of the open source world works.

Also, just a note, pieces of code being authored by microsoft, google, ondsel or anyone else is not really relevant to this question, as long as they use a proper FOSS license, it's open-source software. Now we could have another discussion if we *should* use more and more google/microsoft code, I'd be happy to discuss that, actually... 

What the FreeCAD project needs to do to respect the LGPL is 1) to provide its own source code, and 2) indicate all the other source codes of all other dependencies of FreeCAD. Indeed here I think Zolko has a point, the external libraries are documented, but the gitmodules aren't. And therefore, who does indeed get the source code via the github zips, is missing a piece of information.

So I think this issue is actually valid. We should document how people who get the "pure" FreeCAD source code (via zip and without git) need to get and compile these dependencies

Anyone would volunteer to add that to https://wiki.freecad.org/Compile_on_Linux to start with?

**Comment by leoheck** [comment]
Something from the following text could be added to the cited wiki above.

@Zolko-123 if you have `cmake-gui` you can easily explore the build options and variables. See the following image:

![image](https://github.com/user-attachments/assets/37860e3c-66bb-4e82-835d-4a8b3db62be2)

There are no options related to Microsoft and GSL to be able to disable it. It seems to be a hard dependency not an optional one for now.

**But this is easy to fix** if you are ok in building it.
You just have to have internet to download the zip from its repo here https://github.com/microsoft/GSL/archive/refs/heads/main.zip
And unpack it in `[freecad_repo_clone]/src/3rdParty/`

Then run your cmake recipe again to disable the other things you don't want.
```
cmake -DBUILD_ASSEMBLY=OFF -DENABLE_DEVELOPER_TESTS=OFF ../FreeCAD-main_2024.09.03
```

**Comment by adrianinsaval** [comment]
It's a hard dependency for start, but you can disable it to get freecad compiled without it
> The GSL dependency is in Start, so to get your compilation running you can disable that.

**Comment by leoheck** [comment]
What is Start?

**Comment by adrianinsaval** [comment]
https://github.com/FreeCAD/FreeCAD/tree/main/src/Mod/Start

it's the starting page when you open freecad, no major functionality is lost when disabling it.

**Comment by leoheck** [comment]
Hmm cool, thanks. Let me check if I can disable it somehow. I  understood this page was removed on this 1.0. But it looks like it is not the case.

**Comment by adrianinsaval** [comment]
it was changed from being qtwebengine (html) based to qtwidgets like the rest of the app. You can disable it by setting BUILD_START=OFF

**Comment by leoheck** [comment]
yes, just found it and was building with it to check.

**Comment by adrianinsaval** [comment]
it would be nice if someone could take the time to document this in the wiki and/or the developers guide but there is no actual problem with freecad here so no action to take in the code, should we close this issue?

**Comment by hyarion** [comment]
@luzpaz What do we need to do in order to close this issue?

**Comment by adrianinsaval** [comment]
Just documentation IMO

**Comment by hyarion** [comment]
@adrianinsaval Documentation updated:
* Removed section about downloading source archive from https://wiki.freecad.org/Compile_on_Linux
* Removed section about downloading source archive from https://wiki.freecad.org/Compile_on_Docker
* Verified that https://wiki.freecad.org/Compile_on_Linux `git clone` command contained `--recurse-submodules` flag
* Added `--recurse-submodules` to `git clone` command on https://wiki.freecad.org/Compile_on_MacOS
* Added `--recurse-submodules` to `git clone` command on https://wiki.freecad.org/Compile_on_Windows
* Added `--recurse-submodules` to `git clone` command on https://wiki.freecad.org/Compile_on_Docker
* Added `--recurse-submodules` to `git clone` commands in [DevelopersHandbook](https://github.com/FreeCAD/DevelopersHandbook/pull/106)
