### ISSUE TITLE
[Regression][Sketcher] Rotating the body when in Sketch Mode is showing only the face where the sketch was made 

### ISSUE THREAD

**Issue by astrolemonade** [FreeCAD/FreeCAD#16279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Rotating the body when in Sketch Mode is showing only the face where the sketch was made.
1. have a body
2. start sketch on a face and enter sketch mode
3. try to rotate the sketch to add external geometry
4. observe that the 3D viewer is broken
File to use for replication(I had to compress it since GitHub is not accepting FCStd files):
[replicate.FCStd.zip](https://github.com/user-attachments/files/16869020/replicate.FCStd.zip)

https://www.virustotal.com/gui/file/2ea6893b65c3f39264e068c534c10ce74b340e65e53bf2dffd55f8e10a777e9d?nocache=1
hash: 2ea6893b65c3f39264e068c534c10ce74b340e65e53bf2dffd55f8e10a777e9d

![image](https://github.com/user-attachments/assets/409e55ee-7cab-4502-9c74-f4dca442ebd0)
![image](https://github.com/user-attachments/assets/f70ca6b5-2d68-4af5-82ad-0cab217dcb73)
![image](https://github.com/user-attachments/assets/04baac86-4f80-4de5-8002-3d8dae9bcd83)

### Full version info

```shell
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38622 (Git)
Build type: Release
Branch: main
Hash: ed97f3c4591303ee3b54906768f8f4eba5211265
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * FreeCAD-themes 2024.7.24
  * OpenTheme 2024.9.1
  * IconThemes
  * lattice2 1.0.0
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
deactivate view section

**Comment by maxwxyz** [comment]
Yes, the last option
