### ISSUE TITLE
Feature Request: A place to see the new Splash screen images

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#16288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Splash screen used to take enough time to be appreciated, but since it was changed last weekly, it is passing real quick. Honestly I like that, the quicker it gets to open the tool the better.

I could also see only a single image since it was visible by 2 seconds and then disappeared, on my machine.
I read somewhere that we are going to have multiple splash images. 
So I would like to ask if we can have a place we to see all the existing splash images.

My suggestion is that the About screen could have a carousel with images and 2 buttons to pass the images forth and back.

Something like this would be nice. See 2 triangle shaped buttons on the bottom-right of the image.

![image](https://github.com/user-attachments/assets/b068c901-762f-49d9-ad80-bb236c6d84dc)

What do you think?

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38622 (Git) AppImage
Build type: Release
Branch: main
Hash: ed97f3c4591303ee3b54906768f8f4eba5211265
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
Related issue: https://github.com/FreeCAD/FreeCAD/issues/16264

**Comment by maxwxyz** [comment]
I'd be in favor of #16264 and not this one.
