### ISSUE TITLE
[Regression] Some remaining duplicated extensions on export (example: FEM mesh formats)

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#16299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

As we know, #15838 introduced some regression that was then fixed by #15947. However, it seems that some export formats still exhibit this behavior. This is the case at least for FEM mesh formats.
1. Create Part Cube.
2. Go to FEM. Select the Cube and mesh it with Gmsh.
3. Select FEMMeshGmsh and File --> Export. Change the format from .dat to .unv and export.
4. Try exporting again. It shows Unnamed-FEMMeshGmsh.unv.dat this time.

This doesn't happen in 0.21.2. It might be the same with some other formats so I don't know if it's FEM-specific.

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38622 (Git)
Build type: Release
Branch: main
Hash: ed97f3c4591303ee3b54906768f8f4eba5211265
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@pieterhijma could you take a look at this since #15838 created this regression ? TIA

**Comment by pieterhijma** [comment]
Yes, I will.

**Comment by pieterhijma** [comment]
It is not FEM-specific. It has to do with file patterns that have more than one option, for example "Point formats (*.asc *.pcd *.ply)" or "FEM mesh Fenics (*.xml *.xdmf)". Choosing any of the extensions except for the first results in this situation.
