### ISSUE TITLE
STL does not operate correctly for 3D printing

### ISSUE THREAD

**Issue by 63Vette** [FreeCAD/FreeCAD#16335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I created this simple design and used the STL import into AnkerMake Studio. The hole I had put did not show.

### Full version info

```shell
v.21.1
```

### Subproject(s) affected?

None

### Anything else?

As designed from FreeCAD
![FreeCad design issue for GitHub](https://github.com/user-attachments/assets/03729b26-084a-4283-9929-583315504f21)

As imported STL from FreeCAD into AnkerMake
![AnkerMate import of FreeCad STL](https://github.com/user-attachments/assets/aa5e95b6-4fd1-45da-8917-ac54abde7e14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
I think this is a user error. You have probably selected all objects in the tree, You should only select the Body or its last feature for export.

See this Wiki page:
https://wiki.freecad.org/Std_Export

**Comment by 63Vette** [comment]
Can I send you the file and you provide instructions?


Sent from Yahoo Mail for iPhone


On Friday, September 6, 2024, 1:54 PM, Roy-043 ***@***.***> wrote:




I think this is a user error. You have probably selected all objects in the tree, You should only select the Body or its last feature for export.

See this Wiki page:
https://wiki.freecad.org/Std_Export

**Comment by Roy-043** [comment]
Instructions have already been provided. What is unclear?

1. Open the file.
2. Select the Body (and only the Body) in the tree.
3. Invoke Std_Export.

**Comment by 63Vette** [comment]
Ok thank you for the assistance!


Sent from Yahoo Mail for iPhone


On Friday, September 6, 2024, 2:37 PM, Roy-043 ***@***.***> wrote:




Instructions have already been provided. What is unclear?
   
   - Open the file.
   - Select the Body (and only the Body) in the tree.
   - Invoke Std_Export.

**Comment by luzpaz** [comment]
@63Vette you're using v0.21.x  
Most likely this issue you're reporting is user error. Please use forum.freecad.org to confirm your bug first before opening a ticket. 
Closing.

**Comment by 63Vette** [comment]
I selected the body only from the tree and this is what exported, missing more of the structure!



This is the structure:


    On Friday, September 6, 2024 at 02:37:08 PM EDT, Roy-043 ***@***.***> wrote:  
 
 


Instructions have already been provided. What is unclear?
   
   - Open the file.
   - Select the Body (and only the Body) in the tree.
   - Invoke Std_Export.

**Comment by luzpaz** [comment]
@63Vette we can't see images when you respond via email. Better to respond directly on Github.

**Comment by 63Vette** [comment]
Ok


Sent from Yahoo Mail for iPhone


On Friday, September 6, 2024, 5:37 PM, luzpaz ***@***.***> wrote:




@63Vette we can't see images when you respond via email. Better to respond directly on Github.
