### ISSUE TITLE
Has the shape-binder got lost?

### ISSUE THREAD

**Issue by Panda631** [FreeCAD/FreeCAD#16348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![grafik](https://github.com/user-attachments/assets/ea0314d8-c4bf-4549-852e-e6cff5d9b029)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * EM 2.1.1
  * fasteners 0.5.27
  * Help 1.0.3
  * kicadStepUpMod 10.17.1
  * Pyramids-and-Polyhedrons
  * Render 2024.8.4
  * sheetmetal 0.2.61
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
it's in the menu
