### ISSUE TITLE
Core: background process that watches to see how config files become corrupt over time 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#16370]
For years I've been seeing how the configs get corrupted and we don't really fully know why. We try to find the bug that causes this but the canned response is backup and reset your configs.  It would be beneficial if we ran some background process that just watched config history to see wth changes create these anomalies.

_Originally posted by @luzpaz in https://github.com/FreeCAD/FreeCAD/issues/16127#issuecomment-2318189930_

**Comment by Roy-043** [comment]
There has been a recent PR (#13522) to address this. Have there been any examples of corrupted configs since then?

**Comment by benj5378** [comment]
@luzpaz Can we gather examples of corruption to find similarities?

**Comment by luzpaz** [comment]
Yes, hopefully that will be what this ticket achieves.

**Comment by Roy-043** [comment]
Let's close this for now and just keep our eyes out for future CFG issues.

**Comment by luzpaz** [comment]
> We have a sizeable amount of issues triggered by "something" in the configs, which is really annoying.

https://github.com/FreeCAD/FreeCAD/issues/6106#issuecomment-2348801572

**Comment by benj5378** [comment]
@luzpaz, before they reset their config file, we want them to make a backup of the config file that they can send us - in case the config shows to be the issue.
