### ISSUE TITLE
Two shapes in a sketch can extrude only one body

### ISSUE THREAD

**Issue by HaydenHu** [FreeCAD/FreeCAD#16371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/user-attachments/assets/91ae3ae6-de83-4c16-ad20-c080528abf43)
![image](https://github.com/user-attachments/assets/fc2445e3-4e2e-4d2c-a352-5e3876900406)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Chinese/China (zh_CN)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Please provide a file.

**Comment by HaydenHu** [comment]
> Please provide a file.
[DFN1006-3.zip](https://github.com/user-attachments/files/16922796/DFN1006-3.zip)

**Comment by Roy-043** [comment]
You have to set the Body's "Allow Compound" property to true and then recompute the Pad. Please keep in mind that this is experimental. In V0.21 and earlier a Body must always be a single solid.

Next time please consider starting a forum topic before creating a GitHub issue. Closing this.
