### ISSUE TITLE
Start: Typo in start page

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#16387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

@concretedog shared an image of a running RC1.0 on Raspberry Pi4 and found a typo

![image](https://github.com/user-attachments/assets/55df5b36-2dc8-438d-8aeb-a53804fd9b0e)

![image](https://github.com/user-attachments/assets/b8515c47-546f-4d45-8f8b-23a9ea1e4c8f)

But searching the source, it isn't present in the source
https://github.com/FreeCAD/FreeCAD/blob/7ed1e9380acccd686a0e3573f883ac793aec3299/src/Mod/Start/Gui/GeneralSettingsWidget.cpp#L213

### Full version info

```shell
TBD (concretedog will add to ticket when he's available)
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdrost** [comment]
Probably the screen is not big enough. I "reproduced" the issue by resizing FreeCAD window.

**Comment by luzpaz** [comment]
So weird that it truncates the 'm' to look like an 'n'.  In that case. I'll close ticket. Thought I'd open it JIC.
