### ISSUE TITLE
About info: explicitly mention if no stylesheet or QtStyle are used

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#16391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

https://github.com/FreeCAD/FreeCAD/pull/16281 recently added theme-related information to the output of the About dialog, which is great.

This is simply a suggested enhancement.

If the selected theme has a stylesheet, the output is like this:

```
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/
```

If not, the output is like this:
```
Stylesheet/Theme/QtStyle: /FreeCAD Classic/
```

Notice that in the second case `/FreeCAD Classic/` needs to be enclosed in `/` to show it refers to the second position in the string (`/Theme/`), which could possibly lead to misunderstandings. The first position (no stylesheet) is empty.

My suggestion would be to explicitly mention `none` instead of an empty string whenever a value is empty. So instead:

```
Stylesheet/Theme/QtStyle: none/FreeCAD Classic/none
```

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38654 (Git) Snap 1130
Build type: Release
Branch: main
Hash: 858ae45e18cfbe7ec7d15da21ec675fa249998de
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/
Installed mods: 
  * OpenTheme 2024.9.1
  * Curves 0.6.46
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Core

### Anything else?

I'd personally favor using commas and spaces for improved readability:

```
Stylesheet, Theme, QtStyle: none, FreeCAD Classic, none
```

However, if we start going down that path, it might be worth reviewing all entries in the about info so that they are consistent. E.g. the libraries section uses comma-separated values, but no key. The Stylesheet/Theme/QtStyle section uses a key (`Stylesheet/Theme/QtStyle:`), but uses `\` as a separator. `Installed mods:` uses a bullet list, etc.

I feel using YAML syntax for all entries could address this. It would also bring the benefit of the about info being machine-readable with established syntax parsers.

Also reviewing the need for current or future entries might also be worth considering. E.g. is `Word size of FreeCAD:` still needed nowadays where most users are on 64-bit systems?

I'll file separate issues for those.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kadet1090** [comment]
QtStyle should be obtained not from settings but from Qt - using either `QApplication::style()->name()` (from Qt 6.1) or `QApplication::style()->objectName()`

**Comment by furgo16** [comment]
@kadet1090 while pertaining to the overall topic, if I understand it correctly your comment does not seem to apply to this issue. Was it meant for https://github.com/FreeCAD/FreeCAD/pull/16281 perhaps?
