### ISSUE TITLE
Measurement: can't be closed - 'Access violation' (RC1)

### ISSUE THREAD

**Issue by pixelwaster** [FreeCAD/FreeCAD#16424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Found this by accident. I can reproduce every time.
Start FreeCAD
Auto start in Part WB (also checked Part Design WB)
Open a file (any file for this purpose)
Close the Start tab if open
Activate the Measurement tool
Make some measurements  
         **one last run thru - if you reset the tool, it can be closed.
Close the file (discard or save)
Try to close the measurement tool.

The report window
```
15:23:48  No measure handler available for geometry of module: TechDraw
15:32:13  0 Selection.cpp(157): Unhandled std::exception caught in selection observer: invalid vector subscript
15:32:13  TaskView::slotDeletedDocument: No document name set
15:32:34  Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: Access violation
```
I checked in build 39622(GIT) and the tool closes and this is the report
```
16:07:05  0 Selection.cpp(157): Unhandled std::exception caught in selection observer: invalid vector subscript
16:07:05  TaskView::slotDeletedDocument: No document name set

```

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * AddonManager
  * Assembly
  * BIM021 2021.12.0
  * btl 0.9.9
  * CAM
  * CurvedShapes 1.0.9
  * Curves 0.6.47
  * Draft
  * fasteners 0.5.28
  * FeedsAndSpeeds 0.5.0
  * Fem
  * Help 1.0.3
  * Idf
  * Import
  * Inspection
  * lattice2 1.0.0
  * Material
  * Measure
  * Mesh
  * MeshPart
  * MeshRemodel 1.10.9
  * OpenSCAD
  * Part
  * PartDesign
  * Plot 2022.4.17
  * Points
  * ReverseEngineering
  * Robot
  * sheetmetal 0.4.24
  * Show
  * Sketcher
  * Spreadsheet
  * Start
  * Surface
  * TechDraw
  * Test
  * Tux
  * Web
```

### Subproject(s) affected?

None

### Anything else?

[FreeCAD.log](https://github.com/user-attachments/files/16954927/FreeCAD.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
This may need to be reopened: https://github.com/FreeCAD/FreeCAD/pull/16608#issuecomment-2540467045
