### ISSUE TITLE
DXF importer (Python): AttributeError when importing dimensions

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#16435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Start FreeCAD
2. Create a new document
3. File > Import...
4. Select the previously uncompressed [DXF file attached](https://github.com/user-attachments/files/16959918/Layertest.zip)
5. Use the import settings in the screenshoot below. Most importantly, check `Use legacy Python exporter` (as the C++ importer does not yet support importing dimensions) and `Texts and dimensions`.
6. Click OK
7. The DXF file entities are imported, but dimensions are not. The Report view shows the following error:

```python stacktrace
opening $HOME/Documents/Layertest.dxf...
drawing 8 lines...
drawing 1 polylines...
drawing 2 circles...
drawing 2 dimensions...
pyException: Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/snap/freecad/1131/usr/Mod/Draft/importDXF.py", line 2848, in insert
    processdxf(doc, filename)
  File "/snap/freecad/1131/usr/Mod/Draft/importDXF.py", line 2599, in processdxf
    lay.addObject(newob)
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'addObject'
```

![image](https://github.com/user-attachments/assets/2ffdab81-182a-46f7-acdf-680398532bd3)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38684 (Git) Snap 1131
Build type: Release
Branch: main
Hash: 92e31fa7ea974fe48c372f6749916d68f42dcf95
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/
Installed mods: 
  * OpenTheme 2024.9.1
  * Curves 0.6.46
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

File formats

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Confirmed. The file contains a local `addObject` function that has not been implemented everywhere for some reason.

**Comment by yorikvanhavre** [comment]
> sometimes addObject is called as a local function defined in this module, sometimes as a method from a parent class.

Some objects, those derived from App::DocumentObjectGroup or those that have the App::GroupExtensionPython extension, have an addObject method built-in. Others don't, so for those we often write our own

**Comment by furgo16** [comment]
Would it make sense to a) modify the local `addObject` function to handle objects with a built-in `addObject` method and b) to always call the local the local `addObject` function within the module?

In a way, this is already done if the function is called with a layer:

https://github.com/FreeCAD/FreeCAD/blob/614a14fe87af6ea0a978ee6312b298e4033f1839/src/Mod/Draft/importDXF.py#L1921-L1935

**Comment by yorikvanhavre** [comment]
> Would it make sense to a) modify the local addObject function to handle objects with a built-in addObject method and b) then always call the local addObject function within the module?

Yes I think that's a good idea

**Comment by furgo16** [comment]
Ok, I'll try to give that a go on a separate PR, after https://github.com/FreeCAD/FreeCAD/pull/16469 is reviewed/merged. 

There are other entities in the module that might need the same fix, and it might be a good opportunity to explore if there is room for optimization.
