### ISSUE TITLE
Part Design: Polar pattern and mirror don't work for some padded shapes

### ISSUE THREAD

**Issue by Media-Evil** [FreeCAD/FreeCAD#16440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This issue is present since at least FreeCAD v0.21.2

Some 3D geometry generated from contours (be it a sketch, a shape or subshape binder of that sketch) can not be used to create a polar pattern, and to reflect a shape. The same operation works just fine RealThunder's Link branch.

I couldn't tell what exactly is the cause. Regular rectangular shapes of the same origin as I described work just fine. This is something one would intuitively expect to work. Frustrating.

![image](https://github.com/user-attachments/assets/df888a06-bc8a-46ba-9125-ae555cfd5c91)
![image](https://github.com/user-attachments/assets/e922bfc0-1683-403a-8566-1cf3c36289aa)

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * fasteners 0.5.28
  * sheetmetal 0.4.24
```

### Subproject(s) affected?

PartDesign

### Anything else?

Here is example file with the problem.

[example.zip](https://github.com/user-attachments/files/16962361/example.zip)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
The constraints scheme in "Extrusion Quarter" is unfortunate. It causes tolerances in the area where the 4 parts of the polar array should meet. They almost touch but not quite. Which causes the problem you have. You can get the 4 separate solids to display if you change the "Allow Compound" property of the Body to true and then recompute the polar pattern feature. But you probably want a single solid. For that you need to improve the constraints scheme which, BTW, seems overly complex. I am attaching my quick solution to demonstrate that changing the constraints will fix this.

[example-roy.FCStd.zip](https://github.com/user-attachments/files/16964087/example-roy.FCStd.zip) (remove the zip extension)

If you want more advice you should start a forum topic.

I am closing this as a user error.
