### ISSUE TITLE
Inexisting Sub Folders

### ISSUE THREAD

**Issue by Fouleur** [FreeCAD/FreeCAD#16458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Dans le menu  Édition -> Préférences n'existe pas

### Full version info

```shell
Dans l'aide il est dit : 
En définir un manuellement dans le menu Édition -> Préférences -> Import-Export -> DWG

Le menu préférences n'existe pas ??

Merci pour votre aide.
```

### Subproject(s) affected?

File formats

### Anything else?

<img width="527" alt="Capture d’écran 2024-09-11 à 19 57 47" src="https://github.com/user-attachments/assets/187e7996-5868-4dd0-b33e-2d1c3960acd6">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Please translate to english, Thx

**Comment by Roy-043** [comment]
https://wiki.freecad.org/Preferences_Editor/fr
> Pour lancer l'Éditeur de préférences, sélectionnez l'option Édition → Préférences... dans le menu. Sur macOS, l'option Préférences... apparaît dans le menu FreeCAD à la place (c'est l'emplacement par défaut des préférences sur Mac).
