### ISSUE TITLE
UI/UX: The new freeze object button is missing

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#16459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Some days ago I found this icon right-clicking on an object in the Objects tree.
Right now I found out how to use it, but I cannot locate this icon anymore. 
Is this a bug?
I would like to use this new feature.

![image](https://github.com/user-attachments/assets/95b61b8e-3ad3-4453-a102-480933e606e7)

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git) AppImage
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
Hi, a known bug hide the `Toggle freeze` menu item under Part Design. It is shown when you switch to another workbench.
Listed in https://github.com/FreeCAD/FreeCAD/issues/12829

**Comment by leoheck** [comment]
Thanks @FlachyJoe , is there any workaround? If yes, then I will close this issue.
