### ISSUE TITLE
BIM: 1.0RC1 view error when TechDraw view and BIM workbench is combined

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#16452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When combining open TechDraw page and BIM Workbench, I get an error message when mouse is moved:
```shell
16:33:46  Traceback (most recent call last):
16:33:46    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_38643\Mod\BIM\bimcommands\BimViews.py", line 285, in update
16:33:46      if hasattr(v.ViewObject, "Proxy"):
16:33:46                 ^
16:33:46  UnboundLocalError: cannot access local variable 'v' where it is not associated with a value
```

FreeCAD seems to work without any problems after that, but the warning message is a bit concerning. I am able to reproduce this 100% of time.
I tried combining with spreadsheet view and the error does not occur with this combination.

Steps to reproduce:

1. Open new file
2. Slect Techdraw workbench
3. Create TechDraw_PageDefault
4. Switch to BIM workbench
5. Move your mouse (sometimes more, sometimes less, it does not happen when mouse is moved over certain area)
6. The error message shows up

https://github.com/user-attachments/assets/e30abd11-f5c9-4560-a2c5-a68b2118d4be

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Confirmed. I'll issue a fix
