### ISSUE TITLE
UI/UX: Visibility icon is clicked when a tree item gets collapsed

### ISSUE THREAD

**Issue by NomAnor** [FreeCAD/FreeCAD#16463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is only triggered in certain circumstances, depending on the scroll position and layout of the tree.

![collapsing](https://github.com/user-attachments/assets/16c50c70-748b-4932-a6bc-67f469a3fa8a)
If the left mouse button is pressed on the arrow in the screenshot, the _Holder_ link item will collapse. This causes the Tree to shift down because the scrollbar is not needed any more. The button is still pressed.
The mouse is now over the visibility icon of _Holder_ Part which causes it to activate and inadvertanly toggle it's visibility.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38513 (Git)
Build type: Release
Branch: main
Hash: 7c797b5a10c19ae55e317c4ff9a02823a4b4dc0b
Python 3.12.5, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.1, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: /FreeCAD Classic/
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.62.0
  * Assembly3.backup1715897154.0970206 0.11.3 (Disabled)
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.2.0
  * fasteners 0.5.27
```

### Subproject(s) affected?

Core

### Anything else?

@maxwxyz You can assign myself to this issue.

Propably need to change https://github.com/FreeCAD/FreeCAD/blob/614a14fe87af6ea0a978ee6312b298e4033f1839/src/Gui/Tree.cpp#L1678 for some other mouse event or do an additional check.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pinkavaj** [comment]
The issue is likely caused by modifying the tree in-flight - the tree is folded, but then the position of the items change uder the cursor and the onClick continues the check with the new element pointed by cursor ... (I have checked and there is just one onClick action which causes this.)
