### ISSUE TITLE
Subtractive helix adding material, generally not working (1.0RC1 regression?)

### ISSUE THREAD

**Issue by kbrantley** [FreeCAD/FreeCAD#16493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Starting in 0.21.1, create a new drawing, part, and then a new sketch on the XZ plane. Create a simple shape, kind of like this:
![image](https://github.com/user-attachments/assets/78e848ad-2b7e-4c35-995f-205d3f1b30e7)

Revolve the shape around the Z axis to create a solid object:
![image](https://github.com/user-attachments/assets/3c9a9724-229c-4f23-8e1c-b3d53d8200e3)

Set the transparency of the revolution to 90, and then create a new sketch on the XZ plane:
![image](https://github.com/user-attachments/assets/5b1e7e87-c097-4809-9d11-e7e2ab87183c)

Using the new sketch, apply a subtractive helix, 10mm pitch, 33mm height, reversed:
![image](https://github.com/user-attachments/assets/36975e1e-77c3-4a25-b18c-cd1b2d33cdb6)

To create internal threads on the cylinder:
![image](https://github.com/user-attachments/assets/92dad03a-ed31-4eee-89bc-9cf0028274ce)

Great. It worked. Load it up in 1.0RC1:
![image](https://github.com/user-attachments/assets/3997e5ed-8b28-49e2-9b28-9e7259cc97e1)

Recompute the helix, and observe how it just absolutely explodes, adding material where there shouldn't be any, and generally just doing things I don't understand:
![image](https://github.com/user-attachments/assets/bd594b4b-6b92-483b-a03d-5a16459c53b2)
![image](https://github.com/user-attachments/assets/53777b22-0ec3-4cf7-ab3c-5acc3823d42a)

Note: creating this from scratch in 1.0RC1 produces the same, buggy behavior.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Anything else?

This is the file as generated by 0.21.1:
[HelixBug.zip](https://github.com/user-attachments/files/16985745/HelixBug.zip)

And this is the file after recomputing the object in 1.0RC1 and saving it:
[HelixBug-1.0RC1.zip](https://github.com/user-attachments/files/16985755/HelixBug-1.0RC1.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Suplicate of https://github.com/FreeCAD/FreeCAD/issues/14901

**Comment by FlachyJoe** [comment]
@kbrantley It's a know bug of OCC for solid boolean operation with coincident elements. Tweak the sketch lengths by 1µm and it works:
![image](https://github.com/user-attachments/assets/8c174a05-3d21-4ba9-88fd-5945f6a1df6a)

PartDesign helix uses now a solid algorithm instead of the previous shell one. It fails on some cases but it's roughly better.
