### ISSUE TITLE
Draft: Annotation Styles Editor, Draft Preferences 'Scale multiplier' field in a confusing position

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#16501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The 'Scale multiplier' field in Annotation Styles Editor is placed in the 'Units' group. But it does not influence units, it influences the whole annotation. In the properties panel it is placed under the 'Annotation' group. In global Draft Preferences the same variable is placed under the 'Texts' group. The same location is in the Task Panel, when 'Change default styles of objects' is invoked.
This is a bit confusing.

Annotation Styles Editor:
![annotation-style-editor-units](https://github.com/user-attachments/assets/2a5d9d4a-5820-42bc-a4b0-56b74fdf92ff)

Draft preferences:
![draft-preferences](https://github.com/user-attachments/assets/3dd63ad9-2386-4613-bc2f-24b4847a1115)

Task panel:
![task-panel](https://github.com/user-attachments/assets/ee5ca590-e682-445a-82cc-44ab7c1b2363)

Element properties (the best placement in my opinion):
![properties](https://github.com/user-attachments/assets/952802db-8484-4849-a0a5-c4e73ab0f9c1)

**Proposed solution:**
The 'Scale multiplier' influences not only text, and and it does not influence units. It influences all annotations, all values. Therefore, the location in the 'Annotation' group, as is in the element properties, makes the most sense. To achieve consistency and logical placement, I propose:

1. Place new group of properties in the **Annotation Styles Editor** with the name 'Annotation' at the top of the dialogue. This group would have only one value to set - 'Scale multiplier'. Remove 'Scale multiplier' from the 'Units' group
2.  Place new group of properties in the global **Draft Preferences -> Texts and dimensions** with the name 'Annotation' at the top of the dialogue. This group would have only one value to set - 'Scale multiplier'. Remove 'Scale multiplier' from the 'Texts' group
3.  Place new group of properties in the global  **'Change default styles of objects' ->  Task Panel** with the name 'Annotation' at the top of the dialogue. This group would have only one value to set - 'Scale multiplier'. Remove 'Scale multiplier' from the 'Texts' group

![proposed-solution](https://github.com/user-attachments/assets/56a823fd-a3a1-44c7-bf0b-80d72d536c63)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38684 (Git)
Build type: Release
Branch: main
Hash: 92e31fa7ea974fe48c372f6749916d68f42dcf95
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: /FreeCAD Classic/
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Personally I agree with the proposed changes. Indeed having the scale factor inside "Units" is confusing.

**Comment by hooperbloob** [comment]
Great write up and proposed solution.

**Comment by furgo16** [comment]
Indeed, great analysis and proposal
