### ISSUE TITLE
How to use the mesh merge command in the python console？

### ISSUE THREAD

**Issue by mtime2show** [FreeCAD/FreeCAD#16527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I can't merge the two meshes in the python console, but with the click of a mouse,
![QQ拼音截图20240914120157](https://github.com/user-attachments/assets/7478c213-6bcf-442a-b63b-d622e779760e)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Chinese/China (zh_CN)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
PLease refer to the forums for help requests. If there is a bug, feel free to reopen this issue.
