### ISSUE TITLE
PartDesign: Subtractive Helix Fails to produce sometime produces 'Bnd_Box is void Error' - RC1 

### ISSUE THREAD

**Issue by sparker0594** [FreeCAD/FreeCAD#16553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In RC1 (also in Weekly) I have an issue with a 'Bnd_Box is void' error when producing a subtractive helix along a shaft.

RT Link Branch will produce the expected form (though has different issues).

The GIF below show the issue in RC1 and then shows the 'successful' form in RT Link

![Subtractive Helix Bnd_Box is void ](https://github.com/user-attachments/assets/bced5e39-9404-4825-9a19-d48365be83a3)

When the length of the helix is set to 150mm the form is not produced. but when setting the length to 160mm the form will be produced.
This behaviour is present in RC1 and the latest Weekly.

![Subtractive Helix 150 to 160](https://github.com/user-attachments/assets/f4d40074-4009-486a-922d-2e315faeeea7)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.6.47
  * sheetmetal 0.4.25





[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 2024.408.0.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.8, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.6.47
  * sheetmetal 0.4.25
[/code]


OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git)
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Curves 0.6.47
  * sheetmetal 0.4.25
```

### Subproject(s) affected?

PartDesign

### Anything else?

[FootBar.zip](https://github.com/user-attachments/files/17006372/FootBar.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
Your sketch brush against the shape by one point, it's a known cause for OCC bug. Simply shrink per 1µm and it works.
![image](https://github.com/user-attachments/assets/076e5ca2-735c-4b1d-9f6a-5bfb550d79ff)
