### ISSUE TITLE
Assembly corrupted after applying a fillet

### ISSUE THREAD

**Issue by felixscheibe** [FreeCAD/FreeCAD#16554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I built a simple assembly with a few parts, mainly using revolute joints. As soon as I applied a fillet to an edge, the assembly became corrupted.

Testfile with issue: [Assembly-WB_Filet Problem.zip](https://github.com/user-attachments/files/17006339/Assembly-WB_Filet.Problem.zip)

Screenrecording: https://github.com/user-attachments/assets/3327db1d-bf1f-4a15-a10c-a25caf0c202e

As an alternative, I built the same model using local coordinate systems in the bodies and used them to create the joints, without any problems when modifying the parts.

Testfile with LCS in bodies: [Assembly-WB_test_lcs.zip](https://github.com/user-attachments/files/17006343/Assembly-WB_test_lcs.zip)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Switzerland (de_CH)
Installed mods: 
  * Assembly4 0.50.15
  * fasteners 0.5.28
  * Manipulator 1.5.7
  * sheetmetal 0.4.25
```

### Subproject(s) affected?

Assembly

### Anything else?

Similar Issue was reported in #16207 (applying a chamfer)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Could you add this to #16207
