### ISSUE TITLE
Part Design, Pocket, Type: Up to face, with Offset Bug

### ISSUE THREAD

**Issue by AustinPackard** [FreeCAD/FreeCAD#16557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There is a bug when offsetting a Part Design, Pocket feature with Type: "Up to face" and the face selected is the inner face of half of 
section of a tube. The offset is applied to the outer face of the tube section, instead of the selected, inner face. 

Steps to reproduce:
Using the Part Design workflow:
1. Create a body that is half of a section of a tube (see attached example for reference).
2. Create a sketch of the shape to be debossed on the inner face of the tube section.
3. Create a Pocket feature, setting "Type" to "Up to face", selecting the inner face.
4. Set "Offset to face" to some value less than the wall thickness of the pipe section.
In my testing, the offset will appear on the opposite face.

Example file:
[Pocket Up to Face Bug.zip](https://github.com/user-attachments/files/17006537/Pocket.Up.to.Face.Bug.zip)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38684 (Git)
Build type: Release
Branch: main
Hash: 92e31fa7ea974fe48c372f6749916d68f42dcf95
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/
Installed mods: 
  * Curves 0.6.47
  * Ondsel-Lens 2024.7.5.02
  * OpenTheme 2024.9.1
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
Confirmed.
@bgbsww please assign me to this.
