### ISSUE TITLE
[Regression] TechDraw: Outline of torus missing in views

### ISSUE THREAD

**Issue by entkon** [FreeCAD/FreeCAD#16567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

die Linien werden nicht dargestellt
dieses teil können sie unter diesem link herunterladen
FreeCAD22 KA002 O-Ring Torus
https://entkon.de/freecad22-part-design-einfuehrung-in-klassische-konstruktion/

### Full version info

```shell
38728
2024/09/13
```

### Subproject(s) affected?

TechDraw

### Anything else?

![0001](https://github.com/user-attachments/assets/db5c80ff-af6e-47ce-9ce8-b4a1d1de9fa8)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
It's a regression.

Open the attached [file](https://github.com/user-attachments/files/17010916/td-torus-test-021.FCStd.zip) (remove the zip extension) in V0.21 and 0.22.
In V0.22 the outline of the torus is missing from the TD view.

**Comment by Roy-043** [comment]
@maxwxyz Should this be qualified as a Blocker?

**Comment by WandererFan** [comment]
Is this different from https://github.com/FreeCAD/FreeCAD/issues/16136 and
https://github.com/FreeCAD/FreeCAD/pull/16145 ?

What version are you running.  Seems to work here.
![torus2](https://github.com/user-attachments/assets/ee1a49b7-cf9e-45a7-84c1-b251cf5f02de)
![torus1](https://github.com/user-attachments/assets/0ef265e7-94aa-4d15-a829-8c702e44c6c8)


OS: Linux Mint 21.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38740 +1 (Git)
Build type: debug
Branch: winFilespec
Hash: 78c1a110f4c6ee0b69444f5a821c0b83b2fa8a14
Python 3.10.12, Qt 5.15.2, Coin 4.0.0, Vtk , OCC 7.8.0
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.21

**Comment by entkon** [comment]
Error in FreeCAD Version 22_38728 (13.09.2024):

In the TechDraw environment, lines are not displayed when using the "Torus" function. This may cause issues when creating technical drawings.

To download the part "FreeCAD22 KA002 O-Ring Torus," please use the following link:
https://entkon.de/wp-content/uploads/2024/09/FreeCAD22-KA002.zip

https://entkon.de/freecad22-part-design-einfuehrung-in-klassische-konstruktion/

**Comment by luzpaz** [comment]
@entkon we need full [About](https://wiki.freecad.org/About) info

**Comment by maxwxyz** [comment]
@entkon could you please try the latest dev version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by Roy-043** [comment]
The problem occurs in the latest weekly version. I suppose the previous fixes are included in that version.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git)
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

**Comment by WandererFan** [comment]
Is it possible that 38768 AppImage and local build have source differences?  Qt, OCC and Python versions are different.  

today's main local build - OK
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git)
Build type: debug
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.10.12, Qt 5.15.2, Coin 4.0.0, Vtk , OCC 7.8.0
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.21

today's RC1 local build - OK
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38752 (Git)
Build type: debug
Branch: releases/FreeCAD-1-0
Hash: 814945f72846f965aa53595a202f082a4618d424
Python 3.10.12, Qt 5.15.2, Coin 4.0.0, Vtk , OCC 7.8.0
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.21

recent AppImage - error
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git) AppImage
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/Canada (en_CA)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.21

**Comment by Syres916** [comment]
@WandererFan it's definitely an OCC issue with version 7.7.2, two builds based on the exactly the same libraries except OCC, the 7.8.2dev displays as expected and the 7.7.2 build gives the same incorrect view as reported.


Bad:
```
OS: EndeavourOS (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git)
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: Behave-dark.qss/Behave-dark/
Installed mods: 
  * Behave-Dark-Colors 0.1.1
  * FreeCAD-themes 2024.7.24
```

Good:
```
OS: EndeavourOS (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git)
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.2.dev
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: Behave-dark.qss/Behave-dark/
Installed mods: 
  * Behave-Dark-Colors 0.1.1
  * FreeCAD-themes 2024.7.24
```

**Comment by Syres916** [comment]
@adrianinsaval I believe the PPA has OCCT 7.8.1 now, are the Conda builds still a ways from also going to the same version?

**Comment by WandererFan** [comment]
Compiling OCCT 7.7.2 now.  Thanks for looking into this.

**Comment by adrianinsaval** [comment]
It should be doable to go to occt 7.8, but I'm a little hesitant to do it this late in the game (my fault for not doing it before). It seems that 7.8 might be in a better state than 7.7 though so maybe it makes sense after all. I'll see about making that happen at least for the weeklies and if everything goes well I might do it for the rc too
