### ISSUE TITLE
UI: Zoom in/out buttons for the light source cover the axes

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#16587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The newly added Zoom in/out buttons cover the axes in Preferences --> Display --> Light Sources. You can only see the Y letter here:

![axis](https://github.com/user-attachments/assets/4f3646c2-2499-417a-ae13-7ecca27113f0)

P.S. Those buttons are named Push In and Push Out. Wouldn't Zoom In and Zoom Out be more intuitive?

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git)
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
The buttons move camera, these movements are called _push in_ and _pull out_, I checked. I placed them to cover these axes, because I did not know how to get rid of them (at least, without returning the _NaviCube_ back). You might have different font settings or theme/style, so you can see a letter. =)



I don't mind if somebody improves the dialog, I just don't see room for improvement, besides hiding those axes.

**Comment by FEA-eng** [comment]
> The buttons move camera, these movements are called _push in_ and _pull out_, 

Yeah, but they seem to do the same with the camera as e.g. https://wiki.freecad.org/Std_ViewZoomIn so I suggested more intuitive names.

> I checked. I placed them to cover these axes, because I did not know how to get rid of them (at least, without returning the _NaviCube_ back). You might have different font settings or theme/style, so you can see a letter. =)
> I don't mind if somebody improves the dialog, I just don't see room for improvement, besides hiding those axes.

Couldn't the buttons just go to the other (left) side so that both them and the axis triad can be visible?

**Comment by xtemp09** [comment]
> 
> Yeah, but they seem to do the same with the camera as e.g. https://wiki.freecad.org/Std_ViewZoomIn so I suggested more intuitive names.


Sorry, I'm not a native English speaker, so I prefer to use literature for precise terms. According to the terminology, when the camera moves closer to an object, it is referred to as "pushing in," and when it moves farther away, it is called "pulling out."[^1]

[^1]: https://www.studiobinder.com/blog/different-types-of-camera-movements-in-film/
