### ISSUE TITLE
Segmentation fault in align to selection tool

### ISSUE THREAD

**Issue by Rexbas** [FreeCAD/FreeCAD#16584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

For example, see the attached file. If you select Body in the tree view and then align to selection button, it will crash. This happens because I call `back()` on an empty vector. `Base::Tools::splitSubName()` returns an empty vector when an empty string is passed. @PaddleStroke, is it supposed to do this? I feel like it should return a vector with one empty string if the input is an empty string.

### Full version info

```shell
OS: Fedora Linux 40 (KDE Plasma) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38740 (Git)
Build type: Release
Branch: main
Hash: b4923d1c584a4dce794d91a4b090a5293569223a
Python 3.11.0, Qt 5.15.8, Coin 4.0.3, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.21
```

### Subproject(s) affected?

None

### Anything else?

[Box.zip](https://github.com/user-attachments/files/17017522/Box.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
For me it made sense that it returns empty vector if the subname is empty.
If you still want to make the change, I'm not very opposed to it, but please make sure it does not break something in assembly.
