### ISSUE TITLE
TechDraw: "Smart" View Creation Tool Does not Respect Preference

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FreeCAD#16593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There is a preference on the advanced tab that should allow views to be created with the current camera direction (the default behaviour before the smart view create tool was implemented).  

This preference is not respected by the task dialog - the "use camera direction" button respects the preference, but the view is always created in a "front" view.

To reproduce:
- set preference to "use camera view"
- select an object and press the TechDraw_View button.
- the view will be created in front view.

![ProjGroupTask](https://github.com/user-attachments/assets/389ec1c1-0909-420e-92f3-a61180bd7685)
![UseCameraDirectionPref](https://github.com/user-attachments/assets/78c53651-ba5d-4669-94a3-7a42f3d0febc)

### Full version info

```shell
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38740 +1 (Git)
Build type: debug
Branch: winFilespec
Hash: 78c1a110f4c6ee0b69444f5a821c0b83b2fa8a14
Python 3.10.12, Qt 5.15.2, Coin 4.0.0, Vtk , OCC 7.8.0
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.21
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@PaddleStroke FYI
