### ISSUE TITLE
Assembly: Joint names get returned to default when editing a joint

### ISSUE THREAD

**Issue by ToniTen** [FreeCAD/FreeCAD#16598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I like naming my joints so I can more easily know what does what when returning to an assembly at a later date. However, when you give your joint a name, and then you return and edit the joint (to say, change the offset, limits, etc) the joint name returns to the default value.

It would be useful if Assembly detected that the joint name has been manually changed, and respect the name given by the user

### Full version info

```shell
OS: Ubuntu Core 22 (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git) Snap 1138
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: C/Default (C) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.24
  * Assembly3 0.12.2
  * lattice2 1.0.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Assembly

### Anything else?

Steps to reproduce:

1. Create an assembly, add two random parts, ground one, 
2. Add the revolute joint between them. 
3. Change the name of the joint (hitting F2, or by any other means)
4. Try to edit the joint, the name will instantly change to "Revolute". If you hit cancel, it will return to the name you had used, if you hit accept, it will change permanently to the default name.

This does not happen with fixed and grounded joints though. It has happened with every joint other type of joint I've tried, and it also happens when you change the joint type (from say cylindrical to revolute)

This also happens with 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@ToniTen could you quickly provide a screencast of this behavior ?

**Comment by ilmagico** [comment]
I had this issue as well, it's very easy to reproduce. See recording below.

https://github.com/user-attachments/assets/81b5681e-0bd4-485d-b7f9-7ff382cee9d3

**Comment by furgo16** [comment]
I can also confirm this after seeing all my Revolute joint labels being overwritten to default labels
