### ISSUE TITLE
FreeCad 1.0 RC1 - Image scaling crashing

### ISSUE THREAD

**Issue by weholt** [FreeCAD/FreeCAD#16612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Open FreeCad 1.0 RC1, selects the "Sketcher" workbench, clicks the "Image Scaling" icon to import image and there's a crash reported in the report view: 
```
20:23:42  pyException: Traceback (most recent call last):
  File "C:/Users/Thomas/AppData/Roaming/FreeCAD/Macro/Image_Scaling.FCMacro", line 5, in <module>
    import DraftTrackers, Draft
  File "C:\Users\Thomas\Downloads\FreeCAD_1.0.0RC1-conda-Windows-x86_64-py311 (1)\FreeCAD_1.0.0RC1-conda-Windows-x86_64-py311\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'ModuleNotFoundError'>: No module named 'DraftTrackers'
```

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
I'm guessing you've upgraded from a version where the image scaling had to be done through a macro that you customised the Sketcher Toolbar to have easy access to it, this is not a default icon in the Sketcher Wb.

All you have to do now, is File menu > Import > change to image formats > select the image and click Open

To scale the image plane, double-click it in the tree, click the Calibrate button, click two points and enter the actual size required and it's scaled, click OK to close the task dialog box. further info: https://wiki.freecad.org/Std_Import#Image_Plane

**Comment by Roy-043** [comment]
You  must have installed the macro at some point in the past. It has never been included OOTB. Just delete it and follow the advice given by @Syres916.

**Comment by luzpaz** [comment]
An aside, should the macro have showed up listed in the About info ?

**Comment by luzpaz** [comment]
@weholt can you see what macros you have installed ? https://wiki.freecad.org/Macros
