### ISSUE TITLE
Can no longer set transparency of Link faces with "Override colors" option (regression since V0.20)

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#16637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In V0.19 it is possible to set the transparency of Link faces with the "Override colors" option. In V0.20 to V1.0 this is no longer possible although per-face transparency is still displayed.

1. Create a Link to an object.
2. Right-click the Link in the Tree view.
3. Select "Override Colors".
4. Select a face of the Link.
5. Press the Edit button.
6. The color dialog opens.
7. In V0.19 (see image) there is an alpha channel input that is missing in the later versions.

![link-face-transparency-v019](https://github.com/user-attachments/assets/1b8e2776-25e7-402b-9839-ed68485e2702)

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git)
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
It's caused by #5289 because it calls `setOptions(QColorDialog::DontUseNativeDialog)` after `setOption(QColorDialog::ShowAlphaChannel)` and thus reverts the change. See also `QColorDialog::setOption()` vs. `QColorDialog::setOptions()`
