### ISSUE TITLE
BIM: Walls with door/window disappear when switching to strict IFC mode

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#16631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Walls, which host door or window, disappear from the project when switching FCstd file to srict IFC mode.

It has been confirmed by another user in thread:
https://forum.freecad.org/viewtopic.php?t=90679

See behavior:

https://github.com/user-attachments/assets/67332bc1-0288-4848-a1a2-3ef9b7b60f6e

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git)
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaiwas** [comment]
I did a quick experiment and it seems there is a difference depending on the initial construction tree.
If in addition to walls there is a level, building, etc. - the result will be slightly different.

I also noticed a strange behavior of the cancel operation (ctrl+Z). It seems that when canceling, windows are generated.


https://github.com/user-attachments/assets/483ded6f-9131-47a0-bb4a-b265389b64d5

**Comment by semhustej** [comment]
Thanks for adding more details @kaiwas 

I encountered the Undo (Ctrl+Z) operation bug too. Let's see, whether developers want us to open a new ticket with that issue or if it is related to the original one.

**Comment by yorikvanhavre** [comment]
Indeed appending a wall to an IFC project disconsiders embedded windows. That needs to be fixed.

**Comment by yorikvanhavre** [comment]
@semhustej @kaiwas can you guys test the fix above? It requires compiling FreeCAD I'm afraid...

**Comment by semhustej** [comment]
> @semhustej @kaiwas can you guys test the fix above?

Will do, Yorik. Do I understand it correctly that this commit will be available in the next set of weekly builds? I am not able to build FC myself.

Thank you.

**Comment by kaiwas** [comment]
> can you guys test the fix above?

I will also wait for the new weekly build and will definitely test it.
Thanks!

**Comment by kaiwas** [comment]
It seems the problem occurs with any "attachments".
I'll try to find other places where this happens.

They closed it too early (

https://github.com/user-attachments/assets/3acdd3e1-ec6f-4692-8b91-69b9b8a0363c

**Comment by yorikvanhavre** [comment]
>It seems the problem occurs with any "attachments". (tested on the build without making changes).

This is another issue... I'm not sure what is happening there?

**Comment by kaiwas** [comment]
> This is another issue... I'm not sure what is happening there?

I also don't know how it works at the software level.
The wall is automatically cut by the specified object. No new subtractive objects are not created.
Probably you need to look at how the property is implemented "Substraction".

But if the object to be subtracted is a roof, the entire volume located above the roof is subtracted.

**Comment by semhustej** [comment]
I tested the original file with current version of daily FreeCAD build. The issue is fixed. Thank you.

![window+opening](https://github.com/user-attachments/assets/536d4050-6cfd-4b24-bbe2-bdea283ec5e7)

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38830 (Git)
Build type: Release
Branch: main
Hash: b38c42262f58cf0587b627e7a866d3756da34dc4
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

**Comment by yorikvanhavre** [comment]
> But if the object to be subtracted is a roof, the entire volume located above the roof is subtracted.

Indeed other kinds of subtractions (and additions) are not correctly handled. This needs to be fixed as well.
