### ISSUE TITLE
TechDraw: Inserting an active view - rendering issue 

### ISSUE THREAD

**Issue by pure-machinery** [FreeCAD/FreeCAD#16638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When inserting an active view into a drawing it will add "markers" or "joints" from the assembly workbench. Additionally if you select the part and then insert an active view it will display the part green because it's selected.

![Screenshot from 2024-09-18 17-54-24](https://github.com/user-attachments/assets/24cabc38-5f9f-4e6a-b84d-41c76b103fe3)
![Screenshot from 2024-09-18 17-50-24](https://github.com/user-attachments/assets/900feeae-adba-4db2-9c18-003b4725a4e0)

### Full version info

```shell
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: makepkg
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.12.6, Qt 6.7.2, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Installed mods: 
  * BillOfMaterials 0.1.4.2
  * sheetmetal 0.4.25
  * fasteners 0.5.28
  * fcgear 1.0.0
  * OpenTheme 2024.9.1
  * IconThemes
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
What you report is to be expected. The tool takes a screenshot from the current 3D view. Nothing more, but also, nothing less. For example the axis cross, if visible, will also be included.
