### ISSUE TITLE
TechDraw: crash due to treating a windows backslash in the filespec as an escape character

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#16646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

when I use the function draw a face using an image file, when I close the program it crashes and does not exit the function anymore.
![460295196_8636626136376309_2430578925701366936_n](https://github.com/user-attachments/assets/39094bd0-0776-4e65-bff8-6e7c4c4e4262)
![458405674_1046146523630827_1504499136618388930_n](https://github.com/user-attachments/assets/61aa3a0e-93be-40d5-b300-3dd631b097ba)

### Full version info

```shell
OS: Windows 10 build 19042
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT)
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.67
  * Assembly3 0.12.2
  * Assembly4 0.50.15
  * btl 0.9.9
  * CurvedShapes 1.0.9
  * Curves 0.6.47
  * dxf-library
  * ExplodedAssembly
  * fasteners 0.5.28
  * freecad.gears 1.2.0
  * lattice2 1.0.0
  * Manipulator 1.5.7
  * PieMenu 1.8.0
  * POV-Ray-Rendering
  * QuickMeasure 2022.10.28
  * Render 2024.8.4
  * SearchBar 1.0.2
  * sheetmetal 0.4.25
  * TitleBlock 0.5.2.2

```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Just from a cursory look, this seems like assembly3 related.

**Comment by WandererFan** [comment]
The messages before that asm3 message are the interesting ones (to me!).   Something is interpreting a file spec incorrectly.   It is treating a windows backslash in the filespec as an escape character.   I would guess that "????/Patterns/cuprous.svg" has something like "C:\MyData\..." in the part we can't see. 

My Windows build environment is in pieces at the moment, so I may be a while getting to this.

**Comment by Roy-043** [comment]
Seems the same as:
https://forum.freecad.org/viewtopic.php?t=90325

**Comment by Roberto8303** [comment]
sorry i dont know how to copy and paste the errors
![458974055_494699026779749_1766689349671597208_n](https://github.com/user-attachments/assets/9c23370f-d4da-4737-865d-62bcc38ca041)
![460295193_1601325690803625_8014101411298842401_n](https://github.com/user-attachments/assets/7fc2c5e6-fe61-46e6-9432-a87ceff2e851)

**Comment by luzpaz** [comment]
@Roberto8303 Full [About](https://wiki.freecad.org/About) info please

**Comment by Roberto8303** [comment]
how can i do?

**Comment by Roberto8303** [comment]
OS: Windows 10 build 19042
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT)
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.67
  * Assembly3 0.12.2
  * Assembly4 0.50.15
  * btl 0.9.9
  * CurvedShapes 1.0.9
  * Curves 0.6.47
  * dxf-library
  * ExplodedAssembly
  * fasteners 0.5.28
  * freecad.gears 1.2.0
  * lattice2 1.0.0
  * Manipulator 1.5.7
  * PieMenu 1.8.0
  * POV-Ray-Rendering
  * QuickMeasure 2022.10.28
  * Render 2024.8.4
  * SearchBar 1.0.2
  * sheetmetal 0.4.25
  * TitleBlock 0.5.2.2

**Comment by luzpaz** [comment]
Per wandererfan in the forum:

> FWIW, the issue is caused by the combination of the backslash + the 'U' in "users". Python tries to interpret '\U' as an escape sequence, but '\U' isn't a sequence that Python understands ('\n', '\t', etc).
>
> Issues with passing windows file specs via Python have come up before. I'll have to search, but I seem to recall that the string passed to Python winds up being really ugly with 4 '\' for each backslash - something like "i am escaping the following backslash, that escapes the next backslash, that ...".

and per Roy-043 there is a similar issue in the BIM workbench
  
https://github.com/FreeCAD/FreeCAD/blob/56dbb6532a2c17db1bf08ac329fb75b8ab51ca86/src/Mod/BIM/bimcommands/BimWindow.py#L283-L285
