### ISSUE TITLE
BIM: cannot set "Auto update" option

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#16655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Start FreeCAD, create a new document, switch to BIM workbench
2. Create a new [Arch schedule](https://wiki.freecad.org/Arch_Schedule) by pressing the <kbd>Schedule</kbd> button
3. On the dialog, check `Associate spreadsheet` and `Auto update`
4. Press the <kbd>OK</kbd> button
5. On the document tree, click on your newly created schedule. The dialog opens again
6. **Expected**: `Auto update` is checked
7. **Actual**: `Auto update` is NOT checked

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git) Snap 1140
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by semhustej** [comment]
I can confirm this.

Even though 'Auto update' is not checked, the schedule is updated when changes are made to the model (when this option was enabled previously).

`OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git)
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
`
