### ISSUE TITLE
[UI] Additional lines in Catalan translation affect a Preference visualitzation

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#16712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Catalan language, in Preferences > Import - Export > STEP > Export invisible objects, there is a misalignment between the check box and its text. See attached images.

I have searched in Crowdin and the translation of this string had 2 additional lines at the end. I have corrected the translation and leaved a message to _kaktus_
I don't know if there is something else that I can do to update the translation to be available for 1.0 release. The problem is present in 1.0.0RC1 and before.

In Catalan

![Captura de pantalla_2024-09-21_20-04-50](https://github.com/user-attachments/assets/237885ac-9ba3-45e6-a611-3531193f2e64)

In English for comparison
![Captura de pantalla_2024-09-21_20-07-24](https://github.com/user-attachments/assets/2c626389-3e27-4952-8e12-94f727916651)

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git) AppImage
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Thanks. If you've made the change in crowdin, it should be in the next translation update. @yorikvanhavre will there be another translation update for RC1 ?

**Comment by kaktusus** [comment]
The problem relates directly to string translation for Catalan.
https://crowdin.com/editor/freecad/563/en-ca?view=comfortable#6590971

MiqCG did the revision of the translation. :wink:

**Comment by luzpaz** [comment]
Closing as it should be fixed in crowdin.Please re-open if it persists.
