### ISSUE TITLE
Setting rotation with "Change image" for imported PNG gets reset when dialog is opened again

### ISSUE THREAD

**Issue by tigert** [FreeCAD/FreeCAD#16735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you import an image like a technical drawing bitmap as reference, and use "Change image" feature to resize it to scale, and map it to a desired plane to orient it with your object, the mapping of plane and rotation gets reset if you open "Change image" again.

This only seems to happen with a combination where you both rotate and map the image to **YZ plane**.

If you just map, it works. If you just rotate, it works, but if you do both, that gets reset when the dialog is opened again. Also, if you map to XZ, and rotate, it also works.

### Full version info

```shell
OS: Windows 11 build 22623
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git)
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/Finland (en_FI)
Stylesheet/Theme/QtStyle: OpenDark.qss/FreeCAD Dark/Qt default
Installed mods: 
  * fasteners 0.5.29
  * FeedsAndSpeeds 0.5.0
  * InventorLoader 1.4.0
  * lattice2 1.0.0
  * MnesarcoUtils 0.2.13
  * Ondsel-Lens 2024.9.13.02
  * OpenDark 2024.3.13
  * Render 2024.8.4
  * sheetmetal 0.4.26
```

### Subproject(s) affected?

None

### Anything else?

imported bitmap: 
![image](https://github.com/user-attachments/assets/6cb8a220-ed81-40d7-85e8-dbab1a6ca277)

Rotated and mapped to YZ plane:
![image](https://github.com/user-attachments/assets/994f7771-aa94-49b0-bd38-17980ba4196c)

Click OK. Image is aligned as desired:
![image](https://github.com/user-attachments/assets/524ebfbc-fc5f-4d6d-a2fb-98e2a2ed3696)

Open "Change image" again:
![image](https://github.com/user-attachments/assets/ebedc678-0e19-499f-a74a-0438f62f7db8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
Confirmed, the code involved in matching the existing Placement of the ImagePlane to the correct representation in the Task Panel I believe is https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/TaskView/TaskImage.cpp#L289-L377
@wwmayer would you mind having a look please?

**Comment by wwmayer** [comment]
This caused by the gimbal lock: https://en.wikipedia.org/wiki/Gimbal_lock

The methods TaskImage::restoreAngles and TaskImage::updatePlacement() internally work with Euler angles which are known to suffer from gimbal locks in certain situations.

So, what happens is that these Euler angles 0 deg, -90 deg, 180 deg are used  as fallback and with them it's not possible any more to determine the correct plane and angle.

As a result it leaves the default plane of XY and the default angle of 0 deg that overwrites the previous rotation.
