### ISSUE TITLE
Chamfer size2 field has strange behavior

### ISSUE THREAD

**Issue by j8spencer** [FreeCAD/FreeCAD#16733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I'm trying to chamfer the corner shown here to a mitre on this .75" part. When I click in the Size2 field, the text box for it goes blank with a cursor bar about 4 spaces in. When I type, no numbers show up in the text box. But if I type "0.75" (but don't hit enter), the part in the view rotates to vertical.

View on text entry:
![image](https://github.com/user-attachments/assets/264ec867-8ec3-451e-80b6-5034077642b5)

View after typing ".75":
![image](https://github.com/user-attachments/assets/112c7146-6e18-4d76-8bbb-d2d5428dd5be)

Playing around, I notice that if I type "1", the view goes straight to "Front." "2" gives me Top, 3 Right, 4 Rear, 5 Bottom, etc. It seems this text box is now linked to the view selector cube in the 3D view window.

I can't seem to get the chamfer to range like I'd expect. But I'm a noob, so don't stress too much about that.

UPDATE:
I noticed there was a tack window open, but burried on the left and I couldn't see it. I was able to use that to set the chamfer distance and get it right (or close--choosing the full thickness of the part doesn't work, but .7499999 seems to be close enough). Even so, using size 2 as a view selector still works as above.

### Full version info

```shell
OS: Linux Mint 22 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * Help 1.0.3
  * A2plus 0.4.60n
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Chamfers and fillets cannot fully consume a face. The OCC geometric kernel does not allow it. So you must do what you have discovered, leave a tiny face, or alternative extrude a chamfered sketch.

"Size 2" can only be entered after changing the "Chamfer Type" to "Two distances". If set to "One distance" the "Size 2" field is read-only and user input is interpreted as a short cut. See [Std_ViewFront](https://wiki.freecad.org/Std_ViewFront) etc.

Closing this.

**Comment by j8spencer** [comment]
I fully grant using the size2 field with the chamfer set to "equal distance" is not meaningful to the tool. But are you arguing that, in that context, it's correct behavior for the size2 field to change the 3D view orientation? I think that seems like a clear bug--for text box entry to be tied to some completely different effect. I get that, in that mode, the text field is probably not accepting input and so instead, it goes directly to the view window, where the input is working as intended. But I would suggest it's a usability bug not to indicate that somehow, and maybe consider having some UI feedback that clicking in that field is not allowed under "equal distance."

**Comment by luzpaz** [comment]
@Roy-043 :point_up_2:

**Comment by Roy-043** [comment]
@luzpaz If you want you can create a new issue to improve the UI in such cases (this is not just a PD issue).

**Comment by luzpaz** [comment]
@j8spencer feel free to open a new issue per roy's suggestion.
