### ISSUE TITLE
Thread with cylinder leads to deformation

### ISSUE THREAD

**Issue by Tommy-01** [FreeCAD/FreeCAD#16757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Followed this [instruction](https://wiki.freecad.org/Thread_for_Screw_Tutorial/de#Arbeitsbereich_PartDesign) to make an thread.
Everything works until I add a cylinder at point 8. As soon as this cylinder is rendered, the structure is defomed.

Here you can see the cylinder with the thread.
![Bildschirmfoto vom 2024-09-23 20-20-04](https://github.com/user-attachments/assets/ff3a521b-191c-406d-a8f2-13981f3e94a7)

Here you can see the rendered version.
![Bildschirmfoto vom 2024-09-23 20-20-24](https://github.com/user-attachments/assets/676a73be-2c12-4535-8785-76f88acb9d0f)

The construction as a file.
[Thread_with_cylinder.FCStd.zip](https://github.com/user-attachments/files/17102439/Thread_with_cylinder.FCStd.zip)

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * fasteners 0.5.29
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
This should be fixed on 1.0RC1 or in weekly. Can you try reproducing ?  (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/1.0rc1)

**Comment by Tommy-01** [comment]
I can reproduce it.
![Bildschirmfoto vom 2024-09-23 22-21-55](https://github.com/user-attachments/assets/fc9edd63-e502-458e-b15e-8f0ee86d370e)

OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)

**Comment by FlachyJoe** [comment]
It's a known OCC bug, rotate Helix per 1° around Z-Axis in order the seam edge of the cylinder doesn't coincide anymore with the thread start.
![image](https://github.com/user-attachments/assets/8585568f-22e7-4782-af58-46938155e61a)

**Comment by Tommy-01** [comment]
I'm probably doing something wrong. If I turn the thread, the body is still deformed.

Here you see the Change an the rendered Body.
![Bildschirmfoto vom 2024-09-25 22-16-31](https://github.com/user-attachments/assets/3608b7d6-4d57-4eca-81be-afb353e3f27f)
![Bildschirmfoto vom 2024-09-25 22-16-58](https://github.com/user-attachments/assets/9eab9df4-5a9c-44ab-beb4-b78e5a0af450)

**Comment by Tommy-01** [comment]
Ah sry, now i got it. I rotated the wrong thing. As you write, rotate the Helix an now it's all right.
Thank you!
![Bildschirmfoto vom 2024-09-25 22-27-13](https://github.com/user-attachments/assets/6e3023fb-92aa-4710-91c7-114e8ba655fb)
