### ISSUE TITLE
Sketcher: When the Sketch is over constrained it is not possible to select redundant constraints by clicking on the link shown as the constraint name/number anymore

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#16768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When the Sketch has redundant constraints I cannot select the redundant constraint by clicking the constraint number.
So I cannot delete it easily. I have to track constraint place to select it.

![image](https://github.com/user-attachments/assets/b3cccc09-a0e7-486d-a212-d22214252ecf)

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git) AppImage
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.26
  * InventorLoader 1.4.0
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.0.24
  * lattice2 1.0.0
  * kicadStepUpMod 11.3.8
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Please attach the file. Without it this issue does not make sense.

**Comment by leoheck** [comment]
When the Sketch is overconstrained, it blocks some features/operations. Freecad doesn't allow me to select redundant constraints by clicking on the link referred next to the over constrained message. It doesn't allow me to add more constraints. It doesn't allow me to launch the constraint popup to be able to mark it as reference, for instance.

**Comment by Roy-043** [comment]
Please provide a file. I can't reproduce.
[redundant-constraint.FCStd.zip](https://github.com/user-attachments/files/17150087/redundant-constraint.FCStd.zip) (remove .zip)

```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38830 (Git)
Build type: Release
Branch: main
Hash: b38c42262f58cf0587b627e7a866d3756da34dc4
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

**Comment by leoheck** [comment]
It is working on your Sketch and maybe due the new version. 

I am using this now..  
```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38827 (Git) AppImage
Build type: Release
Branch: main
Hash: abd5c3ca31539f8ed37ac3dec2b9abd252a5310d
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.26
  * InventorLoader 1.4.0
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.0.24
  * lattice2 1.0.0
  * kicadStepUpMod 11.3.8
```
