### ISSUE TITLE
Pocket results in unexpected result

### ISSUE THREAD

**Issue by mavu** [FreeCAD/FreeCAD#16779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

See attached file, sketch made on surface, and any try to make a pocket (cut off a corner) with this sketch, results in twisted geometry, or doesnt' work at all.
[bugreport.zip](https://github.com/user-attachments/files/17114008/bugreport.zip)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Germany (en_DE)
Installed mods: 
  * A2plus 0.4.60n
  * btl 0.9.9
  * fasteners 0.4.66
  * Render 2023.8.18
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
OCC has known limitation with coincidences. Enlarge your sketch to fully include the existent edges and it works.
![image](https://github.com/user-attachments/assets/4ae9f9d2-aa98-4e91-acba-b782f2102f0f)
