### ISSUE TITLE
Exporting a part design body to STL or 3mf exports only up to the tip

### ISSUE THREAD

**Issue by tigert** [FreeCAD/FreeCAD#16800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

So you can set "tip" in part design hierarhy to insert stuff higher up the tree, so it gets inserted after the tip, not to the end of the tree. This is often useful, although it might be a bit advanced topic.

However, if you export the object, after selecting the "body" container, to a mesh like STL or 3mf, it gets exported only up to the tip, even though the whole body is shown in the 3d view, since setting the tip does not change the visibility of the geometry downstream in the tree.

And this is unexpected for this reason. I think the expected result is that the full Body geometry gets exported, regardless of whether the tip is set to the last entry of the tree as usual, or higher up for some reason. The tip does not define geometry, it just sets the point of insertion for new geometry, if I have understood this right.

![image](https://github.com/user-attachments/assets/f1d47d78-49b5-4f4e-9190-84360c4202f5)

### Full version info

```shell
OS: Windows 11 build 22623
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git)
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/Finland (en_FI)
Stylesheet/Theme/QtStyle: OpenDark.qss/FreeCAD Dark/Qt default
Installed mods: 
  * fasteners 0.5.29
  * FeedsAndSpeeds 0.5.0
  * InventorLoader 1.4.0
  * lattice2 1.0.0
  * MnesarcoUtils 0.2.13
  * Ondsel-Lens 2024.9.13.02
  * OpenDark 2024.3.13
  * Render 2024.8.4
  * sheetmetal 0.4.26
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This behavior is how the Tip is intended:
https://wiki.freecad.org/PartDesign_Body#Tip

Note that if you change the Tip the features after it are made invisible. So the confusion here is in part the result of user actions.
