### ISSUE TITLE
Draft: View/Toolbars show boxes without text

### ISSUE THREAD

**Issue by astrolemonade** [FreeCAD/FreeCAD#16832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/user-attachments/assets/b1978596-e9d0-427d-8b92-7be3629cdd12)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38830 (Git)
Build type: Release
Branch: main
Hash: b38c42262f58cf0587b627e7a866d3756da34dc4
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * fasteners 0.5.29 (Disabled)
  * IconThemes
  * lattice2 1.0.0
  * OpenTheme 2024.9.1
  * QuickMeasure 2022.10.28
  * Render 2024.9.25 (Disabled)
```

### Subproject(s) affected?

None

### Anything else?

Deactivating the first deactivates this:
![image](https://github.com/user-attachments/assets/770871f6-9522-4b97-955e-bb705904e3b1)
Deactivating the second deactivates this:
![image](https://github.com/user-attachments/assets/0b751f4d-ac74-4aa9-ac88-e7ece8de887a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
These widgets belong to the Draft Workbench. They should not be listed when you restarts FreeCAD.

Can you give steps how to reproduce?

**Comment by Roy-043** [comment]
Indeed, confirmed.

**Comment by raindropsfromsky** [comment]
If I activate all such nameless checkboxes, the status line gets duplicate controls!

**Comment by Roy-043** [comment]
> If I activate all such nameless checkboxes, the status line gets duplicate controls!

@raindropsfromsky Can you give a scenario for that? I can reproduce the nameless items, but I only get one for each widget.
