### ISSUE TITLE
Wendelfunktion

### ISSUE THREAD

**Issue by Hannes1962** [FreeCAD/FreeCAD#16864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The spiral function is not executed with a circular surface > the program freezes. Freecad must be restarted.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * AnimationFreeCAD 1.0.0
  * Curves 0.6.15
  * fasteners 0.4.56
  * freecad.gears 1.2.0
  * Help 1.0.3
  * Movie 2023.2.15
  * Render 2023.2.3
  * ThreadProfile 1.89.0
[/code]
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Could you test with the FreeCAD 1.0 RC2 version?
Please also add a demo file and steps how to reproduce if the issue is still present in the RC
