### ISSUE TITLE
Git revision is not updated on incremental builds

### ISSUE THREAD

**Issue by NomAnor** [FreeCAD/FreeCAD#16871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I do an incremental build without deleting my build directory, the git revision in the About dialog is not updated to my checked out commit.

This has caused confusion on a bug repot because my information showed an old commit, despite running a current checkout.

This is caused by
https://github.com/FreeCAD/FreeCAD/blob/d519f24df9931e4a98d19ee39cdcd6124ae6a7bd/src/Build/CMakeLists.txt#L12-L17
because it is not run after `Version.h` is created.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38843 (Git)
Build type: Release
Branch: main
Hash: d519f24df9931e4a98d19ee39cdcd6124ae6a7bd
Python 3.12.6, Qt 6.7.2, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.62.0
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.2.0
  * fasteners 0.5.27
```

### Subproject(s) affected?

None

### Anything else?

The `SubWCRev.py` has to run on every build because otherwise it can't detect a change in the commit hash.
But `Version.h` only needs to update when `Version.h.out` is changed. The command uses `copy_if_different` which seems to me that that was the intended behaviour.
I changed the if body to
```cmake
    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Version.h.cmake
                ${CMAKE_CURRENT_BINARY_DIR}/Version.h.in)

    add_custom_command(
        OUTPUT version_file
        BYPRODUCTS ${CMAKE_CURRENT_BINARY_DIR}/Version.h
        COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_SOURCE_DIR}/src/Tools/SubWCRev.py
            --srcdir=${CMAKE_SOURCE_DIR} --bindir=${CMAKE_BINARY_DIR}
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_BINARY_DIR}/Version.h.out
            ${CMAKE_CURRENT_BINARY_DIR}/Version.h
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/Version.h.in)
    set_source_files_properties(version_file PROPERTIES SYMBOLIC true)

    ADD_CUSTOM_TARGET(fc_version DEPENDS version_file ${CMAKE_CURRENT_BINARY_DIR}/Version.h)
```
and that seems to work. If I create a new commit, the `Version.h` file is updated, otherwise only the `SubWCRev.py` runs, but no other targets are rebuild.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benj5378** [comment]
This explains the confusion 😅
