### ISSUE TITLE
[PD] Shape is unnecessarily recomputed when Refine property is switched

### ISSUE THREAD

**Issue by FlachyJoe** [FreeCAD/FreeCAD#16874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Switching the Refine property trigger a recompute of the shape but since the refinement is a process independent of other parameters then the computed shape could be kept and reused.

It will save time for heavy feature e.g. helix. However, it requires to save the unrefined shape.

### Full version info

```shell
all
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
> It will save time for heavy feature e.g. helix. However, it requires to save the unrefined shape.

this would inflate file size unless this is only stored on cache during a session. Maybe the shape can be stored without it's mesh and only meshing would happen when switching refine.
