### ISSUE TITLE
FEM: Text document breaks some Analysis container objects

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#16873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Originally reported here: https://forum.freecad.org/viewtopic.php?t=90973

Steps to reproduce:
1. Open the file.
2. Edit the text document.
3. Use File --> Exit and confirm both save requests.
4. Restart FreeCAD and reopen the file. Material and mesh objects are broken (can't be edited).

![image](https://github.com/user-attachments/assets/c4c5e082-7e30-4a6e-bd2c-13d350e875e9)

[Minimalistic Example.FCStd.zip](https://github.com/user-attachments/files/17167637/Minimalistic.Example.FCStd.zip)

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38830 (Git)
Build type: Release
Branch: main
Hash: b38c42262f58cf0587b627e7a866d3756da34dc4
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marioalexis84** [comment]
The issue is more general and affect all FeaturePython objects since the Proxy property of the view provider is lost.
try this:
1) Create a new file
2) Add a text document and a feature python
```
App.ActiveDocument.addObject("App::TextDocument")
App.ActiveDocument.addObject("App::FeaturePython")   # the view provider property Proxy is None
````
3) Double click the text document object
4) Edit the text document.
5) Use File --> Exit and confirm both save prompts by also saving the file.
6) Restart FreeCAD and reopen the file -> FeaturePython view provider Proxy property is set to 1

Maybe @wwmayer can solve it more quickly.

**Comment by wwmayer** [comment]
The reason why GuiDocument.xml is lost:
If the user tries to close the application (or close all documents) then the destructor of Gui::Document is called where in a first step all callback functions to the boost signals are disconnected, i.e. Gui::Document::Save(Writer) cannot be called any more.

Further down in the destructor all views of the document are checked if they can be closed. This triggers the call of TextDocumentEditorView::canClose that opens the Yes/No/Cancel dialog. When pressing the Yes button the document will be saved but now without the information of the Gui::Document class.

To fix the problem TextDocumentEditorView must check if Gui::Document is about to be closed and if yes it won't pop up the dialog any more.

**Comment by FEA-eng** [comment]
There is a request to reopen this issue: https://forum.freecad.org/viewtopic.php?t=90973#p786175

But maybe a new, more general one should be created.
