### ISSUE TITLE
TechDraw: Can't use TechDraw_DimensionRepair for TechDraw_AreaDimension

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#16894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

For 'normal' dimensions you can use the TechDraw_DimensionRepair tool to change their 2D and 3D references. This is not possible for TechDraw_AreaDimensions.

1. Open the attached [file](https://github.com/user-attachments/files/17175695/td-area.FCStd.zip) (remove .zip).
2. Switch to the TechDraw Workbench.
3. Switch to the 3D view.
4. Select the area "Dimension" in the Tree view.
5. Invoke [TechDraw_DimensionRepair](https://wiki.freecad.org/TechDraw_DimensionRepair).
6. Select a face in the 3D view.
7. Press the "Replace References with Current Selection" button.
8. Result: "Incorrect Selection" warning.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38843 (Git)
Build type: Release
Branch: main
Hash: d519f24df9931e4a98d19ee39cdcd6124ae6a7bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@WandererFan FYI
