### ISSUE TITLE
FreeCAD v1.0 changelog doesn't mention incompatible data format

### ISSUE THREAD

**Issue by Zolko-123** [FreeCAD/FreeCAD#16916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With FreeCAD version 0.22 – which later might become 1.0 – a new model data format was introduced which is incompatible with previous FreeCAD versions.  This has been reported [here previously](https://github.com/FreeCAD/FreeCAD/issues/12894), and it has been reported by several users on the forum (see :

- https://forum.freecad.org/viewtopic.php?p=772681
- https://forum.freecad.org/viewtopic.php?p=754339#p754339

as of yet, none of this incompatibilities has reached the [FreeCAD v1.0 release-notes](https://wiki.freecad.org/Release_notes_1.0) 

Unfortunately, this means that the user facing this problem can't know where the problem comes from, how to circumvent it, and how to repair-it. Even long-term power-users don't know where the problem comes from and can't help regular users ::

> There have been some changes in the structure of some "objects", some properties have been renamed and some details have been changed, rationalized. Usually there is an eye on retro compatibility in the sense that an file made with an old version should work in the new version. It is not true the other way round, so "hopping" between versions will almost for sure result in a "mess".
...
Apologize for the "not resolving" and long post.

> I do wonder if the AttachmentSupport name change has something to do with this, i.e. the old name Support is now AttachmentSupport. Of coarse I have no idea if the Devs are checking for both names but it seems like they would. But, if you check for both names then why have a new name.

What's more, the files can be opened, but the parametric data is then lost. 

Therefore, it is mandatory to explain specifically the new incompatible data format, how best to avoid id, and how to repair-it

### Full version info

```shell
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git) AppImage
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US) [ OS: English/United Kingdom (en_GB) ]
Installed mods: 
  * A2plus 0.4.56a
  * CurvedShapes 1.0.3
  * fcgear 1.0.0
  * sheetmetal 0.2.50
  * TabBar
  * Render 2022.2.0
  * Curves 0.5.1
  * fasteners 0.5.21
  * Assembly4_dev 0.50.16-dev
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Done with https://wiki.freecad.org/index.php?title=Release_notes_1.0&diff=1491849&oldid=1491830

Please expand/fix if I misstated or forgot anything!
