### ISSUE TITLE
Toolbar Customize preference empty 

### ISSUE THREAD

**Issue by ONLYA** [FreeCAD/FreeCAD#16925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

As shown in the image below, the toolbar panel in the preference is empty even if the real toolbar has everything. I cannot add or remove items in the preference window. I just use the "Part Design" workbench as an example but the issue applies to all of them.
The same thing applies to the "Macro" tab: I have got one macro but it's now shown on the side panel. 
![image](https://github.com/user-attachments/assets/072a9ebc-6fed-4753-b558-3c210bcebe7a)

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (KDE/plasmawayland)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38820 (Git)
Build type: Release
Branch: releases/FreeCAD-1-0
Hash: 57a94ff4f3416725e1807eb1d7e9b2909d518a39
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.0
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: OpenLight.qss/FreeCAD Light/Fusion
Installed mods: 
  * FreeCAD-themes 2024.7.24
  * A2plus 0.4.67
  * kicadStepUpMod 11.3.9
  * sheetmetal 0.4.26
  * ProDarkThemePreferencePack 1.0.0
  * InventorLoader 1.4.0
  * Render 2024.9.25
  * OpenTheme 2024.9.1
  * ExplodedAssembly
```

### Subproject(s) affected?

None

### Anything else?

I built it myself. The CMake line is:
```bash
cmake -D BUILD_DRAWING:BOOL=ON -D BUILD_DESIGNER_PLUGIN:BOOL=ON -D BUILD_JTREADER:BOOL=ON -D FMT_DOC:BOOL=ON -D BUILD_FEM_NETGEN:BOOL=ON -D FREECAD_BUILD_DEBIAN:BOOL=ON -D FREECAD_USE_PCL:BOOL=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release ../
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Please read the documentation before creating a GitHub issue:
https://wiki.freecad.org/Interface_Customization

You cannot edit the default toolbars. You can only edit custom toolbars.

Closing this.
