### ISSUE TITLE
aditive helix problem

### ISSUE THREAD

**Issue by RodrigoTMorais** [FreeCAD/FreeCAD#16932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Problem creating helical additive "Removing splitter failed" problem. UI does not reflect parameter changes. Freecad 1.0 RC2. To reproduce: 
1- open atached file error.fcstd
2- click additive helix
3- change any value
4- click "ok" button

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Portuguese/Brazil (pt_BR)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
_Removing splitter failed_ is a Refine problem, will be fixed (hidden) by #16877
