### ISSUE TITLE
[TechDraw] Dimensions in view don't match part 

### ISSUE THREAD

**Issue by j8spencer** [FreeCAD/FreeCAD#16957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I created a view on a page with, I think, a combination of "camera view" and the "Top" arrow. I scaled the view as 1:3, and I also have a default dimension format string of "%.3w". When I add dimensions to the drawing, what should be measurements of 40.0, 41.5, and 45.0 deg. come out as 39.996, 41.499, and 45.006 deg.

Here are the view properties and the result.

![DimensionsWrong](https://github.com/user-attachments/assets/e3b5197c-7d8a-458e-9c69-13e87c9b802d)

### Full version info

```shell
OS: Linux Mint 22 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * Help 1.0.3
  * A2plus 0.4.67
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Look at your projection direction.  It is not standard Z (0,0,1), but slightly off at (0.01, -0.01, 1).   This will cause the unexpected dimensions.

**Comment by luzpaz** [comment]
Closing as PEBCAK

Note: please update to RC2. TIA
