### ISSUE TITLE
FEM: Incorrect constraint symbols and mesh for rectangular ruled surface on the XZ plane

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#16979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Originally reported here: https://forum.freecad.org/viewtopic.php?t=91105

1. Sketch a rectangle on the XZ plane (it works normally on XY).
2. Use Part Ruled Surface on the 2 long edges. Hide the Sketch.
3. Apply fixed constraint, force and mesh. All are incorrectly displayed:

![image](https://github.com/user-attachments/assets/79fccd8a-731f-4fbf-86a4-2c0f9e8d410a)

According to the OP, it happened in 0.21 too. It doesn't seem to happen with Part Make face instead of Ruled surface.

[FEM ruled surface.FCStd.zip](https://github.com/user-attachments/files/17243587/FEM.ruled.surface.FCStd.zip)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@marioalexis84 can I assign this ticket to you ?

**Comment by marioalexis84** [comment]
The problem is not FEM related, it occurs directly on the ruled surface when the sketch is not on the xy plane.
Try this example by creating the ruled surface between edge1 and edge3 of the sketch.

[fail_ruled_surface.FCStd.gz](https://github.com/user-attachments/files/17250071/fail_ruled_surface.FCStd.gz)

**Comment by FEA-eng** [comment]
I guess that's related then: #15675

**Comment by luzpaz** [comment]
@FEA-eng should we close as dupe ?

**Comment by FEA-eng** [comment]
> @FEA-eng should we close as dupe ?

That older issue mentions only offset. Maybe instead of those two issues there should be a general one like "Part Ruled surface is incorrect on the XY plane" listing the two reported problems.

**Comment by FEA-eng** [comment]
Closing in favor of #17235
