### ISSUE TITLE
Assembly: cannot create BOM if the assembly is activated

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#16972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Start FreeCAD
2. On the start page, click on the assembly example shipped with FreeCAD (backhoe) to open it
3. Double-click on the assembly in the document tree to activate it
4. Click on the BOM command
5. Failure with the following error on the report window:

```python-traceback
Running the Python command 'Assembly_CreateBom' failed:
Traceback (most recent call last):
  File "/snap/freecad/1153/usr/Mod/Assembly/CommandCreateBom.py", line 94, in Activated
    self.panel = TaskAssemblyCreateBom()
  File "/snap/freecad/1153/usr/Mod/Assembly/CommandCreateBom.py", line 146, in __init__
    self.createBomObject()
  File "/snap/freecad/1153/usr/Mod/Assembly/CommandCreateBom.py", line 335, in createBomObject
    Gui.doCommand(commands)
  File "<string>", line 1, in <module>

name 'assembly' is not defined
```

https://github.com/user-attachments/assets/28a28ddb-9178-4070-ba6e-693f525c2c24

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38844 (Git) Snap 1153
Build type: Release
Branch: main
Hash: 6e2cd4e73303f817e4bf5e908abe39030b7c5fb3
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
  * Ondsel-Lens 2024.9.13.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Assembly

### Anything else?

Workaround:
1. Start FreeCAD
2. On the start page, click on the assembly example shipped with FreeCAD (backhoe) to open it
3. Skip this step => <strike>Double-click on the assembly in the document tree to activate it</strike>
4. Click on the BOM command
5. The BOM is created outside of the assembly in the document tree: drag it inside
6. Now the BOM command can be used without error

I could reproduce the bug on a local build, on the snap package and on the daily PPA package.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Can't reproduce. This is what I see when clicking on BOM button

![Screenshot_20241002_144859](https://github.com/user-attachments/assets/f5f6237f-78ef-4821-b154-1d9dce09f729)

```shell
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git) AppImage
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Classic/Qt default
```

**Comment by furgo16** [comment]
@luzpaz thanks for testing. I could reproduce it on the snap package, on the PPA package and on a local build. I've added a screencast and a workaround to the issue description, along with a PR.

**Comment by furgo16** [comment]
@luzpaz looking at your spreadsheet, it seems you skipped step 3, which is the key step to trigger the bug.

**Comment by luzpaz** [comment]
I think I got confused because the ticket was being edited while I was checking.
