### ISSUE TITLE
TechDraw: Problem with hidden views when scaling

### ISSUE THREAD

**Issue by picli3** [FreeCAD/FreeCAD#16980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a flat piece with a circle inside that has rounded edges.

![https://i.imgur.com/6u9WZ7J.png](https://i.imgur.com/6u9WZ7J.png)

When I project the faces onto a technical sheet, these roundings look like complete circles.

![](https://i.imgur.com/zhCkUao.png)

I have seen that this is corrected if I increase the scale and it gets worse if I decrease it.

![](https://i.imgur.com/aFFyYPa.png)

I hope it's easy to solve. Thanks for all the work you've done in FreeCad

### Full version info

```shell
OS: Linux Mint 22 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git) AppImage
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Peru (es_PE)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * A2plus 0.4.66
  * kicadStepUpMod 11.2.9
  * ExplodedAssembly
```

### Subproject(s) affected?

None

### Anything else?

[Sample piece](https://drive.google.com/file/d/19p_rleQw1MOGd0f_j31UDd9Qkb-4zC_E/view?usp=sharing)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
can confirm.
@WandererFan FYI

**Comment by benj5378** [comment]
Related til #16898?
