### ISSUE TITLE
PartDesign: Threaded (UTS) hole incorrect dimension

### ISSUE THREAD

**Issue by sfornengo** [FreeCAD/FreeCAD#16984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Create a hole with UTS thread, eg 1/2
It appears half the expected dimension (maybe radius vs diameter confusion)

### Full version info

```shell
OS: Ubuntu 22.04.5 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Assembly4 0.50.12
  * ThreadProfile 1.92.0
  * freecad.gears 1.0.0
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Can you provide a screenshot or screencast perchance ?

**Comment by sfornengo** [comment]
Sorry, I think I found the problem, it is me ;/
I am working on plumbing pipes and in plumbing 1/2 = 15x21 mm so I was expected this dimensions.
Using UTS 1/2 I get a diameter of 12.7 mm.
Digging the standards of UTS and it is ok.
So it is impossible to model a plumbing fitting 1/2 with part design hole function...
Sorry for the noise
