### ISSUE TITLE
BIM: "Join base sketches of wall if possible" throws error

### ISSUE THREAD

**Issue by justluci** [FreeCAD/FreeCAD#16996]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Problem description

While the option "Join base sketches of the wall if possible" in the BIM workbench  is active, drawing an attached wall shows an error.

https://github.com/user-attachments/assets/bd5d985d-9684-428a-a1e4-c2640515bb3b

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/India (en_IN)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaiwas** [comment]
I confirm. Sketches are not merging.
