### ISSUE TITLE
Part: Attachment engines do not support App::Links

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#17022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/user-attachments/assets/d84c7776-369e-4d8d-b27b-8880e29f5539)
You can select a link in the view and task attacher is ok with that. But it offers you no mode than deactivated.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaiwas** [comment]
I don't know if we're talking about the same thing, but I have attached the link. 

https://github.com/user-attachments/assets/0d7acb32-fcc7-42b0-8c12-0b08210ca115

**Comment by kaiwas** [comment]
But if we do it through the command, not through the properties - everything works as it should.


https://github.com/user-attachments/assets/7a0ed528-fb7f-44bd-9383-813e78ac14a0
