### ISSUE TITLE
TaskAttacher: Does not take into account the attaching object position

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#17021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If the object with the attachment extension is not at the same level than the attachment support, then currently the placement is wrong : 
![image](https://github.com/user-attachments/assets/c4d58d2d-3773-4b32-83ec-0c0a8e4dec2c)
(in the above example, Part has a non-identity placement which is not taken into account for the LCS object)

This is because the attachment task is not setting the attachment support correctly. It puts only the selection subObject instead of the full path.
This can be manually edited to be correct : 
![image](https://github.com/user-attachments/assets/79bba43a-2d15-4d72-ac07-1150e814fbc3)

The attachment task should take into account the position of the attaching object and of the attached object so that the placement is correct.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FreeCAD/cad-advisory-group FYI

**Comment by luzpaz** [comment]
Weird that the version info shows '0.22' ?

**Comment by pierreporte** [comment]
Fixing this is definitely needed.
