### ISSUE TITLE
BIM: Elements disappear when switching to strict IFC mode with only Building element present (and no site)

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#17031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When there is Building object created in the file which does not contain a Site object, walls (and also other objects) disappear when users switches to strict IFC mode.

Steps to reproduce:
- open the file "building-IFC.FCstd" 
[ifc-building.zip](https://github.com/user-attachments/files/17266951/ifc-building.zip)

- switch to strict IFC mode
- walls disappear

When site object is created in the file, the conversion to strict IFC mode runs OK. When there is no building object in the file, the conversion to strict IFC mode runs OK.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

BIM

### Anything else?

The issue has been confirmed by another Linux user:
https://forum.freecad.org/viewtopic.php?t=91178

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@yorikvanhavre FYI

**Comment by luzpaz** [comment]
Per the forum thread, this was confirmed by @paullee0

**Comment by yorikvanhavre** [comment]
Confirmed too. Having a deeper look...

**Comment by semhustej** [comment]
> Confirmed too. Having a deeper look...
> 
> Ok. So what happens is this: The contents of the file are correctly converted to IFC and stored into the document. If you save the IFC file, you see the contents are there. The problem is, when switching to strict IFC, although the IFC data is created correctly, there is no object in the document to display it. I think here we should add some code to produce the site/building if needed after conversion. I'll prepare a PR

Great! I am not sure about that, but I think each "proper" (meaning good customs) IFC should have IfcSite and IfcBuildinga anyway. If FreeCAD creates that for the user, that is good.

**Comment by yorikvanhavre** [comment]
It does, but you can switch that off in the preferences.

**Comment by yorikvanhavre** [comment]
This should be addressed by https://github.com/FreeCAD/FreeCAD/pull/16948
