### ISSUE TITLE
BIM: Error when switching wall created in part design workbench to strict IFC mode

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#17032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The sample file contains simple wall created in Part Design workbench - a padded sketch. When switching to strict IFC mode, there are error messages and faulty geometry.

Steps to reproduce:
- Open file 
[wall-shape.zip](https://github.com/user-attachments/files/17266959/wall-shape.zip)

- Switch to strict IFC mode

Error messages:
```
17:59:32  Origin "wall_shape#Origin" doesn't contain feature with role "XY_Plane"
17:59:32  Origin "wall_shape#Origin" doesn't contain feature with role "XY_Plane"
17:59:32  Traceback (most recent call last):
17:59:32    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-38871-conda-Windows-x86_64-py311\Mod\BIM\nativeifc\ifc_status.py", line 70, in on_toggle_lock
17:59:32      lock_document()
17:59:32    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-38871-conda-Windows-x86_64-py311\Mod\BIM\nativeifc\ifc_status.py", line 252, in lock_document
17:59:32      doc.removeObject(n)
17:59:32  ValueError: No document object found with name 'Origin'
```
Video showing the behavior:

https://github.com/user-attachments/assets/49e3a91d-7f73-4086-999f-05bda5080750

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

BIM

### Anything else?

The error has been confirmed by another user:
https://forum.freecad.org/viewtopic.php?t=91177

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@yorikvanhavre FYI
