### ISSUE TITLE
Measure tool error

### ISSUE THREAD

**Issue by juanchibox** [FreeCAD/FreeCAD#17107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

when you do some measures, they stay in the screen(but they doesn't apear in the tree), even if you touch reset or close the measure function, the only solution for this is to close freecad and open it again.
![freecad issue](https://github.com/user-attachments/assets/84969455-5698-44f9-93c3-d296640f9356)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Argentina (es_AR)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
This has already been fixed: #16836.
