### ISSUE TITLE
Marlin Post Processor not able to write to disk

### ISSUE THREAD

**Issue by ringnutz** [FreeCAD/FreeCAD#17122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When trying to Post Process using the CAM workbench and the marlin_post.py postprocessor, the proper output is displayed on the popup dialog box, which can be copied out and saved separately, however when attempting to save the document in the save dialog box, after typing a filename and clicking save, the error

```
19:55:54  Running the Python command 'CAM_Post' failed:
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAGpzZkB/usr/Mod/CAM/Path/Post/Command.py", line 207, in Activated
    self._write_file(fname, gcode, policy)
  File "/tmp/.mount_FreeCAGpzZkB/usr/Mod/CAM/Path/Post/Command.py", line 135, in _write_file
    f.write(gcode)
```

Is shown on the console

**TO FIX THIS**, there needs to be a 
`return final`

on ~line 461 to allow proper saving

### Full version info

```shell
OS: Fedora Linux 40 (Workstation Edition) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * FreeCAD-themes 2024.7.24
  * ProDarkThemePreferencePack 1.0.0
```

### Subproject(s) affected?

CAM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ronaksingh27** [comment]
Could you please review the pull request ? I have completed the requested tasks
