### ISSUE TITLE
About box is hard to read blue text

### ISSUE THREAD

**Issue by bofdahof** [FreeCAD/FreeCAD#17126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Blue text is very hard on the eyes, almost illegible.

<img width="637" alt="Screenshot 2024-10-09 at 15 47 42" src="https://github.com/user-attachments/assets/3813bc11-95c2-47c9-b122-98dec61ddee4">

Also, copy to clipboard button is showing "hot" but OK button is not, even though it is.

I thought there was an issue recorded about the blue text, but couldn't find one. So apols if dupe.

### Full version info

```shell
OS: macOS 15.0.1
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
The issue here is that a dark color pallet should be applied, although I am not sure if links have a color from a pallet or if it is just set with code.
In QT 6.5> there should be a way to detect the dark style and apply a correct color pallet.
In current release this isn't really easy to fix since classic isn't detecting dark or light theme's.

**Comment by FEA-eng** [comment]
Better?

![dark](https://github.com/user-attachments/assets/e741d3d1-1ba0-4c64-8032-dc44ba9e72f6)

![light](https://github.com/user-attachments/assets/32d85a3e-a695-44a8-9c96-e162997bab55)

![classic](https://github.com/user-attachments/assets/fdcae7b8-2191-4525-8aee-9445f9f5034b)
