### ISSUE TITLE
datum plane problem - freeCAD 1.0RC2

### ISSUE THREAD

**Issue by juanchibox** [FreeCAD/FreeCAD#17120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

when you try to change the dimentions of a datum plane, you can't, the box become gray and you can't even slide the mouse to change it or tipe.
![datum plane issue](https://github.com/user-attachments/assets/9054eaef-127d-488f-b53d-0c0a36cd93c9)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Argentina (es_AR)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
You have to change the resize mode to Manual to be able to resize it.
