### ISSUE TITLE
Variables: Checkbox "Prefix group name" is missing in some dialogues

### ISSUE THREAD

**Issue by blank-supportgis** [FreeCAD/FreeCAD#17134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When it comes to referencing variables in expressions, you have the choice of prefixing a variable name with it's group or to just use the variable name alone. This setting is configured by setting a switch called `Prefix group name` in the variable creation dialog.

When creating a new variable set, one must enter the first variable of that set right away. Here this option is missing, so the first variable is always referenced without group.

### Full version info

```shell
OS: Ubuntu 20.04.6 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * btl 0.9.9 (Disabled)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@pieterhijma FYI

**Comment by furgo16** [comment]
This is because you're seeing two different dialogs. See the screenshot in the related issue: https://github.com/FreeCAD/FreeCAD/issues/14633. This seems like a duplicate.

**Comment by blank-supportgis** [comment]
The issue #14633 isn't exactly the same, but it's solution would likely also cover this issue. 
So, I'd say, this issue can be closed in favor of the other.
