### ISSUE TITLE
Access Violation when converting STEP files to solid

### ISSUE THREAD

**Issue by 13061951** [FreeCAD/FreeCAD#17138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Whilst Converting step files to Solid. The above message came up. I could not delete what I was converting. I had to shut the programme down and restart it. 

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * A2plus 0.4.68
  * AirPlaneDesign 0.4.1
  * Assembly4 0.50.15
  * CurvedShapes 1.0.10
  * Curves 0.6.48
  * ExplodedAssembly
  * fasteners 0.5.29
  * freecad.gears 1.3.0
  * Gridfinity 0.6.0
  * lattice2 1.0.0
  * MeshRemodel 1.10.25
  * POV-Ray-Rendering
  * Render 2024.9.25
  * sheetmetal 0.4.26
  * woodworking 0.21.2.33771
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hyarion** [comment]
Can you provide steps to reproduce the issue? (and/or a file where it happens)

**Comment by luzpaz** [comment]
@13061951 :point_up_2:

**Comment by 13061951** [comment]
Good Morning sir, I have tried several times, with no avail. I am now using the latest version and will capture as much data as I can if this happens again. Thank you for your Patients.

Kindest Regards.

Lynn Harris.
________________________________
