### ISSUE TITLE
Missing icon "Create a Shape Binder" on the toolbar.

### ISSUE THREAD

**Issue by mowczar100** [FreeCAD/FreeCAD#17135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Create a Shape Binder icon is missing from the [PartDesign Helper] toolbar. In the puldown menu, this icon is there.
![Brak Shape binder](https://github.com/user-attachments/assets/47a64b07-9d6d-492e-82f8-79c2481f2ba3)

### Full version info

```shell
FreeCAD 1.0.0RC2 and next dev too.
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
This was an intended decision
