### ISSUE TITLE
Mac: FreeCAD app icon is incorrect size

### ISSUE THREAD

**Issue by bofdahof** [FreeCAD/FreeCAD#17156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

<img width="53" alt="Screenshot 2024-10-10 at 10 50 46" src="https://github.com/user-attachments/assets/cb1d05cb-ad43-47ff-ab65-70e72419e1cd">

### Full version info

```shell
OS: macOS 15.0.1
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@bofdahof what is wrong?
![grafik](https://github.com/user-attachments/assets/2e904d9d-0068-4874-ad4e-46edcc0037b5)

**Comment by maxwxyz** [comment]
how does it look when positioning it between two dark icons?

**Comment by maxwxyz** [comment]
I guess it depends also if your OS is in dark or light mode as the bar below is differently colored, and because this is transparent it also depends on the background image. So there will no unified solution which works everywhere.

**Comment by luzpaz** [comment]
@bofdahof feel free to open a forum thread to dissect this issue further. I agree with you that there is something awkward about the icon. Maybe this can be improved for macos UI/UX.

**Comment by JohnOCFII** [comment]
FreeCAD App icon size seems consistent with other items to me.  It is true that in system dark mode, the black background does blend in overly-well to the dock, but it doesn't bother me.  Not sure if there is any sort of HIG guideline for dark app icons on dark backgrounds.

```
OS: macOS 15.0.1
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 (Git)
Build type: Release
Branch: main
Hash: e478192aa5393de9b7df190341a043f79ec6ac49
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * Curves 0.6.50
```

<img width="1358" alt="Screenshot 2024-10-12 at 3 14 11 PM" src="https://github.com/user-attachments/assets/a96cf2c0-f105-4c2e-910b-df08b85a3a39">

<img width="1423" alt="Screenshot 2024-10-12 at 3 17 53 PM" src="https://github.com/user-attachments/assets/71b7373a-5bbe-4274-ae68-3164842196e8">

**Comment by luzpaz** [comment]
JFTR, I think it's ok to nitpick this issue.

**Comment by JohnOCFII** [comment]
I've tagged this Github issue in the FreeCAD Discord channel (and sub Chanel) for the new FreeCAD logo.  https://ptb.discord.com/channels/870877411049357352/1219192793919127552

Maybe some of those folks will come over to this issue and give some input.

**Comment by maxwxyz** [comment]
The background (and therefore shape) comes from the Apple guidelines. IIRC it was discussed whether it should have a white or dark background and dark was decided.
Obviously it mostly depends on each user's personal wallpaper and there is no fit all solution that looks clean. In above screenshots, also the Firefox logo has the same "issue".

As example, here is my dock in dark and light mode. No issues here.
![Bildschirmfoto 2024-10-13 um 18 09 32](https://github.com/user-attachments/assets/35783a2b-1d58-409c-9856-0d8eb1c5b87d)
![Bildschirmfoto 2024-10-13 um 18 09 45](https://github.com/user-attachments/assets/34db5d23-e85c-4ccf-971e-6cf2dbc5bfa0)
