### ISSUE TITLE
Assembly: exploded view does not work correctly with linked assemblies

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#17208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Download the test file and extract it: [test-exploded-view-sub-new.zip](https://github.com/user-attachments/files/17349438/test-exploded-view-sub-new.zip)
2. Open the test file with FreeCAD
3. Double click on the `Assembly` assembly on the document tree to activate it
4. Click on the "Create Exploded view" command
5. Click successively on each frame part to move it away from the glass, using the transform gizmo that appears upon component selection (see screencast below)
6. Click on the "OK" button in the task panel when ready
7. Click on the newly created exploded view in the document tree. The "Exploded Views" group might need to be expanded to see it.
8. **Expected**: all frame components are exploded away from the glass, as per the moves in step 5
9. **Actual**: one frame component remains attached to the glass

https://github.com/user-attachments/assets/5ae9af43-dbd2-4c32-98a1-dda19cc81bd1

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38926 (Git) Snap 1161
Build type: Release
Branch: main
Hash: a9bff78974f301100134a13c636e23aa91be5bcf
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
  * Ondsel-Lens 2024.9.13.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Assembly

### Anything else?

- I'm aware of the work being done at https://github.com/FreeCAD/FreeCAD/pull/15629 to bring flexible subassemblies. This issue is not about the subassemblies themselves, but rather about the components attached to them.
- If instead of individually moving each frame component when creating the exploded view, the "Explode radially" option is set on the task panel, then the exploded view works as expected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
This issue will be affected by the upcoming https://github.com/FreeCAD/FreeCAD/pull/15629

**Comment by furgo16** [comment]
Thanks. Affected or fixed?

**Comment by furgo16** [comment]
Unfortunately, even after having merged https://github.com/FreeCAD/FreeCAD/pull/15629, this issue exhibits the same behavior.

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39100 (Git) Snap 1179
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
  * Ondsel-Lens 2024.9.13.02
  * Assembly4 0.50.15
```
