### ISSUE TITLE
Assembly Solver Problem

### ISSUE THREAD

**Issue by An-m1654** [FreeCAD/FreeCAD#17212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the assembly workbench in the unstable release freecad v1.0, when I make a scissor mechanism thing, the two revolute is somewhat contradicting or something. I don't know if it's my problem or the solver's problem, but it seems like when I move, it doesn't solve it, I have to manually press the z button to solve it. It doesn't show any errors, just doesn't solve it automatically.

### Full version info

```shell
OS: macOS 15.0.1
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * A2plus 0.4.68 (Not important)
```

### Subproject(s) affected?

None

### Anything else?

[Scissor Mechanism.FCStd.zip](https://github.com/user-attachments/files/17350374/Scissor.Mechanism.FCStd.zip)
[Screenshot 2024-10-12 at 10 22 01 PM](https://github.com/user-attachments/assets/a809306a-60bb-4d98-8699-ba4f02a191f8)
[Screenshot 2024-10-12 at 10 21 55 PM](https://github.com/user-attachments/assets/5b950722-389a-4224-897f-d4cd8bcc7e49)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
There are too many user errors in the file. Please start a forum topic instead.

I am closing this.
