### ISSUE TITLE
RC2 step export misfire (probably due to PD bug)

### ISSUE THREAD

**Issue by JaapStruyk** [FreeCAD/FreeCAD#17239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

drawing not exported as expected, draw a square tube, cut the end trough all and on the export the cut isn't trough all but 5mm, adding a cut of whatever kind after that and it's as it should be.
![test](https://github.com/user-attachments/assets/f12c47c3-26de-4555-8d29-c2560ff24452)

### Full version info

```shell
OS: macOS 11.7.10
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38923 (Git)
Build type: Release
Branch: main
Hash: d20cb9e6ee198beb2bfd7e72d3dec0a575e3f28c
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
Installed mods: 
  * Manipulator 1.5.7
  * sheetmetal 0.4.13
  * Curves 0.6.36
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
I think this is caused by a bug in the PartDesign Workbench: #17210. Please recompute the whole document and try exporting again.

**Comment by JaapStruyk** [comment]
Recompute indeed solves the export bug...

**Comment by luzpaz** [comment]
This is a UI issue. Should we address it ?

**Comment by Roy-043** [comment]
This has nothing to do with the GUI AFAICT. But the issue mentioned in my previous comment has been fixed.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git)
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```
