### ISSUE TITLE
Navigation: Trackball rotation around X view axis broken

### ISSUE THREAD

**Issue by TuxRobotics** [FreeCAD/FreeCAD#17246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When set to trackball, view navigation does not rotate correctly when moving the mouse vertically in the viewport.  Horizontal seems correct.  Possibly not accounting for rotation point offset?

Video:
https://github.com/user-attachments/assets/12e7e1df-e1a8-4b59-8550-0be193ee001b

Settings:
![image](https://github.com/user-attachments/assets/b3db41e0-7a2b-4439-853d-017d82d851b9)

### Full version info

```shell
OS: Linux Mint 20.3 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 (Git) AppImage
Build type: Release
Branch: main
Hash: e478192aa5393de9b7df190341a043f79ec6ac49
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@Rexbas could you take a look at this ?

**Comment by Rexbas** [comment]
yes

**Comment by Rexbas** [comment]
I did some testing yesterday and I think I can fix this by setting the spinprojector's sphere depending on the rotation center but I will also check the worldToScreen transform.

**Comment by yorikvanhavre** [comment]
@TuxRobotics can you please test if the issue is solved? Thanks

**Comment by peteristhegreat** [comment]
On a very similar note, I've found that if I have several parts that are hidden, and I am working on a new part, the center of the rotation for trackball is on the center of the the sum of the parts, not on the sum of the visible parts, or the current part.

Ideally the trackball center should map to what is visible.  Should this be it's own issue?
