### ISSUE TITLE
Fasteners Workbench not loaded

### ISSUE THREAD

**Issue by Norbert-Rotorwerk** [FreeCAD/FreeCAD#17245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The fasteners workbench is not loaded and is not available within the menu tools --> addon-manager. 

Norbert

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (MATE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.4.55
  * BOLTSFC 2022.11.5
  * parts_library.bak
  * parts_library
  * symbols_library
  * Defeaturing 1.2.0
  * 3DfindIT 1.2.0
  * Assembly4 0.12.6
  * Manipulator 1.5.0
  * MeshRemodel 1.8919.0
  * Render 2023.2.2
  * sheetmetal 0.2.61
  * Help 1.0.3
  * FEM_FrontISTR 0.1.0
  * Assembly3 0.12.2
```

### Subproject(s) affected?

Addon Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@Norbert-Rotorwerk that's a 3rd party external workbench. Please open a ticket on its appropriate bugtracker: https://github.com/shaise/FreeCAD_FastenersWB

**Comment by JohnOCFII** [comment]
> The fasteners workbench is not loaded and is not available within the menu tools --> addon-manager.

Fasteners workbench shows as available to me in the Add-on manager, and I've been able to load it successfully.  I note you have an old version of Fasteners workbench loaded.  Current version is 0.5.28 (or .29).

I'd try to unload your old version.  If that does not work, I'd suggest temporarily renaming your user.cfg and system.cfg to see if you could then use Add-on Manager to load the Fasteners workbench.

```
UserAppData
Stores user-related application data. The location for this file is:
Windows: C:\Documents and Settings\username\AppData\FreeCAD
Linux: /home/username/.FreeCAD
```

<img width="864" alt="Screenshot 2024-10-14 at 2 20 56 PM" src="https://github.com/user-attachments/assets/1b9dccd7-03c5-4542-bd3c-abff989e2c8f">
