### ISSUE TITLE
Feature: BIM_leader Filled and Close options not applicable for the tool

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#17284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Priority: very low

'Filled' option does not seem make sense for BIM_leader command in my opinion. 
![filled-BIM-leader](https://github.com/user-attachments/assets/76fcc019-bacd-45be-b023-a4e5184f7005)

'Close' option does not seem make sense for BIM_leader command in my opinion. 
![BIM_leader_close](https://github.com/user-attachments/assets/80099642-3cc1-4706-8ea8-4ea500f963f7)

Both of these options could be removed from the tool in my opinion, so that they won't confuse users.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 (Git)
Build type: Release
Branch: main
Hash: e478192aa5393de9b7df190341a043f79ec6ac49
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@paullee0 can you opine on this ? TIA

**Comment by yorikvanhavre** [comment]
Indeed, makes sense. This would be relatively easy to implement, one needs to add one more initializing option at https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/BIM/bimcommands/BimLeader.py#L38 that hides these two controls
