### ISSUE TITLE
Keine Sketcher Funktion unter 1.0.0RC2

### ISSUE THREAD

**Issue by feelman37** [FreeCAD/FreeCAD#17290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Sketcher in Part / Part Design
Nach klicken auf new part im Part Design und Klick auf Skizze erfolgt keine Reaktion. Weder werden die  x,y,z Flächen eingeblendet noch ein irgen ein andere Aktion ausgeführt.
( Windows 11 , 23H2, Nvidia 2000, xeon, 32 GB)

### Full version info

```shell
Sketcher in Part / Part Design
Nach klicken auf new part im Part Design und Klick auf Skizze erfolgt keine Reaktion. Weder werden die  x,y,z Flächen eingeblendet noch ein irgen ein andere Aktion ausgeführt.
( Windows 11 , 23H2, Nvidia 2000, xeon, 32 GB)
```

### Subproject(s) affected?

PartDesign

### Anything else?

keine Bilder vorhanden

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
* Please edit and add English translation.
* Add full [About](https://wiki.freecad.org/about) info.

**Comment by Roy-043** [comment]
Can it be that the new Body is created in an area that is not visible in the 3D view?
Please try the following:
Make the Origin object of the Body visible, Select the Body and press [Std_ViewFitSelection](https://wiki.freecad.org/Std_ViewFitSelection).
Or repeat the test in a new document.

**Comment by luzpaz** [comment]
Ping @feelman37

**Comment by luzpaz** [comment]
Closing, no response from OP
