### ISSUE TITLE
[Regression] FEM: pops up gmsh.exe window

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#17298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

* create a meh in FEM using GMSH
result: a big black window for the gmsh.exe process pops up

This is a regression to FC 0.21for which I once fixed this. The windows just has to be hidden/make invisible.

@marioalexis84 maybe you have a quick fix, otherwise I can have a look this week

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38937 (Git)
Build type: Release
Branch: releases/FreeCAD-1-0
Hash: 64d8ab5e55e14c3818aa417b7e2cd7b3ef30793e
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.0
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/windowsvista
Installed mods: 
  * A2plus 0.4.61
  * Assembly4 0.50.4
  * CfdOF 1.24.8
  * Curves 0.6.14
  * fasteners 0.4.70
  * FEMbyGEN 1.2.0
  * Manipulator 1.5.0
  * Plot 2022.4.17
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
I wonder when it occurs. I don't have this on Windows.

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38977 (Git)
Build type: Release
Branch: main
Hash: facd8ca6e0303cf96297a7a7398185770c1a1e0b
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

**Comment by donovaly** [comment]
@marioalexis84 , man thanks! I can confirm the bugs fixed the Python part. So when I generate a mesh from withing the mesh dialog, the problem is now fixed.

But there is a second part of the issue:
- open any of FC's Elmer example file and start the simulation
Then you still get the cmd.exe window popping up that runs the gmsh.exe
