### ISSUE TITLE
Robot: Example file on Start wb fails to migrate to 1.0

### ISSUE THREAD

**Issue by Samu152** [FreeCAD/FreeCAD#17303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The included example file "RobotExample.FCStd" fails to migrate on multible newer versions.

Console output:
15:19:00  Sketch: This feature is deprecated and won't be longer supported in future FreeCAD versions
15:19:00  Bein1: No object linked
15:19:00  Bein2: No object linked
15:19:00  Bein3: No object linked
15:19:00  Bein4: No object linked
15:19:00  PartToWork: No object linked

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38977 (Git)
Build type: Release
Branch: main
Hash: facd8ca6e0303cf96297a7a7398185770c1a1e0b
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Austria (de_AT)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

None

### Anything else?

https://forum.freecad.org/viewtopic.php?p=787404#p787404

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hyarion** [comment]
How about dropping the robot example file(s) for 1.0?
We can add it later if someone fixes the issues.

**Comment by adrianinsaval** [comment]
> How about dropping the robot example file(s) for 1.0? We can add it later if someone fixes the issues.

yeah that's better than shipping a broken model IMO

**Comment by Samu152** [comment]
https://forum.freecad.org/viewtopic.php?p=787404#p787404

It looks like someone actually fixed the file.
