### ISSUE TITLE
[Feature Request] Make it easier to figure out reason for wire not closed 

### ISSUE THREAD

**Issue by symdeb** [FreeCAD/FreeCAD#17301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

it extremely difficult to figure out this kind of error. (Beginner), there is hardly any way to figure out where the violation is.
This occurred when attempting to pad a fully constrained sketch

### Full version info

```shell
[code]
OS: Ubuntu 24.10 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Sketcher

### Anything else?

I could not understand why a design was fully constraint, the drawing did not show any loose ends . After several hours, found out the reason was a duplicated line. The way I found out was deleting some portions of the sketch and run the geometry checks for each step. 

Feature request:

1, For example (in Kicad),clicking somewhere  where there are two objects it ask you to  select which one to select.
AND/OR
2. In the error report the coordinates of where the error is and the line number, my report shows "edgeXX" but there was no line with such number in the sketch
AND/OR
4. In error report highlight the item in the sketch  that have conflicts in a different color.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
There is a validate sketch tool which highlights the points and in the new version the coincident points are red, so all unconnected points are white in Sketcher. You can try out the 1.0 release candidate or the weekly version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

Also, double clicking an edge selects now all connected edge loops in Sketcher so this might help too.
