### ISSUE TITLE
PartDesign: pad cannot be created deep down in object's tree 

### ISSUE THREAD

**Issue by herrdeh** [FreeCAD/FreeCAD#17316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello,

when trying to add a pad-to-face close to the root of a complex body, I cannot select the faces required.

See file attached:
Sketch 03-06 should pad to face6
Sketch 03-07 should pad to face7

In order to do so, I need to 
* make feature 02 visible
* select sketch 03-06
* click "pad"
* select "to surface"

But now, all features 05 to 09 are visible, surfaces from feature 02 cannot be selected. Feature 02 cannot be made visible with open pad dialogue.

IMHO, when working at a sketch down in hierachy, feature one level below must be visible; in this case sketches are placed between feature 02 and 03, so 02 must be visible.

Hope I was clear enough.

Cheers,
Wolf  

[deep-pad.zip](https://github.com/user-attachments/files/17428760/deep-pad.zip)

### Full version info

```shell
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38984 (Git)
Build type: Release
Branch: main
Hash: 9806a463246f5a0daf5d87b323ab8c06a97feba2
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/Classic/Qt default
Installed mods: 
  * 3D_Printing_Tools
  * Assembly4 0.50.12
  * dodo 1.0.1
  * ExtremeProLight 1.6.0
  * Curves 0.6.29
  * BOLTSFC
  * nurbs
  * animation
  * IconThemes
  * lattice2 1.0.0
  * ProDarkThemePreferencePack 1.0.0 (Disabled)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
You need to change the Tip to feature 02 for this to work:
https://wiki.freecad.org/PartDesign_Body#Tip
