### ISSUE TITLE
Assembly: the little coordinate systems to move parts disappear

### ISSUE THREAD

**Issue by peter-ch** [FreeCAD/FreeCAD#17311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I'm running RC2 on Windows 10. The little coordinate systems of all objects in the assembly just disappeared and I can't bring them back, so I can't move anything. Only right-click on the tree view and transform works, but why are they gone? This cripples my workflow, I can't basically continue when it happens. The last time this happened I created an object with PartDesign and added it to the assembly. Is it something to do with PartDesign? 

I saved my project and it seems the problem is saved along with the file because when I open it I still can't move anything. 

![image](https://github.com/user-attachments/assets/651d7dd9-981e-4840-8fc8-d406b58b4ebb)

### Full version info

```shell
FreeCAD 1.0 RC2
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
try double clicking your assembly object to activate it

**Comment by peter-ch** [comment]
Thanks, that worked. 

I tried before right-click and set "Active Object" but that didn't work.

**Comment by adrianinsaval** [comment]
> Thanks, that worked.
> 
> I tried before right-click and set "Active Object" but that didn't work.

@PaddleStroke shouldn't this work too?

**Comment by maxwxyz** [comment]
works too. In the screenshot it is not activated. Closing this issue.
