### ISSUE TITLE
Addon Manager Welcome screen not very welcoming

### ISSUE THREAD

**Issue by bofdahof** [FreeCAD/FreeCAD#17317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

<img width="494" alt="Screenshot 2024-10-18 at 17 07 08" src="https://github.com/user-attachments/assets/131f5f04-511e-4108-ad00-829a4abafce0">

The Welcome screen is -_**extremely**_- defensive.

1. To start a feature with a bright red (truncated (!)) disclaimer is disturbing.
2. To front and centre "Download Settings" is weird. Proxies? Huh? These seem like really left-field, rare, issues. Surely there is a default situation that works for 90+% of users.
3. Does a user really need detailed instructions to go to preferences? This message could apply to almost anything in FreeCAD. Very strange.

This is not comforting for users: Is there something wrong with add-on manager that it needs all these caveats? Can it be trusted?

### Full version info

```shell
OS: macOS 15.0.1
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamesHodgkins** [comment]
Personally while I agree with the formatting issues. The warning being red and bold is there to inform the user that running 3rd party add-ons is inherently risky. Also the user may not be aware that these add-ons are maybe unofficial

**Comment by luzpaz** [comment]
It's fair feedback. We all know that the Addon Manager is a WIP and certainly needs more work and polish. 

Proposals / mockups are appreciated.

**Comment by JamesHodgkins** [comment]
Are we proposing something simpler like below is preferred?

![Screenshot 2024-10-21 205744](https://github.com/user-attachments/assets/4082010f-4194-44cd-a41d-3879c5331a5a)

**Comment by JamesHodgkins** [comment]
Any thoughts @luzpaz ?

**Comment by JamesHodgkins** [comment]
For reference, I’ve created a [forum post](https://forum.freecad.org/viewtopic.php?t=91564) to facilitate further discussion.

**Comment by chennes** [comment]
@FreeCAD/design-working-group

**Comment by MisterMakerNL** [comment]
Good review, I'd say instead of red bold text, we should do a mandatory checkbox that you need to check that you have read the text.
From a legally standpoint this seems wise. 
Making it big and red doesn't mean people will actually read it. Adding a checkbox at least requires the user to acknowledge it is there. And if they check it without reading it it definitely is on them.

**Comment by obelisk79** [comment]
A check box is not required here. This isn't a legal document and we aren't a corporation with lawyers and 'fair terms of use'... click ok is enough acknowledgement and eliminates unnecessary user interaction.

**Comment by JamesHodgkins** [comment]
![Screenshot 2024-10-22 200726](https://github.com/user-attachments/assets/9171c847-05c8-4f8e-97af-0d24c011decf)

**Comment by hyarion** [comment]
@maxwxyz this can be closed now since https://github.com/FreeCAD/FreeCAD/pull/17518 has been merged

**Comment by luzpaz** [comment]
Thanks to @bofdahof for the report and @JamesHodgkins for the fix. :+1:
