### ISSUE TITLE
Draft: Trimex on B-spline or Bezier curve produces errors

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#17346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Priority: low

When trying to Draft_Trimex B-Spline or Beziere curve, FreeCAD outputs error. Steps to reproduce:

Steps to reproduce:

- Open file 
[b-spline-bezier.zip](https://github.com/user-attachments/files/17446758/b-spline-bezier.zip)

- Select B-spline or Beziere curve
- Start Draft_Trimex
- Type in distance and hit enter
- Error shows up

See behavior in the video:

https://github.com/user-attachments/assets/317f54d2-d8e5-495e-a32e-25045ab9cb09

**Proposed change:**
Post a message: `Trimex is not supported on this type of object.`

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38991 (Git)
Build type: Release
Branch: main
Hash: ef2156d0f6d116b1642a5531a2d44fc6b7d17042
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can confirm. @Roy-043 I guess B-Splines are not supported yet?

**Comment by yorikvanhavre** [comment]
Indeed b-curves are not supported by that tool yet. Maybe we could just add a warning for now?

**Comment by semhustej** [comment]
> **Proposed change:**
> Post a message: `Trimex is not supported on this type of object.`

Yes, that is proposed solution for both  B-splines and Beziere curves too:

Proposed change:
Post a message: `Trimex is not supported on this type of object.`
