### ISSUE TITLE
3DConnexion support aint alright

### ISSUE THREAD

**Issue by APOS80** [FreeCAD/FreeCAD#17352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Using a spacemouse in FreeCAD is not helping as it doesnt seem to be implemented well.

It would be nice to be able to fly fpv around an object, its the natural way to us it in other software.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Swedish/Sweden (sv_SE)
Installed mods: 
  * BIM 2021.12.0
  * QuickMeasure 2022.10.28
  * Trails 2022.1.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
please try it on the dev build: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds or the 1.0 release candidates

**Comment by luzpaz** [comment]
Closing. If issues persist, please specify what they are.

**Comment by APOS80** [comment]
Flying can be set tp fpv now but speed is a problem.

Even if i set to slowest its a bit fast, I recomend to set it lower in code,

**Comment by luzpaz** [comment]
@APOS80 can you open a new ticket for that ? please add your full [About](https://wiki.freecad.org/About) info to it
