### ISSUE TITLE
The sectional view is wrong

### ISSUE THREAD

**Issue by entkon** [FreeCAD/FreeCAD#17380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The sectional view is shown incorrectly or twisted. The link is below, and you can download the part (![FreeCAD22 K011](https://github.com/user-attachments/assets/5c9e5b51-9c84-4f16-b15f-1633cfd860a8)) .
https://entkon.de/freecad22-part-design-klassische-konstruktion/

### Full version info

```shell
OS: Windows 11 build 22000
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38977 (Git)
Build type: Release
Branch: main
Hash: facd8ca6e0303cf96297a7a7398185770c1a1e0b
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.65
  * Assembly4 0.50.13
  * CurvedShapes 1.0.9
  * Curves 0.6.39
  * dodo 1.0.1
  * fasteners 0.5.23
  * freecad.gears 1.2.0
  * sheetmetal 0.4.18
  * toSketch 1.0.1
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by entkon** [comment]
Here you can download the 3D file.
https://entkon.de/freecad22-part-design-klassische-konstruktion/

![FreeCAD22_K0011_b](https://github.com/user-attachments/assets/6a1e777e-252f-4045-85f6-401a9be3ded8)

**Comment by maxwxyz** [comment]
@WandererFan FYI

**Comment by WandererFan** [comment]
Those lines in A-A are supposed to be there.  They are behind the section profile.

![FreeCAD22 K011_projectCutShapes](https://github.com/user-attachments/assets/b26c56ef-6106-4280-bfea-b806bfc7be33)
![FreeCAD22 K011_cutshape](https://github.com/user-attachments/assets/45572f2a-aab6-4630-9a71-2d5025f29324)

**Comment by WandererFan** [comment]
For section B-B the problem seems to be that the cutting wire (Sketch011) has only 1 edge.   Not sure that this case was ever envisioned.

As a work around, if you split the cutting wire into 2 edges, you'll get a proper result, but you'd get the same result from a simple section view at section origin (0, 88, 0).

![FreeCAD22 K011_sectBBmwe_2edges](https://github.com/user-attachments/assets/d2794961-0640-492b-99c6-a388040b774a)

**Comment by entkon** [comment]
In my opinion, the toggle works for Section AA.
![00000](https://github.com/user-attachments/assets/38a88aad-5b8a-4603-b7a6-9fbd2c70cb92)

**Comment by entkon** [comment]
In Section BB, the display is correct, except for the rectangles I marked, which in my opinion should not be present in this direction.
![11111](https://github.com/user-attachments/assets/f8936777-39c0-46f0-a354-6bb2bd60926d)

**Comment by entkon** [comment]
Wenn ich das umschalte (auf dem Bild in Rot markiere), wird der Schnitt verdreht. Diesen Fehler wollte ich melden.
![22222](https://github.com/user-attachments/assets/654468a8-4fd8-44be-a4e9-58bde1123311)

**Comment by entkon** [comment]
When I toggle this (mark it in red on the image), the section is distorted. I wanted to report this error.
![22222](https://github.com/user-attachments/assets/7eb9a651-a921-4fb5-bf06-c98960e4e753)

**Comment by luzpaz** [comment]
> When I toggle this (mark it in red on the image), the section is distorted. I wanted to report this error.  

Is this a different issue ?

**Comment by entkon** [comment]
No, this is still an initial error. I tested these issues with the latest version. The error is fixed, but in my opinion, an incorrect display remains, which I can hide.

Nein, das ist noch ein anfänglicher Fehler. Ich habe diese Fehler mit der neuesten Version ausprobiert. Der Fehler ist behoben, aber meiner Meinung nach bleibt eine falsche Darstellung, die ich ausblenden kann.
![11111](https://github.com/user-attachments/assets/b8abc567-5e91-4c42-b33f-7bf2978e062f)
![22222](https://github.com/user-attachments/assets/ea2abba4-f6c6-4024-b4d5-016a9250a40a)




OS: Windows 11 build 22000
Architecture: x86_64
Version: 1.1.0dev.39141 (Git)
Build type: Release
Branch: main
Hash: 4bd80bdcbb97d6038bc7030aed9ecebf57f4e428
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.65
  * Assembly4 0.50.13
  * CurvedShapes 1.0.9
  * Curves 0.6.39
  * dodo 1.0.1
  * fasteners 0.5.23
  * freecad.gears 1.2.0
  * sheetmetal 0.4.18
  * toSketch 1.0.1

**Comment by entkon** [comment]
No, this is still an initial error. I tested these issues with the latest version. The error is fixed, but in my opinion, an incorrect display remains, which I can hide.

Nein, das ist noch ein anfänglicher Fehler. Ich habe diese Fehler mit der neuesten Version ausprobiert. Der Fehler ist behoben, aber meiner Meinung nach bleibt eine falsche Darstellung, die ich ausblenden kann.
![11111](https://github.com/user-attachments/assets/da7637c5-04b3-4e9b-a5d4-e85b91a96232)
OS: Windows 11 build 22000
Architecture: x86_64
Version: 1.1.0dev.39141 (Git)
Build type: Release
Branch: main
Hash: 4bd80bdcbb97d6038bc7030aed9ecebf57f4e428
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.65
  * Assembly4 0.50.13
  * CurvedShapes 1.0.9
  * Curves 0.6.39
  * dodo 1.0.1
  * fasteners 0.5.23
  * freecad.gears 1.2.0
  * sheetmetal 0.4.18
  * toSketch 1.0.1
![22222](https://github.com/user-attachments/assets/af3099c6-ccd2-48d4-a76a-d3bdf79d20b3)
