### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by gatvol-carel** [FreeCAD/FreeCAD#17401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

mm Measurements suddenly doubled all my values e.g. 10 mm suddenly changed to 20 mm. This is the case on all my previous files as well. A hole that should be 10 mm is now 20 mm, but still prints as 10 mm in Ultimaker Cura. I am on Ubuntu 24.04.1 and Freecad 0.21.2

### Full version info

```shell
[code]
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) Snap 908
Build type: Release
Branch: tag: 0.21.2
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/South Africa (en_ZA)
[/code]
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
> Branch: tag: 0.21.2

We're not addressing 0.21.x bugs. Please install RC2 and report if you can reproduce (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/1.0rc2).

Closing for now.
