### ISSUE TITLE
CAM: Wrong translation of "climb cut" / "conventional cut" to german

### ISSUE THREAD

**Issue by rmu75** [FreeCAD/FreeCAD#17408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

German translation of climb/conventional is backwards. "climb" should be "Gleichlauf" and "conventional" should be "Gegenlauf". This was probably introduced when renaming cut direction from "clockwise" / "counterclockwise". I don't know about other languages .

https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/CAM/Gui/Resources/translations/CAM_de.ts#L1351 et al.

### Full version info

```shell
OS: KDE neon 6.2 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Austria (de_AT)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * sheetmetal 0.5.2
  * WB_Organizer 2024.1.29
  * btl 0.9.9
  * CamScripts
```

### Subproject(s) affected?

CAM

### Anything else?

 https://de.wikipedia.org/wiki/Fr%C3%A4sen
https://en.wikipedia.org/wiki/Milling_cutter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Translation edits are made through Crowdin, see:  
https://crowdin.com/editor/freecad/32192/en-de?view=comfortable&filter=basic&value=0#q=Climb

**Comment by rmu75** [comment]
Ok, already did that -- we'll see what happens next ;)

**Comment by luzpaz** [comment]
Then we'll close this ticket since those changes will get merged before the next release. Thank you for your contribution.
