### ISSUE TITLE
How to globally set the Z-axis direction down in FreeCAD?

### ISSUE THREAD

**Issue by mylysddp** [FreeCAD/FreeCAD#17411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently, the Z-axis direction in FreeCAD is set to upwards by default. If I want to change the Z-axis direction to downwards in certain scenarios, how can I do that? And how can I globally modify the Z-axis direction to point downwards?

### Full version info

```shell
1.0
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please use the forum for help request. There is no 'upwards' definition. You can create parts in any orientation. You can rotate or mirror parts too. I don't see an issue here.
