### ISSUE TITLE
[Regression] CAM: mm/min function is no longer available

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#17451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Why is it no longer possible to set the display of movements and speed to mm/min but only mm/sec?

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38923 (Git)
Build type: Release
Branch: main
Hash: d20cb9e6ee198beb2bfd7e72d3dec0a575e3f28c
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: Dark-blue.qss/FreeCAD Classic/Qt default
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * FreeCAD-themes 2024.7.24
  * Glass
  * IconThemes
  * OpenTheme 2024.9.1
  * PieMenu 1.8.1
  * Render 2024.9.25
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Is this a regression ?

**Comment by Roberto8303** [comment]
Yes, in the old versions I could set it now not

**Comment by luzpaz** [comment]
@Roberto8303 can you screenshot or mention the workflow you used previously to enable this feature ?

**Comment by Syres916** [comment]
@Roberto8303 the Units Schema which 'chooses' whether it be _mm/s_ or _mm/min_ to be shown has been enhanced during the last development cycle. Previously it was a Global setting applied to any document created or opened, now there is a `System` wide setting for new documents in _Preferences > General > Default unit system_ and the `Document` level setting which is saved with the doc, this is set using the push button in the bottom right hand corner as per:

![CAM_UnitsSchema](https://github.com/user-attachments/assets/b4c7b54e-a2cb-459d-82d8-ab331cf83edb)

**Comment by Syres916** [comment]
The enhancement is listed in the [Release Notes](https://wiki.freecad.org/Release_notes_1.0#User_interface) (find under **Further user interface improvements**) , though I can see why it maybe missed in the large list of changes

**Comment by luzpaz** [comment]
Thanks syres. Closing.
