### ISSUE TITLE
FreeCAD RC2 on MacOS 15.0 (M1 CPU): Crashes on start when starting through selecting a file in Finder

### ISSUE THREAD

**Issue by HuibSmeets** [FreeCAD/FreeCAD#17504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I navigate to a FreeCAD file in Finder and open the file (double click) FreeCAD starts up as expected, shows briefly the splash screen and then it crashes and a MacOS bug report is shown. It's not file specific, it happens with any file previously created in FreeCAD.

When I start FreeCAD from the dock/launchpad and open a file then all is fine.

### Full version info

```shell
OS: macOS 15.0
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Render 2024.8.4
  * A2plus 0.4.67
  * fasteners 0.5.28
  * lattice2 1.0.0
  * sheetmetal 0.4.25
  * Curves 0.6.47
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should be fixed in the latest weekly: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
