### ISSUE TITLE
Extremly slow in saving dialog

### ISSUE THREAD

**Issue by brenard** [FreeCAD/FreeCAD#17514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I try to save a project, or save an export, the saving dialog is extremely slow (but its works). I have the same problem with the version included in Debian Bookworm (0.20.2), the 0.20.2 Appimage version and event if with latest Appimage version (0.21.2).

![Screenshot from 2024-10-26 19-37-54](https://github.com/user-attachments/assets/a7ba07d8-21ab-4fd4-85e8-296d681eadf8)

After a while, I can save my project (or an export) and all start to run smoothly again.

### Full version info

```shell
[code]
OS: Debian GNU/Linux 12 (bookworm) (GNOME/gnome-xorg)
Word size of FreeCAD: 64-bit
Version: 0.20.2.
Build type: Release
Python 3.11.1, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * fasteners 0.3.46
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
> Version: 0.20.2

Ancient history.
Download RC2 https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/1.0rc2

Closing. If issue persists for some reason, please notate ticket

**Comment by brenard** [comment]
Same problem with the 1.0.0RC2 release:
![Screenshot from 2024-10-27 11-23-29](https://github.com/user-attachments/assets/54f4f93a-53af-4e12-b6e1-e286aaa1ed90)
