### ISSUE TITLE
Expressions parse octal with leading zero (For what?)

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#17555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In all expressions, if we specify zero at the beginning of the expression (in combination with numbers no more than 8), we have a chance to get a value in the octal system.
Most likely, this is not an error, but in case of accidentally pressing zero when entering, we will get a value that is not typical for CAD (at least I can’t imagine where this might be required)

In this case, the expression itself is converted to the decimal system and there is no way to identify what value was entered initially.

Demonstration on video.

https://github.com/user-attachments/assets/76e102ff-3b98-47ed-9b57-57ff6808de5d

Probably not exactly a bug, but certainly not the expected behavior. Sometimes leading zero (or several) in decimal is useful for sorting (in spreadsheets).

Hexadecimal is converted to a string where it is available (for example, in spreadsheets)

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git) AppImage
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * FreeCAD_SketchArch
  * lattice2 1.0.0
  * PitchedRoof
  * addFC 0.7.4
  * OpenTheme 2024.9.1
```

### Subproject(s) affected?

Expressions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hyarion** [comment]
I can reproduce this on macos

<details><summary>full version</summary>
<p>

```
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git)
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * fasteners 0.5.29
  * sheetmetal 0.4.26
  * Curves 0.6.51
```

</p>
</details> 

My knowledge is really limited when it comes to lexers, but I think it is due to strtoll being used with 0 as base (auto detect):
https://github.com/FreeCAD/FreeCAD/blob/main/src/App/ExpressionParser.l#L343

Since this is only for one or more digits, hex can't be used, only octal and decimal, therefore I believe this is a bug.
