### ISSUE TITLE
Weekly build 39092 conda macOS arm64 py311 "damaged" won't run

### ISSUE THREAD

**Issue by crunchysteve** [FreeCAD/FreeCAD#17568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Drag from disk image to 2020 M1 (ARM64) MacBook Air Applications folder, I get this dialog.

<img width="273" alt="Screenshot 2024-10-30 at 5 12 06 PM" src="https://github.com/user-attachments/assets/89bbe3ce-35ea-437b-ae30-b388ac85b14f">

Version 1.0.0RC2 runs fine but wanted to try the weekly release to see if there are any improvements.

### Full version info

```shell
FreeCAD_weekly-builds-39092-conda-macOS-arm64-py311.dmg
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
See https://github.com/FreeCAD/FreeCAD-Bundle/pull/293#issuecomment-2298014913 for now until the weekly builds are signed

**Comment by crunchysteve** [comment]
That worked, thanks :-)
