### ISSUE TITLE
FEM: Save Geometry Ids in ElmerFEM

### ISSUE THREAD

**Issue by domcivocato** [FreeCAD/FreeCAD#17569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello,

I wanted to ask if it is possible to add a line in the .sif file as a default. Now im adding the line always by hand, but when making changes i need to do this every time i rewrite the .sif file. For experienced developers this might be a workload of seconds and might add this small commit to a larger PR.  

The line in question is the following:

**Save Geometry Ids = Logical True**

It is in the Solver Section with Equation "ResultOutput". This is necessary for further post-processing.
The whole section would look like this then:

Solver 2
  Ascii Output = Logical True
  Coordinate Scaling Revert = Logical True
  Equation = String "ResultOutput"
  Exec Solver = String "After simulation"
  Output File Name = File "FreeCAD"
  Procedure = File "ResultOutputSolve" "ResultOutputSolver"
  Vtu Format = Logical True
  Vtu Time Collection = Logical True
  **Save Geometry Ids = Logical True**
End

Thanks for your time!

### Full version info

```shell
OS: TUXEDO OS 3 (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Qt default
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@FEA-eng FYI
