### ISSUE TITLE
Expressions: No way to move a string to a stringlist when using expressions (solution exists in docs)

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#17607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The documentation does not provide a way to wrap a string in a stringlist when using expressions.
The method used for formatting strings in Python does not work. However, the strings are wrapped in the preview.
![Снимок экрана_20241101_133249](https://github.com/user-attachments/assets/d4222ade-db36-4db4-81c7-d70d3034b348)
![Снимок экрана_20241101_133307](https://github.com/user-attachments/assets/e9d21abb-7adf-4e5f-aa18-d39bc44c3227)

There must be some way, because without expressions we can wrap lines.
![Снимок экрана_20241101_133940](https://github.com/user-attachments/assets/ed791ea4-622b-4bcc-868a-a1950477a995)

A test file is attached. Remove the zip extension.
[Text_expressions.FCStd.zip](https://github.com/user-attachments/files/17598733/Text_expressions.FCStd.zip)

### Full version info

```shell
any versions
```

### Subproject(s) affected?

Expressions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
You can use:
`list(<<a>>; <<b>>; <<c>>)`

The list function is documented:
https://wiki.freecad.org/Expressions#Object_creation_functions

**Comment by Roy-043** [comment]
The Draft_Text and Draft_Label object store multi-line texts as a list of strings. But properties of this type may be used for other purposes as well. It would not be correct to say that `;` produces a linebreak, it just separates arguments here.

**Comment by kaiwas** [comment]
> The Draft_Text and Draft_Label object store multi-line texts as a list of strings. But properties of this type may be used for other purposes as well. It would not be correct to say that `;` produces a linebreak, it just separates arguments here.

Yes. It's all complicated because the same recipes work differently in different places. And it's not just about this case (((
I hope that someday everything will be more stable and predictable.

Again - many thanks for the tip!

Should I close the topic?
