### ISSUE TITLE
Appimage 39100: black screen when New file is created and crash when opening a file

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#17618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When File > New is clicked or any new file type button of the Start window are clicked, a totally black screen appears. FreeCAD is still running and you can close the file through File menu > Close.
If you try to open one of the provided examples, FreeCAD crashes
Tests made with a fresh install (FreeCAD folders of .cache , .config and .local/share deleted).

https://github.com/user-attachments/assets/8ee786e2-7e70-452d-9106-dad1e306a551

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.1.0dev.39100 (Git) AppImage
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

None

### Anything else?

Terminal output of the attached screencast:

`$ ./FreeCAD_weekly-builds-39100-conda-Linux-x86_64-py311.AppImage 
FreeCAD 1.1.0, Libs: 1.1.0devR39100 (Git)
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Coin warning in cc_glglue_instance(): Error when setting up the GL context. This can happen if there is no current context, or if the context has been set up incorrectly.
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLShaderProgram: could not create shader program
Vertex shader for simpleShaderProg (MainVertexShader & PositionOnlyVertexShader) failed to compile
QOpenGLShader: could not create shader
Fragment shader for simpleShaderProg (MainFragmentShader & ShockingPinkSrcFragmentShader) failed to compile
Errors linking simple shader: 
QOpenGLShaderProgram: could not create shader program
Vertex shader for blitShaderProg (MainWithTexCoordsVertexShader & UntransformedPositionVertexShader) failed to compile
QOpenGLShader: could not create shader
Fragment shader for blitShaderProg (MainFragmentShader & ImageSrcFragmentShader) failed to compile
Errors linking blit shader: 
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
Could not link shader program:
 ""
Coin warning in cc_glglue_instance(): Error when setting up the GL context. This can happen if there is no current context, or if the context has been set up incorrectly.
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
Coin warning in cc_glglue_instance(): Error when setting up the GL context. This can happen if there is no current context, or if the context has been set up incorrectly.
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
Coin warning in cc_glglue_instance(): Error when setting up the GL context. This can happen if there is no current context, or if the context has been set up incorrectly.
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
QOpenGLTexture::setMaximumAnisotropy() requires GL_EXT_texture_filter_anisotropic
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f1866e79050]
#1  /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so(+0x5ba6e0) [0x7f185a9ba6e0]
#2  /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so(+0x1cb322) [0x7f185a5cb322]
#3  /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so(+0x1cb6f5) [0x7f185a5cb6f5]
#4  /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so(+0x168e83) [0x7f185a568e83]
#5  /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so(+0x26af22) [0x7f185a66af22]
#6  /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so(+0x26c69f) [0x7f185a66c69f]
#7  0x7f18259faf7d in PartGui::SoBrepFaceSet::VBO::render(SoGLRenderAction*, SoGLCoordinateElement const*, int const*, int, int const*, int, SbVec3f const*, int const*, SoMaterialBundle*, int const*, SoTextureCoordinateBundle*, int const*, int, int, int) from /tmp/.mount_FreeCAfGfMeF/usr/lib/./PartGui.so+0x5dd
#8  0x7f18259fed18 in PartGui::SoBrepFaceSet::GLRender(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/lib/./PartGui.so+0x11e8
#9  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#10  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#11  0x7f18666d54e8 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x68
#12  0x7f186688cb9a in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0xea
#13  0x7f18668faa52 in SoSwitch::doAction(SoAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x2a2
#14  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#15  0x7f1869e8eb86 in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x626
#16  0x7f1869e8ef90 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x70
#17  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#18  0x7f1869e8eb86 in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x626
#19  0x7f1869e8ef90 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x70
#20  0x7f18666d54e8 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x68
#21  0x7f186688cb9a in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0xea
#22  0x7f18668faa52 in SoSwitch::doAction(SoAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x2a2
#23  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#24  0x7f1869e8eb86 in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x626
#25  0x7f1869e8ef90 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x70
#26  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#27  0x7f1869e8eb86 in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x626
#28  0x7f1869e8ef90 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x70
#29  0x7f18666d54e8 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x68
#30  0x7f186688cb9a in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0xea
#31  0x7f18668faa52 in SoSwitch::doAction(SoAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x2a2
#32  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#33  0x7f1869e8eb86 in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x626
#34  0x7f1869e8ef90 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x70
#35  0x7f18668dc29b in SoGroup::GLRender(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x21b
#36  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#37  0x7f1869e8e412 in Gui::SoFCUnifiedSelection::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x22
#38  0x7f18668f6bf4 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x434
#39  0x7f18666d54e8 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x68
#40  0x7f18666dc40a in SoGLRenderActionP::renderSingle(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0xba
#41  0x7f18666dca6e in SoGLRenderActionP::render(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x11e
#42  0x7f18666d61ba in SoAction::apply(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x2ea
#43  0x7f1869e9708a in Gui::SoBoxSelectionRenderAction::apply(SoNode*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x2a
#44  0x7f18669cd219 in SoRenderManager::actuallyRender(SoGLRenderAction*, int, int, int) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x69
#45  0x7f18669cd3c7 in SoRenderManager::renderSingle(SoGLRenderAction*, int, int, int) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0xc7
#46  0x7f18669cda0c in SoRenderManager::render(SoGLRenderAction*, int, int, int) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libCoin.so.80+0x9c
#47  0x7f1869f7712f in Gui::View3DInventorViewer::renderScene() from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x17f
#48  0x7f1869f3b60d in SIM::Coin3D::Quarter::QuarterWidget::paintEvent(QPaintEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x31d
#49  0x7f1869f42315 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent(QPaintEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0x45
#50  0x7f1867f93d51 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x579
#51  0x7f1867ffcf25 in QFrame::event(QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x27
#52  0x7f18673c2fc8 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5+0xe2
#53  0x7f1867f69fba in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xc8
#54  0x7f1869b69599 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0xc9
#55  0x7f18673c3158 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5+0x8e
#56  0x7f1867f8e653 in QWidgetPrivate::sendPaintEvent(QRegion const&) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x27
#57  0x7f1867f8efdd in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x967
#58  0x7f1867f8f9ab in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x2c7
#59  0x7f1867f8f45c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xde6
#60  0x7f1867f8f9ab in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x2c7
#61  0x7f1867f8f45c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xde6
#62  0x7f1867f8f9ab in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x2c7
#63  0x7f1867f8f45c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xde6
#64  0x7f1867f8f9ab in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x2c7
#65  0x7f1867f8f45c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xde6
#66  0x7f1867f8f9ab in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x2c7
#67  0x7f1867f8f45c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xde6
#68  0x7f1867f8f9ab in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x2c7
#69  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#70  0x7f1867f8f45c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xde6
#71  0x7f1867f8f9ab in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x2c7
#72  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#73  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#74  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#75  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#76  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#77  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#78  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#79  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#80  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#81  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#82  0x7f1867f8f8c3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x1df
#83  0x7f1867f8f45c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xde6
#84  /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5(+0x173def) [0x7f1867f73def]
#85  0x7f1867f940be in QWidget::event(QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0x8e6
#86  0x7f1867f69fca in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Widgets.so.5+0xd8
#87  0x7f1869b69599 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0xc9
#88  0x7f18673c3158 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5+0x8e
#89  0x7f18673c3989 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5+0x1d5
#90  /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5(+0x1f3a47) [0x7f18673f3a47]
#91  /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libglib-2.0.so.0(+0x5b1d5) [0x7f1865b101d5]
#92  /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libglib-2.0.so.0(+0x5e377) [0x7f1865b13377]
#93  /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f1865b13a8e]
#94  0x7f18673f35af in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5+0x59
#95  0x7f18673c0dda in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5+0x188
#96  0x7f18673c4ea5 in QCoreApplication::exec() from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libQt5Core.so.5+0xfb
#97  0x7f1869ac85e1 in Gui::Application::runApplication() from /tmp/.mount_FreeCAfGfMeF/usr/bin/../lib/libFreeCADGui.so+0xa41
#98  /tmp/.mount_FreeCAfGfMeF/usr/bin/freecad(+0x78b7) [0x5653e620d8b7]
#99  /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f1866e6424a]
#100  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f1866e64305]
#101  /tmp/.mount_FreeCAfGfMeF/usr/bin/freecad(+0x7c2a) [0x5653e620dc2a]
`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
This likely a packaging problem, the latest appimage is unfortunately shipping with incorrect dependencies, I'm working on fixing this

**Comment by adrianinsaval** [comment]
please test the new appimage

**Comment by MiqCG** [comment]
Well done, @adrianinsaval

**Comment by adrianinsaval** [comment]
is it working on multiple launches? at #17620 it is failing to launch after the first successful launch

**Comment by MiqCG** [comment]
It's starting and working fine, several times, on my side.

BTW, @luzpaz , in my opinion this issue is not a duplicate of #17620


OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.1.0dev.39100 (Git) AppImage
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
