### ISSUE TITLE
Assembly: Error when double-clicking joint in inactive assembly.

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#17622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Open the attached [file](https://github.com/user-attachments/files/17607486/assy.FCStd.zip) (remove the .zip extension).
2. Double-click the last joint in the Tree view.
3. Result: attribute error.
```
16:43:57  pyException: Traceback (most recent call last):
  File "D:\BKG_Tmp\FreeCAD_0.22\Mod\Assembly\JointObject.py", line 922, in doubleClicked
    self.gui_doc.setEdit(assembly)
    ^^^^^^^^^^^^
<class 'AttributeError'>: 'ViewProviderJoint' object has no attribute 'gui_doc'
```

### Full version info

```shell
OS: Windows 8 build 9600
Architecture: x86_64
Version: 1.1.0dev.39100 (Git)
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Thanks for the report
