### ISSUE TITLE
FreeCAD 1.1 General: Recent Files / FreeCAD 1.1 Allgemein: Zuletzt verwendete Dateien

### ISSUE THREAD

**Issue by HKaufmann2** [FreeCAD/FreeCAD#17635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

You have to restart FreeCAD every time so that the edited files appear in the list.
It would be better if you have saved the file that the icon immediately appears in the list.

Where should I best enter these problems? In Github or FreeCAD Forum.

Greetings Holger

Man muss jedesmal FreeCAD neu starten damit in der Liste die bearbeiteten Dateien auftauchen.
Besser wäre es wenn man die Datei abgespeichert hat das in der Liste sofort das Icon auftaucht.

Wo soll ich am besten diese Probleme eintragen? In Github oder FreeCAD Forum.

Gruß Holger

### Full version info

```shell
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.39100 (Git) AppImage
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * sheetmetal 0.5.3
  * TitleBlock 0.5.2.2
  * A2plus 0.4.68
  * WB_Organizer 2024.1.29
  * fasteners 0.5.29
  * Manipulator 1.5.7
  * woodworking 0.21.2.33771
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13846
