### ISSUE TITLE
Assembly: Flexible/rigid subassemblies: tooltip is misleading

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#17636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After merging https://github.com/FreeCAD/FreeCAD/pull/15629 subassemblies can be added as rigid or flexible. The tooltip when adding a component states:

> If checked, the inserted sub-assemblies will not be flexible.
> Rigid means that the sub-assembly will be considered as a solid.
> Flexible means that the sub-assembly joints will be taken into account in the main assembly.
> **You can change this property of sub-assemblies at any time by right clicking them.**

![image](https://github.com/user-attachments/assets/8656d563-a04c-4333-b19f-0fe9198a7d88)

Unlike stated on the tooltip, right-clicking sub-assembiles does not give the ability to change their rigidness. Or at least I've not found a way to do it.

Instead, the **Rigid** property can be changed on the Property Editor

![image](https://github.com/user-attachments/assets/6b587f32-6c9b-4158-a7db-258afca46cd7)

I believe the tooltip should read

```diff
- You can change this property of sub-assemblies at any time by right clicking them.
+ You can change this behavior at time by editing the Rigid property of a given sub-assembly in the Property Editor.
```

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39100 (Git) Snap 1179
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
  * Ondsel-Lens 2024.9.13.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Assembly

### Anything else?

> Flexible means that the sub-assembly joints will be taken into account in the main assembly.

This description of flexible sub-assemblies is in my opinion not easy to understand. What does exactly "will be taken into account" mean?

An alternative description, adapted from https://help.solidworks.com/2021/english/SolidWorks/sldworks/c_flexible_sub-assemblies.htm might be clearer:

> Flexible sub-assemblies allow movement of their individual components within the parent assembly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
![image](https://github.com/user-attachments/assets/2d8a9761-ce84-426d-a7c0-818581747506)
Right click appears to work on my side.
It is a right click on the tree view object item.

**Comment by furgo16** [comment]
It is indeed there. I do not know why I did not see it the first time, probably a user error on my part. I'll leave this issue open for now, as the related PR adds some more context to the tooltip.
