### ISSUE TITLE
Assembly: Can't delete Joints object after deleting active Assembly

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#17662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Open the attached [file](https://github.com/user-attachments/files/17619047/assy-delete-joints-object.FCStd.zip) (remove the .zip extension).
2. Activate the Assembly.
3. Delete the Assembly, press the No button in the "Delete group content" dialog.
4. The Joints object that remains cannot be deleted from the GUI. You can do it with Python code though.

### Full version info

```shell
OS: Windows 8 build 9600
Architecture: x86_64
Version: 1.1.0dev.39100 (Git)
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Interestingly this happens only if the assembly is active. Else the joints group gets deleted correctly
