### ISSUE TITLE
Pad Parameters Symmetric to plane doesn't work

### ISSUE THREAD

**Issue by 199Kay** [FreeCAD/FreeCAD#17675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have made a sketch with a square on the XZ plane and extruded it with "Symmetric to plane" in the middle of the plane. After extruding, no more functions can be used, be it to make a new sketch. The only option left for the tasks is to create a new body. 

**Without "Symmetric to plane" activated.**
![image](https://github.com/user-attachments/assets/07f863da-8c2c-4ddc-9bad-8504a1f55407)

**Activated with "Symmetric to plane".**
![image](https://github.com/user-attachments/assets/28553a07-fe32-4e3c-8e59-d0952addc208)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * A2plus 0.4.60h
  * Assembly4 0.12.5
  * Curves 0.6.5
  * lattice2 1.0.0
  * ProDarkThemePreferencePack 1.0.0
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
That is just a presentation of possible options based on selection.
