### ISSUE TITLE
TechDraw: Error when trying to create a view of a large part - "TechDraw did not retrieve any geometry for View/View"

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#17671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Create Part Cube, enter 11 m (not mm) for each dimension
2. Add TechDraw page and try inserting a view

There's an error message:

`TechDraw did not retrieve any geometry for View/View`

until the default 1:1 scale is adjusted to something more reasonable like 1:100. Of course, I'm not going to create a view in the original scale but the error message is really misleading. I thought I forgot to select the object when creating a view.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39100 (Git)
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Is it the same as in the stable version?

**Comment by FEA-eng** [comment]
> Is it the same as in the stable version?

No such error message there, the view just appears as an empty frame until rescaled.

**Comment by WandererFan** [comment]
If you set "Allow crazy edges" to true on the Advanced tab, then create a 1:1 view of the 11m cube it will work.  An 11m edge on paper is considered "crazy".

Agree that the message is not helpful in this case.  We could print a warning at the point the crazy edge is detected.  Maybe it is time to retire that crazy edge test.

**Comment by FEA-eng** [comment]
> We could print a warning at the point the crazy edge is detected.

That can be a good idea. It would be less confusing if the view was created but there was a warning that something went wrong.

**Comment by WandererFan** [comment]
This is fixed. Adding a 10m cube to a page works.

**Comment by ErtugrulEge** [comment]
I got the TechDraw did not retrieve any geometry for View/View 

![Image](https://github.com/user-attachments/assets/179ce3be-2a49-4ed6-9a3d-3698cd5c0eb4)

![Image](https://github.com/user-attachments/assets/712c8351-518f-43af-8dd0-43fef9e7c4d4)

![Image](https://github.com/user-attachments/assets/ac5dcabe-5dfb-458f-968c-e48af53700a5)


```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.40504 (Git) Conda
Build type: Release
Branch: main
Hash: 855ad6c70904f911b2ce7114dd1a5bc24da98bd1
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, IfcOpenShell 0.0.0, OCC 7.8.1
Locale: Turkish/Turkey (tr_TR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Logical/physical DPI: 96/81.5973
```


[revolve.zip](https://github.com/user-attachments/files/19416028/revolve.zip)
