### ISSUE TITLE
 Treeview - [ANY]Origin - x,y or z axis selection BUG

### ISSUE THREAD

**Issue by philjynx** [FreeCAD/FreeCAD#17697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Select any origin in the tree view and then select any of the x,y or z axis causes an "Unhandled unknown exception".

![OriginSelectionBugV1RC2](https://github.com/user-attachments/assets/c97c4952-e7b8-4286-aade-bd475c367269)

Selecting the planes does not cause a fault.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fcgear
  * FreeCAD-themes 2024.7.24
  * Help 1.0.3
  * HiResMonitor
  * kicadStepUpMod 11.3.9
  * Manipulator 1.5.7
  * sheetmetal 0.5.3
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Fixed https://github.com/FreeCAD/FreeCAD/issues/17667
