### ISSUE TITLE
Any changes causes the body's color to  change back to the default one

### ISSUE THREAD

**Issue by TheRealOne78** [FreeCAD/FreeCAD#17691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If I assign a color to a body and then change the body's shape, that color will get reverted to the default gray color.

### Full version info

```shell
OS: Gentoo Linux (Xsession)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.Unknown
Build type: Release
Python 3.12.7, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Installed mods: 
  * Help 1.0.3
  * ProDarkThemePreferencePack 1.0.0
  * Gridfinity 0.6.0
  * FreeCAD-Gridfinity-Workbench 0.6.0
```

### Subproject(s) affected?

PartDesign

### Anything else?

https://github.com/user-attachments/assets/c1cb88e9-927c-467a-9dd2-1e2be4d20264

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
already resolved in the weekly. https://github.com/FreeCAD/FreeCAD/issues/15503
