### ISSUE TITLE
Draft: AnnotationStyleEditor offers user to create a new style when last annotation style is deleted

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#17716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Draft AnnotationStyleEditor opens 'create new style' dialogue without user prompt when the last annotation style in the project is deleted. I am able to reproduce 100% times in multiple projects.

Steps to reproduce:

- open sample file 
[FC-annotation-style-delete.FCStd.zip](https://github.com/user-attachments/files/17652054/FC-annotation-style-delete.FCStd.zip)

- open Draft AnnotationSyleEditor
- select style 'test-delete'
- click the 'delete' button
- the style is deleted but dialogue, but creation of new style dialogue is automatically invoked too

https://github.com/user-attachments/assets/ef4a10be-cf62-48de-9963-b7a8be572037

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39100 (Git)
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

Draft

### Anything else?

I am able to reproduce in FC 0.21.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@Roy-043 FYI
