### ISSUE TITLE
UI: Tree view renaming field does not automatically expand and the default can be very small

### ISSUE THREAD

**Issue by BMaxV** [FreeCAD/FreeCAD#17747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello everyone,

Here is a maybe easy to fix little thing. The rename entry field object is apparently based on the length of the text, not the available size in the window. And it does not resize when entering more info.

Meaning if the old name is short, and the new name is long, it gets cut off very fast and looks a bit silly. 
 
![image](https://github.com/user-attachments/assets/32c33844-0c87-403e-8cd8-382271556ebd)
![image](https://github.com/user-attachments/assets/410b2c4f-570b-4e4b-b96c-765be06f935c)

This probably doesn't affect anything. Definitely a nice to have polish issue.

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (XFCE/xubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39104 +2 (Git)
Build type: Unknown
Branch: AboutCopyConfirm
Hash: fb16a9d376abdadbbedbdc8dc1afdf076198e443
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * lattice2 1.0.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Cannot reproduce on Windows
```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39100 (Git)
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Fusion
Installed mods: 
  * CfdOF 1.27.13
  * Curves 0.6.51
  * dodo 1.0.1
  * fasteners 0.5.29
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.25
  * Rocket 4.0.0
  * sheetmetal 0.5.3
  * Silk 0.1.5

```

**Comment by hyarion** [comment]
I can reproduce this on:
```
OS: macOS 14.5
Architecture: arm64
Version: 1.1.0dev.39099 +2 (Git)
Build type: Release
Branch: testbranch
Hash: ba08ac359a8494c1f1481e2358683a21138fec7a
Python 3.11.8, Qt 5.15.8, Coin 4.0.2, Vtk , OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * OpenTheme 2024.9.1
```

https://github.com/user-attachments/assets/2452b6aa-7bdc-4f43-94dc-7d85dbef8ee4

**Comment by maxwxyz** [comment]
Thanks for the video, it is the exact same behavior on my side. It cuts off but it is visible what you type.

**Comment by hyarion** [comment]
@BMaxV is this something you would like to look into yourself? It could be a good second issue :)

**Comment by BMaxV** [comment]
I can try.

I was looking at the tree view in general and browsing some issues and it seems like a good focal point to learn about freecad and ask certain questions, both in terms of functionality and UI.

I would like to try a few more things modeling and playing with FreeCAD before I commit to getting this solved. Especially since it's only cosmetic.
