### ISSUE TITLE
Draft: Reset All Preferences throws exception in Draft workbench

### ISSUE THREAD

**Issue by cbagwell** [FreeCAD/FreeCAD#17741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I originally saw this issue when using OpenPreferences and trying to reset back to default configuration and seeing an error message.  I narrowed down reproducing it with these steps.  Issue is not reproducible unless Draft workbench is both loaded and has values stored in user.cfg.

* Delete `user.cfg` to start from defaults.
* Start FreeCAD and switch to Draft workbench
* Go to preferences and select Auto-Load for Draft workbench.
* Close FreeCAD so that user.cfg is updated.
* Start FreeCAD so that Draft workbench is auto-loaded.
* Use Reset All in Preference to produce error.

```
19:12:52  pyException: Traceback (most recent call last):
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Draft/draftutils/params.py", line 51, in slotParamChanged
    _param_observer_callback_scalemultiplier(value)
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Draft/draftutils/params.py", line 93, in _param_observer_callback_scalemultiplier
    value = float(value)  # value is a string
            ^^^^^^^^^^^^
<class 'ValueError'>: could not convert string to float: ''
```

Line stored in user.cfg that is triggering above exception looks OK to me.

```
            <FCFloat Name="DefaultAnnoScaleMultiplier" Value="1.000000000000"/>
```

### Full version info

```shell
OS: macOS 15.1
Architecture: arm64
Version: 1.1.0dev.39127 (Git)
Build type: Release
Branch: main
Hash: 1b1e355b9b8c22ae8ca01c383f6b57cdac8a7c04
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
Installed mods: 
  * InventorLoader 1.4.0
  * OpenTheme 2024.9.1
  * sheetmetal 0.5.3
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@Roy-043 FYI
