### ISSUE TITLE
FreeCAD cannot open previous file after segfault

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#17756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Freecad suddenly segfaulted and then this:

![image](https://github.com/user-attachments/assets/257740a1-a1d4-4217-990e-4d569b698451)

Seriously, this never ever happened. This is so embarrassing. Freecad cannot even try to open the file.

Is there any way to recover a file after this message?

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg/xcb)
Architecture: x86_64
Version: 1.1.0dev.39127 (Git) AppImage
Build type: Release
Branch: main
Hash: 1b1e355b9b8c22ae8ca01c383f6b57cdac8a7c04
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.26
  * InventorLoader 1.4.0
  * diff-tools 0.1.0
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.0.24
  * lattice2 1.0.0
  * kicadStepUpMod 11.3.9
```

### Subproject(s) affected?

Core

### Anything else?

This last weekly is very unstable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaiwas** [comment]
> Is there any way to recover a file after this message?

BackUP?  .FCBak?

**Comment by pierreporte** [comment]
A specific file or every file?

**Comment by leoheck** [comment]
I am updating a single file. So, don't know if it is just file or any file. But this happened after some hours of work. The size of the file was 8.5Mb and after the crash 350Kb or something. 

There is no .FCBak, I don't use this. 

I was able to recover the file since I work on a Dropbox folder. But a crash that destroys the file is the first time in 4 or more years of work.

**Comment by pierreporte** [comment]
Please share the file and steps to reproduce the loss of data.

**Comment by maxwxyz** [comment]
@leoheck you know the deal: demo file, steps to reproduce, descriptive title...

**Comment by luzpaz** [comment]
Similar to #18044 ?

**Comment by luzpaz** [comment]
@leoheck :point_up_2:

**Comment by leoheck** [comment]
it looks like it is similar.

**Comment by maxwxyz** [comment]
I'll close it then and mark the other one as confirmed
