### ISSUE TITLE
FreeCAD 1.0.0RC2 crashes on selecting datumlines in Ondsel files

### ISSUE THREAD

**Issue by alpdigitech** [FreeCAD/FreeCAD#17781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Create a new file in Ondsel ES (2024.2.2.37240) and add an empty Body. Open the file in FreeCAD 1.0.0RC2 and select the X axis in the empty Body Origin. It crashes. Attached is the sample file.
FreeCAD will actually crash when selecting any DatumLine from a file developed in Ondsel ES.

### Full version info

```shell
OS: macOS 15.0.1
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
```

### Subproject(s) affected?

PartDesign

### Anything else?

[testdatumline.FCStd.zip](https://github.com/user-attachments/files/17693457/testdatumline.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
SHould be fixed already in the weekly https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
