### ISSUE TITLE
 Creation of two separate solid bodies failed

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#17791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

by setting allow more solids in the body in partdesign by creating two rectangles and then extruding only one appears
![1](https://github.com/user-attachments/assets/6c0926c5-8bc4-4e47-86d9-79864ae4232a)
![2](https://github.com/user-attachments/assets/2d8b051c-0eef-4bfc-b8a2-ec7260ef3e6f)
![3](https://github.com/user-attachments/assets/f926de30-9849-4b63-b486-e0a2eba9b604)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39153 (Git)
Build type: Release
Branch: main
Hash: 3a7c8ed1c595c2a97116141589ed8f3fb0fd0bb5
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * FreeCAD-themes 2024.7.24
  * Glass
  * IconThemes
  * OpenTheme 2024.9.1
  * PieMenu 1.8.1
  * Render 2024.9.25
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Please check if the "Allow Compound" property of the Body is set to true.

**Comment by Roberto8303** [comment]
was set to false
 it works thanks
