### ISSUE TITLE
C2039	"seekpos" is not a member of class "std::fpos<_Mbstatet>"  	

### ISSUE THREAD

**Issue by liquor2349** [FreeCAD/FreeCAD#17813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello, Sir @chennes 
While I compile it in the windows11 with VS 2022, it gets this error. I used the FreeCAD from the main branch, while the LibPack is LibPack-0.21-V2.10.

It seems that this error is from the library "boost" in the file "positioning.hpp" Line 96. Do I make anythin wrong? Also, this LibPack doesn't have "yaml-app". Can I get a stable version for FreeCAD, which can be compiled in windows11 and VS 2022.

### Full version info

```shell
C2039	"seekpos" is not a member of class "std::fpos<_Mbstatet>"
```

### Subproject(s) affected?

None

### Anything else?

 Looking forward to your reply! 
Best wishes!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
use libpack v3 or downgrade VS (or try updating boost in that libpack if you feel inclined to do so), I believe microsoft dropped support for the boost version that was shipped in that libpack

**Comment by luzpaz** [comment]
Closing as OP used wrong libpack.
