### ISSUE TITLE
Transparency can't have different values accross multiple links

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#17820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Working on this PR for assembly : https://github.com/FreeCAD/FreeCAD/pull/17818
Where we want to **temporarily** switch some unconcerned objects to transparent to improve visibility.

The problem is for App::Link. 2 links to the same object cannot have different transparency values. So you cannot set only one to transparent.
Doing link.Transparency = 80 changes the transparency of the linked object. And so both linked change.

I think it is currently possible of doing this with CopyOnChange but for such a temporary change of a large number of objects it is not adapted.

What we need is that App::Link have their own transparency property, the same as they currently have their own 'Visibility' property.

### Full version info

```shell
1.0
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
Link has its own material property. You just need to enable it. It's the view property OverrideMaterial. You can then set the transparency in Link's ShapeMaterial.

**Comment by PaddleStroke** [comment]
Oh great thanks. Well this is not an issue then.

**Comment by PaddleStroke** [comment]
@realthunder what about line/point colors ? When I toggle OverrideMaterial, the lines becomes gray and I cannot find a way to change them to match the original color.
So I'm doing the following : 

```
            material = vobj.ShapeAppearance[0]
            material.Transparency = 80
            vobj.ShapeMaterial = material
            vobj.OverrideMaterial = True
```
But then the lines become gray. And there is apparantly no LineColor and PointColors override properties. There is a OverrideColorList that could be it but I can't see how to use it

![image](https://github.com/user-attachments/assets/bc1def1e-749d-48d9-a676-bd689a1b193e)

**Comment by PaddleStroke** [comment]
After some more test it appears that points/lines get the color 'DiffuseColor' of the ShapeMaterial. So it seems they can't be customized so far.
