### ISSUE TITLE
Assembly: 1.0.0RC3 problem creating joints: advancedOffsetCheckbox issue.

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#17833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Creating several joints results in an advancedOffsetCheckbox error. Most joints are created anyway, but the Revolute Joint is not.

Similar to: #17823.

Error message:
```
Running the Python command 'Assembly_CreateJointRevolute' failed:
Traceback (most recent call last):
  File "D:\BKG_Tmp\FreeCAD_1.0.0RC3-conda-Windows-x86_64-py311\Mod\Assembly\CommandCreateJoint.py", line 129, in Activated
    activateJoint(1)
  File "D:\BKG_Tmp\FreeCAD_1.0.0RC3-conda-Windows-x86_64-py311\Mod\Assembly\CommandCreateJoint.py", line 61, in activateJoint
    panel = TaskAssemblyCreateJoint(index)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BKG_Tmp\FreeCAD_1.0.0RC3-conda-Windows-x86_64-py311\Mod\Assembly\JointObject.py", line 1244, in __init__
    self.adaptUi()
  File "D:\BKG_Tmp\FreeCAD_1.0.0RC3-conda-Windows-x86_64-py311\Mod\Assembly\JointObject.py", line 1487, in adaptUi
    advancedOffset = self.form.advancedOffsetCheckbox.isChecked()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

'PySide2.QtWidgets.QWidget' object has no attribute 'advancedOffsetCheckbox'
```

### Full version info

```shell
OS: Windows 8 build 9600
Architecture: x86_64
Version: 1.0.0RC3.39100 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0rc3)
Hash: 3c1047103cc8960a92a90a03869a9370b80e6776
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
There seem to be serious regressions with joints in Assembly pretty much breaking it:
https://forum.freecad.org/viewtopic.php?t=92063

Other:
https://github.com/FreeCAD/FreeCAD/issues/17694
https://github.com/FreeCAD/FreeCAD/issues/17556

**Comment by PaddleStroke** [comment]
This error here `'PySide2.QtWidgets.QWidget' object has no attribute 'advancedOffsetCheckbox'` is as Max mentioned due to .ui files changed. So this just needs a clean build to fix.
Since Roy does not build I seem to recall, it'd mean there was a build failure in some released binaries?

**Comment by Roy-043** [comment]
I am using this release binary:
https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/1.0rc3/FreeCAD_1.0.0RC3-conda-Windows-x86_64-py311.7z

That needs to updated then.

**Comment by PaddleStroke** [comment]
I can confirm there is a problem in RC3. The backport of https://github.com/FreeCAD/FreeCAD/pull/17686 has failed.

Looking at FreeCAD-1.0 branch on github, the changes to TaskAssemblyCreateJoint.ui are missing. There is only the changes to JointObject.py. And so the error you have.

So main branch is not broken. Only FreeCAD-1.0.

**Comment by maxwxyz** [comment]
@chennes FYI

**Comment by adrianinsaval** [comment]
rc4 incoming
