### ISSUE TITLE
sheet metal work bench in 0.21.2 reflect .py earror

### ISSUE THREAD

**Issue by bbdhinora66** [FreeCAD/FreeCAD#17852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

sheet metal work bench in 0.21.2 reflect .py earror

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/India (en_IN)
Installed mods: 
  * 3DfindIT 1.2.0
  * A2plus 0.4.68
  * addFC 0.7.5
  * Assembly3 0.12.2
  * Assembly4 0.50.15
  * BillOfMaterials 1.0.1
  * BIM021 2021.12.0
  * CadbaseLibrary 1.0.2
  * CADExchanger
  * Defeaturing 1.2.2
  * dodo 1.0.1
  * dxf-library
  * EM 2.1.1
  * Estimate 0.1.2
  * fasteners 0.5.29
  * frame 0.1.1
  * Freecad-Built-in-themes-beta 1.2.2
  * FreeCAD-themes 2024.7.24
  * GDML 2.0.0
  * InventorLoader 1.4.0
  * Manipulator 1.5.7
  * Nodes 0.1.36
  * Pyramids-and-Polyhedrons
  * QuickMeasure 2022.10.28
  * sheetmetal 0.5.3
  * toSketch 1.0.1
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

sheet metal work bench in 0.21.2 reflect .py earror

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please test in the RC4 or latest weekly: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
If there is still an issue you can comment below but please also open an issue in the sheet metal repository.
