### ISSUE TITLE
Part Design: Model panel Origin.  Expanding Origin and clicking on any of the sub branches crashes FreeCAD

### ISSUE THREAD

**Issue by Brad-gits** [FreeCAD/FreeCAD#17887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

select the model panel, expand the Origin tree, click on X,Y, or Z axis OR X,Y, or Z plane and the application crashes

### Full version info

```shell
OS: macOS 15.1
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

None

### Anything else?

Thunderbolt Bus: Mac mini, Apple Inc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Already fixed, please use RC4
