### ISSUE TITLE
Non-Latin file name is shown as Gibberish

### ISSUE THREAD

**Issue by vovodroid** [FreeCAD/FreeCAD#17880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Follow up to  **STEP import fails #16886** .

After fix in RC4 file is open, but it's name is not displayed correctly:

[Ножки.zip](https://github.com/user-attachments/files/17173891/default.zip)

![image](https://github.com/user-attachments/assets/b9982483-fc82-40e3-b8c3-10f1aa35fa73)

### Full version info

```shell
OS: Windows 10 build 19044
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/Israel (en_IL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Assembly4 0.50.15
  * CurvedShapes 1.0.12
  * MeshRemodel 1.10.32
  * ThreadProfile 1.92.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdieterm** [comment]
Have you tried the import setting as described in
https://forum.freecad.org/viewtopic.php?p=791115#p791115
?

**Comment by vovodroid** [comment]
Yes, setting UTF-8 helps, thanks! Should it be default choice?

**Comment by luzpaz** [comment]
@vovodroid Please open a forum.freecad.org discussion to discuss making this a default feature. Thanks
