### ISSUE TITLE
wrong display/render with default font (BatangChe).

### ISSUE THREAD

**Issue by forest416** [FreeCAD/FreeCAD#17893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Python Console, the display of character back slash '\' become W. it is dimmed as like ']' and '[', while as typing. 
The output of python, stdout/stderr doesnot dim it. 

The font family is BatangChe, Edit -> perference -> python -> Family.

When change to CourierNew. the problem is gone.

is cause by broken render or issue with the font family of BantangChe ?

### Full version info

```shell
[code]
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * A2plus 0.4.65
  * fasteners 0.5.23
  * symbols_library
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should already be fixed, please test with latest weekly https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds or the 1.0 RC4
