### ISSUE TITLE
The design disappeared from the screen and an exception was raised

### ISSUE THREAD

**Issue by mriscoc** [FreeCAD/FreeCAD#17933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

More that an issue report this is a warning to don't forget to save your work from time to time. Fortunately I was able to save the work. Maybe this screen capture can give some light about the error.
![image](https://github.com/user-attachments/assets/568a0fc0-e4f4-4b88-86bb-1188a6308bab)

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Spanish/Peru (es_PE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
Installed mods: 
  * fasteners 0.5.31
  * fasteners.backup1731875068.4162824 0.5.29 (Disabled)
  * FreeCAD-themes 2024.7.24
  * QuickMeasure 2022.10.28
  * Render 2024.9.25
  * slic3r-tools
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
This is a non actionable issue. Please check if there is a similar issue and if not, please provide a detailled description, an example file and steps how to reproduce the issue.
