### ISSUE TITLE
3MF: Support 'Maker World' XML formatting

### ISSUE THREAD

**Issue by liberodark** [FreeCAD/FreeCAD#17957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi,

I cannot open any files from : https://makerworld.com/
PS : 3mf is mostly use on Bambu Lab Printer.

Best Regards

### Full version info

```shell
1.0 RC2 and RC4
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hyarion** [comment]
Can you point to a specific file that doesn't work for you so I don't have to guess which one you mean? (I don't like guessing, it takes too much time)

**Comment by cbagwell** [comment]
@liberodark post this example link on discord:  https://makerworld.com/en/models/798080?designId=798080#profileId-737503

I quickly looked at Freecad code and contents of a few Maker World 3MF's and looks like Freecad expects:

```
 <resources>
  <object>
   <mesh>
   </mesh>
  </object>
 </resources>
```

While maker world has this which references a different file that does have above layout:

```
<resources>
  <object>
   <components>
    <component p:path="/3D/Objects/object_42.model" objectid="1" p:UUID="002a0000-b206-40ff-9872-83e8017abed1" transform="1 0 0 0 1 0 0 0 1 0 0 0" />
   </components>
  </object>
</resources>
```
