### ISSUE TITLE
TechDraw: Cannot change the circle linestyle of the detail highlight of Detail View

### ISSUE THREAD

**Issue by Braulio-B** [FreeCAD/FreeCAD#17981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi! I'm a new Freecad user. I'd like to report a bug to help the development team.

The Detail View tool is not working correctly. I cannot change the circle linestyle of the detail highlight.

Thank you for all the amazing work you are doing!

![Captura de tela 2024-11-19 140634](https://github.com/user-attachments/assets/3602530b-7a7b-4b64-a547-9c9b101ba43b)

### Full version info

```shell
```

### Subproject(s) affected?

TechDraw

### Anything else?

I tried to change it in Edit>> Preferences>> TechDraw>> Annotation>> Datail Highlight Style, and after restart Freecad it didn't work too.

I'm not a programer, I can only help reporting. I hope it help you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Thanks. Please edit the above ticket and place the full [About](https://wiki.freecad.org/About) info into the appropriate section of the template. TIA

**Comment by WandererFan** [comment]
You need to change the highlight style on the base view (ie the view on which the highlight will be drawn), not the detail view.

![DetailHighlightStyle](https://github.com/user-attachments/assets/98bc8d2b-bc64-4b87-9597-9fc4189929fc)
