### ISSUE TITLE
Placement angle doubled when exporting bodies in freecad 0.21

### ISSUE THREAD

**Issue by matc63famcoud** [FreeCAD/FreeCAD#17990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I recently migrated from Freecad 0.20 to 0.21 (debian stable to testing).
Yesterday I had to modify a file I've made on the former version, to export it as a 3mf.
The result wasn't what I expected.
I investigated using a test part (attached in the zip file) and it seems that when I set 90° rotation in the placement settings I get a 3mf or stl rotated by 180° (and to have 90 I had to set 45).
I also tried the flatpak version (0.21 too) and I have the same issue.
I tested on version 1.0 and I can export my parts without any problem so I think I will use the 1.0 appimage as a workaround, but I wanted to report this issue yesterday and I didn't know a new version was released today.
[test rotation.zip](https://github.com/user-attachments/files/17821624/test.rotation.zip)
Thank you for this great piece of work.

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should already be fixed in 1.0
