### ISSUE TITLE
Edges are carried through existing geometry

### ISSUE THREAD

**Issue by kilrah** [FreeCAD/FreeCAD#18005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Selecting an edge when geometry was added does not cause the edge to be broken up.

E.g. on the attached image selecting the edge above / below the extrusion should stop at the extrusion, but instead goes through. That causes fillets/chamfers to fail since they'd be going through existing geometry.

![image](https://github.com/user-attachments/assets/ff57c6fe-53c6-4e24-8e74-d2ab8ed4dde2)

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: French/Switzerland (fr_CH)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

PartDesign

### Anything else?

[testpart.zip](https://github.com/user-attachments/files/17832320/testpart.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Zoom in the corner and you will find your mistake )
![Screenshot_20241120_165447](https://github.com/user-attachments/assets/3af34829-cd69-4bcf-97d6-a207fa5f79e4)
