### ISSUE TITLE
Spreadsheet: Inconsistent tooltip information

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#18013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The tooltip of the cell text color is ''Set cell(s) text color''
![tooltip](https://github.com/user-attachments/assets/2af8fa3f-0664-4f14-8dea-c8ee06a64bc5)

Which is inconsistent with the naming in the properties of the cell:
![properties-spreadsheet](https://github.com/user-attachments/assets/b5371d2b-705e-4d78-9412-f80e6717e78a)

**Proposed solution:**
Change the tooltip of the button to 'Set cell(s) text color'

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

Spreadsheet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
Perhaps, I'll leave these links to support the discussion.

https://github.com/FreeCAD/FreeCAD/blob/2819ca438e3776fdb675fbe061b95019b70940d4/src/Mod/Spreadsheet/App/Cell.h#L75-L79

https://github.com/FreeCAD/FreeCAD/blob/2819ca438e3776fdb675fbe061b95019b70940d4/src/Mod/Spreadsheet/App/Cell.h#L184-L185

https://github.com/FreeCAD/FreeCAD/blob/2819ca438e3776fdb675fbe061b95019b70940d4/src/Mod/Spreadsheet/App/Cell.h#L202-L203
