### ISSUE TITLE
Draft Scale and Snap widgets are not named in toolbar lists

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#18046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

- open new file with Draft WB selected
- right click on one of the toolbars
- Scale Widget and Snap Widget are possible to turn off, but have no names. See screenshot:

![empty-toolbars](https://github.com/user-attachments/assets/10409f1e-e50e-45f0-bb48-bb8237361edd)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
Related/duplicate: #16832.

**Comment by semhustej** [comment]
Closing this issue as a duplicate.
