### ISSUE TITLE
TechDraw: Hidden line colour is always black even when changed in preferences

### ISSUE THREAD

**Issue by Suthy1** [FreeCAD/FreeCAD#18050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The hidden line colour option in techdraw does not work on hidden lines in techdraw drawings in FC 1.0. This previously worked fine in FC 0.21.2.

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/New Zealand (en_NZ)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * ArchTextures
  * BillOfMaterials 0.1.4.2
  * CADExchanger
  * CurvedShapes 1.0.9
  * Curves 0.6.46
  * dxf-library
  * fasteners 0.5.28
  * parts_library
  * QuickMeasure 2022.10.28
  * sheetmetal 0.4.24
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Can you [restart in Safe Mode](https://wiki.freecad.org/Std_RestartInSafeMode) and see if you can reproduce ?

**Comment by Suthy1** [comment]
Yes, the issue is still present.
![Hidden Line Settings](https://github.com/user-attachments/assets/f5686c24-bc20-4677-b522-e07fb38ef1f1)
![Hidden Line Snip](https://github.com/user-attachments/assets/c4a6a5f0-e4d2-451e-ba94-e9ba74080046)

**Comment by Suthy1** [comment]
Looking into this further, the hidden line colour seems to be linked with the "Normal" line colour.
![Base Colour Blue](https://github.com/user-attachments/assets/892eeba5-e862-4ab8-976a-21abdf847a4f)
![Blue Hidden Lines](https://github.com/user-attachments/assets/25d7e0e8-0692-48ea-b898-bd2c3d976900)
