### ISSUE TITLE
PartDesign: New sketch: can't do "tool -> select face -> ok"

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#18062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

You can : 
- Select a planar face
- Trigger the new sketch
-> works OK

But you can't do : 
- Trigger the new sketch
- Select a planar face
- Press OK
- > task does not accept.

No reason this should not work.

I first seen this behavior in a video from a frustrated user trying freecad for the first time.

### Full version info

```shell
1.0
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Known issue, should be solved with https://github.com/FreeCAD/FreeCAD/issues/11133
Closing this in favor of the better attachment
