### ISSUE TITLE
Wrong CMYK color code in documentation

### ISSUE THREAD

**Issue by porgand** [FreeCAD/FreeCAD#18080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

On logo guidelines: https://fpa.freecad.org/handbook/process/logo.html
it says about black: CMYK(0,0,16,1)
CMYK 0,0,16,1 is not black, should be CMYK(0,0,16,82)

### Full version info

```shell
On logo guidelines: https://fpa.freecad.org/handbook/process/logo.html
it says about black: Off Black, #212529, RGBA(33,37,41,1), CMYK(0,0,16,1), PMS BLACK C

CMYK 0,0,16,1 is not black (it is pale yellow)
consulting with guidelines PDF
https://fpa.freecad.org/images/logos/guidelines/guidelines.pdf
it should be CMYK(0,0,16,82)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
cc @obelisk79 @yorikvanhavre

**Comment by yorikvanhavre** [comment]
> cc @obelisk79 @yorikvanhavre

Looks valid to me! Indeed most off-black colors I could find on the net have a K values around 70-80. Probably a typo...

**Comment by obelisk79** [comment]
according to conversion @ https://colocode.io

it looks like it should be CMYK(3,2,0,84)
![image](https://github.com/user-attachments/assets/8bf623c3-8e5e-4cb0-914a-a7d3455ee928)
