### ISSUE TITLE
Draft Workbench widget issue

### ISSUE THREAD

**Issue by Danial1985** [FreeCAD/FreeCAD#18084]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Annotation scale widget and Snap widget doubled on status bar in Draft Workbench. Second copy not fully functional and could not turned off, it appears again after reboot.
![Безымянный](https://github.com/user-attachments/assets/7d019f0b-1c62-4282-8382-43f929a138b7)

### Full version info

```shell
OS: Windows 10 build 14393
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Ukrainian/Ukraine (uk_UA)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Reinforcement
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@Roy-043 FYI. maybe related to https://github.com/FreeCAD/FreeCAD/issues/16832 ?

**Comment by Danial1985** [comment]
Yes. Looks like you are right. I also have empty lines in View->Toolbars. Its do could be  related to #16832
![Безымянный2](https://github.com/user-attachments/assets/e0e60a7c-18d7-44ac-b62d-1ad21893f286)

**Comment by Roy-043** [comment]
Closing this as completed with #18064.
