### ISSUE TITLE
FEMMeshNetgen: The FEM module is built without NETGEN support. Meshing will not work!!!

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD#18145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Tested on conda-version (osx-arm). Something must have changed so that the netgen-mesher is not enabled anymore in version 1.0.0. I get this error message when trying to run netgen:
`FEMMeshNetgen: The FEM module is built without NETGEN support. Meshing will not work!!!`

The conda-packaging didn't change, so normally netgen should work.

### Full version info

```shell
OS: macOS Sequoia (15.1)
Architecture: arm64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.12.7, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: German/Austria (de_AT)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/
Installed mods: 
  * DynamicData 2.62.0
  * Plot 2022.4.17
  * OpenTheme 2024.9.1
  * AirPlaneDesign 0.4.1
  * CurvedShapes 1.0.9
  * Curves 0.6.42
  * Assembly4 0.50.15
  * Assembly3 0.12.2
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@marioalexis84 @oursland FYI

**Comment by marioalexis84** [comment]
Could you check if the cmake entry `BUILD_FEM_NETGEN=ON` is defined?

**Comment by looooo** [comment]
it is but the build logs show: -- NETGEN:                      not enabled

**Comment by marioalexis84** [comment]
There were no recent changes to FindNETGEN.cmake.
Do you have any reference commit for which Netgen is found on your current system?

**Comment by looooo** [comment]
I tested now on different platforms. Netgen works for all the qt5 builds. For the qt6-builds it's not working. One difference I see in the build logs is the following:

qt5 reports this:
```
2024-11-29T18:52:00.0816829Z -- Could NOT find Netgen (missing: Netgen_DIR)
2024-11-29T18:52:00.0817507Z -- Cannot find NETGEN header files.
2024-11-29T18:52:00.0818034Z -- Cannot find NETGEN library.
```
qt6 reports only:
```
-- NETGEN: not enabled
```

**Comment by looooo** [comment]
Sorry for the rumours, somewhere in the commit history during updating to qt6 I had disabled BUILD_FEM_NETGEN. So this should be fixed. Thanks for the help.

**Comment by dyfrgi** [comment]
Does this also cause Netgen to not be selectable in the Mesh Workbench, or is that a separate issue?
