### ISSUE TITLE
Inexplicable distortion appears during Fillet

### ISSUE THREAD

**Issue by jordancrubin** [FreeCAD/FreeCAD#18179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Ive included a file to a simple design.  Three fillets of the outer ring work fine.  When adding the 4th fillet, it takes several minutes before it appears with a distortion imposed over the model.

### Full version info

```shell
OS: macOS 14.5
Architecture: arm64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.25
  * Curves 0.6.42
```

### Subproject(s) affected?

PartDesign

### Anything else?

[flowerpot.FCStd.zip](https://github.com/user-attachments/files/17954192/flowerpot.FCStd.zip)
<img width="1539" alt="Screenshot 2024-11-28 at 11 02 24 PM" src="https://github.com/user-attachments/assets/96e677cd-e706-49e7-83e5-4c93ddfe2491">
<img width="1502" alt="Screenshot 2024-11-28 at 11 06 26 PM" src="https://github.com/user-attachments/assets/4bfc4bda-ca96-4275-a3cf-20335fb012e6">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Files contain 4 fillets, but I do not see issue like you show.
Please write step to reproduce.

**Comment by tarman3** [comment]
Confirmed

![Screenshot_20241129_070645_hor](https://github.com/user-attachments/assets/8871a1c2-bcf7-4659-8bb3-68a06cbc8921)

<details>
  <summary>FreeCAD 1.0.0.39109 (Git), Arch Linux (KDE/plasma/wayland)</summary>

```
OS: Arch Linux (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.0.0.39109 (Git)
Build type: Release
Branch: makepkg
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.12.7, Qt 6.8.0, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Installed mods: lattice2 1.0.0; CurvedShapes 1.0.13; MeshRemodel 1.10.34; freecad.gears 1.3.0; fasteners 0.5.31; sheetmetal 0.5.7; Silk 0.1.5; Curves 0.6.51
```
</details>

<details>
  <summary>FreeCAD 1.1.0dev.39315 (Git) Conda AppImage, Arch Linux (KDE/plasma/xcb)</summary>

```
OS: Arch Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: lattice2 1.0.0; CurvedShapes 1.0.13; MeshRemodel 1.10.34; freecad.gears 1.3.0; fasteners 0.5.32; sheetmetal 0.5.10; Silk 0.1.5; Curves 0.6.51

```
</details>

**Comment by maxwxyz** [comment]
Known issue, similar to https://github.com/FreeCAD/FreeCAD/issues/11082

**Comment by maczargit** [comment]
Workaround for this, is to split the last fillet into two parts.

First fillet bottom and left edge. 
Next fillet right and top.

![obraz](https://github.com/user-attachments/assets/a4285896-67e5-4ed6-a9fa-9ebaee342abf)

**Comment by tarman3** [comment]
I was also work around issue by split fillet feature for long and short curves.

![Screenshot_20241129_155928_hor](https://github.com/user-attachments/assets/bf1c922d-8948-4d8d-800a-8d0d6c64ba3f)

**Comment by jordancrubin** [comment]
> I was also work around issue by split fillet feature for long and short curves.
> 
> ![Screenshot_20241129_155928_hor](https://private-user-images.githubusercontent.com/188672424/391107848-bf1c922d-8948-4d8d-800a-8d0d6c64ba3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MjY1NjYsIm5iZiI6MTczMjkyNjI2NiwicGF0aCI6Ii8xODg2NzI0MjQvMzkxMTA3ODQ4LWJmMWM5MjJkLTg5NDgtNGQ4ZC04MDBhLThkMGQ2YzY0YmEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQwMDI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDM4YzMxZWI0OTU1YmExNmUxYWU0ZDE0MmMxOGY3ZTNmNWE1OTMxODk4YzFjNGEyMTVlZDQ4MDJkNjVmYWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wzef1UCKGsjBIB3nsitrUyzuNXBbp0PmHl2owCNz4Z8)

Ive tried this but as you see the fillet shape is not the same as the others

<img width="1044" alt="Screenshot 2024-11-29 at 7 23 48 PM" src="https://github.com/user-attachments/assets/6aa7ad21-5118-4d53-9a60-e34b846f955f">

**Comment by tarman3** [comment]
What is the difference?

**Comment by jordancrubin** [comment]
> What is the difference?

If you look closely. The fillet done all in one has a boxier appearance where the 2step method has a rounded end.

**Comment by jordancrubin** [comment]
![IMG_9949](https://github.com/user-attachments/assets/10d03f95-3dd2-4800-9a12-24f53b662b69)
Difference close up…

**Comment by FlachyJoe** [comment]
A polar pattern works well
![image](https://github.com/user-attachments/assets/2a858f22-68ff-4c89-8f64-e13fccd0d9d8)

**Comment by jordancrubin** [comment]
> A polar pattern works well ![image](https://private-user-images.githubusercontent.com/10371513/391731129-2a858f22-68ff-4c89-8f64-e13fccd0d9d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODYzNTcsIm5iZiI6MTczMzE4NjA1NywicGF0aCI6Ii8xMDM3MTUxMy8zOTE3MzExMjktMmE4NThmMjItNjhmZi00Yzg5LThmNjQtZTEzZmNjZDBkOWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDAwMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NzIxMjdkMWVhNTM0YTgxNGQ4OTRmNzgwNjRjYmZlMzg0NTllNmMwNTU2ZjJjMzM1YTIyNzQwOGNhOWJlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PmtBv2kR3wJ0gWLDKUXZXkyl3o3cr8dDPMlaFG1qpVs)

I see what you did there, but I feel like were getting into the weeds with these workarounds again.  Consider of course that this is symmetrical and you can get away with that.  More complex shapes would be trouble.

**Comment by jordancrubin** [comment]
> Workaround for this, is to split the last fillet into two parts.
> 
> First fillet bottom and left edge. ![obraz](https://private-user-images.githubusercontent.com/3754746/391050637-e6801e9d-c8d8-4aea-a0b8-5dc215fde380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzk5MjQsIm5iZiI6MTczMzI3OTYyNCwicGF0aCI6Ii8zNzU0NzQ2LzM5MTA1MDYzNy1lNjgwMWU5ZC1jOGQ4LTRhZWEtYTBiOC01ZGMyMTVmZGUzODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDIzMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE3N2M4YmIwYzRjZWMxMzkwNjk2ZDkzODZhZjgwZjFiNWVlY2Q1YjA4ZmM4ZWFmZDljNWVmZjRkMzVmMzMyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.G7RQxy7RdKLWUwopN0rOxsk36EJhNgJvyIPriPyMNdM)
> 
> Next fillet right and top. ![obraz](https://private-user-images.githubusercontent.com/3754746/391050718-2cd25a0d-b2ab-46e7-acc2-1126a45a4d72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzk5MjQsIm5iZiI6MTczMzI3OTYyNCwicGF0aCI6Ii8zNzU0NzQ2LzM5MTA1MDcxOC0yY2QyNWEwZC1iMmFiLTQ2ZTctYWNjMi0xMTI2YTQ1YTRkNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDIzMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRhZTQ5OWYwNGUxNGFmMTMzYjM2OTk1NjBhOGQzNGRlN2NkYzQ2NDJhODRmODE3ZTNlZDYwMGU5NjEyYWIxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hUJitlYWVEL0VfPI2O9-uEuluc1W-BbmKUXqO88y0Do)
> 
> ![obraz](https://private-user-images.githubusercontent.com/3754746/391050375-a4285896-67e5-4ed6-a9fa-9ebaee342abf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzk5MjQsIm5iZiI6MTczMzI3OTYyNCwicGF0aCI6Ii8zNzU0NzQ2LzM5MTA1MDM3NS1hNDI4NTg5Ni02N2U1LTRlZDYtYTlmYS05ZWJhZWUzNDJhYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDIzMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODc0ZWU5ZTNmNjE0YzFhNmE5MjVhMWE5NmJlMzZkMjM1OGQyMmE5ODNkMzQwMjcwZDIzMDQwYTc5YTg3MWRmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yQBWAK80AJ3LcW3xzMJRJUEeEt1lyBgeSYgvLqlCDNA)

You have labeled this as a workaround possible where i've not yet seen an effective workaround demonstrated.
