### ISSUE TITLE
Draft: Default hatch file `Mod/TechDraw/PAT/FCPAT.pat` not shown in Draft Hatch task panel

### ISSUE THREAD

**Issue by tritao** [FreeCAD/FreeCAD#18197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

As the title says, I would expect FreeCAD to show the default hatch file `Mod/TechDraw/PAT/FCPAT.pat` when selecting the Hatch tool. But by default this does not happen and as the screenshot shows its value is empty, which is not very user friendly.

If I extract the app image I can see the file exists in `usr/share/Mod/TechDraw/PAT/FCPAT.pat`.

The code in `gui_hatch.py` is doing:

```python
       self.form.File.setFileName(params.get_param("FilePattern", path="Mod/TechDraw/PAT"))
        pat = params.get_param("NamePattern", path="Mod/TechDraw/PAT")
```

So there seems to be some kind of default to this path but it does not seem to work.

### Full version info

```shell
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * cadquery-freecad-module
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Draft

### Anything else?

![image](https://github.com/user-attachments/assets/47763238-6c5e-4d1c-a317-8acf3c4f7d48)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
The same situation with <ins>Shape from text tool</ins>.

It would be nice to have some default values ​​so that you don’t have to climb through directories looking for a file to create a simple example.

**Comment by semhustej** [comment]
I can confirm OP on Windows:

![windows](https://github.com/user-attachments/assets/7ff8ff3b-7a8f-437b-bf8b-55df64cb127e)


```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion

```

**Comment by maxwxyz** [comment]
@WandererFan FYI

**Comment by Roy-043** [comment]
Seems more of a Draft issue.

**Comment by Roy-043** [comment]
> The same situation with font in Shape from text tool.

Some work has already been prepared to make font selection easier:
https://github.com/FreeCAD/FreeCAD/issues/9458#issuecomment-2296192549
