### ISSUE TITLE
Sketcher: constraints have black box backgrounds

### ISSUE THREAD

**Issue by depthoffocus** [FreeCAD/FreeCAD#18213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Black background blocks have appeared behind sketcher constraints which can make some of the small icons quite difficult/jarring to work with. Apparently regardless of theme choice, and insensitive to the 3D view background colour.

Not sure if a bug or part of an intentional choice. Wasn't in the previous 39315 build. 

These backgrounds could be a really good idea if their colour and padding was configurable and the spacing was right (symbols and text not running up to the edge of the box), if they were rounded slightly, and were not just large blocks when they split over lines etc., but this appears not to be a configurable colour or feature.

Some sort of transparency issue with an overlay?

<img width="315" alt="Screenshot 2024-11-30 at 12 23 50" src="https://github.com/user-attachments/assets/126586c7-eda9-43d2-84c5-57794a6b456d">
<img width="737" alt="Screenshot 2024-11-30 at 12 24 52" src="https://github.com/user-attachments/assets/620cd99f-d297-4a15-b757-61c77b2d7c01">

### Full version info

```shell
OS: macOS 14.7.1
Architecture: x86_64
Version: 1.1.0dev.39380 (Git) Conda
Build type: Release
Branch: main
Hash: 797c1180b012a8aee1d67de62880df0f835a731e
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * ThreadProfile 1.92.0
  * freecad.gears 1.3.0
  * OpenTheme 2024.9.1
  * Manipulator 1.5.7
  * fasteners 0.5.33
  * lattice2 1.0.0
  * CurvedShapes 1.0.13
  * Curves 0.6.51
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
@wwmayer looks like an unintended consequence of https://github.com/FreeCAD/FreeCAD/commit/a372678e987a6522e3de4afc7e981ee67cc5cd34 even with _Anti-Aliasing_ set to _None_ the black background squares/rectangles occur which didn't occur normally.

**Comment by wwmayer** [comment]
For two and four color components the alpha value isn't considered. That's why it's black when it should be transparent.

**Comment by DangerToMe** [comment]
Having same issue with flatpak version 1.0.1 on Linux Mint. It was working fine for days. Then today, this....
<img width="523" height="530" alt="Image" src="https://github.com/user-attachments/assets/97f8dc63-7e1f-44d4-bdb2-df3bd1a3e74e" />
<img width="1042" height="822" alt="Image" src="https://github.com/user-attachments/assets/a7517b97-c447-46a2-a34e-a146f84a1298" />
