### ISSUE TITLE
Forum - Can not see forum topics

### ISSUE THREAD

**Issue by tarman3** [FreeCAD/FreeCAD#18239]
Login the same like in github
After login looks like forum is empty

![image](https://github.com/user-attachments/assets/5b89d634-a0e8-4d11-a4c9-b3c1f2121399)

Tried send message by **contact_us**, but get message
> Your message looks like a spam. Please, adjust your message.

It’s as if the rights to all sections of the forum are limited or I’m blacklisted.

**Comment by maxwxyz** [comment]
@Roy-043

**Comment by tarman3** [comment]
Solved
Thank you

**Comment by Hamsterberg** [comment]
Guten Tag, ich habe genau die selbe Fehlermeldung.

Besteht die Möglichkeit mir weiterzuhelfen.

Good afternoon, I am receiving the exact same error message.

Is there any way you can assist me?

**Comment by Roy-043** [comment]
@Hamsterberg : you should have access now.

**Comment by rmarkus** [comment]
Dear admins, I have the same issue. After login, all topics invisible and I cannot write a help request within the forum due to "Your message looks like spam....". Can you please review my account? Thanks a lot! (account = applepi).

**Comment by Roy-043** [comment]
@rmarkus : you should have access now.
