### ISSUE TITLE
[Regression]Sketcher external geo treated as actual geometry

### ISSUE THREAD

**Issue by Person1873** [FreeCAD/FreeCAD#18237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When selecting external geometry in the sketcher, the newly created geometry in the sketch is considered to be part of the wire.
This differs from previous behavior where it would be ignored for purposes of checking if the wire was closed.

Further details can be found here: https://www.reddit.com/r/FreeCAD/comments/1h42f4s/wire_not_closed_bug_v1/

### Full version info

```shell
OS: NixOS 25.05 (Warbler) (dwl/xcb)
Architecture: x86_64
Version: 1.1.0dev.39380 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 797c1180b012a8aee1d67de62880df0f835a731e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
This is intended behavior. You can toggle it to construction geometry as any other geometry.
