### ISSUE TITLE
Discord verification is not working

### ISSUE THREAD

**Issue by dvdvideo1234** [FreeCAD/FreeCAD#18249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hello,

Probably this thread is not for here, but I do not know where else to put it, because it does not fit any of the other sections... So...

I am trying to log in to the `FreeCAD` `Discord server`, but cannot write and it is only giving me this `Wick app` nonsense. I click verify and it generates an output similar like this one:

![image](https://i.ibb.co/FwqMNtC/image.png)

How should I use these hashes:
https://docs.wickbot.com/commands/moderation/verify/

Second I tried this [dedicated website](https://verify.wick.bot/), which ended in disaster:
![image](https://i.ibb.co/d05b52J/image.png)

Third thing I've tried:

[![](https://img.youtube.com/vi/LgNTbh4DKpo/3.jpg)](http://www.youtube.com/watch?v=LgNTbh4DKpo"")

Does anyone know how can I verify that ?

I am unable to use the Discord server and the forum does not post my message, so I am writing here with hope that anyone sees that..

### Full version info

```shell
N/A
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@obelisk79

**Comment by obelisk79** [comment]
I don't know why there is an issue with the verification bot. Several users joined and verified without problem after this individual. I've manually verified the user in discord. I would close this as a non issue and suspect this is a one-off problem.

**Comment by dvdvideo1234** [comment]
Thank you for the verify. Closing now ;)
