### ISSUE TITLE
Sketcher: Rectangle contained in circle

### ISSUE THREAD

**Issue by langrock** [FreeCAD/FreeCAD#18257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am running into the following two, likely related, problems when placing a rectangle inside a circle within the Sketcher. First, when creating a sketch that contains a large circle and a smaller one fully contained within that outer circle at any position

![image](https://github.com/user-attachments/assets/3efdc60e-da1c-4b8d-ae88-01f3e14df5b8)

and then add a rectangle contained within the smaller circle with their centers coincident and the rectangle's corners on the circle perimeter (another coincidence constraint), padding this sketch results in an incorrect object as shown below.

![image](https://github.com/user-attachments/assets/4d9868bd-3175-4738-80c3-997a6b0e3426)

Second, extruding the nested circles only and then creating a sketch on top of this object, again placing a rectangle on top of the smaller circle in the same location as before, causes this rectangle to disappear when executing the pad operation. 

I have the suspicion that first problem is due to a zero-width overlap between the circle and rectangle. I tried recreating this in a number of other CAD programs, though, and none of them had problems with this sketch ... One problem with my theory, though, is that even when I make the rectangle large enough to have its corners overlap with the perimeter of the circle, the extruded body is still not correct.

![image](https://github.com/user-attachments/assets/8aa52158-5ed4-4127-81fb-d9449a5d276e)

Any suggestion on what may be going on and how these problems can be avoided would be greatly appreciated.

Thanks,
Carsten

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
All these sketches are not logical for constructing a solid body.

![Screenshot_20241203_064501_hor](https://github.com/user-attachments/assets/f1d6f6da-21ef-4766-9224-718eca905932)

**Comment by tarman3** [comment]
Please, attach screenshot from another CAD.

**Comment by maxwxyz** [comment]
Closing this. If there is a bug, please comment and reopen.

**Comment by langrock** [comment]
Thanks for the speedy response and clarifications. I agree that this is a corner case, but I was surprised to see the program neither throw errors nor behave as I had expected based on the results seen in other CAD software or even Freecad in slightly simplified scenarios as follows.

I would not have called the initial sketch 'illogical', though, since it is akin to having two rectangles touch each other at the corners, which should form a perfectly acceptable body. And indeed, this is also not a problem in Freecad. Taking this one step further, placing a rectangle inside a circle and extruding it also works.

![image](https://github.com/user-attachments/assets/825394a3-15e3-4db6-8031-b60ab3a2621f)

The problem only occurs when enclosing this by anther geometry, such as a circle. Enclosing the touching rectangles by a circle results in the expected structure.

![image](https://github.com/user-attachments/assets/396035d7-3c4d-44cc-a7d6-164380403224)
