### ISSUE TITLE
[Compile in windows]Build_Mesh_Part is always in OFF, whether I open the option BUILD_MESH_PAET

### ISSUE THREAD

**Issue by liquor2349** [FreeCAD/FreeCAD#18287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Because of that, when I used the FreeCAD to mesh a part, it will error No module named MeshPartGui.
The cmake-gui is as follows:
![4320c77a41c4b6cb2f56afd4e2c1a66](https://github.com/user-attachments/assets/feb6dc29-9803-4fc2-885c-9e05507d41e5)

### Full version info

```shell
My environment is Windows11, cmake 3.24.2 and visual studio 2022.
I use the the FreeCAD-releases-FreeCAD-1-0 and the libpack is LibPack-1.0.0-v3.0.0RC4-Release
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liquor2349** [comment]
I got a solution that check BUILD_FEM, then the mesh part can be changed to ON.
But is it possible to build Mesh Part without FEM workbench? I just want to get the mesh from parts and make the software as lightweight as possible.
Looking forward to your reply. 
Best wishes!

**Comment by maxwxyz** [comment]
@marioalexis84 @FEA-eng maybe?

**Comment by marioalexis84** [comment]
Can you check if setting `BUILD_FEM_NETGEN=ON` and `BUILD_FEM=OFF` fixes your problem?
MeshPart and Fem are independent modules. You should be able to build MeshPart without Fem.

**Comment by liquor2349** [comment]
> Can you check if setting `BUILD_FEM_NETGEN=ON` and `BUILD_FEM=OFF` fixes your problem? MeshPart and Fem are independent modules. You should be able to build MeshPart without Fem.

Thank you for your reply, here is the screenshot of my CMake. I just checked the Build_FEM, without any other change. I also think that MeshPart and Fem are independent modules, but the fact seems to be confusing.

![4020f50159986c829f6b29b30fc5bf8](https://github.com/user-attachments/assets/079b7d06-9a73-496b-a701-b4b9bdc919e1)
![c3826bd802691f0de0681c16848a5ee](https://github.com/user-attachments/assets/74ffe3d0-df3a-4fbb-9633-be9e3b980ef3)
