### ISSUE TITLE
I would also like it to work with the iPad.

### ISSUE THREAD

**Issue by Metintoshhh** [FreeCAD/FreeCAD#18310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I would also like it to work with the iPad.

### Full version info

```shell
I would also like it to work with the iPad.
```

### Subproject(s) affected?

CAM

### Anything else?

I would also like it to work with the iPad.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Hi, this is an enormous feature request. It would mean building a whole application in iOS and getting it approved on the Apple Store etc..etc.. This feature request deserves more than 1 line repeating 'I would also like it to work with the iPad'. Search the forum.freecad.org for discussions on this topic.
