### ISSUE TITLE
PartDesign: Toggle freeze not available in the Part Design context menu

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#18345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The [Toggle freeze](https://wiki.freecad.org/Std_ToggleFreeze) command is still not available in the Part Design context menu even though it can work on PD objects (it has to be done from other workbenches which is confusing).

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39503 (Git) Conda
Build type: Release
Branch: main
Hash: da45328f6f9b35cbbdc7167d7faadb6a07634bdb
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I think it only makes sense for bodies, not individual features. So not sure if it has to be displayed on the context menu which is not dynamic based on selection. @FlachyJoe ?
