### ISSUE TITLE
Change the model appearance color

### ISSUE THREAD

**Issue by ApprenticeLi12138** [FreeCAD/FreeCAD#18352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After building a model, when setting the appearance color, you can only choose the material and its default color. The model color cannot be changed freely.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Chinese/China (zh_CN)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
It can be: Right click > Appearance.. then custom...
