### ISSUE TITLE
Part: Not enough decimal places for Part Scale

### ISSUE THREAD

**Issue by floppyhammer** [FreeCAD/FreeCAD#18384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

`Part Scale` only supports two decimal places.

<img width="351" alt="image" src="https://github.com/user-attachments/assets/e7d00093-08a2-44b1-8b57-8a6b8f0f8e53">

### Full version info

```shell
OS: Windows 11 build 27758
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
#16971
