### ISSUE TITLE
Fillet/Chamfer either gives Command Not Done or creates spurious planes

### ISSUE THREAD

**Issue by drake7707** [FreeCAD/FreeCAD#18387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Created a simple cable clip from scratch in FreeCAD 1.0. Pad works well, but attempting to chamfer or fillet does not

![image](https://github.com/user-attachments/assets/3a0cb5db-311f-4284-b00d-9d6252eb047c)

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Dutch/Belgium (nl_BE)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
Installed mods: 
  * InventorLoader 1.4.0
  * Manipulator 1.5.7
  * sheetmetal 0.5.10
```

### Subproject(s) affected?

None

### Anything else?

[CableClip.zip](https://github.com/user-attachments/files/18062535/CableClip.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by drake7707** [comment]
The default 1mm is too much for my small part, reducing to 0.2 or 0.3 removes the artifact and makes it work correctly

**Comment by tarman3** [comment]
Max fillet radius 0.99

**Comment by tarman3** [comment]
Setting radius 1 will result in null-area. So it is not correct.

By default in preferences Number decimals is 2.
If you set 0.99, it will not replace by 1.
In addition, in my example I set the radius through the expression
`Sketch.Constraints.width / 2 - 0.01 mm`

**Comment by dragazo** [comment]
Well no, fillet radius 1 is completely well-defined and would form a valid 3D shape. The only reason 1 doesn't work here is because freecad isn't smart enough to understand that the null area should be removed by fusing the overlapping edges. That's just a bug, really. Under-chamfer/fillet works, but freecad doesn't yet support over-chamfer/fillet, nor does it support the critical point (which is the issue here).

Your workaround is fine, I was just adding that finer prevision like `0.9999` would be rounded and cause issues when re-opening the fillet/chamfer. It basically works once, but then the editor (as opposed to the underlying geometry runtime) will round it back to the critical point, which causes an issue only in the editor when the feature is re-opened.

**Comment by drake7707** [comment]
I wouldn't mind as much as it could give an error back saying the chamfer/fillet overlaps with another face and can't be done with that size. 

But it didn't and just created a spurious face. In this case it's pretty obvious but i've had this happen in more complex geometry where it was hidden and only saw it in the slicer that something was amiss. It really shouldn't result in valid faces in mid air and holes in the model.

This is not easy to spot when things are parameterized and I change values in a Spreadsheet. With Pad and Pocket at least it gives a warning that it can't be executed, but it doesn't for Chamfer and Fillet and creates garbage with invalid values.

**Comment by drake7707** [comment]
Is there a reason why the GUI doesn't guard against OCC limitations in this case?

**Comment by dragazo** [comment]
I don't know if this would help in the implementation, but I believe the behavior used by commercial CAD software is equivalent to performing the fillet on each edge loop separately and then taking the intersection. So in this example we would duplicate the part, perform the top fillet on one copy, perform the bottom fillet on the other copy, and then do a boolean intersection to get the final result. As long as boolean intersections don't have some other issue, this should work for both over-fillet and critical-fillet (as is used in this issue), so two birds with one stone.
