### ISSUE TITLE
Issues with Theme Handling, Spreadsheet Color Display, and Git Dependency in FreeCAD 1.0

### ISSUE THREAD

**Issue by kwoqifeli22** [FreeCAD/FreeCAD#18396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Description:
As a long-time FreeCAD user, I have encountered significant issues after upgrading to FreeCAD 1.0, particularly with the following changes:
1.	Spreadsheet Color Issues:
o	When using the "FreeCAD Classic" theme, the Spreadsheet module behaves inconsistently with color display. Despite setting text color to black (RGB: 0, 0, 0) and background color to white (RGB: 255, 255, 255), the text disappears when a cell is not selected. Adjusting the color slightly (e.g., setting text to RGB: 1, 0, 0) makes the text visible again. This indicates a rendering or configuration bug in the theme or Spreadsheet module.
2.	Excessive Focus on Themes:
o	The introduction of numerous new themes feels unnecessary and detracts from FreeCAD's primary purpose: robust and user-friendly 3D modeling. Users often prefer to focus on modeling features rather than appearance. In my case, the addition of "FreeCAD Classic" caused unexpected bugs and confusion.
3.	Git and SSL Dependencies:
o	The reliance on Git for the Addon Manager introduces unnecessary complexity. Previously, I was able to manage my FreeCAD installation without Git or SSL certificates. Now, I need to troubleshoot issues such as SSL errors and Git configuration. This is a burden for users who wish to focus on modeling, not on debugging Git-related issues.
________________________________________
Steps to Reproduce the Spreadsheet Issue:
1.	Open FreeCAD 1.0 and select the "FreeCAD Classic" theme.
2.	Create a new Spreadsheet.
3.	Set the text color of cell A1 to black (RGB: 0, 0, 0) and the background to white (RGB: 255, 255, 255).
4.	Enter text into cell A1.
5.	Observe that the text disappears when the cell is not selected.
Expected Behavior: The text should always be visible, regardless of whether the cell is selected or not.
Actual Behavior: The text becomes invisible when the cell loses focus.
________________________________________
Suggestions for Improvement:
1.	Fix the Spreadsheet color display issue, ensuring that text and background colors render correctly in all themes.
2.	Reconsider the necessity of Git and SSL dependencies for the Addon Manager. Provide a fallback mechanism for users who prefer not to install or configure Git.
3.	Focus development efforts on modeling and drafting improvements rather than cosmetic changes like themes.
________________________________________
System Information:
•	FreeCAD Version: 1.0
•	Operating System: Windows 10 Pro  Version 22H2  Build 19045.5131
•	12th Gen Intel® Core™ i9-12950HX
•	RAM 64GB
•	Theme: FreeCAD Classic
•	Graphics: NVIDIA RTX A3000 12GB Laptop GPU
________________________________________
Additional Notes: "I have been using FreeCAD since around 2017, primarily in combination with my Prusa 3D printer. I have been very satisfied with the software and appreciate its versatility and open-source nature. Learning a new tool or switching to another solution would be very time-consuming for me. I am even willing to support FreeCAD to help improve the software for everyone."

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Help.backup1733761749.4561925 1.0.3
```

### Subproject(s) affected?

None

### Anything else?

![grafik](https://github.com/user-attachments/assets/2faa1218-ae63-419e-8d94-49b528f53a0e)
![grafik](https://github.com/user-attachments/assets/2f4d746e-9069-4594-ac4d-af9c2429df68)
![grafik](https://github.com/user-attachments/assets/e427e879-67b6-4897-b3a1-4716cd033d3e)
![grafik](https://github.com/user-attachments/assets/cff140f9-33f7-4481-9fae-4831efbe4324)
![grafik](https://github.com/user-attachments/assets/63e92be6-86a8-43bd-8ad1-de423e562358)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please create individual actionable issues and check if there might already be similar existing ones, e.g. https://github.com/FreeCAD/FreeCAD/issues/16950, https://github.com/FreeCAD/FreeCAD/issues/17984
You can add your findings there.
