### ISSUE TITLE
sheetmetal V0.2.45

### ISSUE THREAD

**Issue by Akimen64** [FreeCAD/FreeCAD#18427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi. I am using version 1.0.0, and I start the sheetmetal V0.2.45 work bench, it does not prompt any specific application related to the work bench. Also, Freecad prompt me an error message box saying quote : no module named drawing.
One more little thing is that the sheet metal work bench is not in the drop down list below in this form. Thanks.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: French/Canada (fr_CA)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * A2plus
  * ExplodedAssembly
  * fasteners
  * sheetmetal
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Last version of SheetMetal Workbench
0.6.01
2024-12-06

Version 0.2.45 was 4 years ago.
