### ISSUE TITLE
Techdraw: Balloon Bubble Shapes are filled when exported to PDF

### ISSUE THREAD

**Issue by chhoehn89** [FreeCAD/FreeCAD#18443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When exporting a Techdraw Page via File -> Export -> PDF, the Balloon Bubble Shapes are filled instead of outlines.
![Bug Balloon shape filled when exported to PDF](https://github.com/user-attachments/assets/eb553893-1308-4895-adad-6878f45d2c33)
Exporting to svg or dxf via the buttons in the Techdraw workbench works fine.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.60n
  * Curves 0.6.12
  * Defeaturing 1.2.0
  * fasteners 0.5.14
  * freecad.gears 1.0.0
  * lattice2 1.0.0
  * LCInterlocking
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can you please share the file as .zip and your PDF?

**Comment by WandererFan** [comment]
As a work around while I am investigating, pdf from the context menu seems to work correctly.
![BalloonTester-Page_fromContext](https://github.com/user-attachments/assets/43ae1aaa-c467-4898-89a0-020864c34afa)

**Comment by WandererFan** [comment]
The balloon's bubble is transparent.  Printing from the file/export menu makes a PDF/A-1b file.  PDF/A-1b does not support transparency.

Printing from the context menu makes a PDF 1.4 file.  PDF 1.4 does allow transparency.

There was a problem with PDF/A-1b support in some versions of Qt.  Might be fixed now? 

Going to fill the bubble with the page colour and try using PDF/A-1b again.
