### ISSUE TITLE
BIM: Non-IFC properties of BIM object are change upon changing of 'IFC Type' parameter

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#18453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This weird behavior occurs to me: when I create a BIM_Slab, I can change the thickness of the slab with a 'Height' property. But when I change the 'Ifc Type' property of the objects (for instance to Site), the height of the slab is suddenly changed and it is not influenced by the 'Height' property. 
Steps to reproduce:

- create rectangle
- create BIM_Slab from the rectangle
- change the height of the slab - everything is ok
- change 'Ifc Type' to site
- height of the slab changes, it is independent of 'Height' property

See behavior in video:

https://github.com/user-attachments/assets/af712c70-d423-47a0-a64d-665292be124c

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

BIM

### Anything else?

Different 'Ifc Type' property values have different influence on the height value

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@yorikvanhavre FYI

**Comment by yorikvanhavre** [comment]
I'll have a look... But indeed it shouldn't happen
