### ISSUE TITLE
Daily PPA: libfreecad-daily-python3-1.1 package missing files and dependencies

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#18455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After recently bumping the version of the FreeCAD daily packages from 0.22 to 1.1, the libfreecad-daily-python3-1.1 package has missing files and missing dependencies

More detail as reported in other places:
- https://github.com/FreeCAD/FreeCAD-Bundle/issues/354#issuecomment-2536840916
- https://forum.freecad.org/viewtopic.php?t=92865
- https://forum.freecad.org/viewtopic.php?style=4&t=92888

### Full version info

```shell
Package: libfreecad-daily-python3-1.1
Version: 1.1~pre1~202412121233~ubuntu22.04.1
Priority: optional
Section: libs
Source: freecad-daily
Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Installed-Size: 27,6 kB
Download-Size: 15,1 kB
APT-Manual-Installed: no
APT-Sources: https://ppa.launchpadcontent.net/freecad-maintainers/freecad-daily/ubuntu jammy/main amd64 Packages
Description: Extensible Open Source CAx program - Python 3 library files
 FreeCAD is an Open Source CAx RAD based on OpenCasCade, Qt and Python.
 It features some key concepts like macro recording, workbenches, ability
 to run as a server and dynamically loadable application extensions and
 it is designed to be platform independent.
 .
 Currently, FreeCAD can import and display CAD models in IGES, STEP, and
 BRep formats and meshes in STL, BMS, AST and Wavefront OBJ formats.
 Editing and modeling features are currently somewhat limited.
 .
 This package contains shared library files for FreeCAD built against Python 3.
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
Silly me, looks like I messed up the version number update. Hopefully this will fix it: https://salsa.debian.org/adrianinsaval/freecad/-/commit/fe60afde9a1a7bb832c29a2f35dbf2a14b18984c
