### ISSUE TITLE
Activate and deactivate quota on sketch

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#18450]
### Original PR

A

### Description and Justification

Can the function of hiding the single dimension with a space bar be implemented in the sketch? Selecting it individually on the work surface.

**Comment by luzpaz** [comment]
@Roberto8303 this ticket is incomplete. Please open a [new one](https://github.com/FreeCAD/FreeCAD/issues/new?assignees=&labels=Status%3A+Needs+triage%2CStatus%3A+Needs+confirmation&projects=&template=PROBLEM_REPORT.yml).
