### ISSUE TITLE
Dark Theme: Console errors colors bad for colorblind.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#18466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/user-attachments/assets/35eed1f5-1099-4a03-a5e6-1291f6670c7b)

I have the 'classic' type of colorblindness. And this red text in the dark theme is extremely painful for me to look at. I'm not sure why, but yes painful is the right word.

Can this color be changed to #f16101 @MisterMakerNL ?
![image](https://github.com/user-attachments/assets/4282d936-e304-4737-9929-8da603f653e0)

### Full version info

```shell
1.1
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Sensible change, similar to the Z axis / XY plane blue 😄
