### ISSUE TITLE
FreeCAD 1.0 installed on Windows: unable to open Preferences file with Unicode characters in Path

### ISSUE THREAD

**Issue by snooker52** [FreeCAD/FreeCAD#18495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

An error accured during creation of output transcoder. Msg is:
After start FreeCAT a select Theme popup message with errors:
unable to open file 'C:/Users/tom??/AppData/Roaming/FreeCAD/SavedPreferencesPacks/user.cfg.backup'
![FreeCAD-error](https://github.com/user-attachments/assets/1055ff39-2bb4-4938-b1d7-e87ac0ebe131)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Czech/Czech Republic (cs_CZ)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Did you have an older version of FreeCAD installed? Can you try restarting in safe mode (Help>Restart in safe mode).

**Comment by snooker52** [comment]
Older FreeCAD Version is deinstalled.

Error messages in Safe Mode:
11:28:49  C++ exception thrown (boost::filesystem::create_directories: P��stup byl odep�en [system:5]: "C:/Users/tomáš/AppData/Local/Temp/freecad-RHwZJo\UserAppData\SavedPreferencePacks\Backups", "C:/Users/tomáš/AppData/Local\Temp")
11:28:49  C++ exception thrown (boost::filesystem::create_directories: P��stup byl odep�en [system:5]: "C:/Users/tomáš/AppData/Local/Temp/freecad-RHwZJo\UserAppData\SavedPreferencePacks\Backups", "C:/Users/tomáš/AppData/Local\Temp")

**Comment by maxwxyz** [comment]
Does it also happen in the weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by snooker52** [comment]
No, it doesn't happen with weekly build 39560.

**Comment by maxwxyz** [comment]
@hyarion any idea what PR solved this?

**Comment by Syres916** [comment]
https://github.com/FreeCAD/FreeCAD/pull/18068

**Comment by maxwxyz** [comment]
then I'll close it as already fixed and backported. Will be in a 1.0.1 release soon.

**Comment by snooker52** [comment]
Thank you.
