### ISSUE TITLE
Crash after "File Migration Warning" issue on datum plane operation

### ISSUE THREAD

**Issue by rmdug** [FreeCAD/FreeCAD#18521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I’m working since V1.0 RC1 on a project I consider as a sandbox in order to try FreeCAD especially for top-down modelling.
Yesterday, after updating FC the file showed the following warning : 

" This file was created with an order version of FreeCAD.  Origin axes had incorrect placements, which have now been corrected.
However, if you save this file in the current version and reopen it in an older version of FreeCAD, the origin axes will be misaligned. Additionally, if your file references these origin axes, your file will likely be broken."

![image](https://github.com/user-attachments/assets/5f85d42c-c4c8-43a9-9a6d-58dc3139e297)

After saving the file I had to redefine a datum plane, which led to a crash.
After reopening FC the problem still occured.

I then tried to re-build the model from scratch in a new file. All went OK until I set a datum plane. FC crashed on first element selection.
After restart of FC and opening of the new file FC displayed again the file migration warning.

Currently I’m not able to create datum planes anymore, and thus cannot use FC at all : (.
You can find here enclosed the two files: the old one that I used from FC 1.0 RC1 and the new one I created from the last FC update (see below).

Thanks for your attention!

Regards,

Remi

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39642 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: c80bb958f377e4d43c6a4075da173a79d153db68
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: French/Belgium (fr_BE)
Stylesheet/Theme/QtStyle: ProDark.qss/FreeCAD Dark/Qt default
Installed mods: 
  * Render 2024.9.25
  * sheetmetal 0.5.6
  * Curves 0.6.51
  * freecad.gears 1.3.0
  * FreeCAD-themes 2024.7.24
  * GDT
  * fasteners 0.5.31
  * Glass
  * InventorLoader 1.4.0
```

### Subproject(s) affected?

None

### Anything else?

[FileMigrationCrash.zip](https://github.com/user-attachments/files/18138272/FileMigrationCrash.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should be fixed by https://github.com/FreeCAD/FreeCAD/pull/18515 in next weekly.
