### ISSUE TITLE
Base/Reader tests can fail randomly when run in parallel

### ISSUE THREAD

**Issue by bubbleguuum** [FreeCAD/FreeCAD#18549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Running the Reader tests contained in [Reader.cpp](https://github.com/FreeCAD/FreeCAD/blob/main/tests/src/Base/Reader.cpp) with `ctest` in parallel (which is the default) can cause some of them to randomly fail. I observed this on my 6 cores / 12 threads laptop. 

The reason is that a single temporary file `/tmp/unit_test_Reader.xml`  is used for all the tests. When they are run in parallel, the file is accessed concurrently read/write by several tests and some of them may fail because of broken XML.

The fix is to either change the code to use a unique temp file for each test (using for example `mktemp` or its boost equivalent) or modify the cmake configuration to instruct it that the the tests in `Reader.cpp` should be run sequentially.

For distro packagers, an easy work-around is to invoke `ctest` with `-j 1` to disable parallel execution.

### Full version info

```shell
OS: openSUSE Tumbleweed (xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git)
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.11, Qt 5.15.16, Coin 4.0.2, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
> The fix is to either change the code to use a unique temp file for each test (using for example mktemp or its boost equivalent) or modify the cmake configuration to instruct it that the the tests in Reader.cpp should be run sequentially.

> For distro packagers, an easy work-around is to invoke ctest with -j 1 to disable parallel execution.

It makes sense in the: 
**Short term** to set `crest -j 1`
**Long term**  modify cmake to make sure certain tests are run before others
