### ISSUE TITLE
 language translation problem

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#18551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

incomplete translation, some words are not translated into Italian
![lenguage ita](https://github.com/user-attachments/assets/c6a54090-5d59-4643-a773-7e75f0fe6e0f)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39646 (Git) Conda
Build type: Release
Branch: main
Hash: b25b83c1a58bf0ae95cbd502d0ccae27e8127cad
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * CurvedShapes 1.0.13
  * ExplodedAssembly
  * fasteners 0.5.33
  * FeedsAndSpeeds 0.6.0
  * FreeCAD-themes 2024.7.24
  * Glass
  * IconThemes
  * OpenTheme 2024.9.1
  * PieMenu 1.10.1
  * Render 2024.11.22
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roberto8303** [comment]
tell me where I should translate

**Comment by luzpaz** [comment]
In crowdin you can search for the string you want to translate and it should find. Hint: pay attention to where it is in the interface, for example: if the translation is in the PartDesign workbench - then look for the search result to be in the PartDesign.

**Comment by Roberto8303** [comment]
And is it under the display function? Then once corrected in Italian what happens is reported in the next weekly build?

**Comment by maxwxyz** [comment]
I think there was a larger issue with https://github.com/FreeCAD/FreeCAD/pull/17944 which also had the same behavior in the German weekly. Please test with the next weekly tomorrow.
