### ISSUE TITLE
creation of the reference plane. Crash!

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#18554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

when you create a new reference plane and insert incorrect attachment points the program closes
![Cattura](https://github.com/user-attachments/assets/e86519c2-82d7-4afa-ad07-6f525fea1ffe)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39646 (Git) Conda
Build type: Release
Branch: main
Hash: b25b83c1a58bf0ae95cbd502d0ccae27e8127cad
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * CurvedShapes 1.0.13
  * ExplodedAssembly
  * fasteners 0.5.33
  * FeedsAndSpeeds 0.6.0
  * FreeCAD-themes 2024.7.24
  * Glass
  * IconThemes
  * OpenTheme 2024.9.1
  * PieMenu 1.10.1
  * Render 2024.11.22
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should already be fixed in tomorrows weekly build, please report back if there is still an issue.
