### ISSUE TITLE
BIM: Arch.py missing doctrings

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#18560]
As of now, the following 2 functions do not have docstrings:

https://github.com/FreeCAD/FreeCAD/blob/1289997dfd604cb24f060f905f04ec3728d964e4/src/Mod/BIM/Arch.py#L800
Suggestion: ???

https://github.com/FreeCAD/FreeCAD/blob/1289997dfd604cb24f060f905f04ec3728d964e4/src/Mod/BIM/Arch.py#L892
Suggestion:  
```python
def makeRailingLorR(stairs,side="L"): 
    """makeRailingLorR(stairs,side="L"): Figure out what side the railing is on: left or right"""
```

**Comment by yorikvanhavre** [comment]
Those two functions are internal functions inside a public API function. They are not usable directly by someone using the Arch module, so I would say in this case docstrings are not really needed as they will never be seen by anybody, but of course it's always best to have them.

I would suggest:

```python
def makeRailingLorR(stairs,side="L"):
    """makeRailingLorR(stairs,side="L"): Creates a railing on the given side of the stairs, L or R"""
```

and 

```python
def setProperty(obj,length,width,height,steps):
    """setProperty(obj,length,width,height,steps): sets up the basic properties for this stair"""
```
