### ISSUE TITLE
PartDesign: Pad feature not working for another isolated sketch

### ISSUE THREAD

**Issue by vironaxe** [FreeCAD/FreeCAD#18581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The problem is that the pad feature is not working when I create another sketch that I want to select for pad. I have attached the video (watch with audio) which shows that nothing happens when I try to apply this feature. While playing around, I assigned revolve feature to the sketch but then the first body disappears.

https://github.com/user-attachments/assets/c9cc0fcf-5a3b-4675-81ef-8962c4069ecb

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

None

### Anything else?

I have attached the FCStd file.

[tutorial_2.zip](https://github.com/user-attachments/files/18169148/tutorial_2.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Confirm. Before it was error message about multiple body.

Set Allow compound = True
![Screenshot_20241217_193810_opti](https://github.com/user-attachments/assets/1faeaf0e-e02d-4f76-9836-2afae50f1105)

**Comment by luzpaz** [comment]
why was this closed?

**Comment by vironaxe** [comment]
I closed it because the issue was solved by [tarman3](https://github.com/tarman3). As shown by him in the photo above, the _Allow Compound_ option should be set to _True_ which allowed the second sketch to be padded.

**Comment by tarman3** [comment]
This solves the problem, but before FreeCAD gave an error and it was better than doing nothing.
