### ISSUE TITLE
CAM: Metric unit system settings not updated

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#18596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![foto1](https://github.com/user-attachments/assets/c2a6e233-f23a-41e3-85a0-dbcdfea95203)
![fot2](https://github.com/user-attachments/assets/ec34ce6b-97cf-4e8d-9f14-0b42e6376b59)
By setting the units of measurement in mm/min, in CAM the units are always in meters/sec

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39673 (Git) Conda
Build type: Release
Branch: main
Hash: 1289997dfd604cb24f060f905f04ec3728d964e4
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * CurvedShapes 1.0.13
  * ExplodedAssembly
  * fasteners 0.5.33
  * FeedsAndSpeeds 0.6.0
  * FreeCAD-themes 2024.7.24
  * Glass
  * IconThemes
  * OpenTheme 2024.9.1
  * PieMenu 1.10.1
  * Render 2024.11.22
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
Units are set at document level by the pushbutton menu in the lower right hand corner that shows the extents of the view by default. The setting in the screenshot is for system units, i.e. when creating a new document as per Wiki https://wiki.freecad.org/Preferences_Editor#General_2
