### ISSUE TITLE
Part: Solid body loses color after recalculation

### ISSUE THREAD

**Issue by notenwendig** [FreeCAD/FreeCAD#18718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Solid body loses color when recalculating after importing file from version: 0.21.1.33668 +26 (Git)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Please attach file with exampe

**Comment by Syres916** [comment]
This is another duplicate of https://github.com/FreeCAD/FreeCAD/issues/18584
