### ISSUE TITLE
Part -> View -> Create New View => Segmentation Fault on Gentoo

### ISSUE THREAD

**Issue by dnt2git** [FreeCAD/FreeCAD#3]
Hi
I've been experiencing this for the last month. 

Part -> Create a box -> View -> Create new view  => Segmentation Fault

OS: Linux
Platform: 64-bit
Version: 0.13.1756 (Git)
Branch: master
Hash: bd5359f542a3fb1f10f050fb29498b0db3b52173
Python version: 2.7.3
Qt version: 4.8.2
Coin version: 3.1.3
SoQt version: 1.5.0
OCC version: 6.5.4

Repeatability: Always

No previous experience with FreeCAD nor known history of the problem.

Advice and hints welcome

Thanks
D.T.

**Comment by chennes** [comment]
Closing pending migration of bugs from Mantis.
