### ISSUE TITLE
[Feature] Arch: Auto dimension tool that adds dimensions to a set of objects

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5550]
Issue imported from https://tracker.freecad.org/view.php?id=515

* **Reporter:** @yorikvanhavre
* **Date submitted:** 12/5/2011

# Original report text

A tool that automatically adds dimensions to a set of objects:

Select objects, select a point, another point, and the selected objects are measured, with dimensions passing through the 2 points. The result is a "Dimension set" object containing Draft dimensions, where you can change later on which objects are measured, and which "style" of measurement to apply (only biggest exterior dimension, including windows, interior style, etc...)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
@yorikvanhavre have you seen a macro like this since you made this FR ?

**Comment by yorikvanhavre** [comment]
No I haven't... It's really low priority, though.

**Comment by WandererFan** [comment]
Closed as replaced gsoc 2023 unified measurement facility.
