### ISSUE TITLE
Macro editing FCMacro file - 4 improvements

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5551]
Issue imported from https://tracker.freecad.org/view.php?id=573

* **Reporter:** pperisin
* **Date submitted:** 1/17/2012
* **FreeCAD version:** 0.12
* **Category:** Feature
* **Status:** new
* **Tags:** #lowhangingfruit, macros, split ticket

# Original report text

Enhancements that would help with FreeCAD macro scripting:

- [ ] **Auto-indent**: if the line I'm writing something in has i.e. 6 spaces before first character, when I press enter I go to the next line but at it's beginning. I would like to have 6 spaces automatically added when I press enter in this case.
- [ ]  **Multi-line editing**: The easiest way to explain this one is if you open some document in notepad++. then press ALT key and select multiple lines. you will see how it selects in a row+column like way. Also, when you have stuff selected this way, Writing anything will add those characters to all those selected lines.
- [ ] **Code completion** and a list that appears after pressing `.` (same behavior as in the FreeCAD Python console)
- [x] **Find and replace** text :arrow_right:  **Added in the https://github.com/mwganson/Editor_Assistant/ macro**
- [ ] **Python Debugger** see #5540 

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by pperisin 2012-01-18 06:00
oh, another one - Find and replace text

---

### Comment by Kunda1 2017-02-02 14:15
Do you have any interest working on these features at all ?

---

### Comment by Kunda1 2017-04-29 12:54
Check out mumme work in https://forum.freecadweb.org/viewtopic.php?f=10&t=21898
(Also attached #5540 to this ticket)

**Comment by luzpaz** [comment]
CC @mwganson

**Comment by luzpaz** [comment]
@mwganson can we close this ticket based on your macro?

**Comment by mwganson** [comment]
I'm not opposed to it if somebody wants to work on it, but I don't have any plans at this time to work on adding any of these features.

**Comment by luzpaz** [comment]
If there are devs interested, please check out https://github.com/mwganson/Editor_Assistant/issues/11

**Comment by adrianinsaval** [comment]
IMO the best way to tackle this would have been using ktexteditor instead of the current, at least for indentation, search and replace, block editing and probably some code completion.

**Comment by WandererFan** [comment]
Closed as not planned.

**Comment by mwganson** [comment]
This PR adds the automatic indentation when pressing Enter key.

https://github.com/FreeCAD/FreeCAD/pull/11356

Note: Ctrl+Space already provides an autocompletion mechanism.  I believe it is based on searching for text that already exists in the current document that could be used to automatically complete the current word.

**Comment by luzpaz** [comment]
Thanks @mwganson! 
In regards to multiline editing, would that be something that could be implemented in the python editor ?

**Comment by mwganson** [comment]
I don't have any plans for working on multiline editing at this time.
