### ISSUE TITLE
Sketcher: geometry flips erratically while dragging

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5555]
Issue imported from https://tracker.freecad.org/view.php?id=754

* **Reporter:** jmaustpc
* **Date submitted:** 6/16/2012
* **FreeCAD version:** 
* **Category:** General
* **Status:** assigned
* **Tags:** #pending, constraints, Solver

# Original report text

This file is two lines on a circle. The way it is constrained, you can drag the "triangle" in circles around the circle, which partly works.

A vertical or horizontal constraint set on the apex of the triangle will cause it to think it is fully constrained, when it should have two possible locations.

The "triangle" also can be dragged with the mouse when the apex is not constrained, but after it has gone most of the way around the circle, the triangle suddenly flips to the other side of the circle. 

# Additional information

Version: 0.13.1157 (Git)
Branch: sketcher
Hash: cad41483eb5bd175f9755eb4e21b04043207e3e3

I am wondering if this is a problem with how "length along line constraint" works? I might well be talking complete crap, but I was wondering if the horizontal and vertical distant constraint is working of the x and y value of the length along the line constraint rather than truly working on its length. If so that could explain what is going on.

# Steps to reproduce

1) if you drag the "triangle" around the circle it goes most of the way around and then suddenly flips to the other side.... then if you keep the mouse pointer going around the circle, the triangle suddenly flips back again.
2) If you select the apex of the "triangle" and then set either one horizontal distance or one vertical distance constraint it says the sketch is fully constrained, which it is not. If you look at the screen shots attached you will see the two valid possible out comes for a vertical distance constraint. The error is the same type of thing if you set horizontal distance constraint
3) if you set lock constraint on the apex it complains of being over constrained ....which might or might not be the case.
4) this point happened the first two times I tried to set vertical distance constraint but after closing and reopening the file, I have not yet managed to get it to repeat. I will test further on this point. When the apex was one the right hand position of the two possible outcomes for vertical constraint on the apex, it inserted the correct vertical value but flipped the triangle over to the lower left hand side (the second possible outcome for that vertical constraint value)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** General
* **OS: Kubuntu 12.04**
* **Platform:** 32 bit
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by jmaustpc 2012-06-16 06:59
I managed to get the error 4), or something similar to be repeatable. I not sure if this is more of a problem with the undo system, hence maybe should be on a different ticket, for now it is just a note on the existing ticket in my last post above.

1) move the apex of the triangle to point somewhere towards the lower right quadrant
2)set a vertical distance constraint on the apex
3) click "undo" on the tool bar to remove the last added vertical distance constraint
4) move the apex of the triangle to point somewhere towards the lower left quadrant
5) set a vertical distance constraint on the apex

rather than setting the then current correct default value for vertical distance constraint, ....FreeCAD will push the apex back to the position it had been in prior to the "undo", and set the what should have been a new value default vertical constraint value back to what it had previously been prior to the undo.

---

### Comment by jmaustpc 2012-06-16 07:00
This is a link to the topic on the forum

http://forum.freecadweb.org/viewtopic.php?f=10&t=2706&p=20622#p20622

---

### Comment by logari81 2012-06-17 09:42
this is a difficult one. Currently there is no mechanism in the solver for handling multiple solutions and I don't believe that we will have such a possibility soon. However, it is nice to have this test case as a reference when we decide to implement the handling of multiple solutions. Until then, users have to be a bit more clever in order to avoid ambiguous dimensioning.

---

### Comment by jmaustpc 2012-06-18 00:26
I have added another example to the same topic in forum

http://forum.freecadweb.org/viewtopic.php?f=10&t=2706&p=20641#p20641

In this example I don't think its the same, I mean its not an multiple solution, I don't think. 

It is an example where an extra superfluous "=" constraint can be added without causing an over constrained error.

---

### Comment by jmaustpc 2012-06-18 00:34
To be clear, in case it is important, the three files posted to the forum, the first I noticed the superfluous "=" constraint and thought "that's not right", used "save as" to get the second file then deleted the "=" and noticed that it was still fully constrained and I got no error messages. So I "saved as" again to get the third file and then noticed that I could put the "=" back in there even though the file had been in a fully constrained state before I clicked on "=" and it still didn't give me an error message.

---

### Comment by jmaustpc 2012-06-18 00:44
Here is another example of where there is a multiple solution with the tangent constraint in these two examples. The tangent can be in either direction, I have included some screen shots two illustrate this particular example. Of course in this file there are more possibilities when one considers the other tangent.

I've posted the files to the forum topic, at the above url.

---

### Comment by jmaustpc 2012-06-18 01:02
This is the version data for the last three posts today.

version data
Kubuntu 12.04 32bit
Platform: Ubuntu 12.04 LTS (32-bit)
Version: 0.13.1162 (Git)
Branch: master
Hash: e05fcc7daf7d806c9766cfe75ca2b4880c3dccf0
Python version: 2.7.3
Qt version: 4.8.1
Coin version: 3.1.3
SoQt version: 1.5.0
OCC version: 6.5.1

---

### Comment by abdullah 2017-12-08 15:52
kunda1
jmaustpc

I am not able to reproduce this with the current master. I am not sure if I am missing something. 

May some power user check it up with a current version?

---

### Comment by Kunda1 2017-12-09 01:36
chrisb do you mind checking ?

---

### Comment by Kunda1 2017-12-11 06:26
jmaustpc please re-check ticket when you get a moment, thanks!

---

### Comment by chrisb 2017-12-21 10:29
I can reproduce it - of course - because it's the well known behaviour. The current definition of solved is: There is no smooth transition to another solution.
So it works as designed and is definitely not a bug. abdullah may comment if there is a chance to get a solver where solved means: this is the one and only solution. If so this can be a feature request, if not it can be closed.

---

### Comment by Kunda1 2018-01-25 16:58
abdullah please take a look at chrisb's response in ~10623

---

### Comment by abdullah 2018-01-27 17:19
chrisb

Man! I cannot move that triangle. I have tried dragging all the three points and the two edges, in I would say any direction.

When you can reproduce it, what are you dragging?

---

### Comment by abdullah 2018-06-15 16:49
Sorry, I mixed two different aspects of the bug. Yes, I can reproduce.

To me from this example what is pending is the "flipping", which still happens even with the improved dragging implemented at the end of last year.

Regarding the multiple solution, I do not forsee any change in behaviour. The solution is valid. It is somehow similar to x^2=4, x=2, x=-2, both solutions are valid.

**Comment by adrianinsaval** [comment]
should this issue be closed or have a better description to make it clear it is now about constraints flipping?

**Comment by AjinkyaDahale** [comment]
By the title this appears to be a feature request. @adrianinsaval it seems from your last comment that the conversation moved to a different direction altogether?

**Comment by luzpaz** [comment]
@adrianinsaval if it's about constraint flipping then it's related to #6709 which has been closed as a "won't fix", right?

**Comment by adrianinsaval** [comment]
It is about flipping, but specifically while dragging (or rather, it ended up being about that)
![FreeCAD_2KcRQCoP3T](https://user-images.githubusercontent.com/36372335/232254279-06aca668-bf6d-4f12-a693-0fbf5ef338a3.gif)
I reupload the file here for convenience:
[circle_tangent_sketch_fully_constrained_error.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11240730/circle_tangent_sketch_fully_constrained_error.FCStd.zip)

**Comment by adrianinsaval** [comment]
there is one other thing from the original report that I believe remains unaddressed, when you place _both_ horizontal and vertical distance constraints on the triangle apex it is over constrained, but thinking conceptually this would instead properly lock the vertex to a single solution instead of 2.

**Comment by AjinkyaDahale** [comment]
@adrianinsaval what do you mean by "place horizontal and vertical constraints on the apex". From what I can tell the length of the tangent is dictating that only one of the constraints can be applied.

**Comment by adrianinsaval** [comment]
If you constrain from origin, applying only vertical or only horizontal distance means there is two possible solutions. The sketch can flip depending on which is closer. An additional constraint would conceptually fix which of those two solutions is correct, but to the solver this is overconstraining

**Comment by AjinkyaDahale** [comment]
> An additional constraint would conceptually fix which of those two solutions is correct, but to the solver this is overconstraining

This is almost in a "feature request" territory. Additionally, even if we are able to obtain a discrete number of solutions, some of those solutions might not be what we want, and very different than the original/intended sketch.

**Comment by abdullahtahiriyo** [comment]
And the problem has consistently been that the solver does not know which solution the user wants from those meeting the constraints...

**Comment by adrianinsaval** [comment]
Let's discard that side of the request as won't fix, I don't see how to solve overconstrained sketches numerically. In theory the overconstraints can reduce ambiguity of the solutions, when the sketch is fully constrained as described here there are actually 8 possible solutions not just 2 as first said, and additional constraint can discard 4 of those solutions.

Anyways, the actual problem at hand is the erratic flipping of unconstrained geometry while dragging

**Comment by abdullahtahiriyo** [comment]
The solver will not work properly with overconstraints. One would need better constraints (constraints that are more robust, more precise and restrict a solution, for example by having directional properties). won't fix sounds good to me in this case.

**Comment by maxwxyz** [comment]
Following this discussion, is this still an issue worth trying to fix or could this be closed?

**Comment by AjinkyaDahale** [comment]
> Following this discussion, is this still an issue worth trying to fix or could this be closed? 

It has been called "won't fix" quite often so I guess we can.

> Is this related to: #5763

The difference I could gather is that this commit is about dragging and that one is about which solver to use (when dragging?). I don't see much discussion there in the issue so I'll comment more if I find something in the forum post.

**Comment by vollyimnetz** [comment]
This is a rather nasty behaviour. If its currently not automatic solvable (as the constrain system is not powerfull enough), wouldnt it be good to have some **button for half-automated flip the constrain**. If its had two valid positions but could not determine whats the correct one, a button to switch to the second (correct) position would speed editing a hole lot. Currently if have to (1) remove the constrain, (2) move the geometry, (3) add the new constrain - which is very tedious.
