### ISSUE TITLE
Robot Tools are not correctly placed when robot has another placement

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5562]
Issue imported from https://tracker.freecad.org/view.php?id=1089

* **Reporter:** luigirin
* **Date submitted:** 4/8/2013
* **FreeCAD version:** 0.13
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

If I place a robot on a placement different from the origin frame and then i place connect a tool, this one is placed as if the robot was in the origin position. If I connect first the tool and then I move the robot with a placement the toll goes in their original position.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
Closing since Robot workbench hasn't been maintained in a long time. From the [wiki page](https://wiki.freecad.org/Robot_Workbench):

> The Robot Workbench is unmaintained. If you have experience with the topic and are interested in maintaining it, please state your intention in the developer's section of the [FreeCAD forum](https://forum.freecadweb.org/index.php).

> The reason this workbench is still in the master source code is because this workbench is programmed in C++. If this workbench could be programmed in Python, then it could be made an [external workbench](https://wiki.freecad.org/External_workbenches) and it could be moved to a separate repository.
