### ISSUE TITLE
[Feature Request] Extend Draft Edit mode to work with 3D shapes

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5579]
Issue imported from https://tracker.freecad.org/view.php?id=1367

* **Reporter:** yorik
* **Date submitted:** 1/27/2014
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Allow to edit simple, non-parametric prismatic shapes

in Draft Edit:
- check if the object has no curves (all edges are derived from Part Line)
- get the position of an original vertex and its new position

in a new Draft function:
- find the vertex that has the original position
- find all faces that have that vertex
- redo these faces with the new vertex
- rebuild a shell from all faces
- rebuild a solid from the shell, if the original one was  a solid

possible extension:
- instead of eding the original shape, create a new parametric feature, that links to the original object and its vertex, and has a "delta" property. This would allow to elso edit parametric objects, and keep the edit.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by yorik 2014-01-27 14:08
Forum thread: http://forum.freecadweb.org/viewtopic.php?f=10&t=5369&p=44354

---

### Comment by carlopav 2020-06-14 20:21
This issue is quite old it seems. yorik, do you still think this could be something to implement in Draft_Edit or we'd better address Moult partial work on subelement modifiers?

---

### Comment by yorik 2020-06-15 08:16
Well Draft Edit has come a long way since then... You are more able to assess this question than me now, probably. I would say maybe we could make it into a kind of full feature now, which could make changes parametric.

---

### Comment by carlopav 2020-06-15 17:12
Well, it's a difficult question: DraftEdit it's already a quite complex tool, it deals with a ton of different object from Draft, Part, Arch, Sketcher WBs. All those objects are treated parametrically (it means we do not modify the shape directly, but modify parameters such as vector lists, length, radius, angles, etc...)
So to introduce the shape modification seems quite odd to me... and what mostly seems strange is to do it just by points: what if we want to move a face? what if we want to move an edge? If we move just one point of a cube face, and then the others, in the meantime we obtain a bspline surface, or whatever other strange surface...
So to me it's better if we limit Draft Edit to parameter editing and we complete Moult work on subelements modifiers. At the moment those tools are really in bad shape: they just work on Draft Wire. It would be better to me to adapt them to modify raw part shapes directly instead of changing a vector list... 
What do you think?

---

### Comment by yorik 2020-06-15 18:48
I had in mind something like: 1) user moves a face. 2) identify all edges of that face 3) move the edges 4) identify all verts that have moved 5) recalculate all needed edges 6) recalculate all needed faces. This operation would be stored in a new feature on top of the original object. So yeah it's a pretty different operation than draft edit. Actually this is more a generic idea that is not really related to draft anymore..

---

### Comment by carlopav 2020-06-15 20:51
Yes, I agree...
I think anyway that this kind of task that you imagine can be added to draft subelements move... it's just not so straightforward to implement, but neither impossible...
Should we change the issue title to readdress it or just close it?

**Comment by yorikvanhavre** [comment]
Superseded by #5764
