### ISSUE TITLE
Respect symbolic links

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5592]
Issue imported from https://tracker.freecad.org/view.php?id=1666

* **Reporter:** triplus
* **Date submitted:** 8/4/2014
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** #lowhangingfruit, Qt, Qt5

# Original report text

Based on discussion in this feature request:

http://www.freecadweb.org/tracker/view.php?id=1665#c4918

# Steps to reproduce

1.) Create new folder and save test .fcstd file in this folder
2.) Create symbolic link to test .fcstd file (ln -s) from different directory
2.) Open the file in FreeCAD by clicking on just created symbolic link
3.) Modify the file and save the changes

Expected behaviour:

FreeCAD saves the changes at original test .fcstd file location. Backup files are saved to original test .fcstd file location.

Current behaviour:

FreeCAD saves the changes at symbolic link test .fcstd file location. Backup files are saved to symbolic link test .fcstd file location.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Ubuntu 14.04**
* **Platform:** Linux
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by triplus 2014-10-25 22:55
For future reference if anybody will try to tackle this area and to provide symbolic links support for FreeCAD this is how Qt Creator deals with symbolic links:

https://qt.gitorious.org/qt-creator/qt-creator/commit/a8ee92a53ba4b1c4c7e2c34db27ee44ed7e9c585

Relevant discussion (don't rewrite symlink on save, rewrite target instead):

https://qt.gitorious.org/qt-creator/qt-creator/merge_requests/399

---

### Comment by Kunda1 2017-03-10 23:14
triplus can you find a more up-to-date source? since Qt seems to have moved their repo.

---

### Comment by Sam 2017-09-03 00:07
Forum thread: [Issues 1665 & 1666; Symbolic links & backups](https://forum.freecadweb.org/viewtopic.php?f=10&t=24195)

**Comment by luzpaz** [comment]
Related to backups. Linking to #6697 and #6045
