### ISSUE TITLE
Change default draft precision to allow planar surfaces from dwire

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5598]
Issue imported from https://tracker.freecad.org/view.php?id=1786

* **Reporter:** more11
* **Date submitted:** 10/13/2014
* **FreeCAD version:** 0.14
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

See forum discussion: http://forum.freecadweb.org/viewtopic.php?f=3&t=7989

Increase default precision to 8 digits in order to avoid extrusion problems. Alternatively don't truncate position values when using snap.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Windows 7 64 bit**
* **Platform:** Dell XPS
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by more11 2014-10-13 16:34
OS: Windows 7
Word size: 64-bit
Version: 0.14.3700 (Git)
Branch: releases/FreeCAD-0-14
Hash: 32f5aae0a64333ec8d5d160dbc46e690510c8fe1
Python version: 2.7.6
Qt version: 4.8.5
Coin version: 4.0.0a
SoQt version: 1.6.0a
OCC version: 6.6.0

---

### Comment by shoogen 2014-10-13 16:58
increasing the draft precision will break code elsewhere (liuke dxf and svg import). IMHO changing snapping should be the preferable solution.

---

### Comment by more11 2014-10-16 16:23
There is also a problem with tessellation. I have another thread about that at the forum: http://forum.freecadweb.org/viewtopic.php?f=3&t=8042. 

Maybe change the default tessellation value to 0.05% as well?

**Comment by Roy-043** [comment]
The issue cannot be reproduced in V0.21.
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.21.31058 (Git)
Build type: Release
Branch: master
Hash: e6c53d8642af36ce7d738ab6058b063ec58e0859
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
```
