### ISSUE TITLE
Move Export 3D SVG From Export To Tools Menu

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5599]
Issue imported from https://tracker.freecad.org/view.php?id=1792

* **Reporter:** quick61
* **Date submitted:** 10/20/2014
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** #pending

# Original report text

Export 3D SVG is a capture of the 3D view and does not facilitate the selection of individual objects within the document. Thus, 3D SVG export does not behave the same way as the other export formats do, including Flattened SVG. 

Therefor 3D SVG export has more in common with the Tools > Save picture function than it does with actual export functions. 

# Additional information

FreeCAD Forum thread - http://forum.freecadweb.org/viewtopic.php?f=3&t=8099

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: All **
* **Platform:** All
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
Export 3D SVG no longer exists. Closing this as stale.
