### ISSUE TITLE
Ball corner

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5600]
Issue imported from https://tracker.freecad.org/view.php?id=1801

* **Reporter:** Pauvres_honteux
* **Date submitted:** 10/26/2014
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** #post-to-forum, ball corner, variable fillet

# Original report text

I'd like to propose a feature called "ball corner".
As I saw dubstar-04 starting on variable fillets I thought this would be one step closer to become reality, although it might be a feature on its own.

A principally example: http://www.dkszone.net/wp-content/uploads/2010/05/CATIA_Part_with_blended_corner_Edge_Fillet_7_.jpg

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2017-06-24 11:12
Pauvres_honteux please post to forum and bi-directionally link ticket<=>thread so people associate one to another. Thx!

---

### Comment by Pauvres_honteux 2017-06-24 12:59
[Variable radius fillet](https://forum.freecadweb.org/viewtopic.php?f=19&t=8022&hilit=variable)

---

### Comment by Kunda1 2017-06-26 13:03
Pauvres_honteux I bumped the forum thread. Too bad that user (dubstar) didn't share his work. Let's see what happens.

**Comment by adrianinsaval** [comment]
"example" link is spam 🤬

**Comment by chennes** [comment]
Since the example link appears to have been hijacked and there is no forums discussion, I am closing this. If someone runs across this and would like to elaborate on the feature request, please open a new issue.
