### ISSUE TITLE
Bool Op  representation error

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5602]
Issue imported from https://tracker.freecad.org/view.php?id=1818

* **Reporter:** @microelly2
* **Date submitted:** 11/7/2014
* **FreeCAD version:** 0.14
* **Category:** Bug
* **Status:** confirmed
* **Tags:** #pending

# Original report text

A Pocket on a Box or the bool difference of two part::Box:

two of the orthogonal views in the 3D windows have errors
hidden inner edges are shown!

The case pad - pocket works fine.

# Steps to reproduce

see the example file [issue5602.zip](https://github.com/FreeCAD/FreeCAD/files/8557957/issue5602.zip)  
go through all ortho views

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by quick61 2014-11-07 19:46
I think this error is being caused by a forked model. A properly constructed model does not show this problem. See the dependency graph of the attached file.

What is being seen visually in the 3D view is not the same that is seen mathematically inside FreeCAD when projecting the 2D view from a forked model.

---

### Comment by microelly2 2014-11-07 23:08
No, its not the fork, I have packed two cases into one file

if you delete the pocket so that there are only the two cubes and the cut the representation error ist still there.

the same if you delete the outer path.

the error occurs already in the case cut: box - box
(on my computer:

OS: Ubuntu 14.04.1 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.15.4159 (Git)
Branch: master
Hash: fa3a2a0d3a7a0a619ab6323e236376bb43636e79
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.7.1

---

### Comment by quick61 2014-11-07 23:57
Switch your "View from: X +ve" to "View from: X -ve" and leave "Axis aligned right: Y +ve"

---

### Comment by Kunda1 2017-01-20 01:53
microelly2 does ~5290 help ?

---

### Comment by Kunda1 2017-01-28 13:49
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=20312

---

### Comment by normandc 2017-01-29 17:11
What quick61 suggests is for the creation of 2D projected views in the Drawing workbench. The problem in this bug report relates to the 3D view. It still persists in current master when switching to a standard view. But doing a zoom "Fit All" corrects the issue and it no longer appears afterwards.

OS: Ubuntu 14.04.5 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.9822 (Git)
Build type: None
Branch: master
Hash: 0df4af4ba5e6edce825af6ecf6d024c704292633
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17

---

### Comment by Kunda1 2017-02-16 14:27
Issue still persists in:
<code>OS: Ubuntu 14.04.5 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.10091 (Git)
Build type: None
Branch: master
Hash: 3076b5938f3af5b7a3375c6aa8471bbacb9d6c4a
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17</code>
ref: https://forum.freecadweb.org/viewtopic.php?f=10&t=20312#p160229

---

### Comment by Kunda1 2017-02-16 16:07
https://youtu.be/pCDEJtFC6rs <== screencast showing issue

**Comment by luzpaz** [comment]
Closing since we think it is a display driver issue.
