### ISSUE TITLE
Fillet after thickness gives invalid geometry (upstream OCC Bug)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5604]
Issue imported from https://tracker.freecad.org/view.php?id=1840

* **Reporter:** ShapeShifter
* **Date submitted:** 11/26/2014
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** #pending, #ready-for-migration, bump, OCC Bug, OCC NotOnRoadmap, upstream

# Original report text

Putting a fillet on the inside corner of a thickness box creates an invalid shape.

# Additional information

I am using:

OS: Ubuntu 12.04.5 LTS
Word size of OS: 32-bit
Word size of FreeCAD: 32-bit
Version: 0.15.4159 (Git)
Branch: master
Hash: fa3a2a0d3a7a0a619ab6323e236376bb43636e79
Python version: 2.7.3
Qt version: 4.8.1
Coin version: 3.1.3
OCC version: 6.7.1

so the problem seems to be caused by the positive thickness somehow, when the part "grows"

Hope this helps

# Steps to reproduce

go to part workbench
make a cube 100 mm all over
run geometry checker - no errors
select the top face of the cube
use thickness to make +10 mm sides and bottom
run geometry checker - no error
Select one of the inside vertical edges
fillet it with 6 mm radius
run geometry checker - error is "bad orientation of sub shape"
delete the fillet and thickness
make a new thickness with -10 mm
run geometry checker - no error
select a vertical inside edge and fillet 6 mm radius
run geometry checker - no error

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Linux 12.04.5 lts**
* **Platform:** Ubuntu 
* **Updated:** 1/24/2022

# Discussion from Mantis ticket

### Comment by shoogen 2014-11-26 18:10
http://tracker.dev.opencascade.org/view.php?id=25521

---

### Comment by Kunda1 2017-01-24 19:18
Can someone bump the upstream bug ?

---

### Comment by wmayer 2017-09-02 13:07
In occ 7.2 the error is slightly different: it now reports that the tolerance value is invalid

---

### Comment by Kunda1 2018-10-13 14:26
wmayer any changes in 7.3 ?

---

### Comment by wmayer 2018-10-14 17:18
Still the same behaviour with 7.3

---

### Comment by chennes 2021-09-16 19:59
I do not get this problem with 

OS: Ubuntu 21.04 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.25731 (Git)
Build type: Unknown
Branch: master
Hash: e305dbd49caa2ede83dab8e8c34a4180b2cf26cc
Python version: 3.9.5
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.1
Locale: English/United States (en_US)

---

### Comment by chrisb 2021-09-17 05:46
No issues, confirmed in the [forum discussion](https://forum.freecadweb.org/viewtopic.php?p=533635#p533635). Before closing: how can we notify OCC?

OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.25645 (Git)
Build type: Release
Branch: master
Hash: 37d9757399b4c2ec30318eb88d7cd7c508246345
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: C/Default (C)

---

### Comment by Kunda1 2022-01-15 13:06
Who has upstream tracker access? chennes abdullah ? Could someone notate the upstream ticket? (http://tracker.dev.opencascade.org/view.php?id=25521)

**Comment by adrianinsaval** [comment]
seems to be fixed, I don't get any errors in geometry check, even with BOP check enabled
```
OS: Linux 5.16.8-arch1-1 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27465 (Git)
Build type: Release
Branch: master
Hash: 092afacfcb5127eb67c385a43cbe34a4cd15bef4
Python version: 3.10.2
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)
```
@chennes can you inform upstream too?

**Comment by chennes** [comment]
I have notified the upstream via their bug tracker.

**Comment by chennes** [comment]
Upstream reports that the bug as reported still crashes with the DRAW test case we provided. We must have made an internal change that affected the result.

**Comment by luzpaz** [comment]
upstream reporting the crash persists: https://tracker.dev.opencascade.org/view.php?id=25521#c106884

**Comment by luzpaz** [comment]
Guess this should be closed.
