### ISSUE TITLE
Add the capability to communicate as  a client with a BIMSie server

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5605]
Issue imported from https://tracker.freecad.org/view.php?id=1842

* **Reporter:** bofhjr
* **Date submitted:** 12/1/2014
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

This would allow for example to directly checkout, checkin IFC Files from the open source BIMServer.

However It seems that there is not (yet ?) a python client for BIMSie  web services

# Additional information

http://www.nibs.org/?page=bsa_bimsie

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by yorikvanhavre** [comment]
The BIMSie API project seems to have been abandoned:
https://github.com/BuildingSMART/BIMSie-API is archived and
openbimstandards.org doesn't exist anymore...
Closing this issue because there is no change to do anymore. Note that the WebTools addon provides a client for BIMserver.
