### ISSUE TITLE
Integrate a BIMSie server into FreeCAD

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5606]
Issue imported from https://tracker.freecad.org/view.php?id=1843

* **Reporter:** bofhjr
* **Date submitted:** 12/1/2014
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** IFC

# Original report text

This would allow an IFC Structure Validator to act as a WIMSie client  of FreeCAD.
It would also allow  any enabled BIMSie  viewer to display IFC views of the currently opened FreeCAD ARCH models.

# Additional information

http://www.nibs.org/?page=bsa_bimsie

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by yorik 2017-02-25 04:18
The given URL seems disabled. Not sure this project is still alive...

---

### Comment by Kunda1 2017-02-26 12:31
yorik i can load the webpage. What is 'disabled' for you about it?
there is an email for the project coordinator:
> The project is being organized into a core technical team and corresponding user members membership who will review and comment on the work of the core team. United States and international data modelers and API developers are also supporting the team to ensure the work accomplished will be consistent with other efforts of the buildingSMART alliance and buildingSMART international. To participate in this project, please contact Leon van Berlo from the Netherlands organisation for applied scientific research TNO: ***leon.vanberlo@tno.nl***

---

### Comment by yorik 2017-02-26 15:22
This page doesn't work anymore (which would contian the specification): http://bimsie.openbimstandards.org/

That's why I think the project is not active anymore...

---

### Comment by Kunda1 2017-02-27 01:46
yorik found https://github.com/openBIMstandards/
Looks like there is sporadic activity but not necessarily on bimsie AFAICT

**Comment by yorikvanhavre** [comment]
Closed together with #5605
