### ISSUE TITLE
Draft workbench preferences snap settings does not use "units" settings

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5610]
Issue imported from https://tracker.freecad.org/view.php?id=1951

* **Reporter:** ctjctj
* **Date submitted:** 2/4/2015
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** assigned
* **Tags:** snap, units

# Original report text

In preferences general select an imperial units.  Go to draft workbench then bring preferences up.  Select draft->snap settings.  Grid spacing is always mm

# Other bug information

* **Priority:** normal
* **Severity:** trivial
* **Category:** Bug
* **OS: Ubuntu 14.1**
* **Platform:** Linux
* **Updated:** 1/24/2022

# Discussion from Mantis ticket

### Comment by Kunda1 2017-01-09 20:01
Still an issue 0.16
Tested on OS: "Manjaro Linux"
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.Unknown
Build type: Release
Python version: 2.7.12
Qt version: 4.8.7
Coin version: 3.1.3
OCC version: 6.9.1

---

### Comment by Kunda1 2017-01-13 00:09
Devs, this ticket needs to move to the 'Draft' category

---

### Comment by Kunda1 2018-01-09 10:34
Forum thread https://forum.freecadweb.org/viewtopic.php?f=8&t=26277

---

### Comment by Kunda1 2018-01-23 19:08
[quote=yorik]All Draft/Arch prefs settings are in millimeters still.... Couldn't find out how to use the InputField widget in qt designer yet[/quote]

---

### Comment by sopwith 2019-01-14 19:49
I ran into this problem just now with 0.18dev-15619 on Windows Conda build. Kind of hard to draft anything in feet and inches... Bump.

---

### Comment by Kunda1 2019-01-29 18:14
yorik will this make it in to 0.18 or bumped to 0.19?

---

### Comment by yorik 2019-02-15 00:05
It seems possible already (the sketcher has one), but haven't looked at how they did it yet.. Let's bump it to 0.19

---

### Comment by Kunda1 2022-01-23 01:31
ctjctj can confirm
After setting imperial units I still see:
Preferences > Draft > 'Text and Dimensions'  
the units for the preferences are in mm

OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27148 (Git)
Build type: Release
Branch: master
Hash: 88ded38ca16e38a556e432a651792c56a65fc80d
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

---

### Comment by Kunda1 2022-01-23 01:34
Preferences > Draft > 'Grid and Snapping' also is showing mm units

**Comment by 0penBrain** [comment]
Has been fixed by #5427
