### ISSUE TITLE
[Feature Request] Draft: Better hatch pattern presentation in the 3D view for planes not parallel to XY

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5615]
Issue imported from https://tracker.freecad.org/view.php?id=1980

* **Reporter:** microelly2
* **Date submitted:** 2/23/2015
* **FreeCAD version:** 0.14

# Original report text

please change the Draft.py

see http://forum.freecadweb.org/viewtopic.php?f=9&t=4264&start=10#p79888

# Steps to reproduce

testcase file  see forum entry

# Other bug information

* **Updated:** 9/8/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2017-05-10 02:57

microelly2 any progress on this?

**Comment by luzpaz** [comment]
Per @WandererFan in the [forum thread](https://forum.freecadweb.org/viewtopic.php?p=153520#p153520):
> PAT hatching only applies to TechDraw drawings, while "Hatch patterns on Draft objects" refers mainly to the 3D view

**Comment by luzpaz** [comment]
@Roy-043 is this still relevant ?

**Comment by yorikvanhavre** [comment]
This is obsolete since Draft now has a new hatching pattern tool that uses the same system as TechDraw
