### ISSUE TITLE
Profile shift for involute gear

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5618]
Issue imported from https://tracker.freecad.org/view.php?id=2022

* **Reporter:** shoogen
* **Date submitted:** 3/22/2015
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Add profile shift to the involute gear feature in the PartDesign Workbench.

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
@jbaehr any interest in tackling this?

**Comment by jbaehr** [comment]
Actually, it's on my todo list already.

atm I'm cleaning the code up a bit, get rid of py2-style `xrange`, deleting the obsolete PyQt4 gui etc. Then, I want to harmonize the code for external and internal profiles again -- the way the internal profile was introduce may years ago unfortunately left a huge copy/paste mess. And then there is only a single item left before the profile shift: don't crash when setting the fillet radius to zero.

**Comment by luzpaz** [comment]
Thanks @jbaehr ! Closing.
Note: next time if you add Fix (or Fixes) `#ticket_number` in the PR (body), upon merge the ticket will be auto-closed.
