### ISSUE TITLE
Fillet to maximum possible value

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5620]
Issue imported from https://tracker.freecad.org/view.php?id=2037

* **Reporter:** larsen
* **Date submitted:** 4/7/2015
* **FreeCAD version:** 0.14
* **Category:** Feature
* **Status:** new
* **Tags:** fillet

# Original report text

As a simple example, take a box where one corner is already filleted. Now, when I want to fillet a neighboring corner, that fillet is limited by the first one. I can enter values and FreeCAD will show the new fillet, but when the entered value is too big, nothing will happen (no preview, no warning message). I could enter "999 mm" and FC simply wouldn´t create the fillet. I then have to reduce the value to find out what maximum I can use.

It would be convenient if FC replaced "999" by the maximum possible value (or used this as the maximum wanted valued in case the maximum possible value would change afterwards).

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by adrianinsaval** [comment]
I'm closing this as out of scope for the reasons above
