### ISSUE TITLE
Use default selection for exports

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5621]
Issue imported from https://tracker.freecad.org/view.php?id=2039

* **Reporter:** larsen
* **Date submitted:** 4/7/2015
* **FreeCAD version:** 0.14
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

When nothing is selected and the user wants to export, FreeCAD shows a warning message. IMHO it would be useful to automatically export the latest entry from the tree.

# Other bug information

* **Priority:** normal
* **Severity:** tweak
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2018-10-05 23:47
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=31377

**Comment by Roy-043** [comment]
Closing this as stale.
