### ISSUE TITLE
[Feature Request] Add Chamfer Edge-Tool

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5623]
Issue imported from https://tracker.freecad.org/view.php?id=2052

* **Reporter:** r-frank
* **Date submitted:** 4/13/2015
* **FreeCAD version:** 0.14
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Like the already existing "Fillet Edge" tool to apply a fillet to two lines, there should be a tool to apply a chamfer as well. Could use the same logic (workflow) as the "Fillet Edge" Tool.
See discussion here:
http://forum.freecadweb.org/viewtopic.php?p=83906#p83906

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Windows 7 64 bit**
* **Platform:** Windows
* **Updated:** 2/6/2021

**Comment by adrianinsaval** [comment]
@PaddleStroke has implemented the tool but it's not merged yet, I think it's mixed in a PR for another feature. Let's see how it goes.

**Comment by maxwxyz** [comment]
@PaddleStroke I couldn't find the PR, just tag this issue if you submit.

**Comment by PaddleStroke** [comment]
I don't have a PR for this yet
