### ISSUE TITLE
Display which parts of a sketch are fully constrained.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5624]
Issue imported from https://tracker.freecad.org/view.php?id=2069

* **Reporter:** spike.barnett
* **Date submitted:** 4/25/2015
* **FreeCAD version:** 0.15
* **Category:** General
* **Status:** assigned
* **Tags:** sketcher, Solver

# Original report text

Displaying which parts of a sketch are fully constrained would make it much easier to fully constrain complex sketches. This could be done by way of color change of the points and lines which are fully constrained in the same way the sketch itself changes color when it is fully constrained.

# Steps to reproduce

Create a sketch with only a line and fully constrain it, then add a second line. The whole of the sketch will change from green to the standard white lines and red dots.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** General
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by abdullah 2018-06-15 16:58
There are two things about this request:
a) the solver is not currently able to show all the parameters that are dependent, but the ones it detects as dependent, so while it can show things that are not constraint, it can not show all the things that are not constraint.
b) second and more important, the previous detection, that could theoretically be improved, depends on using DenseQR decomposition. I have been unable to implement the algorithm using SparseQR decomposition. DenseQR is way lower performing than SparseQR as the number of elements increases, due to the Sparse nature of the Jacobian matrices of the solver. Currently a) is requested on demand (when clicking the hyperlink in the DoFs). But implementing this feature would mean requesting it constantly. This would make the Sketcher much more slower, which I think it is not acceptable.

All in all, implementing this feature requires implementing the DoF finder feature for SparseQR. I have failed to do it so far.

**Comment by adrianinsaval** [comment]
this has been implemented. Issue can be closed.

**Comment by luzpaz** [comment]
Closing
