### ISSUE TITLE
Assembly Merge: remove automatic App::Part functionality

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5625]
Issue imported from https://tracker.freecad.org/view.php?id=2076

* **Reporter:** tanderson69
* **Date submitted:** 5/1/2015
* **FreeCAD version:** 0.16
* **Category:** General
* **Status:** new
* **Tags:** 

# Original report text

http://forum.freecadweb.org/viewtopic.php?f=20&t=10735

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** General
* **OS: Kubuntu 14.1**
* **Platform:** amd64
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by ickby 2015-05-01 13:47
Sorry for the assignment confusion, I did try to add it to the assembly project but did not succeed

---

### Comment by ickby 2015-05-03 11:22
As jriegel started work again I think it would be useful to first make everything work again with the App::Part object. Then we can decide if we merge completely or without the App::Part, dependend of the overall state.

---

### Comment by Kunda1 2017-01-11 20:44
This ticket labeled 'assigned' but it isn't assigned to anybody? wmayer please advise

---

### Comment by wmayer 2017-01-11 21:30
ickby by accident assigned it to him but wanted to move it to the Assembly project. So, I set back the status to "New".

**Comment by adrianinsaval** [comment]
there's no incoming assembly merge on sight, shoud be closed IMO
