### ISSUE TITLE
Assembly Merge: update tree view upon active object change

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5626]
Issue imported from https://tracker.freecad.org/view.php?id=2077

* **Reporter:** tanderson69
* **Date submitted:** 5/1/2015
* **FreeCAD version:** 
* **Category:** General
* **Status:** new
* **Tags:** 

# Original report text

http://forum.freecadweb.org/viewtopic.php?f=20&t=10735

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** General
* **OS: Kubuntu 14.1**
* **Platform:** amd64
* **Updated:** 2/6/2021

**Comment by adrianinsaval** [comment]
there's no incoming assembly merge on sight, shoud be closed IMO
