### ISSUE TITLE
Support to apply equality constraint on angles

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5627]
Issue imported from https://tracker.freecad.org/view.php?id=2078

* **Reporter:** wmayer
* **Date submitted:** 5/1/2015
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** constraints

# Original report text

The related forum post (in German):
http://forum.freecadweb.org/viewtopic.php?f=13&t=10765

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment]
@luzpaz i guess this could be closed in favor of  https://github.com/FreeCAD/FreeCAD/issues/11893

**Comment by maxwxyz** [comment]
@Roy-043 ^ while you are at it :)
