### ISSUE TITLE
Pythonic vs. non-pythonic

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5630]
Issue imported from https://tracker.freecad.org/view.php?id=2173

* **Reporter:** galou_breizh
* **Date submitted:** 6/26/2015
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

I think the Python interface could be improved and be made more pythonic.

An example:
Gui.ActiveDocument.ActiveView.getCamera()
and
Gui.ActiveDocument.ActiveView.setCamera()
could be replaced by a property
Gui.ActiveDocument.ActiveView.Camera.

For example:
c = ActiveDocument.ActiveView.Camera
ActiveDocument.ActiveView.Camera = '#Inventor V2.1 ascii ....'

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment]
Please comment if this is still relevant.

**Comment by maxwxyz** [comment]
I'll close this for no more feedback
