### ISSUE TITLE
Extrude contours (sketch regions).

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5633]
Issue imported from https://tracker.freecad.org/view.php?id=2220

* **Reporter:** bluemirage335
* **Date submitted:** 8/18/2015
* **FreeCAD version:** 0.15
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Modern CAD programs allow specific regions of sketches to be extruded, rather than placing rigorous requirements on the sketch.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Arch Linux current**
* **Platform:** X220_ThinkPad
* **Updated:** 2/6/2021

**Comment by NXTler** [comment]
I can work very well without is, though it would be a nice to have. Maybe useful for top to bottom modeling method?
