### ISSUE TITLE
[Feature Request] Draft: Use Units widgets in preferences pages

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5637]
Issue imported from https://tracker.freecad.org/view.php?id=2349

* **Reporter:** yorik
* **Date submitted:** 12/1/2015
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** units

# Original report text

Currently they all work in mm. The units widget should be used instead for Arch and Draft

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Debian Testing 64bit**
* **Platform:** PC
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
@yorikvanhavre is this still the case ?

**Comment by yorikvanhavre** [comment]
This is done almost everywhere, but I think it still needs a good check to make sure everything works as it should. Relates to #5427

**Comment by donovaly** [comment]
> @donovaly can we raise the priority on this pre-release?

I don't think that we can do much few days before the release.

A list of places there the units are not yet used, would be good.

**Comment by yorikvanhavre** [comment]
I don't think this should be tied to 0.20... It will probably need some fine-tuning and more discussion, as it also needs further implementation (see #5427)

**Comment by sliptonic** [comment]
This issue appears to be ancient.  Is it still relevant?

**Comment by Roy-043** [comment]
Still relevant. I am working on the Draft preferences, including this issue, ATM.

**Comment by Roy-043** [comment]
Note that I'll use Gui::PrefUnitSpinBoxes, not Gui::PrefQuantitySpinBoxes.

I currently do not see any advantage to changing preferences from floats to quantities. For the Draft WB this has been done for gridSpacing. Except for the grid spacing pref in the Sketcher WB, there do not seem to be any other preferences that are stored as quantities.

Using quantities may actually not make sense in relation to preference packs, or if we decide to store the gridSpacing in the document.

**Comment by Roy-043** [comment]
Completed with #11579.
