### ISSUE TITLE
Trackpad navigation on mac does not use full capabilities of the trackpad

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5640]
Issue imported from https://tracker.freecad.org/view.php?id=2437

* **Reporter:** jimhigson
* **Date submitted:** 2/5/2016
* **FreeCAD version:** 0.15
* **Category:** Feature
* **Status:** acknowledged
* **Tags:** Bountysource Potential, gesture, macOS, Qt5, trackpad

# Original report text

OSX conventions are:

* Pinch to zoom in/out (currently this is done via scroll gesture)
* 2-finger scroll gesture to pan (currently done via shift-move)
* Recognise sideways scrolling (ie 2d, not 1d as with mouse wheel)

These changes would make better use of the extended touch capabilities on mac laptops and the Apple magic touchpad.

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Feature
* **OS: OSX El Capitan**
* **Platform:** OSX
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @luzpaz 2017-02-03 00:18
From http://doc.qt.io/qt-5/qnativegestureevent.html

Event Type: Qt::ZoomNativeGesture	
Description: Magnification delta in percent.	
Touch-equence: macOS: Two-finger pinch.
URL: http://doc.qt.io/qt-5/qt.html#NativeGestureType-enum

Event Type: Qt::SmartZoomNativeGesture	
Description:  Boolean magnification state.	
Touch-equence: macOS: Two-finger douple tap (trackpad) / One-finger douple tap (magic mouse).
URL: http://doc.qt.io/qt-5/qt.html#NativeGestureType-enum

Event Type: Qt::RotateNativeGesture	
Description: Rotation delta in degrees.	
Touch-equence: macOS: Two-finger rotate.
URL: http://doc.qt.io/qt-5/qt.html#NativeGestureType-enum

---

### Comment by @luzpaz 2017-05-31 05:06
Trackpad navigation on Linux: https://github.com/JoseExposito/touchegg

---

### Comment by @luzpaz 2019-06-17 06:27
Relevant #5938 and https://forum.freecadweb.org/viewtopic.php?f=9&t=36387

**Comment by luzpaz** [comment]
Closing in favor of #5938
