### ISSUE TITLE
Integrate LibreOffice Calc via GUI

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5646]
Issue imported from https://tracker.freecad.org/view.php?id=2474

* **Reporter:** Spindoctor
* **Date submitted:** 3/14/2016
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** spreadsheet

# Original report text

A convenient way to integrate a spreadsheet from LibreOffice Calc via GUI would be nice to have

# Additional information

The FreeCAD spreadsheets offer some awesome functionalities for FreeCAD while still being slim and fast. However, for some applications it is necessary to do more difficult calculations.

Most of them would be more or less doable in FreeCAD spreadsheets but sometimes it can be more convenient to use a "full grown" spreadsheet program like LibreOffice Calc. For those cases an integration of LibreOffice Calc would be good.

If this is going to be implemented one difficulty might be to handle cell aliases. LibreOffice however has that feature, see https://help.libreoffice.org/Calc/Naming_Cells

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 11/24/2021

# Discussion from Mantis ticket

### Comment by silopolis 2017-08-08 09:02
Without a doubt, power of a full featured spreadsheet program should certainly be useful in a number of projects !
AFAIC, linking models to external spreadsheets presents another VERY important and powerful advantage that is being able to centralize and share parameters between models. This would allow me to put all common parameters in a LO Calc "project sheet", and link/dynamicaly import it in all parts and assembly files.
This way:
   * modifying a parameter in the central sheet would "spread" into the whole project
   * misses and errors in duplicating values and cells aliases in all spreadsheets in all project files would be avoided.
Looking for a solution for this, I found this page https://freecad-tutorial.blogspot.fr/2011/10/oosheet-as-freecad-and-libreoffice.html which may present the beginning of a solution with 2 way (!) communication between a OO sheet and a FreeCAD model.

---

### Comment by Kunda1 2017-08-08 17:12
silopolis please open a forum thread to generate more community discussion on this topic. Thanks for the link. Very interesting.

---

### Comment by silopolis 2017-08-12 19:14
Discussion opened [here](https://forum.freecadweb.org/viewtopic.php?f=8&t=23863)

---

### Comment by Kunda1 2020-03-14 21:59
Integration attempt happening in https://github.com/myoldz/FC_LibreOffice.git

---

### Comment by Kunda1 2020-11-03 15:08
Moved to https://github.com/myoldz/FC_Libre

---

### Comment by Kunda1 2020-11-03 15:12
[s]Another[/s] project thread by salp (AKA myoldz on github) at https://forum.freecadweb.org/viewtopic.php?f=8&t=44005

**Comment by luzpaz** [comment]
Closing feature as it seems superfluous and hasn't gained much traction over the years.
