### ISSUE TITLE
[FEM] [Feature] Spreadsheet/Expressions data be accessible to FEM workbench

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5655]
Issue imported from https://tracker.freecad.org/view.php?id=2547

* **Reporter:** HoWil
* **Date submitted:** 5/12/2016
* **FreeCAD version:** 0.16
* **Category:** Feature
* **Status:** confirmed
* **Tags:** #lowhangingfruit, expressions, FEM, GUI, spreadsheet

# Original report text

All values dialogs in the FEM WB do not use input from spreadsheet-Data. The part-design WB does accept them and it would be great if FEM would do also. For instance it would help if in the FEM-mesh dialog one could specify a max. size value derived form a spreadsheet value used in part design.  

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=18&t=68668
# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by user2853 2016-05-13 13:38
It's there in 0.17

---

### Comment by Kunda1 2017-02-21 16:08
> It's there in 0.17 
sgrogan what do you mean ?

---

### Comment by user2853 2017-02-22 00:05
I meant the feature exists in 0.17. But re-reading more carefully it exists in the property editor not the creation dialog. So the feature request stands. The work around is to create the feature and then edit the numerical property from the data tab. I think it should be possible to do directly from python but I didn't test.

---

### Comment by HoWil 2017-06-23 20:28
Is there a reason why my screenshot was deleted?

---

### Comment by Kunda1 2017-06-24 01:14
HoWil yes, because it wasn't good enough... j/k 
Real reason: recently when we restored the tracker from backup many attachments didn't make it.

---

### Comment by berndhahnebach 2018-09-18 15:51
It would be nice to have. But in my ToDo this is for sure some piece away from the beginning.

**Comment by luzpaz** [comment]
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=18&t=68668

**Comment by maxwxyz** [comment]
@FEA-eng is this still an issue? If FEM is so different, this should also be considered for https://github.com/FreeCAD/FreeCAD/issues/12120

**Comment by FEA-eng** [comment]
> @FEA-eng is this still an issue? If FEM is so different, this should also be considered for #12120

It depends on the feature. Some have it in widgets while some only have it in the property editor (as user2853 explained in the discussion above). So it's inconsistent.
