### ISSUE TITLE
Container for points, lines, planes and surfaces

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5662]
Issue imported from https://tracker.freecad.org/view.php?id=2686

* **Reporter:** Pauvres_honteux
* **Date submitted:** 8/31/2016
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** containers, lines, Part Design, planes, points, surfaces

# Original report text

 I'd like to propose a new container (name: Geometry?) were we store anything related to; points, lines, planes and surfaces. But not anything solid related.

This container would allow linking to/from anything within it. There will NOT be a result of the container itself. The container shall NOT have any hierark dependency to any other "geometry" containers. It will have more resemblence with a folder in an archive. Moreover it shall NOT be possible to link to the container itself.

These containers must be freely reorganized within the visible tree and with respect to each other, visability vise.

# Additional information

This picture might help a bit:
https://catiatutor.com/images/stories/bestpractises1/image001.jpg

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Pauvres_honteux 2016-08-31 04:47
Forum discussion:
http://forum.freecadweb.org/viewtopic.php?f=8&t=17214

---

### Comment by Kunda1 2018-01-21 13:28
Ticket referenced also in https://forum.freecadweb.org/viewtopic.php?f=8&t=17630&start=10#p210712

---

### Comment by Pauvres_honteux 2018-07-18 09:12
I'm adding this discussion [Datum entity vs Body](https://forum.freecadweb.org/viewtopic.php?f=3&t=28839)

**Comment by adrianinsaval** [comment]
Groups exist for a long time, nothing actionable here
