### ISSUE TITLE
Part Offset2D fill offset problems

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5664]
Issue imported from https://tracker.freecad.org/view.php?id=2700

* **Reporter:** @DeepSOIC
* **Date submitted:** 9/16/2016
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

Filling offset does not work, when a 2D offset is applied to another 2D offset.

# Additional information

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.8361 (Git)
Build type: Release
Branch: DeepSOIC10
Hash: 4ac7673e543274bcae856872033a114c7b60481b
Python version: 2.7.8
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.0.0

Seems to be related to extrusion direction weirdness. Offsetting a Draft Clone of offset works as expected.

forum thread:
"Bug in Part Offset 2D filling"
http://forum.freecadweb.org/viewtopic.php?f=3&t=17445

# Steps to reproduce

1. Sketch. Circle.
2. Part 2D Offset the circle. Leave values at defaults.
3. 2D Offset the offset. Tick Fill checkbox. The offset is filled incorrectly (face covers the hole, instead of the offset space).

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by wmayer 2018-01-02 13:42
Postpone to 0.18 is it's not realistic to get this fixed soon.

**Comment by Roy-043** [comment]
Works as expected now.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33492 (Git)
Build type: Release
Branch: master
Hash: 6e235a4809e14674aa2cd23e68630b68998a53d4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```
