### ISSUE TITLE
IGES and STEP export compatibility

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5668]
Issue imported from https://tracker.freecad.org/view.php?id=2732

* **Reporter:** vern.zimm
* **Date submitted:** 10/10/2016
* **FreeCAD version:** 0.16
* **Category:** General
* **Status:** new
* **Tags:** #ready-for-migration, file format, IGES, OCC Bug, STEP, units

# Original report text

Greetings,

Disclaimer : I do understand that the Import/Export is part of OCC and you do not have control over that, and also understand that you have no control over the CMM software, but I would appreciate any help you can give me. It does appear that there are some settings for OCC that are variable on your end.

I am using CMM software called PC-DMIS, and it has some very strange results from attempts to import both .step and .iges from FreeCAD. It is a bit finicky with .iges, but .step has always been the better format and I can't think of the last time I had an issue with it.

.step files fail to import completely. Luckily there is a translate log and it shows errors "building bounds of Face". That and the exported .step are attached.

.iges files have mixed results depending on "144" or "186" type.

The "144" type will import all curves, but only some faces.
The "186" type will import all faces, and some huge lines that are clearly related to the missing curves.
(File and screenshots of results attached for both)

I am able to merge the two, then delete huge lines and duplicate faces, so it does work to do that. The settings for the .iges importer are attached as well. Perhaps you can make some sense of them, but no combination seems to give better results.

# Additional information

OS: Windows 7
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.6706 (Git)
Build type: Release
Branch: releases/FreeCAD-0-16
Hash: f86a4e411ff7848dea98d7242f43b7774bee8fa0
Python version: 2.7.8
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17

# Steps to reproduce

Create part (including curves of some sort for the IGES issue)
Export using either File menu, or Part Workbench export

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** General
* **OS: Windows 7 SP1**
* **Platform:** Intel Core i5 64-bit
* **Updated:** 1/24/2022

# Discussion from Mantis ticket

### Comment by normandc 2016-10-12 11:29
Creating a post on the forum first would have been more appropriate. This looks like a help request, not like a bug report. As it is, this bug report is much too vague.

Please read the "Please read before reporting" link. http://forum.freecadweb.org/viewtopic.php?f=3&t=5236

---

### Comment by vern.zimm 2016-10-14 17:21
There would appear to be a bug in either FreeCAD or OCC with the Inch export vs. MM export. In the preferences for Import/Export, one can set the export units. I set this to MM and suddenly my .step files come in perfectly. The "186" .iges files still have the lines, but do pull in complete otherwise. I suspect there may be a conversion error somewhere, for instance, in the MM .iges I find this "-0.E+000", but in the Inch .iges, I find "-1.928577636E-017". I don't know if that's the issue, but it is one difference I found. See the "502" line from each file in the attached MM to Inch Compare.txt (with the inch equivalent converted for the other numbers).

---

### Comment by Kunda1 2017-01-16 08:58
Forum thread to continue discussion: http://forum.freecadweb.org/viewtopic.php?f=10&t=19941

---

### Comment by Kunda1 2017-05-06 11:07
Forum thread updated

**Comment by adrianinsaval** [comment]
is this still relevant?

**Comment by grubertechnic** [comment]
@adrianinsaval : we neither have a (FreeCAD)file, nor the software the OP use to compare. Also in the forum thread is written, that his software is picky. I would close it, just also because it is non-testable.
