### ISSUE TITLE
PART_WB: Add "Measure Radial" to Std Measure Menu

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5670]
Issue imported from https://tracker.freecad.org/view.php?id=2748

* **Reporter:** nokian
* **Date submitted:** 10/25/2016
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** feedback
* **Tags:** Part, UI

# Original report text

Discussed here:
http://forum.freecadweb.org/viewtopic.php?f=8&t=18102

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by nokian 2017-07-26 21:18
Devs: What do you think about increasing the priority of this issue?

---

### Comment by Kunda1 2017-07-27 01:05
nokian better to ask in the forum thread than here.

---

### Comment by Kunda1 2017-10-11 03:50
A workaround could be to use triplus new Command Panel Workbench: https://forum.freecadweb.org/viewtopic.php?f=34&t=23207

---

### Comment by Kunda1 2018-11-07 00:48
wmayer verdict on this ticket ?

**Comment by FEA-eng** [comment]
@maxwxyz I guess that it can be closed since the new measurement tool includes a radius for edges.
