### ISSUE TITLE
Expression link is cuting by creating new object

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5672]
Issue imported from https://tracker.freecad.org/view.php?id=2766

* **Reporter:** FFW
* **Date submitted:** 11/11/2016
* **FreeCAD version:** 0.16
* **Category:** Bug
* **Status:** assigned
* **Tags:** expressions

# Original report text

When using an expression linked to a certain object, creating another object with a close name cause the link to switch to this last created.

# Steps to reproduce

- Create a Part Design/Cube, named Cube by default
- Create another object
- Link a property of this object to Cube.Length
- Create another Part Design/Cube, named Cube001 by default
- Show the property of the object, it is now linked to Cube001.Length and break the model.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Linux Debian 4.8.0-1-amd64**
* **Platform:** x86-64
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @wwmayer 2016-11-11 12:23
Hint: this only happens with using the Label value of an object (Cube). When using its internal name (in this case "Box") it works correctly.

The same problem still exists in 0.17.

---

### Comment by eivindkvedalen 2016-11-13 21:55
This happens because the GUI tries to assign e.g 'Cube' to the second object when it is created. This in turn triggers a relabelObject signal, and the expression engine happily renames the expression when the GUI changes the label because duplicate labels are not allowed (before this happens there are two object with the label 'Cube'; this is why it can be renamed to Cube001; not sure why this is so predictable, though).

Not sure how to fix this, because I also found another thing that probably should be looked into first: The "Allow duplicate label" handling is done in the Gui part of FreeCAD. Shouldn't this really be in the App part?

---

### Comment by @wwmayer 2016-11-14 17:53
> Shouldn't this really be in the App part? 

True, since ObjectLabelObserver anyway only accesses App stuff this class could be moved to FreeCADApp.

---

### Comment by wmayer 2017-10-11 12:52
See also:
https://forum.freecadweb.org/viewtopic.php?f=10&t=24839&p=195041
https://forum.freecadweb.org/viewtopic.php?f=10&t=24595&p=194633#p194633

**Comment by Jolbas** [comment]
This seems to work as expected now. I can't reproduce using provided steps.

```
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
```
and
```
OS: macOS 12.6
Word size of FreeCAD: 64-bit
Version: 0.21.0.32630 (Git)
Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
```
I don't know why about dialog on 20.2 reports macOS 10.16 when it's actually macOS 12.6.3

**Comment by luzpaz** [comment]
> I don't know why about dialog on 20.2 reports macOS 10.16 when it's actually macOS 12.6.3

Weird! Maybe open a ticket for this ?

**Comment by JohnOCFII** [comment]
> I don't know why about dialog on 20.2 reports macOS 10.16 when it's actually macOS 12.6.3

I saw this behavior too, when I downloaded the weekly macOS Intel version (running with Rosetta 2 on my MacBook Pro with M1 arm processor:

 ```
    - OS: macOS 10.16
    - Word size of FreeCAD: 64-bit
    - Version: 0.21.0.32532 (Git)
    - Build type: Release
    - Branch: master
    - Hash: 20e44eba50e1365b9e7bb9c5c244afe96a627a28
    - Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
    - Locale: C/Default (C)
``` 

But a locally built arm version showed the correct OS version:

```
- OS: macOS 13.2
    - Word size of FreeCAD: 64-bit
    - Version: 0.21.0.32587 (Git)
    - Build type: Release
    - Branch: conda-devenv
    - Hash: 228ea5e11f6bef063a8469981f4f8244f12c3600
    - Python 3.11.0, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.6.3
    - Locale: English/United States (en_US)
 ```

The python version went from 3.10.10 to 3.11.0 and the FreeCAD commits were about 55 ahead of the Mac Intel version.

**Comment by Roy-043** [comment]
I confirm that this issue has indeed been resolved. I see no reason to keep this open. But feel free to reopen if you disagree.
