### ISSUE TITLE
Allow cherrypicking individual lines from a sketch when creating a wall

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5675]
Issue imported from https://tracker.freecad.org/view.php?id=2795

* **Reporter:** TomV
* **Date submitted:** 11/26/2016
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

My current (noob) workflow is as follows:
1. create a single monster sketch with the floorplan of my house
2. then draw draft rectangle over the sketch lines to specify walls
3. then convert those draft rectangles into a wall

It's not possible to select lines from the sketch directly, which makes step number 2 necessary. If you select a single line from the sketch and then press 'wall', all lines of the sketch are converted into a wall.

My RFE is to make it possible to specify select lines from a sketch.

# Steps to reproduce

N/A

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Ubuntu 16**
* **Platform:** Linux
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by yorik 2016-11-29 14:14
That could be a good thing indeed. Will try to think a bit about how to do it (users must be able to pick the whole object as well)

**Comment by Roy-043** [comment]
It is possible to create a [PartDesign_SubShapeBinder](https://wiki.freecadweb.org/PartDesign_SubShapeBinder) from selected edges of a sketch. The resulting object can then be used as the base for a wall.

IMO this is a valid solution for the requested functionality. I am therefore closing this FR.
