### ISSUE TITLE
Path: Dogbone dressup needs visualisation and preferences

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5677]
Issue imported from https://tracker.freecad.org/view.php?id=2839

* **Reporter:** mlampert
* **Date submitted:** 1/11/2017
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** acknowledged
* **Tags:** dogbone

# Original report text

Dogbone should have a way of visualising the currently selected bone, similar to how HoldingTags displays the currently selected tags (and synchronises the visualisation with the list selection).

Similarly the default settings for the dressup should be held in the preferences

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: all all**
* **Platform:** all
* **Updated:** 9/6/2021

# Discussion from Mantis ticket

### Comment by flopsy 2018-02-05 23:45
i'm on it to do some artwork/pictures/visualization. For Dogbone is on my todo-list, too...(just pictures not "hard-code"-visualization like "tag-dressup", but maybe it will help, too...)

---

### Comment by mlampert 2021-03-18 03:08
https://github.com/FreeCAD/FreeCAD/pull/4634

Can't think of any preferences to add

---

### Comment by Kunda1 2021-09-06 10:20
515c7de

edit: manually associated commit to this ticket

**Comment by mlampert** [comment]
I think this bug can be closed, the visualisation was added and I still can't think of any preferences. Not sure why we didn't close it back when.
