### ISSUE TITLE
Add knife align up function to locate knife at beginning cut precisely

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5682]
Issue imported from https://tracker.freecad.org/view.php?id=2916

* **Reporter:** EdgarRobles
* **Date submitted:** 2/22/2017
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** confirmed
* **Tags:** dragknife

# Original report text

You can see similar function in dxf2gcode application
it align up the knife before begin to cut and between cut inputs.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **OS: Ubuntu 16.04 LTS**
* **Platform:** Linux
* **Updated:** 8/25/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2017-02-22 12:37
EdgarRobles Thanks for the report. Just a tip to help bug triage and expediting your request: please always try to: 

* open a forum thread before opening a ticket to generate discussion
* if the indication from the community is to open a ticket then do so
* link said ticket <=> thread 
* to paste the contents of *****Help > About FreeCAD > Copy to clipboard***** in to the ticket/thread

---

### Comment by EdgarRobles 2017-02-22 14:20
Here is what i post but it is not in english
https://forum.freecadweb.org/viewtopic.php?f=14&t=20620
ty didn't know about triage.

---

### Comment by Kunda1 2017-02-22 16:48
EdgarRobles you can also ask in https://gitter.im/FreeCAD/Path
Bug triage is when someone goes through bugs organizing them for clarity and helps get them to the correct people. ;)

---

### Comment by sliptonic 2017-02-23 22:56
Can you describe better what kind of behavior you're looking for in the 'align' function?  
Should the program pause to let the user manually align the knife or should it add some kind of lead-in move to give the knife time to pivot.

If it's a lead-in move, how do I determine a safe position to start from?

---

### Comment by EdgarRobles 2017-02-24 19:58
Sure, If you try to make a dress-up knife path as fast as you start to cut it, you will see knife is not aligned at one specific direction; I think one simple solution could be say the final user align it by hand before start cutting always at the same direction.
Other case might have to change it's between cuts for example if you have two squares 
at moment you wanted to cut the second square, it will be necessary to get down the knife and re-align (make a semi-circle to point the knife towards the first trajectory)

I saw a little issue on the path you can see it from here: https://forum.freecadweb.org/viewtopic.php?f=14&t=20620 
 in the "dragknife.png" image.
I saw on second edge that not do knife dress-up operation; I did a second test and always it misses the second edge.

---

### Comment by EdgarRobles 2017-02-24 20:02
This attach g code is from dxf2gcode dressup knife function, i think a example file is better than my words. xDD

---

### Comment by mlampert 2017-02-28 19:29
Would one way to solve this would be to "drag the knife into the starting position" - if that makes any sense. Probably easiest to let the user specify a starting position from where to start dragging.

The same is true for every independent Path. Whenever there is a rapid-move (aka the knife gets lifted off completely), there needs to be a "lead in" segment to orient the knife.

---

### Comment by Kunda1 2017-03-23 23:55
changing to feedback to keep track of ticket. 

---

### Comment by Kunda1 2017-04-28 16:21
sliptonic do you mind weighing in on the discussion at your earliest convenience?

---

### Comment by sliptonic 2017-05-10 13:41
I don't have a good solution at this time.  I think the most expedient solution is for the dressup to add a pause event to give time for the user to align the knife.

Basically, after every G0 rapid, check if we are descending to the cut depth.  If so, descend to just above the material, insert a M0 command, descend to cut depth, and continue.  I don't know if an M0 will work on controllers other than LinuxCNC

This logic could be implemented as another entry dressup and applied optionally to dragknife dressed operations.

---

### Comment by Kunda1 2017-05-11 21:27
sliptonic should I change this to a ticket as a feature request?

---

### Comment by sliptonic 2017-05-25 15:51
The simple solution of pausing and waiting for the operator to align the knife won't work for many machine controllers that don't allow interaction. For example, Smoothie doesn't even have a pause command. I don't know of a way to safely determine an entry position where a big entry arc could be cut to guarantee starting angle.
I think it should be left as a feature request. Maybe someone will come along with a bright idea.

---

### Comment by Kunda1 2017-05-26 13:15
Changed ticket to Feature Request.

---

### Comment by Kunda1 2020-01-06 16:36
Opened a thread in the Path subforum for discussion: https://forum.freecadweb.org/viewtopic.php?f=15&t=42233

---

### Comment by Kunda1 2021-08-25 15:39
Summary by sliptonic: 
[quote=sliptonic]There's consensus that something is needed but no ideas about how to achieve it. For a simple single-wire profile, it's pretty easy. Let the user pick a point to start at. That doesn't work in all cases because a profile might have many wires where the tool is lifted between. What's needed is an algorithm that will consistently pick a safe starting point regardless of the profile.[/quote]

**Comment by sliptonic** [comment]
Issue is aspirational but no clear idea of how to do it.  Closing the issue for lack of engagement
