### ISSUE TITLE
FEM, post processing, results, reaction forces

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5684]
Issue imported from https://tracker.freecad.org/view.php?id=2934

* **Reporter:** berndhahnebach
* **Date submitted:** 3/1/2017
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** confirmed
* **Tags:** 

# Original report text

reaction forces:
- add them to the result object 
- add the possibility to create them by the solver (solver input file)
- read them and store them in the result object
- post process them

forum topic:
http://forum.freecadweb.org/viewtopic.php?f=18&t=20664

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by berndhahnebach 2017-03-19 21:21
related post but in German:
https://forum.freecadweb.org/viewtopic.php?p=166225#p166225

---

### Comment by berndhahnebach 2017-03-29 11:45
interesting post in this regard:
http://forum.freecadweb.org/viewtopic.php?p=167047#p167047

---

### Comment by berndhahnebach 2018-09-18 06:21
related #3126

---

### Comment by berndhahnebach 2019-06-06 07:14
another forum topic: https://forum.freecadweb.org/viewtopic.php?f=18&p=312643#p312643

**Comment by FEA-eng** [comment]
@maxwxyz This is already implemented so the issue can be closed.
