### ISSUE TITLE
[Feature] [FEM] GUI constraint force should display units

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5690]
Issue imported from https://tracker.freecad.org/view.php?id=2981

* **Reporter:** @kkremitzki
* **Date submitted:** 3/23/2017
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** feedback
* **Tags:** #lowhangingfruit, #tobeclosed, units

# Original report text

Object FemConstraintForce needs to display appropriate units when applied as a point load, line load, or area load.

Ideally, if line load or area load is selected, the appropriate length or area should display.

An optional checkbox to input normalized force would be good too. So a user input of F newtons automatically gets converted to create the correct ConstraintForce which is a line load F/l on a line of length l, or an area load F/A when a face with area A is selected. 

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 1/20/2022

# Discussion from Mantis ticket

### Comment by berndhahnebach 2017-03-29 11:51
Good point. Fully agree.

---

### Comment by Kunda1 2017-05-02 21:16
Confirming based on bernd's response

---

### Comment by Kunda1 2022-01-19 17:41
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=18&t=65474

---

### Comment by Kunda1 2022-01-20 12:00
kkremitzki see thschrader response in https://forum.freecadweb.org/viewtopic.php?p=563409#p563409

**Comment by FEA-eng** [comment]
@maxwxyz IMO this can be closed as not planned or already available because the units are displayed now, it's always total force in N and there's no need to change it: https://forum.freecad.org/viewtopic.php?f=18&t=65474#p563409
