### ISSUE TITLE
[Feature Request] TechDraw: "Broken view" - ability to depict very large objects on a page by cutting a segment from the middle and juxtaposing them

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5694]
Issue imported from https://tracker.freecad.org/view.php?id=3011

* **Reporter:** @luzpaz  
* **Date submitted:** 5/1/2017 
* **FreeCAD version:** 0.17

# Original report text

"Broken view" - the ability to depict very large objects on the page.

![image](https://github.com/FreeCAD/FreeCAD/assets/4140247/c7ecfeb8-9fae-4609-8381-72af3c60043d)
![image](https://github.com/FreeCAD/FreeCAD/assets/4140247/689389cd-0812-44fa-aba4-04af0cebaaf6)

# Other bug information

Part of the [TechDraw Roadmap](https://www.freecad.org/wiki/TechDraw_Roadmap)
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=35&t=48655

**Comment by PLChris** [comment]
Link to different flavors, which may be handy: https://forum.freecadweb.org/viewtopic.php?p=587659#p587659

**Comment by luzpaz** [comment]
Related to #6309

**Comment by luzpaz** [comment]
Yes, more nuanced tickets should be opened to improve the functionality added in #13331
