### ISSUE TITLE
[Feature Request] TechDraw - 2D Geometry

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5695]
Issue imported from https://tracker.freecad.org/view.php?id=3014

* **Reporter:** Kunda1
* **Date submitted:** 5/1/2017
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

A number of 2D geometry functions were recently added to the Part module. This needs to be reviewed with an eye towards replacing custom 2D geometry code in TechDraw with standard code from Part.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by pierreporte** [comment]
@maxwxyz Is this still relevant?
