### ISSUE TITLE
[Feature] [FEM] constraint pressure - make it work on face meshes too

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5699]
Issue imported from https://tracker.freecad.org/view.php?id=3050

* **Reporter:** @berndhahnebach
* **Date submitted:** 5/27/2017
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** confirmed
* **Tags:** constraints, FEM

# Original report text

The pressure constraint (***FemConstraintPressure***) should work on face meshes too. CalculiX supports this. 

But we'll face a problem here:
How do we get the information if a FEM mesh face is in the same direction like the geometrical face normal (the normal of the reference shape)? 

For more information see forum thread: https://forum.freecadweb.org/viewtopic.php?f=18&t=21872

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/20/2021

# Discussion from Mantis ticket

### Comment by @berndhahnebach 2017-05-28 10:49
A first implementation has been merged into master. But it is a start only. The FEMMesh faces should not have flipped normals and group data is needed too. See the forum thread linked in description for more informations.

https://github.com/FreeCAD/FreeCAD/commit/7ed786cf863f5b11de55c6d4c7c8ce3e753bd5ce

---

### Comment by @berndhahnebach 2018-09-18 06:37
[MantisBT issue 3313](https://tracker.freecad.org/view.php?id=)  has further information.

---

### Comment by @berndhahnebach 2020-06-12 05:29
related: https://forum.freecadweb.org/viewtopic.php?f=18&t=47497

---

### Comment by @berndhahnebach 2020-06-12 05:32
https://github.com/FreeCAD/FreeCAD/blob/6271887cc656d8571000de2f4e06df2be8d84105/src/Mod/Fem/femmesh/meshtools.py#L1586

**Comment by luzpaz** [comment]
Once this FR gets address, please update https://wiki.freecad.org/FEM_ConstraintPressure
