### ISSUE TITLE
Persistent Clipping Plane

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5706]
Issue imported from https://tracker.freecad.org/view.php?id=3069

* **Reporter:** attesz86
* **Date submitted:** 6/4/2017
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** clipping plane

# Original report text

Feature request for a Clipping Plane feature that does not need to be closed when executing other operations.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by adrianinsaval** [comment]
poorly described request without forum discussion, this is either covered by #4118, was not an issue to begin with or was implemented somewhere along the way since it is perfectly possible to perform other operations while clipping plane is active in current master.

Issue should be closed.
