### ISSUE TITLE
MacOS application crashes should generate Diagnostic Reports

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5711]
Issue imported from https://tracker.freecad.org/view.php?id=3081

* **Reporter:** berka
* **Date submitted:** 6/13/2017
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** confirmed
* **Tags:** #post-to-forum, crash, distribution specific, macOS, packaging

# Original report text

I'm testing 0.17 nightlies (primarily to use Path Workbench).
I found 0.17 crashes often enough to be annoying.  However, unlike other MacOS apps I'm accustomed to, this application doesn't pop up with a backtrace and other diagnostic report information.  I've spent a long time fishing through log files with no result.
This is de ja vu for me (bug #2521).  I will now start systematically running under lldb.

However, I think it would be helpful if an unexpected crash generated some diagnostic information.  Please identify and implement what you need to do to enable such diagnostic gathering.

I looked, but couldn't find how to enable the MacOS facility that generates these reports.  Some things that show up in web search:
ReportCrash utility (e.g. "man ReportCrash")
CrashReporter https://developer.apple.com/library/content/technotes/tn2004/tn2123.html  <- This describes what I'm accustomed to seeing as an app user.

I find the crash reports I expect from other applications at: ~/Libary/Logs/DiagnosticReports

# Additional information

OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.11232 (Git)
Build type: Release
Branch: (detached from 5f54fc0)
Hash: 5f54fc0298cea749c53fa3c1a6be71f1f1e1476f
Python version: 2.7.13
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.1.0

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: MacOS 10.12.5**
* **Platform:** Intel
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by berka 2017-06-13 10:42
This may be related to why crash reports aren't displayed/logged for FreeCAD.  I had found this in my syslog:
`com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000016.FreeCAD[4320]): Service exited with abnormal code: 1`
Thinking back, it hints that FreeCaD may be running as a background app.  Crash reports (by default) are not generated for background apps.

---

### Comment by Kunda1 2017-06-13 21:44
blacey care to comment?

---

### Comment by Kunda1 2017-06-13 21:47
In the same vein as #2731

---

### Comment by Kunda1 2017-06-29 13:12
peterl94 mind taking a look?

---

### Comment by peterl94 2017-07-01 22:21
It seems to depend on how the app crashed. The following two examples both crash freecad ( builds from github), but only the first shows the mentioned diagnostic report.

```part1 = App.ActiveDocument.addObject("App::Part", "Part1")
part1.Group = [part1]
```

```import Part
circle = Part.makeCircle(10)
result = Part.makeFilledFace([circle])
```

**Comment by JohnOCFII** [comment]
Pretty sure this can be closed.  Diagnostic reports are certainly now displayed as of 0.21.
