### ISSUE TITLE
Graceful handling of self-intersections when creating part from imported mesh

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5725]
Issue imported from https://tracker.freecad.org/view.php?id=3183

* **Reporter:** KarenRei
* **Date submitted:** 9/12/2017
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** new
* **Tags:** constraints

# Original report text

Currently, self-intersections are anethema to FreeCAD. Unfortunately, meshes from external sources frequently have self-intersection. For example, if one makes a 2d surface in blender, then applies a "solidify" modifier to add thickness, the modifier will often have minor self intersection around sharp corners.

It's common for many other programs I've used to deal gracefully with self-intersection because it's such a common issue. For example, if I upload a model with self intersection for 3d printing with iMaterialize, they convert it into a solid without complaints; the only constraints are the obvious - no non-manifold edges (aka, it must be "watertight").

Even if you don't personally see value on this feature (or trust me that it would be well appreciated), adding it would at the very least save you the time of people seeking help about them on the forum   ;)

# Additional information

OS: "Fedora release 24 (Twenty Four)"
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.11828 (Git)
Build type: Unknown
Branch: master
Hash: 71130d09ed57c03c03bbbc0ef49e94a590f6ddd4
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 3.1.3
OCC version: 6.8.0.oce-0.17
Locale: Icelandic/Iceland (is_IS)

# Steps to reproduce

Load any model with self-intersection. I'll make one for you if you'd rather  :)

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @luzpaz 2017-09-13 12:13
Quick question, why is your version of FC 0.17 using an inferior version of OCC? Should be at least 7.1 
Also please upload an example file to expedite things for testers. 
Have you discussed this on the forum at all?

---

### Comment by KarenRei 2017-09-13 19:18
I don't even know what OCC is. My install process was simply "dnf install freecad" on a stock Fedora 24 system.

Yes, this has been discussed quite a few times on the forum, as it's a common complication when importing meshes.

Attaching a sample model with self intersection.  :)
[tmp.dae.zip](https://github.com/FreeCAD/FreeCAD/files/8847564/tmp.dae.zip)

---

### Comment by @wwmayer 2017-09-13 20:21
What is a "minor self intersection"? is there also a "major self intersection"? And the model you uploaded is this a "minor" or a "major" self-intersection?

---

### Comment by KarenRei 2017-09-13 20:40
It doesn't really matter; that was just an example of self intersection.  "Minor" self intersection would be self intersection that is "adjective: lesser, as in size, extent, or importance, or being or noting the lesser of two"

Any algorithm for self intersection should work for all self intersection, regardless of how much there is, should it not?

**Comment by luzpaz** [comment]
@wwmayer when you get a moment, can you follow-up? Thanks!

**Comment by maxwxyz** [comment]
any news on this?

**Comment by maxwxyz** [comment]
I'll close this for no further feedback since 2017.
