### ISSUE TITLE
Make Transformation tool available for GeoFeatureGroups

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5727]
Issue imported from https://tracker.freecad.org/view.php?id=3195

* **Reporter:** ickby
* **Date submitted:** 9/21/2017
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

The default 3D view GeoFeature Transformation tool will be very handy for GeoFeatureGroups and should be available by default from the mouse menu.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by normandc 2018-02-25 07:50
ickby wrote on the forum that he won't be available for FreeCAD development for the foreseeable feature. https://forum.freecadweb.org/viewtopic.php?f=8&t=26958&p=215930#p215930

Unless someone else is willing to tackle this very soon, maybe we should bump it to 0.18.

---

### Comment by normandc 2019-02-24 15:40
wmayer
I'm not certain what a GeoFeatureGroup is, if it's a Part or Body container, hasn't this been implemented already? Both provide a Transform item in the contextual menu, even in v0.17.

---

### Comment by wmayer 2019-02-24 17:17
Recently I had a look at this ticket too and the forum thread but for me it's not clear either what exactly is meant with GeoFeatureGroup. A class of this name doesn't exist and furthermore the transformation tool should be implemented for a view provider, not its feature class.

The closest thing I found is the class ViewProviderGeoFeatureGroupExtension and this ticket could be about to implement the transformation tool there so that it's available for all classes that use or inherit from this extension class. But this is just guessing.

**Comment by ickby** [comment]
I do not remember exactly what I meant back then... most likely the Transformation-Gizmo (moving, rotating)  couldn't be accessed for GeoFeatureGroups (all objects with this extension). I don' think this is very relevant, as I think the App::Part can now be moved with the gizmo from wthin the 3D view now. So IMHO can b closed.
