### ISSUE TITLE
Displaying name instead of value in Sketcher constraint

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5729]
Issue imported from https://tracker.freecad.org/view.php?id=3198

* **Reporter:** jrt
* **Date submitted:** 9/27/2017
* **FreeCAD version:** 0.16
* **Category:** Feature
* **Status:** new
* **Tags:** constraints

# Original report text

See discussion thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=24611

The idea is to be able to choose to display name, or other symbol, instead of the value of a constraint in either sketcher, 3D view etc.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 3/27/2021

**Comment by adrianinsaval** [comment]
with #4966 this is now possible after checking an option in sketcher preferences, default format string shows name = value, here I made it show just the name and if the constrain is not named just the value is shown
![image](https://user-images.githubusercontent.com/36372335/153617606-ff3b8bfd-7a03-4c5e-8150-d3fc5f9a34ba.png)
this issue can be closed
