### ISSUE TITLE
More convenient arc-drawing in polyline mode

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5730]
Issue imported from https://tracker.freecad.org/view.php?id=3203

* **Reporter:** SparkyCola
* **Date submitted:** 10/1/2017
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** arc, input, keyboard, mouse-gestures, Poly-line

# Original report text

1. Usage of mouse-gestures (similar to those in Solid Works, Solid Edge, AutoCAD and more) and 
2. Multiple key bindings (***a*** for arc and ***l*** for line which seems to be a CAD convention). 

The mouse-gestures would also allow to determine the perpendicularity/tangency of the arc to the last, and the next line/arc-segment. 

The feature has been discussed in the [forum](https://forum.freecadweb.org/viewtopic.php?f=8&t=24673).

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
This has been implemented. User can hit M multiple times during the command.
