### ISSUE TITLE
TravisCI to run code linting to report trailing whitespace/tabs + LF line endings

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5731]
Issue imported from https://tracker.freecad.org/view.php?id=3206

* **Reporter:** Kunda1
* **Date submitted:** 10/1/2017
* **FreeCAD version:** 
* **Category:** General
* **Status:** assigned
* **Tags:** #pending, TravisCI, unit-test

# Original report text

Recently wmayer expressed a way to remove trailing whitespaces and tabs in FC code. We could also think about avoiding more of them from being introduced in to source via testing when a PR is submitted. 

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** General
* **Updated:** 2/6/2022

# Discussion from Mantis ticket

### Comment by berndhahnebach 2017-10-08 07:16
How did he do this?

AFAIK FEM is be free of trailing whitespaces and tabs. I remove them manually. For tabs I use: 

`grep -rl --exclude=\*.{qm,fcstd,png} $'\t' ./src/Mod/Fem/`

Would be cool if we could include this in travis and step by step add any clean source directory of FreeCAD to it. 

From my point it should be before any start of compiling on travis. 

bernd

---

### Comment by Kunda1 2017-10-09 19:27
Here's a tut on [Howto Automatically fix PEP-8 issues using Travis-CI](https://gist.github.com/MichaelCurrie/802ce28c993ff2dd632c)
Just can show us how to implement something in to travis

---

### Comment by Kunda1 2017-10-14 18:41
Cause TravisCI to fail on any trailing whitespace
https://coderwall.com/p/h988xa/cause-travis-to-fail-on-trailing-whitespace
Add this to the script: section of .travis.yml
```- "! git grep ' $' -- \\*.rb \\*.js \\*.other-file-types | grep -v -e 'FILE_TO_IGNORE' -e 'OTHER_FILE_TO_IGNORE"
```

---

### Comment by Kunda1 2017-10-16 14:27
wmayer what do you think would be a good outcome if a PR is found to have trailing whitespace? Should it kill the build process and report to the user where the whitespace is?

---

### Comment by wmayer 2017-10-17 18:12
> what do you think would be a good outcome if a PR is found to have trailing whitespace?
Detecting a trailing whitespace would be good but it should not abort the build process.

---

### Comment by Kunda1 2017-11-10 14:25
FFmpeg has a cool script that checks patches: 
https://github.com/FFmpeg/FFmpeg/blob/master/tools/patcheck

---

### Comment by chennes 2021-12-17 03:54
This can probably be handled via GitHub Actions now.

---

### Comment by Kunda1 2022-01-24 18:04
A volunteer is working on this now

---

### Comment by Kunda1 2022-02-06 23:10
'Floriansimmer' https://github.com/FreeCAD/FreeCAD/pull/5314#issuecomment-1019503744

**Comment by luzpaz** [comment]
CC @Floriansimmer
