### ISSUE TITLE
Wall additions can not be set to auto (floor height).

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5732]
Issue imported from https://tracker.freecad.org/view.php?id=3208

* **Reporter:** mandichjr
* **Date submitted:** 10/3/2017
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** confirmed
* **Tags:** #lowhangingfruit, Arch

# Original report text

When a wall is composed of additions and placed in a floor... the hight of the composed wall can be set to automatic (i.e. resulting in the floor's height).  However, this does not carry through to the additions. While the additions' heights can be altered, when set to automatic and recomputed, they remain whatever they were last at.

I recommend that when a a parent wall is changed it doesn't automatically change the child's, (because internal wall may intentionally be unique) - however, the children should at least be allowed to be set to automatic as well.

**First time submitter, anxious, and sorry if broke any rules... really like this software and want to start participating. Using daily build.

# Additional information

OS: Ubuntu 17.04
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.12289 (Git)
Build type: None
Branch: master
Hash: 53168d39d6ea03a21f38337363ae0669f1f31507
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

1. Create multiple walls
2. Merge walls by adding to a parent (plus sign) [not sure about MergeWalls()]
3. Place in a floor
4. Set parent wall's height to '0'
5. Modify floor height (note only parent wall changes)
6. Modify child wall (note change)
7. Set child wall to '0' (not no change) 

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** Bug
* **OS: Zesty Zapus 17.04**
* **Platform:** Ubuntu
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by mandichjr 2017-10-03 20:10
Sorry, example .fcstd attached.  Had to remove personal info about my home first.

---

### Comment by Kunda1 2017-10-04 00:02
mandichjr No worries :) The way we do it here is first you open a forum thread and get the attention of the community. When they ascertain that it's a bug then we open a ticket and link the thread to the ticket and vice-a-versa. Conversations are recommended to happen on the thread. Check out https://freecadweb.org/wiki/Tracker for more guidance.

---

### Comment by Kunda1 2018-01-26 18:56
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=23&t=26597

---

### Comment by Roy_043 2019-09-17 14:51
The issue also occurs with walls nested in other containers such as an Arch_BuildingPart.
F.e. this does not work:
Arch_Floor (height=2960) > Arch_BuildingPart (height=0) > Arch_Wall (height=0).

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=39302

**Comment by yorikvanhavre** [comment]
Confirmed. Working on this
