### ISSUE TITLE
[Feature Request] Arch: Add "fill shape" to Arch sections

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5735]
Issue imported from https://tracker.freecad.org/view.php?id=3229

* **Reporter:** Kunda1
* **Date submitted:** 11/4/2017

# Original report text

Per http://yorik.uncreated.net/guestblog.php?2017=414

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
@yorikvanhavre when you get a chance, can you populate this ticket with more descriptive info ?

**Comment by yorikvanhavre** [comment]
This is actually already implemented ad section planes can now display cut areas as filled.
