### ISSUE TITLE
Allow to change Draft Label's target object

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5737]
Issue imported from https://tracker.freecad.org/view.php?id=3235

* **Reporter:** Kunda1
* **Date submitted:** 11/4/2017
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Per http://yorik.uncreated.net/guestblog.php?2017=414

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by vocx 2020-06-13 21:16
This bug doesn't provide a lot of information about what is wrong.

With this https://github.com/FreeCAD/FreeCAD/pull/3593, I clean up the Label object. It works well, and you can change the target object by changing the "Target" property. So I'm not sure what this bug describes.

**Comment by Roy-043** [comment]
As already mentioned, since V0.19 the "Target" property of a Draft_Label can be changed. Note that the property is hidden, you need to select "Show all" in the context menu of the Property editor first.
