### ISSUE TITLE
Add option to make Length autofocused when drawing line/walls, so one can indicate a direction with the mouse and type a length

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5745]
Issue imported from https://tracker.freecad.org/view.php?id=3248

* **Reporter:** Kunda1
* **Date submitted:** 11/7/2017
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

As per http://yorik.uncreated.net/guestblog.php?2017=414

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
This has already been implemented. Will try to close this one...

**Comment by Roy-043** [comment]
@luzpaz can you close this issue? Thanks.
