### ISSUE TITLE
Port PySide imports to pyqt-abstraction-layer

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5754]
Issue imported from https://tracker.freecad.org/view.php?id=3290

* **Reporter:** looo
* **Date submitted:** 12/26/2017
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** pyside, Qt5

# Original report text

For Qt5 we are currently using the PySide api for PySide2. This results in conflicts when used with other python libraries which depends on qt-bindings. (qt-console, spyder, matplotlib)
qtpy [1] seems to offer a good abstraction layer which will also simplify the porting for future versions of Qt.

[1] https://github.com/spyder-ide/qtpy#description

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by looooo** [comment]
I guess this one can be closed. It's not of a big advantage to use such an abstraction layer.
@FreeCAD-Bug-Importer please close ;)
