### ISSUE TITLE
Provide Alignment Guidelines On Drawing Page

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5762]
Issue imported from https://tracker.freecad.org/view.php?id=3345

* **Reporter:** wandererfan
* **Date submitted:** 2/11/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

A method to assist in aligning the various Views on a Page would be nice. 

[Forum Discussion](https://www.forum.freecadweb.org/viewtopic.php?f=35&t=26780)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by wandererfan 2019-02-15 13:27
will not be included in v0.18.

**Comment by WandererFan** [comment]
page grid implemented by commit 953304089a / #6504
