### ISSUE TITLE
Draft Clone does not maintain the colours of the original

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5765]
Issue imported from https://tracker.freecad.org/view.php?id=3354

* **Reporter:** abdullah
* **Date submitted:** 2/25/2018
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** assigned
* **Tags:** colors

# Original report text

I am not sure how difficult is this to handle as it is in the Python realm, but it would be great if the original colors where maintained.

# Steps to reproduce

1. Make a part of your choice.
2. Colour it using the "Shape Color" property.
3. Make a clone of it.

The result is with the default system color (grey).

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by gift 2018-06-10 08:47
Hello abdullah,

The provider copy the color. So it is not a Draft topic rather PartDesign. I don't know it good enough in the part design next source and I can't find the pdn provider. We must implement this Darft source code in PartDesign:

```class _ViewProviderClone:
    "a view provider that displays a Clone icon instead of a Draft icon"

    def __init__(self,vobj):
        vobj.Proxy = self

    def getIcon(self):
        return ":/icons/Draft_Clone.svg"

    def __getstate__(self):
        return None

    def __setstate__(self, state):
        return None

    def getDisplayModes(self, vobj):
        modes=[]
        return modes

    def setDisplayMode(self, mode):
        return mode

    def resetColors(self, vobj):
        colors = []
        for o in getGroupContents(vobj.Object.Objects):
            if o.isDerivedFrom("Part::Feature"):
                if len(o.ViewObject.DiffuseColor) > 1:
                    colors.extend(o.ViewObject.DiffuseColor)
                else:
                    c = o.ViewObject.ShapeColor
                    c = (c[0],c[1],c[2],o.ViewObject.Transparency/100.0)
                    for f in o.Shape.Faces:
                        colors.append(c)
            elif o.hasExtension("App::GeoFeatureGroupExtension"):
                for so in vobj.Object.Group:
                    if so.isDerivedFrom("Part::Feature"):
                        if len(so.ViewObject.DiffuseColor) > 1:
                            colors.extend(so.ViewObject.DiffuseColor)
                        else:
                            c = so.ViewObject.ShapeColor
                            c = (c[0],c[1],c[2],so.ViewObject.Transparency/100.0)
                            for f in so.Shape.Faces:
                                colors.append(c)
        if colors:
            vobj.DiffuseColor = colors
```

---

### Comment by gift 2018-06-11 18:56
Using grep I found that the clone is small solution in pdn(src/Mod/PartDesign/Gui/Command.cpp). Look on commit: [600b736](https://github.com/FreeCAD/FreeCAD/pull/1512/commits/600b736c01aff341f5430c54cb03df659e1ae1c7) Please keep in mind that not included a update service of color analogy to the placement.

---

### Comment by yorik 2019-02-15 00:00
Just add a look at this one, indeed by cloning an App::Part the clone doesn't take the individual face colors. But, it's not possible to set individual face colors to an App::Part. Only to its child objects. If you clone the child objects, it works correctly.

So the App::Part doesn't know of individual face colors. Should the clone go through the different children to make up the colors? Not realy sure that would be the proper way... Isn't the App::Part that should hold a colors list instead?

**Comment by luzpaz** [comment]
Dedicated forum thread: https://forum.freecadweb.org/viewtopic.php?t=67053

CC @yorikvanhavre @abdullahtahiriyo

**Comment by abdullahtahiriyo** [comment]
@luzpaz 
I think we could skip this ticket for the present release. I understand Yorik's comment. But I am not sure what is the current state of the code of App:Part and what would be best.

**Comment by yorikvanhavre** [comment]
I would leave this open so we don't forget about it, but indeed I don't see what to do right now, it probably needs more discussion

**Comment by Roy-043** [comment]
I assume that 'maintain the colours' means the clone should receive the colors of the original object upon creation. And once created the clone's colors should be independent.

I am not entirely sure if the word 'part' in the original report means 'App::Part'.

AFAICT there are two bugs in the Draft code, and a strange DiffuseColor update issue that need to be addressed.

Draft bug 1:
https://github.com/FreeCAD/FreeCAD/blob/d955e0f1088c9f2082822de6b7fa89024257efb1/src/Mod/Draft/draftmake/make_clone.py#L125-L126
`and (len(obj) > 1)` should be removed as `resetColors` is required for an App::Part.

Draft bug 2:
https://github.com/FreeCAD/FreeCAD/blob/d955e0f1088c9f2082822de6b7fa89024257efb1/src/Mod/Draft/draftviewproviders/view_clone.py#L65-L66
`for so in vobj.Object.Group:` should be `for so in o.Group:`

With those modifications the clone of an App::Part will receive the correct DiffuseColor, but there is an update issue. You either have to save and reopen the file to see the effects of that property, or once the clone is created run:
`obj.ViewObject.DiffuseColor = obj.ViewObject.DiffuseColor`

```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.21.31058 (Git)
Build type: Release
Branch: master
Hash: e6c53d8642af36ce7d738ab6058b063ec58e0859
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
```

**Comment by Roy-043** [comment]
... The DiffuseColor update issue can be fixed by using `ToDo.delay`

https://github.com/FreeCAD/FreeCAD/blob/d955e0f1088c9f2082822de6b7fa89024257efb1/src/Mod/Draft/draftmake/make_clone.py#L126
then becomes `ToDo.delay(cl.ViewObject.Proxy.resetColors, cl.ViewObject)`
