### ISSUE TITLE
inner/outer Threads

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5766]
Issue imported from https://tracker.freecad.org/view.php?id=3369

* **Reporter:** reox
* **Date submitted:** 3/10/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Enable drawing of threads

# Additional information

See discussion: https://forum.freecadweb.org/viewtopic.php?f=35&t=27376

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by maker 2020-12-05 22:16
Should be reviewed in extension and in comparison to existing ticket https://tracker.freecadweb.org/view.php?id=4489 dated 2020-11-10.

**Comment by luzpaz** [comment]
@WandererFan is this fully complete or is there anything left?

**Comment by luzpaz** [comment]
@Wandererfan ping

**Comment by Roy-043** [comment]
Related #6127.

**Comment by benj5378** [comment]
> To me it looks like it was implemented in https://github.com/FreeCAD/FreeCAD/commit/380386851e2349e87665a60464b0e7ba7d4c1047.
@WandererFan

**Comment by luzpaz** [comment]
Consolidated in to #6127. Closing.
