### ISSUE TITLE
[Feature Request] TechDraw: BOM (Bill of Materials) functionality

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5769]
Issue imported from https://tracker.freecad.org/view.php?id=3378

* **Reporter:** Kunda1
* **Date submitted:** 3/16/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** feedback
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=8&t=23592

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2018-10-05 12:00
https://github.com/openscopeproject/InteractiveHtmlBom
Posted on [Interactive Html Bom Plugin](https://forum.freecadweb.org/viewtopic.php?f=8&t=31344)

Edit: another BOM utility for KiCAD: [KiBOM](https://github.com/SchrodingersGat/KiBoM)

---

### Comment by wandererfan 2018-10-05 12:08
BOM is not core TD functionality.  Displaying an existing BOM might be reasonable request, but creating the BOM is related to "assembly"(?).

**Comment by FEA-eng** [comment]
@maxwxyz I guess this can be closed (also based on wandererfan's comment).
