### ISSUE TITLE
Provide Attachment mode perpendicular to an existing plane

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5779]
Issue imported from https://tracker.freecad.org/view.php?id=3407

* **Reporter:** chrisb
* **Date submitted:** 3/28/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Attachment should support attachin a plane perpendicular to another plane.
[See forum discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=27698)

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
#14372 introduces the "XY parallel to plane" mode. With angular offsets that mode can probably be used to align perpendicularly as well.

**Comment by Roy-043** [comment]
@chrisb-github Should this stay open?

**Comment by luzpaz** [comment]
@chrisb-github bump

**Comment by maxwxyz** [comment]
I'm closing this then fo rno feedback and it is possible as described above.

**Comment by luzpaz** [comment]
JFYI @chrisb-github
