### ISSUE TITLE
Add "X-Ray" display mode

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5780]
Issue imported from https://tracker.freecad.org/view.php?id=3414

* **Reporter:** silopolis
* **Date submitted:** 3/31/2018
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Hi,

As suggested by zbigg in the forum here https://forum.freecadweb.org/viewtopic.php?f=8&t=27049, having a display mode as the X-Ray one found in Sketchup would be very beneficial in a number of situations.

Adding the possibility to snap to otherwise hidden geometries would surely ice the cake :)

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **OS: Debian 9 "Stretch" Linux 4.9**
* **Platform:** Intel x86_64
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2018-05-31 17:33
See 
https://forum.freecadweb.org/viewtopic.php?f=8&t=27049&start=10#p224664
and
https://forum.freecadweb.org/viewtopic.php?f=22&t=20698&hilit=x+ray&start=120#p234462

---

### Comment by nhomar 2019-01-12 22:51
Hello.

It is also necessary on Draft, and IMHO it is a bug not a feature.

Snap should be available in the hidden elements from the view if not it is almos impossible to move one object in reference to the other, (Even with snap grid activated, the grid itself is hidden also).

Thanks in advance for this tool.

**Comment by luzpaz** [comment]
https://github.com/sanguinariojoe/freecad.xray

**Comment by luzpaz** [comment]
The official repo is at https://gitlab.com/sanguinariojoe/freecad.xray/
