### ISSUE TITLE
Show in Sketcher if the sketch is closed

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5784]
Issue imported from https://tracker.freecad.org/view.php?id=3438

* **Reporter:** chrisb
* **Date submitted:** 4/21/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

It would be helpful if a closed sketch is displayed in a different color.
[Forum discussion](https://forum.freecadweb.org/viewtopic.php?p=229022#p228654)

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment]
This can be closed in favor of https://github.com/FreeCAD/FreeCAD/issues/11799

**Comment by maxwxyz** [comment]
@Roy-043 ^ also this one
