### ISSUE TITLE
Add the following functions to expressions and spreadsheet: concatenate text and indirect

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5788]
Issue imported from https://tracker.freecad.org/view.php?id=3460

* **Reporter:** ulrich1a
* **Date submitted:** 5/4/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** expressions, spreadsheet

# Original report text

It would be an advantage, if a spreadsheet can be filled with different sets of parameters to create a model and then just change one cell to select a certain parameter set.

This can be done in a traditional spreadsheet with text concatenation and a line with indirect-functions that use the concatenated text as a cell-adress.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 11/24/2021

# Discussion from Mantis ticket

### Comment by realthunder 2020-02-27 05:54
Implemented with [this](https://github.com/FreeCAD/FreeCAD/commit/d141975701923971ee3845667f07f3c0c1fc15e7) commit in upstream. String can be concatenated using simple '+', or '%' similar to Python string formatter. Indirect reference can be done by just referring to another string property/cell.

**Comment by Roy-043** [comment]
[Configuration tables](https://wiki.freecad.org/Spreadsheet_Workbench#Configuration_tables) are available since V0.20. Closing this as completed.
