### ISSUE TITLE
Allow use of Draft Picker to set start points in paths.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5790]
Issue imported from https://tracker.freecad.org/view.php?id=3481

* **Reporter:** sliptonic
* **Date submitted:** 5/16/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

It's sometimes desireable to specify exactly where an operation path will begin. Many operations currently allow the user to manually set a start point for the path by entering the coordinates and setting the boolean 'use start point' to True.  

This is cumbersome and error prone.  The user should be able to click a button to 'set start point'.  The draft-snapper tool should activate to allow picking a point on the canvas and returning the coordinates to the operation.

# Additional information

Multiple start points should also be allowed.  On processing, the nearest start point from the list should be found and passed to PathArea to be used.

This is necessary for operations like Profile From Faces with the option to process holes set to true.  In this case the cutter will pick up and rapid between holes.  The start point for each hole should be configurable.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-03-03 21:12
sliptonic are you planning for this to be fixed pre 0.18 or are you bumping to 0.19 ?

---

### Comment by sliptonic 2019-03-04 00:30
It would be a nice UI improvement but not going to happen this cycle.  moved to 0.19

**Comment by sliptonic** [comment]
Lots of overlap with issue https://github.com/FreeCAD/FreeCAD/issues/5935
Closing this one.  We'll look at a more uniform approach to startpoints post 0.20.
