### ISSUE TITLE
Add ability to copy objects with expressions linked to spreadsheet

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5791]
Issue imported from https://tracker.freecad.org/view.php?id=3487

* **Reporter:** clarkitect
* **Date submitted:** 5/18/2018
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** new
* **Tags:** expressions

# Original report text

As discussed in this thread https://forum.freecadweb.org/viewtopic.php?p=232149&sid=592cce21db486df260e6f8e1b91b2edc#p232149

When copying objects that have expressions using an alias controlled by a spreadsheet, the copies always reference the original spreadsheet. There is no way to deep copy and point the expressions to the new, copied spreadsheet. Users should be given the choice whether expressions point to original, or copied spreadsheet. 

# Additional information

OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13450 (Git)
Build type: Release
Branch: (HEAD detached at 129e2f7)
Hash: 129e2f7a1b55c91880f2db2da264746acdc14d38
Python version: 2.7.14
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedKingdom (en_GB)

# Steps to reproduce

Files and further detailed description are in the forum thread.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
The requested feature is available in the version listed below:
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33492 (Git)
Build type: Release
Branch: master
Hash: 6e235a4809e14674aa2cd23e68630b68998a53d4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
```
