### ISSUE TITLE
DXF export (Autodesk DXF 2D type) doesn't add any UNITS field inside the dxf file.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5793]
Issue imported from https://tracker.freecad.org/view.php?id=3494

* **Reporter:** @easyw 
* **Date submitted:** 5/25/2018
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** confirmed
* **Tags:** DXF, export, units

# Original report text

FreeCAD DXF export does not add $LUNITS and $INSUNITS both of which are needed for correct importing into any CAD.
$LUNITS and $INSUNITS should be included in the exported file, to specify which units the design is based on.
Autodesk section group codes:
https://www.autodesk.com/techpubs/autocad/acad2000/dxf/header_section_group_codes_dxf_02.htm

Related forum topics:
https://forum.freecadweb.org/viewtopic.php?f=8&t=28925
https://forum.kicad.info/t/units-once-more-dxf-import-trouble/10844

# Other bug information

* **Priority:** high
* **Severity:** feature
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @easyw 2018-05-25 22:58
following the KiCAd forum here some valuable notes:
The fun you find while digging into obscure specifications

$INSUNITS was introduced in the “Autocad 2000” specification for DXF.

This means any export methods set to AC1006 = R10, AC1009 = R11 and R12, AC1012 = R13 or AC1014 = R14. Will not have that tag present if the tool is respecting the export option,

Freecads export is for AC1009 / R12, so it will never include that tag so long as they are following the specification, and to include it would involve them remaking the exporter to support whatever the Autocad 2000 version is.

Before this, It was simply that DXF files where unitless, Most tools like solidworks and Autocad assumed this to be in inches if not specified on import,

---

### Comment by Kunda1 2018-05-30 23:22
> I had this issue once too. Back than it turned out the DXF version freecad exports does not use units, it is not in this versions standart. You can check the version by the DXF file header, there is a identifier which you can than relate to the spec version.
> 
> The conclusion back than was, that the error is on the importing software site: it needs to check the specification version of the DXF and use units only when supportet by it.
> 
> Don't know if this is still valid though it if freecad has upgraded the DXF version.
ref: https://forum.freecadweb.org/viewtopic.php?f=8&t=28925#p235782

---

### Comment by Kunda1 2018-09-14 19:56
Related: #5805

---

### Comment by rawrpenguinzombies 2018-09-14 20:05
I am willing to pitch in on something for whoever fixes this and the related #5805 ID tickets.

---

### Comment by Kunda1 2018-09-15 12:48
rawrpenguinzombies please mention that on the forum thread so it's more visible.

**Comment by luzpaz** [comment]
My bad.. the PR hasn't been merged yet :facepalm: (Sorry for all the noise)
