### ISSUE TITLE
Sketcher Issue while using Windows high constrast mode

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5797]
Issue imported from https://tracker.freecad.org/view.php?id=3536

* **Reporter:** Stonehenge81
* **Date submitted:** 7/9/2018
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** confirmed
* **Tags:** sketcher, Win

# Original report text

When in Windows High Contrast mode, the sketcher doesn't work as expected. When trying on a sketch, items are not visible until you either exist the sketcher or select an already existing line.

When selecting a sketch line, it is not highlighting correctly.

I have tried selecting different stylesheets, but the issue persists.

These issues go away when Windows is not in high contrast mode.

# Additional information

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13522 (Git)
Build type: Release
Branch: releases/FreeCAD-0-17
Hash: 3bb5ff4e70c0c526f2d9dd69b1004155b2f527f2
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

- Place Windows into High Contrast mode. (left-alt + left-shift + PrintScreen).
- Create a new sketch
- Draw line / rectange

# Other bug information

* **Priority:** normal
* **Severity:** tweak
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2018-07-09 18:35
Stonehenge81 Can you recreate with [0.18dev](https://github.com/FreeCAD/FreeCAD/releases/tag/0.18_pre) ?
Also please open a forum thread and link this ticket to it (+ add the thread URL to this ticket)

---

### Comment by Kunda1 2018-10-08 14:18
Stonehenge81 please respond 

CC GeneFC can you please try to recreate this ?

---

### Comment by Stonehenge81 2018-10-08 15:09
I downloaded the latest .18dev and I still experience the same issue. 

After further investigation, I noticed that the sketch (not freecad application) is unresponsive. The same unresponsiveness can be noticed when in the viewing plan. Trying to zoom in / out or rotate is extremely sluggish.

Also, this issue, happening on an Intel system, does not happen on another computer, which is an AMD system. I'm not sure if there is any correlation, but thought I would mention it.

---

### Comment by Kunda1 2018-10-08 15:38
Stonehenge81 Thanks for the response. Can you post the actual v0.18dev ***Help > About FreeCAD > Copy to clipboard*** info in this ticket please? 

---

### Comment by Stonehenge81 2018-10-08 15:49
Of course, sorry for the very delayed initial reply. Also, I posted my issues on the Forum. I'll add the link once it has been approved.

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14928 (Git)
Build type: Release
Branch: master
Hash: 3d833e52df450cb98c1dacd0a3d17b439217a4c0
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: English/UnitedStates (en_US)

---

### Comment by Kunda1 2018-10-08 22:48
Confirmed bug on the forum thread

---

### Comment by wmayer 2019-01-16 15:12
https://forum.freecadweb.org/viewtopic.php?t=31425

**Comment by luzpaz** [comment]
Can a windows user test if this is still relevant ?
