### ISSUE TITLE
Renaming alias in spreadsheet changes the spreadsheet part of the reference from label to internal name

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5800]
Issue imported from https://tracker.freecad.org/view.php?id=3560

* **Reporter:** lokomoko
* **Date submitted:** 8/15/2018
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** confirmed
* **Tags:** equation, expressions, formula, spreadsheet

# Original report text

Renaming an alias in a spreadsheet changes the spreadsheet-part of a reference to the alias from Label (e.g. "MyInputData") to internal name/Id (e.g. "Spreadsheet001").

Discussed in Forum under [Renaming alias in spreadsheet changes the name of the spreadsheet in any reference](http://forum.freecad.org/viewtopic.php?f=3&t=30294)

# Additional information

OS: Ubuntu 16.04.5 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13528 (Git) AppImage
Build type: None
Branch: releases/FreeCAD-0-17
Hash: 5c3f7bf8ec51e2c7187789f7edba71a7aa82a88b
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

# Steps to reproduce

1. Create new document
2. In spreadsheet workbench create a spreadsheet by the name "MyData"
3. Create cell with an alias e.g. "BoxSize" and a value
4. In part workbench create a 3D-object (e.g. cube) and therein a reference to the alias (e.g. "=MyData.BoxSize").
5. In spreadsheet change name of alias to BoxLength

Actual Result: The reference in the 3D-Object is "=Spreadsheet001.BoxLength" now, that is the alias was changed, but also the name of the spreadsheet
Expected Result: The reference in the 3D-Object should be "=MyData.BoxLength"

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 11/24/2021

# Discussion from Mantis ticket

### Comment by lokomoko 2018-08-15 12:41
Direct link to forum topic [Renaming alias in spreadsheet changes the name of the spreadsheet in any reference](https://forum.freecadweb.org/viewtopic.php?f=3&t=30294)

---

### Comment by wmayer 2018-11-11 11:27
When renaming an alias then at some point the functions Document::renameObjectIdentifiers,  DocumentObject::renameObjectIdentifiers, PropertyExpressionEngine::renameObjectIdentifiers and ObjectIdentifier::relativeTo are called.
Because the ObjectIdentifier hasn't explicitly set documentObjectName it gets the (internal) name from the pointer to the DocumentObject.

**Comment by BuhtigithuB** [comment]
Get caught by this bug that requires a lot of edits if we ever need to rename spreadsheet parameters names because cloning designed part and reuse it for other purpose... So the need is there for having opened document renaming referenced alias the same way as "save as" will upgrade assembly 4 part links of linked component part of an assembly.

Thanks for great CAD software which is so useful and versatile!

**Comment by luzpaz** [comment]
Do you mind bumping the forum thread to get more exposure?

**Comment by djurodrljaca** [comment]
Since I am annoyed by this as well I would be willing to try to fix it...
