### ISSUE TITLE
Improve PartDesign Transformation features performance

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5806]
Issue imported from https://tracker.freecad.org/view.php?id=3600

* **Reporter:** normandc
* **Date submitted:** 9/16/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

PartDesign Transformation features (linear/polar pattern, mirrored, MultiTransform) are extremely slow when the number of occurrences is high. Surely there is a way to improve performance, because Draft Array can create multiple occurrences a lot faster.

Forum topics to be linked later, as I can't find any relevant one at the moment.

Test file may be added later as well, please attach if you have one.

# Additional information

#3527 is a good usecase

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 3/15/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-03-15 21:47
davidosterberg would you be interested in looking at this?

**Comment by mwganson** [comment]
Can be closed now, I think.

**Comment by chennes** [comment]
For reference: this is based on @davidosterberg's work, described in forums discussion here: https://forum.freecadweb.org/viewtopic.php?t=55860

The PR was #4504.
