### ISSUE TITLE
[Feature] [FEM] CalculiX support analysis type 'no analysis' for model checking (in task panel)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5814]
Issue imported from https://tracker.freecad.org/view.php?id=3622

* **Reporter:** berndhahnebach
* **Date submitted:** 10/3/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=18&t=31303#p260032

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by berndhahnebach 2019-03-01 15:23
https://github.com/FreeCAD/FreeCAD/commit/40d0db3

but it needs to be added to the task panel too.

**Comment by FEA-eng** [comment]
This issue can be closed as completed:

![analysis](https://github.com/FreeCAD/FreeCAD/assets/59876896/1b613594-d7c0-4b1d-bd70-c704275e615f)

**Comment by FEA-eng** [comment]
@maxwxyz Can you close this as completed (screenshot above shows it in the task panel)?

**Comment by maxwxyz** [comment]
Closed as implemented.
