### ISSUE TITLE
[FEM] GUI, mesh VP, setting element colors does not work as expected in some cases

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5815]
Issue imported from https://tracker.freecad.org/view.php?id=3624

* **Reporter:** berndhahnebach
* **Date submitted:** 10/5/2018
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

It seams setting element colors does not work as aspected in some cases. 

see https://forum.freecadweb.org/viewtopic.php?f=18&t=31123&start=30#p258911

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by wmayer 2019-01-15 20:33
This fixes the colouring of the nodes:
https://github.com/FreeCAD/FreeCAD/commit/bdbea25d0d7e00cad5d71184a63e9c9e270df2aa

**Comment by FEA-eng** [comment]
@marioalexis84 This issue was closed accidentally by the word fix here:

> This fixes https://github.com/FreeCAD/FreeCAD/issues/6131 FemMesh coloring issue (fix https://github.com/FreeCAD/FreeCAD/issues/5815 requires one more step, since currently only first-order meshes are colored correctly).

and it should be reopened, right?

**Comment by marioalexis84** [comment]
I think a new issue should be created for the case of 2nd elements.

**Comment by FEA-eng** [comment]
> I think a new issue should be created for the case of 2nd elements.

Actually, what's the current problem with the coloring of 2nd order meshes? I haven't found any specific issues, even those from https://forum.freecad.org/viewtopic.php?f=18&t=31123&start=30#p258911

**Comment by marioalexis84** [comment]
>what's the current problem with the coloring of 2nd order meshes?

Create a 10mm x 10mm Part Plane.
Create a 2nd order mesh setting min element size to 10mm to create only four faces.
Set the mesh view property `ColorMode` to `"ByElement"`.
Set the color of the first face (element id = 5) to red:
`App.ActiveDocument.FEMMeshGmsh.ViewObject.ElementColor={5:(1,0,0)}`
The element is partially colored.
