### ISSUE TITLE
Mediawiki Extension: Please install MassRegex to make sweeping changes to blocks of wiki pages at once

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5820]
Issue imported from https://tracker.freecad.org/view.php?id=3645

* **Reporter:** Kunda1
* **Date submitted:** 10/21/2018
* **FreeCAD version:** 
* **Category:** General
* **Status:** assigned
* **Tags:** documentation, wiki

# Original report text

Ref: https://forum.freecadweb.org/viewtopic.php?f=21&t=31424

# Other bug information

* **Priority:** high
* **Severity:** major
* **Category:** General
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
Closing as this is obsolete
