### ISSUE TITLE
Infinite lines in Sketcher

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5825]
Issue imported from https://tracker.freecad.org/view.php?id=3660

* **Reporter:** abdullah
* **Date submitted:** 10/29/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Consider the impact of infinite lines in the sketcher vs its convenience.

This can be effected in several ways, from including a new geometric type, to introducing a new constraint to constraint unused DoFs of an element.

Just see if it makes sense within the whole FC.

https://forum.freecadweb.org/viewtopic.php?f=8&t=31854&p=265469#p265439

# Other bug information

* **Priority:** none
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by normandc 2018-10-30 02:24
I have no objection to it, but I hope you still allow construction lines to have finite length as what we have now. IMO seemingly infinite lines would clutter a sketch real fast.

**Comment by adrianinsaval** [comment]
this one doesn't make much sense and has been inactive since 2018, I suggest closing.

**Comment by luzpaz** [comment]
CC @abdullahtahiriyo (who opened the ticket)
