### ISSUE TITLE
Sketcher: wrong normals of tangents of ellipses

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5827]
Issue imported from https://tracker.freecad.org/view.php?id=3667

* **Reporter:** @PLChris  
* **Date submitted:** 11/2/2018
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

The normal of an arc which is tangent to an ellipse is not calculated correctly. Seen when investigating filleting ellipse-ellipse intersections.
[forum discussion](https://forum.freecadweb.org/viewtopic.php?f=10&t=31700#p265173)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by PLChris** [comment]
Issue is fixed.
