### ISSUE TITLE
Implement offset curves in the sketcher

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5828]
Issue imported from https://tracker.freecad.org/view.php?id=3668

* **Reporter:** abdullah
* **Date submitted:** 11/3/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Never realised how useful they may become.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by chrisb 2019-01-21 17:38
Is this a doublette of [3708](https://www.freecadweb.org/tracker/view.php?id=3708)?

**Comment by abdullahtahiriyo** [comment]
@adrianinsaval 

Yes, a lot of life happened and continues to happen.

Maybe this year is different :)
