### ISSUE TITLE
[Feature Request] Sketcher: Valid profile validation at sketch exit

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5833]
Issue imported from https://tracker.freecad.org/view.php?id=3681

* **Reporter:** abdullah
* **Date submitted:** 11/11/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Work out a final check on exit, in order to get confirmation on exiting edit mode that the user intends to have an "open" profile.

Rationale:
- 99% of the profiles must be extrudable
-  1% may be open, like paths to sweep.

Benefit:
- Increase productivity by avoiding to have to come back to the Sketcher.
- Better detection of bugs relating to closed profiles that are not so detected.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by luchete80 2018-12-23 02:09
Hi, i think this could be shown by darkening the profile one is closed, like in new solidworks versions. Just an idea. I'm begining to study source in order to try to do at least something about it. Regards!

**Comment by maxwxyz** [comment]
@luzpaz can be closed in favor of https://github.com/FreeCAD/FreeCAD/issues/11799
Not all WB and features need closed loops

**Comment by maxwxyz** [comment]
@Roy-043 ^ this one too, sorry for the spam
