### ISSUE TITLE
Sweep Missing Path / Spine in Dialog or Properties

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5842]
Issue imported from https://tracker.freecad.org/view.php?id=3713

* **Reporter:** @paullee0 
* **Date submitted:** 12/3/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Discussion in forum [Sweep Missing Path / Spine in Dialog or Properties](https://forum.freecadweb.org/viewtopic.php?f=3&t=32569#p271762):

"...want to edit a sweep object.

In the property dialog, there is 'Sections' to change, but there is none for the ''path' or 'spine'. Double-click it return a translation dialog only.

Need to access through python sweep.spine attribute."
1. It would be good if the property tab has the Spine attribute to edti.
2. Even better is something like Curve WB's intuitive and interactive dialog could be included

# Steps to reproduce

See above copy of forum discussion.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **OS: All n/a**
* **Platform:** All
* **Updated:** 12/29/2021

# Discussion from Mantis ticket

### Comment by @paullee0  2018-12-03 14:23
[See more discussion and suggestion here](https://forum.freecadweb.org/viewtopic.php?f=3&t=32569&p=272072#p271989)

---

### Comment by @chennes 2021-12-29 05:35
@donovaly this sounds like something you've worked on during the 0.20 dev cycle. Can you comment on the status of this report?

**Comment by donovaly** [comment]
The missing property for Sweeps are there in FC 0.19. So this was fixed in the meantime.
