### ISSUE TITLE
Block constraint does not work on GeomPoints

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5844]
Issue imported from https://tracker.freecad.org/view.php?id=3718

* **Reporter:** abdullah
* **Date submitted:** 12/8/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Not sure if it should or not. As block constraint should be reviewed because it seems to be possible to improve it, I put this here to remember to take a look.

Forum:
https://forum.freecadweb.org/memberlist.php?mode=viewprofile&u=8738

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment]
Will close this in favor of https://github.com/FreeCAD/FreeCAD/issues/11434 for further discussion.
