### ISSUE TITLE
[Feature] [FEM] make elmer writer fully compatible with FreeCAD unit system

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5851]
Issue imported from https://tracker.freecad.org/view.php?id=3742

* **Reporter:** @berndhahnebach
* **Date submitted:** 12/19/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** confirmed
* **Tags:** 

# Original report text

It seams Elmer solver uses SI units, which means meter. We gone use milli meter which works well but could result in some problems. There is a forum topic about this, see https://forum.freecadweb.org/viewtopic.php?f=18&t=32211

Best would be if Elmer writer would use units, and the user could decide if he wants to write SI units or mm.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by wwmayer** [comment]
Another related thread: https://forum.freecadweb.org/viewtopic.php?f=18&t=67199

**Comment by luzpaz** [comment]
@donovaly is this issue still valid?  (asking because of https://forum.freecad.org/viewtopic.php?p=581263#p581263)

**Comment by donovaly** [comment]
This is fixed since FC 0.20.0.
