### ISSUE TITLE
Solver failing on certain sketch

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5854]
Issue imported from https://tracker.freecad.org/view.php?id=3745

* **Reporter:** @PLChris 
* **Date submitted:** 12/23/2018
* **FreeCAD version:** 0.18
* **Category:** General
* **Status:** assigned
* **Tags:** 

# Original report text

[Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=32967)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** General
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
Per user1234 on the forum:
> As far as i know, abdullah worked on the solver over this time. Now It works, also the redundancy is noticed by the solver. Should be solved. 
![image](https://user-images.githubusercontent.com/4140247/165182739-6bd31ade-4f80-4151-8655-504bea561885.png)

CC @abdullahtahiriyo @PLChris

**Comment by PLChris** [comment]
Fixed.

**Comment by luzpaz** [comment]
@PLChris any idea in what commit ?
