### ISSUE TITLE
Sign AppImages

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5856]
Issue imported from https://tracker.freecad.org/view.php?id=3758

* **Reporter:** Kunda1
* **Date submitted:** 12/31/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** appimage, packaging

# Original report text

[quote=blacey]signing appimages looks straight-forward here - https://docs.appimage.org/packaging-guide/signatures.html . No special cert is needed so anyone can extend the travis.yml to perform the signing step. We would need to produce a key and embed it as a secure variable in the travis.yml. I’m trying to resurrect the macOS builds so don’t know when I will have a chance to look at this...[/quote]

Per probonopd in https://github.com/FreeCAD/FreeCAD-AppImage/issues/6 we can:
**Use the -s switch of [appimagetool](https://github.com/AppImage/AppImageKit#appimagetool-usage) to embed a signature into the AppImage.**

Related Forum threads: 
https://forum.freecadweb.org/viewtopic.php?f=10&t=15525&start=300#p268325
https://forum.freecadweb.org/viewtopic.php?f=10&t=34981&p=329620#p329620

# Other bug information

* **Priority:** immediate
* **Severity:** major
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-01-05 11:53
punting to sgrogan

---

### Comment by Kunda1 2019-03-16 12:27
Hey triplus is it OK that I assign this ticket to you? I was following the 0.18 Release thread on the forum and sgrogan defers to you on this task.

---

### Comment by Kunda1 2019-06-18 09:19
Examples of users concerned with unsigned appimages:

* https://www.reddit.com/r/FreeCAD/comments/c0pp2h/cannot_install_latest_freecad_package_from_ubuntu/erg3obe/
* https://forum.freecadweb.org/viewtopic.php?f=4&t=33244&p=279262#p279233

---

### Comment by Kunda1 2019-08-12 20:56
This still needs to happen

---

### Comment by Kunda1 2019-08-19 00:49
Another inquiry regarding this issue: 
https://forum.freecadweb.org/viewtopic.php?f=3&t=38641

---

### Comment by Kunda1 2019-08-30 13:07
Solution according to probonopd is at 
https://github.com/FreeCAD/FreeCAD-AppImage/issues/6#issuecomment-525840839

**Comment by luzpaz** [comment]
Closing in favor of https://github.com/FreeCAD/FreeCAD-Bundle/issues/6
