### ISSUE TITLE
dxf export units

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5858]
Issue imported from https://tracker.freecad.org/view.php?id=3764

* **Reporter:** Renato Rebelo
* **Date submitted:** 1/9/2019
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

When trying to export a file to dxf the file is always exported in millimeters, would it be possible to create an option to choose the export units?

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by yorikvanhavre** [comment]
Fixed with 8585149ab4ee0c165c5c443e84915741968d5624
