### ISSUE TITLE
Base::Console().Warning() Color almost unreadable on status bar with standard color theme

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5860]
Issue imported from https://tracker.freecad.org/view.php?id=3772

* **Reporter:** wwwutz
* **Date submitted:** 1/14/2019
* **FreeCAD version:** 0.18
* **Category:** General
* **Status:** new
* **Tags:** 

# Original report text

When `Base::Console().Warning()` is called, the text color changes to 'orange' which is hard to read on white, but almost impossible to read on grey background. 
See attached screen crop.

Suggested fix: make it black. [ colour visual impaired people would be pleased 8-) ]

# Additional information

OS: Windows 7
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15619 (Git)
Build type: Release
Branch: master
Hash: 7d8e5662648b794b5c93e28835a2bf5c1fddffec
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: German/Germany (de_DE)

# Steps to reproduce

generate a Warning() to be logged 8-)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** General
* **OS: Windows 7**
* **Platform:** PC
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-02-10 15:54
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=34124

**Comment by luzpaz** [comment]
Obsolete
