### ISSUE TITLE
Central translate function

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5863]
Issue imported from https://tracker.freecad.org/view.php?id=3778

* **Reporter:** Kunda1
* **Date submitted:** 1/17/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** feedback
* **Tags:** #pending

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=8&t=22324&start=60#p178380

[quote=loooo]I think we already had a discussion about a centralized translate function. This stuff comes up again and again, so in my mind it would make sense to have a centralized function available. It would definetly simplify porting to new dependencies, as the same stuff doesn't have to be done in all kind of modules.[/quote]

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 1/23/2022

# Discussion from Mantis ticket

### Comment by Kunda1 2022-01-23 01:14
looo can you weigh in on this ticket? Has anything progressed on this front since?

**Comment by luzpaz** [comment]
Closing in favor of the documentation on translation in https://wiki.freecad.org/Translating_an_external_workbench#Technical_details_and_advanced_usage
