### ISSUE TITLE
[Feature] Sketcher - overload of the horizontal/vertical distance constraints between curves

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5864]
Issue imported from https://tracker.freecad.org/view.php?id=3780

* **Reporter:** freecad-heini-1
* **Date submitted:** 1/18/2019
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?p=280421#p280421
https://forum.freecadweb.org/viewtopic.php?p=280680#p280680

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by adrianinsaval** [comment]
@FlachyJoe what do you think of this request? If you consider it feasible and potentially useful it might be worth keeping, otherwise I think this one should be closed.

for convenience I'll upload here the demo gif from the form post:
![image](https://user-images.githubusercontent.com/36372335/228376571-b6faaaa9-a672-41dc-b100-aff648ac83d5.png)

**Comment by FlachyJoe** [comment]
I add this to my todo list.

**Comment by NXTler** [comment]
This would make the sketcher so much better

**Comment by luzpaz** [comment]
@FlachyJoe do you have a branch associated with this ticket yet ?

**Comment by maxwxyz** [comment]
@FlachyJoe do you already have something, else I might try this one at some time.

**Comment by maxwxyz** [comment]
To be clear, should the minimum or the maximum of the distance be constrained?

**Comment by FlachyJoe** [comment]
@maxwxyz I have nothing yet, feel free.

**Comment by maxwxyz** [comment]
@FlachyJoe ok, do you have a maximum distance between two circles already? Currently  the shortest distance between two circles is constrained, but I guess with this FR, the maximum distance between two curves is more interesting

**Comment by FlachyJoe** [comment]
@maxwxyz you have to define a new constraint for the solver,  read Abdullah's [FreeCAD Sketcher Solver Architecture](https://github.com/FreeCAD/FreeCAD/files/13462593/fc-solver-latex.pdf) and take a look at https://github.com/FreeCAD/FreeCAD/blob/37f7ccfc862ebaae72769dbd75079be2b69bdaaf/src/Mod/Sketcher/App/planegcs/Constraints.cpp#L2923-L2977

**Comment by maxwxyz** [comment]
@FlachyJoe so am I right to define 15 new constraints for circles and arcs:
- max distance circle to circle, circle to line, and circle to point
- max/min horizontal distance circle to circle, circle to line, and circle to point
- max/min horizontal distance circle to circle and circle to line
