### ISSUE TITLE
Fix movement of children of Arch objects

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5868]
Issue imported from https://tracker.freecad.org/view.php?id=3789

* **Reporter:** yorik
* **Date submitted:** 1/23/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

When rotating an Arch object that has additions, the result is not correct (the additions get disaligned), and if removing the addition, moving it to the right place and re-add it, the result is not correct either. So:

- The code that moves children (ArchComponent.onChanged) is buggy
- The code that constructs the final object (ArchComponent.processSubShapes) is buggy too

Below is an alternative snippet I tested but doesn't work either. Seems a better base to start with, though

# Additional information

https://forum.freecadweb.org/viewtopic.php?f=23&t=33669&p=281903#p281903

Snippet for ArchComponent.py, L330 - different method to calculate child movement

```# TODO - Implement/test this method instead - calculate additional movement caused by the rotation
diff = child.Placement.Base.sub(self.oldPlacement.Base)
if diff.Length:
    diff = self.oldPlacement.inverse().multVec(diff) # move back to origin
    diff = obj.Placement.multVec(diff) # move to the new location
    npos = obj.Placement.Base.add(diff) # new position of the child placement
    child.Placement.Base = npos```


# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Debian Testing 64bit**
* **Platform:** PC
* **Updated:** 2/6/2021


# Discussion from Mantis ticket

### Comment by mickele 2019-10-30 14:16
Any news about this bug?

**Comment by Roy-043** [comment]
Fixed with #8506.
