### ISSUE TITLE
PartDesign Hole Depth Dimension should provide the option not to take the angled drill point type into account

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5879]
Issue imported from https://tracker.freecad.org/view.php?id=3818

* **Reporter:** LAROBERTE
* **Date submitted:** 2/5/2019
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** resolved
* **Tags:** 

# Original report text

In the PartDesign Hole feature, the Depth Dimension option controls the overall depth of a blind hole. When the Drill point option is set to Angled, the dimension includes the conical end point generated by the Angled drill point option.

There should be an option to set the depth dimension so that it does not include the conical end point, to comply with some standards.

http://euro.branly.free.fr/ISI/Construction/Dessin/filet/filets.htm
http://joho.p.free.fr/EC/COURS%20DOC/FILETAGE/REPRESENTATION/Cotation%20des%20filetages.pdf

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-02-06 03:00
LAROBERTE Did you mean Path Workbench ?
Have you opened a forum thread to discuss this ? (per our guidelines at the top of the page)

CC sliptonic

---

### Comment by LAROBERTE 2019-02-06 08:18
Hello
I do not speak English, it is very difficult for me to open and follow a discussion, I am obliged to translate everything, it is long and tedious.
I looked in the forum if someone was talking about it, but I did not find anything.
The problem is not a bug, but rather an error in the standards of rating, surely very easy to solve, that's why I intervened.

---

### Comment by Kunda1 2019-02-08 21:48
mlampert care to weigh in ?

---

### Comment by mlampert 2019-02-08 22:14
I have never seen this dialog before - where does it come from?

---

### Comment by Kunda1 2019-02-10 00:46
LAROBERTE please provide instructions on how to reproduce the bug

---

### Comment by LAROBERTE 2019-02-10 05:16
Ok
I take care of it, but I do not work until Tuesday
thank you for considering my post.

---

### Comment by normandc 2019-02-10 19:02
Bug was wrongly reported in "FreeCAD (all projects)" instead of PartDesign.

Changed bug severity from major to minor.

I cannot reproduce the issue. For me, if I set the hole depth to 10mm with angled drill point, the 10mm value includes the drill point. Please provide your FreeCAD info as explained in the enormous yellow banner that you could not possibly miss.

I'm switching this report's status to feedback required.

OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15816 (Git)
Build type: Release
Branch: master
Hash: 7ee0e4d43909ec688299b8498b240cccf8362c47
Python version: 2.7.15rc1
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/Canada (fr_CA)

---

### Comment by normandc 2019-02-10 19:05
Okay, I think I understand the issue now. You actually want the hole depth NOT TO take the conical end into account.

This would be a feature request then, because in commercial software I use, both possibilities are offered (depth with or without the conical drill point).

---

### Comment by LAROBERTE 2019-02-10 22:41
hello, the downhole cone should never be included in the hole depth, it is only the consequence of the shape of the drill bit. The depth of a hole should take into account only the part with the correct diameter. see the two links of my first post.
if you want to add a feature, you should be able to choose the thread depth and drilling depth. Drilling and always deeper than the threading so as not to break the tools. the angle of the drilling cone is 120 degrees, the angle of the thread is 90 degrees. I do not have freecad until Tuesday, I promise you to make a correct post as soon as possible.
it's not very important for 3D printing, but it's very important for mechanical machining

---

### Comment by normandc 2019-02-10 23:51
[quote=LAROBERTE]the downhole cone should never be included in the hole depth[/quote]
I disagree. At work, plenty of time I really, really needed to define the total depth of a blind hole including the drill tip, so it would not punch through the material or would leave minimal thickness. Doing it your way would require guesswork or calculation.

As I said, Solid Edge (a commercial mid-range CAD package) offers ***both*** options. FreeCAD should do the same.

Your other arguments about thread depth and drilling depth are of course to the point. But the Hole feature cannot currently display a modelled thread, and the TechDraw workbench cannot extract hole information nor display it; so implementing this at this time would not really be useful. With 0.18 nearing release I doubt that we will see this implemented before release, which is why I set the target version to 0.19. Unfortunately, there is no longer a developer dedicated to the PartDesign workbench.

---

### Comment by LAROBERTE 2019-02-11 01:13
I agree with you, which is why my first post did not mention a request to add a function. I know that Freecad is evolving, but in the current state of things, the most important is the useful depth of the hole, which is the current standard in technical drawing. if you feel that the cone depth is half a diameter, you will have no problem and it is very easy with a 3D software to see if the cone of the bottom of the hole passes through.
Of course, if the drill cone is a problem, nothing prevents you from making a hole with a flat bottom with a suitable tool.
very cordially

---

### Comment by LAROBERTE 2019-02-12 17:21
Hello
For years, technicians have been working to develop international standards for technical drawing.
If you want freecad to become one of the software that can also be used by professionals, you have to respect them.
The Hole function of freecad is for the moment only the draft, I am sure, of a practical and complete intuitive function. You can add as many functions as you want, but basic functions and their default values ​​must comply with existing standards.
I am willing to participate on a forum to help develop Freecad, this particular function, but I opened this post only to correct this glaring error which will only cause the development of other functions or options for the materialization of the threads of freecad.
I'm not sure if the translation is understandable, I'm really sorry I do not write English directly.
I leave attached sketches that will be more meaningful than me.
Very sincerely
OS: W10 lasted version or UBUNTU 18.10 with virtual box 5.2.26 r128414 (Qt5.6.2)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15806 (Git) or 0.17
Build type: Release
Locale: French/Fr

---

### Comment by LAROBERTE 2019-02-14 14:05
thank you

---

### Comment by uwestoehr 2020-12-01 13:29
Thanks for the report. We are currently fixing all known hole dialog issues, see this forum thread: https://forum.freecadweb.org/viewtopic.php?p=453371#p453371

Should your requested option be the default or not?

---

### Comment by Kunda1 2020-12-03 18:40
LAROBERTE please reply

---

### Comment by uwestoehr 2020-12-13 01:22
> Should your requested option be the default or not?

I checked and asked colleagues, it is indeed the common rule not to take the drill angle into account. Here are some more documents stating the same as the French ones the bug reporter linked:
https://www.technisches-zeichnen.net/technisches-zeichnen/grundkurs-03/gewinde-bemassen.php
https://www.joshuanava.biz/engineering-3/draughting-conventions-associated-with-threads.html

So I will add this option and make it default.

---

### Comment by uwestoehr 2020-12-13 05:21
> So I will add this option and make it default.

Here is the PR: https://github.com/FreeCAD/FreeCAD/pull/4134

---

### Comment by uwestoehr 2021-01-31 00:43
Fixed: commit 7306ed28 ; PR https://github.com/FreeCAD/FreeCAD/pull/4134

**Comment by donovaly** [comment]
Fixed since FreeCAD 0.19 by #4134
