### ISSUE TITLE
Support to update sketch when changing values in a spreadsheet

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5883]
Issue imported from https://tracker.freecad.org/view.php?id=3839

* **Reporter:** wmayer
* **Date submitted:** 2/15/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Support to update sketch when changing values in a spreadsheet. It would be nice to at least  activate the Refresh button so that the sketch can be updated manually.

# Additional information

https://forum.freecadweb.org/viewtopic.php?f=13&t=33614&sid=f6023ab75ecaa26377d3e1472d50cd9c

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
In the current version changing a value in a spreadsheet automatically changes the sketch.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33492 (Git)
Build type: Release
Branch: master
Hash: 6e235a4809e14674aa2cd23e68630b68998a53d4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```
