### ISSUE TITLE
Add and subtract in Arch workbench don't follow object selection order

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5890]
Issue imported from https://tracker.freecad.org/view.php?id=3882

* **Reporter:** brjhaverkamp
* **Date submitted:** 3/4/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

When trying to subtract 2 structures in the Arch workbench, the order in which the 2 objects are selected is not used. Therefore in the attached example there is no way to subtract structure 2 from structure 1.

This is related to forum thread https://forum.freecadweb.org/viewtopic.php?f=23&t=34293 
and possibly to https://forum.freecadweb.org/viewtopic.php?f=23&t=34429 where a similar issue is discussed with the add button in Arch.
I tested this in a couple of the latest builds, currently running

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15998 (Git)
Build type: Release
Branch: master
Hash: 5791c341be797ff2eee99eccac53df71db510fae
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

How to reproduce: open the simplified example file attached.
Select structure 1, ctrl+ select structure 2, hit substract, and you end up with structure 2 minus structure 1.
Selecg structure 2, ctrl+ select structure 1, hit substract, and you end up with structure 2 minus structure 1.
There is no way to create structure 1 minus structure 2 with the subtract function!

File: [example subtract 2.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/8317098/example.subtract.2.FCStd.zip)

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-03-06 00:32
brjhaverkamp Please also confirm in Python3/Qt5 build. Thanks

---

### Comment by brjhaverkamp 2019-03-07 07:24
Hi Kunda1, I hadn't realised the build I downloaded was without QT5/Python3. 
So here the update, I confirm it is also happening in the QT5/Python3 build.
I added a bit more realistic example (example subtract 2) that comes from an actual project I am working on. I want to cutout a stairwell hole in a floor structure. But all I manage is to cut out the floor from the hole structure. Irrespective from which object is selected first and which one is added with Ctrl pressed. 

Mind you that this is _only_ if I use the big blue minus sign button on the arch workbench toolbar. I meanwhile found a workaround by manually adding the subtracting object in the data view of the floor structure. That way it works perfectly. But the minus sign should do the same thing.
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16028 (Git)
Build type: Release
Branch: master
Hash: 9079de7516eca945587e18f6076ec74eb7bd043c
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

---

### Comment by Kunda1 2019-03-07 13:21
brjhaverkamp thank you. BTW, next time you encounter an issue, please open a forum thread dedicated to it first. it's easier and more efficient to get direct help and possibly a bug fix if you first post because the amount of exposure.
 
paullee care to weigh in on this ticket?

---

### Comment by brjhaverkamp 2019-03-08 08:16
Hi Kunda1
The Forum thread is mentioned in my first submission
.
Regis an Roy weight in on the matter and there was quite some discussion on it.

The second thread I mentioned in the initial bug submission looks related in my view, but I could be wrong.

Regards,

Bert

---

### Comment by paullee 2019-03-08 13:41
Hi all, I had checked the thread previously and noted Regis etc. are helping.

See discussion thread - should be a bug.

**Comment by Roy-043** [comment]
This issue has meanwhile been fixed.
See: https://forum.freecadweb.org/viewtopic.php?p=293533#p293533
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.21.31109 (Git)
Build type: Release
Branch: master
Hash: c23ee7ad88433a0f00e84afae0a62fe738be0c09
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
```
