### ISSUE TITLE
Draft _ Delete objects while command is active

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5896]
Issue imported from https://tracker.freecad.org/view.php?id=3904

* **Reporter:** @carlopav
* **Date submitted:** 3/13/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** Draft

# Original report text

Draft _ Delete objects while command is active

# Additional information

https://forum.freecadweb.org/viewtopic.php?f=23&t=34771

# Steps to reproduce

set "when drawing lines set focus on Lenght instead of X coordinate" preference
Draft
Draw a line
Activate a command like move
Press "del"
The entity is deleted and the command crash

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-03-15 22:23
Confirmed in the forum thread

**Comment by Roy-043** [comment]
I can't reproduce this.
```
OS: Windows 8.1 (6.3)
Word size of FreeCAD: 64-bit
Version: 0.20.28765 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
```

**Comment by luzpaz** [comment]
Thank Roy. @carlopav do you mind retesting?

**Comment by yorikvanhavre** [comment]
I can't reproduce either. I think the focus has been fixed a while ago, which now makes the "Del" key delete the input field contents. In any case, the problem is certainly solved.
