### ISSUE TITLE
Manipulating groups in treeview usability improvement

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5899]
Issue imported from https://tracker.freecad.org/view.php?id=3907

* **Reporter:** brjhaverkamp
* **Date submitted:** 3/17/2019
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

I have been extensively working with the Arch workbench for the past couple of weeks.

One issue I had was that my object treeview got scattered with duplicates of object that were also items in other groups. I couldn't  remove them by deleting them, because that also deletes the orignal.
After consulting the forum, I was adviced to install the BIM workbench that has a function "Remove from group" under the left mousebutton. This works great.

An other problem I had was that dragging and dropping objects into groups didn't always work. The target group somehow didn't accept the drop.
However in the Arch workbench there is a Utility-> "Move to Group" function. that works very reliable.

My usability problem now is that I have to switch between Arch and BIM to access these 2 functions when cleaning up my treeview. 
My proposal is to make this Utility submenu item available generally in the LMB menu and add the "Remove from group" function to this utility submenu. This will not only benefit the Arch and BIM workbench but also Part Design and others.

# Additional information

OS: Ubuntu 18.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 2.7.15+
Qt version: 5.11.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Other bug information

* **Priority:** normal
* **Severity:** tweak
* **Category:** Feature
* **Updated:** 8/25/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-06-20 06:36
brjhaverkamp please post this in a forum thread for it to get more visibility, especially since BIM development is very 'hot' right now. This may facilitate this feature being implemented. 

---

### Comment by brjhaverkamp 2019-06-22 06:06
It is discussed (amongst others) in this thread

https://forum.freecadweb.org/viewtopic.php?f=23&t=34166&p=305040&hilit=treeview#p305040

Indeed good to add here for completeness

**Comment by Roy-043** [comment]
In the current version objects cannot be part of more than one group. This should prevent the mentioned problems from occurring in the first place. I am therefore going to close this as stale.
