### ISSUE TITLE
Entering text in Arch annotation is confusing and non-intuitive

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5900]
Issue imported from https://tracker.freecad.org/view.php?id=3908

* **Reporter:** brjhaverkamp
* **Date submitted:** 3/17/2019
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** Arch, Bountysource Potential, Draft, Task View, UI

# Original report text

When adding a text annotation in the Arch workbench, I was not able to create the text object. After entering the text in the single line edit in the task panel, nothing happened. After pressing close, there was no text object.

I consulted the forum and Regis explained that he initially (long time ago) had the same confusion. The trick is to press enter twice. It is possible to enter multiple lines of text and only when entering an empty line at the end, the text object is created.

This is very workable for experienced freecad users, but totally confusing when first using the function. 
Proposal: make the line edit in the task pane a multi-line edit to clearly show it is possible to enter multiple lines and add an OK button to confirm the action.
This would be more clear and userfriendly.

# Additional information

OS: Ubuntu 18.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 2.7.15+
Qt version: 5.11.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Other bug information

* **Priority:** normal
* **Severity:** tweak
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by vocx 2019-03-18 21:47
First of all, the annotation tool is part of Draft, not Arch. So strictly speaking this should be classified in Draft.

Second, the behavior of double Enter is documented in the wiki and in the offline documentation included with FreeCAD.

https://www.freecadweb.org/wiki/Draft_Text

However, I agree that the behavior is not intuitive, and should probably be changed as you describe.

---

### Comment by Kunda1 2019-03-20 18:53
brjhaverkamp please discuss this on the forums. We ask users do this (per the large annoying yellow banner at the top of every page of this bug tracker) per our guidelines. Thanks

---

### Comment by brjhaverkamp 2019-03-20 20:42
Hi Kunda1,

Of course I read the yellow banner. And indeed it is common practice. Only missed linking the bugreport the thread and vice versa. Here is the link.
https://forum.freecadweb.org/viewtopic.php?f=23&t=34934

I realise this is probably not high on the list of improvements. But I wanted to make sure that if someone wants to attack the low-hanging fruit, it is in the system. 

Regards,
Bert

**Comment by Roy-043** [comment]
Since version V0.19 a multi-line text can be entered and there is a "Create text" button in the task panel.
