### ISSUE TITLE
Arch remove does not work correctly for creating subtractions/holes

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5901]
Issue imported from https://tracker.freecad.org/view.php?id=3909

* **Reporter:** brjhaverkamp
* **Date submitted:** 3/17/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

As discussed in forum thread https://forum.freecadweb.org/viewtopic.php?f=23&t=34747
Arch_subtract gives misalligned results when one of the objects has an offset. 

In the added example this is the case where I subtracted "Thick roof dormer holes" from Thick roof for cutting walls" The roof is raised by .80m compared to the sketch and it looks like this is not taken correctly into account.

A second problem seems to be that nesting subtractions doesnt work correctly.
In the added example I subtract "Thick roof for cutting walls" from "Interior walls. This works correctly, except for the places where the dormer holes should have kept the Interior walls intact.
Apparently the "Thick roof dormer holes" are not taken into account in this subtraction.

# Additional information

OS: Ubuntu 18.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 2.7.15+
Qt version: 5.11.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

See attached example

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by paullee 2021-01-18 23:02
Similar / related Forum Discussion-

1.  [Arch Window create Wrong Opening Position Bug?](https://forum.freecadweb.org/viewtopic.php?f=23&t=28247&hilit=wall+opening)
2.  [Copying and moving a window to opposite wall](https://forum.freecadweb.org/viewtopic.php?f=3&t=54328)

---

### Comment by Roy_043 2021-01-20 10:20
The reported bug has already been fixed:
https://github.com/FreeCAD/FreeCAD/pull/4054

**Comment by luzpaz** [comment]
Per @Roy-043 this has been fixed in #4054 (e06e3d7bb6e779170012aa5174e4b1ea0bc7bf2a)
