### ISSUE TITLE
sketch lost tangent constraint using trim

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5902]
Issue imported from https://tracker.freecad.org/view.php?id=3910

* **Reporter:** Jee-Bee
* **Date submitted:** 3/17/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** Sketch, Tangent

# Original report text

Trim function in sketcher removes (wrong) constraint with tangent lines.

# Additional information

OS: OS X El Capitan (10.11)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14976 (Git)
Build type: Release
Branch: (HEAD detached at e79a19828)
Hash: e79a19828e2e92269ff96110dfeadaa245ad17c2
Python version: 2.7.15
Qt version: 5.11.2
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: English/Netherlands (en_NL)

Also at windows but don't know with version

# Steps to reproduce

1. New part
2. create new sketch
3. add a line and a arc
4. make arc and line tangent
5. force that line and arc have overlap (both have to much length
6. trim overlap
7.  end with coincident/ point on entity and tangent is lost

see https://forum.freecadweb.org/viewtopic.php?f=8&t=34774&start=20#p293117
and https://forum.freecadweb.org/viewtopic.php?f=8&t=34774&start=20#p293495

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by harrygeier 2019-03-19 13:12
I can verify that . It´s even more strange as the constraints still are existing, but do not act on the elements

---

### Comment by Kunda1 2019-03-20 18:48
Marking issue 'Confirmed'
BTW Jee-Bee did you mean to tag as 'Tangent' (instead of 'tangend') ?

---

### Comment by Jee-Bee 2019-03-21 06:18
Kunda1 you right i have updated the Tag.

**Comment by Roy-043** [comment]
This has been fixed in the version listed below:
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33492 (Git)
Build type: Release
Branch: master
Hash: 6e235a4809e14674aa2cd23e68630b68998a53d4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```
