### ISSUE TITLE
Path Stock using Existing Solid not maintaining state

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5904]
Issue imported from https://tracker.freecad.org/view.php?id=3914

* **Reporter:** sliptonic
* **Date submitted:** 3/20/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

When the user chooses to use an existing solid as the stock object for a Job, the behaviour is inconsistent and confusing.

1) The user selects 'use existing solid' from the combobox.
2) The user picks the solid from the list of available choices.
3) If the user presses 'refresh' at this point, the choice to use existing solid remains but the selected solid switches to the first one in the list.

4) If the user selects a solid (other than the first) and then closes the Job task panel, everything is fine.  But if the Job is re-opened, the selected solid switches back to the first in the list again.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by gauna 2020-12-13 19:55
PR:

https://github.com/FreeCAD/FreeCAD/pull/4140

---

### Comment by gauna 2021-01-27 17:30
Fix committed to master branch.

**Comment by sliptonic** [comment]
Not sure why this didn't close.  It seems to be resolved.
This PR adds a little bit to avoid an unnecessary error being displayed in the console and reverts an incorrect tab selection in the Path Edit dialog.
