### ISSUE TITLE
Text (Annotation) moves greatly when placement edited.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5908]
Issue imported from https://tracker.freecad.org/view.php?id=3924

* **Reporter:** Geoplace
* **Date submitted:** 4/4/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

The place where the Text (annotation) are shown is disproportionately modified even when the placement has been edited by 1mm.

The placement edition of one Text note affects others notes, even when you edit a windows placement it also distorts Text showed in the 3D space.

OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0

# Additional information

The text placement parameters stay the same. Lucky when we save and reopen the file its Texts takes the correct place. 

The same happen in the Linux OpenSuse Version 0.18. And Windows v 0.19.
OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16267 (Git)
Build type: Release
Branch: master
Hash: ddb335cfe057336f1958d68126bb0471328d735c
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0

It's an annoying bug because when you have a larger file that takes times to load, the open-close workaround to see the correct result would waste a lot more time.

Here is the link to the forum with steps with images:
https://forum.freecadweb.org/viewtopic.php?f=8&t=35307

Here is a test file you just need do the step 6 to see the bug.

# Steps to reproduce

1.- Open FreeCAD v18 . Switch to Arch workbench.
2.- Create a Rectangle and make face false. (Being in the default top view)
3.- Create Text (Annotations) one at each corner of the rectangle.
4.- Use the wall tool in the rectangle to get walls.
5.- Use windows tool and insert one at the front wall.
6.- Change the windows (or text) placement parameter by opening it from the properties/data window and edit for example de X axis by 1mm. Clic Apply or OK.
7.- Now the texts go far away, at least 3 of them. The recompute don’t fix its shown positions.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/11/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-02-11 17:13
Re-added attachment as the previous one was corrupted somehow.   
[Prueba Annoation Windows wall-wind.FCStd.gz](https://github.com/FreeCAD/FreeCAD/files/11240792/Prueba.Annoation.Windows.wall-wind.FCStd.gz)

**Comment by Roy-043** [comment]
Bug cannot be reproduces, either in V0.18 or V0.21. I'll therefore close this.

```
OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 32-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: Dutch/Netherlands (nl_NL)
```
