### ISSUE TITLE
Meshing should be non blocking or at least has a progress bar/log output

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5914]
Issue imported from https://tracker.freecad.org/view.php?id=3933

* **Reporter:** @joha2
* **Date submitted:** 4/13/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** FEM

# Original report text

Referring to the forum thread https://forum.freecadweb.org/viewtopic.php?f=18&t=35480

joha2:

The meshing with gmsh or netgen or other external meshers is blocking. Is it possible to perform these subprocesses in a non-blocking manner or at least - if this is not possible - with a process indicator and a cancel button?

bernd:

very good point. Same on import of large ifc files. For ccx or gmsh it is simple. Since they are external programms, just kill them. This is not smart but works quite well. For netgen some break button would be cool.

joha2:

Yes, killing gmsh would be possible. But when I perform the meshing of a complicated part, I never know what gmsh actually does (some logging would be nice) or whether it is frozen. Further meshing of a part is independent from other things you can do in FreeCAD. Therefore it would be nice to execute gmsh independently from the rest of FreeCAD. Some cancel button is possible, but some intermediate feedback is maybe not so trivial.

bernd:

In the regard of gmsh you are totally right. I have had a look into this myself some time ago. Feel free to make a bug report and asign it to me. Something in the regard of process logging for gmsh.

# Additional information

Not applicable

# Steps to reproduce

* Select Part workbench
* Create part (e.g. Cube)
* Select FEM workbench
* Mesh part (GMSH) with MaximumLength 0.001
* Wait a looooong time

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 3/21/2021

# Discussion from Mantis ticket

### Comment by @joha2 2019-04-18 21:19
I just compiled the gmsh binary with `cmake -DENABLE_OPENMP=1 -DENABLE_MPI=1`. This improves the speed of the process by using `gmsh -nt $(nproc)` [I don't know the windows equivalen]. For large meshes, it might be useful to save the mesh to a .med file instead of .unv. What do you think bernd?

---

### Comment by @luzpaz 2021-03-21 11:18
CC @berndhahnebach

**Comment by luzpaz** [comment]
Related #5566
