### ISSUE TITLE
Using "Tab" to cycle thru properties, go up to the first once we get to the last.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5918]
Issue imported from https://tracker.freecad.org/view.php?id=3942

* **Reporter:** freedman
* **Date submitted:** 4/22/2019
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** keyboard, shortcuts, UI

# Original report text

The "Tab" key works to cycle thru properties but when it gets to the last property it stops there. It would be best if it goes back to the first property, hince the feature request.

It appears to work differently in Part, that's why i'm targeting Part Design.

# Additional information

OS: Windows 7
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 +17 (Git)
Build type: Release
Branch: (HEAD detached at 0.18.1)
Hash: f7dccfaa909e5b9da26bf50c4a22ccca9bb10c40
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

Use the "Tab" to cycle thru properties.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-05-09 13:32
freedman moving forward, please use a py3/qt5 0.18/0.19_pre builds 
Thanks

**Comment by Roy-043** [comment]
The requested functionality is available in recent versions (V0.21 for example).
