### ISSUE TITLE
Disable auto hide solid option when entering Sketch edit mode sets and leaves solid hidden

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5919]
Issue imported from https://tracker.freecad.org/view.php?id=3943

* **Reporter:** jmaustpc
* **Date submitted:** 4/24/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

In PartDesign, if you enter edit mode of a feature's sketch, by default the solid will be set to hidden so that the solid will not obscure the sketch. There is a property of the sketch to disable this feature as well as a setting in preferences to change the default value of that property. 

When the property is set to disable this auto hide function, FreeCAD still hides the solid and also leaves the solid hidden when you close sketch edit mode. 

The first feature seems to work correctly but subsequent features show this bug.

https://forum.freecadweb.org/viewtopic.php?p=303218#p303218

# Additional information

OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.1.
Build type: Release
Python version: 3.6.7
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/Australia (en_AU)

# Steps to reproduce

In the file attached, try toggling the "Hide Dependent" property of the three sketches then double click so that the sketch goes into edit mode. 

The first sketch will hide or not hide the solid and then if it was hidden it returns it to visible after closing sketch edit mode.  

however the subsequent sketches when "Hide Dependent" is set to false, 1) the feature related to that sketch is firstly hidden anyway, and then when edit mode is closed, the solid remains hidden 

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Kubuntu 18.04**
* **Platform:** AMD64
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
The problem no longer occurs in the version listed below:
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33492 (Git)
Build type: Release
Branch: master
Hash: 6e235a4809e14674aa2cd23e68630b68998a53d4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```
