### ISSUE TITLE
Part-Container: Moved Part container with objects,  shapeblinder links to nothing

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5921]
Issue imported from https://tracker.freecad.org/view.php?id=3948

* **Reporter:** seppelw
* **Date submitted:** 4/27/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

When having Objects within a moved part-container, it is not possible to create a shapebinder that is automatically linked to the object implicitly moved by the part-container.

https://forum.freecadweb.org/viewtopic.php?f=3&t=35938

# Steps to reproduce

 1) Add 3 Solids, Cube, Cylinder, Cone
 2) Place each in an individual part
 3) Move the parts 
 4) Add a new Body
 5) Add Facebinders to the Objects
Result) The Facebinder is not linked tot he object in the part-container.

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **OS: Windows 7 and 10**
* **Platform:** x86 64 Bit
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-04-27 11:50
Please always add you ***Help > About FreeCAD > Copy to clipboard*** info to any ticket, per our guidelines (yellow banner top of page)

---

### Comment by seppelw 2019-07-14 19:28
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

---

### Comment by openBrain 2019-07-15 16:46
seppelw this version is outdated (even in the 0.18 branch) so no real interest to confirm bug with it.
For ones landing here, you can give a try to [PlacementAbsolufy Macro](https://www.freecadweb.org/wiki/Macro_PlacementAbsolufy) that will reset Part containers to origin of Global Coordinate System while preserving objects position.

**Comment by adrianinsaval** [comment]
from the discussion I think this issue can be closed, shapebinders woks as expected. There's an argument to be made about having TraceSupport default to true or not but it's clear that it's working as intended and this statement is simply not true:

> When having Objects within a moved part-container, it is not possible to create a shapebinder that is automatically linked to the object implicitly moved by the part-container.

For the record I agree TraceSupport=true is a better default. Subshapebinder defaults to this behavior (but the property that appears to control this is called Relative instead for whatever reason). I don't care much for shapebinder anyways as IMO it should be deprecated in favor of subshapebinder.
