### ISSUE TITLE
Possible conflict between QT and Opengl, titlebar overlaps menubar

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5924]
Issue imported from https://tracker.freecad.org/view.php?id=3956

* **Reporter:** Phalax
* **Date submitted:** 5/2/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** feedback
* **Tags:** 

# Original report text

* Titlebar overlaps menubar
* Mouse alignment is not correct
* Working area is blurry

Found fix here i think: https://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows

Blender (2.8) have the same problem, there for this is maybe something else.

# Additional information

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16388 (Git)
Build type: Release
Branch: master
Hash: 473f7ff0113a0f059a832fb74e4e050a12215d3c
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Swedish/Sweden (sv_SE)

# Other bug information

* **Priority:** normal
* **Severity:** tweak
* **Category:** Bug
* **Updated:** 9/16/2021

# Discussion from Mantis ticket

### Comment by chennes 2021-08-25 03:47
The image attached to this report does not seem to work anymore: is there a forums discussion? It looks like the fix is straightforward if this problem is still happening.

---

### Comment by chennes 2021-09-16 03:51
Phalax can you reconfirm this issue, and upload a new version of your screenshot (which seems to have gone missing at some point here)?

**Comment by luzpaz** [comment]
Closing this ticket as OP has not responded. 

CC @chennes JFYI
