### ISSUE TITLE
freecad help broken (in general on every platform)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5926]
Issue imported from https://tracker.freecad.org/view.php?id=3960

* **Reporter:** Kruthers
* **Date submitted:** 5/4/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** assigned
* **Tags:** appimage, documentation, Qt, upstream

# Original report text

The help menu item plus all attempts to use the "Whats this" tool fail with the error:

Unable to launch Qt Assistant (/home/travis/build/FreeCAD/FreeCAD-AppImage/conda/linux_stable/AppDir/usr/bin/assistant)

X-posted to github: https://github.com/FreeCAD/FreeCAD-AppImage/issues/25

# Additional information

appimage file: FreeCAD_0.18-16110-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage

OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16110 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.18.1)
Hash: f7dccfaa909e5b9da26bf50c4a22ccca9bb10c40
Python version: 3.6.7
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

Hit "F1"

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by kkremitzki 2019-06-17 21:03
I'm not maintaining the appimage ATM so this would probably be better assigned to someone else.

---

### Comment by Kunda1 2019-07-03 17:48
Pressing F1 I see
> FreeCAD help files not found (/tmp/.mount_FreeCAvVNccw/usr/doc/freecad.qhc). You might need to install the FreeCAD documentation package.

OS: Manjaro Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.17175 (Git) AppImage
Build type: Release
Branch: master
Hash: 507c40669d48ae4732268324cd0140c80cf68222
Python version: 3.7.3
Qt version: 5.9.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

---

### Comment by Kunda1 2019-08-23 02:43
Follow progress on https://github.com/FreeCAD/FreeCAD-AppImage/issues/25
triplus do you mind closing this ticket as well when the above github issue is closed ?

**Comment by luzpaz** [comment]
Closing in favor of #6514
