### ISSUE TITLE
Security Audit of 0.20

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5934]
Issue imported from https://tracker.freecad.org/view.php?id=3983

* **Reporter:** Kunda1
* **Date submitted:** 5/19/2019
* **FreeCAD version:** 
* **Category:** General
* **Status:** new
* **Tags:** #ready-for-migration

# Original report text

Using flawfinder 2.0.8 I've generated the attached report for consideration.

This issue has been set to 'private'. 

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** General
* **Updated:** 2/3/2022

**Comment by adrianinsaval** [comment]
@luzpaz what to do with this one?

**Comment by luzpaz** [comment]
Keep it open for when we announce a feature-freeze and I'll run another audit  for v0.20dev

**Comment by donovaly** [comment]
FreeCAD 0.20 is out. if there should be an audit, just do this and make a new PR or open a forum thread in the development section.
