### ISSUE TITLE
Shortcut buttons for primitive shapes are not highlighted when active

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5939]
Issue imported from https://tracker.freecad.org/view.php?id=3996

* **Reporter:** bzb.dev001
* **Date submitted:** 5/31/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

In sketcher workbench. When user click on a shortcut button for primitive shapes(eg. line, arc, circle, etc), the button should change to indicate that it is currently active.

# Additional information

OS: Ubuntu 18.04.2 LTS (LXDE/Lubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16854 (Git) AppImage
Build type: Release
Branch: master
Hash: fe0fd5512ba9a8a9c729cdc47af35bbe965050ac
Python version: 3.7.1
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/Canada (en_CA)

# Steps to reproduce

Create new document
create body
create new sketch
select plane for sketch
click on a shortcut button for one of the sketch primitives(eg. line,arc,circle,etc)
notice the button remains the same. The button should change to indicate that the selected primitive is currently active.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 8/25/2021

**Comment by Roy-043** [comment]
There is an icon attached to the cursor that already provides information about the active sketcher command. Buttons are not highlighted in other workbenches either BTW. So the requested feature would introduce an inconsistency. Closing this (won't fix).
