### ISSUE TITLE
Renaming spreadsheet no longer has any affect on field tags.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5943]
Issue imported from https://tracker.freecad.org/view.php?id=4003

* **Reporter:** grog
* **Date submitted:** 6/6/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** new
* **Tags:** spreadsheet

# Original report text

I have one computer with v0.17 and I can reliably change the Spreadsheet.  Typically I rename it to 'S' for less typing.  On my other computer which I just upgraded to v0.18 I can no longer reference tags by my typical S.tagname.  I have to state Spreadsheet.tagname.  I marked it as major as it's serious enough for me to downgrade to regain the functionality.

# Additional information

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16110 (Git)
Build type: Release
Branch: (HEAD detached at upstream/releases/FreeCAD-0-18)
Hash: f7dccfaa909e5b9da26bf50c4a22ccca9bb10c40
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

1. new file
2. Select Spreadsheet workbench and click on the spreadsheet icon to create a new spreadsheet.
3. Select spreadsheet on navigation window.
4. type:  F2 - S  (To rename the spreadsheet to 'S')
5. enter a number in a cell
6. [CTRL][SHIFT]a - <cell tag name>
7. now switch to Part workbench
8. create a primitave part
9. select one of it's dimensions, 
10. click on the calculation icon, and enter S.tagname. (This fails in v0.18 but works in v0.17)
11. now try Spreadsheet.tagname (This works)

Thanks for an awesome program.
GROG

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **OS: Windows 10 1803**
* **Platform:** PC
* **Updated:** 11/24/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-06-06 14:30
Moved to Expressions category.
grog Please x-post this to the freecad forum to validate by the community (per our guidelines in the large yellow banner at the top of this page)

---

### Comment by wmayer 2019-06-07 10:45
Forum link: https://forum.freecadweb.org/viewtopic.php?f=3&t=36877

According to the replies there you have to write `<<S>>` instead of `S`.

---

### Comment by Kunda1 2019-06-19 22:34
Per openBrain this seems to look like a dupe of #3379

---

### Comment by grog 2019-08-25 14:55
Thus far the answer is to avoid problem characters for naming.
Is there a simple way to change the Spreadsheet name and adjust the references to it? I created a nice collection of documents that can't be read in newer versions because of this bug.

**Comment by adrianinsaval** [comment]
can anybody edit the text and remove the strike-through? Looks like some symbols used there resulted in md interpreting it like that
