### ISSUE TITLE
Dogbone locks up on path with two surface elements

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5944]
Issue imported from https://tracker.freecad.org/view.php?id=4009

* **Reporter:** freman
* **Date submitted:** 6/6/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** #tobeclosed, dogbone

# Original report text

As discussed here, if two sufraces are selected to for a milling path and dog-bone is applied it locks up totally. This does not seem to happen with a single geometry. 

https://forum.freecadweb.org/viewtopic.php?f=15&t=36832

Freecad file demonstating problem. 
https://forum.freecadweb.org/download/file.php?id=85053

# Additional information

OS: Linux (LXDE/LXDE)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16854 (Git)
Build type: Release
Branch: master
Hash: fe0fd5512ba9a8a9c729cdc47af35bbe965050ac
Python version: 2.7.15
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

# Steps to reproduce

select two surfaces
add face mill path 
add dog bone dress-up
kill FreeCAD process
rince and repeat. ;)

# Other bug information

* **Priority:** normal
* **Severity:** crash
* **Category:** Bug
* **Updated:** 1/26/2022

# Discussion from Mantis ticket

### Comment by sliptonic 2019-06-11 01:51
The description is not quite accurate.  A dogbone dressup works fine with two separate faces.  The problem is unique to this shape.  

Increasing the radius of the circular middle tier so that it overlaps the lower square resolves the error.  (see attached negtest3 file)

---

### Comment by Kunda1 2020-01-08 18:24
Any conclusions on this ticket?

---

### Comment by Kunda1 2022-01-22 22:09
sliptonic I've tagged this #tobeclosed
Can you let me know if anything needs to happen before closing this ticket?

---

### Comment by sliptonic 2022-01-25 15:00
Good to close.

---

### Comment by fremen 2022-01-26 07:09
What is the motivation to close this before the bug is fixed ? 
Of course there a specific set of conditions which triggers the bug.That is the case with most bugs which don't get caught in initial testing. 
Dogbone is fine mostly. 

I cannot re-examine the FCStd file attached because the link no longer works but from the description it a work around. It is not showing that the original geometry was invalid in some way or that it will not be reproduced in the future.

The whole point of this test piece ( based on on ISO standard for testing CNC machine accuracy ) is that the circle diameter is identical to the side of the square. So the proposed "solution" negates the point of the part. Maybe the ISO standards should be changed so we don't need to fix FreeCAD ?

---

### Comment by sliptonic 2022-01-26 15:27
Lots of reasons to close an issue.  Lack of interest is one.  If the issue isn't getting attention, even by the original poster, then it's not likely to be taken seriously by a developer.

If this is still an issue for you, we can leave it open

---

### Comment by fremen 2022-01-26 15:38
The bug seems legitimate and not disputed. It should stay open until it gets fixed, o/w not much point in having a bug tracker and taking the trouble to report defects. 

It's unfortunate that the internal changes in FC mean the original file no longer works. But the cause seems clearly identified.

**Comment by sliptonic** [comment]
Closing due to lack of interest.  The original test file is wildly out of date.  It has no dogbone dressup in it.  
Dogbone dressup is designed to work on profiles, not pockets. 
If OP wants to reopen the issue, we need a recent test shape demonstrating the problem.
