### ISSUE TITLE
untrapped file error on start up due to spacenavd

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5947]
Issue imported from https://tracker.freecad.org/view.php?id=4020

* **Reporter:** freman
* **Date submitted:** 6/14/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

Due to manual changes to file ownerships, some file has become a problem when starting FreeCAD.  However, the error does not seem to be trapped at the point where the file is accessed and just bubbles up to be caught as an untrapped error which is so general as to not be any help in identifying and resolving the problem 

https://forum.freecadweb.org/viewtopic.php?f=3&t=37021&p=314367#p314367

```
connect failed: No such file or directory
Unhandled std::exception caught in GUIApplication::notify.
The error message is: Permission denied
```

An error report which stated the full file path and name would allow this to be fixed immediately. 

It seems that whatever function is attempting this file access is not trapping any file access errors and assumes it always works. 

While the cause in this case is outside FreeCAD, it seems it should trap any errors in file access. 

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by freman 2019-06-14 07:26
OS: Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15303 (Git)
Build type: Release
Branch: master
Hash: 6199c95fd71eacb9cc168426e55254aa79a42034
Python version: 2.7.15
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

---

### Comment by openBrain 2019-06-14 16:03
freman as required in the bug submission guidelines, could you please confirm bug is still present in the latest release version (yours is outdated) ?
If possible, could also provide a way to reproduce the issue ?

---

### Comment by freman 2019-06-14 17:16
yes, still present on new build of 0.19 master today. 

However, as discussed in thread, there are two things happening here. The file permissions problem disappeared after a reboot, so the cause will be undetermined unless it happens again. 

the other connection message seems to be be LVM related coming from Qt. It is probably banal. 

This still reflects the need for better error trapping at a lower level, though it will not be possible to work out exactly where in this case until and unless it reoccurs. It seems some file access was being attempted without the success being tested. Knowing what file it was would have enabled it being resolved in minutes instead of not detected properly after hours. 

If I see it again , I will report back.

---

### Comment by cbruner 2020-07-22 14:05
While going through https://tracker.freecadweb.org/view.php?id=4351#bugnotes found this error as well. Using wmayer's comments in https://forum.freecadweb.org/viewtopic.php?t=37021 I modified the FreeCAD/src/Gui/GuiApplication.cpp to have Base::Console().Error("Event type: %d, receiver: %s\n", (int)event->type(), receiver->metaObject()->className()); at the exception handling areas.
(made no difference). 
starting it with QT_QPA_PLATFORMTHEME=gtk3 QT_DEBUG_PLUGINS=1 ./bin/FreeCAD --write-log produced the attached file.
OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22108 (Git)
Build type: Unknown
Branch: master
Hash: 886d9656f0c4ccfd016e373f74cc2dde965d88e1
Python version: 3.6.9
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/Canada (en_CA)

**Comment by luzpaz** [comment]
This has been addressed
