### ISSUE TITLE
Pocket operation yields invalid result with "Refine = True"

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5949]
Issue imported from https://tracker.freecad.org/view.php?id=4029

* **Reporter:** fabrico
* **Date submitted:** 6/19/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

Certain pocket geometries yield invalid results with missing surfaces or distorted shapes when their "Refine" property is set to "True". See examples in the forum thread for details.

[forum thread](https://forum.freecadweb.org/viewtopic.php?f=3&t=37101)

# Additional information

OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.1.
Build type: Release
Python version: 3.6.7
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

Use Part Design Workbench in the provided file.

Behavior1:
1) Open the attached file.
2) Create a new sketch on the front face of the part.
3) Draw a circle somewhere on the face of the part.
4) Close the sketch.
5) Attempt to create a pocket with the sketch.
6) The part disappears.
7) Cancel the pocket task.
8) Hover over "Body" in the tree.
9) An error message appears: "Tip shape is empty (but must be executed)"

Behavior2:
1) Open the attached file.
2) Right click on "SubtractivePipe" in the tree.
3) Select "Set tip".
4) Create a new sketch on the front face of the part.
5) Draw a circle somewhere on the face of the part.
6) Close the sketch.
7) Attempt to create a pocket with the sketch.
8) The pocket is created.
9) Click OK for the pocket task.
10) No error is evident.

openBrain's posted reply revealed that the part had a missing surface before the attempted pocket. This missing surface is the evidence of the bug.

---

openBrain : it seems user level root cause is that setting "Refine=True" on the CableSlitPocket in the example file fails (a face vanishes leading to an invalid solid). Setting "Refine=False" solves the problem.
Moreover, despite step 3 of Behavior2 may prevent the bug to happen, there is still a missing face.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Ubuntu 18.04.2 LTS**
* **Platform:** AMD64
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by openBrain 2019-06-19 10:57
fabrico : I added some details in your ticket so devs hopefully don't have to go to the forum to get a basic understanding of the possible cause. Hope you're OK with that. ;)

**Comment by grubertechnic** [comment]
Some notes about this ticket.

The file RefineBug_kiss.FCStd works flawless (already for a long time).

[RefineBug_kiss.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11951253/RefineBug_kiss.FCStd.zip)


The file test.FCStd still have some small issues.

 - the missing face on the circle is gone in PartDesign
 - the faces of the sweep (plane even it is a sweep)  and pocket do not refine (red and green arrow)
 - the plane of the sweep (green arrow, on both sides) have a shape tolerance of ~1.0 * 10^-6 (also before the pocket)
 - the profile of the sweep have a bad quasi tangency, correct it to an real tangency does not help
 - replace the profile with a rectangle makes ~1.0 * 10^-7, but still does not refine

![2023-07-04_18-57](https://github.com/FreeCAD/FreeCAD/assets/109620914/ebddf164-0c49-45ac-a283-a5ab721ab593)

 - when make a refined object out of it from the PartWB (PartWB --> Menu --> Part --> Create a copy --> Refine shape) refine the planes, but the missing circle face reappear, intepended how the sweep is made

![2023-07-04_19-15](https://github.com/FreeCAD/FreeCAD/assets/109620914/9bfd06a6-7419-494f-997c-bb4f66e84a14)

[test.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11951387/test.FCStd.zip)
