### ISSUE TITLE
Translations of External workbenches need to be incorporated in to Crowdin (import/export) translation scripts

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5952]
Issue imported from https://tracker.freecad.org/view.php?id=4033

* **Reporter:** Kunda1
* **Date submitted:** 6/22/2019
* **FreeCAD version:** 
* **Category:** General
* **Status:** assigned
* **Tags:** translation

# Original report text

The following workbenches

* BIM Workbench
* Ship workench
* Plot workbench
* and others (WBs and Macros) in the future
need to be incorporated in to the Crowdin python scripts since they are now external to FreeCAD master (aka out of core).
The script needs to pull their translations in to Crowdin and then export them back out. Perhaps this also involves creating automatic PRs or else the script has commit access to said workbenches and auto-commits the translations. 

Not sure exactly what the right solution is, but nevertheless, something needs to be done. Especially since more and more workbenches will opt to be translated in the future (now that yorik figured out how said workbenches and macros can utilize Qt translation methods and recently posted on how to do this)

# Other bug information

* **Priority:** high
* **Severity:** major
* **Category:** General
* **Updated:** 2/6/2021

**Comment by yorikvanhavre** [comment]
External addons translations are now handled on https://crowdin.com/project/freecad-addons . They must (if they wish so) implement their own script (there is an example to take and adapt). Everything is explained on https://wiki.freecadweb.org/Translating_an_external_workbench so I think this issue can be closed?
