### ISSUE TITLE
Job | Tool editor  does not get keystrokes when mm/s items are selected.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5954]
Issue imported from https://tracker.freecad.org/view.php?id=4036

* **Reporter:** freman
* **Date submitted:** 6/25/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

when attempting to input cutting speeds into Job edit | Tools tab, keystrokes go to 3D view window and change the view. Annoying and confusing. 

BTW, these columns do not have meaningful headers. "mm/s" is not the quantity being input, it is the units. User is left to guess which is XY cutting speed and which is Z cutting speed.  Space if tight but the unit is not the right text for the header. 

# Additional information

OS: Linux (LXDE/LXDE)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.17119 (Git)
Build type: Release
Branch: master
Hash: e72b48e0cfcf4773e4b6527c74f2bac11ccff1ab
Python version: 2.7.15
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

# Steps to reproduce

create a job 
set 3D view to isometric
go to edit job
select tool edit tab
click once is one of the "mm/s" text entry boxes
note text entry is dark blue indicating it is selected and should recv. keyboard focus
type numeric key 6
note 3D view jumps to different view 
type numeric key 2
note 3D view jumps to different view
type numeric key 8 ( out of range of view numbers )
note digit is entered in edit box as expected.

Clearly the keyboard events are going initially to the 3D window, it this does not catch the event it is passed to the active editbox.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 8/25/2021

# Discussion from Mantis ticket

### Comment by openBrain 2019-06-25 18:59
freman : could you please at least precise which WB you're using ? ;)

---

### Comment by freman 2019-06-25 20:16
Sorry, isn't Job and Job Edit specific to Path?

**Comment by sliptonic** [comment]
Nothing to fix.  Everything appears to work correctly.
Single clicking in the columns only selects the column, it does not open for edit.  Double clicking sets the field for input.

PR makes headers less ambiguous.  https://github.com/FreeCAD/FreeCAD/pull/6530
