### ISSUE TITLE
Linear and Polar Transform Tools apply the wrong failure criteria to Transforms and needlessly fail

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5964]
Issue imported from https://tracker.freecad.org/view.php?id=4048

* **Reporter:** FreeCAD97990
* **Date submitted:** 7/2/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Hi this is a bug that I have been aware of for the last 18 months or even longer. It happens with ALL the development releases that have been made over the last 18 months. 

I have over that time posted two forum threads describing the bug, but have got very little response.

My second (and probably better) thread:

https://forum.freecadweb.org/viewtopic.php?f=8&t=33742

My first thread:

https://forum.freecadweb.org/viewtopic.php?f=3&t=23222

# Additional information

The problem occurs with all FreeCAD release and development versions!!!!!!!!!!!
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.17201 (Git)
Build type: Release
Branch: master
Hash: 20b78fca97e21473716c7fc13cb4acc9afe4710a
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: English/UnitedKingdom (en_GB)

# Steps to reproduce

Run the four files below, the first two for Polar Transformation and the second two for Linear Transformation. In each case, one of the transformation fails and the other succeeds.

In 'Polar Transformation Failed', go to the Tree View and select Edit Polar Pattern. You can see that the transformation has failed because one of the Pocket features (in red) has not intersected the Pad Plate.
In 'Polar Transformation Succeeded', go to the Tree View and the transformation has succeeded. You can see that the Pocket Feature (the same one that was in red before) is now Sketched longer and it just intersects the Pad Plate. So no error!!!!!

The two Linear Transformations files work in exactly the same way.

The operation of the Linear Transformation and Polar Transformation Tools is described in the Users Documentation Help Files: 

PartDesign LinearPattern
Limitations
Any pattern shapes that do not overlap the original's support will be excluded. This ensures that a PartDesign feature always consists of a single, connected solid

PartDesign PolarPattern
Limitations
See linear pattern feature limitations

The reason for this bug is that these limitations are WRONG!

If the pattern shapes are Pads, then YES!, any pattern shape that does not overlap the original's support should be excluded to ensure that a Part Design Feature always consists of a single, connected solid.

BUT.... If the pattern shapes are Pockets, then any pattern shape that does not overlap the original's support should be INCLUDED because it CANNOT cut the original support into two pieces. It is therefore 'safe'!!!!

The Linear (and Polar) Pattern Tools should both be changed to:

Limitations
Any ***Pad*** pattern shapes that do not overlap the original's support will be excluded. This ensures that a PartDesign feature always consists of a single, connected solid.

You may think that there is no real bug here - that it does not cause much of a problem because you can use some sort of workaround. But I have been designing, over the last 2 years or so, graduated plates with cut-outs that are always causing Polar Pattern to fail. So I use two (or more) Polar Patterns to do the job. And then the cut-outs need to change.... It's very time consuming and non-parametric!!!! 

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Platform:** Windows 10
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by FreeCAD97990 2019-07-03 18:23
Please note that where I have written 'Pad pattern shapes' in the above bug report this really would refer to any Additive Feature that is selected to be Linear Patterned or Polar Patterned. I think these are Pad, Revolve, Additive Loft, Additive Sweep, or any Additive Primitive.

In the User Documentation Help Files, it would probably be clearer to refer to 'Additive Pattern Feature' rather than 'Additive Pattern Shapes'.

And where I have written 'Pocket pattern shapes' this really would refer to any Subtractive Feature that is selected to be Linear Patterned or Polar Patterned. I think these are Pocket, Hole, Groove, Subtractive Loft, Subtractive Sweep, or any Subtractive Primitive.

Of course, the Linear and Polar Pattern Tools can both be used to pattern not just a single feature, but a list of several features, some of which might be Additive, and the others Subtractive. Some thought needs to be given regarding the order in which the Patterning and the intersection test is applied where several features are involved. Possibly do all the Additive Features first, followed by the Subtractive Features? Or perhaps just in the order selected by the FreeCAD user, to give the user more control and allow him to re-order them to his best advantage?

Finally,maybe the Mirror and Multitransform Tools have these same problems too.

---

### Comment by jmaustpc 2020-10-30 05:21
This is not a bug, it is deliberately intended designed behavior. It is certainly not worthy of a "blocking" priority.  

It is just that a Body must be a single contiguous solid. How pattern features should behave when some or all of its elements don't intersect with the solid is a matter for discussion that may or may not result in any change to the current behavior. Hence this is really a feature request. 

Please continue with any discussion about this on the forum. I will leave this ticket open for future reference until any decision is made on the matter. 

I will leave this here as a feature request

**Comment by adrianinsaval** [comment]
should be closed per forum discussion: https://forum.freecadweb.org/viewtopic.php?p=569329#p569296
