### ISSUE TITLE
Weird behavior in Placement dialog when using "center of mass" with Datum Plane

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5967]
Issue imported from https://tracker.freecad.org/view.php?id=4061

* **Reporter:** wmayer
* **Date submitted:** 7/18/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=3&t=37803&p=321702

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by wwmayer** [comment]
Problem is that a datum plane is an infinite shape and thus it's impossible to define a center of gravity.
