### ISSUE TITLE
Job path visualization

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5970]
Issue imported from https://tracker.freecad.org/view.php?id=4071

* **Reporter:** dhka2
* **Date submitted:** 7/26/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** confirmed
* **Tags:** Bountysource

# Original report text

Currently the Job object contains a visualization of the gcode of all child "Operations" objects and all Operations. This visualization is identical to the one shown when all "Operations" objects are visible, and also identical to the visualization that is shown when all operations (ie children of the operations object such as a drill object) are visible.

I propose that the Job object should not contain a visualization of the child object paths as this is redundant. Additionally making the Job object invisible should make all child objects invisible, without chaingeing their visibility state, so that making the job visible again shows all objects that where visible before the hiding of the Job object and only these objects.

I also propose that the "Operations" Object behaves in the same manner with regards to the its children (ie the operations as a drill object).

# Additional information

***Note***: this ticket has a Bounty ([link](https://www.bountysource.com/issues/77869088-job-path-visualization))

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by dhka2 2019-07-26 17:55
[Forum thread](https://forum.freecadweb.org/viewtopic.php?f=15&t=37960&start=10)

---

### Comment by sliptonic 2019-07-26 18:54
How should toggling visibility of the job affect visibility of non-path child objects (stock, model, tool controllers, etc)?

---

### Comment by dhka2 2019-07-26 19:31
In exactly the same manner as path objects.

the general point here is that the user, after generating a path with the path wb, needs only to hide the job object (or objects for a multi-body fcstd file) if he wishes to go back to the part workbench to make further modifications to the model. Then when the modifications are complete the user only needs to unhide the job object to continue work in the path wb.

---

### Comment by dhka2 2019-07-26 19:56
I have not looked at the code, but as a user it is my opinion, that if technically feasible, this should not be specially implemented in the path wb. As a general rule, for consistency and to avoid code duplication the behaviour should be as follows freecad wide:

All objects are hidden except objects that have:

A. Their visibility flag set to true AND
B. The visibility flags of all parents up to document root (Application) are set to true.

Also, as a general rule, objects that are expected to have children (ie are containers) should not have any visible elements at all unless there is a good reason to do otherwise, such as in the case of patterns or path dressups

---

### Comment by sliptonic 2019-07-28 15:53
https://www.bountysource.com/issues/77869088-job-path-visualization

**Comment by sliptonic** [comment]
This issue is resolved by PR https://github.com/FreeCAD/FreeCAD/pull/4911
