### ISSUE TITLE
A bug in the Coin3D library causing app to crash on RPi4 (Upstream Raspbian libs need updating)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5973]
Issue imported from https://tracker.freecad.org/view.php?id=4083

* **Reporter:** FrankGould
* **Date submitted:** 8/8/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** new
* **Tags:** Coin3d, raspberry pi, upstream

# Original report text

From the #freecad forum chat yesterday, "there's a bug in an underlying library (Coin3D)" that needs to be fixed. The results of running the FreeCAD app is that it crashes anytime someone tries to load a file or create a new one. FreeCAD should run on the new desktop Raspberry Pi 4B models running Raspbian Buster.

# Additional information

Original forum thread: https://forum.freecadweb.org/viewtopic.php?f=42&t=37458
Discussion thread related to this bug: https://forum.freecadweb.org/viewtopic.php?f=8&t=39444

OS: Raspbian GNU/Linux 10 (buster)
Word size of OS: 32-bit
Word size of FreeCAD: 32-bit
Version: 0.18.
Build type: Release
Python version: 2.7.16
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

Install buster on RPi4B, install FreeCAD, run app, and try to load an existing STL file or create a new file. In both cases, the app crashed on my 4GB system.

# Other bug information

* **Priority:** normal
* **Severity:** crash
* **Category:** Bug
* **Updated:** 1/19/2022

# Discussion from Mantis ticket

### Comment by FrankGould 2019-08-08 15:14
https://forum.freecadweb.org/viewtopic.php?f=42&t=37458

When running freecad from terminal CLI, received the following error message. Did not see this when running from drop-down menu. This is the same as reported in forum.

Coin warning in cc_glglue_instance(): Error when setting up the GL context. This can happen if there is no current context, or if the context has been set up incorrectly.
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0xb32b6120]

---

### Comment by Kunda1 2019-09-19 03:30
Thread dedicated to discussion about this bug is https://forum.freecadweb.org/viewtopic.php?f=8&t=39444

---

### Comment by Kunda1 2019-09-20 19:35
A bug was open on Debian for this as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931458

---

### Comment by @-alex- 2020-04-13 14:08
If FreeCAD compiled with PY2/Qt4 -> no crash
If FreeCAD compiled with PY3/Qt4 -> no crash
If FreeCAD compiled with PY2/Qt5 -> crash with segfault occurs
If FreeCAD compiled with PY3/Qt5 -> crash with segfault occurs

---

### Comment by Kunda1 2020-07-06 11:44
FrankGould this is reproducible on 0.19.x as well ?

---

### Comment by FrankGould 2020-07-06 12:02
Kunda1 I have migrated to Arch Linux ARM due to several Buster issues and am no longer using FreeCAD.

---

### Comment by Kunda1 2020-12-01 12:30
This issue has to do with the Raspbian libs that need to be updated.  
https://forum.freecadweb.org/viewtopic.php?f=42&t=37458&p=453369#p453369

---

### Comment by @-alex- 2020-12-10 23:37
update:
If FreeCAD compiled with PY2/Qt4 RPIOS32B-> no crash
If FreeCAD compiled with PY3/Qt4 RPIOS32B-> no crash when creating new document
If FreeCAD compiled with PY2/Qt5 RPIOS32B-> crash with segfault occurs when creating new document
 
If FreeCAD compiled with PY3/Qt5 RPIOS32B-> crash with segfault occurs when creating new document
If FreeCAD compiled with PY3/Qt5 RPIOS64B(betatest)-> no crash when creating new document (it happens time to times when opening other documents, maybe not related)
If FreeCAD compiled with PY3/Qt5 Ubuntu 20.04 LTS (XFCE/xubuntu)64B -> no crash when creating new document
More details here: https://forum.freecadweb.org/viewtopic.php?f=8&t=39444&p=456568#p456568

---

### Comment by Kunda1 2021-02-18 18:24
@-alex-	anything still pending for this? Did downstream update their libs?

---

### Comment by ShiftPlusOne 2022-01-18 12:46
I'm having trouble finding concrete information on what the issue is. Which libraries need to be updated? Since the issue hasn't been fixed in Raspbian, I'd like to push an update to Raspberry Pi OS to override it, but the linked threads don't seem to contain any viable solutions.

---

### Comment by ShiftPlusOne 2022-01-19 08:24
I've confirmed the issue occurs in vanilla Debian as well and have sent another report there https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004007.

**Comment by luzpaz** [comment]
bump

**Comment by adrianinsaval** [comment]
well I don't think there's anything for us to do here, if anything this was a Raspbian issue although by now these outdated libs have probably been updated already. Not too long ago an user helped in troubleshooting a navicube problem in raspberry pi so I don't think he was having constant crashes.
