### ISSUE TITLE
create links of a  selected object along selected path

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5976]
Issue imported from https://tracker.freecad.org/view.php?id=4091

* **Reporter:** tino
* **Date submitted:** 8/19/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** feedback
* **Tags:** #post-to-forum

# Original report text

I made a cylinder and a spiral then I aligned the cylinder to the spiral and it should have created cylinders aligned to the spiral, it makes the cylinders aligned but it starts outside the spiral and part inside without any logic

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2019-08-19 22:56
tino Big yellow banner at the top of the page, please follow it. 

---

### Comment by Kunda1 2020-01-16 13:22
tino ping

---

### Comment by Kunda1 2020-06-07 14:31
where is the [About](https://wiki.freecadweb.org/About) info ? 
Please follow up!

**Comment by Roy-043** [comment]
Closing this as stale. But I suspect that the issue is related to the Placement of the selected object and how Draft_PathArray uses that.
