### ISSUE TITLE
TechDraw Workbench Intersection dimensioning.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5981]
Issue imported from https://tracker.freecad.org/view.php?id=4114

* **Reporter:** PeterPNoster
* **Date submitted:** 9/4/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 0.19

# Original report text

Needed when dealing with sheet metal dimensioning.

Related to the following discussion:
[Intersection point](https://forum.freecadweb.org/viewtopic.php?f=35&t=39037)

Somehow related to this disussion:
[TechDraw and Fillets/Chamfers](https://forum.freecadweb.org/viewtopic.php?f=35&t=36208)

And certainly related to this feature request:
https://freecadweb.org/tracker/view.php?id=3004

# Additional information

OS: Linux Mint 19.2 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.17935 (Git) AppImage
Build type: Release
Branch: master
Hash: bdc229f51e959caedf24459c1b9c9de7f6567298
Python version: 3.7.3
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Switzerland (de_CH)

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by wandererfan 2019-09-12 13:51
[Solution via macro available here](https://github.com/reox/FreeCAD_macros/blob/master/EdgeIntersection.FCMacro)

PeterPNoster, Kunda1 - does the availability of a macro justify a change to "fixed" for this issue?

---

### Comment by PeterPNoster 2019-09-12 16:46
Yes, I can work with this solution.
Although it's clear for me that this request will come back. Because it is essential doing this kind of dimensioning on sheet metal bendings. Implementation in a future version of the TechDraw Workbench would be certainly much appreciated by a lot of users.

Thank you for the great work you do for FreeCAD!

**Comment by grubertechnic** [comment]
@WandererFan : there is already an intersection tool in TechDraw

![2023-05-15 12-12-02](https://github.com/FreeCAD/FreeCAD/assets/109620914/99c5584d-89ee-4c6f-a2d5-b6188a00fdb8)


Only issue atm, it is not parametric, but for that there are other issues to handle before (TNP in 2D), closing?

**Comment by WandererFan** [comment]
Closed as completed by dimension extensions.
