### ISSUE TITLE
[Feature Request] Ability to change the Crosshair color

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5982]
Issue imported from https://tracker.freecad.org/view.php?id=4115

* **Reporter:** Kunda1
* **Date submitted:** 9/5/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** resolved
* **Tags:** #tobeclosed, mouse

# Original report text

Referencing 2 older threads:
***2016: Crosshair color & size - update?*** (https://forum.freecadweb.org/viewtopic.php?t=14597)
***2013: Setup for Crosshair*** (http://forum.freecadweb.org/viewtopic.php?t=3722)

This would be a nice customization option.
 
***Usecase***: if the user has setup their background to be a lighter neutral color it's difficult to see the crosshair

***Case in point:***
(see screenshot below)

***Workaround***: obviously to change the background color (but this is not an ideal solution hence the Feature Request)

# Additional information

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=39099

OS: Manjaro Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18009 (Git) AppImage
Build type: Release
Branch: master
Hash: 0641ca0d1e020d18f23d2adb49959195266f04f7
Python version: 3.7.3
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/4/2022
* **Fixed in version:** 0.2

# Discussion from Mantis ticket

### Comment by Kunda1 2019-09-05 20:23
Screenshot shows the usecase for changing the crosshair color

---

### Comment by Kunda1 2022-02-04 16:35
realthunder is this possible in Link branch?

---

### Comment by realthunder 2022-02-04 22:50
This has already implemented in upstream, by setting parameter **User parameter:BaseApp/Preferences/View/CursorCrosshairColor**

---

### Comment by Kunda1 2022-02-04 23:12
realthunder Oh wow...! Had no idea.
hmmm...i don't see this mentioned in https://wiki.freecad.org/Fine-tuning

What are the colors one can choose?

Edit: here's the commit: https://github.com/FreeCAD/FreeCAD/commit/0e9b8ef4d44ac0d3ed438d00abb29b38ef881157

**Comment by adrianinsaval** [comment]
feature exists and is configurable from the GUI
