### ISSUE TITLE
Allow Angled Section Views

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5988]
Issue imported from https://tracker.freecad.org/view.php?id=4128

* **Reporter:** wandererfan
* **Date submitted:** 9/13/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** feedback
* **Tags:** 

# Original report text

[Forum discussion](https://www.forum.freecadweb.org/viewtopic.php?f=3&t=39275)

Currently, the Section tool will only create sections in 4 directions (left, right, up, down).  There are occasions where a Section at an angle (say 45*, left/down to right/up) to the Base view would be useful. 

# Additional information

There was a question about this in the German forum some time ago.  [German forum thread re angled Section](https://www.forum.freecadweb.org/viewtopic.php?f=13&t=22764&p=176571&hilit=section+techdraw#p176517)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Platform:** all
* **Updated:** 1/15/2022

# Discussion from Mantis ticket

### Comment by wandererfan 2022-01-15 15:37
This can be accomplished by changing the Direction and SectionNormal properties of the SectionView after it is created.

---

### Comment by wandererfan 2022-01-15 15:39
Is this request still valid given the ability to adjust the direction after creation?

**Comment by WandererFan** [comment]
completed by recent ComplexSection & SimpleSection mods
