### ISSUE TITLE
[Feature Request] Start WB could report more details when highlighting an FCStd file

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5992]
Issue imported from https://tracker.freecad.org/view.php?id=4142

* **Reporter:** Kunda1
* **Date submitted:** 9/24/2019

# Original report text

sliptonic makes a great point in his YT clip [1] about the StartWB adding the ability to report more information on a file when highlighting or hovering over it. 

[1] https://youtu.be/uKD6sGdci4Y?t=189

The whole segment starts at https://youtu.be/uKD6sGdci4Y?t=53
Another interesting part https://youtu.be/uKD6sGdci4Y?t=114

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
@tmksw any interest looking in to this feature ?

**Comment by tmksw** [comment]
@luzpaz  From the attached video I understood that it's about adding the full path of the drawing file to the thumbnail when hovering over recent file in `Start WB`. Is that correct, what exactly needs to be done in this specific task ?

**Comment by luzpaz** [comment]
@sliptonic would you have a moment to weigh-in ?

**Comment by yorikvanhavre** [comment]
We could add more information like:

* The full path of the file
* The author
* The license
* The number of objects maybe?

**Comment by tmksw** [comment]
PR for above mentioned changes is ready.

*Before*

![tooltip-before](https://github.com/FreeCAD/FreeCAD/assets/36006451/ff83eba4-59ab-4a3c-bdaa-5902ddf94459)

*After*

![tooltip-after](https://github.com/FreeCAD/FreeCAD/assets/36006451/57e4fab4-b9a1-417e-aa21-358dd514c6af)
