### ISSUE TITLE
Add Support for Bezier Curves in Import Module Dxf Exporter

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6008]
Issue imported from https://tracker.freecad.org/view.php?id=4201

* **Reporter:** @wandererfan
* **Date submitted:** 11/23/2019
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** bezier curve

# Original report text

[Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=41113&p=349379#p349379)

Bezier curves are used in the definitions of .ttf fonts.  Without support for Bezier curves the exporter is not able to export ShapeStrings. 

# FreeCAD Info

```
OS: Linux Mint 19 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18760 +7 (Git)
Build type: debug
Branch: SectionAngles5
Hash: f18885c66cddfb97e5686a7e3384311c48a9cd38
Python version: 3.6.8
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/Canada (en_CA)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
Using the new C++ exporter ShapeStrings are exported to DXF as splines. DXF does not support Bézier curves.
