### ISSUE TITLE
Allow Adjustment of Stacking Order of Views

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6012]
Issue imported from https://tracker.freecad.org/view.php?id=4208

* **Reporter:** wandererfan
* **Date submitted:** 11/29/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Views are currently stacked in the order they are drawn.  It would be convenient to move a view above or below another view.

many forum discussions. [One here.](https://forum.freecadweb.org/viewtopic.php?p=350597#p350597)

# FreeCAD Info

```
OS: Linux Mint 19 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18787 +15 (Git)
Build type: debug
Branch: Cosmetics2
Hash: 79fc2bdada724391cfe2b42afda42b8c379e2cc7
Python version: 3.6.8
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/Canada (en_CA)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by WandererFan** [comment]
implemented by commit fcef1cb174
