### ISSUE TITLE
[Problem] PartDesign Pad 'Up to face' has issues when selecting a ShapeBinder's or Binder's face

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6014]
Issue imported from https://tracker.freecad.org/view.php?id=4211

* **Reporter:** Dan-K
* **Date submitted:** 12/5/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 0.18, 0.19, shapebinder

# Original report text

If a PartDesign body has a ShapeBinder or Binder to a reference object and a sketch within that same body attempts to pad to once of the binder's surfaces with 'Up to face', the following error occurs:

`311.375 <App> Document.cpp(3462): Failed to recompute uptoface_bug#Pad002: Pad: Resulting shape is empty`

Discussed on the forum: https://forum.freecadweb.org/viewtopic.php?f=3&t=41280

# Steps to reproduce
[uptoface-bug.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/14546310/uptoface-bug.FCStd.zip)

1. Download and open the attached 'uptoface-bug.FCStd' file.
2. Notice the 'Target Body' PartDesign Body has a ShapeBinder and a Binder of the 'Static Body' body and that the positions of these binders are correct.
3. Hide the 'Static Body' and one of the binder objects such that the other binder object is visible.
4. Switch to the 'PartDesign' workbench.
5. Select 'Sketch002' from the tree.
6. Press the 'PartDesign' 'Pad' button.
7. Change the 'Type' to 'Up to face'.
8. Select one of the two faces of the visible binder object whose normal is parallel to the sketch's face.
9. Press 'OK'.
10. Notice the error popup and error message in the 'Report view'.
11. This can be repeated with the other binder object, the issue will happen with both ShapeBinder and Binder.

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18811 (Git)
Build type: Release
Branch: master
Hash: b809867021deb37be1039dab37b9fe1cafab254e
Python version: 3.6.7
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/Canada (en_CA)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Windows 10, macOS Catalina 1607, 10.15.1**
* **Updated:** 2/6/2021

**Comment by FlachyJoe** [comment]
Fixed in current dev

**Comment by luzpaz** [comment]
@FlachyJoe for posterity can you add the full [About](https://wiki.freecad.org/About) info? TIA. 

Closing.
