### ISSUE TITLE
Ability to drag and drop the circle/square defining the detail view in TechDraw

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6016]
Issue imported from https://tracker.freecad.org/view.php?id=4221

* **Reporter:** dxp.dev
* **Date submitted:** 12/10/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 0.19, TechDraw

# Original report text

***Actually:***
When adding a detail view of a part in Techdraw WB ([https://www.freecadweb.org/wiki/TechDraw_NewDetail](https://www.freecadweb.org/wiki/TechDraw_NewDetail)), we have to guess the coordinates of the circle/square defining the detail view to display as another element on the sheet by adjusting the values of the x,y,z anchor properties manually.

***Proposed:***
I think that adding the possibility to drag and drop the circle/square and defining its radius/dimension the same way we can drag and drop a circle/square in Sketcher WB as well as drag and drop the radius/dimension by dragging the circle/point of the square would be better.

***Advantages:***

* Faster
* More precision
* More user-friendly

# Additional information

* [Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=8&t=41549)
* Ticket opened on request of [Wandererfan](https://forum.freecadweb.org/memberlist.php?mode=viewprofile&u=1375)

# FreeCAD Info

```
OS: macOS Mojave (10.14)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18775 (Git)
Build type: Release
Branch: master
Hash: 9e93e621f9d5332114d29ea316f27aa6698eb70b
Python version: 3.7.3
Qt version: 5.12.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/Switzerland (fr_CH)
```

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **OS: MacOS 1.14.6**
* **Platform:** Mac
* **Updated:** 7/29/2021

**Comment by WandererFan** [comment]
Should be resolved by PR #8094.
