### ISSUE TITLE
Crash: when testing Draft Dimension

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6021]
Issue imported from https://tracker.freecad.org/view.php?id=4242

* **Reporter:** vocx
* **Date submitted:** 1/9/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

All workbenches include unit tests to tests many of its tools.

When running the test for the Draft Dimension tool, and only this tool, from the command line, the software crashes.

It doesn't crash if all tests are run, only when this single test is run in isolation.

Many people can't reproduce this crash. Therefore, the problem could be my particular system, including Coin version, and graphics card.

Forum thread [Crash: when testing Draft Dimension](https://forum.freecadweb.org/viewtopic.php?f=3&t=39477&p=359047#p359047)

# Additional information

My system has
```
pivy.__version__
'0.6.5a0'
```

And Intel HD 620 (rev 02) graphics.

Backtrace in the attached file.

# Steps to reproduce

Run from the command line

```
freecad -t drafttests.test_creation.DraftCreation.test_dimension_linear
```

It does not crash if all tests are run
```
freecad -t TestDraft
```

# FreeCAD Info

```
OS: Ubuntu 18.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19212 (Git)
Build type: Debug
Branch: master
Hash: 004fda205ed8470702864083f417710db222b760
Python version: 3.6.9
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

# Other bug information

* **Priority:** normal
* **Severity:** crash
* **Category:** Bug
* **OS: Ubuntu 18.04**
* **Platform:** Linux
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by openBrain (private) 2020-02-11 09:48
vocx : your note ~14147 just above is blank. What's its purpose ?

---

### Comment by vocx 2020-02-11 16:47
Attachment of log

---

### Comment by vocx 2020-05-17 20:23
Another forum thread to reproduce the error with a single file containing a single Draft Dimension, [Crash with a single Draft Dimension](https://forum.freecadweb.org/viewtopic.php?f=3&t=46459).

Probably an explanation for the problem is that the Dimension rebuilds its viewprovider using Pivy (Coin), which is not available at start.

To make it work, first create a new document, which creates a 3D view, and then switch to the Draft Workbench to initialize Pivy. Then loading the single document with a single dimension works correctly.

**Comment by luzpaz** [comment]
Per @Roy-043: 

> The function test_dimension_linear() does not exist anymore. There are 2 new functions that replace it: `test_dimension_linear_simple()` and `test_dimension_linear_obj()`.

Both of those tests work. Therefore closing this ticket
