### ISSUE TITLE
[Feature request] Shorctut for Transform

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6023]
Issue imported from https://tracker.freecad.org/view.php?id=4248

* **Reporter:** leoheck
* **Date submitted:** 1/15/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** shortcuts

# Original report text

I use the "Transform" action to move objects very often. This action does not have a shortcut. It will represent a really good improvement to have this shortcut implemented.

I posted this some time ago in the Forum too.
https://forum.freecadweb.org/viewtopic.php?f=8&t=38258&hilit=shortcut 

I would suggest something like Ctrl+Shit+T (or something with T, because it is easier to remember) for example. Working at least in Part Workbench and Part Design Workbench.

# FreeCAD Info

```
This is what I am using right now.

OS: Ubuntu 19.10 (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Python version: 3.7.5
Qt version: 5.12.4
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** high
* **Severity:** trivial
* **Category:** Feature
* **OS: Ubuntu 18.04/19.04/19.1**
* **Platform:** x86_64
* **Updated:** 5/11/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2020-01-16 16:58
leoheck why are you marking this ticket ***Product Version*** 0.18 when you are using 0.19 ? Please use the correct version next time. Thank you

---

### Comment by leoheck 2020-01-16 18:28
I use Freecad in a bunch of computers. On my personal computer, I am using Freecad 0.19. But since it is a small feature request it would be nice to implement it in 0.18 as well if possible. I am trying to change it. It took me about 10 minutes just to understand how to reply to your message.

---

### Comment by leoheck 2020-01-16 18:30
Ah, you already fixed it. Alright, thanks.

---

### Comment by heewa 2021-05-11 21:19
Looks like this has been fixed on the 0.20 release (with [PR #4678](https://github.com/FreeCAD/FreeCAD/pull/4678)). I verified that it works for me on a build from master. A simple merge to the 0.19 branch should fix it for that release as well.

**Comment by xtemp09** [comment]
Has this issue been resolved?

**Comment by luzpaz** [comment]
@leoheck ping

**Comment by leoheck** [comment]
I am not aware if we have this shortcut.
The context menu does not show any keyboard shortcut for that action.

![image](https://github.com/FreeCAD/FreeCAD/assets/1277920/f15296ba-464d-4549-af0e-3e554a695fff)

**Comment by Roy-043** [comment]
There is no default shortcut. But a user can assign a custom shortcut since #4678. Since that is a pretty simple action I see no reason to keep the feature request open.
