### ISSUE TITLE
Constructor from the makeArray Function in the Draft Workbench does not Allow Polar Array

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6030]
Issue imported from https://tracker.freecad.org/view.php?id=4264

* **Reporter:** louisgag
* **Date submitted:** 2/12/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** #pending-forum

# Original report text

Yes, I have not created a thread because I think the bug is quite obvious.
I verified it on 0.19 and 0.18.4 but it probably also affects other earlier versions.

When in Python mode, trying to construct an array with a name using for example `Draft.makeArray(App.getDocument('Unnamed').getObject('Cylinder'),App.Vector(0,0,0),360,4,"testArray")` from the function (line 1249 from Draft.py) does not allow to directly make a polar array with a name.

Indeed, the instructions in the code say  `makeArray(object,center,totalangle,totalnum,[name]) for polar array`

but because of this part from the code:

```
        elif arg4:
        obj.ArrayType = "ortho"
```

it forces any call with a non-null "arg4" argument (in this case the name of the array) to make an Orthogonal array, or when the arguments for are polar array are given to simply return an error about wrong argument type.

# Steps to reproduce

This is just an example:
Make a new document, go to Part workbench, make a cylinder, go to python console, type:
```
import Draft
Draft.makeArray(App.getDocument('Unnamed').getObject('Cylinder'),App.Vector(0,0,0),360,4,"testArray")
```

# FreeCAD Info

```
OS: Ubuntu 18.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.Unknown
Build type: Unknown
Python version: 2.7.17
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: C/Default (C)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2022

# Discussion from Mantis ticket

### Comment by openBrain 2020-02-19 13:06
louisgag : according guidelines (big yellow bow on top of the page), could you please open a topic on the forum (Draft subforum) so it can be more widely discussed ?
Please cross-post ticket number in forum, and forum thread in this ticket. Thanks.

---

### Comment by louisgag 2020-02-19 15:53
thanks for having a look at my report, here is the [Forum thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=43498) I just opened.

**Comment by Roy-043** [comment]
As discussed in the forum thread: this issue can be closed.
