### ISSUE TITLE
Allow user specified line width for SVG export

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6034]
Issue imported from https://tracker.freecad.org/view.php?id=4269

* **Reporter:** wucke13
* **Date submitted:** 2/18/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Some lasercutters present themselves as printers. In order to cut something, the one has to send a PDF/SVG as print job to the cutter. The thickness of lines determines whether something is cut or engraved. Our current workflow includes exporting an SVG from our CAD model in FreeCAD, and then modifying this model in Inkscape to adjust the thickness of all cut-lines to the desired value for cutting and the thickness of all other lines to a distinct thickness. This is tedious and error prone. It would greatly improve said workflow if FreeCAD lets one specify the desired thickness for the lines in the exported SVG. Even better would be, if the user can choose different thicknesses for both the cutted and not cutted lines.

# FreeCAD Info

```
OS: NixOS 19.09.1977.1dadefec574 (Loris)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.Unknown
Build type: Release
Python version: 3.7.5
Qt version: 5.12.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 12/29/2021

# Discussion from Mantis ticket

### Comment by wandererfan 2020-02-20 15:06
I can think of at least 3 different SVG exports (DrawingWB, Flattened SVG from 3D and TechDrawWB.

Was there one in particular that causes your issue?

---

### Comment by wucke13 2020-02-20 19:37
I've used the GUI. First I marked the flattened 2D geometry, then I used the File -> Export (or CTRL + E) dialog to export as a Flattened SVG.

---

### Comment by Kunda1 2020-02-20 21:01
Ticket is missing a forum thread. Please follow the FreeCAD tracker guidelines (yellow banner top of page)next time before opening a ticket.

---

### Comment by Kunda1 2020-12-04 04:15
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=52876

**Comment by luzpaz** [comment]
![Screenshot_20231023_134216](https://github.com/FreeCAD/FreeCAD/assets/4140247/8f8c556e-2309-4b32-a9f7-76a67ac29938)

CC @chennes @yorikvanhavre
