### ISSUE TITLE
LeadinLeadout DressUp Causes Tool Crash on Deburr Ops

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6037]
Issue imported from https://tracker.freecad.org/view.php?id=4280

* **Reporter:** dubstar_04
* **Date submitted:** 3/5/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

Forum Post: https://forum.freecadweb.org/viewtopic.php?f=15&t=43896

# Steps to reproduce

Create a deburr operation, Add a leadinleadout dressup. 

observe that part of the deburr path is likely missing and the path intersects the model. 

# FreeCAD Info

```
OS: Debian GNU/Linux 10 (buster) (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19803 (Git)
Build type: Unknown
Branch: master
Hash: 1bd4a173ef1e8a68e074ef9a7e6003430eac5e2d
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

```

# Other bug information

* **Priority:** high
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2020-03-05 19:22
dubstar_04 please add the FC info in the field dedicated to it called 'FreeCAD Information' for posterity reviewers/devs etc...

---

### Comment by openBrain (private) 2020-03-05 22:05
Kunda1 : move to 'Path' project ?

---

### Comment by dubstar_04 2021-01-14 21:27
The original issue seems to be resolved however on internal edges the path still intersects the part. This can be worked around by changing the entry point to an outside edge. 

Due to the workaround the priority could now be reduced to low but the issue could be revisited.

---

### Comment by schildkroet 2021-01-19 17:04
The dressup isn't aware of the part shape and is just applied at the current place. To avoid problems like this, you can choose the entry point.

**Comment by sliptonic** [comment]
I think the dressup is now working as designed.  Making the dressup part-aware is outside scope.  Closing issue.
