### ISSUE TITLE
Better Error message for No active body

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6039]
Issue imported from https://tracker.freecad.org/view.php?id=4288

* **Reporter:** cbruner
* **Date submitted:** 3/14/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** #pending-PR

# Original report text

Forum discussion:
https://forum.freecadweb.org/viewtopic.php?f=3&t=44172
Creating something in the part workbench, switching to part design selecting a face and clicking sketch gives an error about no body being present. 

Using PartDesign body (while in part design workbench), then selecting the face, and activating sketch does the same thing as what selecting face and activating sketch used to do (while in part workbench).

So would a valid enhancement be that instead of throwing that error (which is confusing), how about when activating a sketch with a face selected, switching to partdesign workbench and doing the equivalent. 

Or... change the error message to add the text, "Perhaps use partdesign workbench/part design body to do what you are trying to do"  As a newbie, I would have found this very helpful.

# Steps to reproduce

I know that the problem is differences in versions, however, my current version .19.19... seems wrong.
In this old tutorial (fc 14) He has created a dice with the part workbench, then goes to part design, selects a face and starts sketching on the face.
https://youtu.be/uBKhBwSP_iM?t=244

This makes perfect intuitive sense, as the face is the body. But my freecad complains that there is no body. Can someone explain to me why the face isn't the body, or even the cube isn't the body? and how I would properly do this tutorial with a current version of freecad? (I want to see the face while creating the dots on the dice).

# FreeCAD Info

```
OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19758 (Git) AppImage
Build type: Release
Branch: master
Hash: c165edd52c7f06ac09f992e5b5bf1d37661a8c0f
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/Canada (en_CA)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 8/25/2021

# Discussion from Mantis ticket

### Comment by chennes 2021-08-25 00:51
If I am understanding correctly, this is addressed by [PR 4949](https://github.com/FreeCAD/FreeCAD/pull/4949).

**Comment by adrianinsaval** [comment]
I too believe this has been adressed by #4949
time to close?
