### ISSUE TITLE
[Feature] PartDesign: 5 standard options are missing in PD Tree view context menu

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6043]
Issue imported from https://tracker.freecad.org/view.php?id=4308

* **Reporter:** Roy_043
* **Date submitted:** 4/10/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** acknowledged
* **Tags:** 

# Original report text

5 standard options are missing in the PartDesign Tree view context menu:
"Toggle visibility" - "Select all instances"

#### Part Tree Context menu
![image](https://github.com/FreeCAD/FreeCAD/assets/4140247/b40c25b6-89e7-4e2c-9f06-b8bd07ecb4c7)

#### PartDesign Tree Context menu
![image](https://github.com/FreeCAD/FreeCAD/assets/4140247/cfd7db06-007d-4006-9bf3-88d767a4be92)

# Steps to reproduce

Select an object in the tree and right-click.

# FreeCAD Info

```
OS: Windows 8.1 (6.3)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.20311 (Git)
Build type: Release
Branch: master
Hash: 915e551bbb7e3614bc804f1ae1f65027b5432b9f
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Dutch/Netherlands (nl_NL)

```

# Other bug information

* **Priority:** normal
* **Severity:** tweak
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Roy_043 2020-04-10 08:46
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=44948

**Comment by maxwxyz** [comment]
@Roy-043 is this still relevant?

**Comment by Roy-043** [comment]
Yes, this is still relevant.
