### ISSUE TITLE
Strange character after bracket, appear in expression input field for a constraint in sketcher on Windows (due to interpreting AltGr as Ctrl+Alt)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6051]
Issue imported from https://tracker.freecad.org/view.php?id=4325

* **Reporter:** lc03
* **Date submitted:** 4/27/2020

# Original report text

When I type in expression containing bracket in the expression editor a strange character appear at the end of the entered text.

# Steps to reproduce

1)	Create a new sketch
2)	Create 2 new line.
3)	Create a dimension constraint on the first line.
4)	Create a dimension constraint on the second line and then enter the “=” sign to edit expression.
5)	Type in the expression “Constraints[0]”
Result: just after you type in the last character (that is “]”) the strange character appear in the expression editor

[Forum thread](https://forum.freecadweb.org/viewtopic.php?f=12&t=45811)

Edit: see https://github.com/FreeCAD/FreeCAD/issues/6051#issuecomment-1140772357 

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.20738 (Git)
Build type: Release
Branch: master
Hash: 0c96f77184edc0a6747483b2ff1462fc6dae46ff
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/France (fr_FR)
```

**Comment by luzpaz** [comment]
@0penBrain can you still reproduce?

**Comment by 0penBrain** [comment]
@luzpaz I never reproduced that because it seemed to be Windows+French specific (I'm lacking the Windows part 😄). I will bump the topic on the French subforum and report.

**Comment by 0penBrain** [comment]
What I understand from answer on the forum is that it's probably a Windows issue :
* Windows has a feature that when you hold `Alt` and enters a number with numpad, you can get special symbols
* Windows seems to interpret `AltGr` as `Ctrl+Alt`
So depending on how those virtual `Ctrl+Alt` are considered to be pressed then released, if you have used the numpad while holding `AltGr`, you can see weird symbols appearing.
There are things we can do, but looks to me like killing a fly with a bazooka...

**Comment by luzpaz** [comment]
@PaddleStroke have you encountered this bug yet ? Any idea on how to auto-correct this phenomena so it doesn't present ?

**Comment by PaddleStroke** [comment]
I have tried and cannot replicate. Even if I hold altGr while typing the '[0]' and use the numpad to type the 0, I don't get a special character to appear.

**Comment by luzpaz** [comment]
Thanks paddle. 

Does anyone by chance know [mario52's](https://forum.freecad.org/memberlist.php?mode=viewprofile&u=1058) github account ? He's been the only one to reproduce this. 

I think we should close in the meantime.
