### ISSUE TITLE
Application defaults to display port dock instead of embedded graphics - causes empty editor screen without error notification

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6056]
Issue imported from https://tracker.freecad.org/view.php?id=4333

* **Reporter:** wrpetersen
* **Date submitted:** 5/2/2020
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** feedback
* **Tags:** #post-to-forum

# Original report text

I have a laptop with a multi-monitor USB3 dock. When I open FreeCad with the dock connected I get a blank screen in the editor, cannot view cad files. There is no error message so it leaves you wondering what is wrong. If I unplug my dock and open FreeCad everything works fine, I can then reconnect my dock and use the application normally because at startup it pointed to my embedded graphics.

This is especially frustrating because Windows loves to do automatic updates overnight and close out all of your applications. I would probably leave my laptop plugged into the dock for several weeks if it weren't for FreeCad needing to be opened off of it.

# Additional information

I have two possible suggestions; If there was a setting to permanently point to which graphics device FreeCad will use for processing OR when the default device is not compatible, the application will check for an additional graphics processor. I have similar issues with 3D printer slicers but they specifically throw an error with the OpenGL driver, I am not sure if FreeCad uses that driver. 

# Steps to reproduce

Attach a USB3 dock with external monitors, open application and attempt to make a new sketch/part etc. I am using a Wavlink UG39DK1 specifically on an i7 laptop without an additional GPU- laptop uses embedded CPU graphics. 

# FreeCAD Info

```
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Windows 10 Home**
* **Platform:** Intel i7 Laptop
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by wrpetersen 2020-05-02 19:55
Just to clarify the description portion " If I unplug my dock and open FreeCad everything works fine, I can then reconnect my dock and use the application normally because at startup it pointed to my embedded graphics."

If I open the application with the dock unplugged- you cannot correct the issue by unplugging dock while the application is already open. Once the application is open you can then re-dock the computer and use the external displays

---

### Comment by openBrain 2020-05-03 10:13
wrpetersen : please process according our [reporting guidelines](https://forum.freecadweb.org/viewtopic.php?f=3&t=5236) by always first open a topic in [our forum](https://forum.freecadweb.org/). Thx
Though some words about your issue :
* Probably you can tell your GFX drivers which output to use with which application
* You should give a try to [FreeCAD 0.19](https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre). Latest Qt has fixed lot of issues with GFX
Please add link to your forum topic here when it's created.

**Comment by luzpaz** [comment]
Closing
