### ISSUE TITLE
Do not add files to the recent list on import or export

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6076]
Issue imported from https://tracker.freecad.org/view.php?id=4375

* **Reporter:** TedM
* **Date submitted:** 6/16/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

See forum thread [here](https://forum.freecadweb.org/viewtopic.php?f=3&t=47642).

Currently, all user files read or written are added to the recent files list on the start page. However, files that are imported or exported are unlikely to be simply opened and so make little sense to be in this list. These files get little or no value from being able to be clicked on to be opened and push off files that the user are likely to want to simply open.

Specifically, the feature request is that only files that used in "open", "save" and "save as" should be added to the recent file list. File read or written in any other way (including but not necessarily limited to "import" and "export") should not be added to the list.

It may be desirable to make this a preferences option to maintain the old way for those who may like it.

# Steps to reproduce

1. Create a new file.
2. Go to Part WB and create a cube.
2. Select the cube and use file->export to create test.stl
3. Go to the start page; observe that test.stl is in the recent file list even though there is little value on being able to click on it to open it.

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21125 (Git)
Build type: Release
Branch: master
Hash: 40600a55c2fe71ff589be677f6e427ccc937d003
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by TedM 2020-06-16 11:24
“Save copy” should also go into the resent file list. I overlooked that in the initial report.

---

### Comment by chennes 2021-01-30 16:14
Hidden preferences "RecentIncludesImported" and "RecentIncludesExported" were added to control the Recent files list behavior: 
PR: https://github.com/FreeCAD/FreeCAD/pull/4165
Commit: https://github.com/FreeCAD/FreeCAD/commit/ca346b90992e9241e0edea953a1528dfbe41a693
Wiki documentation: https://wiki.freecadweb.org/Fine-tuning

**Comment by Roy-043** [comment]
Closing this as fixed.
