### ISSUE TITLE
Documentation: Sweep: Include "attach it to the path" step.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6079]
Issue imported from https://tracker.freecad.org/view.php?id=4383

* **Reporter:** sangue
* **Date submitted:** 6/25/2020
* **FreeCAD version:** 0.18
* **Category:** General
* **Status:** new
* **Tags:** documentation

# Original report text

The documentation of the Sweep command is very misleading and misses essential steps:

Additional recipe specified by TheMarkster should go (analogously) into the docs:
"Center the profile to the origin of the sketch, then attach it to the path. (Select profile sketch, in properties select Map Mode property, then click the [...] button to open that attachment editor.) The map path parameter (a value from 0.0 to 1.0) can be used to position the profile along the path once it is attached as a means of testing how the profile will proceed along the path."

Was asked to put that in the tracker according to this forum thread:
https://forum.freecadweb.org/viewtopic.php?f=3&t=47760

# Steps to reproduce

https://forum.freecadweb.org/viewtopic.php?f=3&t=47760

# FreeCAD Info

```
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Switzerland (de_CH)

```

# Other bug information

* **Priority:** low
* **Severity:** text
* **Category:** General
* **Updated:** 2/6/2021

**Comment by FEA-eng** [comment]
@maxwxyz This can be closed as completed now: https://wiki.freecad.org/Part_Sweep#Accepted_geometry
