### ISSUE TITLE
Extensions module directory lacking from module paths on startup

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6086]
Issue imported from https://tracker.freecad.org/view.php?id=4397

* **Reporter:** Fizik
* **Date submitted:** 7/2/2020
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** resolved
* **Tags:** 

# Original report text

Modules installed (by the Extension Manager) in the user Python modules directory ***%appdata%\FreeCAD\Mod*** are not accessible by means of the Python console (nor are they available to macros loaded into the workbench) when FreeCAD is started without command line options (e.g. from the start menu after a fresh install).

Things work fine when starting with the `--module-path` option, like
```
 path\to\FreeCAD.exe -M %appdata%\FreeCAD\Mod
```

# Steps to reproduce

This description is pretty arbitrary, but it is what I stumbled across.

1.  Get a fresh install of FreeCAD 0.18.4 on Windows 10.
2.  Install, by means of the Extension Manager, A2+. This drops a Python module directory ***A2plus*** in your ***%appdata%\FreeCAD\Mod*** directory.
3.  Start FreeCAD (from the Windows Menu, i.e. without command line options).
4.  In the Python console, type
5.  Quit FreeCAD, and restart with the extension modules directory passed as an additional Python module path, e.g.
6.  In FreeCAD, try accessing **A2+** from the Python Console again,

# FreeCAD Info

```
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

```

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** Bug
* **OS: Windows 10 Build 19041.329**
* **Updated:** 2/6/2022

# Discussion from Mantis ticket

### Comment by Fizik 2020-07-02 15:13
Please delete this. I learned what I did wrong.

---

### Comment by openBrain 2020-07-07 16:22
Fizik : please tell us what you did wrong so everybody will take advantage of this. I'll close ticket when done. Thx.

---

### Comment by Fizik 2020-07-07 21:37
openBrain The module is accessible by the name ***FreeCAD.A2plus*** (instead of ***A2plus*** without the prefix), and hence is imported by
```
import FreeCAD.A2plus
```

(I got myself fooled by the — apparently outdated — example file [A2p_animation-example-script.py](https://forum.freecadweb.org/download/file.php?id=97981) from the [A2+ documentation wiki](https://wiki.freecadweb.org/A2plus_Workbench).)

---

### Comment by Kunda1 2022-02-04 18:45
openBrain where should we document this?

---

### Comment by openBrain 2022-02-06 17:48
Kunda1 : It's purely related to A2plus so we don't really have room for that. At least the information is here. ;)

**Comment by luzpaz** [comment]
@kbwbe if the A2+ docs aren't showing this, do you mind adding?
Closing this ticket as it is A2+ related.
