### ISSUE TITLE
Improve the sketcher clone tool

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6087]
Issue imported from https://tracker.freecad.org/view.php?id=4398

* **Reporter:** abdullah
* **Date submitted:** 7/3/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Chrisb describes here an improved version of the sketcher clone tool:
https://forum.freecadweb.org/viewtopic.php?f=10&t=48268#p413637

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment]
@PaddleStroke I guess this is closed with the implementation of array #11267 and copy&paste #11537
