### ISSUE TITLE
FEM constraints not shown in PartDesign workbench object when moved using placement

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6093]
Issue imported from https://tracker.freecad.org/view.php?id=4408

* **Reporter:** lsoltmann
* **Date submitted:** 7/21/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** #pending, #pending-forum, FEM, Part Design, Placement

# Original report text

The FEM constraints (only tested force and fixed) graphics do not show up in the selected location if an object created with the part workbench was moved using placement. The graphics show up in the location of the part as if it were at the global origin. Running the FEM confirms that the constraints are not on the object. It was noted by the user thschrader that this only happens in the part design workbench and not the part workbench. Moderator bernd said this is a known problem that the FEM does not play well with the part design workbench.

Issue was posted about here: https://forum.freecadweb.org/viewtopic.php?f=18&t=48750

# Steps to reproduce

1. Create a new file and select the part design workbench.
2. Create a new body and a sketch on the XY plane.
3. Sketch a square that is 1in by 1in.
4. Pad the sketch 1in in +z direction.
5. Using the placement property in the model view, set y = 2.0in.
6. Open the FEM workbench and create a new analysis.
7. Add a fixed constraint to any side of the cube using Model > Mechanical Constraints > Constraint fixed.
8. Observe that the constraint graphics are not on the object, but would be if the object had not been moved from the global origin. The same issue occurs with the force constraint as well. Those are the only two constraints that were tested.

# FreeCAD Info

```
OS: macOS Mojave (10.14)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21938 (Git)
Build type: Release
Branch: master
Hash: 5666598a6be219830a992610243fe23144a61453
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: C/Default (C)
```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/5/2022

# Discussion from Mantis ticket

### Comment by @berndhahnebach 2020-07-26 21:54
confirmed by Bernd

---

### Comment by @berndhahnebach 2020-07-26 21:55
Workaround. Create Simple Copy of the body with Part workbench.

---

### Comment by @wmayer 2021-02-20 11:00
In `Constraint::getPoints`
the line can be added before accessing the sub-elements:
```
  toposhape.setPlacement(feat->globalPlacement());
```

---

### Comment by Kunda1 2022-01-22 21:58
jnxd can you take a look at this?

---

### Comment by @AjinkyaDahale 2022-01-25 17:41
ref: https://forum.freecadweb.org/viewtopic.php?f=18&t=48750&p=564856#p564856

So I debugged and observed a couple of differences between using part and part design features (refer to the example files attached):

1. When placement is changed for a PD body (there is no placement option in the feature itself), `Fem::Constraint::execute()` is not called. This is called in
2. Even after a forced recompute (with PD), the TopoShape that is being used does not have any transformation applied. For part this transformation is applied.

This suggests that the following is happening: any placement changes are stored in the body, but the FEM constraint stores references from the feature (the box in the examples) and uses the feature's transformation.

So our task is to make sure these transformations can be accessed from each other: on the one side pd feature should be "touched" when the body's placement is changed, and on the other side when we use the feature's geometric data, the body's placement is taken in account.

[fem-files.zip](https://github.com/FreeCAD/FreeCAD/files/8514600/fem-files.zip)

---

### Comment by @AjinkyaDahale 2022-02-04 18:14
@berndhahnebach @wmayer do you have any comments on this, especially the forum post? I am trying to make the PD feature also include the body's transformation/placement when it's own transformation/placement or coordinates are asked. I expect this, however, to have some side effect elsewhere in PD.

**Comment by luzpaz** [comment]
I've updated the ticket to reflect @AjinkyaDahale forum response + the attached sample files
