### ISSUE TITLE
Pockets into a circular hole and refining object damages the object structure

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6095]
Issue imported from https://tracker.freecad.org/view.php?id=4412

* **Reporter:** MRx
* **Date submitted:** 8/1/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

I've created a sample project, and it seems creating a vertical circular pocket into a horizontal circular pocket damages the object structure.

1. create some shape with horizontal pockets
2. create some vertical pockets touching the horizontal pockets
3. run refine object
4. run check geometry

it gives a lot invalid curve on surface.
A sample project is attached.

It happened to me on 2 other objects, all I could do is to redraw the object when this happened.

OS: macOS Mojave (10.14)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21938 (Git)
Build type: Release
Branch: master
Hash: 5666598a6be219830a992610243fe23144a61453
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: C/Default (C)

Forum Post:
https://forum.freecadweb.org/viewtopic.php?f=3&t=49154&p=421135#p421094

# Other bug information

* **Priority:** urgent
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by MRx 2020-08-02 00:30
With FreeCad 0.19 I have to refine an object and create a simple copy.
With FreeCad 0.18 it's enough to refine the object and the history can be deleted.

Is this intended?

**Comment by wwmayer** [comment]
It's not necessarily a bug. If further operations still produce usable results I would just ignore the error messages.

Btw, OCC provides a lot of ShapeFix and ShapeUpgrade algorithms that we currently hardly use. It should be checked if applying them fixes the error messages.

Besides this a Repair workbench is something that we need sooner or later anyway. This is e.g. needed to fix defects when importing STEP or IGES files that are created from other CAD systems.
