### ISSUE TITLE
Improve setup of open wire profiling

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6104]
Issue imported from https://tracker.freecad.org/view.php?id=4435

* **Reporter:** gauna
* **Date submitted:** 9/14/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

Path generated by profil tool is located on the wrong side under certain circumstances. Maybe there are some rounding issues with "Final Depth". 

Thread with a more detailed description: https://forum.freecadweb.org/viewtopic.php?f=15&t=50172

# Steps to reproduce

See thread.

# FreeCAD Info

```
OS: Manjaro Linux (KDE//usr/share/xsessions/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22443 (Git)
Build type: Unknown
Branch: master
Hash: 3fd492fabe0868928a031507d94ff788a15286b5
Python version: 3.8.5
Qt version: 5.15.0
Coin version: 4.0.0
OCC version: 7.4.0
Locale: German/Germany (de_DE)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by russ4262 2020-12-07 06:29
This behavior is not so much a bug, as a error due to improper usage for open-edge profiling.  
 
True, selection of bottom edges for combined purposes of setting geometry and Final Depth is intuitive and logical.  However, due to the current implementation of the open-edge feature, it requires top edges be selected and a Final Depth to be set manually.  Perhaps rethinking the approach to profiling open-edges will yield a return to the ability to select bottom edges as a means to fewer user inputs and easier, simpler usage.

This requirement to select top edges is noted in the Usage section of the Profile wiki page and has been there since 15 September 2020 per wiki history.

---

### Comment by Kunda1 2020-12-07 11:24
russ4262 then should we flip this ticket to a 'feature' instead of a bug and reword it a bit to reflect why?

**Comment by sliptonic** [comment]
Open edge profiling has been thoroughly reworked.  closing the isssue.  please reopen if there's still missing functionality
