### ISSUE TITLE
FreeCAD menus and buttons very slow (Linux version) on ChromeOS (GPU Acceleration must be enabled)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6107]
Issue imported from https://tracker.freecad.org/view.php?id=4445

* **Reporter:** mrjohnc
* **Date submitted:** 9/26/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** resolved
* **Tags:** ChromeOS

# Original report text

FreeCAD menus and buttons [s]don't work[/s] respond very slowly on Linux version run on ChromeOS, this is true for installing through FlatHub, Snapstore and Appimage. Sometimes the menus change when you mouse over them so you can't click on anything, sometimes the blue background turns grey, flashing when the mouse moves. When the app first opens it is possible to select the menu options but they often don't seem to do anything. In an earlier version of Prusa Slicer I had a similiar issue but it seems that it was resolved.

# Steps to reproduce

Install FreeCAD 0.18 using snap, flathub or appimage
Open and try to use 

# FreeCAD Info

```
OS: KDE Flatpak runtime
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 783e134)
Hash: 783e1346c7a078f5265c3f0c6a927d09a8c1fe70
Python version: 3.7.4
Qt version: 5.14.2
Coin version: 4.0.0
OCC version: 7.3.0
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** none
* **Severity:** crash
* **Category:** Bug
* **Updated:** 3/13/2021
* **Fixed in version:** 0.19

# Discussion from Mantis ticket

### Comment by mrjohnc 2020-09-27 08:14
Just to add, when I try to use parts of the UI eg creating a new body parts of the UI disappear like the view controls and everything in the application box. Once I've tried to do this often FreeCAD stops responding and once closed when I try to repopen I just get a black screen and have to restart my laptop

---

### Comment by mrjohnc 2020-09-27 09:33
OK, it looks like the issue is being caused by GPU acceleration, disabling GPU acceleration for Linux apps means it runs. I'm not sure how to include this as a fix

---

### Comment by mrjohnc 2020-09-27 09:34
You can turn off GPU support by disabling chrome://flags/#crostini-gpu-support

---

### Comment by Kunda1 2020-09-27 11:19
mrjohnc, Thanks for the heads up. This is good to know.
A favor, next time please follow our tracker guidelines (yellow banner, top of page). It helps us with dealing with triage immensely. As you can see we are currently only accepting v0.19 bugs. Is this then something that can be replicated on v0.19? 
Try it quickly via [AppImage](https://wiki.freecadweb.org/AppImage)

CC chrisb (we may need to add this to Known Issues thread)

---

### Comment by mrjohnc 2020-09-27 11:48
Hi Kunda1

Thanks, I can confirm that the issues remain with 0.19 when GPU acceleration enabled although they're not quite as bad its still not usable. Again disabling GPU acceleration is a workaround

---

### Comment by openBrain 2020-10-09 21:27
mrjohnc : could you please paste the full information about the 0.19 version your tried ? Thx

---

### Comment by Kunda1 2020-10-22 11:26
mrjohnc ping

---

### Comment by Kunda1 2020-10-22 11:31
Updated ticket to reflect v0.19 only

---

### Comment by mrjohnc 2020-10-22 11:45
openBrain and Kunda1 thanks, its the latest version available on Flathub as of now. I'm happily using it with GPU acceleration turned off, I'm unsure if its an issue with the OS, Linux support is still in Beta. My suggestion would just be to have some guidance on ChromeOS installation with a little not to say 'if you have issues with the interface turn off GPU acceleration in chrome://flags

---

### Comment by Kunda1 2020-10-22 15:45
mrjohnc where do you propose we should display this note so ChromeOS users see it?
BTW, the problem goes away with GPU acceleration then? *confused*

---

### Comment by mrjohnc 2020-10-22 16:50
Kunda1

I think that instructions should live here  
https://wiki.freecadweb.org/Install_on_Unix

And then maybe a small note on this page in the Linux section on the downloads page saying something like 'including Chromebooks with Linux support' https://www.freecadweb.org/downloads.php 

The Chromebook instructions could be something like this, are you able to add it?

==Chromebooks with Linux support==
FreeCAD can be installed on Intel based Chromebooks with Linux support (link https://www.chromium.org/chromium-os/chrome-os-systems-supporting-linux)

# Enable Linux support (https://support.google.com/chromebook/answer/9145439?hl=en-GB)
# Enable Flatpak installation using the terminal (https://flatpak.org/setup/Chrome%20OS/)
# Install FreeCAD via Flathub using the command line instructions (https://flathub.org/apps/details/org.freecadweb.FreeCAD)
# Find FreeCAD in your Linux Apps folder 

Note: there is an issue with some Chromebooks which causes UI problems in FreeCAD, this can be solved by disabling Linux GPU acceleration in Chrome Flags (chrome://flags/#crostini-gpu-support)

----

There are some other ways to achieve installing it but this is the one with the least steps and most simple for new users.

---

### Comment by Kunda1 2020-10-22 19:27
kkremitzki what do you think? Should we put this on the site and/or the Github release page ?

---

### Comment by kkremitzki 2020-10-22 23:08
Sure, if there are platform-specific instructions needed, it seems pretty reasonable to expand the "For distro-specific instructions..." sentence on the downloads page to specifically mention them, as Chromebooks are extensively used in education.

---

### Comment by Kunda1 2020-12-12 12:52
sgrogan please update the 0.19 Release page mentioning Chromebook support. Here's the suggested text (please modify as you see fit)
```
#### Chromebook

We understand through our forum users that FreeCAD can successfully run on Chromebooks. The only caveat known to us is the need to enable GPU acceleration (Ticket [#4445](https://tracker.freecadweb.org/view.php?id=4445)) within FC. 
```

---

### Comment by mrjohnc 2021-01-15 23:55
Kunda1 sorry to miss this before, I think this is good, please can you add it?

---

### Comment by Kunda1 2021-02-20 18:01
pinged sgrogan via the forum. Hope he gets it this time ;)

---

### Comment by Kunda1 2021-02-20 20:39
sgrogan has added a note to the release page. Closing this ticket. 

---

### Comment by mrjohnc 2021-02-21 10:50
correcting message

---

### Comment by mrjohnc 2021-02-21 10:53
Kunda1, I just spotted an error in the message you suggested, it only works if you disable GPU acceleration, not enable it, it should read (adding a few more instructions)

Chromebook

We understand through our forum users that FreeCAD can successfully run on Chromebooks which have Linux support https://support.google.com/chromebook/answer/9145439?hl=en-GB. The only caveat known to us is the need to disable GPU acceleration via chrome://flags/#crostini-gpu-support The easiest way to install it is to enable Flatpak https://flatpak.org/setup/Chrome%20OS/ and then install using this link https://flathub.org/apps/details/org.freecadweb.FreeCAD

---

### Comment by Kunda1 2021-02-21 11:36
Sorry, mrjohnc, lots going on ATM. Thanks for the orientation. 

sgrogan please copy/paste (again) this corrected version to 0.19_pre Release page

```
## Chromebook

We understand through our forum users that FreeCAD can successfully run on Chromebooks which have [Linux support](https://support.google.com/chromebook/answer/9145439?hl=en-GB). The only caveat known to us is the need to disable GPU acceleration via `chrome://flags/#crostini-gpu-support` The easiest way to install it is to enable [Flatpak](https://flatpak.org/setup/Chrome%20OS/) and then install using this [link](https://flathub.org/apps/details/org.freecadweb.FreeCAD)
```

---

### Comment by Kunda1 2021-03-13 21:29
Ok, sorry for the delay! Too much going on. I've updated the release page to reflect the correct message.
https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre

Resolving

**Comment by adrianinsaval** [comment]
is this issue worth keeping? I think it's been dormant long enough that we can close it and chromeOS is not officially supported anyways. I don't think there's anything actionable here.
