### ISSUE TITLE
Zoom with mouse wheel is broken

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6111]
Issue imported from https://tracker.freecad.org/view.php?id=4452

* **Reporter:** Kryptal
* **Date submitted:** 10/7/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** feedback
* **Tags:** #pending-forum, 0.19, linux, mouse, UI, zoom

# Original report text

When working on any document (even a new one) the zoom functionality doesn't work when using the mouse wheel with any navigation style.
However, zooming is still possible using Ctrl + Wheel click and moving the mouse forward and backward with the following navigation styles : OpenInventor, Revit and Blender.

# Steps to reproduce

Use the mouse wheel to zoom on any document (a new one or one you already have. It doesn't change anything)

# FreeCAD Info

```
OS: Manjaro Linux (KDE//usr/share/xsessions/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22656 (Git)
Build type: Release
Branch: master
Hash: 1816a71d270c21e9657c99ed376138efb01f85b1
Python version: 3.8.5
Qt version: 5.15.1
Coin version: 4.0.0
OCC version: 7.4.0
Locale: French/France (fr_FR)

```

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Bug
* **OS: Manjaro Linux 20.1.1**
* **Platform:** PC
* **Updated:** 2/4/2022

# Discussion from Mantis ticket

### Comment by Kunda1 2020-10-08 01:13
Forum thread, per the guidelines, please?

---

### Comment by openBrain 2020-10-09 21:08
[Forum thread](https://forum.freecadweb.org/viewtopic.php?f=3&t=50231)

---

### Comment by Kunda1 2022-02-04 18:55
Kryptal can you recheck this on latest v0.20dev ?
The forum thread mentions that the issues may be fixed. See https://forum.freecadweb.org/viewtopic.php?p=568306#p568306

Edit: 
Commit associated with this ticket: https://github.com/FreeCAD/FreeCAD/commit/c9923ab15

**Comment by adrianinsaval** [comment]
issues is fixed according to forum discussion
