### ISSUE TITLE
[PATH] Engrave 'start at vertex'  gives wrong path

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6113]
Issue imported from https://tracker.freecad.org/view.php?id=4458

* **Reporter:** sliptonic
* **Date submitted:** 10/12/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** resolved
* **Tags:** 

# Original report text

The engraving operation allows for changing the vertex to start at.  Some values produce correct paths.  Others
produce paths that gouge the part.

# Steps to reproduce

Create a cube.   
Create a job and add an engrave operation
Select the four edges on the top face and add them to the base tab of the engrave
The path should generate correctly.
change the 'start at vertex' property to '3' and recompute

The starting position is recalculcated but the path now gouges the part and misses one edge.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by gauna 2020-12-13 16:28
PR:
https://github.com/FreeCAD/FreeCAD/pull/4136

---

### Comment by sliptonic 2020-12-16 00:09
https://github.com/FreeCAD/FreeCAD/pull/4136

---

### Comment by Kunda1 2020-12-22 00:48
07e2e8f

**Comment by luzpaz** [comment]
Previously resolved in #4136
