### ISSUE TITLE
Place and orientate dimension constraints in one go

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6120]
Issue imported from https://tracker.freecad.org/view.php?id=4472

* **Reporter:** Sandkuchen
* **Date submitted:** 10/23/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Concerned environment/workbench: Sketcher

Requested Feature: Ability to orientate the labels/arrows of dimensional constraints (aka drag them to a convenient place within the the sketch) while still being within the constraint command

The feature is described and to some degree discussed in https://forum.freecadweb.org/viewtopic.php?f=8&t=51125

The requested feature is not related to the consolidated dimension constraint tool (aka "Smart Dimension" etc.) described in https://forum.freecadweb.org/viewtopic.php?f=8&t=50521 apart from both requests dealing with dimensional constraints in general. Neither feature depends on the other; neither includes the other; neither makes the other obsolete; they don't come as a set.

# FreeCAD Info

```
OS: Windows 7 SP 1 (6.1)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22665 (Git)
Build type: Release
Branch: master
Hash: b0d7850406e046f3b7a8cd5da261e7d54df6bd99
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: German/Germany (de_DE)

```

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
@paddlestroke this looks like something you've been working on, right?

**Comment by PaddleStroke** [comment]
Dev branch : https://www.youtube.com/watch?v=J7khOBhch44&t=53s&ab_channel=FreeCADDevDiary
Video showing the tool : 
https://www.youtube.com/watch?v=J7khOBhch44

**Comment by luzpaz** [comment]
Thanks! 
Can you also add the forum thread to the above reply if you don't mind (so users can follow the development discussion)

**Comment by maxwxyz** [comment]
@PaddleStroke can this be closed now?

**Comment by PaddleStroke** [comment]
Yes
