### ISSUE TITLE
Thumbnail creation sometime fails.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6121]
Issue imported from https://tracker.freecad.org/view.php?id=4475

* **Reporter:** fcaduser
* **Date submitted:** 10/26/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** #pending-PR

# Original report text

About 20% of them are "blank" (ie using the default FC logo) within the start page.
This behavior is quite old but I still can't determine if there is a specific property of a file preventing the creation mechanism, it seems totally random.

# Steps to reproduce

# FreeCAD Info

```
OS: Debian GNU/Linux 10 (buster) (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22798 (Git)
Build type: Release
Branch: master
Hash: a29d834bd31fcf5dedfceb159c4d36c18194197f
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.5.0.beta
Locale: French/France (fr_FR)
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2020-10-27 01:03
Please link to the forum thread. 

---

### Comment by fcaduser 2020-10-28 10:47
Link to the forum about this :
https://forum.freecadweb.org/viewtopic.php?f=8&t=51493

---

### Comment by Kunda1 2020-11-24 12:38
Looks like someone is submitting a fix. See #4078  
Thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=48509&p=451098#p451063

---

### Comment by Kunda1 2020-12-06 19:57
[s]fcaduser please retest[/s]

---

### Comment by Kunda1 2020-12-06 19:59
drmacro care to weigh in?

---

### Comment by fcaduser 2020-12-12 15:35
Same problem with the last release.

--------------------------------
OS: Debian GNU/Linux 10 (buster) (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23073 (Git)     <--------------------------------------------------
Build type: Release
Branch: master
Hash: acf9b1f0de0b931ba767d1d3a3115627b35b441e
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.6.0.dev
Locale: French/France (fr_FR)

**Comment by luzpaz** [comment]
[Per fcaduser on the forum](https://forum.freecadweb.org/viewtopic.php?p=476590#p476590), this bug can't be reproduced on a latter v0.19
Closing ticket
