### ISSUE TITLE
Roof Overhang not removed by Arch:Remove Component

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6126]
Issue imported from https://tracker.freecad.org/view.php?id=4488

* **Reporter:** AndrewA
* **Date submitted:** 11/10/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

On the Roof:GarageEast the Structure has been removed using the Remove Component, however the overhang has been left.

https://forum.freecadweb.org/viewtopic.php?f=23&t=52035

# Steps to reproduce

Draw a polyline and produce a roof.
Produce a solid that intersects.
Use Arch:Remove Component to cut the roof.

The Overhang is left

# FreeCAD Info

```
OS: Debian GNU/Linux bullseye/sid (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22960 (Git) AppImage
Build type: Release
Branch: master
Hash: c5a4b01d2e4218bcc0eb6650337650a6c65ef0e4
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 3/8/2021

# Discussion from Mantis ticket

### Comment by Roy_043 2021-03-08 10:01
This issue has already been fixed:
https://github.com/FreeCAD/FreeCAD/pull/4054

**Comment by luzpaz** [comment]
Per @Roy-043 this was fixed in #4054 (https://github.com/FreeCAD/FreeCAD/commit/e06e3d7bb6e779170012aa5174e4b1ea0bc7bf2a)
