### ISSUE TITLE
Automate Link and ShapeBinder

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6132]
Issue imported from https://tracker.freecad.org/view.php?id=4502

* **Reporter:** Pauvres_honteux
* **Date submitted:** 11/25/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

See [Automate Link and ShapeBinder](https://forum.freecadweb.org/viewtopic.php?f=8&t=51608)
Today one must first create a link-holder/container based on what you want to fill it with AND use it for, then fill it with the targeted object/feature. I say the user should not be bothered with the internals of linking. She/he should only need to decide whether to create a link or not.

As seen in the forum thread I suggest it to be done as follows:

Copy/ctrl+c then paste/ctrl+v(= Link or No link or Result or As is or ... etc [user sets a default for this]) or right click and choose other paste options.
.
If the user wants a link, then chose that type of pasting.
.
If the user wants a plain copy without link, then chose that type of pasting.
.
... and so on and so forth.

# FreeCAD Info

```
OS: openSUSE Leap 15.1 (KDE//usr/share/xsessions/default)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.Unknown
Build type: Release
Python version: 3.6.5
Qt version: 5.9.7
Coin version: 4.0.0
OCC version: 7.5.0
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by Roy-043** [comment]
Closing...
