### ISSUE TITLE
Add depth support to vcarve operation

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6135]
Issue imported from https://tracker.freecad.org/view.php?id=4507

* **Reporter:** sliptonic
* **Date submitted:** 12/1/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** resolved
* **Tags:** 

# Original report text

Vcarve is currently 'centerline' engraving.  It derives its depths from the tool geometry.
However, the operation should have support for depths as well.  This would allow the user to set a maximum depth to keep the tool from going too deep in thin material.  It would also allow for step-down passes.

# FreeCAD Info

```
OS: Linux Mint 19.3 (i3/i3)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23137 +10 (Git)
Build type: Unknown
Branch: (HEAD detached at upstream/pr/4089)
Hash: 0c9536df0dc63e0a650b96dc8514aba07e9ffac9
Python version: 3.6.9
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by sliptonic 2020-12-02 21:06
vcarving is almost always done in a single pass. 
do not implement step-downs unless users identify a necessary use-case

---

### Comment by sliptonic 2020-12-02 21:10
https://github.com/FreeCAD/FreeCAD/pull/4102

---

### Comment by sliptonic 2020-12-16 00:07
https://github.com/FreeCAD/FreeCAD/pull/4143

---

### Comment by Kunda1 2020-12-22 00:56
c80adf8
b920bbf

**Comment by luzpaz** [comment]
Previously resolved in above mentioned PRs/commits.
