### ISSUE TITLE
round pocket exports as a hexagonal pocket in obj format. Is filled in solid in stl and 3mf formats. There is no gco export.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6137]
Issue imported from https://tracker.freecad.org/view.php?id=4509

* **Reporter:** 533online
* **Date submitted:** 12/11/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** feedback
* **Tags:** #post-to-forum

# Original report text

round pocket exports as a hexagonal pocket in obj format. Is filled in solid in 
stl and 3mf formats. There is no gcode export in FC 0.19.

I tried turning off curves as line segments in export preferences, but no go.
Every format I tried that is compatible with cura either fills in the pocket
as a solid, or converts the round pocket into a hexagonal pocket. Only when I 
loaded my fcstd model into Freecad 0.18.4 did the round pocket actually export 
as a round pocket in obj format. I am currently printing the model to confirm 
a successful print.

# Steps to reproduce

Create round pocket in model. I ain't tried it with a through hole.
Finish model. Export model in any format recognized by cura. Round 
pocket translates to hexagon in cura. To my knowledge, the latest 
cura has no issues that I am aware of. I'm pretty much a newbie to 
Freecad and cura and 3d printing, so this probably should be more 
thoroughly tested by some one with more experienced.

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23074 (Git)
Build type: Release
Branch: master
Hash: 74b866ed3022fd1452c534dae31a721bcc668f2f
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **OS: win 10**
* **Platform:** pc
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2020-12-12 13:36
Forum thread where the discussion happened before opening the ticket?
Please also choose a more friendly tracker username. Let me know and I will update it.

Edit: most up to date version of 0.19 at the time of this ticket is:
FreeCAD_0.19.***23258***-Win-Conda_vc14.x-x86_64.7z
FreeCAD_0.19.***23266***_Win-LPv12.1.6_vc14.x-x86-64.7z
Please make sure to test on the most up to date 0.19 before submitting bug reports to the forum. Thx.

---

### Comment by kisolre 2020-12-22 08:30
Body exports properly to STL and OBJ. Could you provide your exports for comparison?
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23489 (Git)
Build type: Release
Branch: master
Hash: a43736b04ec26745865ee78afa88c112c62d2dde
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Bulgarian/Bulgaria (bg_BG)

---

### Comment by Kunda1 2021-02-04 10:32
533online ping

**Comment by adrianinsaval** [comment]
no further comments form op and not enough info to act. I suspect the tesellation of the cirles might have made them look like polygons but have no way of checking. Should be closed IMO.
