### ISSUE TITLE
TechDraw page layout screwing up

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6146]
Issue imported from https://tracker.freecad.org/view.php?id=4527

* **Reporter:** Roeland Huys
* **Date submitted:** 1/2/2021
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** feedback
* **Tags:** #pending-forum, #tobeclosed, macOS

# Original report text

After deleting a dimension, the layout of the drawing page screws up.
I use MacOS Big Sur.

# Steps to reproduce

Create a new page using TechDraw toolbox
Insert Multiple linked views of drawable objects
Set scale to 0.5
Arrange the views in a convenient way
Add dimensions
Delete dimension
-> Message: "These items are linked to items selected for deletion and might break. Page"
Click OK
Observe how all views are messed up.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS:  Big Sur**
* **Platform:** macOS
* **Updated:** 1/25/2022

# Discussion from Mantis ticket

### Comment by Kunda1 2021-01-31 12:05
Please post to the forum next time. Please paste your full [About](https://wiki.freecadweb.org/About) info in the ***FreeCAD Information*** field next time. Please open a forum thread to discuss this issue. 

---

### Comment by Kunda1 2022-01-24 20:36
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=35&t=65637

---

### Comment by Kunda1 2022-01-25 12:52
no file was attached or full version info. OP please respond or we will close ticket very soon

**Comment by WandererFan** [comment]
No response.  Closing.
