### ISSUE TITLE
homebrew does not have a beer

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6148]
Issue imported from https://tracker.freecad.org/view.php?id=4531

* **Reporter:** qwerty_f
* **Date submitted:** 1/9/2021
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

When running homebrew to create FC on Big Sur it ends without success message. See [forum post](https://forum.freecadweb.org/viewtopic.php?f=4&t=51345&sid=bc6afb21106de82856c94f2113e271d3&start=120). At least there should be a message where to find the binary to start it manually. Of course a bundled app would be preferable.

# Steps to reproduce

brew install freecad --head

# FreeCAD Info

```
OS: macOS 11.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23648 (Git)
Build type: Release
Branch: master
Hash: 5b058a9f13c89bb374ddf77b93008d560822398c
Python version: 3.9.0
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.0
Locale: German/Germany (de_DE)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: OSX Big Sur**
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-01-31 12:01
Sorry vejmarie for the flood. 
which ticket do you want to keep? :P

**Comment by luzpaz** [comment]
Homebrew related tickets should be directed to https://github.com/FreeCAD/homebrew-freecad
CC @ipatch 

Closing
