### ISSUE TITLE
Sketcher: Add new method for trim sketch

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6152]
Issue imported from https://tracker.freecad.org/view.php?id=4544

* **Reporter:** Jee-Bee
* **Date submitted:** 1/25/2021
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** sketcher, trim

# Original report text

Add a new method for trimming multiple sketch lines at once.
Description of work flow
- Model a shape that needs a trim
- start trim tool
- click at some point and while clicking move the mouse
- All lines that are crossed remove them till nearest intersection(s)
See images for simple example

# Additional information

![image](https://user-images.githubusercontent.com/4140247/161437013-bdc453ad-c5ad-4441-92f6-2fa3b3256caf.png)
![image](https://user-images.githubusercontent.com/4140247/161437022-e9ab69d8-5b70-40e7-bf49-87122eab0b72.png)

see: https://forum.freecadweb.org/viewtopic.php?f=10&t=54441#p468692

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment]
@abdullahtahiriyo shares his perspective:
> It involves having a new mode in the trim tool and changing what to do when moving the mouse and clicking.
>I was thinking about this behaviour of deleting when there is nothing left after trimming: 

![Peek 25-01-2021 07-37](https://user-images.githubusercontent.com/4140247/161437094-af118cba-d304-4435-85f4-8d164907e0d2.gif)

**Comment by luzpaz** [comment]
CC @paddlestroke
