### ISSUE TITLE
Allow engraving of 3D paths.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6153]
Issue imported from https://tracker.freecad.org/view.php?id=4545

* **Reporter:** sliptonic
* **Date submitted:** 1/29/2021
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

engraving currently assumes 2D paths. In some cases it would be useful to engrave paths that have a z axis component.

# Additional information

forum thread
https://forum.freecadweb.org/viewtopic.php?f=15&t=54860&p=472185#p472185

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by sliptonic** [comment]
Not relevant.  functionality covered by basic pocketing and engraving
