### ISSUE TITLE
Arch:Stair - Connection issue between landing and second flight

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6154]
Issue imported from https://tracker.freecad.org/view.php?id=4548

* **Reporter:** @balrobs
* **Date submitted:** 1/31/2021
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

ATM using the Arch stair tool to create a HalfTurnLeft/HalfTurnRight stair with a single line as base element leads to a connection result between the landing and the seconf flight that can be improved!
See forum discussion with picture at https://forum.freecadweb.org/viewtopic.php?f=22&t=53018&start=30#p472079 

# Steps to reproduce

1) model an Arch Stair by creating a single line with a length i.e. 4500mm
2) change to the Arch workbench and select the line
3) press the Arch Stair button to generate an Arch Stair
4) in the Structure properties set Flight = HalfTurnLeft
5) observe the connection between landing and second flight

![image](https://user-images.githubusercontent.com/4140247/163652930-b140784c-0fad-454f-9151-8f3d4aebd938.png)

[RC-stair.zip](https://github.com/FreeCAD/FreeCAD/files/8498909/RC-stair.zip)

# FreeCAD Info

```
OS: Ubuntu 20.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Branch: unknown
Hash: 497ecbe0eb399dd2b873762e4406aa9569976870
Python version: 3.8.5
Qt version: 5.12.8
Coin version: 4.0.0
OCC version: 7.3.0
Locale: English/United States (en_US)
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @paullee0 2021-01-31 18:32
Another similar issue discussed in same thread -

[2nd Issue in Post - RC stairs macro ](https://forum.freecadweb.org/viewtopic.php?f=22&t=53018&start=20#p470657)

**Comment by Roy-043** [comment]
This problem has already been fixed.
