### ISSUE TITLE
PathGeom.edgeForCmd() function can't handle full-turn circles.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6155]
Issue imported from https://tracker.freecad.org/view.php?id=4551

* **Reporter:** sliptonic
* **Date submitted:** 2/3/2021
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

PathGeom.edgeForCmd() function is intended to take a Path Command (pseudo gcode) and return a corresponding Part Edge.

However, has an implicit assumption about the working plane.  The assumption is set by setting a G17/18/19 command to select the XY, XZ, YZ plane in which an arc will exist.  Arcs in other planes are not supported at all.

Since there are an infinte number of solutions to for a 360 degree arc that starts and ends on the same point and passes through another point at the midpoint, OCC throws an error.

# Additional information

PathGeom.edgeForCmd() should take a named argument for plane which defaults to the XY plane.
It should detect the full circle case and return a circular edge.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by sliptonic** [comment]
Resolved by https://github.com/FreeCAD/FreeCAD/pull/4446
