### ISSUE TITLE
Change workbench dropdown menu size along with toolbar icons

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6163]
Issue imported from https://tracker.freecad.org/view.php?id=4570

* **Reporter:** Huldar
* **Date submitted:** 2/16/2021
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

I posted to the forum first, here is the link [Forum post](https://forum.freecadweb.org/viewtopic.php?f=8&t=55684).

The feature request I want to make is that the workbench dropdown menu scales in size along with the toolbar icons when you change them through
Edit>Preferences>General>Size of toolbar icons

That's all :)
Thanks.

# Steps to reproduce

Go to 
Edit>Preferences>General>Size of toolbar icons

# FreeCAD Info

```
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

```

# Other bug information

* **Priority:** low
* **Severity:** tweak
* **Category:** Feature
* **Updated:** 2/16/2021

**Comment by luzpaz** [comment]
Forum post doesn't exist. Closing ticket
