### ISSUE TITLE
Sketcher does not report error

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6169]
Issue imported from https://tracker.freecad.org/view.php?id=4580

* **Reporter:** garya
* **Date submitted:** 2/28/2021
* **FreeCAD version:** 0.20
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

See discussion on 
[help forum](https://forum.freecadweb.org/viewtopic.php?f=3&t=56029&sid=cae9731349d24c2a6929a890bf2208b6)
In the development version of the code at which this is being reported, this bug *does actually report the error*, but that is only because of extra code chrisb pushed a workaround for another issue which will not be fixed in 0.19.  When that bug is fixed, this bug will reappear.
So this bug is being reported to not lose the issue.

# Additional information

from chrisb:
2) The not reporting the situation directly. With the latest master the error is reported directly as conflicting (one case appearing to defy the principle of causality in which the fix preceeds the bug report, though it is not really the case). This was "fixed" because a couple of days ago I pushed a "work-around" for another issue. The workaround includes executing an extra solve that should not be necessary, but it is because of a bug that will not be fixed in 0.19. The extra solve coincidentally also "fixes" the reporting. However, when this workaround is reverted because a proper solution is found for the bug in 0.20, this bug will appear again. So here it might makes sense to have a separate ticket for the reporting, not to lose the information on how to reproduce it.

# Steps to reproduce

[Bug_Sketcher_NotRedundant_2_5.zip](https://github.com/FreeCAD/FreeCAD/files/8492208/Bug_Sketcher_NotRedundant_2_5.zip)

- load the file Bug_Sketcher_NotRedundant_2_5.FCStd
- edit sketch Sk_Diamond
- set length of Edge2 to 0.4mm
-> The diamond shape collapses on itself, the top two legs folding down onto the bottom
   This is a violation of the L2_nrm_L3 constraint
-> solver reports 1 DOF
-> Report View shows
  Updating geometry: Error build geometry(2): Both points are equal
  Invalid solution from SQP(augmented system) solver
- close sketcher
-> an error is reported for the sketch. 

# FreeCAD Info

```
OS: FreeBSD 11.4-RELEASE-p6 (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.b2ca86d8d
Build type: Release
Python version: 3.7.9
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.0
Locale: C/Default (C)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/28/2021

**Comment by luzpaz** [comment]
CC @PLChris as you're mentioned in this ticket
