### ISSUE TITLE
Vcarve path cuts air above the part

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6180]
Issue imported from https://tracker.freecad.org/view.php?id=4602

* **Reporter:** Colin_W
* **Date submitted:** 3/23/2021
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=15&t=56990

When creating a Vcarve path from a shapestring the generated path is created above the surface,
bug confirmed with mlampert.

# FreeCAD Info

```
OS: Debian GNU/Linux 10 (buster) (KDE//usr/share/xsessions/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.19.1)
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 3/27/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-03-27 10:20
Confirmed in the forum thread.

**Comment by sliptonic** [comment]
Issue was resolved by https://github.com/FreeCAD/FreeCAD/pull/4680
