### ISSUE TITLE
Draft. snapping mode.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6182]
Issue imported from https://tracker.freecad.org/view.php?id=4604

* **Reporter:** tmplitmir
* **Date submitted:** 3/24/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** feedback
* **Tags:** #post-to-forum, snap

# Original report text

snapping mode does not work. does not work at all. equally negative result in different versions. (0.16, 0.18, 0.19)

# FreeCAD Info

```
OS: Fedora 27 (Twenty Seven) (KDE//usr/share/xsessions/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.19.1)
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Russian/Russia (ru_RU)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **OS: linux fedora 27**
* **Updated:** 6/29/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-03-24 17:26
Please open a forum thread as requested in the large banner at the top of the page. 

---

### Comment by marioalexis 2021-03-29 16:21
tmplitmir try unchecking Snap Near because it takes precedence over other snaps options (contrary to wiki ...).
From the video, it looks like you expect to use Snap Center but you are turning it off.

---

### Comment by marioalexis 2021-06-24 04:43
Kunda1 I think we can close this.

---

### Comment by jnxd 2021-06-29 18:22
Are attachments being deleted? I see the attached video is missing.

**Comment by yorikvanhavre** [comment]
I think this can be closed...
