### ISSUE TITLE
Export of .obj files inconsistant between Wavefront and Alias Mesh

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6187]
Issue imported from https://tracker.freecad.org/view.php?id=4611

* **Reporter:** @macdroid53
* **Date submitted:** 3/30/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** new
* **Tags:** OBJ

# Original report text

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=57195

When exporting an assembly:
Wavefront export appears to ignore the deviation property of a feature. Alias mesh uses the deviation value.
Wavefront export adds the feature name to the item in the export, exporting multiple items. Alias mesh exports a single monolithic item

# Steps to reproduce

1. Create an assembly (I used A2+)
1. set the deviation value on features to differ values.
1. Select features export with Wavefront selected.
1. Select same features, export with Alias Mesh

Import each .obj file in Blender.

Example: 
![image](https://user-images.githubusercontent.com/4140247/167323989-adbb2c9d-84c2-4630-9b6a-d6159bb29c72.png)
The default of 0.5 (on the left) versus 0.01 (on the right) after import to Blender:

# FreeCAD Info

```

OS: Ubuntu 20.04.2 LTS (XFCE/ubuntustudio)
Word size of FreeCAD: 64-bit
Version: 0.20.24640 (Git)
Build type: Unknown
Branch: master
Hash: afa40aa0493309013e2e0dc5199523ef1f4c046c
Python version: 3.8.5
Qt version: 5.12.8
Coin version: 4.0.0
OCC version: 7.5.1
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Ubuntu 20.04**
* **Platform:** PC
* **Updated:** 3/30/2021

**Comment by luzpaz** [comment]
CC @PLChris (just a heads up since you participate on the forum thread)

@yorikvanhavre any idea who could tackle this issue?

**Comment by adrianinsaval** [comment]
`obj.ViewObject.AngularDeflection` ? however it's a vale in degrees, not sure what unit is 0.7 in or if it's a percentage

**Comment by luzpaz** [comment]
rebumped forum discussion
