### ISSUE TITLE
When trying to create reference radius/diameter from dialog it is always created as real one.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6197]
Issue imported from https://tracker.freecad.org/view.php?id=4627

* **Reporter:** kisolre
* **Date submitted:** 4/9/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

When a dimensional constraint is created there is a "Reference" check box in the dialog, which when checked should allow creation of reference constraint without having to switch constraint creation mode before head. This does not work then creating radius/diameter constraints. The other ones (distance, angle) work as expected.

# Additional information

[Forum thread](https://forum.freecadweb.org/viewtopic.php?f=3&t=57584)

# Steps to reproduce

Create an arc/circle. Try to dimension its radius. Check the "Reference" checkbox to try to create reference constraint. Confirm dialog. Real constraint is created instead.

# FreeCAD Info

```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.20.24673 (Git)
Build type: Release
Branch: master
Hash: e66ed26769ce8affe0a4ed330ff0435f4802f05e
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Bulgarian/Bulgaria (bg_BG)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 7/29/2021

# Discussion from Mantis ticket

### Comment by openBrain 2021-04-19 20:06
[Pull request](https://github.com/FreeCAD/FreeCAD/pull/4744)

---

### Comment by openBrain (private) 2021-07-29 15:59
Kunda1 : may you have a look as it seems Source Integration missed the commit ? https://github.com/FreeCAD/FreeCAD/commit/7a7cfcd9175a2c32a2d9a3eea0561f313dda90fc
Thx

**Comment by 0penBrain** [comment]
Has been fixed by #4744
