### ISSUE TITLE
[Arch] "Show Fill" in ArchView-TechDraw no longer works

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6208]
Issue imported from https://tracker.freecad.org/view.php?id=4646

* **Reporter:** @bitacovir 
* **Date submitted:** 4/27/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** new
* **Tags:** 0.19, Arch

# Original report text

It seems Show Fill set to True no longer works for ArchWall in TechDraw with ArchView.
Forum discussion for more information: https://forum.freecadweb.org/viewtopic.php?f=23&t=57534
Bug in FC 0.19 and 0.20
Maybe assign this to @yorikvanhavre ?

[Test_ TechDraw-ArchView_ ArchWall_05_ No Fill Bug.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/8460893/Test_.TechDraw-ArchView_.ArchWall_05_.No.Fill.Bug.FCStd.zip)

# FreeCAD Info

```
OS: Windows 10 Version 1909
Word size of FreeCAD: 64-bit
Version: 0.20.24587 (Git)
Build type: Release
Branch: master
Hash: 1f62d4666102d8efd4d8f3ba58a1037456a3bcfb
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: windows 10**
* **Updated:** 4/27/2021

**Comment by luzpaz** [comment]
Attached test file to ticket

**Comment by luzpaz** [comment]
bumped forum thread

**Comment by yorikvanhavre** [comment]
There were two problems here, that are solved by the above PR:
- The fill had a default white color so it was not noticeable. If the section plane's "UseMaterialColor" option is turned on, fills will now take the object color if no material is defined
- The fill didn't update when the object color changed. This is now solved too
