### ISSUE TITLE
[Path] Relative location of Toolbit files

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6209]
Issue imported from https://tracker.freecad.org/view.php?id=4647

* **Reporter:** dubstar_04
* **Date submitted:** 4/28/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

It's currently not possible to create a toolbit library using relative paths. 

This means that is not possible to share libraries between machines / different OS'

https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Path/PathScripts/PathToolBit.py#L107-L117

https://forum.freecadweb.org/viewtopic.php?f=15&t=58174&sid=5c2c7fda248c0380c556a4813e7f749b

# Steps to reproduce

1. Delete FreeCAD config
2. Create completely new tool library in an empty directory
3. Create a toolbit
4. check fctl and tctb

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 9/3/2021

# Discussion from Mantis ticket

### Comment by dubstar_04 2021-05-04 06:48
Forum Link: https://forum.freecadweb.org/viewtopic.php?f=15&t=58174&sid=3d0acf6eccb83839ec06242a3d5469f7

---

### Comment by russ4262 2021-07-25 04:09
PR #4906 contains a possible fix for this issue.

---

### Comment by russ4262 2021-09-03 22:03
dubstar_04, sliptonic
Has this issue been fixed?  Are we accepting PR #4906 as the fix for this bug, or only a partial fix since it limits the scope of the relative paths to within a given set of `Library`, `Bit`, and `Shape` folders?  Any ideas?

---

### Comment by russ4262 2021-09-03 22:19
I can confirm bug as reported.

**Comment by dubstar-04** [comment]
This specific issue is resolved for me.
