### ISSUE TITLE
planarFaceFromExtrusionEdges: sub is not defined

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6221]
Issue imported from https://tracker.freecad.org/view.php?id=4668

* **Reporter:** oscar
* **Date submitted:** 5/27/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** new
* **Tags:** 0.19, Path

# Original report text

The method planarFaceFromExtrusionEdges() in src/Mod/Path/PathScripts/PathPocketShape.py, line 735 of current HEAD (https://github.com/FreeCAD/FreeCAD/blob/c6771853ae951f5d4fb029f3423ce2132f0ba22b/src/Mod/Path/PathScripts/PathPocketShape.py#L735), there is a variable that is not defined.

# Additional information

19:46:37  Traceback (most recent call last):
  File "/tmp/.mount_freeca7dqM3T/usr/Mod/Path/PathScripts/PathUtils.py", line 60, in new_function
    res = function(*args, **kwargs)
  File "/tmp/.mount_freeca7dqM3T/usr/Mod/Path/PathScripts/PathOp.py", line 552, in execute
    result = self.opExecute(obj)  # pylint: disable=assignment-from-no-return
  File "/tmp/.mount_freeca7dqM3T/usr/Mod/Path/PathScripts/PathAreaOp.py", line 392, in opExecute
    aOS = self.areaOpShapes(obj) # pylint: disable=assignment-from-no-return
  File "/tmp/.mount_freeca7dqM3T/usr/Mod/Path/PathScripts/PathPocketShape.py", line 357, in areaOpShapes
    if not self.clasifySub(subBase, sub):
  File "/tmp/.mount_freeca7dqM3T/usr/Mod/Path/PathScripts/PathPocketShape.py", line 773, in clasifySub
    (planar, useFace) = self.planarFaceFromExtrusionEdges(face, trans=True)
  File "/tmp/.mount_freeca7dqM3T/usr/Mod/Path/PathScripts/PathPocketShape.py", line 696, in planarFaceFromExtrusionEdges
    fName = sub + '_face_' + str(fCnt)
<class 'NameError'>: name 'sub' is not defined

# Steps to reproduce

* Create an SVG with a rectangle and a circle inside
* Import the SVG file as geometry
* Convert both paths to sketches
* Extrude the rectangle sketch, and make a hole on it using the circle sketch
* Open Path workbench and try to create a pocket operation using the hole

# FreeCAD Info

```
OS: Ubuntu 20.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.19.1)
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Spanish/Spain (es_ES)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **OS: Ubuntu 20.04**
* **Platform:** Linux
* **Updated:** 7/26/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-06-02 20:36
oscar Thanks for the effort, but our guidelines are to post to the forum first. the v0.19 that you're using is already inferior since Path development is very rapid. Please test on v0.20 dev appimage from https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds 

---

### Comment by oscar 2021-06-04 05:49
Kunda1 thank you for reviewing the issue! I'm sorry for not posting first in the forum, I tried, but I did not very well understand the proper place :/ 
Also, note please that provided list is for the latest code (the HEAD of the master branch), and the code is still there :D 

Thanks and sorry again, I'll try to follow the rules :)

---

### Comment by oscar 2021-06-04 05:53
Kunda1 You are right!! I've checked the real master branch, and I see a lot of changes!! That's good! :) 
I'll clone the latest repo and try again.

Thank you!

---

### Comment by russ4262 2021-07-25 04:05
oscar
Buenas noches, señor.  ¿Cómo está?  Me llamo Russell y me interesa el problema que usted ha reportado aquí. ¿Todavía existe el problema con la version más actual de FreeCAD «master»?  Se lo menciono porque el archivo PathPocketShape.py ya no contiene 773 líneas indicado en el texto del error publicado.  También nos ayudaría si usted adjuntara un archivo sencillo de FreeCAD que produce el error.

Hablo inglés mejor que el español.

Gracias.

---

### Comment by oscar 2021-07-26 07:14
russ4262 Thank you very much for taking the time and see the issue! I've checked the latest version of the source code and, as you say, that file has been heavily refactorized! I need to test again using the latest version, and if it still fails, then I'll report back and attach a sample file.

Thanks again!

**Comment by luzpaz** [comment]
Since code was 'heavily refactored' most likely fixed and we haven't heard back from OP...
@Russ4262 I'm closing this ticket.
