### ISSUE TITLE
FreeCAD cannot execute in Surface Pro X ARM based 64-bit system

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6225]
Issue imported from https://tracker.freecad.org/view.php?id=4674

* **Reporter:** jose-giraldez
* **Date submitted:** 6/1/2021
* **FreeCAD version:** 0.19
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

[forum thread](https://forum.freecadweb.org/viewtopic.php?f=3&t=52193)

Even though Microsoft's Surface Pro X, which is ARM based architecture, Windows 10 ARM, still can execute all x86 software by using internal x86 emulator. 
It works for most software so far, with minor exceptions... I guess FreeCAD 0.19 is an exception can cannot execute in Windows 10 ARM

After Apple annoucement in 2020 and other major OEM (DELL, HP, ETC) laptops are migrating to ARM architecture.
It is time FreeCAD fixes compatibility issues with Windows ARM. 

# Steps to reproduce

Install FreeCAD 0.19.x 
Execute FreeCAD
Windows gives error "Cannot execute program" 

# Other bug information

* **Priority:** high
* **Severity:** crash
* **Category:** Feature
* **Updated:** 6/1/2021

**Comment by luzpaz** [comment]
'jmaustpc' writes: 
>According to wikipedia https://en.wikipedia.org/wiki/Surface_Pro_X
you have bought a computer with an ARM cpu not x86. Very bad idea if you want easy access to compatible software. Although their performance is improving all the time, ARM is still a primarily low power energy efficient risk architecture cpu. For power applications like CAD, x86 makes more sense at this point in history.
>
>Also not that (I only just found out) some new computers are now being sold with a cut down/restricted Windows that will only allow you to install applications from the MS application store! So make sure you have a "real" non-restricted Windows on any new machine, or at least understand what you are buying.
>
>I know some here have succeeded in getting FreeCAD up and running on a Raspberry PI 4, which has an ARM CPU, but that is on Linux with a full open source stack, so less issues compiling. I have no idea if anybody has yet or ever will compile for Windows ARM.
>
>At this point in history, the best energy efficiency yet powerful new CPU is the AMD Ryzen series, the latest just release is leaving Intel in the dust for energy efficiency but also outright performance.

**Comment by luzpaz** [comment]
Per a user 'Mallen' on the [forum thread](https://forum.freecadweb.org/viewtopic.php?p=554717#p554717):
> The surface pro x at that time only ran 32 bit programs. With windows 11 it can run 64 bit Intel code but freecad still won't run. However, it can run Linux programs with a gui now. The arm64 linux version can be installed with apt-get install freecad. The graphics won't have full hardware acceleration until they releases wddm 3.0 compliant driver though.

**Comment by rozmansi** [comment]
I have just confirmed FreeCAD x64 works on Windows 11 ARM (Microsoft Surface Pro X) provided [OpenCL™ and OpenGL® Compatibility Pack](https://apps.microsoft.com/store/detail/opencl%E2%84%A2-and-opengl%C2%AE-compatibility-pack/9NQPSL29BFFF?hl=en-us&gl=us) from the Microsoft Store is installed first.

**Comment by adrianinsaval** [comment]
Emulation is not a supported usecase. If it doesn't work then it's a problem in the emulation not in FreeCAD. Later on we might be able to produce arm native binaries for windows.

If WSL is available on arm too you could try running the linux arm native version.
