### ISSUE TITLE
Gcode generated by Path engrave skips some lines

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6232]
Issue imported from https://tracker.freecad.org/view.php?id=4685

* **Reporter:** mhindi
* **Date submitted:** 6/16/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=15&p=510599#p510599

I produced a sketch part of which is in the attached image (sketcher_lines_bug_report.png). I created a Path Job with the sketch selected, and added an engrave operation to the job. The generated engrave path (path_engrave_bug_report.png, attached), is missing line segments from the "6" at the beginning, and the "Upsilon" (fourth character), while other characters have a correct engrave paths.
I uploaded a file just including the "6" sketch to the forum and one of the respondents got the same result - missing the upper part of the "6". The file FreeCAD with the "6" sketch (but not the Path job, since it references a local tool) is attached.

# Steps to reproduce

1- The lines in the sketch are produced via a script that reads a Hershey font in an SVG format. The script produces "Part::Feature" objects that are then converted to a sketch, via Draft->birectional Draft to sketch icon.
2- Select the resulting sketch
3- Create a Job from the Path workbench.
4- Add an engrave operation, Accept.
5- The resulting engrave path misses some lines.
(N.B., if the sketch is selected and converted back to individual Draft elements via (Draft->bidirectional Draft object to sketch icon) and the resulting draft objects engraved, the resulting operation produces the correct, complete figure "6".) 

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Platform:** Linux
* **Updated:** 6/16/2021

# Discussion from Mantis ticket

### Comment by mhindi 2021-06-16 17:08

---

### Comment by mhindi 2021-06-16 17:12
I get an error when I try to attach the images and the file. Something about directory not being writable. Please advise how to attach the files dragging and dropping to the upload seems not to work. (The total size is less than 2 MB.)

---

### Comment by mhindi 2021-06-16 17:18
https://drive.google.com/file/d/1L0BXlSnecxE41kTtPY2fVwD9b5S8kuUR/view?usp=sharing, https://drive.google.com/file/d/1VwgQM76TabZu_oX3cGihCFnad0eGRn1r/view?usp=sharing

---

### Comment by mhindi 2021-06-16 17:49
Link to the FreeCAD file containing the "6" sketch.

https://drive.google.com/file/d/1ahe75VIeMdZQNHkvYa0kr4zZxRZ4fvbI/view?usp=sharing

**Comment by sliptonic** [comment]
Resolved by PR  https://github.com/FreeCAD/FreeCAD/pull/6394
