### ISSUE TITLE
[Path] Arrays are not included in the Path Simulation

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6241]
Issue imported from https://tracker.freecad.org/view.php?id=4704

* **Reporter:** Giulio Buccini
* **Date submitted:** 7/11/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** resolved
* **Tags:** Path

# Original report text

An "Array" operation is not displayed by the Path-Simulator. Only the original, single, operation is shown after pressing the "Play" button.
On the other side, the generated g-code is correct.

The Freecad file is attached.

# Additional information

The "active" property must be added and flagged to true, as depicted in the thread.

# Steps to reproduce

Refer to thread:
https://forum.freecadweb.org/viewtopic.php?f=15&t=60049&sid=5dcbec38eac8eb4c4b843c6e5ada0615

# FreeCAD Info

```
OS: Ubuntu 16.04.7 LTS (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Platform:** Ubuntu
* **Updated:** 9/3/2021
* **Fixed in version:** 0.2

# Discussion from Mantis ticket

### Comment by russ4262 2021-07-25 03:33
Fix is contained in PR #4818.

---

### Comment by russ4262 2021-09-03 22:13
[PR #4818](https://github.com/FreeCAD/FreeCAD/pull/4818)

**Comment by luzpaz** [comment]
Closed  by @Russ4262 in #4818
