### ISSUE TITLE
[FEM] More than 3 yield points in FEM_MaterialMechanicalNonlinear

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6246]
Issue imported from https://tracker.freecad.org/view.php?id=4720

* **Reporter:** @FEA-eng
* **Date submitted:** 8/6/2021
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** FEM, material

# Original report text

Currently only 3 yield points can be defined in FEM_MaterialMechanicalNonlinear (plasticity definition). It should be fairly simple to add a possibility to define more points so that a full stress-strain curve can be approximated. Ideally, there should be no limitation on the number of yield points at all. But if a limit can't be avoided due to coding issues then let's increase it significantly.

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=18&t=57382

Previous forum thread with the discussion about this limitation: https://forum.freecadweb.org/viewtopic.php?f=18&t=51756

# FreeCAD Info

```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Polish/Poland (pl_PL)
```

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 8/6/2021

# Discussion from Mantis ticket

### Comment by @luzpaz 2021-08-06 20:43
NewJoker thanks. BTW, if you're using FEM, please make sure to use the dev version as opposed to what you reported using in this ticket 'Version: 0.19.24276 (Git)' since FEM development progresses in bursts and changes are rarely backported.

**Comment by FEA-eng** [comment]
This issue can be closed since #5024 resolved it.
