### ISSUE TITLE
Creating a 2D path job for ShapeStrings fails

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6258]
Issue imported from https://tracker.freecad.org/view.php?id=4745

* **Reporter:** mclane
* **Date submitted:** 9/17/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** new
* **Tags:** Path

# Original report text

see forum [thread](https://forum.freecadweb.org/viewtopic.php?f=15&t=62250)

The creation of a path job with a 2D ShapeString fails with a Python error. This seems to happen only in Linux environments, not in Windows. However, the Python versions are different, see forum thread.

# Additional information

09:10:50  Traceback (most recent call last):
  File "/usr/lib/freecad/Mod/Path/PathScripts/PathStock.py", line 153, in onChanged
    self.execute(obj)
  File "/usr/lib/freecad/Mod/Path/PathScripts/PathStock.py", line 147, in execute
    shape = Part.makeBox(self.length, self.width, self.height, self.origin)
<class 'ValueError'>: height of box too small
09:10:50  PathJobGui.ERROR: height of box too small
09:10:50  Traceback (most recent call last):
09:10:50    File "/usr/lib/freecad/Mod/Path/PathScripts/PathJobGui.py", line 1561, in Create
    obj = PathJob.Create("Job", base, template)
09:10:50    File "/usr/lib/freecad/Mod/Path/PathScripts/PathJob.py", line 718, in Create
    obj.Proxy = ObjectJob(obj, models, templateFile)
09:10:50    File "/usr/lib/freecad/Mod/Path/PathScripts/PathJob.py", line 244, in __init__
    obj.Stock = PathStock.CreateFromTemplate(obj, json.loads(stockTemplate))
09:10:50    File "/usr/lib/freecad/Mod/Path/PathScripts/PathStock.py", line 390, in CreateFromTemplate
    return CreateFromBase(job, neg, pos, placement)
09:10:50    File "/usr/lib/freecad/Mod/Path/PathScripts/PathStock.py", line 267, in CreateFromBase
    obj.Proxy.execute(obj)
09:10:50    File "/usr/lib/freecad/Mod/Path/PathScripts/PathStock.py", line 147, in execute
    shape = Part.makeBox(self.length, self.width, self.height, self.origin)
09:10:50  ValueError: height of box too small
09:10:50  

# Steps to reproduce

1.  Create new document
2.  Go to Draft workbench and create ShapeString
3.  Go To Path workpench and click on CreatePathJob; check 2D ShapeString and click ok
4.  --> Python error is thrown

# FreeCAD Info

```
OS: Manjaro Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.20.25697 (Git)
Build type: Release
Branch: master
Hash: da918350c9efbd7751bd7e48a71cd4bded571500
Python version: 3.9.6
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **OS: Linux Manjaro**
* **Platform:** X86-64
* **Updated:** 9/17/2021

**Comment by sliptonic** [comment]
I'm not sure when this was fixed but the problem cannot be replicated anymore.  closing
