### ISSUE TITLE
Wrong shape generation for ArchStructure with non-normalized node coordinates

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6264]
Issue imported from https://tracker.freecad.org/view.php?id=4751

* **Reporter:** hlg
* **Date submitted:** 9/24/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

When a beam is created, nodes are normalized to the internal model with second node at (positive length, 0,0) and rotation, hence beam axis aligned to local x-axis and rotation stored in placement. Then subsequently, only length and rotation are used for shape generation. For example, if a beam is entered with node coordinates (0,0,0) and (-4010,0,0), they are normalized to (0,0,0) and (4010,0,0) and the structure rotation will be set to 180° around z-axis (see example file in [forum discussion](https://forum.freecadweb.org/viewtopic.php?f=39&t=61835).

With a legacy file, where at one point apparently shapes where generated differently and node coordinates where not normalized, the once properly generated shape may have a wrong orientation after recompute. Also, when node coordinates are edited directly, they are not normalized and length and rotation are not updated, leading to the same discrepancy between node coordinates and shape.

Instead, I believe normalization should be checked and recalculated to the internal model before shape generation and on change of node coordinates, but I cannot oversee the implications on previous behaviour and potential legacy files.

# Steps to reproduce

1. Open the file from forum https://forum.freecadweb.org/download/file.php?id=163600.
2. Switch on node display for the structure and observe generated shape.
3. Recompute shape.
4. The shape will be in the wrong place.

# FreeCAD Info

```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 9/24/2021

**Comment by yorikvanhavre** [comment]
This is probably solved already. When opening the given test file, the nodes are correctly regenerated.
For the other issue, that manually-set nodes are not recomputed on shape change, I don't see what needs to be done there, it requires probably more discussion and possibly a more in-depth refactoring.
I'm going to close this because there is nothing more to be done for now, don't hesitate to reopen if needed.
