### ISSUE TITLE
Objects jumping and appearing randomly I - drawing a Dimension moves object

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6265]
Issue imported from https://tracker.freecad.org/view.php?id=4753

* **Reporter:** tudorapo
* **Date submitted:** 9/25/2021
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** #post-to-forum

# Original report text

When trying to add a dimension to an object, another object jumps around. In the screenshot I'll try to attach the I tried to add a dimension to the pentagonal object on the lower right corner and the "bounding box", actually the walls of the room jumped up and left. 

# Steps to reproduce

1. add a dmiension
2. watch your object fly.

# FreeCAD Info

```
OS: Ubuntu 21.04 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.20.
Build type: Release
Branch: unknown
Hash: 582c26ea8b5f9d85957a6cb1bf798839fa2ce94c
Python version: 3.9.5
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** high
* **Severity:** major
* **Category:** Bug
* **OS: Ubuntu  21.4**
* **Platform:** PC
* **Updated:** 10/15/2021

# Discussion from Mantis ticket

### Comment by openBrain 2021-10-13 13:42
tudorapo : a single forced recompute of your file makes the frame to jump. No link with adding a direction.
Please check your file and if you think there is still a problem, please open a new thread in our forum per our reporting guidelines. Thx

---

### Comment by tudorapo 2021-10-14 17:56
I'm sorry, I did not do any forced recomputing and I did not create any frame, that's an object I draw.
Your reply thus makes no sense for me.

---

### Comment by openBrain 2021-10-15 08:20
tudorapo : I'm not so familiar with Arch.
Please do a forced recompute on your document (RMB on document name in the tree -> Mark to recompute -> F5) and you'll see the wall (what I previously called frame, but now I guess it's a wall) will jump. So for sure it's not linked to adding dimension. And I suspect it's a problem in your model.

**Comment by Roy-043** [comment]
OpenBrain's analysis is correct. This issue can be closed.
