### ISSUE TITLE
When creating a wall from a rectangle in Arch it makes a oversize wall on the outskirts of the area for manipulation

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6267]
Issue imported from https://tracker.freecad.org/view.php?id=4756

* **Reporter:** SB
* **Date submitted:** 9/29/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** new
* **Tags:** #post-to-forum

# Original report text

I can't sign up for forums, it won't let me sign up.
Separately in FreeCAD I just create a rectangle in Arch and want it to make a wall.
What it does is make a oversized wall on the perimeters of the platform to make the architecture and all that was expected for a wall to be made with the perimeters of the rectangle.

# Steps to reproduce

1. Open FreeCAD 0.19
2. Pick new project
3. Pick Arch
4. make rectangle
5.turn off face of rectangle: make false
6.highlight rectangle
7.pick wall and click on rectangle
8. Oversize wall outside perimeters of Area for manipulation shows up instead of on rectangle
9. must zoom out and rotate to see incorrect wall.

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **OS: Windows 2010**
* **Updated:** 10/13/2021

# Discussion from Mantis ticket

### Comment by doia 2021-10-01 09:15
This is actually the normal and expected behaviour. The Arch Wall is created from all 4 edges of the drawn rectangle, making it a rectangular shape enclosed by 4 walls. The drawn rectangle acts as the base line for the walls. You can now change the orientation of the walls on this base line to center/left/right. If you want to create a single straight wall, use the Draft_Line command (draw a single line), select this line and then select Arch_Wall.

Maintainer -> please close this ticket as it is no bug.

---

### Comment by SB 2021-10-02 02:52
That's not is what is happening to mine. It produces a wall outside the perimeters of the area for manipulation that is not along the rectangle produced and the wall is extremely large but  now I don't even get a wall but an error message when I try the same procedure.

![image](https://user-images.githubusercontent.com/4140247/157747511-9c81dd0f-f804-498e-9b7e-15c53a4bc1a1.png)

---

### Comment by doia 2021-10-02 08:43
Could you please post your version information and a simple example file -> point 4 and 6 of the really BIG yellow banner!

---

### Comment by SB 2021-10-03 02:19
I thought that I already put in the version as 0.19 in product and I don't know how to do a simple example file.
I don't know what to do now to show the problem.

---

### Comment by SB 2021-10-03 02:20
Can I show an example in the notes?

---

### Comment by openBrain 2021-10-13 13:59
SB : please open a new thread in our forum to discuss your issue with the community ([per our reporting guidelines](https://forum.freecadweb.org/viewtopic.php?f=3&t=5236))

---

### Comment by SB 2021-10-13 14:23
The forum wouldn't let me on. This tracker is the only place I can go.

---

### Comment by doia 2021-10-13 14:45
Then please try one of the other discussion boards like Reddit, Discord or Gitter. You will find the links to these on the https://www.freecad.org main page at the bottom. There you can sort out your problems with the forum access and will get more help with your problem in creating an Arch wall.

---

### Comment by SB 2021-10-13 22:28
If your implying you want this taken down I don't know how to do that. What do I do to take it down?

**Comment by yorikvanhavre** [comment]
This is most probably a manipulaiton or understanding error from the OP, but it is hard to know what from the given feedback. I can confirm building a wall from a rectangle works as expected. Closing this issue now becaue of lack of feedback. Please reopen if needed.
