### ISSUE TITLE
Crashing when extending dimension

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6269]
Issue imported from https://tracker.freecad.org/view.php?id=4760

* **Reporter:** electro707
* **Date submitted:** 10/8/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** confirmed
* **Tags:** #post-to-forum

# Original report text

When changing the length of a certain sketch's geometry in the attached file from 3mm to 4mm or 5mm, FreeCAD crashes with the attached debug trace with a segmentation fault.

# Additional information

Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3cda0) [0x7f8b333aeda0]
#1  0x7f8a7913bae8 in Geom2d_Curve::Value(double) const from /usr/lib/libTKG2d.so.7+0x18
#2  0x7f8a7b5ba94d in ChFi3d_Builder::PerformMoreThreeCorner(int, int) from /usr/lib/libTKFillet.so.7+0xb73d
#3  0x7f8a7b59db6f in ChFi3d_Builder::PerformIntersectionAtEnd(int) from /usr/lib/libTKFillet.so.7+0x80bf
#4  0x7f8a7b5a28ac in ChFi3d_Builder::PerformOneCorner(int, bool) from /usr/lib/libTKFillet.so.7+0x2d2c
#5  0x7f8a7b53fa59 in ChFi3d_Builder::PerformFilletOnVertex(int) from /usr/lib/libTKFillet.so.7+0x499
#6  0x7f8a7b540ad3 in ChFi3d_Builder::Compute() from /usr/lib/libTKFillet.so.7+0xfa3
#7  0x7f8a7b6d52ce in BRepFilletAPI_MakeFillet::Build() from /usr/lib/libTKFillet.so.7+0x2e
#8  0x7f89dc5a7479 in PartDesign::Fillet::execute() from /usr/lib/freecad/lib/_PartDesign.so+0x3e9
#9  0x7f8b352e3f62 in App::DocumentObject::recompute() from /usr/lib/freecad/lib/libFreeCADApp.so+0x122
#10  0x7f8a8c76bdea in Part::Feature::recompute() from /usr/lib/freecad/lib/Part.so+0xa
#11  0x7f8b3525fead in App::Document::_recomputeFeature(App::DocumentObject*) from /usr/lib/freecad/lib/libFreeCADApp.so+0x33d
#12  0x7f8b3527b314 in App::Document::recompute(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> > const&, bool, bool*, int) from /usr/lib/freecad/lib/libFreeCADApp.so+0x8f4
#13  0x7f8b35335eed in App::DocumentPy::recompute(_object*) from /usr/lib/freecad/lib/libFreeCADApp.so+0x2dd
#14  0x7f8b353360b9 in App::DocumentPy::staticCallback_recompute(_object*, _object*) from /usr/lib/freecad/lib/libFreeCADApp.so+0x29
#15  /usr/lib/libpython3.9.so.1.0(+0x148f08) [0x7f8b34ba2f08]
#16  /usr/lib/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x2e3) [0x7f8b34b8b333]
#17  /usr/lib/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x52a8) [0x7f8b34b87218]
#18  /usr/lib/libpython3.9.so.1.0(+0x126fd9) [0x7f8b34b80fd9]
#19  /usr/lib/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x51) [0x7f8b34b80c41]
#20  /usr/lib/libpython3.9.so.1.0(PyEval_EvalCode+0x23) [0x7f8b34c37ae3]
#21  /usr/lib/libpython3.9.so.1.0(+0x1ed9f4) [0x7f8b34c479f4]
#22  /usr/lib/libpython3.9.so.1.0(+0x1e96cb) [0x7f8b34c436cb]
#23  /usr/lib/libpython3.9.so.1.0(PyRun_StringFlags+0xa0) [0x7f8b34c3c330]
#24  0x7f8b34f48cfc in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /usr/lib/freecad/lib/libFreeCADBase.so+0x6c
#25  0x7f8b35b23656 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x96
#26  0x7f8b35b237e6 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /usr/lib/freecad/lib/libFreeCADGui.so+0xe6
#27  0x7f8b35b23915 in Gui::Command::updateActive() from /usr/lib/freecad/lib/libFreeCADGui.so+0x45
#28  0x7f89d902e583 in SketcherGui::ViewProviderSketch::unsetEdit(int) from /usr/lib/freecad/lib/SketcherGui.so+0x1f3
#29  0x7f8b35e5d773 in Gui::ViewProvider::finishEditing() from /usr/lib/freecad/lib/libFreeCADGui.so+0x13
#30  0x7f8b35aa781d in Gui::Document::_resetEdit() from /usr/lib/freecad/lib/libFreeCADGui.so+0x9d
#31  0x7f8b35a39dda in Gui::Application::setEditDocument(Gui::Document*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x3a
#32  0x7f8b35ad2522 in Gui::DocumentPy::resetEdit(_object*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x32
#33  0x7f8b35ad2559 in Gui::DocumentPy::staticCallback_resetEdit(_object*, _object*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x29
#34  /usr/lib/libpython3.9.so.1.0(+0x148f08) [0x7f8b34ba2f08]
#35  /usr/lib/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x2e3) [0x7f8b34b8b333]
#36  /usr/lib/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x52a8) [0x7f8b34b87218]
#37  /usr/lib/libpython3.9.so.1.0(+0x126fd9) [0x7f8b34b80fd9]
#38  /usr/lib/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x51) [0x7f8b34b80c41]
#39  /usr/lib/libpython3.9.so.1.0(PyEval_EvalCode+0x23) [0x7f8b34c37ae3]
#40  /usr/lib/libpython3.9.so.1.0(+0x1ed9f4) [0x7f8b34c479f4]
#41  /usr/lib/libpython3.9.so.1.0(+0x1e96cb) [0x7f8b34c436cb]
#42  /usr/lib/libpython3.9.so.1.0(PyRun_StringFlags+0xa0) [0x7f8b34c3c330]
#43  0x7f8b34f48cfc in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /usr/lib/freecad/lib/libFreeCADBase.so+0x6c
#44  0x7f8b35b23656 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x96
#45  0x7f8b35b237e6 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /usr/lib/freecad/lib/libFreeCADGui.so+0xe6
#46  0x7f89d905f529 in SketcherGui::TaskDlgEditSketch::reject() from /usr/lib/freecad/lib/SketcherGui.so+0x159
#47  0x7f8b35dd5979 in Gui::TaskView::TaskView::reject() from /usr/lib/freecad/lib/libFreeCADGui.so+0x69
#48  /usr/lib/libQt5Core.so.5(+0x2f07a0) [0x7f8b33a5f7a0]
#49  /usr/lib/libQt5Widgets.so.5(+0x2ff761) [0x7f8b346a4761]
#50  /usr/lib/libQt5Core.so.5(+0x2f07a0) [0x7f8b33a5f7a0]
#51  0x7f8b345f74e3 in QAbstractButton::clicked(bool) from /usr/lib/libQt5Widgets.so.5+0x43
#52  /usr/lib/libQt5Widgets.so.5(+0x25276c) [0x7f8b345f776c]
#53  /usr/lib/libQt5Widgets.so.5(+0x254374) [0x7f8b345f9374]
#54  0x7f8b345f9595 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /usr/lib/libQt5Widgets.so.5+0xf5
#55  0x7f8b345430be in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x20e
#56  0x7f8b344ffd62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x82
#57  0x7f8b34507ac9 in QApplication::notify(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0xaa9
#58  0x7f8b35af2ab9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#59  0x7f8b33a283ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x13a
#60  0x7f8b3450657b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /usr/lib/libQt5Widgets.so.5+0x1bb
#61  /usr/lib/libQt5Widgets.so.5(+0x1b7a84) [0x7f8b3455ca84]
#62  /usr/lib/libQt5Widgets.so.5(+0x1badb5) [0x7f8b3455fdb5]
#63  0x7f8b344ffd62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x82
#64  0x7f8b35af2ab9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#65  0x7f8b33a283ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x13a
#66  0x7f8b33e031f0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /usr/lib/libQt5Gui.so.5+0x6b0
#67  0x7f8b33dd87d5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xb5
#68  /usr/lib/libQt5XcbQpa.so.5(+0x62fcc) [0x7f8b2df7ffcc]
#69  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x26c) [0x7f8b317a44dc]
#70  /usr/lib/libglib-2.0.so.0(+0xa8749) [0x7f8b317f8749]
#71  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f8b317a1bc1]
#72  0x7f8b33a80fe6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x66
#73  0x7f8b33a26d2c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x12c
#74  0x7f8b33a2f294 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x94
#75  0x7f8b35a4482e in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0x1b9e
#76  freecad(+0x4858) [0x560a8a909858]
#77  /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7f8b33399b25]
#78  freecad(+0x4b8e) [0x560a8a909b8e]

# Steps to reproduce

Open at the attached file
Edit Sketch001
Change the 3mm dimension to 5mm 
Exit out of editing the sketch

# FreeCAD Info

```
OS: Arch Linux (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git)
Build type: Release
Branch: makepkg
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.9.6
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)
```

# Other bug information

* **Priority:** normal
* **Severity:** crash
* **Category:** Bug
* **Updated:** 12/13/2021

# Discussion from Mantis ticket

### Comment by electro707 2021-10-08 04:42
Note: This is also an issue in the most recent git version:
OS: Arch Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25997 (Git)
Build type: Release
Branch: master
Hash: 77b198048a63f1e9ca15eef64c8042d599a14cf3
Python version: 3.9.7
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

---

### Comment by openBrain 2021-10-13 14:14
electro707 : could you please open a new thread in our forum ([per our reporting guidelines](https://forum.freecadweb.org/viewtopic.php?f=3&t=5236)) and add link here ? Thx

---

### Comment by electro707 2021-10-16 04:54
Created, as [https://forum.freecadweb.org/viewtopic.php?f=3&t=62912](https://forum.freecadweb.org/viewtopic.php?f=3&t=62912)

---

### Comment by electro707 2021-10-22 03:09
Issue is closed due to issue [#992](https://tracker.freecadweb.org/view.php?id=922) as mentioned in the forum thread.

---

### Comment by wmayer 2021-12-12 15:38
It crashes with OCC 7.3 and I get the same stack trace. However, it's an OCC bug and when using the latest version 7.6 it doesn't crash any more but only creates an invalid shape.

**Comment by adrianinsaval** [comment]
according to discussion this can be closed, I did not retest
