### ISSUE TITLE
Pocket using SubShapeBinder does not occur on orthogonal axis.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6273]
Issue imported from https://tracker.freecad.org/view.php?id=4767

* **Reporter:** BruceL
* **Date submitted:** 10/17/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

[Forum Post](https://forum.freecadweb.org/viewtopic.php?f=3&t=62913)

When making pockets with sub-shapebinders, FreeCAD insists on pocketing along the z-axis.

# Steps to reproduce

1. Open the attached SM-PLB03A case file: [SM-PLB03A case.zip](https://github.com/FreeCAD/FreeCAD/files/8805578/SM-PLB03A.case.zip)  
2. make "SLIDE_IN" the active body
3. select the "vent_binder" subshapebinder in "SLIDE_IN"
4. pocket the "vent_binder"
5. observe that the pocket appears to be along the z axis as it appears in the section below the "vent binder" instead of along the y axis where I would expect it.
6. note that the "thread_holes_2" pocket, which is also based on a subshapebinder from "MAIN_CASE" works fine (but it's along the z-axis)

# FreeCAD Info

```
OS: Debian GNU/Linux bookworm/sid (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.20.25997 (Git) AppImage
Build type: Release
Branch: master
Hash: 77b198048a63f1e9ca15eef64c8042d599a14cf3
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/Canada (en_CA)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 10/17/2021

**Comment by luzpaz** [comment]
Bumped [forum thread](https://forum.freecadweb.org/viewtopic.php?p=598799#p598799)

**Comment by adrianinsaval** [comment]
pocketing the mentioned subshapebinder works without problems now, issue can be closed
[code]
OS: Linux 5.18.1-arch1-1 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28994 (Git)
Build type: None
Branch: master
Hash: 37e93f421cb8d30455ce9ce8c778d40db4f9f55c
Python 3.10.4, Qt 5.15.4, Coin 4.0.1, OCC 7.5.3
Locale: English/United Kingdom (en_GB)
[/code]
also confirmed by someone else in the forum
