### ISSUE TITLE
Changing TC with same tool number but different spindle speed doesn't produce correct gcode

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6275]
Issue imported from https://tracker.freecad.org/view.php?id=4769

* **Reporter:** @sliptonic
* **Date submitted:** 10/18/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

The user may desire to run the same tool at different feeds and speeds within a job.  This is achieved by creating two tool controllers and using the same tool number for both.  During post processing, the tool number of the new tool is compared to the old one and if they are the same, the tool change code is suppressed.  This is correct behavior.  However, if the spindle speed changes, an M3 (or M4) with the new spindle speed should be emitted and it is not.

# Additional information

https://forum.freecadweb.org/viewtopic.php?f=15&t=62762&start=10

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 10/18/2021

**Comment by Russ4262** [comment]
0.20 pre-release analysis with Revision 28638:
 
This is a candidate in my opinion for correction in 0.20.  I can believe the re-use of a tool controller with different speeds occurring with some frequency in production lines.

**Comment by J-Dunn** [comment]
Nice. This may also relate to LASER cutters / pyrography where spindle "speed" is used as the LASER power setting. Changing power setting from one op to another would seem a likely requirement.
