### ISSUE TITLE
No ficheiro de trabalho que acaba de abrir a funcionalidade é bastante reduzida!

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6287]
Issue imported from https://tracker.freecad.org/view.php?id=4792

* **Reporter:** Carlos Machado
* **Date submitted:** 11/24/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

Boa tarde!

Ao trabalhar neste ficheiro deparei-me com um arrasto na execução de qualquer comando a executar.
Ao abrir dá-me esta mensagem: "12:25:23  3.1e-08 <App> Document.cpp(3172): The graph must be a DAG.". 
Estará relacionado?
Tem resolução? Qual?
Não esquecer que eu não entendo nada de programação!

OS: macOS 10.16
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git)
Build type: Release
Branch: (HEAD detached at 0.19.2)
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: C/Default (C)

3,4 GHz Intel Core i5 de núcleo quádruplo
40 GB 2400 MHz DDR4
Radeon Pro 570 4 GB

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Bug
* **OS: macOS OS: macOS 10.16**
* **Platform:** Mac (Retina 5K, 27-inch, 2017)
* **Updated:** 11/24/2021

# Discussion from Mantis ticket

### Comment by Carlos Machado 2021-11-24 13:29
Será que a reprodução seguinte ajuda?

12:25:23  3.1e-08 <App> Document.cpp(3172): The graph must be a DAG.
13:19:28  3224.01 <App> Document.cpp(3172): The graph must be a DAG.
13:19:28  3245.17 <App> Document.cpp(3527): Altera____o#Extrude007 still touched after recompute
13:19:28  3245.17 <App> Document.cpp(3527): Altera____o#Sketch027 still touched after recompute
13:19:28  3245.17 <App> Document.cpp(3527): Altera____o#Extrude006 still touched after recompute
13:19:28  3245.17 <App> Document.cpp(3527): Altera____o#Sketch019 still touched after recompute
13:19:28  3245.17 <App> Document.cpp(3527): Altera____o#Extrude005 still touched after recompute
13:19:28  3245.17 <App> Document.cpp(3527): Altera____o#Sketch018 still touched after recompute
13:20:05  ----------------
13:20:05  GuiCommand: Move
13:20:05  Pick start point
13:20:10  Pick end point
13:20:51  3306.97 <App> Document.cpp(3172): The graph must be a DAG.
13:20:51  3328.03 <App> Document.cpp(3527): Altera____o#Extrude007 still touched after recompute
13:20:51  3328.03 <App> Document.cpp(3527): Altera____o#Sketch027 still touched after recompute
13:20:51  3328.03 <App> Document.cpp(3527): Altera____o#Extrude006 still touched after recompute
13:20:51  3328.03 <App> Document.cpp(3527): Altera____o#Sketch019 still touched after recompute
13:20:51  3328.03 <App> Document.cpp(3527): Altera____o#Extrude005 still touched after recompute
13:20:51  3328.03 <App> Document.cpp(3527): Altera____o#Sketch018 still touched after recompute
13:21:58  3374.25 <App> Document.cpp(3172): The graph must be a DAG.
13:21:58  3395.37 <App> Document.cpp(3527): Altera____o#Extrude007 still touched after recompute
13:21:58  3395.37 <App> Document.cpp(3527): Altera____o#Sketch027 still touched after recompute
13:21:58  3395.37 <App> Document.cpp(3527): Altera____o#Extrude006 still touched after recompute
13:21:58  3395.37 <App> Document.cpp(3527): Altera____o#Sketch019 still touched after recompute
13:21:58  3395.37 <App> Document.cpp(3527): Altera____o#Extrude005 still touched after recompute
13:21:58  3395.37 <App> Document.cpp(3527): Altera____o#Sketch018 still touched after recompute
13:24:09  3504.58 <App> Document.cpp(3172): The graph must be a DAG.
13:24:09  3526.19 <App> Document.cpp(3527): Altera____o#Extrude007 still touched after recompute
13:24:09  3526.19 <App> Document.cpp(3527): Altera____o#Sketch027 still touched after recompute
13:24:09  3526.19 <App> Document.cpp(3527): Altera____o#Extrude006 still touched after recompute
13:24:09  3526.19 <App> Document.cpp(3527): Altera____o#Sketch019 still touched after recompute
13:24:09  3526.19 <App> Document.cpp(3527): Altera____o#Extrude005 still touched after recompute
13:24:09  3526.19 <App> Document.cpp(3527): Altera____o#Sketch018 still touched after recompute
13:25:23  3556.75 <App> Document.cpp(3172): The graph must be a DAG.
13:25:23  3578.41 <App> Document.cpp(3527): Altera____o#Extrude007 still touched after recompute
13:25:23  3578.41 <App> Document.cpp(3527): Altera____o#Sketch027 still touched after recompute
13:25:23  3578.41 <App> Document.cpp(3527): Altera____o#Extrude006 still touched after recompute
13:25:23  3578.41 <App> Document.cpp(3527): Altera____o#Sketch019 still touched after recompute
13:25:23  3578.41 <App> Document.cpp(3527): Altera____o#Extrude005 still touched after recompute
13:25:23  3578.41 <App> Document.cpp(3527): Altera____o#Sketch018 still touched after recompute
13:25:23  3578.85 <App> Document.cpp(3172): The graph must be a DAG.
13:25:23  3600.13 <App> Document.cpp(3527): Altera____o#Extrude007 still touched after recompute
13:25:23  3600.13 <App> Document.cpp(3527): Altera____o#Sketch027 still touched after recompute
13:25:23  3600.13 <App> Document.cpp(3527): Altera____o#Extrude006 still touched after recompute
13:25:23  3600.13 <App> Document.cpp(3527): Altera____o#Sketch019 still touched after recompute
13:25:23  3600.13 <App> Document.cpp(3527): Altera____o#Extrude005 still touched after recompute
13:25:23  3600.13 <App> Document.cpp(3527): Altera____o#Sketch018 still touched after recompute

**Comment by adrianinsaval** [comment]
probably just a broken filedue to incorrect ussage, file was not provided it seems, plus incorrect language for an international project... should be closed IMO
