### ISSUE TITLE
spreadsheet: the alias content is not visible (black on black)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6294]
Issue imported from https://tracker.freecad.org/view.php?id=4803

* **Reporter:** roipoussiere
* **Date submitted:** 12/11/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** resolved
* **Tags:** 

# Original report text

The "content" textbox content is displayed with white color, but the "alias" textbox content is displayed with black color, so it's not really visible. See image attached.

I use a dark theme on my system btw.

# Additional information

OS: Ubuntu 20.04.3 LTS (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.19.2)
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: French/France (fr_FR)

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Kubuntu 20.04**
* **Platform:** Linux
* **Updated:** 12/30/2021
* **Fixed in version:** 0.2

# Discussion from Mantis ticket

### Comment by chennes 2021-12-29 03:12
This is happening because a QPalette is being used to set the text color to either "red" in the case of an error, or "black" in the case of no error. Obviously "black" should be replaced by "the original color".

---

### Comment by chennes 2021-12-30 03:55
This is fixed by [commit 4098c8817](https://github.com/FreeCAD/FreeCAD/commit/4098c8817106bb298dcf7458f4c150ff4f106075).

**Comment by adrianinsaval** [comment]
per your comment it should be closed @chennes
