### ISSUE TITLE
"Part Design" > "Hole" > "Model Thread" > "Thread Depth" > "Dimension"

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6297]
Issue imported from https://tracker.freecad.org/view.php?id=4808

* **Reporter:** lual
* **Date submitted:** 12/20/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** resolved
* **Tags:** 

# Original report text

"Part Design" >
"Hole" >
"Model Thread" >
"Thread Depth" >
"Dimension" >
pressing "OK" resets the given value to the value for the for hole-depth!

# Additional information

Discussion in Forum
https://forum.freecadweb.org/viewtopic.php?f=3&t=64682

This Pull Request from Github may helps to find the code...
https://github.com/FreeCAD/FreeCAD/pull/4274

# Steps to reproduce

1. Open the Attached File
2. doubleclick on "Hole"
3. Click "OK"
4. Thread Depth is changed unexpected!

# FreeCAD Info

```
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26683 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0388fbc)
Hash: 0388fbc98d49d874fb341b9037a743bc691d501f
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: German/Germany (de_DE)
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Linux Manjaro stable**
* **Platform:** PC
* **Updated:** 12/22/2021
* **Fixed in version:** 0.2

# Discussion from Mantis ticket

### Comment by uwestoehr 2021-12-21 01:55
proposed fix: https://github.com/FreeCAD/FreeCAD/pull/5272

---

### Comment by uwestoehr 2021-12-22 00:41
fix merged

**Comment by donovaly** [comment]
Bug was not in FC 0.19 and had been fixed in master -> closing
