### ISSUE TITLE
Zoom tree with mouse

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6303]
Issue imported from https://tracker.freecad.org/view.php?id=4819

* **Reporter:** Pauvres_honteux
* **Date submitted:** 1/5/2022
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** tree view

# Original report text

See forum [Zoom tree with mouse](https://forum.freecadweb.org/viewtopic.php?p=525830#p525830)

# Additional information

N/A

# Steps to reproduce

N/A

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 1/5/2022

**Comment by yorikvanhavre** [comment]
Fixed by #6333
