### ISSUE TITLE
TechDraw: Built-in symbols (such as diameter, angle and geometric tolerances) accessible when creating a dimension or annotation

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6312]
Issue imported from https://tracker.freecad.org/view.php?id=4837

* **Reporter:** @FEA-eng
* **Date submitted:** 1/27/2022
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

It would be great to have a list of built-in symbols (standards, such as diameter, angle and geometric tolerances) accessible when creating a dimension or annotation.

[Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=35&t=65706)

# FreeCAD Info

```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Polish/Poland (pl_PL)
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 1/27/2022

**Comment by FEA-eng** [comment]
This issue can be closed since #6382 resolved it. @luzpaz Can you close it?
