### ISSUE TITLE
Topological naming interface

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6316]
Issue imported from https://tracker.freecad.org/view.php?id=876

* **Reporter:** wmayer
* **Date submitted:** 11/14/2012
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

http://forum.freecadweb.org/viewtopic.php?f=10&t=2980

# Additional information

Downgraded and assigned to jnxd 

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/20/2021

# Discussion from Mantis ticket

### Comment by wmayer 2012-11-21 09:47
Some more information from pythonocc:
http://www.pythonocc.org/resources/meshing/pythonocc-and-smesh/

---

### Comment by jrheinlaender 2012-12-21 09:32
Just a reminder that I submitted a draft implementation for a topological naming interface on github jrheinlaender/TNaming

https://github.com/jrheinlaender/FreeCAD/tree/jrheinlaender/TNaming

---

### Comment by normandc 2014-08-17 20:02
I don't know who can edit the bug description but since then the forum was migrated out of SF. So the updated link to the forum topic should be http://forum.freecadweb.org/viewtopic.php?f=10&t=2980

---

### Comment by Kunda1 2021-02-20 13:55
realthunder is this a dupe of #922 ?

**Comment by yorikvanhavre** [comment]
Handled by #4752
