### ISSUE TITLE
[Path] Cmake using the `-G Xcode` generator results in error

### ISSUE THREAD

**Issue by dirkolbrich** [FreeCAD/FreeCAD#6328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

-

### Version

0.20 (Development)

### Full version info

```shell
latest master branch
```

### Issue description

When trying to setup a CMake build configuration using the cmake `-G Xcode` option, which generates a .xcodeproj file for use with the Mac Xcode IDE, the setup process fails with the following message:

```
CMake Error in src/Mod/Path/CMakeLists.txt:
  The custom command generating

    /Users/username/FreeCAD/freecad-build-xcode/Mod/Path/PathCommands.py

  is attached to multiple targets:

    PathScripts
    PathTests

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".
```

This prevents the generation of the .xcodeproj and leads to an abort of the cmake process.

The error is most likely due to a duplicated linking of `PathCommands.py` file within `[src/Mod/Path/CMakeLists.txt]`:
here
https://github.com/FreeCAD/FreeCAD/blob/83cc413e1885ebb8097b9038fbe4f2ce58a94e61/src/Mod/Path/CMakeLists.txt#L9-L15
and here
https://github.com/FreeCAD/FreeCAD/blob/83cc413e1885ebb8097b9038fbe4f2ce58a94e61/src/Mod/Path/CMakeLists.txt#L28-L30

### Anything else?

see PR #5488 [Path] remove duplicate link of PathCommands.py

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
Please first open a forum thread (you can always use the general Help forum).

When people there agree there is a bug, the issue can be reopened.
Issues without prior forum discussion won't be accepted since otherwise our issue tracker would quickly overflow and unusable.
