### ISSUE TITLE
[Bug] FreeCAD crashes when making a fillet on an edge, face or body in Part Design mode

### ISSUE THREAD

**Issue by mattislechner** [FreeCAD/FreeCAD#6350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

n.a.

### Version

0.19 (Release)

### Full version info

```shell
OS: Ubuntu 20.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24366 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0f9259c)
Hash: 0f9259cda103ae1824ac16c68ac9b4a0d54b05fc
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

PartDesign

### Issue description

FreeCAD crashes when making a fillet on some edges in Part Design mode.
See attached log for more information.

[FreeCAD_GITHub.log](https://github.com/FreeCAD/FreeCAD/files/8053277/FreeCAD_GITHub.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Thanks for the report -- this was probably fixed upstream in OCCT 7.6 by https://git.dev.opencascade.org/gitweb/?p=occt.git;a=commit;h=329e5df986519164083d78b28ae62d1a3b10fa6a

Please post an example file to the FreeCAD Forum so that we can make sure that's the case.

**Comment by luzpaz** [comment]
@chennes we should have a label for these types of tickets. On mantis we had a `post-to-forum` tag

**Comment by chennes** [comment]
If you'd like to create that label I don't object, but I never used that label for anything in Mantis, it doesn't really add any information for me as a developer. If you have use for it during triage, go for it.

**Comment by donovaly** [comment]
I think we should use a strict bug policy: issues without prior forum discussions will be closed. When there is a forum discussion and we can reopen the bug.
@mattislechner please start a forum thread and attach there your file and a step by step description how you got the crash. We can reopen this issue then if necessary.
