### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by RayAtGit** [FreeCAD/FreeCAD#6386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

Excel import crashes and some part is imported

### Version

0.19 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)
```

### Issue description

After creatinga new project and saving it as an emtpy project and creating a new file test.xlsx with some data and formulas, with MS-Excel 2010 the error as enclosed in the attachment is produced. Column B has some simple formulas. Taking out the formulas and replace them by the values it works fine. (This is an error demo XLS file, replacing the formulas with values is no option in the actual project).

[test.xlsx](https://github.com/FreeCAD/FreeCAD/files/8083425/test.xlsx)

![image](https://user-images.githubusercontent.com/34373427/154353292-7fa0fde8-0171-444a-9e1f-7833c04d4f61.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Please open a forum discussion beforehand per our guidelines. Closing ticket. You can re-open it pending the outcome of the forum discussion
