### ISSUE TITLE
missing 2d fillet python bindings

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD#6407]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=22&t=49562&p=425165&hilit=ChFi2d#p425165

### Version

0.20 (Development)

### Full version info

```shell
0.20.latest (not at han right now), why is this imortant for feature requests?
```

### Idea description

It would be nice to have python bindings for the occ 2d fillet method `ChFi2d`.

### Anything else?

https://forum.freecadweb.org/viewtopic.php?f=22&t=49562&p=425165&hilit=ChFi2d#p425165

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by looooo** [comment]
@donovaly @wwmayer This feature is needed in the gear-wb (development version). Currently python-occ is used for this task, but it would be nice if FreeCAD offers a python command to do 2d fillets.

**Comment by wwmayer** [comment]
bd853e5ef292a9b0c0f and b07be8767722b4128ea38

**Comment by looooo** [comment]
wow, this was fast, thanks.

**Comment by luzpaz** [comment]
Thank you wmayer!

**Comment by donovaly** [comment]
Many thanks!
