### ISSUE TITLE
[Task] Remove remaining Python2 code

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6413]
### Issue description

There is still remaining Python2 related code in the FreeCAD source code. Once a new development version is cut, the task to remove said py2 code should occur very early in the development cycle so any bugs/regressions can be caught and fixed.  

### Anything else?

https://github.com/FreeCAD/FreeCAD/search?q=sys.version_info+%3C+3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sz47** [comment]
Hello, Ive made a commit on my fork after removing all sys.version_info from the python code. Its in [this](https://github.com/sz47/FreeCAD/commit/dd82d5905b7b93f8558ee22de9daf635181b9a7b) commit. 

If I'm missing something please pardon me, I'd really like to do more. Should I open pull request?

**Comment by luzpaz** [comment]
@chennes can we close this ?

**Comment by chennes** [comment]
I can easily clean up the last couple of `sys.version_info` checks, but there are still quite a few "py2" search results in the codebase.
