### ISSUE TITLE
[Task] search and replace URLs to freecad.org

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6415]
### Issue description

Once v0.21dev is cut, migrate all freecad URLs to use the freecad.org domain name.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Let's postpone till toponaming is merged so there are less cosmetic changes and therefore ess of a merge headache for the topinaming devs?

**Comment by luzpaz** [comment]
@chennes postpone till after v0.21 release ?

**Comment by chennes** [comment]
Not really any reason to delay, is there?

**Comment by luzpaz** [comment]
Since toponaming approach has changed, I actually don't see what the delay would be.

**Comment by luzpaz** [comment]
I suggest in order to limit rebasing for pending PRs and other efforts that will happen prior to release, that this PR be delayed till right before release. Thoughts?

**Comment by chennes** [comment]
We can easily do all SVGs in one go without risking any merge conflicts. For actual code it should probably go the same was as the pre-commit formatting, letting each WB's lead Maintainer coordinate when it happens.

**Comment by luzpaz** [comment]
I like using the regex function in the vscode, it shows all the search and replace results.

**Comment by yorikvanhavre** [comment]
Ok testing further, changing eveerything at once with `find . -type f | xargs sed -i 's/freecadweb/freecad/g'` does not work here because some file paths include freecadweb, like `src/XDGData/org.freecadweb.FreeCAD.appdata.xml.in` so FreeCAD fails to build. I always said that was a bad idea to have a domain name in paths... :sweat:

**Comment by luzpaz** [comment]
@yorikvanhavre i'm happy to tackle this and free you up for other tasks

**Comment by luzpaz** [comment]
PR submitted

**Comment by luzpaz** [comment]
Rebased and added recently merged TD templates that made it into master peri-PR (during the PR process)
