### ISSUE TITLE
[Bug] C++ DXF importer: Wrong scale factor for inches

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#6461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=66646

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 8.1 (6.3)
Word size of FreeCAD: 64-bit
Version: 0.20.27518 (Git)
Build type: Release
Python version: 3.8.12
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Dutch/Netherlands (nl_NL)
```

### Issue description

The C++ DXF importer wrongly applies a 25.4 scale factor twice when importing a DXF with the following settings:

MEASUREMENT=0
INSUNITS=1

These settings are correct for a DXF where drawing units are inches.

In the attached ZIP the DXF file from the forum topic.

The DXF is for an N Scale (1/160) model part. It has a width of 0.226 inches.
When imported this should result in 0.226\*25.4 = 5.74mm.
But the actual result is 0.226\*25.4\*25.4 = 145.8mm

Related PR:
https://github.com/FreeCAD/FreeCAD/pull/3992

Side note: there are 3 dxf.cpp files. That can't be a good idea...
src\Mod\Path\libarea\dxf.cpp
src\Mod\Import\App\dxf.cpp
src\Mod\Draft\App\dxf.cpp

[New POLY pt226 wide.zip](https://github.com/FreeCAD/FreeCAD/files/8147611/New.POLY.pt226.wide.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
I believe Import/App/dxf.cpp is the successor to Draft/App/dxf.cpp.
