### ISSUE TITLE
[Feature Request] TechDraw: Move `TransparentFace` setting to Page/View level

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FreeCAD#6527]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://www.forum.freecadweb.org/viewtopic.php?p=577504#p577504

### Subproject(s) affected?

Techdraw

### Idea description

Transparent Faces settings is current global scope.  It would be convenient to be able to specify this at the Page or View level.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Closing as solved by @pavltom  
@yorikvanhavre do you mind adding @pavltom to FreeCAD assigneess so we can assign this ticket to them ?
