### ISSUE TITLE
[Bug] gmsh with VTK9.x does not work

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#6553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=18&t=66948

### Version

0.20 (Development)

### Full version info

```shell
OS: Debian GNU/Linux 11 (bullseye) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.20.27972 (Git)
Build type: Release
Branch: master
Hash: 068f02c4b786bc425b44b7f8eec77ea6beab7f61
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, OCC 7.6.1
Locale: English/United States (en_US)
```

### Subproject(s) affected?

FEM

### Issue description

gmsh fails to generate a mesh in the case of many distributions (mainly Linux) using VTK9.x
There are several forum threads regarding this issue, links to them can be found in the thread assigned to this report.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akrpic77** [comment]
problem seems to be in compactMesh function https://github.com/FreeCAD/FreeCAD/blob/5d49bf78de785a536f941f1a6d06d432582a95d3/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Mesh.cpp#L2153

bypassing this function (placing `return` as first statement in this function) successfully creates the mesh.
