### ISSUE TITLE
[Bug] FreeCAD 0.20 crashes when attempting to change template in TechDraw.

### ISSUE THREAD

**Issue by mfraser** [FreeCAD/FreeCAD#6583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=67083

### Version

0.20 (Development)

### Full version info

```shell
OS: Ubuntu 21.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.
Build type: Release
Branch: unknown
Hash: c5a0db5e4736a6cd43d239e15d5e0daf7006a642
Python 3.9.7, Qt 5.15.2, Coin 4.0.0, OCC 7.5.2
Locale: English/United Kingdom (en_GB)
Installed mods:
* sheetmetal 0.2.49
* lattice2
* fcgear 1.0.0
* Curves 0.3.0
* Assembly4 0.11.8
* fasteners
* A2plus 0.4.54b
* VendorParts
```

### Subproject(s) affected?

Techdraw

### Issue description

Insert page using template, pick any template.
Select the template in the combo view and then click on the 3 dots icon next to Template in Data, a window appears to select a new template and then FreeCAD crashes.

### Anything else?

Launching FreeCAD from the terminal:
connect failed: No such file or directory
Qt: Session management error: networkIdsList argument is NULL
free(): invalid pointer
Aborted (core dumped)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Can't reproduce on 
```
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28060 (Git)
Build type: Release
Branch: master
Hash: a10fd46b09ba01bd2e0dc922a2d796cfc3911485
Python 3.8.10, Qt 5.15.3, Coin 4.0.0, OCC 7.6.1
Locale: English/United States (en_US)
Installed mods: 
  * ToolbarStyle
  * stickframe
  * sheetmetal 0.2.49
  * Behave-Dark-Colors 0.0.1
  * Curves 0.3.0
  * Ship
  * BIM 2021.12.0
```
