### ISSUE TITLE
[Bug] [Regression] Pocket becomes a pad when next object ofter a polar pattern

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#6584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=579381#p579381

### Version

0.19 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24267 +148 (Git)
Build type: Release
Branch: Branch_0.19.4
Hash: 476ecf091941bead59b14e44afa6064d5a66afa3
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

PartDesign

### Issue description

See https://forum.freecadweb.org/viewtopic.php?p=579381#p579381 for a description and example file.

We found out that the issue occurred with https://github.com/FreeCAD/FreeCAD/commit/aa19f8b05fbbd2f40f075fcad0e6d22b3dc2bff0 but this commit is not directly to blame.

However, a mustfix for 0.20 since padding is an essential feature for 3D of course ;-)

**Comment by donovaly** [comment]
@realthunder , since you did much to PD in your branch, maybe you have an idea what is causing this nasty issue?

**Comment by 0penBrain** [comment]
I had a quick look but can't find anything obvious in the code that would create this. I'm balanced between a FC bug and an OCC one...

**Comment by donovaly** [comment]
> Caused by [aa19f8b](https://github.com/FreeCAD/FreeCAD/commit/aa19f8b05fbbd2f40f075fcad0e6d22b3dc2bff0)

Since this commit does not seem the be the origin, just a symptom, could it be that this commit causes this bug?: https://github.com/FreeCAD/FreeCAD/commit/03da9d3501

**Comment by donovaly** [comment]
> could it be that this commit causes this bug?: https://github.com/FreeCAD/FreeCAD/commit/03da9d3501

No, reverting this commit does not fix the issue.

**Comment by donovaly** [comment]
Also reverting https://github.com/FreeCAD/FreeCAD/commit/aa19f8b05fbbd2f40f075fcad0e6d22b3dc2bff0 does not fix the issue.

**Comment by 0penBrain** [comment]
@AjinkyaDahale Could you clarify about difference between 6665 and 6671 ? What are pros & cons of each ? Is one covering more cases ?

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale Could you clarify about difference between 6665 and 6671 ?

Just where the inversion check happens. A user there did some benchmarks and found a significant speed difference in #6665. HOWEVER, they have since found an error in that test so now it looks quite better.

> What are pros & cons of each ?

I guess #6671 does the check at the very end, so it happens even if refine is set to false. #6665 on the other hand will also correct the loose solids if that is wanted.
