### ISSUE TITLE
[Bug] [Mesh] read unitialized variables

### ISSUE THREAD

**Issue by mosfet80** [FreeCAD/FreeCAD#6598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewforum.php?f=4&sid=db4c985f788f36bb46319af246d1b461

### Version

0.20 (Development)

### Full version info

```shell
SbBool SoSFMeshFacetArray::read1Value(SoInput * in, unsigned long idx)
{
  assert(idx < value->size());
  MeshCore::MeshFacet& v = (*value)[idx];
  int32_t p0, p1, p2;
  SbBool ret = (in->read(p0) && in->read(p1) && in->read(p2));
  if ( ret ) {
    v._aulPoints[0] = p0;
    v._aulPoints[1] = p1;
    v._aulPoints[2] = p2;
  }

  return ret;
}
```

### Subproject(s) affected?

Mesh

### Issue description

`src/Mod/Mesh/Gui/SoFCMeshFaceSet.cpp` on line 197 
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Mesh/Gui/SoFCMeshFaceSet.cpp#L197-L206

the variables `p0`, `p1` and `p2` are used in `in->read()` without initializing them

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@mosfet80 FYI, the `<title>` in the bug description should be written over. 
Here's a tip how to open a ticket regarding source code issues:
1. Open https://github.com/FreeCAD/FreeCAD
2. Press the `t` key
3. Github fuzzy search dialog will open. Type the file name you're looking for.
4. Once on the correct page, locate the code block in question and press on the line number (hold down `ctrl` key and scroll down or up to highlight the code block you're targeting and click the mouse again.
5. An ellipsis `...` will show up in the sidebar, click it and it will open a context menu.
6. Choose the 'Reference in new issue' option 
![image](https://user-images.githubusercontent.com/4140247/158848159-1646e270-a5c2-4966-aec9-8046ec33b58b.png)
