### ISSUE TITLE
[Bug] Draft Snap Near is inaccurate when snapping to curves

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#6613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=23&t=67289

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.27809 (Git)
Build type: Release
Python 3.8.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Draft

### Issue description

The Draft Snap Near tool is inaccurate for curves - apparently, it snaps to their polygonal representations. The issue can be easily seen when snapping a line starting from the center of a circle and ending on its perimeter. Dimensioning such a line results in a value differing from the circle radius.

![image](https://user-images.githubusercontent.com/4140247/171654580-c692ca8d-87bf-42f4-a183-2ad6dea27c09.png)

![image](https://user-images.githubusercontent.com/4140247/171654649-abd6f3f5-30e5-47bf-b809-c1057dbff6d1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Fixed with #7132
