### ISSUE TITLE
[Bug] [Draft] SVG import does not work with plain SVG

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#6653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=67413

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.28343 (Git)
Build type: Release
Branch: master
Hash: b0b243bee79cd5924210e2c8241cde2d30b51ab1
Python 3.8.6+, Qt 5.15.2, Coin 4.0.1, OCC 7.5.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Draft

### Issue description

- take this plain SVG of a box (created using Inkscape 1.1 and then saved as "Plain SVG"):
![Box-plain-SVG](https://user-images.githubusercontent.com/1828501/159828603-eef38b7b-4344-42fd-b7a8-a74c394bb6b2.svg)

and import it as SVG

result:
- you get an "error" about a missing DPI setting. However the settings are the SVG (as in the SVG specs it contains the mm settings).

The issue is in Draft/importSVG.py.

**Comment by WandererFan** [comment]
Why is this tagged for TechDraw?  "Insert Svg Symbol" imports the file without complaints.  

The error messages only appear on import as geometry or import to Drawing wb.

**Comment by donovaly** [comment]
Thanks, I was not aware this is a Drawing WB issue.

**Comment by yorikvanhavre** [comment]
Will look at it again
