### ISSUE TITLE
[Bug] [regression] recomputing DataAtPoint leads to error console message

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#6674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=583676#p583676

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.28467 (Git)
Build type: Release
Branch: master
Hash: 5f5afd4b65f59ac1b06edc637033fc6686ac3eb6
Python 3.8.6+, Qt 5.15.2, Coin 4.0.1, OCC 7.5.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

FEM, but the cause is probably somewhere else

### Issue description

see https://forum.freecadweb.org/viewtopic.php?p=583676#p583676

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
Fixed with 5974abe351
