### ISSUE TITLE
[Bug] Flipping rectangles in"fully constrainted"parametric sketch

### ISSUE THREAD

**Issue by CharlemagneLasse** [FreeCAD/FreeCAD#6709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=67720

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28567 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Sketcher

### Issue description

[This is an extremely simplified reproducer - I know how to work around this by constraining it differently but it is simple enough to show the bug]

This should show that the same, fully contrained sketch results in different results with exactly the same parameters and the same software version. Our parameter here is called distance and we use two values for testing

* 4: should have only one solution for a fully contrained sketch. But it has two
* 2: should have only one solution for a fully constrained sketch. But it has two

Steps to reproduce it:

* Open attached [broken_constraint_check.zip](https://github.com/FreeCAD/FreeCAD/files/8404524/broken_constraint_check.zip)
* switch to the part designer work bench
* open both 3d view and spreadsheet (window -> tiled)
* ensure that you made the sketch visible (but don't open it)
* check that you see two parallel rectangles (basically mirrored on the y-axis)  ![parallel_rectangles](https://user-images.githubusercontent.com/85514502/161429198-27bcd3ca-f2d7-4db1-8afb-1ccb7f971974.png)
* change in the spreadsheet the *distance* from 4 to *2*
* recompute using F5  ![parallel_negative_rectangles](https://user-images.githubusercontent.com/85514502/161429207-b28d26d5-4bf7-461a-a0f4-5d3f5e63b9db.png)
* change *distance* in the spreadsheet from 2 to *4*
* recompute using F5
* observe that the right most rectangle flipped on the lower (parallel to x) line ![parallel_flipped_rectangles](https://user-images.githubusercontent.com/85514502/161429213-b6d0135f-f549-4c8f-ae8f-0f46e3ed18ec.png)

This procedure (4 -> 2 -> 4) can be repeated again and again to always flip the right most rectangle via this specific vertical line. And then the left most rectangle (when they are in the negated rectangle state) as seen in ![parallel_flipped_negative_rectangles](https://user-images.githubusercontent.com/85514502/161429226-472cb1f8-1611-455a-bfd1-414bb3869d91.png)

After this state, the change from 2 -> 4 will result in the initial "parallel rectangle" state.

But when opening the sketch, the UI shows that the sketch would be fully constrained. Any attempt to add more constrains will result in "over constrained"/"invalid constrain" errors.

This problem can be reproduced with:

```
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28567 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: English/United States (en_US)
```

In my eyes, all these results are either

* completely fine because the sketch is not fully constrained. If this interpretation is correct then the UI is incorrectly thinking that the sketch is fully constrained (while it isnt)
* And if it is really fully constrained then there are some implicit constraints which are not clear to me and also not clear to the solver (or otherwise it wouldn't flip the rectangles).

### Anything else?

I searched the issue tracker but I am not sure whether #5555 is actually the same problem or not.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PLChris** [comment]
Known behaviour. It has often been discussed, that this may be unexpected, but it is no error.
