### ISSUE TITLE
[Bug] Draft Join fails when there is a minor difference in coordinates due to rounding

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#6734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=67936

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28611 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Draft

### Issue description

Draft Join fails even when points are visually coincident but their coordinates are slightly different due to rounding error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nexx512** [comment]
Actually, there seem to be more precision issues.
When drawing 2 wires on an arbitrary plane, even when end point snapping is used, the points of the two wires don't match. Therefore joining these wires is not possible.

I tried to work around this using a macro that connects close lines by assigning the points. However this didn't work either. The points were assigned correctly, But after then next recompute the point are off again by a few nm.

Looking at the [code](https://github.com/FreeCAD/FreeCAD/blob/a13e251ad45c3562875e6bcc8e1c7e84882a4d52/src/Mod/Draft/draftfunctions/join.py#L56-L62) I would suggest to not directly compare points with floating numbers. Instead the distance between point should be below a certain minimum distance that is slightly higher than rounding errors.

That is actually how you should compare floating point numbers. That leads me to the suggestion to overwrite the compare function of two points using a minimum distance compare.
