### ISSUE TITLE
[Bug] Spreadsheet merge/split cells bug

### ISSUE THREAD

**Issue by m1cha1** [FreeCAD/FreeCAD#6744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=67969

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28671 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)

```

### Subproject(s) affected?

Spreadsheet

### Issue description

Steps to reproduce:
Problem with merging
1. Merge cells A1 & B1
2. Merge A1 & B1 & C1 - it's not working

Problem with splitting
1. Merge cells A1 & B1
2. Merge cells C1 & D1
4. Select the range from A1 to D1 and split it - it's working partially, only C1 and D1 are splitted

2nd Problem with splitting (openBrain comment)
1. Merge A1 & B1
2. Merge A1B1 & C1
"Split cells" in the menu is now disabled (greyed out), not only with the current selection (A1/B1/C1) but also if you then only select the merged cell A1B1.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0penBrain** [comment]
As a whole, PR #6748 should resolve this ticket.
There are possible further improvements as discussed in the forum thread, but that should IMO be traced as other feature improvement tickets.

**Comment by wwmayer** [comment]
Are you sure the issues are solved? Especially none of the issues described by the OP in the forum are solved for me. It's even worse now. While in an older version the splitting worked for C1+D1 it now doesn't work at all any more because the command is disabled.
