### ISSUE TITLE
[Feature Request] Option to add gaps between the dimension extension lines and the part

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#6774]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=68153

### Subproject(s) affected?

Techdraw

### Idea description

Several users have already asked for an option to add gaps between dimension extension lines and parts being drawn. Currently, this is only possible with ASME dimensioning style but it would be good to have an option to add a custom gap also for other styles.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benj5378** [comment]
Fixed in #7133. @luzpaz, can you close the issue?
