### ISSUE TITLE
FreeCad does not start on windows 10 even though it used

### ISSUE THREAD

**Issue by iliaskessaris** [FreeCAD/FreeCAD#6790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?f=3&t=30573&sid=d9b4a91fdbb7acc09ea1439a943a9f27

### Version

0.19 (Release)

### Full version info

```shell
FreeCAD 0.19 revesion 24267 +148 (Git)
```

### Issue description

The application does not start on windows 10. I tried many previous versions from 17 up to 19.4 (the latest), but nothing. After installation as soon as I start the application a window tries to appear but immediately closes. 
In task manager I see that the application has not started.
At this point I would like to say that it used to work on windows 10.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
No information provided about crash. 
No forum thread. (Please don't link to a non-relevant forum thread. You need to start your own thread and get validation from the community.) 
Ticket doesn't follow guidelines. Closing.

**Comment by LeDimi4** [comment]
well, i got the same thing on my two pc's, and it seems that deleting both system and user config files from the user/roaming/freecad solves the cases... well - its starts to work after that, but its not a solution, rather a little hack to open the app and do something with it(
