### ISSUE TITLE
[Bug] Can't exit Stereo view

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=68314

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.20.28753 (Git)
Build type: Release
Branch: master
Hash: fe5ac277a017413a8646b621d5b993b0c606d551
Python 3.8.6+, Qt 5.15.2, Coin 4.0.1, OCC 7.5.3
Locale: Bulgarian/Bulgaria (bg_BG)
```

```shell
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28756 (Git)
Build type: Release
Branch: master
Hash: 53cc22225599a07addfbdc7c9b560795dbd80a83
Python 3.8.10, Qt 5.15.3, Coin 4.0.0, OCC 7.6.1
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Core

### Steps to Reproduce:
* Create new documemt
* View > Stereo > (Choose any stereo mode)
* View > Stereo > `Stereo off`

Result:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'NameError'>: Unknown stereo type 'None
```

You can reproduce via the console:  
```
>>> Gui.activeDocument().activeView().setStereoType("Anaglyph")
>>> Gui.activeDocument().activeView().setStereoType("None")
```

### Anything else?
First reported by @kisolre

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
That is as far as I got: https://github.com/FreeCAD/FreeCAD/blob/cb1093ef305010d218c74868e65d64e261fce3fb/src/Gui/CommandView.cpp#L2285

**Comment by chennes** [comment]
The problem is that "None" is not actually the value in that enumeration: it's "Mono".

**Comment by luzpaz** [comment]
@chennes just for my edification, where is the enumeration located in the code?
