### ISSUE TITLE
[Core] Base/FileInfo.cpp: macOS path names are UCS-4 encoded. For the moment we cannot handle path names containing non-ASCII characters.

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6802]
https://github.com/FreeCAD/FreeCAD/blob/cb1093ef305010d218c74868e65d64e261fce3fb/src/Base/FileInfo.cpp#L282-L284

**Comment by ageeye** [comment]
Is there a source, that MacOS used UCS-4 (similar UTF-32?) for path names? If I try to get the file system encoding by python console[1], the result is UTF-8. But MacOS used other representing form, which called NFD [2]. If I understand correctly, the standard libraries which FreeCAD used not support NFD. That means many lines of the source code have to changed.


 Or did I understand that incorrectly?

[1] Script:
```
import sys
sys.getfilesystemencoding()
```

[2] [unicode-composition-for-filenames](https://opensource.apple.com/source/subversion/subversion-52/subversion/notes/unicode-composition-for-filenames.auto.html)

**Comment by luzpaz** [comment]
Per the git blame that portion of the code is ~11 years old. That FIXME maybe obsolete at this point. @wwmayer can you confirm ?

**Comment by wwmayer** [comment]
> Is there a source, that MacOS used UCS-4 (similar UTF-32?) for path names?

When we started to handle the encoding on the different platforms I read some articles about Linux, Windows and macOS and I am pretty sure that somewhere it was claimed that macOS uses UCS-4 or UTF-32 (which is more or less identical). Not sure if it was the same resource that claimed that Windows uses UCS-2 which in fact  was true but has changed with Windows 2000.

Either the resource was plain wrong or things have changed in the meantime. At least when searching now I cannot find any resource claiming that.

Anyway, the comment is in `FileInfo::toStdWString()` and this function is only supposed to be used for Windows when using the overloaded IO stream functions for wide characters that are not available under Linux or macOS.

So, the comment can be removed and instead an exception should be raised.

**Comment by luzpaz** [comment]
Thanks @ageeye for responding.  
Thanks @wwmayer for the follow-up and commit. :+1:

**Comment by wwmayer** [comment]
std::wstring uses wchar_t that according to [Wikipedia](https://en.wikipedia.org/wiki/Wide_character#C/C++) is unspecified in C++. It depends on the compiler where it can be even defined as 8-bit char.

Usually on Windows it's defined as 16-bit char and on Linux/macOS it's mostly 32-bit.
