### ISSUE TITLE
[Feature Request] CLI -t flag should list all available unit tests instead of user guessing which to run (besides `-t 0` AKA all tests)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6809]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

n/a

### Subproject(s) affected?

Core

### Idea description

When running FreeCAD executable from the CLI with the `-t` flag, user should get a list of optional individual tests to choose from instead of needing to guess or lookup the names for them.  

`./Applications/FreeCAD_weekly-builds-28751.AppImage -t`
Result:
![Screenshot_20220428_075557](https://user-images.githubusercontent.com/4140247/165746735-49776e1b-4a60-4d96-ae0c-ce89e4528f21.png)

Current workaround:  
I need to start FC GUi and go to the TestWB and find the name of the individual test that I want to run (not very convenient)
![Screenshot_20220428_075845](https://user-images.githubusercontent.com/4140247/165747308-bab5a6a4-3dff-43f6-9689-8658fc5c7710.png)
 

### Anything else?

Relevant code blocks:

https://github.com/FreeCAD/FreeCAD/blob/bcc960dc696571320d1f621d3aebdbf0fca790e7/src/App/Application.cpp#L2391-L2400

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Here's the GUI code used in TestWB to get the tests:  
https://github.com/FreeCAD/FreeCAD/blob/aa19e216625cbfdab5099d8eea6b62122917a3f6/src/Mod/Test/Gui/UnitTestImp.cpp#L254-L260

CC @wwmayer

**Comment by luzpaz** [comment]
@mwganson i was wondering if you can help me figure out how the UnitTestImp.cpp is getting the names of all the tests. It looks like the names are found in the `src/Mod/$foo/init.py` files, for instance the AddonManager test files 
(https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/AddonManager/Init.py#L8)
 
`FreeCAD.__unit_test__ += ["TestAddonManagerApp"]`

**Comment by mwganson** [comment]
Sorry, I'm not feeling well right now.

**Comment by ageeye** [comment]
You can clone [TestApp.All](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Test/TestApp.py#L55):

```
def PrintAll():
    # Registered tests
    tests = FreeCAD.__unit_test__

    print("Registered test units:")

    for test in tests:
        print(test)
```

Untested:
```
if (testCase.empty()) {
    testCase = "TestApp.PrintAll";
}
```

**Comment by yorikvanhavre** [comment]
From the command line, though, not all tests are present I think:
```
>>> FreeCAD.__unit_test__
['MeshTestsApp', 'TestFemApp', 'TestDraft', 'BaseTests', 'UnitTests', 'Document', 'Metadata', 'UnicodeTests', 
'TestPythonSyntax', 'TestSketcherApp', 'TestAddonManagerApp', 'TestSpreadsheet', 'TestTechDrawApp', 
'TestPathApp', 'TestPartApp', 'TestOpenSCADApp', 'TestPartDesignApp']
```
Of course a quick fix would be to hard-code the list in the help text shown to the user...

**Comment by ageeye** [comment]
> From the command line, though, not all tests are present I think:
> 
> ```
> >>> FreeCAD.__unit_test__
> ['MeshTestsApp', 'TestFemApp', 'TestDraft', 'BaseTests', 'UnitTests', 'Document', 'Metadata', 'UnicodeTests', 
> 'TestPythonSyntax', 'TestSketcherApp', 'TestAddonManagerApp', 'TestSpreadsheet', 'TestTechDrawApp', 
> 'TestPathApp', 'TestPartApp', 'TestOpenSCADApp', 'TestPartDesignApp']
> ```
> 
> Of course a quick fix would be to hard-code the list in the help text shown to the user...

Yes. "./FreeCADCmd -t" only display which do not need the GUI. But "./FreeCAD -t" lists all test units. 

[First Draft](https://github.com/ageeye/FreeCAD/commit/698a585740ff84074fcb1cf47b54a990576f85b3)

**Comment by luzpaz** [comment]
Nice @ageeye  
Would you be open to making a PR? :grinning: 

@mwganson hey mate, hope you're feeling better. I was AFK for a while myself so I didn't see your response before.

**Comment by ageeye** [comment]
> Nice @ageeye Would you be open to making a PR? 😀

Done
