### ISSUE TITLE
[Bug] Path/Helix Start radius broken

### ISSUE THREAD

**Issue by marshr32** [FreeCAD/FreeCAD#6826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=15&t=68150&start=10

### Version

0.20 (Development)

### Full version info

```shell
[code]
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28567 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: English/New Zealand (en_NZ)
Installed mods: 
  * A2plus
  * CurvedShapes
  * Curves 0.4.2
  * sheetmetal 0.2.49
[/code]
```

### Subproject(s) affected?

Path

### Issue description

When using the helix tool for holes greater that 2x tool dia, a second path should be created to remove the centre of the hole (or multiple) .
However when "start radius" is set to 0mm this doesn't happen. Setting it to 0.01mm brings up the other tool path/s.
Multiple tool paths should be the default as having just one will leave an unsupported part in the middle...... dodgy!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
@sliptonic , can you have a quick look. As I understand it the fix is simply to allow also a negative helix start radius.
(FC 0.20 is open for at least another weeks for bugfixes.)
