### ISSUE TITLE
Path workbench Post Process not starting spindle in git build 27422

### ISSUE THREAD

**Issue by bhowiebkr** [FreeCAD/FreeCAD#6842]
Missing commands like M3, M4, S##### and possibly others

**Comment by sliptonic** [comment]
I cannot duplicate this.  There's no attached project file.  There's no forum thread.  
Recommend closing issue.   I will leave open for now if OP wants to improve the bug report.  Will close if not improved within a week or so.

**Comment by luzpaz** [comment]
@bhowiebkr if you produce a file, re-open ticket. Closing for now.
