### ISSUE TITLE
CMake: Quarter support on macOS 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6856]
Is this FIXME still relevant ?

https://github.com/FreeCAD/FreeCAD/blob/5d49bf78de785a536f941f1a6d06d432582a95d3/src/Gui/Quarter/CMakeLists.txt#L62

**Comment by luzpaz** [comment]
@ipatch care to weigh-in ?

**Comment by ipatch** [comment]
ill try and get back to you on that one tomorrow. i've been working towards getting python 3.10 support going with macos. i got pyside, shiboken, and coin, but ran into some issues bulding pivy using the cmale setup, need to open an issue about that. and then build a new app bundle hopefully around python 3.10.

life caught up with me today so didn't get troubleshoot my pivy compliation issue.

**Comment by ageeye** [comment]
@ipatch Please use the head:

`brew install --head %your%/freecad/pivy`

**Comment by ipatch** [comment]
@ageeye 

here's what i'm running into with **pivy**

https://github.com/coin3d/pivy/issues/96

**Comment by donovaly** [comment]
What is the status of this bug? If there will not be a PR to fix this in the next week, the bug cannot be fixed for FreeCAD 0.20.

**Comment by luzpaz** [comment]
bumped upstream coin ticket

**Comment by luzpaz** [comment]
Upstream ticket is dormant. How should we proceed ?

**Comment by adrianinsaval** [comment]
The question is, does it affect our usage? If not, I don't think we should care

**Comment by luzpaz** [comment]
Closing since this an upstream issue.
