### ISSUE TITLE
[Feature Request] New Datum Line based on Intersection between two Planes

### ISSUE THREAD

**Issue by RickX56** [FreeCAD/FreeCAD#6870]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?t=62149

### Subproject(s) affected?

PartDesign

### Idea description

Hi, 
I'm requesting an old feature discussed on FreeCAD forum (https://forum.freecadweb.org/viewtopic.php?t=62149)
Would it be possible to create a Datum Line from the intersection of two datum planes? 
There is a macro to do this ([datumplane_intersection.FCMacro](https://forum.freecadweb.org/download/file.php?id=164282)) but it would be best for it to be imbedded into Part Design Workbench, thus making it parametric.

Thanks for your hard work!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
CC @mwganson (as the forum shows your participation)

**Comment by luzpaz** [comment]
cc @mwganson could you perhaps test the proposal by LemonBoy ? :point_up_2:

**Comment by mwganson** [comment]
I am not able to test at this time.
