### ISSUE TITLE
[Bug] Certain PostProcessors spam errors and other output.

### ISSUE THREAD

**Issue by JanneKro** [FreeCAD/FreeCAD#6871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

N/A

### Version

0.20 (Development)

### Full version info

```shell
The implementation in 'centroid' and 'nccad' try to read the filename of the current document as soon as the PP is being loaded.

If one is to go into Edit -> Preferences -> Path to choose (or even hover over) select PPs, the Report-view is spammed with errors as no ActiveDocument exists.

Also, since these PPs seem to be reloaded multiple times, a select few also keep outputting '<name_of_pp> gcode postprocessor loaded.' repeatedly.
```

### Subproject(s) affected?

Path

### Issue description

* Start FreeCAD
* Select Path Workbench
* Go into Edit -> Preferences -> Path
* Expand the "Post Processor"-tab
* However over the list of post-processors.
* -> **Report View is filled with errors.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JanneKro** [comment]
The issue does no longer exist on master branch.

**Comment by luzpaz** [comment]
@JanneKro JFYI:
* You can remotely close a ticket by adding `Fixes #<ticket_number>` in the commit message body
* In the ticket you filed above, please always add you full [About](https://wiki.freecad.org/About) info. The desciption of the ticket should go in the 'Issue Description' section. You mixed those up.
* Also you can close a ticket by saying `Closed in <add_link_to_git_commit_here>` which helps anyone scanning through the ticket to quickly find what they were looking for.
