### ISSUE TITLE
[Crowdin] UI tweak needed for: Preference - Display - Navigation (zoom step) 

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD#6875]
Can we align "zoom step" to the right and increase region for text?
I have to shorten the text so that it is not cut off on the left
![Знімок екрана з 2022-05-11 20-30-05](https://user-images.githubusercontent.com/1382812/167911648-ad2bf90d-2225-477c-9381-dd7c00c21e4a.png)

![Знімок екрана з 2022-05-11 20-30-39](https://user-images.githubusercontent.com/1382812/167911667-df251ec8-6e4d-4f3d-9a34-17b5384d599e.png)

**Comment by luzpaz** [comment]
Transferred to FreeCAD/FreeCAD for quick discussion

**Comment by kaktusus** [comment]
Aleks how did you achieve that the function buttons at the bottom of the window have their labels translated?

![image](https://user-images.githubusercontent.com/39754351/167933116-bfb28853-f81f-447b-be93-51dba48bb87b.png)

Your point is valid, I didn't even pay attention to it before.
The label is truncated, the caption unreadable.

**Comment by Kuzma30** [comment]
Like this? :)
![Знімок екрана з 2022-05-12 10-13-01](https://user-images.githubusercontent.com/1382812/168013110-61e2fbf5-0765-4ee4-b6d3-71fd01817547.png)

You can test with this file https://github.com/Kuzma30/FreeCAD/commit/e4c09e15d097b5ab629392bfd7467df49abfab1e

**Comment by kaktusus** [comment]
8-O

**Comment by kaktusus** [comment]
Where should I copy this file?

**Comment by kaktusus** [comment]
![image](https://user-images.githubusercontent.com/39754351/168023569-e1a0f463-c31b-4d10-a3ac-2a699f3bcd3d.png)

well, I copied it to the standard file location for translations. It worked.
I made one small change in it to make the file 100% compatible with the source file. 
Now there are not even warnings.

What needs to be done to make the change permanent and available to all?

**Comment by Kuzma30** [comment]
https://github.com/qt/qttranslations
Branch 5.15.2 more info later if need

**Comment by donovaly** [comment]
There is now place also for longer translations:
![FreeCAD_OCFMHOmcHV](https://user-images.githubusercontent.com/1828501/168052611-b48829b9-4389-4f42-a4e0-8e18d51a035c.png)
