### ISSUE TITLE
[Draft] Importing SVG: missing colors

### ISSUE THREAD

**Issue by Jihadist** [FreeCAD/FreeCAD#6900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=66981

### Version

0.19 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24267 +99 (Git)
Build type: Release
Branch: Branch_0.19.3
Hash: 6530e364184ce05ccff39501e175cf2237e6ee4b
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

### Issue description

FreeCAD renders long (very long) colored lines as black when importing from svg
FreeCAD view:
![изображение](https://user-images.githubusercontent.com/26579016/168986567-c44d85c3-4fb4-4302-88d9-d5d942231312.png)
Firefox view:
![изображение](https://user-images.githubusercontent.com/26579016/168986607-e4589bdb-46e4-4d5f-a025-2a8b4bc3116d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
The issue here is that the color info is done on groups, not on geometry. See [file to download](https://forum.freecadweb.org/download/file.php?id=182291). Seems supported by Firefox, and I couldn't see in inkscape... We need to see if this is officially supported in SVG

**Comment by donovaly** [comment]
> Seems supported by Firefox, and I couldn't see in inkscape.. We need to see if this is officially supported in SVG

I tried the brand-new Inkscape version 1.2 and also with this, the example SVG from the previous post is not displayed as you expect it - there are no lines at all and Inkscape only allows you to zoom out down to 1.0 % of the original size.

> We need to see if this is officially supported in SVG

It is see
https://www.w3.org/TR/SVG11/struct.html#GElement
and as example
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g

So independent that Inkscape has issues with the file, it is according to the SVG 1.1 specs and we should therefore support it.

**Comment by yorikvanhavre** [comment]
indeed... and the group supports the whole array of styling that normal entities do... okay, indeed we need to add that!

**Comment by donovaly** [comment]
I reported the bug also to Inkscape:
https://gitlab.com/inkscape/inbox/-/issues/7030

**Comment by luzpaz** [comment]
@donovaly can you bump the inkscape ticket to get more exposure ?

**Comment by donovaly** [comment]
> @donovaly can you bump the inkscape ticket to get more exposure ?

What does "bump a ticket" mean?
I reported it correctly and I cannot fix it in Inkscape. The Inkscape guys are also only volunteers.

**Comment by luzpaz** [comment]
It simply means to type 'Bump' in the ticket so it brings it back to the Inkscape team's radar

**Comment by luzpaz** [comment]
@0penBrain does #9242 address this issue ?

**Comment by luzpaz** [comment]
Should this ticket be in the v0.21 release roadmap ?

**Comment by yorikvanhavre** [comment]
sample file: [test.svg](https://github.com/FreeCAD/FreeCAD/assets/1136856/1307013d-9583-4408-b11a-ae34cb3772cb)
