### ISSUE TITLE
[Bug] Crash on start

### ISSUE THREAD

**Issue by Jihadist** [FreeCAD/FreeCAD#6901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=68657

### Version

0.19 (Release)

### Full version info

```shell
FreeCAD 0.19 Revision: 24267 +148 (Git)
```

### Issue description

I used FreeCAD for months, but after one day I see crash every time I launch freecad.
Console log:
```
$ ./FreeCAD.exe
[5652:4816:0513/142502.444:ERROR:gl_surface_wgl.cc(388)] wglCreatePbufferARB not available.
[5652:4816:0513/142502.444:ERROR:gl_surface_qt.cpp(197)] Requested OpenGL implementation is not supported. Implementation: 1
Illegal storage access...
Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: Illegal storage access! Please save your work under a new file name and restart the application!
Segmentation fault
```

This anwser looks relevant https://stackoverflow.com/questions/62920307/requested-opengl-implementation-is-not-supported-implementation-1-error-in-p

Full crash logs please view in forum discussion  

### Anything else?

I don't have this issue on my desktop, but my remote desktop affected
Windows version:
OS Name: Microsoft Windows Server 2019 Standard Evaluation
OS Version: 10.0.17763 N/A Build 17763

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
Please only report issue s that are confirmed by others. Up to now nobody can confirm the crash and there is no response in the forum
-> closing for now
