### ISSUE TITLE
[Bug] navicube location sometimes jumps to other side

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#6935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=10&t=69003

### Version

0.19 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24267 +148 (Git)
Build type: Release
Branch: Branch_0.19.4
Hash: 476ecf091941bead59b14e44afa6064d5a66afa3
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: German/Germany (de_DE)
```

### Issue description

- set the NaviCube location to TopLeft
- grab the right border of the main window and shrink the window it to the minimum
result: The NaviCube jumps to the right edge and stays there:
![FreeCAD_jD61WCSdcb](https://user-images.githubusercontent.com/1828501/170900646-9bcee7e4-8c4f-41cc-8435-145ddfc87264.gif)

**Comment by donovaly** [comment]
Interestingly the bug dos not appear on all systems. For example I took the same installer and on some PCs I see this bug while on others I don't. All PCs have Win 10 2021 H2. So it must be something with the graphics settings.

**Comment by luzpaz** [comment]
@donovaly was this bug fixed before release?

**Comment by donovaly** [comment]
> @donovaly was this bug fixed before release?

No.

**Comment by Jolbas** [comment]
I'm working on https://github.com/FreeCAD/FreeCAD/issues/6818 and this issue is going to be fixed at the same time
