### ISSUE TITLE
[Bug] [FEM] editing histogram blocks access to FreeCAD's main window

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#6959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=18&t=69162

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.29011 (Git)
Build type: Release
Branch: master
Hash: e8f1bde36707b31e4f0d9a0a909d0fee8cb74f00
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, OCC 7.6.2
```

### Subproject(s) affected?

FEM

### Issue description

- open the CCX result dialog
- select there e.g. the result "Displacement X"
- the Click the Histogram button
- in the histogram click in the toolbar the button "Configure subplots" (number 3 counted from the right)
result: the configure dialog opens behind the histogram but since the histogram can't be moved when a subdialog is open and since FC is blocked too, you cannot do anything anymore
The only way is to take the hammer of the Windows Task-manager to kill the histogram subdialog, therefore this is a rather major bug.
-> setting to 0.20 milestone

I assume the fix is to bring the subdialog to front. Additionally FC should not be frozen when a plot is open.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@FEA-eng can u help us find Linux testers for this?

**Comment by donovaly** [comment]
@chennes tested it earlier today. I committed now a simpler fix than in the above diff.

**Comment by donovaly** [comment]
Many thanks!
Note that I got 2 positive test results from people at Linux before I merged this.

I'll comment further in #6989.

**Comment by 0penBrain** [comment]
> Note that I got 2 positive test results from people at Linux before I merged this.

I guess so. :) And indeed it "works" on Linux too. Notice that actually, the issue didn't exist on Linux --at least on mine-- as "StayOnTopHint" is relying on the WM that widely differs. ;)
