### ISSUE TITLE
Conda: graphviz not found automatically

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD#6986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

no forum discussion

### Version

0.20 (Development)

### Full version info

```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.28929 (Git)
Build type: Release
Branch: master
Hash: 9251480ddb
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: German/Austria (de_AT)
Installed mods: 
  * fcgear 1.0.0
```

### Issue description

I guess graphviz should be found automatically as it is installed in std bin directory. Not sure if there has changed anything regarding the search path.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@looooo you referring to how/where CMake is looking for graphics?

**Comment by luzpaz** [comment]
Sorry, what's the difference between 'built' and 'run' ?

**Comment by looooo** [comment]
in conda-land we have build, host and run dependencies. build-dependencies are dependencies that are necessary to build a library (eg.: make, ninja, compilers), host dependencies are libraries which are necessary for the compilation (eg.: boost, Eigen, ...) run dependencies are libraries which are only needed for running a library/programm (eg: graphviz, numpy, scipy)

So what I actually was referring to were the host-dependencies. As it doesn't make any difference to compile freecad with or without graphviz, it doesn't make a lot of sense to have it installed during the compilation. But to make the dependency-graph work for freecad we need it at runtime.

This is my personal view on this topic. Not sure if it is super correct, but at least it's a way to understand the different dependency types for conda. Also have a look at the freecad-recipe where we list these different dependency-types:

https://github.com/conda-forge/freecad-feedstock/blob/main/recipe/meta.yaml#L18

**Comment by luzpaz** [comment]
graphiz should be considered essential as it helps the user troubleshoot their models, right?

**Comment by luzpaz** [comment]
Heads up, Graphviz  was fixed in Snap package. See https://github.com/FreeCAD/FreeCAD-snap/commit/3b43c39b47e5311709b329f47e945f87733bd5b9

**Comment by luzpaz** [comment]
@looooo just checking in on the status of this (did you see the Snap fix :point_up_2: ? )

**Comment by looooo** [comment]
Last time I checked it worked for me on a Mac.

**Comment by looooo** [comment]
I will check this.

**Comment by luzpaz** [comment]
@looooo ping

**Comment by looooo** [comment]
also works on linux. So I close this one.
