### ISSUE TITLE
[Bug] [Techdraw] Rich texteditor Techdraw icons not readable on dark themes.

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD#6988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=599460#p599460

### Version

0.20 (Development)

### Full version info

```shell
Not version depended. 
But tested in :
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.28886 (Git)
Build type: Release
Branch: master
Hash: a564d5ced7aecf320a0ac2d73f824a3dc7861eb3
Python 3.8.10, Qt 5.15.3, Coin 4.0.1, OCC 7.5.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
  * Assembly3 0.11.3
  * Behave-Dark-Colors 0.0.1
  * FeedsAndSpeeds 0.4.0
  * FEM_FrontISTR 0.1.0
  * lattice2 1.0.0
  * ProDarkThemePreferencePack 1.0.0
  * SelectorToolbar
  * sheetmetal 0.2.49
  * ToolbarStyle
[/code]
```

### Subproject(s) affected?

Techdraw

### Issue description

The text icons in the Rich text editor are not readable in dark theme's since they are black and have no background.
It seems like the background is not addressable directly by a style-sheet, which would be nice.
But for now I think it is just fast and simplest too just add a white background too the icons.
**And I already did that see below for attachments.**
Icons need to be in : [FreeCAD](https://github.com/FreeCAD/FreeCAD/tree/52c86de3cbb62346c94539696a3288a9c28b5f46)/[src](https://github.com/FreeCAD/FreeCAD/tree/52c86de3cbb62346c94539696a3288a9c28b5f46/src)/[Mod](https://github.com/FreeCAD/FreeCAD/tree/52c86de3cbb62346c94539696a3288a9c28b5f46/src/Mod)/[TechDraw](https://github.com/FreeCAD/FreeCAD/tree/52c86de3cbb62346c94539696a3288a9c28b5f46/src/Mod/TechDraw)/[Gui](https://github.com/FreeCAD/FreeCAD/tree/52c86de3cbb62346c94539696a3288a9c28b5f46/src/Mod/TechDraw/Gui)/[Resources](https://github.com/FreeCAD/FreeCAD/tree/52c86de3cbb62346c94539696a3288a9c28b5f46/src/Mod/TechDraw/Gui/Resources)/[icons](https://github.com/FreeCAD/FreeCAD/tree/52c86de3cbb62346c94539696a3288a9c28b5f46/src/Mod/TechDraw/Gui/Resources/icons)/MRTE/

### Anything else?

![textItalic](https://user-images.githubusercontent.com/29804962/172550894-87f8ff57-96b4-40cd-bea5-e1bf5b1ab683.svg)
![textStrike](https://user-images.githubusercontent.com/29804962/172550898-1a4f379a-0765-444b-ad7f-1265e5761678.svg)
![textUnderline](https://user-images.githubusercontent.com/29804962/172550900-257c1147-52a9-49da-b9ce-f980bdf2bc48.svg)
![bgColor](https://user-images.githubusercontent.com/29804962/172550902-e587f8f7-4dd8-4ea7-a0c3-b8ae45e2eac5.svg)
![fgColor](https://user-images.githubusercontent.com/29804962/172550905-fb4cf4c3-56bc-478c-b14d-f2e4d0da8c4c.svg)
![indentLess](https://user-images.githubusercontent.com/29804962/172550908-a3bd44df-ca8a-4690-884d-06b6dcafa5bc.svg)
![indentMore](https://user-images.githubusercontent.com/29804962/172550912-ada0ea7a-65fb-4724-8be0-8efa30934a7a.svg)
![listBullet](https://user-images.githubusercontent.com/29804962/172550914-84a4bb5d-f02c-4a96-8887-38b2eefaec62.svg)
![menu](https://user-images.githubusercontent.com/29804962/172550915-dcf0e5f3-0abe-45e8-849f-ac1f1c27f243.svg)
![textBold](https://user-images.githubusercontent.com/29804962/172550916-9208faca-4171-47dd-9be0-cc3b926370d4.svg)
[srcModTechDrawGuiResourcesiconsMRTE_whiteback.zip](https://github.com/FreeCAD/FreeCAD/files/8859051/srcModTechDrawGuiResourcesiconsMRTE_whiteback.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
![afbeelding](https://user-images.githubusercontent.com/29804962/172553183-8a6bd94f-9877-4dce-a04c-eb57351af7cc.png)
Screenshot about the issue

**Comment by WandererFan** [comment]
merged to master.  commit 1b65b3f600.
