### ISSUE TITLE
Supporting Qt6 / PySide6 / Shiboken6

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6992]
This ticket tracks the Qt5 :arrow_right: Qt6 migration progress. See also dedicated [forum thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=65089)   

## Commits 

Qt6 commits to master: 
| commit | summary | committer |
| --------- | ------------- | ------------- |
| 339bb73e9f | Base: add convenience classes/functions that are marked as deprecated in Qt 5.15 and removed in Qt 6  | wwmayer | 

## Notes

* [Porting to Qt 6](https://doc.qt.io/qt-6/portingguide.html)
* [Porting from PySide2 to PySide6](https://doc.qt.io/qtforpython/porting_from2.html)
* A Clazy-based tool is available to facilitate porting from Qt 5 to Qt 6: [Porting C++ Applications to Qt 6 using Clazy checks](https://doc.qt.io/qt-6/porting-to-qt6-using-clazy.html). #7134

### Module level changes
- [ ] The content of the *QtOpenGL* module has been replaced. The class `QGLWidget` and related classes (`QGLContext`, `QGLFunctions`, `QGLShaderProgram`) have been removed. Parts of the *Open GL* functionality from *QtGui* have been extracted into this module, for example `QOpenGLBuffer` and `QOpenGLShaderProgram`. There is a new module *QtOpenGLWidgets* which contains the class `QOpenGLWidget`, a replacement for `QGLWidget`.

## Imports
- [ ] Change PySide2 -> PySide6
Ex. 
	```python
	from PySide2.QtWidgets import QApplication...
	from PySide2 import QtCore
	```
    to 
	```python
	from PySide6.QtWidgets import QApplication...
    from PySide6 import QtCore
	```
- [ ] Some classes are in a different module now, for example `QAction` and `QShortcut` have been moved from `QtWidgets` to `QtGui`.

### Class/Function Deprecations
- [ ] The High DPI scaling attributes `Qt.AA_EnableHighDpiScaling`, `Qt.AA_DisableHighDpiScaling` and `Qt.AA_UseHighDpiPixmaps` are **deprecated**. High DPI is by default enabled in Qt 6 and cannot be turned off.
- [ ] `QDesktopWidget` has been **removed**. `QScreen` should be used instead, which can be retrieved using `QWidget.screen()`, `QGuiApplication.primaryScreen()` or `QGuiApplication.screens()`.
- [ ] `QFontMetrics.width()` has been **renamed** to `horizontalAdvance()`.
- [ ] `QMouseEvent.pos()` and `QMouseEvent.globalPos()` returning a `QPoint` as well as `QMouseEvent.x()` and `QMouseEvent.y()` returning `int` are now **deprecated**. `QMouseEvent.position()` and `QMouseEvent.globalPosition()` returning a `QPointF` should be used instead.
- [ ] `Qt.MidButton` has been **renamed** to `Qt.MiddleButton`.
- [ ] `QOpenGLVersionFunctionsFactory.get()` instead of `QOpenGLContext.versionFunctions()` should be used to obtain *Open GL* functions.
- [ ] `QRegExp` has been **replaced** by `QRegularExpression`.
- [ ] `QWidget.mapToGlobal()` and `QWidget.mapFromGlobal()` now also accept and return `QPointF`.
- [ ] Functions named `exec_` (classes `QCoreApplication`, `QDialog`, `QEventLoop`) have been **renamed** to `exec` which became possible in Python 3.
 
## Other tasks
- [ ] Track Addons (workbenches, addons, macros, preference packs) for Qt6 migration
- [ ] Snap package migration to Qt6 https://github.com/FreeCAD/FreeCAD-snap/issues/19
- [ ] flatpak package migration to Qt6 https://github.com/flathub/org.freecadweb.FreeCAD/issues/54
- [ ] Conda package migration to Qt6
- [ ] homebrew-FreeCAD package migration to Qt6
- [ ] Windows Libpack package migration to Qt6
- [ ] https://github.com/FreeCAD/FreeCAD/pull/9977

**Comment by luzpaz** [comment]
Transferred to FreeCAD/FreeCAD repo

**Comment by luzpaz** [comment]
Added the Also [Porting from PySide2 to PySide6](https://doc.qt.io/qtforpython/porting_from2.html) link to the OP of this ticket.

**Comment by luzpaz** [comment]
Started tracking Qt6 commits to master in the OP. See **Commits** section

**Comment by luzpaz** [comment]
Hi @wwmayer, how would you feel about linking Qt6 related commits to this ticket so we can track them in one place?

**Comment by wwmayer** [comment]
339bb73e9f23f is not directly related to Qt6 but allows to reduce some `if QT_VERSION < QT_VERSION_CHECK(...)` checks in client code.

**Comment by luzpaz** [comment]
Related: 
#7712  
#7677  
#7647

**Comment by iamdbychkov** [comment]
Is there any instruction on installing FreeCad on newer distributions? Official binaries is not useful as every operation fails on some python error.
Is there a way to instruct compile which python to use when building FreeCad from source? For some reason page with building instructions is unavailable.
Shouldn't this instruction be on a front page for now?

**Comment by adrianinsaval** [comment]
what's still missing for qt6 support?

**Comment by berniev** [comment]
MacAppBundle/CMakeLists.txt
Resolve Homebrew v Pip v native on macOS esp re Python, PySide, Shiboken

**Comment by luzpaz** [comment]
Added https://github.com/FreeCAD/FreeCAD/pull/9977 to the OP

**Comment by luzpaz** [comment]
We're gonna need some help porting Snap to Qt6 (https://github.com/FreeCAD/FreeCAD-snap/issues/19). Volunteers for this would be very much appreciated!

**Comment by chennes** [comment]
FYI compiling against Qt6 with MSVC activates the `/permissive-` option, which we don't currently support. PR #11014 will address these issues.

**Comment by luzpaz** [comment]
> a nightly F(edora)39 build at this point isn't going to happen against the stock F39 repos, as there are no python qt5 bindings. For a FreeCAD nightly to be compiled successfully for F39, python qt6 bindings need to be in the virtual environment (there is already a build in copr for python-pyside6). This would require copr to include python-pyside6 in it's virtual build environment for FreeCAD nightly (it can be done, but I don't have enough experience with copr to set it up properly). When (and if) FreeCAD nightly is compiled successfully, any user who enables the FreeCAD nightly repo and wants to use it, would need to install python-pyside6 too - either will be provided from another copr repo, or ideally shipped in the FreeCAD copr repo (until Fedora officially includes the python-pyside6 in their official repos). Can someone just fix the references in the spec file from master to main, so we can get at least an attempt for a build for F38. It might finish successfully, or it might fail, but at least we can get the logs.

ref: https://github.com/FreeCAD/FreeCAD/issues/11619#issuecomment-1868390068

**Comment by adrianinsaval** [comment]
Are they using Py_LIMITED_API in their pyside build? Pyside6 uses it by default I think, I had to disable it to be able to build freecad on flatpak because freecad doesn't support that.

**Comment by ipatch** [comment]
can someone explain to me how a workbench such as draft which heavily uses the runtime dep of pyside works with qt6?

on the build box i'm working with i have qt6 and pyside6 installed but i still see references in the freecad source using `from PySide.QtCore` which from what i'm experience that "call" will not work with pyside6 because the module name is PySide6, no?

and doing a search in the draft sub dir of the freecad src repo i see all the mentions of `PySide`

```
╰─λ rg -L -i pyside .                                                                                                   0 (0.015s)
./draftutils/todo.py
39:import PySide.QtCore as QtCore

./draftguitools/gui_arrays.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./WorkingPlane.py
39:from PySide.QtCore import QT_TRANSLATE_NOOP
1731:            from PySide import QtGui
1768:    from PySide import QtWidgets

./drafttaskpanels/task_polararray.py
30:import PySide.QtGui as QtGui
31:from PySide.QtCore import QT_TRANSLATE_NOOP
87:        self.form = Gui.PySideUic.loadUi(ui_file)

./DraftGui.py
42:import PySide.QtCore as QtCore
43:import PySide.QtGui as QtGui
44:import PySide.QtWidgets as QtWidgets

./drafttaskpanels/task_scale.py
31:import PySide.QtCore as QtCore
32:import PySide.QtGui as QtGui
33:import PySide.QtWidgets as QtWidgets

./draftguitools/gui_annotationstyleeditor.py
30:import PySide.QtGui as QtGui
31:import PySide.QtWidgets as QtWidgets
33:from PySide.QtCore import QT_TRANSLATE_NOOP
62:    form: PySide.QtWidgets.QDialog
94:        self.form = Gui.PySideUic.loadUi(ui_file)

./draftutils/gui_utils.py
51:    from PySide import QtCore
52:    from PySide import QtGui
53:    # from PySide import QtSvg  # for load_texture
710:        # from PySide import QtGui, QtSvg

./drafttaskpanels/task_shapestring.py
31:import PySide.QtCore as QtCore
32:import PySide.QtGui as QtGui
52:        self.form = Gui.PySideUic.loadUi(":/ui/TaskShapeString.ui")

./draftutils/grid_observer.py
34:    from PySide import QtWidgets

./draftutils/init_tools.py
33:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_togglemodes.py
36:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_polygons.py
35:from PySide.QtCore import QT_TRANSLATE_NOOP

./drafttaskpanels/task_orthoarray.py
30:import PySide.QtGui as QtGui
31:from PySide.QtCore import QT_TRANSLATE_NOOP
87:        self.form = Gui.PySideUic.loadUi(ui_file)

./draftutils/units.py
31:import PySide.QtCore as QtCore

./draftguitools/gui_texts.py
36:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftutils/translate.py
35:import PySide.QtCore as QtCore
36:import PySide.QtWidgets as QtWidgets
75:    Reference: https://doc.qt.io/qtforpython/PySide2/QtCore

./drafttaskpanels/task_circulararray.py
30:import PySide.QtGui as QtGui
31:from PySide.QtCore import QT_TRANSLATE_NOOP
87:        self.form = Gui.PySideUic.loadUi(ui_file)

./draftutils/utils.py
39:import PySide.QtCore as QtCore

./DraftTools.py
42:from PySide import QtCore, QtGui

./draftguitools/gui_labels.py
38:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftutils/init_draft_statusbar.py
34:import PySide.QtCore as QtCore
35:import PySide.QtGui as QtGui
36:import PySide.QtWidgets as QtWidgets

./draftutils/params.py
26:import PySide.QtCore as QtCore
38:    from PySide import QtWidgets

./draftguitools/gui_move.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./drafttaskpanels/task_selectplane.py
43:from PySide import QtWidgets
50:        self.form = Gui.PySideUic.loadUi(":/ui/TaskSelectPlane.ui")

./drafttaskpanels/__init__.py
40:            self.form = Gui.PySideUic.loadUi(ui_file)

./draftguitools/gui_arcs.py
33:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_split.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./InitGui.py
204:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_splines.py
35:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_circulararray.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_orthoarray.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_draft_annotation.py
44:from PySide.QtCore import QT_TRANSLATE_NOOP
46:import PySide.QtCore as QtCore
47:import PySide.QtGui as QtGui

./draftguitools/gui_wire2spline.py
39:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_subelements.py
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_shapestrings.py
40:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_mirror.py
38:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_pointarray.py
36:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_planeproxy.py
28:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_points.py
39:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_downgrade.py
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_heal.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_hatch.py
26:import PySide.QtCore as QtCore
27:import PySide.QtGui as QtGui

./draftguitools/gui_grid.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./importSVG.py
67:    from PySide import QtWidgets

./draftguitools/gui_circles.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_styles.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_upgrade.py
36:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_rectangle.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_join.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_base_original.py
37:from PySide import QtCore

./CMakeLists.txt
4:    PYSIDE_WRAP_RC(Draft_QRC_SRCS Resources/Draft.qrc)

./draftguitools/gui_selectplane.py
29:from PySide import QtGui
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_snapper.py
42:import PySide.QtCore as QtCore
43:import PySide.QtGui as QtGui
44:import PySide.QtWidgets as QtWidgets

./draftguitools/gui_rotate.py
33:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_setstyle.py
32:from PySide import QtCore
33:from PySide import QtGui
34:from PySide import QtWidgets
78:        self.form = Gui.PySideUic.loadUi(":/ui/TaskPanel_SetStyle.ui")

./draftguitools/gui_edit.py
37:import PySide.QtCore as QtCore
38:import PySide.QtWidgets as QtWidgets
342:        from PySide import QtCore

./draftguitools/gui_layers.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP
51:    from PySide import QtCore,QtGui
101:        from PySide import QtCore, QtGui, QtWidgets
107:        self.dialog = Gui.PySideUic.loadUi(":/ui/dialogLayers.ui")
305:        from PySide import QtCore, QtGui
389:        from PySide import QtCore
406:        from PySide import QtCore
419:    from PySide import QtCore, QtGui, QtWidgets

./draftviewproviders/view_wire.py
35:import PySide.QtCore as QtCore
36:import PySide.QtGui as QtGui
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_dimensions.py
40:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_lines.py
36:from PySide.QtCore import QT_TRANSLATE_NOOP

./importDXF.py
80:    from PySide import QtWidgets

./draftguitools/gui_draft2sketch.py
38:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_rectangles.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_stretch.py
38:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_facebinders.py
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_hatch.py
60:        from PySide import QtCore,QtGui
64:        self.form = FreeCADGui.PySideUic.loadUi(":/ui/dialogHatch.ui")

./draftviewproviders/view_text.py
34:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_beziers.py
38:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_patharray.py
39:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_ellipses.py
33:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_hyperlink.py
39:    from PySide.QtCore import QUrl
40:    from PySide.QtGui import QDesktopServices
45:from PySide import QtWidgets

./draftguitools/gui_trimex.py
41:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_scale.py
39:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_polararray.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_dimension.py
39:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_clone.py
44:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_shape2dview.py
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_lineslope.py
36:import PySide.QtWidgets as QtWidgets
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_fillets.py
36:import PySide.QtCore as QtCore
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_dimension_ops.py
36:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_layer.py
33:import PySide.QtCore as QtCore
34:import PySide.QtGui as QtGui
35:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_pathtwistedarray.py
34:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_snaps.py
33:from PySide import QtGui
34:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_wpproxy.py
31:import PySide.QtCore as QtCore
32:import PySide.QtGui as QtGui
33:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_base.py
33:import PySide.QtCore as QtCore
34:import PySide.QtGui as QtGui
35:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_offset.py
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftviewproviders/view_label.py
36:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftguitools/gui_groups.py
37:import PySide.QtCore as QtCore
38:from PySide.QtCore import QT_TRANSLATE_NOOP
39:from PySide import QtWidgets

./draftobjects/clone.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/dimension.py
104:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/array.py
37:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/wpproxy.py
32:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/block.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/circle.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/shapestring.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/ellipse.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/facebinder.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/label.py
33:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/fillet.py
28:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/shape2dview.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/draftlink.py
38:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/wire.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/polygon.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/layer.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/bspline.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/rectangle.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/bezcurve.py
30:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/text.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/point.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP

./draftobjects/pointarray.py
31:from PySide.QtCore import QT_TRANSLATE_NOOP
```

**Comment by chennes** [comment]
FreeCAD provides a wrapper called `PySide` which, when imported, correctly imports either PySide6 or PySide2 depending on which version of Qt FreeCAD was compiled against. It also provides some other wrapping functions to help mod developers write code that works with both Qt5 and Qt6.

**Comment by ipatch** [comment]
> FreeCAD provides a wrapper called `PySide` which, when imported, correctly imports either PySide6 or PySide2 depending on which version of Qt FreeCAD was compiled against. It also provides some other wrapping functions to help mod developers write code that works with both Qt5 and Qt6.

okay if that's the case then looking at the install structure / layout, should the local `PySide` be accessible via the python interpreter?

```
╰─λ cd MacOS/                                                                                                                                                       0 (0.015s)
╭─chris ssh Chriss-Mac-mini in /Users/chris/.local/fc-git/MacOS
╰─λ l                                                                                                                                                               0 (0.013s)
total 680
drwxrwxr-x   5 chris  staff   160B Aug  2 14:21 ./
drwxrwxr-x   8 chris  staff   256B Aug  2 14:21 ../
-rwxr-xr-x   1 chris  staff   194K Aug  2 14:17 FreeCAD*
-rwxr-xr-x   1 chris  staff   142K Aug  2 14:17 FreeCADCmd*
drwxr-xr-x  11 chris  staff   352B Aug  2 14:21 PySide/
╭─chris ssh Chriss-Mac-mini in /Users/chris/.local/fc-git/MacOS
╰─λ tree PySide/                                                                                                                                                    0 (0.014s)
PySide/
├── QtCore.py
├── QtGui.py
├── QtNetwork.py
├── QtSvg.py
├── QtSvgWidgets.py
├── QtUiTools.py
├── QtWebEngineWidgets.py
├── QtWidgets.py
└── __init__.py

1 directory, 9 files
```

**Comment by luzpaz** [comment]
Related:  
* #16047

**Comment by luzpaz** [comment]
Should we keep this ticket open ?

**Comment by chennes** [comment]
IMO no, it should be migrated to individual issues that need addressing: in bulk, FreeCAD works fine with Qt6 (I use it every day!). The catch-all is no longer necessary.
