### ISSUE TITLE
[Bug] 3mf created with FreeCAD cannot be loaded with PrusaSlicer

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#7018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=63095

### Version

0.20 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 18.04.6 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.29165 (Git)
Build type: Debug
Branch: master
Hash: c0cccf7f7ea87663cca813c147f81380c87e6969
Python 3.6.9, Qt 5.9.5, Coin 4.0.0a, Vtk 7.1.1, OCC 7.3.0
Locale: German/Germany (de_DE)
[/code]
```

### Issue description

PrusaSlicer or Fusion 360 cannot load an 3mf file created with FreeCAD. However, Blender is able to load it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
PR: https://github.com/FreeCAD/FreeCAD/pull/7023

**Comment by chennes** [comment]
Do we want to backport this for 0.20.1?

**Comment by luzpaz** [comment]
It makes sense to.
