### ISSUE TITLE
[Feature Request] FEM: Adjust constraint indicators to the size of the model

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#7030]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=18&t=69445

### Subproject(s) affected?

FEM

### Idea description

For very small models a hard-coded size of the constraint indicators causes the problem that in the view they appear as huge object and cover the model. This makes the further handling very difficult.

What's needed is a way to make the size of the indicators depending on the size of the model.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NXTler** [comment]
I want this feature too

**Comment by luzpaz** [comment]
@FEA-eng is this on the FEM roadmap ?

**Comment by FEA-eng** [comment]
> @FEA-eng is this on the FEM roadmap ?

No, because solving this one should be sufficient: https://github.com/FreeCAD/FreeCAD/issues/11306

There is some size dependence already but it's not working properly and we need a functional Scale property for those symbols.
