### ISSUE TITLE
[Bug]how to compile and install freecad on centos？

### ISSUE THREAD

**Issue by lindow2009** [FreeCAD/FreeCAD#7033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?f=4&t=55984&p=481597&hilit=centOS&sid=eb7bd2b42f63cec78a57033926d3e9d2#p481597

### Version

0.19 (Release)

### Full version info

```shell
environment：centOS 7
python3
freecad 0.19
```

### Issue description

how to compile and install freecad on centos？

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Why was a ticket opened? 
Is there a patch being submitted? Are you wanting wiki documentation?
