### ISSUE TITLE
[Wiki Documentation] Add link

### ISSUE THREAD

**Issue by yashpalgoyal1304** [FreeCAD/FreeCAD#7040]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

No

### Subproject(s) affected?

Other (specify in description)

### Idea description

The link to [Plot Workbench wiki page](https://wiki.freecadweb.org/Plot_Workbench) should be given in the release notes: https://wiki.freecad.org/Release_notes_0.20#Plot

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Done in https://wiki.freecad.org/Release_notes_0.20#Plot  
Closing
