### ISSUE TITLE
[Problem] PartDesign: Attachment of (sub-object) shapebinder co-modifies wrong field

### ISSUE THREAD

**Issue by quiret** [FreeCAD/FreeCAD#7052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=69542

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.2
Locale: English/Germany (en_DE)
```

### Issue description

[![Issue 7052](https://img.youtube.com/vi/gWf-_U64IMo/hqdefault.jpg)](https://youtu.be/gWf-_U64IMo)

When I attach a shape binder which has a selection of geometry using the Data tab of the Combo View then the selection set gets overwritten along with the attachment Support.

### Anything else?

As noted by @Roy-043 in the forum thread:

> Confirmed. What you are doing was obviously never considered by the developers. The [Part_EditAttachment](https://wiki.freecad.org/Part_EditAttachment) command tries to add a new property "Support", and because shapebinders already have a property with that name this results in a conflict.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
@realthunder , can you please have a look at this?

**Comment by quiret** [comment]
Please note this aswell: https://forum.freecadweb.org/viewtopic.php?p=604704#p604704

**Comment by jcoalson** [comment]
I added a simple example to reproduce here: https://forum.freecad.org/viewtopic.php?p=741301#p741301

Everything appears to work until the project is saved.

**Comment by jcoalson** [comment]
Another discussion: https://forum.freecad.org/viewtopic.php?t=76445
