### ISSUE TITLE
[Bug] Menu Bar stay behind Title Bar

### ISSUE THREAD

**Issue by AirJoeZ32** [FreeCAD/FreeCAD#7060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

Menu bar stay behind title bar. When I point the function icons by mouse, they are all position are shifted

### Version

0.20 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.2
Locale: English/United States (en_US)
```

### Issue description

![image](https://user-images.githubusercontent.com/4140247/174656883-615dbfba-9391-4255-8fa5-7adc244ee091.png)
https://www.dropbox.com/s/w5utr83l40pugz3/Screenshot.jpg?dl=0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
Please open a forum discussion. Nobody else reported this bug so most probably it is a wrong setting on your PC and people in the forum can help you.
