### ISSUE TITLE
[Bug] TechDraw does not work with SVG parameter `dominant-baseline`

### ISSUE THREAD

**Issue by tobiasfalk** [FreeCAD/FreeCAD#7076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=69691

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: openSUSE Leap 15.3 (KDE//usr/share/xsessions/plasma5)
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20)
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: German/Germany (de_DE)
[/code]
```

### Subproject(s) affected?

Techdraw

### Issue description

If you create a template and use the parameter dominant-baseline for setting the text position point in to the middle height for example, the TechDraw viewer does not render it properly. It is trivial if you use it as a SVG parameter or as a Style parameter.
`dominant-baseline="middle"`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Qt only supports Svg Tiny.  dominant-baseline is not available in Svg Tiny.
