### ISSUE TITLE
[Bug] <0.0: Error : Gmsh requires OpenCASCADE to import shape >

### ISSUE THREAD

**Issue by Gogikok** [FreeCAD/FreeCAD#7077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewforum.php?f=18&sid=3e3f1fa80432757c2f020890851296f3

### Version

0.20 (Release)

### Full version info

```shell
Vrersion 0.20
Revisionsnummer 29192 (Git)
Utgivningsdatum 2022/06/18 18:34:28
Opperativsystem Ubuntu Core 20
Ordstolek 64-bit
Branch master
Hash fb1a7af
```

### Subproject(s) affected?

FEM

### Issue description

I have Open Cascade in my computer.
But FreeCAD does not seem to find them.
So I can not do any calculations at all.

```shell
$ locate opencascade
/ snap / freecad / 74 / usr / include / opencascade
---------------------------------------
-------------------------------------------------
0.0: We are going to start ...
0.0: Start Gmsh ...
0.0: Gmsh had warnings ...
0.0: Error : Gmsh requires OpenCASCADE to import shape 
0.0: Gmsh done!
---------------------------------------------------
````

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Closing. Please open a forum thread first.
