### ISSUE TITLE
[Bug] sheetmetal workbench overrides part transparency and colour

### ISSUE THREAD

**Issue by thegavs** [FreeCAD/FreeCAD#7085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=69726

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Linux Mint 20 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20)
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: English/United Kingdom (en_GB)
[/code]
```

### Subproject(s) affected?

PartDesign

### Issue description

Any action in sheet metal workbench overrides the transparency and colour set in the part.

To replicate create a flat part in part design workbench and set the transparency to a high value I used 80%
then swap to sheet metal workbench and add a bend to a face.
The transparency setting seems then to be ignored but not reset. changing the value will bring the transparency back.

### Anything else?

![bent showing data](https://user-images.githubusercontent.com/32636046/175533283-cf02bf70-abe4-4c03-b959-027f3659c889.png)
![bent not transpartent](https://user-images.githubusercontent.com/32636046/175533292-f6043433-20b0-403e-9281-c20a3bf32da2.png)
![unbent transparent](https://user-images.githubusercontent.com/32636046/175533296-bd2f4c8a-e515-4191-b161-f4ac29a0c1b2.png)
[sheetmetal transparency.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/8976081/sheetmetal.transparency.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Related https://github.com/shaise/FreeCAD_SheetMetal/issues/206

**Comment by luzpaz** [comment]
Hi @Syres916,  can we close this ticket then ?

**Comment by Syres916** [comment]
If @thegavs is happy that individual face colours will have to wait until after TopoNaming is sorted then yes but I was giving a little time for feedback, it's holiday time in the northern hemisphere after all.

**Comment by thegavs** [comment]
am happy with that as there is an easy workaround for the time being.

thank you

**Comment by Syres916** [comment]
> Hi @Syres916, can we close this ticket then ?

@luzpaz This can now be closed, TIA
