### ISSUE TITLE
[Feature Request] Parametric projection 

### ISSUE THREAD

**Issue by CsatiZoltan** [FreeCAD/FreeCAD#7086]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=22&t=69732

### Subproject(s) affected?

Part

### Idea description

Projecting a curve onto a surface is available in the `Part` workbench of FreeCAD. However, it is not exposed to the Python API. Therefore, I rely on *PythonOCC* to use the underlying projection implemented in *OpenCASCADE*, see the [documentation](https://dev.opencascade.org/doc/refman/html/class_b_rep_proj___projection.html). The Python code can be found [here](https://gist.github.com/CsatiZoltan/f4fd10bf20923143ba0e0678ea1d3d61).
First, import the following:
```python
import Part
from OCC.Core.BRepProj import BRepProj_Projection
from OCC.Core.gp import gp_Dir
```

This worked well, until PythonOCC was removed from FreeCAD. Possible solutions:
- integrate my solution into FreeCAD so that PythonOCC is not needed any more for this functionality
- bundle PythonOCC with (the conda-packaged) FreeCAD

### Anything else?

Related forum entry: https://forum.freecadweb.org/viewtopic.php?f=9&t=33700&start=20#p529942

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
So, IOW, you're asking to expose OCC's  `BRepProj_Projection` class to FC's Python API ?

**Comment by CsatiZoltan** [comment]
@luzpaz Yes.

**Comment by luzpaz** [comment]
@wwmayer do you mind weighing-in ? TIA!

**Comment by wwmayer** [comment]
BRepProj_Projection is already available in our Python API. The methods are part of Part.Shape and they are called `makeParallelProjection` and `makePerspectiveProjection`

**Comment by CsatiZoltan** [comment]
@wwmayer Thanks, I did not know about this method.
https://github.com/FreeCAD/FreeCAD/blob/93525ff7eb28418e0237b0a866f797c74adfa569/src/Mod/Part/App/TopoShapePyImp.cpp#L2018

This solves my issue, so I close it. If you want to introduce the parametric projection into FreeCAD, feel free to use the referenced code.

**Comment by luzpaz** [comment]
@CsatiZoltan where in the documentation would you say this would be helpful for others to find?

**Comment by CsatiZoltan** [comment]
@luzpaz I would place a link at the end of the [wiki page](https://wiki.freecadweb.org/Part_ProjectionOnSurface), mentioning when my custom class is useful (written in the *Notes* section of the class docstring). I will modify that GitHub Gist to use `makeParallelProjection` instead of the PythonOCC function, making it compatible with FreeCAD 0.20.

**Comment by luzpaz** [comment]
@CsatiZoltan would you like access to the wiki to add it yourself?

**Comment by CsatiZoltan** [comment]
@luzpaz Yes, please. That would allow me to start contributing to FreeCAD.

**Comment by luzpaz** [comment]
You can [DM me](https://forum.freecad.org/ucp.php?i=pm&mode=compose&u=12229) a valid email address

**Comment by CsatiZoltan** [comment]
Added to the wiki.
