### ISSUE TITLE
Custom Toolbar Crash

### ISSUE THREAD

**Issue by Xalex74** [FreeCAD/FreeCAD#7095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

//

### Version

0.20 (Release)

### Full version info

```shell
//
```

### Subproject(s) affected?

Addon Manager

### Issue description

Whenever I try to create a custom toolbar, it appears blank after reboot

### Anything else?

![Error](https://user-images.githubusercontent.com/108174856/175766136-7845ffde-af88-4f19-aa8e-e4f2d563eba2.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
As the bug submission form stated, please report issues in the forum first. In most cases people there can help you. Only when people agree it is a bug in FreeCAD open an issue.
