### ISSUE TITLE
[Bug] "Please delete and recreate the job" (triggered by locale switching?)

### ISSUE THREAD

**Issue by 103131** [FreeCAD/FreeCAD#7164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=15&t=70083

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 20.04.4 LTS (XFCE/ubuntustudio)
Word size of FreeCAD: 64-bit
Version: 0.21.29393 (Git) AppImage
Build type: Release
Branch: master
Hash: 6820e0a9ec85203a6f342ca72a2ff8fd417beaf1
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: French/France (fr_FR)
Installed mods: 
  * Help 1.0.0-alpha
[/code]
```

### Subproject(s) affected?

Path

### Issue description

I created a simple cylinder in Blender which I transformed into a solid in Freecad. When I go to the path workbench and want to create a job on this solid, I get the message: "The Job was created without fixture support. Please delete and recreate the job".
I tried by using a cylinder created directly in Freecad, and it's the same.
A user gave me a hint to solve this issue. That's to say that I put the interface in French and when I switched it back to English, I no longer had this error message.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sliptonic** [comment]
https://github.com/FreeCAD/FreeCAD/pull/7178
