### ISSUE TITLE
Panel Buttons Thread Size missing

### ISSUE THREAD

**Issue by CJUGroenewald** [FreeCAD/FreeCAD#7170]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

M12x0.75 Panel Buttons Thread Size

### Subproject(s) affected?

Addon Manager

### Idea description

Hi Guys,
Panel buttons have tread size of M12x0.75 fine thread.
Can that be added to the Hole Parameters Please under Part Design please? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Invalid ticket. Please open a forum thread, follow [guidelines](https://forum.freecad.org/viewtopic.php?f=3&t=2264), add screenshots of what you're talking about. 

Closing ticket
