### ISSUE TITLE
[Feature Request] Adaptive sketcher grid

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#7223]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=611312#p611312

### Subproject(s) affected?

Part

### Idea description

Currently the grid size of a sketch is hard-coded and the number of lines depends on the size of the sketch. The disadvantage is that if the sketch is fairly big but the grid size very small there will be many thousand of lines that slows down the rendering. And if additionally the 3D view is zoomed out then the grid will become useless as it's not possible any more to see the individual lines.

Now the idea is to have an adaptive grid that doesn't depend on the sketch size but on the screen size. If the user zooms in then the grid is recreated if the rendered width of a grid cell has doubled its size. And if the user zooms out the grid is recreated if the cell has halved its size.

This way the user could arbitrarily zoom in or out and will always have a sensible grid.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
+1000 and to add to the request it would be nice if the grid step adapted to be multiples of the chosen unit of measure, I've recently seen someone asking for this on the forum too.
As a bonus it would be nice if the grid was implemented as a general feature not necessarily sketcher specific, this way the same adaptive grid could be used in Draft WB and whoever else needs it.

**Comment by PaddleStroke** [comment]
I think this can be closed
