### ISSUE TITLE
[Feature Request] TechDraw: Calculate Area of Arbitrary Faces

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FreeCAD#7317]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://www.forum.freecadweb.org/viewtopic.php?f=3&t=70824

### Subproject(s) affected?

Techdraw

### Idea description

From ticket:  
>> When trying to calculate an area I get the following error.
>> `<Exception> CmdTechDrawAreaAnnotation - forbidden border element found`

> Faces with curved edges are not supported: [TechDraw ExtensionAreaAnnotation](https://wiki.freecad.org/TechDraw%20ExtensionAreaAnnotation) and in your case there are such edges (doors).

Issue: ExtensionAreaAnnotation currently is limited to polygonal faces.  The ability to calculate areas for arbitrary faces is available in OCC.  

- [ ] ExtensionAreaAnnotation should be able to accept an arbitrary face (or list of faces).
- [ ] It should also have an option to calculate the area of a bounding rectangle to handle situations where the selected faces contain voids.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Looks like this is where it is in the code: 

https://github.com/FreeCAD/FreeCAD/blob/f741d28b43b93a08ac2f3700e0df2e831b873576/src/Mod/TechDraw/Gui/CommandExtensionPack.cpp#L1812-L1820

**Comment by WandererFan** [comment]
GProp_GProps gprops;
BRepGProp::SurfaceProperties(face, gprops);
double area = gprops.Mass();

**Comment by luzpaz** [comment]
@pavltom if this is of interest to you, would you like to take a swing at it ?
