### ISSUE TITLE
[Bug] Icon "edit-cut.svg" is licensed CC-BY-SA-NC-2.0, which is a problem for Debian

### ISSUE THREAD

**Issue by coldtobi** [FreeCAD/FreeCAD#7347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

n/a

### Version

0.20 (Release)

### Full version info

```shell
n/a
The files have been added a decade ago, so any version in Debian is affected.
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

I'm currently working on updating the Debian FreeCAD packaging, to fix all (for Debian) release critical bugs and get FreeCAD back on track for the next Debian release.

 During that, lintian, a Debian QA tool pointed me out that two files are licenses with an non-[DFSG](https://www.debian.org/social_contract#guidelines) license. (It's findings are [here](https://udd.debian.org/lintian/?packages=freecad))

The file is (both are identical copies)
```
./src/Gui/Icons/edit-cut.svg
./src/Mod/TechDraw/Gui/Resources/icons/MRTE/edit-cut.svg
```

According to the embedded meta-data the license is CC-BY-SA-*NC*-2.0 -- the NC being problematic. (CC versions 2.0 are also disputed to be DFSG compatible, but the NC is clearly not compliant) 

I did a bit of research, and it seems that the tango icon library has a relicenses version, under Public Domain, so replacing this files by the tango version would solve this issue.

If the resolution to use the Tango "edit-cut.svg" is OK for you, I can provide a PR. Comparing the two icons. I think they are identical.

### Anything else?

Lintian: https://udd.debian.org/lintian/?packages=freecad
Tango Icons: http://tango.freedesktop.org/Tango_Icon_Library

Comparing the two icons: on the left, the one from FreeCAD, on the right the one from Tango. (They look identical to me.)
![icons](https://user-images.githubusercontent.com/3774790/183856690-d2a2637b-8cad-4655-9014-c572fc118ff6.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
A PR would be great, thanks!
