### ISSUE TITLE
[Bug] [FEM] CalculiX `write_constraint_temperature.py` outputs incorrect file name format

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#7360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=617376#p617376

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

FEM

### Issue description

Error: `FEM: No frd result file found at ...` due to:

>The input is split to few files and Calculix searches for:
`FEMMeshGmsh_constraintstemperaturenodesets.inp`
but this file written by FC contains spaces in the name:
`FEMMeshGmsh_constraints temperature node sets.inp`
When I deleted spaces manually, ccx runs well.

### Anything else?

Fix is pending

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
Thanks. Merged and backported, for more see the FEM forum.
