### ISSUE TITLE
[Bug] Arch Wall not visible when base sketch lines overlap

### ISSUE THREAD

**Issue by eshattow** [FreeCAD/FreeCAD#7370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=23&t=71107
https://forum.freecadweb.org/viewtopic.php?f=23&t=67107

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Debian GNU/Linux bookworm/sid (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.30058 (Git) AppImage
Build type: Release
Branch: master
Hash: cb96332a64db8ae855ca700212eebb0f5151230a
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * BIM 2021.12.0
  * parts_library
[/code]
```

### Subproject(s) affected?

Arch

### Issue description

Create sketch, apply Wall. Edit sketch and overlap a new line within one of the existing lines. In the view your wall is not visible anymore. This seems broken, overlapping lines should get merged not cause a failure of the wall to be visible.

### Anything else?

![FCArchWallsOverlapBug-2view](https://user-images.githubusercontent.com/12215438/184627046-d7cf2044-ee15-4034-bec3-97c64ba39447.png)
![FCArchWallsOverlapBug-2sketch](https://user-images.githubusercontent.com/12215438/184627049-1dce789d-1e32-4277-9808-00bc1955335a.png)
![FCArchWallsOverlapBug-1view](https://user-images.githubusercontent.com/12215438/184627051-77c938e8-0074-4580-9e9f-20a53cd96685.png)
![FCArchWallsOverlapBug-1sketch](https://user-images.githubusercontent.com/12215438/184627061-fc81da2d-5140-4b39-8095-0ffd083ad09d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
Is the bug also in FreeCAD 0.20? @Roy-043

**Comment by Roy-043** [comment]
See comment here: #7436
