### ISSUE TITLE
[Bug] Link to TechDraw template is lost when a document is resaved

### ISSUE THREAD

**Issue by benj5378** [FreeCAD/FreeCAD#7376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=71184

### Version

0.21 (Development)

### Full version info

```shell
OS: Ubuntu 22.04.1 LTS (Unity/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.30119 (Git)
Build type: Unknown
Branch: inheritance3
Hash: 8b056f156fd087b3df36a5223fc5ca6900649a83
Python 3.10.4, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.2
Locale: English/United States (en_US)
```

### Issue description

The link to the TechDraw template is lost when doing "Save as" after the file has already been saved. The issue is confirmed on both MacOS and Ubuntu. Steps to reproduce:
1) Create a new Document in FreeCAD
2) Add a new TechDraw page in the TechDraw workbench
3) Save the document in a location
4) Close the document internally (close the tabs but keep the same FreeCAD window open)
5) Reopen the same document
6) Save the document by "Save as" with a new filename
7) Make a change in the template field (eg. date) and recompute it
The connection to the template should now be lost

Reported by the bughunter @wolflu05 

Video for lazy purposes: https://youtu.be/tWtotlsUQZM (credits once again to @wolflu05)

### Anything else?

Video for lazy purposes: https://youtu.be/tWtotlsUQZM (credits once again to @wolflu05)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
this was fixed by PR #7714
