### ISSUE TITLE
[Feature Request] Include thumbnail when exporting as .3mf

### ISSUE THREAD

**Issue by mfraser** [FreeCAD/FreeCAD#7414]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=63095&p=621747

### Idea description

The KDE-Extras package in all KDE based operating systems can now use a thumbnail saved inside .3mf files as the file icon. .3mf files exported from FreeCAD currently don't have embedded thumbnails.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
Added with 086ce2d34
