### ISSUE TITLE
[Feature Request] Please add exported file to "recent files" 

### ISSUE THREAD

**Issue by AndKe** [FreeCAD/FreeCAD#7451]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=71675

### Subproject(s) affected?

Other (specify in description)

### Idea description

Let's say I export a 3mf file.
The next, very likely thing would be to open it in another tool.

It would be nice that the recently exported file shows up in "recent" file list (of file manager) - but it does not.
(Tested on Ubuntu)

### Anything else?

[code]
OS: Ubuntu 22.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20.1)
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
[/code]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onekk** [comment]
I think that for Linux this link should be of some help.

https://specifications.freedesktop.org/recent-file-spec/recent-file-spec-latest.html

**Comment by luzpaz** [comment]
Directly contradicts #6076

**Comment by Roy-043** [comment]
As mentioned in #6076 there are hidden preferences for this.
Wiki documentation: https://wiki.freecadweb.org/Fine-tuning

**Comment by luzpaz** [comment]
How do we inform end-users of fine-tuning preferences?

**Comment by Roy-043** [comment]
I'll add a note to the [Preferences Editor](https://wiki.freecad.org/Preferences_Editor) page.
