### ISSUE TITLE
[Bug] Toolbars visually distorted on Fedora 35

### ISSUE THREAD

**Issue by tkontogi** [FreeCAD/FreeCAD#7458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=71721

### Version

0.20 (Release)

freecad-0.20.1-1.fc35.x86_64

### Full version info

```shell
[code]
OS: Fedora Linux 35 (Thirty Five) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.21.Unknown
Build type: Unknown
Python 3.10.5, Qt 5.15.2, Coin 4.0.0, Vtk 9.0.3, OCC 7.5.0
Locale: English/United States (en_US)
Installed mods: 
  * 3D_Printing_Tools
  * CurvedShapes 1.0.4
  * WebTools
  * Rocket 2.7.1
  * CADExchanger
  * slic3r-tools
[/code]
```

### Issue description

All tool bars are visually distorted and the look and feel also looks broken.

Please review attached images (from the Sketcher, but the same look and feel appears to all toolbox toolbars).

![Selection_972](https://user-images.githubusercontent.com/15005048/188883267-55e80fbe-7c0d-4cad-8087-5f41506c98da.png)
![Selection_973](https://user-images.githubusercontent.com/15005048/188883347-dc71064b-39e1-4903-ab4f-f6cb6e6e261e.png)
![Selection_974](https://user-images.githubusercontent.com/15005048/188883835-b1235238-478e-44cc-90d0-d64aeb67877e.png)

### Anything else?

100% reproducible
Log:

 ```
 [tkonto@tweety-lap tmp]$ tail -f freecad.log 
Log: Init: Entering event loop
Log: Init: Executing event loop...
Log: Init: Processing command line files
Log: Loading Sketcher module... done
Log: Loading GUI of Part module... done
Log: Loading GUI of Sketcher module... done
Log: Loading PartDesign module... done
Log: Loading GUI of PartDesign module... done
Log: Sketcher::setUpSketch()-T:0
Log: Sketcher::Solve()-DogLeg-T:0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Forum thread? (the one above is unrelated)

**Comment by tkontogi** [comment]
Thank you.
Posted in the forum.
Updated this case with forum URL.

Appreciated.

**Comment by tkontogi** [comment]
Issue related to DPI value, configurable in xfce4-appearence-settings --> Fonts

In my case the value was set to 95.
Setting it back to 96 solved the issue.

Solution provided in:  [https://forum.freecadweb.org/viewtopic.php?p=624718#p624718](url)


Thank you.


![Selection_980](https://user-images.githubusercontent.com/15005048/189186981-4dc3a27e-5b6f-4cfb-bf11-b03010739510.png)

**Comment by luzpaz** [comment]
Thanks for the follow-up. Closing!
