### ISSUE TITLE
[Bug] Menu bar

### ISSUE THREAD

**Issue by 1959didier** [FreeCAD/FreeCAD#7464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/

### Version

0.20 (Release)

### Full version info

```shell
The menu bar is half displayed on my Samsung 27" screen, version 0.20 and 0.21 of Freecad
```

### Issue description

Displaying the menus.

### Anything else?

![image](https://user-images.githubusercontent.com/23725988/189306234-6707c00c-3f40-43ae-a9fd-31b6ce8275e3.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Thank you for the impulse to make a bug report. But our guidelines ask to first open a forum thread. This may be a DPI issue, see #7458

**Comment by adrianinsaval** [comment]
full version information please, if OP does not follow up this issue should be closed.

**Comment by luzpaz** [comment]
No response. Closing
