### ISSUE TITLE
[Bug] Leader Line Auto Horizontal -setting

### ISSUE THREAD

**Issue by kemes** [FreeCAD/FreeCAD#7465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=71751

### Version

0.21 (Development)

### Full version info

```shell
OS: Ubuntu 20.04.5 LTS (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20.1)
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Techdraw

### Issue description

Eventhough the (Preferences > Techdraw > Annotation) "Leader Line Auto Horizontal" preference is unchecked, the property Auto Horizontal of the Leader lines are set to True by default. It seems like the checkbox value in the preferences does not make a difference.

### Anything else?

![image](https://user-images.githubusercontent.com/22754180/189314422-0d6a0a0c-c9df-4a67-903b-8a2631b3aee3.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Fixed by @WandererFan in e28317f772
