### ISSUE TITLE
[Feature Request] TechDraw: Add `Use template` property in page properties

### ISSUE THREAD

**Issue by kemes** [FreeCAD/FreeCAD#7466]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=71735

### Idea description

For example when designing sheet metal parts there is a need to create a simple outline drawing of the part which will be cut. In this case I always use a blank template. Would be handy if the Template property section had a property `Use template` which could be used to enable/disable the template. In the case of false the page would be blank and dimensioned according to the dimensions in the Page Properties -section.

### Anything else?

![image](https://user-images.githubusercontent.com/22754180/189315360-c8e8ad7f-9a89-4875-bd3d-8765e5f65368.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
There are blank page templates for a number of common page sizes.   This is a much bigger change than just adding a property.

I don't plan on implementing this.
