### ISSUE TITLE
[Bug] [MSVC] FreeCAD failed to build with error C2036 on MSVC

### ISSUE THREAD

**Issue by fangzhouxia** [FreeCAD/FreeCAD#7486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=4&t=71889

### Version

0.21 (Development)

### Full version info

```shell
N/A
```

### Issue description

Hi all,
FreeCAD fails to build on MSVC due to error C2036. Could you help look?
**Error message**
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\vector(1946,1): error C2036: 'TechDraw::LineSet *': unknown size (compiling source file F:\gitP\FreeCAD\FreeCAD\src\Mod\TechDraw\App\AppTechDraw.cpp) [F:\gitP\FreeCAD\FreeCAD\build_amd64\src\Mod\TechDraw\App\TechDraw.vcxproj]
**Repro steps**
1. open VS2019 x64 tools command
2. git clone https://github.com/FreeCAD/FreeCAD.git F:\gitP\FreeCAD\FreeCAD
3. download [https://github.com/apeltauer/FreeCAD/re ... ack_12.5.2](https://github.com/apeltauer/FreeCAD/releases/tag/LibPack_12.5.2) F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17
4. mkdir F:\gitP\FreeCAD\FreeCAD\build_amd64 && cd F:\gitP\FreeCAD\FreeCAD\build_amd64
5. set _CL_= /permissive- or set _CL_= /std:c++latest
6. set PATH=F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\bin;%PATH%
7. set PATH=F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\bin\Scripts;%PATH%
8. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DFREECAD_LIBPACK_DIR=F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17 -DBUILD_FEM_NETGEN=OFF -DFREECAD_RELEASE_PDB=OFF -DFREECAD_RELEASE_SEH=OFF -DCMAKE_BUILD_TYPE=Release.
9. msbuild /m /p:Platform=x64 /p:Configuration=Release FreeCAD.sln /t:Rebuild
**Detailed log**
[build (5).log](https://github.com/FreeCAD/FreeCAD/files/9563230/build.5.log)
**Expected Behaviour**
build successfully.
**version info**
OS Version: windows server 2019
VS version: VS2019 (16.11.18)
the commit of FreeCAD we use is dcf2bc4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Werner has already fixed this - https://forum.freecadweb.org/viewtopic.php?p=626194#p626194

**Comment by luzpaz** [comment]
Specifically 8b4e114b9d

**Comment by fangzhouxia** [comment]
@WandererFan Hi, according to this - https://forum.freecadweb.org/viewtopic.php?p=626194#p626194 error C2036 has indeed been resolved. But a new problem appeared in the runtest stage, as follows. Do I need to re-issue this issue?
Traceback (most recent call last):
  File "F:\gitP\FreeCAD\FreeCAD\build_amd64\Mod\Part\TestPartApp.py", line 230, in testPlacement
    self.assertTrue(box.Placement.isSame(p2 * p1))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 974 tests in 66.711s

FAILED (failures=1)
			(25 %)	
						(33 %)	
						(41 %)	
						(50 %)	
						(58 %)	
						(66 %)	
						(75 %)	
						(83 %)	
						(91 %)	
						(100 %)

**Comment by WandererFan** [comment]
Doesn't look related to the other issue.  I would make a post about this in
the Install/Compile section of the forum.

**Comment by fangzhouxia** [comment]
Hi, @ WandererFan could you give me a link to the forum, I can't find it

**Comment by WandererFan** [comment]
https://www.forum.freecadweb.org/viewforum.php?f=4

**Comment by luzpaz** [comment]
Per wwmayer in the [thread](https://forum.freecadweb.org/viewtopic.php?p=626194#p626194): 
> Your version is too old. The issue has been fixed with [git commit 8b4e114b9d](http://github.com/FreeCAD/FreeCAD/commit/8b4e114b9d)
