### ISSUE TITLE
[Bug] Preferance Pack Save as duplicates entries in package.xml if duplicate name is specified.

### ISSUE THREAD

**Issue by macdroid53** [FreeCAD/FreeCAD#7499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=71580&start=20

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Debian GNU/Linux 11 (bullseye) (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.21.30378 (Git)
Build type: Release
Branch: master
Hash: 48aafc3f8b36ded8dc80fbf83ec608898ed16d4a
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.0.dev
Locale: English/United States (en_US)
Installed mods: 
  * kicadStepUpMod 10.15.1
  * ZolkoBase.backup1661627527.5180008
  * PrefExtras
  * Glass.backup1661627524.3866751
  * ZolkoBase.backup1661604597.4908574 0.0.1
  * lattice2.backup1661627525.6921222
  * ZolkoBase 0.0.1
  * DynamicData 2.46.0
  * fasteners 0.4.6
  * ExtremeProDark 1.0.4
  * ProDarkThemePreferencePack 1.0.0
  * fcgear 1.0.0
  * plugins
  * Pyramids-and-Polyhedrons
  * Defeaturing 1.2.0
  * ZolkoBase.backup1661623779.4314604
  * BasicMech.backup1661621506.8091254
  * Assembly4 0.12.4
  * ZolkoBase.backup1661625916.8140683
  * OpticsWorkbench 1.0.9
  * workfeature-macro
  * sheetmetal 0.2.57
  * A2plus 0.4.59
  * CurvedShapes 1.0.4
  * Dracula 0.0.2
  * Curves 0.5.8
  * workfeature
  * lattice2 1.0.0
[/code]
```

### Issue description

Side note: when Save new is used and an existing name is specified, there is an identical entry in package.xml for each time the the name is used.

(so if I do a Save as 5 times and specify the name ThePack, there are 5 copies of:

    <preferencepack>
      <name>ThePack</name>
      <version>1.0.0</version>
    </preferencepack>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Thanks for the report - this is now fixed, by dc2bf6c7546e2f079165ca5163a8dd76f4a3a64b.
