### ISSUE TITLE
part_cut

### ISSUE THREAD

**Issue by GustavoGirardelli** [FreeCAD/FreeCAD#7509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

a

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.1.29177 +233 (Git) Snap 245
Build type: Release
Branch: tag: 0.20.1
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: Spanish/Argentina (es_AR)
Installed mods: 
  * Help 1.0.3
[/code]
```

### Issue description

**Hello:
When I want to use part_cut I get an error "_Recompute failed! Please check report view._" and the entire panel is erased, it remains blank.
Thanks.**

Hola:
Cuando quiero usar part_cut me salta un error "Recompute failed! Please check report view." y se borra todo el panel, queda en blanco.
Gracias.

### Anything else?

a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
This is not a helpdesk. Direct your queries to the forum.freecadweb.org
