### ISSUE TITLE
[Bug] <Error Save AS>

### ISSUE THREAD

**Issue by Itacate** [FreeCAD/FreeCAD#7537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/

### Version

0.20 (Release)

### Full version info

```shell
FreeCad 0.20.1
Windows 11 

13:07:35  Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'Base.FreeCADError'>: <unknown exception data>
```

### Issue description

Ya sea un archivo nuevo o uno existente, Se Genera un error  al intentar salvar el archivo  //  The file is new o the file is Existen, An error occurs when trying to save the file

### Anything else?

![FreeCAD 0 20 1 29_9_2022 13_07_39](https://user-images.githubusercontent.com/108371415/193111281-83900800-74c4-4abf-b390-cb6e086a2143.png)
![FreeCAD 0 20 1 29_9_2022 13_08_06](https://user-images.githubusercontent.com/108371415/193111302-29dbc91f-77bc-4221-935f-9b09f8ab44d9.png)
![FreeCAD 0 20 1 29_9_2022 13_09_00](https://user-images.githubusercontent.com/108371415/193111312-653d7bfb-2b77-4859-905c-fc6ce1f5c0a1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
No example file given. No explanation on how to reproduce. No forum thread opened. No full About info. Closing ticket unless OP follows through. Then feel free to re-open.
