### ISSUE TITLE
[Feature Request] <title>plug-in unit

### ISSUE THREAD

**Issue by a937983423** [FreeCAD/FreeCAD#7545]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

Your plug-in design is too poor. Every time you go in, you have to refresh, and the refresh takes half a day. What's more, your plug-in design should not only consider the good aspects of your network, but also the bad aspects of our network

### Subproject(s) affected?

Addon Manager

### Idea description

Your plug-in design is too poor. Every time you go in, you have to refresh, and the refresh takes half a day. What's more, your plug-in design should not only consider the good aspects of your network, but also the bad aspects of our network

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
This is not a feature request. There is no forum thread. No mention of version number.
Closing.
