### ISSUE TITLE
[Bug] <title>Symmetry function (><) does not work properly, the center was not over the chosen line. Fixed when I dragged the center over the line, manually

### ISSUE THREAD

**Issue by SergioPappalardo** [FreeCAD/FreeCAD#7565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

I´m just reporting a failure to the FreeCAD team! 

### Version

0.20 (Release)

### Full version info

```shell
Symmetry function (><) does not work properly, the center was not over the chosen line. Fixed when I dragged the center over the line, manually later.
```

### Issue description

Symmetry function (><) does not work properly, the center was not over the chosen line. Fixed when I dragged the center over the line, manually later.

### Anything else?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Not the way to report as specified in the issue template. Open a ticket.
