### ISSUE TITLE
[Bug] <title> QCAD error

### ISSUE THREAD

**Issue by Bermulee** [FreeCAD/FreeCAD#7578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

I'm unable to open a DWG file or export to DWG.

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Core

### Issue description

The program will not open a DWG file or export from another file type to DWG. It comes up with a QCAD error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Please open a [forum thread](https://forum.freecadweb.org) first to discuss with community before opening a ticket. Re-open ticket once you do.
