### ISSUE TITLE
[Bug] Logo broken in README.md

### ISSUE THREAD

**Issue by HerrNamenlos123** [FreeCAD/FreeCAD#7595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

-

### Version

0.21 (Development)

### Full version info

```shell
-
```

### Issue description

Not a big deal, just wanted to bring up that the Logo in the main Readme is broken, on the main page of the repository (branch master & 0.20 release). It seems like the link is broken, something that could be easily fixed. Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmg-duarte** [comment]
From a quick history review, it seems as though it wasn't the link that changed, it just got invalidated somehow. As you said, it's easy to fix, just get a replacement 😅
