### ISSUE TITLE
[Problem] Users don't understand stylesheets vs preference packs

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD#7640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=72889&p=635896#p635896

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.30345 (Git)
Build type: Release
Branch: master
Hash: f42a47aa0fd8c4f34ef63c185d9f29b9b6e84737
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
  * Assembly3 0.11.3
  * Behave-Dark-Colors 0.1.1
  * BIM 2021.12.0 (Disabled)
  * Dracula 0.0.2
  * ExtremeProDark 2.3.2
  * ExtremeProDark.backup1665346471.659064 2.3.1 (Disabled)
  * ExtremeProLight 1.0.1
  * ExtremeProLight.backup1665559197.7999926
  * FeedsAndSpeeds 0.4.0
  * FEM_FrontISTR 0.1.0
  * IconThemes
  * lattice2 1.0.0
  * PieMenu 1.1.10
  * PieMenu.backup1664822562.2342157
  * ProDarkThemePreferencePack 1.0.0
  * scanObjects
  * SelectorToolbar
  * sheetmetal 0.2.58
  * SP_Startup
  * ToolbarStyle
[/code]
```

### Issue description

Ok so people get confused to when to use a style-sheet or when a preference pack.
Also the preference pack has colors that you would expect in the style-sheet. But who cares? (probably people who read this)
But as an end user you just want a good looking Freecad, and it all works like you expect.

Now the cool thing is, it all works very well already so the hard work is already done for 99%.

Now we only need to fine tune it a bit.
And my proposal is too rename "Preference packs" to "Theme's" and style-sheets too "Highlights".
We need to link the style-sheet to a preference pack since they work together. Like you can't use a light theme preference pack with a dark stylesheet that doesn't work.
It could look like this: 
![afbeelding](https://user-images.githubusercontent.com/29804962/197600437-898f608a-dac8-489f-9e57-8fd06743b80d.png)

Kinda is logical or not? This is how like every other program does it so why not we too?
That it works a bit differently behind the scene's is something we can fix overtime but end users won't be bothered by that.

### Anything else?

I just found out preference packs rebranded from theme's. Ah well Doesn't matter to much how it is called for me we just need to link the 2 together so we have a working system.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
![themes_UI](https://user-images.githubusercontent.com/36372335/197856851-d13af217-4df4-43bb-9738-5cbc63185b0b.png)
I suggest something like this for the UI instead, all themes are forced to be preference packs+stylesheets, for stylesheet designers we shall a provide a base preference pack for dark and light themes.
The full preference pack functionality can then be moved to another tab.

**Comment by chennes** [comment]
The checkbox "Apply associated preferences" is a little misleading, because applying preferences from a pack is a one-time application.

**Comment by adrianinsaval** [comment]
That's why I chose to use "apply" not "use", I can't think of a straightforward way of communicating that fact without overloading the UI with unnecessary stuff. I suggest explaining how this works on a tooltip for that checkbox.

**Comment by chennes** [comment]
Maybe a dropdown menu isn't quite right here: we could have a "Change theme..." button that opens a simple dialog with a dropdown menu, the checkbox, and an "Apply" button. Alternately, maybe there isn't really a need to have the checkbox at all: I don't know how users could make an informed decision about whether or not to check it.

**Comment by luzpaz** [comment]
@MisterMakerNL any opinion?

**Comment by luzpaz** [comment]
bump

**Comment by MisterMakerNL** [comment]
I think btw that someone just need to make a PR with a good proposal.
I would do that if I have the time. But I don't have so much time free.

**Comment by PaddleStroke** [comment]
Hey guys,
I have been thinking about this and came to this proposal :

- The preference pack cannot be rebranded 'Theme' because preference pack can be other things.

- Addons that are Themes specify it in the package.xml as @chennes suggested : 
```
  <content>
    <preferencepack>
      <name>ProDarkThemePack</name>
      <type>Theme</type>
      <description>ProDark stylesheet and Colour scheme</description>
      <version>1.0.0</version>
      <tag>stylesheet</tag>
      <tag>dark</tag>
      <tag>professional</tag>
      <file>ProDark.qss</file>
    </preferencepack>
  </content>
```

- The 'Preference packs' widget does NOT show the preference packs of type 'Theme'.

- The "StyleSheet" combobox is removed. Ther user doesn't care to be able to select a stylesheet, he wants to select a theme.
  
  - A "Theme" combobox replace the one we removed : This combobox shows all the preference packs of type 'Theme'. When the user select a theme it applies the preference pack.
  
  - If we want to enable further theme settings, such as 'secondary color' for example (cf dark-green, dark-blue...) Then we create a 'Theme' groupbox in the Preferences "Display/Colors". If there are a lot of settings we want to add, then we create a preference page Display/theme. Note the settings have to be cross-themes, they wouldn't be implemented by themes individually.

**Comment by chennes** [comment]
Makes sense to me.

**Comment by MisterMakerNL** [comment]
I like it too!

**Comment by adrianinsaval** [comment]
I think it can be frustrating if a theme overwrites the customisations you've made to the configurable colours, so it might be desirable to have some way of preventing or reverting this.

**Comment by PaddleStroke** [comment]
Ok I'm on it then.

**Comment by chennes** [comment]
> some way of preventing or reverting this.

Reverting exists, at any rate: every time you apply a preference pack a backup of your settings is taken, and you can roll the changes back from that.

**Comment by luzpaz** [comment]
What's left to do here ?

**Comment by PaddleStroke** [comment]
I think it can be closed
