### ISSUE TITLE
[Feature Request] Prevent losing selection when clicking empty space when Ctrl is pressed

### ISSUE THREAD

**Issue by pathfinder555** [FreeCAD/FreeCAD#7673]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=73056
https://forum.freecadweb.org/viewtopic.php?f=8&t=72435

### Subproject(s) affected?

Other (specify in description)

### Idea description

When selecting features in the main view, while keeping Ctrl pressed, accidentally clicking empty space instead of a feature shouldn't make you lose your selection.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Closed by https://github.com/FreeCAD/FreeCAD/pull/7699 -- thanks to @PaddleStroke for coding this up.
