### ISSUE TITLE
[Bug] Bug Reporting Template Requires Previous Forum Discussion

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FreeCAD#7687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://www.forum.freecadweb.org/viewtopic.php?p=638121#p638121

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.30767 +7 (Git)
Build type: debug
Branch: robustReferences
Hash: f8572af5db0b71007a8813cf10bf9480409ecbc0
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk , OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * QuickMeasure-main
  * A2plus.backup1662229165.818354
  * A2plus 0.4.56a
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

The bug reporting template indicates that all bug reports should be preceded by a forum discussion.  
CONTRIBUTING.md does not mention this requirement.   This is confusing. 

The bug reporting template should be revised to indicate that a forum discussion is not required, or the requirement for a preliminary forum discussion should be added to CONTRIBUTING.md.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
I've submitted PR #7696 that, if merged, resolves this by removing the forums requirement from the language on GitHub.
