### ISSUE TITLE
[Bug] No icon for macros in startpage

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD#7709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

none, thought this was going to be removed?

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Linux 5.15.76-1-lts (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.30829 (Git)
Build type: None
Branch: master
Hash: 92819be7fd267d3d951061963de8a543c063a57b
Python 3.10.8, Qt 5.15.7, Coin 4.0.1, Vtk 9.1.0, OCC 7.5.3
Locale: C/Default (C) [ OS: English/United Kingdom (en_GB) ]
Installed mods: 
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

unlike FCStd files macros are shown without an icon in the startpage:
![image](https://user-images.githubusercontent.com/36372335/200090888-8500c45d-c99b-44f8-af11-a20a6db06b76.png)

this doesn't look particularly good, it would be nice if it showed an icon for the FCMacro files as is done for the FCStd files that have no preview, perhaps
https://github.com/FreeCAD/FreeCAD/blob/master/src/Gui/Icons/MacroEditor.svg
![image](https://user-images.githubusercontent.com/36372335/200090648-7d75188b-8392-46c6-9bb5-a36fa122e0e5.png)

or
https://github.com/FreeCAD/FreeCAD/blob/master/src/Gui/Icons/freecad-doc.svg
![image](https://user-images.githubusercontent.com/36372335/200090638-8a147a87-c5f5-45fe-85b7-0682e132017a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
I think we should make it the 1st one macro editor icon.

**Comment by luzpaz** [comment]
ping @yorikvanhavre where is the code for this located ?

**Comment by yorikvanhavre** [comment]
Hah i had never seen this before :)
On my system it takes the system icon:
![image](https://user-images.githubusercontent.com/1136856/202418578-612e0ac8-4d83-443a-91ae-24b926cd65f8.png)
I think the problem here is that the code that provides a default icon seems weird: https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/StartPage/StartPage.py#L220

**Comment by chennes** [comment]
It would be easy enough to add another condition in the code just above that to specifically handle FCMacro files. We could even consider parsing their metadata (if present), the way we do with the FCStd files.

**Comment by adrianinsaval** [comment]
I'm on mobile now and this is just speculation but after thinking about it I suspect that my issue actually comes from using the
`BaseApp/Preferences/Bitmaps/Theme/ThemeSearchPaths` parameter to ignore the system icon theme, the icon theming system needs some rework IMO
