### ISSUE TITLE
PR #7428 got mangled during merge

### ISSUE THREAD

**Issue by mlampert** [FreeCAD/FreeCAD#7762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=15&t=71059&start=10

### Version

0.21 (Development)

### Full version info

```shell
all
```

### Subproject(s) affected?

Path

### Issue description

see title

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@mlampert also #7758
