### ISSUE TITLE
[Issue] Sketcher Trim tool inconsistent behavior

### ISSUE THREAD

**Issue by macdroid53** [FreeCAD/FreeCAD#7770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=640095#p640095

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Debian GNU/Linux 11 (bullseye) (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.21.30924 (Git)
Build type: Release
Branch: master
Hash: c726b69d7ede5b1af82407c515e14375f3358be3
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: English/United States (en_US)
Installed mods: 
  * parts_library
  * kicadStepUpMod 10.16.5
  * Manipulator 1.4.9
  * PrefExtras
  * QuickMeasure
  * MyDefaults 2022.9.15
  * ZolkoBase 0.0.1
  * DynamicData 2.46.0
  * fasteners 0.4.23
  * MacMechX 2022.9.15
  * ExtremeProDark 2.5.3
  * ProDarkThemePreferencePack 1.0.0
  * fcgear 1.0.0
  * plugins
  * Pyramids-and-Polyhedrons
  * Defeaturing 1.2.0
  * Assembly4 0.12.4
  * BaseTest 0.0.1
  * OpticsWorkbench 1.0.9
  * workfeature-macro
  * sheetmetal 0.2.58
  * A2plus 0.4.60b
  * CurvedShapes 1.0.4
  * BasicMech 0.0.1
  * Dracula 0.0.2
  * Curves 0.5.13
  * workfeature
  * lattice2 1.0.0
[/code]
```

### Issue description

When using the trim tool line/line or line/arc or line/circle the resulting end vertexes are marked coincident. (With or without auto constraint)

When using the trim tool line/spline the resultant vertexes are marked point on object, but not coincident.

### Anything else?

Further details and discussion in forum thread.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AjinkyaDahale** [comment]
Authorized people can assign this to me. This can only be fixed after point on b-spline is merged, otherwise the constraint can be (temporarily) malformed.
