### ISSUE TITLE
[Problem] Menu "Formteil" is missing in english version

### ISSUE THREAD

**Issue by grautvornix** [FreeCAD/FreeCAD#7812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods: 
  * Help 1.0.3
```

### Problem description
Workbench "part":
If language is set to German, you have the menu "Formteil".
After switching language to english, this menu is missing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Example of #6704  
CC @0penBrain @donovaly

**Comment by 0penBrain** [comment]
@luzpaz Not really an example of the other issue (the other is about translations not being updated directly at language change).
Moreover I don't see issue reported here. The German 'Formteil' is strictly same as English 'Part' menu... :confused:

**Comment by luzpaz** [comment]
> (the other is about translations not being updated directly at language change)   

I see what you're saying. But @0penBrain that wasn't my impression of the whole issue. I understood it as anomalies would present when setting in a new language. This falls under that behavior as well, IMHO

**Comment by 0penBrain** [comment]
@grautvornix Can you please give some screenshots/screencast ?

**Comment by luzpaz** [comment]
> Can you please give some screenshots/screencast ? 

@grautvornix indeed, i could use some help recreating this.

**Comment by luzpaz** [comment]
@grautvornix ping

**Comment by luzpaz** [comment]
@Kuzma30 can you recreate this ?

**Comment by luzpaz** [comment]
Closing as no response from op
