### ISSUE TITLE
[Issue] Path: PathSimulator zip archive stored in Path subdir to be removed?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#7816]
### Version

0.21 (Development)

### Full version info

```shell
Latest HEAD
```

### Subproject(s) affected?

Path

### Issue description

The [src/Mod/Path/PathSimulator/Gui](https://github.com/FreeCAD/FreeCAD/tree/955eeb4775b87bb80655f0bbbf993bef49916713/src/Mod/Path/PathSimulator/Gui) has an archive stored in it called [Gui Backup - no need.zip](https://github.com/FreeCAD/FreeCAD/blob/955eeb4775b87bb80655f0bbbf993bef49916713/src/Mod/Path/PathSimulator/Gui/Gui%20Backup%20-%20no%20need.zip). 

Looks like it was added by @shaise when he coded all that work for the Path Simulator. Can this .zip file be removed? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shaise** [comment]
I believe this zip can be deleted. Its a remnant of simulator being a separate wb.
