### ISSUE TITLE
[Problem] [TechDraw]3d Dimensions are too difficult to create

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FreeCAD#7830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
n/a
```

### Subproject(s) affected?

Techdraw

### Problem description

a) To create a dimension based on 3d geometry requires the use of the awkward LinkDimension command.   It should as close as possible to the method of creating a dimension based on projected 2d geometry.

b)  The code to create dimensions is duplicated for each type of dimension.  The common bits should be extracted.

c) Geometry references (PropertyLinkSubList) are awkward to use.  A layer should be added to minimize the complexity of retrieving the geometry details.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@WandererFan is this ticket still relevant ?

**Comment by WandererFan** [comment]
closed as completed by #8141
