### ISSUE TITLE
Bug Report on Shell command

### ISSUE THREAD

**Issue by TyPosey** [FreeCAD/FreeCAD#7838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
Version FreeCAD 0.20.1 for MacOS intel.
```

### Subproject(s) affected?

PartDesign

### Problem description

Workbench: Part Design
create sketch: Circle at origin
pad extrude: 22 mm check draft option
Shell command. the part places the outer shell 90 degrees to the rest of the part.

Not sure if this is part of the topographical naming issue or not.

14:38:45 1.810736 <asm3.main> init_gui.py(14): no solver backend found

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Looks like an assembly3 issue. No idea what Assembly3 version you're running. You missing full `About` version.  Closing as this looks like user error. Please ask on the Assembly sub forum: https://forum.freecadweb.org/viewforum.php?f=20
