### ISSUE TITLE
[Issue] German -> Arbeitsbereich Part -> have a wrong link

### ISSUE THREAD

**Issue by designlabworms** [FreeCAD/FreeCAD#7843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

https://wiki.freecad.org/User_hub/de:

 [[Image:Workbench_**Part**.svg|32px]] Der [[**Image**_Workbench/de|Arbeitsbereich Part]] für die Arbeit mit CAD Teilen.

have to be:

 [[Image:Workbench_Part.svg|32px]] Der [[Part_Workbench/de|Arbeitsbereich Part]] für die Arbeit mit CAD Teilen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Fixed.
Please open a forum thread next time on the Translation subforum instead of opening a ticket here. 

Thank you!
