### ISSUE TITLE
add ppa for Ubuntu 22.10 / kinetic

### ISSUE THREAD

**Issue by bastolino** [FreeCAD/FreeCAD#7845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
no installation possible for 0.20/0.21 on Ubuntu 22.10 / kinetic
```

### Issue description

Installation not possible because no ppa available for kinetic; with jammy ppa I get the following unresolved dependency:
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libfreecad-python3-0.20 : Hängt ab von: libboost-regex1.74.0-icu70 ist aber nicht installierbar
                           Hängt ab von: libocct-data-exchange-7.5 (>= 7.5.1+dfsg1) ist aber nicht installierbar
                           Hängt ab von: libocct-foundation-7.5 (>= 7.5.1+dfsg1) ist aber nicht installierbar
                           Hängt ab von: libocct-modeling-algorithms-7.5 (>= 7.5.1+dfsg1) ist aber nicht installierbar
                           Hängt ab von: libocct-modeling-data-7.5 (>= 7.5.1+dfsg1) ist aber nicht installierbar
                           Hängt ab von: libocct-ocaf-7.5 (>= 7.5.1+dfsg1) ist aber nicht installierbar
                           Hängt ab von: libocct-visualization-7.5 (>= 7.5.1+dfsg1) ist aber nicht installierbar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
This is a known issue. We currently are looking for a PPA maintainer. See https://forum.freecadweb.org/viewtopic.php?f=42&t=69055

Closing
