### ISSUE TITLE
[Problem] Navicube corners are small and difficult to click on

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD#7875]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=34&t=68544

### Subproject(s) affected?

Core

### Idea description

Currently navi cube corners are small and can be hard to click, one proposed solution is to use a bigger hexagonal shape instead of the current triangular shape
![image](https://user-images.githubusercontent.com/36372335/203849807-d8ca2a57-6172-4da7-a975-762ba25355b5.png)
![image](https://user-images.githubusercontent.com/36372335/203849862-5fa0611d-2713-4cf2-add0-b32e5bd2af35.png)

here the lines of code that likely need to be changed:
https://github.com/FreeCAD/FreeCAD/blob/a6b9a53bed2775107d8b8d21eedab5cdba3fdf2f/src/Gui/NaviCube.cpp#L422-L438

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by silopolis** [comment]
YES! 😍
Please 🙏

**Comment by MisterMakerNL** [comment]
IT's cool, not original but it's better.

**Comment by adrianinsaval** [comment]
almost there:
![image](https://user-images.githubusercontent.com/36372335/203868044-5b8d46fb-c899-4f7e-9c92-ff49a1c9510c.png)
I don't understand well how the transformations of the corner work so I don't know how to properly adjust the position, also I don't know why a square is still being drawn on the sides on top of the filleted squares

**Comment by adrianinsaval** [comment]
thanks to the help from @Jolbas it's almost ready now:
![image](https://user-images.githubusercontent.com/36372335/203876834-cb5da466-9b8d-4aef-b014-5884a09096e1.png)

**Comment by adrianinsaval** [comment]
made a PR #7876
