### ISSUE TITLE
[Issue] Parsing of i18n-numeric formats (with a comma instead of a dot)

### ISSUE THREAD

**Issue by vanrein** [FreeCAD/FreeCAD#7894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: elementary OS 6.1 Jólnir
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Python version: 3.9.2
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.1
Locale: English/United Kingdom (en_GB)

[So, the version is not 0.20 but I did not find an issue so I suspect it also occurs in later versions]
```

### Subproject(s) affected?

FEM

### Issue description

My locale uses `LC_NUMERIC="nl_NL.UTF-8"` which means that 8 is printed as `8,00` -- the comma separates the integer part from the fractional part, what is done with a dot in most other environments.

Creating a 1mm x 1mm x 8mm beam of the material Calculix-Steel, it wants to set a Young's Modulus of `2100,00 GPa` and a Poisson Rate of `0,300` -- note the commas in these GUI representations of the values.  The Python console complains about the format of the Poisson Rate (which it presumably sees first, but all values use those silly Dutch commas) with

```
12:44:03  Traceback (most recent call last):
12:44:03    File "/usr/share/freecad/Mod/Fem/femtaskpanels/task_material_common.py", line 572, in pr_changed
12:44:03      self.update_material_property(
12:44:03    File "/usr/share/freecad/Mod/Fem/femtaskpanels/task_material_common.py", line 526, in update_material_property
12:44:03      value = float(input_field.text())
12:44:03  ValueError: could not convert string to float: '0,300'
```

Presumably the value is setup with knowledge of `LC_NUMERIC` but not parsed accordingly.

I can edit comma-based values in other places (like the beam size) and that works flawlessly.

This issue is remedied with `LC_NUMERIC="en_GB.UTF-8"`.  Which gives me a work-around, but it also demonstrates the cause to be with i18n of those value(s).

### Anything else?

I'm just getting started with CAD/FEM, but after having gone through the initial frustration of misunderstanding the software I watched YouTube guides and they made it all "click".  FreeCAD now makes a lot of sense to me, thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vanrein** [comment]
Browsing around the code, most fields use `Units.Quantity()` but the Young's Modulus is dimension-less and uses the `float()` builtin directly.  Making it easy to oversee when adding i18n.

**Comment by adrianinsaval** [comment]
can you link to the line of code in question?
@WandererFan could you check this one out?

**Comment by adrianinsaval** [comment]
I did not notice this was reported for 0.19, please test in the latest stable release (currently 0.20.1) before creating an issue, older versions will not receive any bugfixing anymore so it's pointless. If the bug has been fixed already please close this issue.
