### ISSUE TITLE
[Problem] CAM: pocket made with splines fails

### ISSUE THREAD

**Issue by acp693** [FreeCAD/FreeCAD#7913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?f=15&t=74016

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.31109 (Git)
Build type: Release
Branch: master
Hash: c23ee7ad88433a0f00e84afae0a62fe738be0c09
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes 1.0.4
  * Curves 0.5.3
  * FeedsAndSpeeds 0.4.0
  * Marz 0.0.26-alpha
  * Silk 1.0.0
```

### Subproject(s) affected?

Path

### Issue description

Path generated for a pocket made with splines fails to generate path that reaches the bottom of the pocket

### Anything else?

[BSplinePocket.zip](https://github.com/FreeCAD/FreeCAD/files/10125680/BSplinePocket.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Looks like in last dev situation with curve and spline is the same.
To get full depth need to set little value for **Finish Depth**

![Screenshot_20241221_082714_opti](https://github.com/user-attachments/assets/eaec6024-7ebf-4a7c-8d25-ca36447a9d2b)

**Comment by maxwxyz** [comment]
So is the issue resolved?

**Comment by tarman3** [comment]
It doesn't look like it.
It seems the behavior has changed.
