### ISSUE TITLE
[Problem] Sketcher: disabling edit controls causes core dump on exit

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD#7931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Linux 6.0.10-zen2-1-zen (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.31182 (Git)
Build type: None
Branch: master
Hash: 3148ea6651bcc4af7fdebf1bdb7fe131502341a9
Python 3.10.8, Qt 5.15.7, Coin 4.0.1, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C) [ OS: English/United Kingdom (en_GB) ]
Installed mods:
[/code]
```

### Subproject(s) affected?

Sketcher

### Problem description

after disabling the edit controls widget in sketcher preferences (a restart might be needed?) when closing freecad after having opened sketcher at least once it always leaves this message in the console:

> Not detached all observers yet
> freecad: /__w/pacman-repo/pacman-repo/PKGBUILD/freecad-git/src/FreeCAD/src/Base/Observer.h:122: Base::Subject<MessageType>::~Subject() [with _MessageType = const Gui::SelectionChanges&]: Assertion `0' failed.
> [1]    64641 IOT instruction (core dumped)  freecad

And it appears to not be able save preferences, I realized now this was the cause of a bug I reported while testing a PR:
https://github.com/FreeCAD/FreeCAD/pull/7886#issuecomment-1328357029

> the checkboxes are now working correctly within the same session, but it seems the state is not saved to the config file, any time you close and restart freecad everything is back to where it was, including active filters and the filter checkbox.

After enabling again the edit controls widget the checkboxes I change correctly saved and restored and no error message is displayed on the console when exiting freecad

ping @PaddleStroke @0penBrain 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0penBrain** [comment]
Good catch :)
