### ISSUE TITLE
[Problem] 2D Offset with a complex imported sketch 

### ISSUE THREAD

**Issue by Igor-Misic** [FreeCAD/FreeCAD#7945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: Ubuntu 20.04.5 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20.1)
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Part

### Problem description

When I imported SVG and then converted it to sketch I got this: 

![image](https://user-images.githubusercontent.com/10188706/205494390-7f7f937d-d73a-4200-a140-0a08dca755b5.png)

The issue is when I try to use Part -> 2D-Offset I got this:
```
14:52:01  <Exception> makeOffset2D: result of offsetting is null!
14:52:01  Recompute failed! Please check report view.
```

Just to mention that 2D Offset works properly if I sketch something on my own. Also, I can create objects from the sketch and manipulate them. 
What could be the issue? to complex sketch or something else? 

### Anything else?
SVG:
![pikacu](https://user-images.githubusercontent.com/10188706/205501050-3d043458-439f-45c4-a240-4e9464e814c9.svg)

To reproduce use the first "Path"
![image](https://user-images.githubusercontent.com/10188706/205501111-42001b64-f945-4524-9ddb-ecf7659bc66d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Please attach SVG

**Comment by Igor-Misic** [comment]
![pikacu](https://user-images.githubusercontent.com/10188706/205501050-3d043458-439f-45c4-a240-4e9464e814c9.svg)
SVG attached. 
To reproduce use the first "Path"
![image](https://user-images.githubusercontent.com/10188706/205501111-42001b64-f945-4524-9ddb-ecf7659bc66d.png)

**Comment by grubertechnic** [comment]
svg is a "crap" format for any type of CAD. It have not the preciseness, which is needed for that, besides the shape is too cluttered (see the points positions) and complex (awaiting intersections) in combination. I am sure that pretty every CAD will give not valid offset (in term of CAD, no nearing method) in this. Should be closed.

**Comment by Igor-Misic** [comment]
Thanks for the explanation.
