### ISSUE TITLE
[Issue] Moving an object with "Transform" leaves a ghost artifact

### ISSUE THREAD

**Issue by lmurta** [FreeCAD/FreeCAD#7988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 2022.1021.26244 +5249 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: d307b5c936403e8dca3f24b5c1e64bd16c88b28d
Python version: 3.9.13
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Issue description

1 Select some objects;
2 Move them with the Transform At tool;
3 The objects are moved but a "ghost" image or ghost lines are left behing (See first image)
4 Close the file and reopen it and the ghost images disappears. (see second image)
![bug1](https://user-images.githubusercontent.com/605261/206429344-1fe6fe3c-58e6-4c9f-bc71-f5b91ce4c2c5.png)
![bug2](https://user-images.githubusercontent.com/605261/206429348-c05bf2c8-d191-4ff6-80c3-957d7ef48ba1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adiazubierna** [comment]
I tried to replicate this issue with a very simple model and I was unable to replicate it.

If you can add some extra details or the file might be helpful.

Full version info

> [code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Spanish/Spain (es_ES)
[/code]

**Comment by grubertechnic** [comment]
> ```shell
> Branch: LinkDaily
> ```

Branches, they are not from this repository, does not belong here.

Should be closed.

**Comment by luzpaz** [comment]
This is a Link Branch issue. Please don't confuse the 2. Post your problem to https://github.com/realthunder/FreeCAD/issues
