### ISSUE TITLE
build on mac

### ISSUE THREAD

**Issue by jaywarrick** [FreeCAD/FreeCAD#8]
Not sure if this is the best medium but I wondered if you have tried very recently to run ./autogen.sh, ./configure (tons of options), make recently. I'm trying to run this off the master github repository and have all the dependencies in place. The make won't complete because of a host of missing src files, which I don't think should be a system or compiler dependent issue. Files like...

FeaturePythonPy.cpp
InitScript.h
TestScript.h

Are reported. Also, some errors like...
error: 'FreeCADInit' was not declared in this scope
error: 'FreeCADTest' was not declared in this scope

PropertyContainerPy.h was also missing

There are likely more but I decided to give up. Could someone take a look at why these files would be missing from the github repository? Likely the whole process of making should be verified by one of the developers given it seems that it is quite broken at the moment. 

I'm trying to build from scratch because the mac binary is significantly out of date. If I'm wrong about this or If someone gets it working on mac, I (and likely many others) would LOVE a link to an updated binary if possible.

Thank you thank you thank you. I love that there is finally a free parametric modeling software!!!!

Cheers.

**Comment by chennes** [comment]
Closing pending migration of bugs from Mantis.
