### ISSUE TITLE
[Problem] choosing new document segfaults the application

### ISSUE THREAD

**Issue by janneman001** [FreeCAD/FreeCAD#8049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: openSUSE Leap 15.3 (GNOME/default)
Word size of FreeCAD: 64-bit
Version: 0.20.2.Unknown
Build type: Release
Python 3.6.13, Qt 5.12.7, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
[/code]
```

### Subproject(s) affected?

None

### Problem description

choosing a new document segfaults like so:

** (FreeCAD:19670): WARNING **: 21:09:10.531: invalid source position for vertical gradient

** (FreeCAD:19670): WARNING **: 21:09:10.531: invalid source position for vertical gradient
Segmentatiefout (geheugendump gemaakt)

I tried new document icon also the menu item new document and the + in the startpage. All the same result and GUI disappears. I have to restart the application.

### Anything else?

I also looked in the forum. I did not find it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
I suggest starting a discussion in the forum: until there is some indication of what is actually going wrong there's not much developers can do. Feel free to reopen this issue once there is some indication of what's causing the segfault you are seeing.
