### ISSUE TITLE
[Task] Update FreeCAD copyright to 2023

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#8130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

n/a

### Version

HEAD

### Subproject(s) affected?

All

### Issue description

self-explanatory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Would we want to wait until certain large pending PRs are merged ?

**Comment by luzpaz** [comment]
Should I close this issue since it's obvious ?

**Comment by luzpaz** [comment]
We should do this in conjunction with #6166

**Comment by donovaly** [comment]
What exactly has to be updated? For the *-cpp/*.h files we usually use the year the file was created of heavily modified?

Can you therefore please add a list of dates that have to be updated?

**Comment by luzpaz** [comment]
@donovaly you're absolutely right, I was mistaken. There are only 3 files that need to be updated. I've created a PR. Please squash before merging. TIA!
