### ISSUE TITLE
Thank you so much for destroying unsaved data!

### ISSUE THREAD

**Issue by imyoric** [FreeCAD/FreeCAD#8164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

After launching the application, my system hung! And finally, after a long time, the Finder restarted, destroying all unsaved data! Thank you THANK YOU SO MUCH! THANK YOU VERY MUCH!

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
* No full version info
* No error message
* Aggro
* FreeCAD autorecovery options https://wiki.freecadweb.org/Preferences_Editor#Document
