### ISSUE TITLE
Missing dimension arrows

### ISSUE THREAD

**Issue by ANV-2023** [FreeCAD/FreeCAD#8177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Portuguese/Brazil (pt_BR)
Installed mods: 
  * A2plus 0.4.60f
  * ArchTextures
  * BIM 2021.12.0
  * ExplodedAssembly
  * ModernUI
```

### Subproject(s) affected?

None

### Problem description

**English:**  
I'm using version 0.20.2 and the dimension arrows don't appear (no format). I already uninstalled and installed version 0.19, but the problem continues. Before it was normal. I've looked into this and found nothing.

**Portuguese:**  
Estou usando a versão 0.20.2 e as setas das cotas não aparecem (nenhum formato). Já desinstalei e instalei a versão 0.19, mas o problema continua. Antes estava normal. Já pesquisei sobre isso e não encontrei nada.

### Anything else?

![Captura de tela 2023-01-12 171901](https://user-images.githubusercontent.com/122567882/212172147-81c7b873-95fc-44c4-9f2d-a797e1d4d524.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
The bug tracker is english speaking. Do you mind uploading an example file (you can zip the .FCStd file)

**Comment by WandererFan** [comment]
Arrow size in preferences?

![DimensionArrowSize](https://user-images.githubusercontent.com/3587161/212439899-3d1ed1ce-050f-4280-8631-98047dc41904.png)

Size = 0.0
![DimensionArrowSizeZero](https://user-images.githubusercontent.com/3587161/212439906-f6592e1d-5c59-487e-86e8-5ba6c19fa70a.png)

Size = 5.0
![DimensionArrowSize5](https://user-images.githubusercontent.com/3587161/212439913-27dd1537-1818-4587-a78a-546f036fb53f.png)

**Comment by ANV-2023** [comment]
> Tamanho da seta nas preferências?
> 
> ![DimensãoArrowSize](https://user-images.githubusercontent.com/3587161/212439899-3d1ed1ce-050f-4280-8631-98047dc41904.png)
> 
> Tamanho = 0,0 ![DimensãoArrowSizeZero](https://user-images.githubusercontent.com/3587161/212439906-f6592e1d-5c59-487e-86e8-5ba6c19fa70a.png)
> 
> Tamanho = 5,0 ![DimensãoArrowSize5](https://user-images.githubusercontent.com/3587161/212439913-27dd1537-1818-4587-a78a-546f036fb53f.png)


> O rastreador de bugs fala inglês. Você se importa em enviar um arquivo de exemplo (você pode compactar o arquivo .FCStd)

Segue arquivo de exemplo:

[teste.zip](https://github.com/FreeCAD/FreeCAD/files/10417406/teste.zip)

**Comment by ANV-2023** [comment]
It's not a problem of lack of value in preferences.

![Captura de tela 2023-01-14 100444](https://user-images.githubusercontent.com/122567882/212474365-6aa1c646-1489-41cd-9192-f923be0e818c.jpg)

**Comment by ANV-2023** [comment]
Follow exemplo file:

[teste.zip](https://github.com/FreeCAD/FreeCAD/files/10417434/teste.zip)

**Comment by WandererFan** [comment]
5 μm?  That smaller than a human hair!

**Comment by luzpaz** [comment]
Looks like a PEBKAC error. Closing ticket

**Comment by ANV-2023** [comment]
Obrigado e desculpem. Não percebi.
