### ISSUE TITLE
 [Problem] Cuts not working across multiple bodies 

### ISSUE THREAD

**Issue by FurrySparkle** [FreeCAD/FreeCAD#8183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
```

### Subproject(s) affected?

None

### Problem description

I've followed your wiki, forum, and even asked Chatgpt to help me cut 3 cones with a subtractive box. Cgpt was best but telling me to add shapes in some non existing menu.

Quite infuriating that the box is sized right and even cuts the first cone but not the others

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
No About info or file. No effort bug report.  
This is not a helpdesk. Ask on the forum next time before opening a ticket (save the time of volunteers)
