### ISSUE TITLE
[Issue] Pad with reference direction does not allow to select edges from a feature different than the previous

### ISSUE THREAD

**Issue by chrisb-github** [FreeCAD/FreeCAD#8202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.21.0.31598 (Git)
Build type: Release
Branch: master
Hash: f7db685a2821adaf23c85a25855401ecc1eeff2c
Python 3.10.8, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FC_SU
  * DynamicData 2.46.0
  * freecad.gears 1.0.0
  * FeedsAndSpeeds 0.4.0
  * dxf-library
  * fcgear 1.0.0
  * fasteners 0.4.16
  * sheetmetal 0.2.60
  * ExplodedAssembly
  * Curves 0.6.5
```

### Subproject(s) affected?

None

### Issue description

To minimize topological issues it is sensible to reference the first occurrence of an edge. For Pads with a reference direction - and probably for pockets too - the selection is restricted to the direct predecessor. Other tools allow to change the visibility while the tool is active and selecting the reference direction should behave the same. An example is Pad's "Up to face" type

Attached file: [padReferenceDirection.zip](https://github.com/FreeCAD/FreeCAD/files/10430291/padReferenceDirection.zip)

![SnipScreenshot-7374df](https://user-images.githubusercontent.com/11750017/212787706-88c765ec-12ed-4e47-b74b-09ed1d0d13a2.png)  
Above image shows the final result, the selected edge defines the direction of the pad.

If selected from the pad dialog Edge9 defines the direction. If the previous sketch is changed, then Edge9 is in a different place and the last pad fails. The image shows where it is now.
In the attached FreeCAD file this is fixed by changing the reference to Pad[Edge6] instead of Pocket[Edge9].
![SnipScreenshot-b62102](https://user-images.githubusercontent.com/11750017/212788229-91a20a55-d591-4bc7-a31c-8ca493a1e182.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PLChris** [comment]
Here is the file, it didn't make it in the first post.
[padReferenceDirection.zip](https://github.com/FreeCAD/FreeCAD/files/10430291/padReferenceDirection.zip)

**Comment by luzpaz** [comment]
@AjinkyaDahale do you have a moment to look in to this ?

**Comment by AjinkyaDahale** [comment]
@luzpaz this is just another toponaming issue, right?

**Comment by AjinkyaDahale** [comment]
I feel a bit confused what the point here is: is it to implement a simpler form of toponaming fix?

**Comment by luzpaz** [comment]
@AjinkyaDahale yes, indeed that is what it looks like. 

@PLChris is there a forum thread where this is discussed or did you intend for this to be the discussion place?

**Comment by luzpaz** [comment]
ping @PLChris

**Comment by maxwxyz** [comment]
is this still relevant?
@FlachyJoe @bgbsww FYI

**Comment by FlachyJoe** [comment]
Fixed only by showing the Eye icons, else we can't switch features visibility when edge selection mode is activated.

**Comment by maxwxyz** [comment]
@NomAnor how the eye for default going?

**Comment by NomAnor** [comment]
#14393 is merged

**Comment by maxwxyz** [comment]
So this issue could be closed then?
@chrisb-github

**Comment by maxwxyz** [comment]
I'm closing this then.
