### ISSUE TITLE
Multiple documents open: when editing feature/sketch in the 2nd document: switches always to the 1st document 3D view

### ISSUE THREAD

**Issue by HuibSmeets** [FreeCAD/FreeCAD#8204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=46421

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * A2plus 0.4.60h
  * kicadStepUpMod 10.16.9
  * Assembly3 0.11.4
[/code]

and also:

[code]
OS: macOS 13.1
Word size of FreeCAD: 64-bit
Version: 0.21.0.31483 (Git)
Build type: Release
Branch: master
Hash: 588620fd9fd138892b1cd2466f5c87d441493174
Python 3.11.0, Qt 5.15.6, Coin 4.0.0, Vtk 9.2.2, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

None

### Issue description

This is most likely MacOS (in combination with Qt) specific.

Was discussed in the forum some years ago, I can reproduce this consistently.

To reproduce:

1) open a existing document (or create one with simple geometry like a padded circle)
2) open a 2nd document (or create one with a simple geometry like a padded square)

keep the windows in tabbed (not tiled or cascaded) arrangement

3) make the second document active and edit the padding or sketch.

On MacOS the software now selects the 3D view of the first document instead of the 2nd document that's being worked on.

When windows are tiled: no issue
When windows are cascaded: similar as with tabbed: If the 2 windows overlap, upon editing the 2nd document the window of the first document will overlay the 2nd document again.

This is confusion (at least at first), current workaround is to select the correct window via the tabs below the 2 windows, not a showstopper but would be nice if it could be fixed one day. Maybe due to a underlaying Qt issue with MacOS?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HuibSmeets** [comment]
Additional observation:

The issue seems to be related to the combo view  panel of the Tree and Tasks.

When I drag the Tree view panel out of the Combo view panel and place it elsewhere the behavior as described above does no longer occur and the correct window is shown. 

And when I drag the Tree panel back into the Combo panel the "problem" behavior returns. 

<img width="1552" alt="Scherm­afbeelding 2023-01-17 om 20 56 50" src="https://user-images.githubusercontent.com/117679210/213000222-f111e4c7-c74f-44dd-9c7d-1c5de7b4bd44.png">

**Comment by luzpaz** [comment]
Is this a dupe of #7745 ?

**Comment by HuibSmeets** [comment]
oops, yes, it is a duplicate of #7745.

When looking at the (source code of the) patch @realthunder created it seems to confirm it is a MacOS specific problem with the Comboview as I experienced myself (see my comment about dragging the tree view out of the combo view). 

I'll close this one.

**Comment by rixth** [comment]
@HuibSmeets How the heck do you drag the tree view out of the combo view? I've been trying to do it for 20 minutes!

**Comment by HuibSmeets** [comment]
@rixth It's in the preferences......change from Combo View to any of the other two.

but it only takes effect after restarting FreeCAD

<img width="892" alt="Scherm­afbeelding 2023-04-21 om 20 37 23" src="https://user-images.githubusercontent.com/117679210/233711194-6febbec0-13c3-46a9-830a-ff2f4adad4c8.png">
