### ISSUE TITLE
[Problem] Is the installer of "FreeCAD-0.20.2-WIN-x64-installer-2" broken?

### ISSUE THREAD

**Issue by softempire** [FreeCAD/FreeCAD#8279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
I always got the error message
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

![image](https://user-images.githubusercontent.com/1004480/215036887-3c82ee21-bf25-49df-95e7-ea4a5a254e0a.png)
![image](https://user-images.githubusercontent.com/1004480/215036906-6f1c7561-cddd-487d-83d4-08afd1aa9c9b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
For this we have the checksum. Download the checksum file and compare it with the checksum of what you have downloaded. Here is my result:
![7zG_mH6VOgYdda](https://user-images.githubusercontent.com/1828501/215186873-26ec3d58-a32a-40eb-bdad-60dbb0b0f349.png)

By deleting the downloaded file and re-downloading your problem should be solved.

**Comment by donovaly** [comment]
Moment, from where have you downloaded the file?
Your screenshot shows as if the installer requires admin permissions. That is not the case. So in your icon shouldn't be the small shield icon.
