### ISSUE TITLE
[Feature Request] Radial/Elliptical gradient as display background colour

### ISSUE THREAD

**Issue by Intuos5** [FreeCAD/FreeCAD#8297]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?t=72672&start=60

### Subproject(s) affected?

Other (specify in description)

### Idea description

Currently, it is possible to choose between a flat background colour and a linear gradient:
![Linear gradient](https://user-images.githubusercontent.com/63149655/215363551-0ba0233d-0274-46df-a2e5-e59eb1cc3795.png)

It would be nice to have a radial/ elliptical gradient as option:
![elliptical gradient](https://user-images.githubusercontent.com/63149655/215363886-1bb9e4af-57dd-4340-88de-ba1d65e5bc50.png)

The reason is that this gives a more balanced colour distribution across the screen. That way, there is less of a strong highlight in the centre and more a halo-like effect, which helps improve visibility of the model and sketches.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@Intuos5 just wondering, can this be set via stylesheet?

**Comment by MisterMakerNL** [comment]
Been digging into this:
Came out on the 3DInventoryViewer.
IS this the viewer that the Quarter widget uses to overlay the Coin3D engine?
https://freecad.github.io/SourceDoc/d5/d29/classGui_1_1View3DInventorViewer.html#a80066cb7b376b603218006587af684a1

**Comment by luzpaz** [comment]
@realthunder would you happen to know ?

**Comment by MisterMakerNL** [comment]
Did some more digging but the deeper I go the further I am out of my league.
3DInventoryViewer has an [GLOverlayWidget()](https://freecad.github.io/SourceDoc/df/d70/classGui_1_1GLOverlayWidget.html#af98a4ccb67c263d0e0bc85c74ad22215) that use [Qpainter](https://doc.qt.io/qt-6/qpainter.html), that also has a background and an image option.
My goal is an image btw not a gradient, images are way more versatile and current systems won't mind the extra memory usage. (also you can just go back to single color if you are worried about that.)
An SVG file option would be ideal, since it would be small sized and versatile. Although having png as an option would be cool too!

**Comment by Intuos5** [comment]
@MisterMakerNL indeed an image is more versatile. Inventor also uses images, noticed that when I gave it a spin. Maybe it's possible to ship an inkscape template (SVG) file so people can easily adjust it. Completely agree with you.

**Comment by Intuos5** [comment]
> @Intuos5 just wondering, can this be set via stylesheet?

It's not in the default templates IIRC, haven't read it, but didn't use the search function in VSCode either.

**Comment by MisterMakerNL** [comment]
Currently we change the gradient colors with the theme cfg file. There is a background image/watermark in the stylesheet, you see that when you close all documents.
If we can set the background of the 3D window to transparent. 😆

**Comment by Intuos5** [comment]
Ah yes the FreeCAD watermark.Don't add hidden easter eggs 😂

**Comment by MisterMakerNL** [comment]
More diggin:
https://www.openinventor.com/reference-manuals/NewRefMan9912/RefManJava/com/openinventor/inventor/vrmlnodes/SoVRMLTextureBackground.html#backTexture
and
https://www.openinventor.com/reference-manuals/NewRefMan9912/RefManJava/com/openinventor/inventor/vrmlnodes/SoVRMLBackground.html#backUrl
Now if only I knew how to test those command :)

**Comment by luzpaz** [comment]
@chennes do you mind weighing-in ?
