### ISSUE TITLE
File, Edit, View Drop Downs - don't work.

### ISSUE THREAD

**Issue by bstott** [FreeCAD/FreeCAD#8331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 Version 2004
Word size of FreeCAD: 64-bit
Version: 0.21.0.31739 (Git)
Build type: Release
Branch: master
Hash: 37dc6e8a296073bf5c437b975d8fb236f923723f
Python 3.10.8, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * A2plus 0.4.60g
  * Assembly4 0.12.5
  * boltsfc 2022.11.5
  * CfdOF 1.20.6
  * CurvedShapes 1.0.4
  * Curves 0.6.5
  * Defeaturing 1.2.0
  * Design456 0.0.1
  * DynamicData 2.46.0
  * EM
  * Estimate 0.1.2
  * ExplodedAssembly
  * fasteners 0.4.50
  * fcgear 1.0.0
  * FEMbyGEN 1.2.0
  * FEM_FrontISTR 0.1.0
  * freecad.gears 1.0.0
  * Help 1.0.3
  * InventorLoader 1.3.0
  * lattice2 1.0.0
  * Launcher
  * Manipulator 1.4.9
  * offline-documentation 1.0.0-alpha
  * OpticsWorkbench 1.0.9
  * parts_library
  * pcb
  * PieMenu 1.2.4
  * POV-Ray-Rendering
  * QuickMeasure 2022.10.28
  * Silk 1.0.0
  * slic3r-tools
  * SlopedPlanesMacro
  * symbols_library
  * ThreadProfile 1.84.0
  * toSketch 1.0.1
[/code]
```

### Subproject(s) affected?

None

### Problem description

The File, Edit, View drop down menus do not highlight with mouse over or drop down when clicked on. It appears there is a click region which does not extend over those menu items. 

How to observe the problem.  Mouse over the View menu to the right edge, near to the Tool menu, until the View menu item highlights.  You can then click the View menu for the expected drop down.  You can only get to the Edit and File menus by then, dragging the mouse left. Otherwise. you can not get to the drop down selections beneath the File, Edit, or View menus. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
This should be closed as a duplicate, I'm updating what I find in #7965
