### ISSUE TITLE
[Feature Request] Extend PartDesign's python interface (API)

### ISSUE THREAD

**Issue by Jee-Bee** [FreeCAD/FreeCAD#8345]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=75627

### Subproject(s) affected?

PartDesign

### Idea description

Currently the PartDesign Workbench is scriptable but not on a nice pythonic way.
There are only a few features directly accessible when import PD.

an example of what i have in mind(rough idea):
```
import PartDesign as pd

my_body = pd.add_body()
new_sketch = my_body.add_sketch(Some_plane, ...)
new_pad = my_body.add_pad(new_sketch, ..., ...)
```

Since it is some time ago that i checked the PD C++ code i'm not sure if my rough idea is the best way to go.
In my opinion every feature that is accessible from python is an improvement 

### Anything else?

Print screen of current in python available PD features

<img width="374" alt="Screenshot 2023-01-29 at 13 00 23" src="https://user-images.githubusercontent.com/7187677/216772383-6a90d3bf-a7e6-4044-8b20-48100fd92db1.png">
<img width="320" alt="Screenshot 2023-01-29 at 19 21 19" src="https://user-images.githubusercontent.com/7187677/216772384-8bd66b52-7ca1-4a71-a278-a1ea952e8a3f.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@Jee-Bee can you make a list of requested python functions (that we can track in this ticket) ?

**Comment by Jee-Bee** [comment]
I tried to create a list of features i want to acces. I don't care about the naming. I think that is not my role even if i created the FR.

- Create body
- Create Sketch
- Map sketch

- Create Datum Plane
- Create Datum Axis (line)
- Create Datum CS
- Create Datum point
  

- Create Shape Binder
- Create Sub object
- Create Clone


- Pad
- Revolution
- additive Loft
- additive Pipe
- additive Helix
 
- Pocket
- Hole
- Groove
- subtractive loft
- subtractive pipe
- subtractive helix
 
- Mirror
- Linear Pattern
- Polar Pattern
- Multi Transform

- Fillet
- Chamfer
- Draft
- Thickness

I'm not sure about the primitives. I personally don't care. But i can understand that others thing different about that

**Comment by FlachyJoe** [comment]
NB : all listed objects can be make throw DocumentObject.addObject and BodyObject.newObject so only helpers are claimed.
```
>>> App.ActiveDocument.addObject('PartDesign::Body', 'Body')
<body object>
>> pad = App.ActiveDocument.Body.newObject('PartDesign::Pad','Pad')
>> mirror = App.ActiveDocument.Body.newObject('PartDesign::Mirrored','Mirrored')
>> mirror.Originals = [pad]
>> #etc.
```

**Comment by luzpaz** [comment]
Maybe this is a usecase for @mnesarco's https://github.com/mnesarco/fcscript ?

**Comment by mnesarco** [comment]
> Maybe this is a usecase for @mnesarco's https://github.com/mnesarco/fcscript ?

Yes, in the demo macro available after install, there are many examples creating sketches and padding in a PD Body.

**Comment by Jee-Bee** [comment]
The request is not about what is already possible. Ofcourse i can record a macro and i am able to automate things...
The request is about having a dedicated (preferable )pythonic interface.
The mentioned commands work probably well when recording a macro but give no help when using with PD as imported Module.
see as example: https://forum.freecad.org/viewtopic.php?t=76312

**Comment by mnesarco** [comment]
fcscript is a project  of a simplified and pythonic api for FreeCAD

**Comment by mnesarco** [comment]
fcscript is a project  of a simplified and pythonic api for FreeCAD

**Comment by Jee-Bee** [comment]
Thanks! Sounds like a good idea, assuming it ends in FC main code ;)

**Comment by luzpaz** [comment]
@Jee-Bee it's currently available via the Addon Manager. It's super promising!

**Comment by adrianinsaval** [comment]
I don't consider Part Design to be primarily intended for this kind of use, I consider this request out of scope for the Part Design project as maintaining an additional interface is quite the maintenance burden as it would need to be constantly updated and extended as Part Design evolves.

Not everything needs to be on the main repo, I would say mnesarco's addon satisfies this need. Also consider using the Part API instead when working through python.
