### ISSUE TITLE
[Issue] typo in code example for Arch CurtainWall

### ISSUE THREAD

**Issue by zenmatic** [FreeCAD/FreeCAD#8364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * parts_library
[/code]
```

### Subproject(s) affected?

Arch

### Issue description

Typo in code example on https://wiki.freecad.org/Arch_CurtainWall/en

`baseface = Free.ActiveDocument.addObject('Part::Extrusion','Extrusion')`

should be

`baseface = FreeCAD.ActiveDocument.addObject('Part::Extrusion','Extrusion')`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Thanks!  
Fixed in https://wiki.freecad.org/index.php?title=Arch_CurtainWall&oldid=1227255
