### ISSUE TITLE
[Issue] NURBS circular arcs are incorrectly trimmed

### ISSUE THREAD

**Issue by edwilliams16** [FreeCAD/FreeCAD#8385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=75846

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.21.0.31709 (Git)
Build type: Release
Branch: master
Hash: e188802ca6997d2564e7570ab648462e6a059f87
Python 3.10.8, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * MeshRemodel 1.8919.0
  * Trails 2022.1.0
  * offline-documentation.backup1670387333.286728 1.0.0-alpha (Disabled)
  * DynamicData 2.46.0
  * offline-documentation.backup1668887250.997013 1.0.0-alpha (Disabled)
  * Curves.backup1667610597.862062 0.5.12 (Disabled)
  * fcgear 1.0.0
  * workfeature
  * offline-documentation.backup1673656435.692312 1.0.0-alpha (Disabled)
  * Pyramids-and-Polyhedrons
  * QuickMeasure-main
  * GDML 1.8.0
  * offline-documentation
  * Manipulator 1.4.9
  * fasteners 0.4.53
  * lattice2 1.0.0
  * CurvedShapes 1.0.4
  * toSketch 1.0.1
  * Help 1.0.3
  * Curves 0.6.5
[/code]
```

### Subproject(s) affected?

None

### Issue description

NURBS circular arc curves are incorrectly trimmed.  They are trimmed using the BSpline parameter - which only approximately maps to angle.  A python algorithm fix is provided in the forum thread - but the problem lies in the C++ code referenced there. [https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geometry.cpp#L2262](url)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
Oh, I didn't realize there is a ticket for it. Yes, it's fixed now.
