### ISSUE TITLE
[Issue] [FEM] transparency of pipeline objects is visually lost

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#8485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
[/code]
```

### Subproject(s) affected?

FEM

### Issue description

- open this FEM file: 
[FEM-selection-bug.zip](https://github.com/FreeCAD/FreeCAD/files/10735410/FEM-selection-bug.zip)

result: the Warp filter is displayed without transparency

- now double-click on it in the tree view

result: as soon as the dialog pops up, the transparency is visible

- now press in the dialog OK
- do a single left-click on the 3D view
- do another single left-click on the Warp vector object in the tree view

result: the transparency is again lost

This bug only occurs for objects that don't have a field selected to color the object.
One often needs uncolored transparent objects. Especially for deformations, one uses the main pipeline object transparent and uncolored to show the initial shape of the body in addition to the deformation result. Therefore this bug should be fixed.

(I tried already but could not yet find the cause. @wwmayer , you implemented kindly last year the transparency handling. Could you maybe have a look?)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
```
from pivy import coin
node = Gui.ActiveDocument.WarpVector.RootNode

act = coin.SoSearchAction()
act.setType(coin.SoMaterial.getClassTypeId())
act.setInterest(coin.SoSearchAction.FIRST)
act.apply(node)
path = act.getPath()
found = path.getTail()

found.transparency.getValues() # [0.0]
Gui.ActiveDocument.WarpVector.Transparency # 67
```

After double-clicking:
```
found.transparency.getValues() # [0.6700000166893005]
Gui.ActiveDocument.WarpVector.Transparency # 67
```

The transparency is reset in ViewProviderFemPostObject::WriteColorData
