### ISSUE TITLE
OpenSCAD "Clear" button is not undoable

### ISSUE THREAD

**Issue by jempabroni** [FreeCAD/FreeCAD#8576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Arch Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: makepkg
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.9, Qt 5.15.8, Coin 4.0.1, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

OpenSCAD

### Issue description

When using the OpenSCAD workbench, you can enter some OpenSCAD code in the "Add OpenSCAD Element" text box.

Ctrl+Z, Ctrl+Shift+Z, etc all work. However, if you hit Clear, you lose everything you typed in the box, and you cannot undo Clear. It seemed like this button would wipe out the 3D models in the viewer, but it actually just wiped out the text in the OpenSCAD Element code box. This is unintuitive.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
So really two Issues here, right?
1. Button name needs to be something like "Clear code" or something.
2. Clearing should be undo-able.
