### ISSUE TITLE
[Issue] Load function of Add OpenSCAD Element OpenSCAD work fails

### ISSUE THREAD

**Issue by KeithSloan** [FreeCAD/FreeCAD#8605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * ImportNURBS 1.1.0
  * ImportExport_3DM 0.1.0
  * DynamicData 2.46.0
  * Pyramids-and-Polyhedrons
  * occi-freecad-plugin 0.1.0
  * GDML 2.0.0
  * Design456 0.0.1
  * Alternate_OpenSCAD 1.0.0
  * toSketch 1.0.1
  * Curves 0.6.6
[/code]
```

### Subproject(s) affected?

None

### Issue description

With OpenSCAD workbench active use Add OpenSCAD Element icon.

With the "Add OpenSCAD Element" Panel open, click on "Load"

Fails with

````
10:37:36  Traceback (most recent call last):
10:37:36    File "/Applications/FreeCAD.app/Contents/Resources/Mod/OpenSCAD/OpenSCADCommands.py", line 423, in loadelement
10:37:36      filename, filter = QtGui.QFileDialog.getOpenFileName(parent=self.form, caption='Open file', dir='.', filter='OpenSCAD Files (*.scad)',selectedFilter='',option=0)
10:37:36  AttributeError: PySide2.QtWidgets.QFileDialog.getOpenFileName(): unsupported keyword 'option'
````

### Anything else?

Thought there was a bug reported the other day with a problem with the "Save" Button.

Question is why do we see these regressions in functions where there is not any obvious change in function?

Are these problems due to changes in the PySide2 library? and if so how do we stop these problems being repeated. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Fixed by https://github.com/FreeCAD/FreeCAD/commit/a79b397e85ed6031f7faf4659720b253787ddcf4
