### ISSUE TITLE
[Feature Request] Add the outside of the Sketch on PD (related to #8706)

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#8710]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

Per @FlachyJoe's comment (https://github.com/FreeCAD/FreeCAD/issues/8706#issuecomment-1449918242) this feature would compliment #8706 

### Subproject(s) affected?

PartDesign

### Idea description

![image](https://user-images.githubusercontent.com/4140247/222469511-e06e7ceb-3f4d-4292-8782-eb4c5285f5b7.png)

This is a similar idea to the #8706
However, the idea is to pad (or add mass) from outside of a Sketch.

The existing design would be used as a bounding box between the Sketch and the infinity.
In this way, it would not work if used in as the First feature of the Body.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
It's a stronger case if you provide an use case for this feature on what difficulty it would be solving, according to the new contribution process an issue (including feature requests) should be described in terms of a problem that has to be solved, in that spirit please describe what situation is difficult when this feature is not present?

Do note please that I am not advocating against this feature but merely asking for good justification to improve the request.

**Comment by leoheck** [comment]
Sure. I don't have any use case for this. I just mentioned it  since it is a complementarity case of the other issue. I created this to remove tis discussions from the other issue so we can close it due to the fact I don't know a use case for this.

**Comment by luzpaz** [comment]
Re-opening. Usecase was given by @FlachyJoe in:  
https://github.com/FreeCAD/FreeCAD/issues/8706#issuecomment-1449918242  
https://github.com/FreeCAD/FreeCAD/issues/8706#issuecomment-1450044863

**Comment by adrianinsaval** [comment]
That's not really an usecase

**Comment by leoheck** [comment]
Exactly, that is an example on how it would work. Use case is to show why it is important to waist someone's lifetime to implement this.

**Comment by leoheck** [comment]
The author of the second item/link said this

![Screenshot_20230302-144512](https://user-images.githubusercontent.com/1277920/222509824-b7c52509-d61d-4f6e-ad90-8abca917a9d8.png)

**Comment by luzpaz** [comment]
I linked to @FlachyJoe directly so they could comment. But point taken, closing FR

**Comment by FlachyJoe** [comment]
> I linked to @FlachyJoe directly so they could comment. But point taken, closing FR

I agree. I can't find an useful extrusion of outer sketch.
