### ISSUE TITLE
[Issue] wormgear broken

### ISSUE THREAD

**Issue by apper002** [FreeCAD/FreeCAD#8713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Ubuntu 22.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * freecad.gears 1.0.0
[/code]
```

### Subproject(s) affected?

None

### Issue description

wormgear over 600MM broken

### Anything else?

https://drive.google.com/file/d/1JVgA0-t5sGxAqdt-H7FRAogS-SDm1kav/view?usp=share_link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
I'm going to close this since we can't automatically  transfer from this repository to looooo's -- you'll have to manually create a new issue there.
