### ISSUE TITLE
Mesh Design "Unwrap Mesh" broken in 0.21 ?

### ISSUE THREAD

**Issue by PhiJu5** [FreeCAD/FreeCAD#8741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.32110 (Git)
Build type: Release
Branch: master
Hash: a000dcf60af18f489fff48d29d7f2f4b2092483f
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * AirPlaneDesign 0.4.0
  * CurvedShapes 1.0.4
  * Curves 0.6.8
  * Curves.backup1678010057.868822 0.6.8 (Disabled)
  * fasteners 0.4.55
  * MeshRemodel 1.8919.0
  * Plot 2022.4.17
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

Use attached Unwrap.FCStd (zipped [Unwrap.7z.txt](https://github.com/FreeCAD/FreeCAD/files/10891696/Unwrap.7z.txt)), mesh "Solid" than "Unwrap Mesh" the mesh fails.

```
Traceback (most recent call last):
  File "E:\FreeCad21\Mod\MeshPart\MeshFlatteningCommand.py", line 58, in Activated
    boundaries = flattener.getFlatBoundaryNodes()

Unable to convert function return value to a Python type! The signature was
	(self: flatmesh.FaceUnwrapper) -> std::vector<Eigen::Matrix<double,-1,3,0,-1,3>,std::allocator<Eigen::Matrix<double,-1,3,0,-1,3> > >
```

Did you forget to `#include <pybind11/stl.h>`? Or `<pybind11/complex.h>`,
`<pybind11/functional.h>`, `<pybind11/chrono.h>`, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

Doing same with 020 works.

[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * AirPlaneDesign 0.4.0
  * CurvedShapes 1.0.4
  * Curves 0.6.8
  * Curves.backup1678010057.868822 0.6.8 (Disabled)
  * fasteners 0.4.55
  * MeshRemodel 1.8919.0
  * Plot 2022.4.17
[/code]

### Anything else?

![OK](https://user-images.githubusercontent.com/15790503/222957712-eaf7229a-11ae-4ca2-a6cc-9e198ec6910c.JPG)
![KO](https://user-images.githubusercontent.com/15790503/222957719-d70c3e76-9a3d-4470-a4e8-ac432b246699.JPG)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
> Did you forget to `#include <pybind11/stl.h>`? Or `<pybind11/complex.h>`,
`<pybind11/functional.h>`, `<pybind11/chrono.h>`, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

@donovaly, perhaps these libs were removed in one of the lib 'purges' ?

**Comment by donovaly** [comment]
> @donovaly, perhaps these libs were removed in one of the lib 'purges' ?

No. One must only set in CMake these options
* BUILD_FLAT_MESH
* FREECAD_USE_PYBIND11

After these have been set to True, a complete recompilation might be necessary to get the feature.

**Comment by donovaly** [comment]
@PhiJu5 do you compile by yourself? If not, from where do you get your build?

**Comment by PhiJu5** [comment]
No, download from https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
FreeCAD-0.21.0dev-32110-Installer.exe

**Comment by donovaly** [comment]
> No, download from https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds FreeCAD-0.21.0dev-32110-Installer.exe

Thanks.
I indeed made a mistake once I cleaned the includes. #8799 will fix this.
I will provide a new weekly installer tomorrow with the fix included.

**Comment by donovaly** [comment]
> I will provide a new weekly installer tomorrow with the fix included.

Here it is: https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD-0.21.0dev-32258-Installer.exe
