### ISSUE TITLE
[Draft] Clone doesn't behave as clone

### ISSUE THREAD

**Issue by balrobs** [FreeCAD/FreeCAD#8771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=76559

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.31917 (Git)
Build type: Release
Branch: master
Hash: 4639283b459f9ff9093e289908cc003db8745b82
Python 3.10.9, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3DfindIT.backup1663070439.7435825
  * Assembly3 0.11.4
  * BIM 2021.12.0
  * dodo 1.0.0
  * ExtremeProDark 2.6.4
  * FreeCAD_SketchArch
  * Help 1.0.3
  * Nodes 0.1.17
  * PieMenu 1.2.3
  * ProDarkThemePreferencePack 1.0.0
  * Pyramids-and-Polyhedrons
  * ZolkoBase 0.0.1
[/code]
```

### Subproject(s) affected?

Draft

### Issue description

Clone is not updated with its starting object. 
For further details see the forum discussion.

### Anything else?

Reproduce:
1. Rename [Sketch_Clone.FCStd.txt](https://github.com/FreeCAD/FreeCAD/files/10908401/Sketch_Clone.FCStd.txt) and open in FC
2. Select Sketch
3. change in the property tab the constraint value from 25 to 40.  

Result:  
![image](https://user-images.githubusercontent.com/4140247/223428897-81741c95-2a7c-45ba-829f-1e5f202176ea.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
The second clone is mapped to the second sketch. I think it prevents something, but I fail to see what...
