### ISSUE TITLE
[Arch] Remove the "Untitled" IFC type

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FreeCAD#8774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?p=665093#p665093

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Debian GNU/Linux bookworm/sid (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32205 (Git)
Build type: Unknown
Branch: master
Hash: 8381ea079ddadf7c582dcfafeb8a6f9c4c004108
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * BIM 2021.12.0
  * FreeCAD-NativeIFC 2022.10.20
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

Arch

### Issue description

The IFCType property of Arch object allows for a known IFC type, or "Undefined". The problem is, that Undefined type gets currently mapped to different things on export, depending on the object.

The "Undefined" entry should be removed, to "force" each object to define a valid default type.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@yorikvanhavre will this make it in to v0.21 release ?

**Comment by yorikvanhavre** [comment]
Yes! On it!
