### ISSUE TITLE
[Problem] Sketcher: Element Widget. Checkboxes not clicking correctly.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#8814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.32237 (Git)
Build type: Release
Branch: master
Hash: d27e69bdc9cf42489067ec2fbda8e17a17d35929
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk , OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Sketcher

### Problem description

The Element widget just got new checkboxes to toggle visibility. Same as it was implemented in constraint widget.
However the checkboxes don't work properly. Clicking on the checkboxes don't toggle them on the first try. It first select the row. Then you need to click again.
GeoPoints can't be toggled at all.
Sometimes clicking on one checkbox, toggle another checkbox (last selected it seems).

@abdullahtahiriyo I think you implemented those checkboxes last week?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abdullahtahiriyo** [comment]
There is an issue with the selection of the row. I will need to take a look into it.

**Comment by luzpaz** [comment]
@PaddleStroke is this still an issue ?

**Comment by PaddleStroke** [comment]
Just tested and yes

**Comment by abdullahtahiriyo** [comment]
The current implementation is not good. I would like to address this as part of the changes to the widgets using a proper model-view architecture. Hopefully during this development cycle.
