### ISSUE TITLE
[Issue] Extensions missing edges in some cases

### ISSUE THREAD

**Issue by jffmichi** [FreeCAD/FreeCAD#8915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=76828

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Arch Linux (KDE/plasmawayland)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32246 (Git)
Build type: None
Branch: master
Hash: f1ffaf3ba9a1cdf408334383e0ba5c6767919b2c
Python 3.10.10, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * dodo 1.0.0
  * sheetmetal 0.2.59
  * fcgear 1.0.0
  * fasteners 0.4.24
  * fcgear.backup1663629032.4145591 1.0.0 (Disabled)
  * Assembly4 0.12.4
  * lattice2 1.0.0
[/code]
```

### Subproject(s) affected?

Path

### Issue description

Hello everyone,

The extension feature for Path_Pocket_Shape or Path_Adaptive misses edges in some cases (see attached screenshot and example project file). The edge should be extended all around the selected face.

This is how @Russ4262 describes the origin of the issue:
"The missing edge is Edge7. It gets removed from the wire list when [the call to 'edgesMatchShape()' fails](https://github.com/FreeCAD/FreeCAD/blob/138688d25e6c79ffb5c6712a0b66544df201464f/src/Mod/Path/Path/Op/Gui/FeatureExtension.py#L395) to flip Edge7 properly. I ran into this a while back and tracked it to Path.Geom code. This Path.Geom bug causes extensions to fail in other instances as well (how I found it)."

Thank you all for the great work!

### Anything else?

![extensions_missing_edge](https://user-images.githubusercontent.com/14004750/225703608-393ebf86-ff50-4fa4-b753-540cd48c5cf9.png)

[extensions_missing_edge.zip](https://github.com/FreeCAD/FreeCAD/files/10993891/extensions_missing_edge.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@sliptonic is this on your radar ?
