### ISSUE TITLE
[Feature Request] Support zero length in Linear Pattern

### ISSUE THREAD

**Issue by kerrickstaley** [FreeCAD/FreeCAD#8935]
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=76911

### Subproject(s) affected?

PartDesign

### Idea description

Oftentimes with parametric models you can end up with a degenerate Linear Pattern where Occurrences = 1 and Length = 0. When this happens FreeCAD should just create one instance of the object, as if you didn't create a linear pattern. Instead, it currently throws the error "Pattern length too small".

The work-around for now is to add 1 nm (1e-6 mm) to your Length, but it's a little ugly.

The Occurrences = 1 issue was recently fixed, see https://github.com/FreeCAD/FreeCAD/issues/7791 .

### System info
Arch Linux latest
FreeCAD latest Git build (c4b63bc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Do you mind opening a forum thread (and bi-bidirectionally linking it) to attract more attention to this FR ?

**Comment by kerrickstaley** [comment]
@luzpaz done

**Comment by luzpaz** [comment]
@kerrickstaley can you please ask 'Jolbas' what their github handle is so I can assign them this ticket ?

**Comment by Jolbas** [comment]
Jolbas is Jolbas here too

**Comment by Jolbas** [comment]
The issue can be closed. PR https://github.com/FreeCAD/FreeCAD/pull/9111 is merged.
