### ISSUE TITLE
[Issue] PartDesign: (extrude) Pad inward taper angle orientation selection

### ISSUE THREAD

**Issue by tbMaker1** [FreeCAD/FreeCAD#8949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.32362 (Git)
Build type: Release
Branch: master
Hash: 45401e30ce29c8a8c66bced6d2db216c96227289
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
[/code]
```

### Subproject(s) affected?

PartDesign

### Issue description

(Issue was modified to Feature Request to avoid overlaping with other issue.)

Currently, in version 20.2, the outward pad taper angle can be set positive or negative.

The inward taper angle direction, on the other hand, is fixed in one direction.

Or it can be useful to be able to have inward taper angle either parallel or opposite to the outward taper angle direction.

An extra parameter in the Pad extrude menu could be useful to be able to select the direction for inward taper.

### Anything else?

![TaperAngleCorrected](https://user-images.githubusercontent.com/128159531/226114940-6f7af7d4-109d-4457-b4c9-166dac3e8ec7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
isn't this a duplicate issue?

**Comment by tbMaker1** [comment]
Yes and no. It was not only about the other bug (which is more than just single edge issue), it was about the possibility to adjust the orientation as needed.

**Comment by adrianinsaval** [comment]
In that case this should have been made as exclusively about adjusting orientation

**Comment by tbMaker1** [comment]
But adjusting orientation per internal feature would not have been the same topic either (because much more complex and probably not adequate).
Here, the simplification assumed was that all internal feature would be in one way or the other. 
Therefore the implication that the discrepency could/would be removed.

**Comment by adrianinsaval** [comment]
sorry if I wasn't clear but that is not what I meant, what I mean is that we should leave the problem with circles in it's own issue as it is not related to this one. Make it exclusively about allowing to choose to have parallel or opposite orientation.

**Comment by tbMaker1** [comment]
Ok
