### ISSUE TITLE
Admin Privileges Retained when Launched after Installation (windows)

### ISSUE THREAD

**Issue by xeluior** [FreeCAD/FreeCAD#9030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Issue description

Steps to Reproduce:

1. FreeCAD 20.2 x64 Windows installer on Windows 10
2. Accept UAC prompt
3. Select either current user only or system-wide
4. After install, check the Launch FreeCAD box

After the above steps, I noticed by network drives were not bound in the Open File dialog, which Windows unbinds network drives for applications running as Admin. I then verified the privileges by Save As... and saving to a location in Program Files that only Administrators had write privileges to. Closing and relaunching the application downgrades its privileges as expected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
> FreeCAD 20.2 x64 Windows installer on Windows 10
> Accept UAC prompt

By default FreeCAD is installed for the current user only. If you explicitly call for accelerated privileges, you of course get them.

I wonder that you wonder to end up with admin privileges despite you even entered your admin password for UAC.

**Comment by donovaly** [comment]
> Attempting to run the Windows installer always shows the UAC prompt. The selection for single-user or system-wide install happens afterwards.

If you always get the UAC prompt, this means you are an admin (have admin privileges). But then of course FreeCAD has admin privileges too.

If you are not admin and get the UAC, what is you Windows version and what what installer did you use?
If you use the latest Windows installer "FreeCAD-0.20.2-WIN-x64-installer-3.exe" from our download page, you only get the UAC prompt if you either execute the installer with admin privileges or of you already admin. (Tested with latest Win 10 professional and 11 professional).

> I expected this would downgrade the user privileges which it did not.

I am confused. You are admin, started the install as admin and you expect to get FreeCAD running without admin privileges. That is impossible. FreeCAD cannot have a non-admin privileges if the user has already admin privileges.

**Comment by xeluior** [comment]
> FreeCAD cannot have a non-admin privileges if the user has already admin privileges.

This is verifiable false. Please understand that in Windows there is a difference between being an admin (that is, being logged in as an account with admin privileges) and running a program as Admin.

Running any program while you are an administrator does not automatically grant it administrator rights. The rights have to be explicitly granted (Run As Administrator) or asked for (UAC Prompt). You can verify this yourself by running, for example, notepad and trying to save a file to C:\Program Files. Regardless of if you are an admin or not, your access will be denied. Then, run it using the Run As Administrator context menu option and you will be allow to save it.

When running FreeCAD normally (that is, after it has been installed and you launch it from the start menu or elsewhere), it correct uses the non-privileged role most normal applications use (the first instance of notepad in the above example). However, when it is launched at the end of the installation, it retains the admin rights granted to the installer, ie. without you having to explicitly use the Run As Administrator option.

> If you are not admin and get the UAC, what is you Windows version and what what installer did you use?

I have been testing this with an admin account. I just created a non-admin account to test and it does work as you describe.

**Comment by donovaly** [comment]
> You can verify this yourself by running, for example, notepad and trying to save a file to C:\Program Files. Regardless of if you are an admin or not, your access will be denied

Does work here as admin (win 10 professional)

However, since you are an admin, you know that when you give a program rights via UAC, it run with these rights.
The option to run FreeCAD is there for admins to check if everything went well, especially when they installed for all users. Nobody forces you to run FC with UAC, it is up to you as admin.

(Besides this, if you don't want to install FC for all users, why are you the installing it as admin? This makes no sense to me. The admin account is there to administrate, nothing else. I hope you don't use your admin account to browse the web, write Word files etc.)

**Comment by xeluior** [comment]
> The option to run FreeCAD is there for admins to check if everything went well

It appears we are now on the same page about the behavior.

> The admin account is there to administrate, nothing else.

It is extremely common for users to have an administrator account for everyday tasks, especially on personal computers.

Both the above taken together, I believe the real issue here is that administrator accounts are forced to accept the UAC before proceeding with the installation. The installer appears to detect that the account running it is an admin and displays the UAC, which, if rejected cancels the installation. Administrators should be able to perform single-user install without needing to grant the installer elevated privileges.

**Comment by donovaly** [comment]
> Administrators should be able to perform single-user install without needing to grant the installer elevated privileges.

This is a valid point. I once had this (the installer originated from the project lyx.org 10 years back and was improved over the years). But the feedback I got from admins was "I am admin to administrate". They don't install things for themselves.

> It is extremely common for users to have an administrator account for everyday tasks, especially on personal computers.

Extremely? I haven't seen this for years now. In the  companies, nobody except the IT guys have admin privileges. Also in sport associations and the like where I am active people have admin permissions. I recently bought a Win 11 laptop and it also came with an admin and a user account and they told me I should only use the admin account to install things, I should not use a browser as admin if not explicitly necessary.
I remember old Win Vista times where the basic Windows version "Home" came with one admin account only.

However, I have to decide for admins:
Should the installer by default be launched with admin privileges or not. If not, then professional admins will complain for sure (they did in the past)
Over the time I just got less complaints about UAC for admins than admins who complained that they have to explicitly request UAC while already being the admin.

**Comment by xeluior** [comment]
A possible middle ground: the installer runs initially without prompting for admin. If the user selects install for all users, then they get the UAC prompt. That way, admins (which, in my experience, outside of corporate networks, most people are) can still install it as single-user without needing to grant the installer admin privileges, meanwhile IT admins can install it without having to remember to "Run As Admin".

**Comment by donovaly** [comment]
Yes, this should be doable. However, right now I won't have time -> put it on my todo list when we release FreeCAD 0.20.3
