### ISSUE TITLE
[Problem] Crash by clicking "print preview" menu and changing the paper orientation to horizontal

### ISSUE THREAD

**Issue by bilcam36** [FreeCAD/FreeCAD#9072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell

```

### Subproject(s) affected?

Other (specify in description)

### Problem description

file menu

when i click the "print preview" menu and than changed the paper to horizontal the program close itself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
please post full version information. At the bare minimum you must say what OS you are using

**Comment by AjinkyaDahale** [comment]
Cannot reproduce with 

```
OS: Ubuntu 22.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32499 (Git)
Build type: Release
Branch: core-detect-new-save
Hash: 1e5fa5de6057014518cb89585f7ac575321181f9
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: English/India (en_IN)
```

**Comment by xtemp09** [comment]
I cannot reproduce the crash with the latest stable and the latest master version on Windows 10 and on Ubuntu. Perhaps, it depends on a printer or a file. Though, I can't figure out why the page turned vertical, if it were horizontal and nothing toggled the radiobutton to turn it into portrait layout.

Perhaps, logging will shed some light on this.

**Comment by luzpaz** [comment]
@bilcam36 please provide Full [About](https://wiki.freecad.org/About) info please!

**Comment by luzpaz** [comment]
@bilcam36 ping

**Comment by adrianinsaval** [comment]
I can't reproduce the crash, but the behavior is buggy, the portrait/landscape state of the preview page is not kept in sync. This can also be observed in OP's video

```
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: C/Default (C) [ OS: Spanish/Paraguay (es_PY) ]
Installed mods: 
[/code]
```

**Comment by adrianinsaval** [comment]
nobody else seems to be able to reproduce and we got no response with further info from @bilcam36, I will close this as it is not actionable as is. Feel free to reopen if you are still experiencing this and can provide us more information.
