### ISSUE TITLE
[Issue] [WIP] TopoNaming Phase 2 (card 3 of 5) - ComplexGeoData dressing

### ISSUE THREAD

**Issue by JohnAD** [FreeCAD/FreeCAD#9116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.20.14555 (Git shallow) Snap 222
Build type: Debug
Branch: master
Hash: d4feb6578398d51eaf56cd794e8d3e2e000bea64
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Issue description

> The toponaming algorithm needs the basic object to support element names.

## description

This step relies on card 2 being done first.

The "core object" (from a toponaming point of view) for expressing/storing "element" names is the ComplexGeoData class.

Add functions to this class (in complexgeodata.h / .cpp) so that the workbenches (mainly Part and Sketcher) can do that storage and expression.

These functions will NOT be called yet. That will be dones in Phase 3. Instead we will be adding unit testing to ensure they are ready to be used.

For context, see issue #8432

## notes

Do not worry about the save/restore functions, that is in Phase 4.

The following are the public functions that need to be written per the TopoNaming branch:

- `static const std::string &externalTagPostfix();  // link and part design wb`
- `IndexedName getIndexedName(const MappedName & name, ElementIDRefs *sid = nullptr) const; // used in gui and part wb`
- `MappedName getMappedName(const IndexedName & element, bool allowUnmapped = false, ElementIDRefs *sid = nullptr) const; // used in app, part wb, and gui`
- `MappedElement getElementName(const char * name, ElementIDRefs *sid = nullptr, bool copy = false) const; // used in many places incl gui and part wb`
- `std::vector<std::pair<MappedName, ElementIDRefs>> getElementMappedNames(const IndexedName & element, bool needUnmapped=false) const; // part wb`
- `MappedName setElementName(const IndexedName & element, const MappedName & name, const ElementIDRefs * sid = nullptr, bool overwrite = false); // part/sketcher/py etc`
- `void setMappedChildElements(const std::vector<MappedChildElements> & children); // part wb`
- `void hashChildMaps(); // part wb`
- `bool hasChildElementMap() const; // part wb`
- `virtual void reTagElementMap(long tag, App::StringHasherRef hasher, const char *postfix=0); // Link`
- `long getElementHistory(const char *name, MappedName *original=0, std::vector<MappedName> *history=0) const; // part wb / topo shape`
- `long getElementHistory(const MappedName & name, MappedName *original=0, std::vector<MappedName> *history=0) const;  // part wb / gui`
- `void encodeElementName(char element_type, MappedName & name, std::ostringstream &ss, ElementIDRefs *sids, const char* postfix=0, long tag=0, bool forceTag=false) const; // py`
- `char elementType(const Data::MappedName &) const; // part wb`
- `char elementType(const Data::IndexedName &) const; // py`
- `virtual ElementMapPtr resetElementMap(ElementMapPtr elementMap=ElementMapPtr()); // py`
- `std::vector<MappedElement> getElementMap() const; // py`
- `void setElementMap(const std::vector<MappedElement> &elements); // py`
- `size_t getElementMapSize(bool flush=true) const; // py, part & part design wb`
- `virtual std::vector<IndexedName> getHigherElements(const char *name, bool silent=false) const; // geoFeature`
- `virtual std::string getElementMapVersion() const; // py, part wb`
- `virtual bool checkElementMapVersion(const char * ver) const; // propertygeo`
- `static int findTagInElementName(const MappedName & name, long *tag=0, int *len=0, std::string *postfix=0, char *type=0, bool negative=false, bool recursive=true); // part wb`
- `void traceElement(const MappedName &name, TraceCallback cb) const; // part wb`
- `virtual void flushElementMap() const; // part wb (toposhape)`
- ` ElementMapPtr elementMap(bool flush=true) const; // part wb (toposhape)`

I have added comments to the above with details of where these will be called from just in case the comments and code are not descriptive enough.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zolko-123** [comment]
when this is implemented, will we be able to `setElementName()` of a geometrical element (Face, Edge ...) from the Python console (or otherwise) ?

**Comment by JohnAD** [comment]
I've got a "visibility" card I'm writing up that will let you see the empty names. But since nothing is being written to until Phase 3, so I had not planned on anything more that that.

At Phase 3, you will be able to start doing manipulation; very likely similar to what you want. As to whether that is a good idea yet is not known :), but I plan on adding the ability to do it. In Phase 4 we will actually start using the element names; that is the first point in which it will actually make a difference to anything. FreeCAD will starting getting slower in that phase. In phase 5 we start optimizing and making adjustments.

**Comment by adrianinsaval** [comment]
> As to whether that is a good idea yet is not known :)

From the python console by a random user likely not, but addons need a way of using the algorithm and registering their operations.

If their operations make direct use of Part API do they automatically get the toponaming from Part?

**Comment by JohnAD** [comment]
@adrianinsaval  I'm hesitant to say "absolutely yes" since I/we are learning as we go. But that is what Sketcher is doing and it should be generally possible.

**Comment by Pesc0** [comment]
As noted here https://github.com/FreeCAD/FreeCAD/pull/9175#issuecomment-1567567390, it seems `ComplexGeoData::getMappedChildElements` is not called anywhere, so it can be removed.
