### ISSUE TITLE
[Issue] [WIP] TopoNaming Phase 2 (card 4 of 5) - SketchObject dressing

### ISSUE THREAD

**Issue by JohnAD** [FreeCAD/FreeCAD#9119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.20.14555 (Git shallow) Snap 222
Build type: Debug
Branch: master
Hash: d4feb6578398d51eaf56cd794e8d3e2e000bea64
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

## description

This step relies on card 2 being done first.

The "core object" (from a toponaming point of view) for expressing/storing "element" names for the Sketcher Workbench is the SketchObject class.

Update `SketchObject` so that `App::DocumentObjectExecReturn *SketchObject::execute(void)` could call a function that applies naming. But don't actually call that function yet. The TopoNaming branch calls this `buildShape`.

Examine other changes made in the the TopoNaming branch classes. Some changes are needed when naming is added. Others are simply refactoring not related to TopoNaming. Make best judgement.

There is a solver added to this (see class `class SketchObject::GeoHistory` and other code). Again, don't call this in production, but support the function with unit testing.

The goal is to add the naming algorithm functions, but not actually do the naming yet.

For context, see issue #8432

## notes

```text
Mod/Sketcher/App/ExternalGeometryExtension.h
Mod/Sketcher/App/ExternalGeometryFacade.cpp
Mod/Sketcher/App/GeometryFacade.cpp
Mod/Sketcher/App/SketchGeometryExtension.cpp
Mod/Sketcher/App/SketchObject.cpp
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AjinkyaDahale** [comment]
I could take this up once dependencies are done.

**Comment by abdullahtahiriyo** [comment]
buildshape is a meaningful difference in responsibility.

In FreeCAD master Sketch.cpp (solvedSketch) has the responsibility to create the shape from the latest solved geometry:
```Shape.setValue(solvedSketch.toShape());```

In RT's, this is moved to SketchObject.

This decision makes sense as SketchObject will implement the toponaming and the shape needs to be created with toponaming in mind.

I do not see anything off.

**Comment by AjinkyaDahale** [comment]
Seems the changes are all smooshed in https://github.com/FreeCAD/FreeCAD/commit/8ee6153f4b6e0b298dce1703ac8553e00e5f7dbc#diff-b9dbc09c2c4b8417d6df9b1640fe0b24441cf026658dd5220d8917aa1ebcf356. The problem is that some of these changes seem to be part of "phase 3", and others may not even be part of toponaming...

**Comment by abdullahtahiriyo** [comment]
I am not sure I fully understand your question. Let me know if I am not replying to it.

If you mean that Sketch.cpp does not have any change. You are right. 

However, the responsibility to build the shape is moved from Sketch.cpp to SketchObject.cpp, because the function that is called to build the shape is no longer the one of Sketch.cpp, but a new one in SketchObject.cpp. Take a look to ```SketchObject::execute(void)```.

If the question is whether Sketch.cpp needs changes because its method ".toShape" is no longer necessary. I have not compiled it, but from a visual inspection it is probably the case.

**Comment by AjinkyaDahale** [comment]
@abdullahtahiriyo thanks. Those were exactly my questions: a step has been moved to SketchObject from Sketch but there is no change that should have been. Now that you put it this way, we probably surely can remove code from `Sketch.cpp`, but I believe that should not.be happening at this point. In this phase, we are building the steps and tests to be able to perform the action (i.e. add the method needed) but not perform it (i.e. we will not call the method in execute).

**Comment by abdullahtahiriyo** [comment]
@AjinkyaDahale 

I am glad to be of help.

At this moment, I guess, there will be a commented out call to the new method and a call still to the old one, eventually the commented lines will switch and ultimately the method of Sketch.cpp will disappear... not trying to rush things :smiley:

**Comment by AjinkyaDahale** [comment]
@JohnAD the method we plan to implement here requires methods like `Part::TopoShape::makEWire()` (note the capital E), but they seem to not be part of any previous phase. Did I/we just missed this, or are these going to be replaced by something totally different?

**Comment by JohnAD** [comment]
In phase 3 we will actually start applying the naming to the objects. In phase 2, we were just going to "add the member variables". But not do the actual naming mechanism as that would create a performance hit prior to the next major release. I did not realize that Sketcher would be calling functions like `makeEWire`. I thought that was just the Part workbench. Even so, we will be likely adding those functions in phase 3.

BTW, it does appear that we can unit test naming prior to using the algorithm by providing the ElementMap class a "mocked" history for it to working. Card 3, which simply adds ElementMap field to ComplexGeoData will be fairly simple because it isn't much more than adding a few member variables.

Our first attempt at such mocking can be seen here: https://github.com/Pesc0/FreeCAD/pull/7
