### ISSUE TITLE
[Issue] Build failing due to HDF5 upstream bug

### ISSUE THREAD

**Issue by Pesc0** [FreeCAD/FreeCAD#9132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
--
```

### Subproject(s) affected?

None

### Issue description

Build failing with:
```
CMake Error in src/3rdParty/salomesmesh/CMakeLists.txt:
  Imported target "VTK::hdf5" includes non-existent path

    "/build/hdf5-openmpi/src/hdf5-1.14.0/src/H5FDsubfiling"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Upstream bug: HDFGroup/hdf5#2422

Is there any temporary workaround?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@wwmayer when you have a moment, would you kindly look in to this? TIA!

**Comment by yorikvanhavre** [comment]
So this can be closed I guess... Please reopen if needed!
