### ISSUE TITLE
[Issue] sqrt with unit mm doesn't seem to work

### ISSUE THREAD

**Issue by ctron** [FreeCAD/FreeCAD#9158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.6, Qt 5.15.8, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/Ireland (en_IE)
Installed mods: 
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

Expressions

### Issue description

I have a value of  `15mm` with an alias of `foo` in a spreadsheet. I want to use `sqrt(<<parameters>>.foo)`.

The result is an error: `<Spreadsheet> Cell.cpp(645): myfile#Spreadsheet.H14: All dimensions must be even to compute the square root.
in expression: sqrt(15mm)`

This can also be reproduced by just using `sqrt(15mm)`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
What unit would you expect to result from taking the square root of a length?

**Comment by xtemp09** [comment]
`sqrt(15 mm^2)` gives correct result.

**Comment by chennes** [comment]
I'm going to close this as I wouldn't expect it to work: taking the square root of an area makes sense, and yields a length. But taking the square root of a length yields some non-physical unit, and I believe FreeCAD is right to reject it.

**Comment by ctron** [comment]
So assuming I have a spreadsheet with a length (in mm), and want to calculate the diagonal of a square, how would I do this?

Normally I would use: `d = sqrt(2 * <<parameters>>.side)` But if `side` has a unit (like mm), it won't work in FreeCAD.

**Comment by chennes** [comment]
That's not the right equation: starting from a^2 + b^2 = c^2, you need 2 * sqrt(2 * <<parameters>>.side * <<parameters>>.side).

**Comment by mfro0** [comment]
> Normally I would use: `d = sqrt(2 * <<parameters>>.side)` But if `side` has a unit (like mm), it won't work in FreeCAD.

to get rid of any unwanted unit in an expression just divide by it:
`5 mm / 1 mm = 5`

**Comment by ctron** [comment]
Which brings me back to my original report, that it is not necessary in this case.

But as @mfro0 already suggested, there is a way to work around the (IMHO unnecessary limitation) of FreeCAD.

**Comment by drf5n** [comment]
> So assuming I have a spreadsheet with a length (in mm), and want to calculate the diagonal of a square, how would I do this?
> 
> Normally I would use: `d = sqrt(2 * <<parameters>>.side)` But if `side` has a unit (like mm), it won't work in FreeCAD.

If `<<parameters>>.side = 5`, then that would give `d = sqrt(2*5) = 3.162278`  which is not the `7.071` length of the diagonal of a square of `side=5.`  Your formula happens to work numerically for side=1 only because `1^2 = 1` so  `2*1^2=2,` for non `side=1` cases, that isn't true.
