### ISSUE TITLE
[Problem] Sketcher Marker Size setting is misplaced

### ISSUE THREAD

**Issue by sliptonic** [FreeCAD/FreeCAD#9206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
N/A
```

### Subproject(s) affected?

None

### Problem description

The General / 3D View / Rendering section has a setting for 'Marker size'.  This setting controls the size of vertices in the Sketcher workbench.  

![2023-04-06_10-47](https://user-images.githubusercontent.com/538057/230430913-9ce96516-be26-4aa3-be81-3a4006c98839.png)

This setting should be moved to the Sketcher Group in the Display Tab
![2023-04-06_10-49](https://user-images.githubusercontent.com/538057/230431447-339f39dd-0a73-45d7-bca0-864033f48b65.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
I believe the reason that _Marker Size_ is in Display>3D View is due to the number of workbenches that specific _View_ parameter is used:
Fem, Mesh, PartDesign, Path, Robot and Sketcher so the tooltip is misleading to say the least so change the tooltip but it shouldn't be moved to a specific Wb when it's used elsewhere.

**Comment by benj5378** [comment]
> Fem, Mesh, PartDesign, Path, Robot and Sketcher so the tooltip is misleading to say the least so change the tooltip but it shouldn't be moved to a specific Wb when it's used elsewhere.

@sliptonic any comments on this? Should we just change the tooltip?

**Comment by luzpaz** [comment]
bump

**Comment by howie-j** [comment]
I can at least verify that MarkerSize changes TechDraw vertices, so perhaps this setting is correctly placed after all.
Updated tooltip: https://github.com/FreeCAD/FreeCAD/pull/10215
