### ISSUE TITLE
IMAGE WORKBENCH MISSING

### ISSUE THREAD

**Issue by Jasonv310** [FreeCAD/FreeCAD#9212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
I now have the image workbench missing since I upgraded to .21
```

### Subproject(s) affected?

None

### Issue description

I now have the image workbench missing since I upgraded to .21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
The image workbench functionality has been integrated into the core of FreeCAD. To load an image, use File->Open or File-> Import. To control its placement, double-click on it in the tree and use the Task panel.

**Comment by xtemp09** [comment]
@chennes, the wikipedia does not mention the removal. [^1]
 [^1]: https://wiki.freecad.org/Image_Workbench

**Comment by Jasonv310** [comment]
What is the easiest way to scale my pic or item? I get to the scale part but it wont let me go past 0 on the settings and my project is already to big. 
Jason "Cueball" VernonPresidentPunishers LEMC Hellbranch Ohio ***@***.*** 

    On Friday, April 7, 2023 at 09:47:22 AM EDT, xtemp09 ***@***.***> wrote:  
 
 


@chennes, the wikipedia does not mention the removal. 1

Footnotes
   
   -    
https://wiki.freecad.org/Image_Workbench  ↩
