### ISSUE TITLE
[Issue] Pref General: Useless General groupbox.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#9255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
0.21
```

### Subproject(s) affected?

None

### Issue description

There is a General groupbox holding all the items of the General tab. This is redundant and cluttering the view.

![image](https://user-images.githubusercontent.com/19984177/231792771-e6f24aaa-748f-4e52-80ac-f622d56d9464.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Yeah, axe it.

**Comment by adrianinsaval** [comment]
fixed by #9260
