### ISSUE TITLE
[Issue] Navigation cube font size strange behaviour

### ISSUE THREAD

**Issue by Jolbas** [FreeCAD/FreeCAD#9262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?p=674532#p674532

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.21.0.31917 (Git)
Build type: Release
Branch: master
Hash: 4639283b459f9ff9093e289908cc003db8745b82
Python 3.10.9, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * kugghjul.py
  * dxf-library
  * fcgear 1.0.0
  * __pycache__
  * sheetmetal 0.2.61
  * tida.py
  * Curves 0.6.8
  * Assembly4 0.12.7
[/code]
```

### Subproject(s) affected?

Core

### Issue description

• The font size setting of the navigation cube does not match the size of the navigation cube. Setting the font size to 100 gives a 4 times smaller font. Image showing cube size 250 and font size 250
![Skärmavbild 2023-04-13 kl  19 12 08](https://user-images.githubusercontent.com/39026960/231834758-b186b5ac-4be7-48d5-a9ec-1f2ca592253d.png)
• Setting a too big font size makes the text beed over the edges of the face it should lie on.
Image showing cube size 250 and font size 900
![Skärmavbild 2023-04-13 kl  19 08 02](https://user-images.githubusercontent.com/39026960/231834055-949ee582-71b7-4f2d-a33d-908003a0be7e.png)
• If tuning the font size to match the cube size and then change the cube size you have to tune the font size again. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jolbas** [comment]
I have an almost done fix for this. The font size is instead set as percentage of cube size and labels that doesn't fit is individually downsized until they fits the face.

**Comment by chennes** [comment]
How does your fix interact with https://github.com/FreeCAD/FreeCAD/pull/9244?

**Comment by ronnystandtke** [comment]
Great, I absolutely love the idea of autoscaling the font size on the navicube.

I see the following variants:
- individual autoscaling on every face
  - most probably resulting in different font sizes on every face
  - some people don't seem to like it (see forum discussion)
- synchronized autoscaling
  - the face with the longest text determines the font size
  - same font size on every face
  - a bit of wasted space
  - maybe visually more pleasing
- manual font size

I would probably default to the second option but offer the other variants in the preferences.

**Comment by adrianinsaval** [comment]
I think the second option makes the most sense, we can then easily use 100 as the default value and it would look good regardless of platform or selected font. Offering 3 options seems overkill.

**Comment by Jolbas** [comment]
I would like to keep the option to make labels as big as possible (100%)
![Skärmavbild 2023-04-15 kl  00 16 24](https://user-images.githubusercontent.com/39026960/232164275-7762b134-8fbf-4b50-a2d2-9be59de02c55.png)
I think I prefer something like this to make it more readable without having a massive TOP label (25%)
![Skärmavbild 2023-04-15 kl  00 15 32](https://user-images.githubusercontent.com/39026960/232164796-cfc88711-b2f9-4f34-bda8-c2198aa1d5e4.png)
With my suggestion it wouldn't be hard to make all labels have the same font size (18%)
![Skärmavbild 2023-04-15 kl  00 40 56](https://user-images.githubusercontent.com/39026960/232166472-8819afee-f53e-4b7a-9b53-73246b973b6e.png)
I don't really get why you want to ditch the flexible font size in favour for the option to undersize the font (5%)
![Skärmavbild 2023-04-15 kl  00 17 22](https://user-images.githubusercontent.com/39026960/232165053-f3201acd-824b-4e3f-879a-9a0505c438cf.png)
How about removing the numbers from the setting and instead choose between the following?
- individual autoscaling on every face
- individual but set maximum size so that the median length word fits
- synchronized autoscaling
Those options would result in the three first images.

Note: Changed REAR to BOTTOM to get longest and shortest word in the same picture

**Comment by adrianinsaval** [comment]
Ok, I think I got a little confused, the 25% option looks pretty good actually. And since the number is not very meaningful when it is dynamically ignored I think you are right that it might not be worth showing.
And that leads me to the question... Do we even need an option here? The font size option now exists because users need it to adapt to their cube sizes and font of choice, with an automated way of getting sane font sizes I think we can just get rid of the option altogether. What usecase is there for changing the font size separately?

So I now propose, we just set it to 25% and get rid of the GUI to change this.

**Comment by Jolbas** [comment]
Sure. I like your proposal.

**Comment by Jolbas** [comment]
I have now tested a non GUI parameter called FontZoom.
 1.0 = The labels are individually maximized
 0.0 = The longest label is maximized. All labels have the same font size 
Values in between controls the maximum font size
A negative value is possible and reduces the font size further.
Default value 0.3 reduces the size of "BOTTOM" and with some fonts also "FRONT" in the default label set
I think this works very well.
