### ISSUE TITLE
[Bug] Std_Import: problem importing image if path contains a single quote.

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#9306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### GitHub discussion

https://github.com/FreeCAD/FreeCAD/pull/8955#issuecomment-1507093822

### Version

0.21 (Development)

### Full version info
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32785 (Git)
Build type: Release
Branch: master
Hash: 010e2ca37771fb9d89d513869baf520f89090204
Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Core

### Issue description

There is a problem when importing an image if the path contains a single quote:
```
16:39:07  <string>(1)<class 'SyntaxError'>: ('unterminated string literal (detected at line 1)', ('<string>', 1, 86, "App.getDocument('Unnamed').ActiveObject.ImageFile = 'C:/Downloads/Foto's/IMG_8371.JPG'", 1, 86))
16:39:07  App.getDocument('Unnamed').ActiveObject.ImageFile = 'C:/Downloads/Foto's/IMG_8371.JPG'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
@Roy-043 Here's a quick fix specifically for images https://github.com/FreeCAD/FreeCAD/compare/master...Syres916:FreeCAD:patch-78 but you realise this is going to have to be checked against at least VRML, Inventor and many others no doubt? To be honest I'll leave you with it, you can borrow and expand the code as you wish.

**Comment by Roy-043** [comment]
Thanks. But I have no C++ programming experience. So I have to leave this in the hands of others.

**Comment by luzpaz** [comment]
Hi wmayer, do you have any time to address this image import issue ?

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/9431
