### ISSUE TITLE
[Problem] PartDesign datum planes are too opaque by default and significantly obstruct visibility of objects

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD#9391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Arch Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33001 (Git)
Build type: None
Branch: master
Hash: 252c628f9024eff2752d9dacc47edfd99e2c14c1
Python 3.10.10, Qt 5.15.9, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C) [ OS: English/United Kingdom (en_GB) ]
Installed mods: 
  * fasteners 0.4.56
  * Assembly3 0.11.4
  * CfdOF 1.21.7
  * Plot 2022.4.17
  * Curves 0.6.8
  * Defeaturing 1.2.0
  * DynamicData 2.46.0
  * Dracula 0.0.4
  * 3DfindIT 1.2.0
  * SelectorToolbar
  * FC_SU
  * A2plus 0.4.60k
  * Assembly4 0.50.1
  * CurvedShapes 1.0.4
  * sheetmetal 0.2.63
  * AirPlaneDesign
  * Glass
[/code]
```

### Subproject(s) affected?

PartDesign

### Problem description

By default PartDesign datum objects have a transparency of 60% and can quickly clutter the view when several are visible at the same time.
![image](https://user-images.githubusercontent.com/36372335/234361740-6857c227-1ac3-4d25-b911-1159ddafba42.png)

Suggest increasing default transparency to 95%, still visible but not so obstructive anymore:
![image](https://user-images.githubusercontent.com/36372335/234361075-97a435d4-add2-41bf-b45f-ad1dca745942.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0penBrain** [comment]
I feel like so much transparency make it very difficult to catch the relative location of planes vs. objects. :confused:

**Comment by adrianinsaval** [comment]
can you check changing a datum plane's transparency to different values and tell me what's the highest transparency value where you still feel like you can understand relative positions? I'm really unhappy with the current 60% value, it obstructs too much and is specially annoying when you start a sketch on a plane and then have to go and hide the planes before being able to see the part you are working on. For visualizing the position of the plane the outline fells like enough to me.
Here's how it looks on #9393 (not the same as the picture I uploaded here on the issue):
![image](https://user-images.githubusercontent.com/36372335/236407897-f9283866-c733-4798-85a1-1fb53503bdff.png)

**Comment by 0penBrain** [comment]
> can you check changing a datum plane's transparency to different values and tell me what's the highest transparency value where you still feel like you can understand relative positions? 

Did a very quick test with 2~3 datum planes. To me max transparency would be 75%. Over this I'm confused about locations.

> I'm really unhappy with the current 60% value, it obstructs too much and is specially annoying when you start a sketch on a plane and then have to go and hide the planes before being able to see the part you are working on. For visualizing the position of the plane the outline fells like enough to me.

That's another rationale. Maybe the solution here is to enhance the visibility automation so datum objects are automatically hidden when Sketcher enters edit mode (and restored when leaving). ;)

**Comment by adrianinsaval** [comment]
Another related problem is that we are using yellow as default color, this color is usually associated with warnings and it draws too much attention to itself, so it's even more distracting. I think we would benefit from using a cold color instead. Here a datum plane in master branch with 85% transparency and using color #00aa7f
![image](https://user-images.githubusercontent.com/36372335/236410332-79647d70-01b7-4c87-bbf4-ac815a8a2435.png)

**Comment by 0penBrain** [comment]
Still too much transparency for me (just my opinion). About colors and so on, I already proved I'm so bad at it that I won't comment. :)

**Comment by JohnOCFII** [comment]
I think 80-85% transparency looks fine.  IMO, too many preference settings makes long-term maintenance more difficult.

**Comment by luzpaz** [comment]
What is the verdict here ?

**Comment by maxwxyz** [comment]
related: #12584
