### ISSUE TITLE
[Problem] Error message doesn't help me solve the problem (importDWG not finding 3rd party deps)

### ISSUE THREAD

**Issue by StukSteen** [FreeCAD/FreeCAD#9400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
```

### Subproject(s) affected?

File formats

### Problem description

![Screenshot from 2023-04-26 15-49-34](https://user-images.githubusercontent.com/114410968/234598447-87d60b17-910f-4c1e-a58f-3d977134ccb4.png)

Trying to import a .dwg, the errormessage was completely useless to help me solve the problem and get on with my work.

```
14:59:31  QCAD error
14:59:37  QCAD error
14:59:54  QCAD error
15:00:35  QCAD error
15:00:54  QCAD error
15:33:04  LibreDWG error
15:33:33  ODA File Converter not found
15:34:50  QCAD error
```

This message has no value for me as end user. I haven't got a clue if the error originated in my drawing, my system or the software? Could you improve the user experience by providing a bit more information on the type of error and how to solve them? Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Thanks. 
In the meantime @StukSteen, check to see if the path to ODA file converter (3rd party depedency) is correct 
https://wiki.freecad.org/Import_Export_Preferences#DWG

**Comment by luzpaz** [comment]
@Roy-043 maybe we can add a link to the wiki as a hint where to look ? 
https://github.com/FreeCAD/FreeCAD/blob/f9413307e73af97a20f27d53b9f4696584770419/src/Mod/Draft/importDWG.py#L230

**Comment by Roy-043** [comment]
The provided error message is not the result of a single import attempt. 8 import attempts have been made and before each of the last 3 attempts the "Conversion method" preference has been changed. So in this case a link to the preferences would not have helped.

**Comment by Roy-043** [comment]
One of the problems is that currently the code calls a subprocess which can fail because the executable is missing or because the file to convert is faulty. The code is not able to tell the difference.

**Comment by luzpaz** [comment]
> One of the problems is that currently the code calls a subprocess which can fail because the executable is missing or because the file cannot be converted. The code is not able to tell the difference.

@Roy-043 thanks for weighing-in. That's a super important point and something that we should open a ticket for because this would really help end-users understand what is actually occurring and how to possibly fix it themselves before turning to the forum for direct help.

**Comment by Roy-043** [comment]
One way to check if the executable can be found:
`subprocess.Popen((path, "-h"), shell=True)`

Works for LibreDWG (tested) and should also work for QCAD as its support the `-h` argument (untested).
For ODA there seems to be no such argument. Calling the executable without arguments will display a dialog, which you would not want in this case.

Suggested improvements:

1. Find out the path of the ODA executable on macOS and add it.
2. Improve the error messages. A link can simply be displayed as part of the message text. It need not be clickable.
3. The DWG tab in the preferences does not specifically mention that you need to download/install a 3rd party component. A user might select an option from the dropdown list thinking these are built-in. A simple text on the tab would help.

**Comment by luzpaz** [comment]
Per the macOS question, I pinged @ipatch on the forum but not sure they might see it (sorry for the multiple pings ipatch).

**Comment by yorikvanhavre** [comment]
What we could also do is print the subprocess string to be executed as info in the report view. So users could try to execute that string themselves in a terminal, which might help them debugging further

**Comment by Roy-043** [comment]
That was already implemented for the ODA DWG to DXF conversion. I am working on a PR to implement this for the other 2 converters as well.
