### ISSUE TITLE
Draft: ImportDWG 'QCAD error' is too vague and should have more informative output 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#9401]
https://github.com/FreeCAD/FreeCAD/blob/f9413307e73af97a20f27d53b9f4696584770419/src/Mod/Draft/importDWG.py#L243

ref: #9400

**Comment by adrianinsaval** [comment]
why create a new issue? Isn't this the same as the mentioned issue?

**Comment by luzpaz** [comment]
I'll close it if it gets addressed.

**Comment by luzpaz** [comment]
Thanks again Roy!
