### ISSUE TITLE
[Problem] Navigation animations don't always work

### ISSUE THREAD

**Issue by Rexbas** [FreeCAD/FreeCAD#9415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: KDE Flatpak runtime (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git) (and also 0.21)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.6, Qt 5.15.8, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Problem description

Some navigation animations don't work with animations enabled. The animations don't work when using the two arrows above the NaviCube. Also, alternating between the corner and edge of the NaviCube results in maybe one or two frames of animation and feels like it immediately snaps to the selected view. I attached a video that demonstrates this.

I have been working on something to deal with different kinds of navigation animations. A first version, that also fixes the animations, is almost finished so expect a PR soon.

### Anything else?

https://user-images.githubusercontent.com/14298143/234894433-039e478c-4b04-48e6-bebf-c49a26bea4d4.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Have you tested this on development branch ? Navigation cube code just got refactored in #9356

**Comment by Rexbas** [comment]
Yes I have tested it on the development branch and I was aware that the navigation cube got refactored. The navigation cube is, however, not directly related to the animations. The problem is clearly visible when using the navigation cube as described previously.
