### ISSUE TITLE
[Problem] Importing Base geometry from one Path operation to another only takes the first.

### ISSUE THREAD

**Issue by jimzim111** [FreeCAD/FreeCAD#9428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Ubuntu 22.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33029 (Git)
Build type: Release
Branch: path_maintainposition
Hash: 64ff8aa833ae17ead5509edd542fc97eb4d37562
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Path

### Issue description

The Path Operation Base Geometry Import button only imports the first base feature from other operations, even if the other operation has multiple bases.  It would be ideal for the import button to import all of the base features from the selected operation rather than whichever one happens to be first.

### Anything else?

https://github.com/FreeCAD/FreeCAD/pull/9419 is proposed to change the behavior of the import button so that it loops through all base features of the selected op and imports all of them to the current op being edited.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mlampert** [comment]
'should probably get closed - #9419 is merged and apparently fixes this issue.
