### ISSUE TITLE
[Issue] Crash when loading DXF file with a text element

### ISSUE THREAD

**Issue by wwmayer** [FreeCAD/FreeCAD#9438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=78003

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 22.04.2 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33037 (Git)
Build type: debug
Branch: master
Hash: 4d076a70568403f87c33d403835810053ef97aaf
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
[/code]
```

### Subproject(s) affected?

File formats

### Issue description

When loading the file of the forum a crash occurs because it accesses a dangling function pointer.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kpemartin** [comment]
The change to "fix" this appear to break the fix for #8968 as the prefix text collected in 'textPrefix' is no longer used.
