### ISSUE TITLE
[Issue] App not responding when use plygon

### ISSUE THREAD

**Issue by cheuhyakuroku** [FreeCAD/FreeCAD#9453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
0.20.2
```

### Subproject(s) affected?

Sketcher

### Issue description

App not responding when use plygon in sketcher 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
No response. Closing
