### ISSUE TITLE
3DConnexion - Spacemouse is not detected in the snap distribution

### ISSUE THREAD

**Issue by Ventusfahrer** [FreeCAD/FreeCAD#9508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
Version Info of the freecad-snap-variant:
[code]
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git) Snap 698
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: German/Germany (de_DE)
[/code]

version info of the freecad-app-image-variant (3dConnexion is detected and working):
[code]
OS: Ubuntu 23.04 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33071 (Git) AppImage
Build type: Release
Branch: master
Hash: 703ba9b3cf6f673e6870aa8b7e1badbdeb6c9cd2
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.0
Locale: German/Germany (de_DE)
Installed mods: 
  * IconThemes
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

I would like to use the 3DConnexion Spacemouse in FreeCad and struggled to get it visible in FreeCad.

When starting snap-version of freecad from commandline with the parameter --log-file <somefile>
I can find following line in the logfile: 

`Log: Couldn't connect to spacenav daemon. Please ignore if you don't have a spacemouse.`

Hence the Dialog in Tools - User Defined

![image](https://user-images.githubusercontent.com/5901190/236695471-7d71949c-c90e-4f52-be7e-2a36a44bc05d.png)

is empty whereas the app-image-variant shows the line 

`Log: Connected to spacenav daemon` 

in the logfile.
The dialog is filled and the spacemouse can be customized.
![image](https://user-images.githubusercontent.com/5901190/236696052-91031312-339a-47aa-b7a6-0acf1456e441.png)

A hint (?):
I had a similar problem with prusaslicer. There the snap installed variant was not able to update a 3d-printer, because the access of the USB-Port needs to be enabled explicitly by fireing the command snap connect prusa-slicer:raw-usb.

snap seems to introduce an additional security model and does not allow hardware access to all resources a native application might have.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD-snap/issues/61
