### ISSUE TITLE
[Problem] FEM_ClippingPlaneAdd icon missing from GUI

### ISSUE THREAD

**Issue by chennes** [FreeCAD/FreeCAD#9550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.33158 +1 (Git)
Build type: Release
Branch: minorTranslationFixes20230511
Hash: 80b29d2dbfed242e7320d03a4c17464340b8d9a5
Python 3.8.6+, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.5.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Problem description

As reported first here: https://github.com/FreeCAD/FreeCAD-translations/issues/197#issuecomment-1537280732

The icon is present in the source tree, but does not appear in the GUI. There is no error in the log file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
bumpingfor visibility

**Comment by luzpaz** [comment]
bump to get this in before release
