### ISSUE TITLE
[Problem] TechDraw: Lines are sometimes missing due unprecise view directions (or section directions)

### ISSUE THREAD

**Issue by grubertechnic** [FreeCAD/FreeCAD#9572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Debian GNU/Linux 11 (bullseye) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33177 (Git)
Build type: Release
Branch: master
Hash: 3c8ee2213f85b056a742a7e386620d8d2fc0abf9
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, Vtk 9.0.1, OCC 7.7.1
Locale: English/United States (en_US)
Installed mods: 
  * QuickMeasure 2022.10.28
  * Assembly4 0.12.6
  * CurvedShapes 1.0.4
  * Curves 0.6.8
```

### Subproject(s) affected?

Techdraw

### Problem description

When creating a view, it could be too unprecise to get valid results. 0 are not 0, -1 is not -1, 1 is not 1, and so on.

related threads:
https://forum.freecad.org/viewtopic.php?t=78298
https://forum.freecad.org/viewtopic.php?t=77368

file: [example.zip](https://github.com/FreeCAD/FreeCAD/files/11472693/example.zip)

![view_created_per _default](https://github.com/FreeCAD/FreeCAD/assets/109620914/3b7dbbbc-160c-413a-894b-f3cc717e09e0)

![section_created_per _default](https://github.com/FreeCAD/FreeCAD/assets/109620914/fbfefbfc-2b8d-44c8-9e86-4d6208524343)

![section_corrected](https://github.com/FreeCAD/FreeCAD/assets/109620914/cab2c90c-eabd-46c7-93a8-40a26db10402)

### Anything else?

A way to solve that would be to create the views from geometries with a certain task dialog (get a origin, view direction from line or plane, horizontal or vertical specification from a line, intersection plane or whatever, and so on).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
closed as completed

**Comment by grubertechnic** [comment]
thanks
