### ISSUE TITLE
[Problem] OpenSCAD CSG file not imported correctly

### ISSUE THREAD

**Issue by tcurdt** [FreeCAD/FreeCAD#9602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US) [ OS: C/Default (C) ]
Installed mods: 
  * ExtremeProDark 2.6.4
  * ExtremeProLight 1.4.3
[/code]
```

### Subproject(s) affected?

OpenSCAD

### Problem description

I have export a CSG in OpenSCAD and imported it FreeCAD. It looks very different:

**In OpenSCAD:**
<img width="711" alt="openscad" src="https://github.com/FreeCAD/FreeCAD/assets/13697/138eb6ee-9a5d-4f20-a38e-768dea941de7">

**In FreeCAD:**
<img width="638" alt="freecad" src="https://github.com/FreeCAD/FreeCAD/assets/13697/1f373328-fc30-4ea6-94af-854c72438a8b">

So far I have not manage to break this down into a simpler testcase. That's why I have attached the original CSG file.

[linear_motor_plate.csg.zip](https://github.com/FreeCAD/FreeCAD/files/11503166/linear_motor_plate.csg.zip)

### Anything else?

I am wondering if this another story similar to https://github.com/FreeCAD/FreeCAD/issues/6271
Searching on the forum did not yield anything for me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Do you have a minute to try it with a recent developer build of FreeCAD? We've made quite a few bugfixes to the OpenSCAD importer in the past year.

**Comment by tcurdt** [comment]
Sorry, I didn't think of that right away. 🙄
I didn't realize my version was so old.

I can confirm with:

```
OS: macOS 12.6
Word size of FreeCAD: 64-bit
Version: 0.21.0.31483 (Git)
Build type: Release
Branch: master
Hash: 588620fd9fd138892b1cd2466f5c87d441493174
Python 3.11.0, Qt 5.15.6, Coin 4.0.0, Vtk 9.2.2, OCC 7.6.3
Locale: English/United States (en_US) [ OS: C/Default (C) ]
Installed mods: 
  * ExtremeProDark 2.6.4
  * ExtremeProLight 1.4.3
```

It works just fine now!

<img width="698" alt="Screenshot 2023-05-18 at 04 01 58" src="https://github.com/FreeCAD/FreeCAD/assets/13697/44fda93c-0c8c-425b-9f83-3b26201cd59c">

Thanks for the quick response!
