### ISSUE TITLE
[Problem] fem result text color

### ISSUE THREAD

**Issue by myname1614** [FreeCAD/FreeCAD#9617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
[/code]
```

### Subproject(s) affected?

None

### Problem description

no text color setting for that:

![image](https://github.com/FreeCAD/FreeCAD/assets/34938365/6e02013c-987a-480f-b3d1-25d772f0c59d)

it invisible for black on  bg dark

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Do you mind testing on the development version (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds) ?

**Comment by myname1614** [comment]
I didn't see the difference

![image](https://github.com/FreeCAD/FreeCAD/assets/34938365/06341e0f-7a7b-4d0e-b44e-deed73ccd768)

I did not find any new settings on this subject.
black labels on black background.

**Comment by luzpaz** [comment]
@MisterMakerNL, in you opinion, is this something we could address directly in FEM wb or with stylesheets ?

**Comment by MisterMakerNL** [comment]
I couldn't find what it's called, but looking at it there are more issues. It doesn't respects scale-up/dpi with my resolution.
It also isn't using any default font that is used in Freecad.
So I wonder if this graph is even a QT widget.
![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/29804962/13390edb-4c8b-4f31-9fa3-50c6e58fc73a)
![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/29804962/2a6ce087-f39b-4106-96d2-e37249079efc)

**Comment by MisterMakerNL** [comment]
I think I found the code here:
https://github.com/FreeCAD/FreeCAD/blob/b6e0cfc52b1d33502f72a03c834bb27deaf52d0c/src/App/ColorModel.cpp#L487

**Comment by luzpaz** [comment]
@chennes would you mind weighing-in ?

**Comment by MisterMakerNL** [comment]
That happens if you start Freecad on a 4k monitor and then move the window to 1080p screen.

**Comment by luzpaz** [comment]
Closing in favor of #10439
