### ISSUE TITLE
[Feature Request] TechDraw: Manipulation with cosmetic objects in TechDraw

### ISSUE THREAD

**Issue by xtemp09** [FreeCAD/FreeCAD#9619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Forum thread

https://forum.freecad.org/viewtopic.php?style=10&t=78463

### Subproject(s) affected?

Techdraw

### Problem description

My proposal is simple:

- [X] Deletion of cosmetic object with the delete key on keyboard (and/or via an option in the context menu) 0125662
- [x] Changing properties of cosmetic object with double click (and/or via an option in the context menu)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Deletion of cosmetic elements via the Del key implemented by 01256623ff

**Comment by luzpaz** [comment]
I've updated OP with commit and some markdown tweaks

**Comment by FEA-eng** [comment]
> * [ ]  Changing properties of cosmetic object with double click (and/or via an option in the context menu)

With #11188, double-clicking on any edge (including cosmetic lines) brings the line decoration tool where you can set the appearance (style, thickness, color, visibility) of the line. So maybe this issue can be closed as completed.

**Comment by luzpaz** [comment]
@xtemp09 :point_up_2:
