### ISSUE TITLE
Visualization after importing step file

### ISSUE THREAD

**Issue by LuigiWR** [FreeCAD/FreeCAD#9620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Italian/Italy (it_IT)
Installed mods: 
  * A2plus
  * ExplodedAssembly
  * fasteners
  * Manipulator
[/code]
```

### Subproject(s) affected?

None

### Problem description

I generated a step file of a PCB using ALTIUM DESIGNER electronic cad. I can display it correctly also with other step file visualizers such as E Drawing, IDA Step, Fusion360, Shapr3D. Only with FreeCad the visualization is wrong as you can see from the images.  In the zip file there is the original step file.

![Altium Designer](https://github.com/FreeCAD/FreeCAD/assets/117817447/73eefe71-975a-40fd-b598-e3f6aa47614a)
![eDrawings](https://github.com/FreeCAD/FreeCAD/assets/117817447/7c3aef23-ea7d-4a88-b351-a718b4251146)
![FreeCad](https://github.com/FreeCAD/FreeCAD/assets/117817447/0e422772-8db9-474e-a617-46be353cd70c)
![Fusion360](https://github.com/FreeCAD/FreeCAD/assets/117817447/50120681-75a9-4034-a030-503c3328c856)
![Ida Step](https://github.com/FreeCAD/FreeCAD/assets/117817447/bbf784ab-709f-4892-b7ed-9e73d5e67dcd)
![Shapr3D](https://github.com/FreeCAD/FreeCAD/assets/117817447/aae8c03b-04bc-4f91-bb5f-3bf1fb4e42f7)
[BOXALRIT.zip](https://github.com/FreeCAD/FreeCAD/files/11522996/BOXALRIT.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
Here is the screenshot from the git version:

![Ubuntu 22 04 64-bit-2023-05-21-18-36-38](https://github.com/FreeCAD/FreeCAD/assets/9303235/b0b8c64c-08fc-4287-993d-1550f75c4f8c)

**Comment by LuigiWR** [comment]
OK, I'm very happy to see that you can display correctly the file... The problem is that on 3 different PC (one of witch is with WIN7), the visualization of the file is the same, and it's wrong. So, the question is: what I have to do to obtain the correct visualization?

**Comment by luzpaz** [comment]
Wait for next version release or use the development releases.

**Comment by luzpaz** [comment]
Closing as 'wont fix' since it's fixed in dev and probably won't be backported.
