### ISSUE TITLE
[Problem] Arch Workbench Wall Fails

### ISSUE THREAD

**Issue by nelsonic** [FreeCAD/FreeCAD#9659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * BIM 2021.12.0
```

### Subproject(s) affected?

Arch

### Problem description

While attempting to follow @yorikvanhavre's "Presentation of FreeCAD Arch Workbench": https://youtu.be/CH_io4MHJ4U?t=100
and create a basic Wall in the Arch Workbench based on a Rectangle I get the following strange result:
<img width="1920" alt="freecad-wall-weird" src="https://github.com/FreeCAD/FreeCAD/assets/194400/bc2bfeb7-25e7-415d-a7e6-bc5a6dcc04ee">

In case it's easier to see the full sequence of events, I recorded a video of all the steps:
https://youtu.be/2n_JjEguOGw [71 seconds]

Really don't understand what I'm doing wrong and wanted to report it in case it's a bug. 🤷‍♂️ 

Created a forum topic: https://forum.freecad.org/viewtopic.php?t=78586 as it appears to be the faster way to get help. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Can you attach the file here? (You might need to change the extension to .zip)

**Comment by nelsonic** [comment]
Hi @yorikvanhavre thanks for checking this out. I'm literally just taking a `Rectangle` created in the `Arch` Workbench:

<img width="2533" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/194400/8ef181c2-4376-404c-9926-acc14bf4a48a">

<img width="2533" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/194400/ced5cde8-53a4-43d1-82d5-fecb1ed37eeb">

![freecad-arch-wall-issue](https://github.com/FreeCAD/FreeCAD/assets/194400/650ad8d2-02b2-4a62-a2a2-8bee8a867d83)

The file is on GitHub at: https://github.com/dwyl/learn-cad-cam-cnc/blob/master/freecad/20220524-freecad-arch-learning.FCStd

But also uploaded here as `.zip` for convenience:  [20220524-freecad-arch-learning.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11563672/20220524-freecad-arch-learning.FCStd.zip)

Appreciate the help.
If it's just my Mac (M1) being silly, I could try a different computer. 
But given that this is the most recent machine I have with a decent graphics card I wanted to use it for `FreeCAD` so that I can build a reasonably complex/complete architectural model.

**Comment by nelsonic** [comment]
On the advice of [**`@hko`**](https://forum.freecad.org/memberlist.php?mode=viewprofile&u=30966) (on the [forum](https://forum.freecad.org/viewtopic.php?p=684122#p684122)), updated the Preferences > Draft > Default Working plane from "None":
<img width="971" alt="freecad-pref-draft-default-working-plane-none" src="https://github.com/FreeCAD/FreeCAD/assets/194400/aee7bf16-65cd-43f0-aba5-39f5590399fc">

To "XY Top":
<img width="971" alt="freecad-pref-draft-default-working-plane-XY-top" src="https://github.com/FreeCAD/FreeCAD/assets/194400/a23d5936-b7fa-4abc-8066-934b214b2ea8">

Then in a **`new document`**, created a fresh `Rectangle` with the dimensions I waned `3m x 4m`
and when creating a wall based on the `Rectangle` get the desired result:

<img width="1954" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/194400/27fa3b41-e110-445e-80aa-fae8960e09d9">


Closing as "PEBCAK". ✅  (thanks for your patience with me ... 🙏)
Not a problem/issue/bug with `FreeCAD` but rather a lack of knowledge/experience of the **working plane**. 🙄 
But wish there was an easy way new `FreeCAD` people avoid this issue ... 💭

**Comment by nelsonic** [comment]
Follow-up note: In the Wall properties the `Length` is listed as `14.00m`: 

<img width="2201" alt="freecad-arch-wall-length-14m" src="https://github.com/FreeCAD/FreeCAD/assets/194400/e07a7c2b-2b65-4d7f-bbc0-9b4fe90fe46c">

The `Wall` is based on a `3m x 4m` `Rectangle`: 
<img width="2201" alt="freecad-arch-rectangle-3x4m" src="https://github.com/FreeCAD/FreeCAD/assets/194400/901e6abf-323c-43fd-a89e-673722629b21">

Therefore my assumption is that the "Length" of the wall is in fact the _perimeter_.
i.e. `3 + 4 + 3 + 4 = 14m` ...

**Comment by yorikvanhavre** [comment]
Glad you have it sorted. Indeed the working plane is something to be aware of when starting. It is set by default to the XY plane. However, it is in "unattached" mode, which means if you change your view point it will adapt to the current view. I understand this might be confusing.

This is a useful behaviour though, but I'm not sure attaching it to the XY plane by default would make things better.

Thinking out loud now, we could add an additional "smart" auto mode to that working plane:

- if you are in top, front or side view, the plane adapts to your view
- in all other cases, the plane goes to XY

What would you think of that @Roy-043 ?

**Comment by Roy-043** [comment]
The defaultWP is actually set to zero. Setting it to 1 would be a good idea IMO. I would not change the behavior of Auto mode.

It would also be good if Arch_Wall were not restricted to the XY plane. It could then be used as a more generic tool.
