### ISSUE TITLE
[Problem] Revolution/Mirroring produces a gap in a body

### ISSUE THREAD

**Issue by holmas** [FreeCAD/FreeCAD#9660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.0.0
  * A2plus 0.4.60n
  * fasteners 0.4.56
  * CurvedShapes 1.0.4
[/code]
```

### Subproject(s) affected?

None

### Problem description

While building the attached body a gap was produced as shown in picture Nº2. I had noticed this gap when I wanted to make fillets on the edges shown in picture Nº1. After reloading of the file the gap was gone, but it is still impossible to make that fillets.

### Anything else?

[fehler_entriegelung.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11564381/fehler_entriegelung.FCStd.zip)
![fehler_entriegelung_2](https://github.com/FreeCAD/FreeCAD/assets/466220/115e8e94-9562-4715-aa09-a1f1a0dec12a)
![fehler_entriegelung](https://github.com/FreeCAD/FreeCAD/assets/466220/e85cedb6-5c8c-4b7e-b8cf-c1e8c39cd937)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Heads up. please don't use `#1` or any number after a hashtag because it will link to another ticket in github. I've fixed this in the original ticket for you by adding Nº1 and Nº2. TIA!

**Comment by luzpaz** [comment]
Is this then just UX error and if so do we do anything about it ?

**Comment by grubertechnic** [comment]
It is a mixture of coplanar issue and user error. I would close it.

**Comment by grubertechnic** [comment]
I would close it. It is a user error. And for the coplanar issue (which is in that case not really the source of the issue), there are dozens of duplicates in the tracker.

**Comment by grubertechnic** [comment]
@adrianinsaval or @luzpaz : i definitely think, that is a candidate to close it.

**Comment by grubertechnic** [comment]
thanks!
