### ISSUE TITLE
[Problem] FEM Workbench doesn't work in MacOS

### ISSUE THREAD

**Issue by alexandervincon** [FreeCAD/FreeCAD#9669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: macOS 13.3.1
Word size of FreeCAD: 64-bit
Version: 0.21.0.33303 (Git)
Build type: Release
Branch: master
Hash: 5b075a9938b78076fdde9034de4a05685e42690e
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: C/Default (C)
Installed mods: 
  * CfdOF 1.22.9
  * workfeature
  * DesignSPHysics.backup1672319298.637321 0.6.3(24-09-2022)
  * QuickMeasure 2022.10.28
  * offline-documentation 1.0.0-alpha
  * A2plus 0.4.60n
  * fasteners 0.4.56
  * Estimate 0.1.2
  * CurvedShapes 1.0.4
  * offline-documentation.backup1682623751.106855 1.0.0-alpha (Disabled)
  * sheetmetal 0.2.63
  * NikraDAP 2.0.0
  * toSketch 1.0.1
  * Help 1.0.3
  * Cfd
  * Curves 0.6.9
  * Assembly4 0.50.2
[/code]
```

### Subproject(s) affected?

FEM

### Problem description

FEM Workbench doesn't start in Freecad 0,21 and gives the shown message below. Freecad 0.20.2 doesn't show the failure.

### Anything else?

<img width="638" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/109148443/774889c3-309f-42ff-a66e-63dd7f7d3c27">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
This is a packaging problem, tracked at https://github.com/FreeCAD/FreeCAD-Bundle/issues/173
