### ISSUE TITLE
[Problem] Unknown command 'WebTools_Speckle

### ISSUE THREAD

**Issue by DimitriBolt** [FreeCAD/FreeCAD#9710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Ubuntu 23.04 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.2.
Build type: Release
Python 3.11.1, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Help 1.0.3
  * WebTools
[/code]
```

### Subproject(s) affected?

Addon Manager

### Problem description

When it is choosing a workbench WebTools an error occurs. There are notices "20:53:34  Unknown command 'WebTools_Speckle' in Report view window.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DimitriBolt** [comment]
![image](https://github.com/FreeCAD/FreeCAD/assets/37275623/99271f20-4d1d-4f03-a976-67510006704c)

**Comment by yorikvanhavre** [comment]
That command is obsolete anyway and does not work with current version of Speckle. I disabled it now
