### ISSUE TITLE
All Sketches have exclamation marks on Mac, even empty ones

### ISSUE THREAD

**Issue by IlmariTamminen** [FreeCAD/FreeCAD#9718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS Mojave (10.14)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.0.0
  * Manipulator 1.5.0
  * sheetmetal 0.2.63
[/code]
```

### Subproject(s) affected?

Sketcher

### Problem description

Hi.

I just updated my FreeCad on Mac, the problem was also in the previous 0.20.1 version. All the Sketches have the red exclamation-mark symbol in the Combo View, even if I create an empty Sketch. If I create a simple circle with 0 degrees of freedom the issue persists. I have done all the Validate-sketch analyses for the Sketches and found no problems, similarly the Report view does not help. How could I fix the issue or is this a bug, although the problem does not seem to bother the following steps in my workflow.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
please provide pictures and example file.

Also checkout https://wiki.freecad.org/Tree_view#Overlay_icons as whatever you are seeing may very well be perfectly normal.
