### ISSUE TITLE
Draft: Unable to read svg on windows with system locale not utf-8

### ISSUE THREAD

**Issue by BuddhasPriest** [FreeCAD/FreeCAD#9726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell

```

### Subproject(s) affected?

None

### Problem description

Users cannot import svg files on windows with a system locale other than utf-8.

When importing svg file on Japanese Windows 11, I get an error because the default system locale is shift-jis (cp932). Saving the svg file in utf-8 also causes an error.
Changing line 1770 of importSVG.py to parser.parse(pythonopen(filename, errors='ignore')) works, but I am not sure if this is a fundamental solution.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
We need a better system that supports different encodings probably...

Could you try this?

Place this line above line 1770: `import codecs`

Set line 1770 to this: `parser.parse(codecs.open(filename))`

`codecs.open()` is advertised as being more tolerant to different encodings than standard `open()`...

**Comment by BuddhasPriest** [comment]
@luzpaz 
Thanks for your comment.
I tried it and still got the codec error...

**Comment by luzpaz** [comment]
@BuddhasPriest missing About info  
missing test on dev version

**Comment by yorikvanhavre** [comment]
Does the first line of the file (the <xml> tag) informs of the encoding?
Also, what is the error you get when trying to open the file?
I'm not sure using open(errors='ignore')  is a good idea because some people might have encoding errors that will give wrong results...

**Comment by benj5378** [comment]
@BuddhasPriest are you able to share your SVG file? Just to prevent false debug results

**Comment by BuddhasPriest** [comment]
Dear Yorik van Havre,

I'm  responding GitHub, but will comment.
This code did not work, it fails to load svg created with cp932
codec(Shift-Jis codec).

 I have thought a bit about essential solutions, but currently have no
ideas. I'm stumped.

Sincerely regards,


2023年6月6日(火) 21:30 Yorik van Havre ***@***.***>:

**Comment by luzpaz** [comment]
@BuddhasPriest can you please drag and drop an svg file for testing please?

**Comment by luzpaz** [comment]
@BuddhasPriest :point_up_2:

**Comment by benj5378** [comment]
> ideas. I'm stumped.

SVG file is not that necessary if we can just make an SVG file that can recreate the bug ourselves (which we very likely can).

**Comment by luzpaz** [comment]
> can you please drag and drop an svg file in to this ticket (in order to attach it) for testing please?

@BuddhasPriest

**Comment by maxwxyz** [comment]
Issue closed as discussion stalled and we get no further feedback.
