### ISSUE TITLE
[Problem]  Carbon Copy does not work with SketchObjectPython (Archsketch)

### ISSUE THREAD

**Issue by jsolersallent** [FreeCAD/FreeCAD#9767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * BIM 2021.12.0
  * FreeCAD_SketchArch-master
  * parts_library
  * parts_library.bak
[/code]
```

### Subproject(s) affected?

ArchSketch (external addon)

### Problem description

Hi,
I'm trying to make an archsketch and I want to use the carbon copy tool to copy another archsketch in it. The tool works fine with Sketcher, but not with Archsketch.
Thanks

#https://forum.freecad.org/viewtopic.php?t=78881 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
CC @paullee0

**Comment by jsolersallent** [comment]
Thanks luzpaz!

**Comment by luzpaz** [comment]
Please alter the title of the ticket so it's more elaborate

**Comment by paullee0** [comment]
Thanks  @jsolersallent and @luzpaz 

 @jsolersallent, suggested subject  -  "Carbon Copy does not work with SketchObjectPython  (Archsketch)"

**Comment by paullee0** [comment]
@abdullahtahiriyo, when you have a gap, see if you would like to have a look.

Forum Discussion  -  https://forum.freecad.org/viewtopic.php?t=78881#p686564

[https://github.com/paullee0/FreeCAD_Ske ... ect.py#L57](https://github.com/paullee0/FreeCAD_SketchArch/blob/master/ArchSketchObject.py#L57)
[https://github.com/paullee0/FreeCAD_Ske ... t.py#L1683](https://github.com/paullee0/FreeCAD_SketchArch/blob/master/ArchSketchObject.py#L1683)

      archSketch = grp.newObject("Sketcher::SketchObjectPython",name)

**Comment by adrianinsaval** [comment]
could you provide an example file?

**Comment by paullee0** [comment]
@adrianinsaval  File uploaded in forum discussion OP

[Vil·la Savoye.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11747952/Vil.la.Savoye.FCStd.zip)

**Comment by jsolersallent** [comment]
@adrianinsaval,  is easy to view.

1. Create a simple Sketch with Archsketch ( it can be fully constrained or not ).
2. Create a new Archsketch and try to create a carbon copy of the other archsketch. The tool is locked.
3. However, if an Archsketch is created and you want to trace a sketch made with Sketcher, it does work.

**Comment by luzpaz** [comment]
> @abdullahtahiriyo, when you have a gap, see if you would like to have a look.
> 

JFYI, @paullee0 that abdullah will be AFK for a while (he mentioned in a previous ticket recently) that he won't be available for a period of time (he didn't specify when)

**Comment by paullee0** [comment]
> JFYI, @paullee0 that abdullah will be AFK for a while (he mentioned in a previous ticket recently) that he won't be available for a period of time (he didn't specify when)

Thanks for the heads-up, he did mention something similar when he made a simple reply in the forum discussion on this issue :)

> @adrianinsaval, is easy to view.
> 
>     1. Create a simple Sketch with Archsketch ( it can be fully constrained or not ).
> 
>     2. Create a new Archsketch and try to create a carbon copy of the other archsketch. The tool is locked.
> 
>     3. However, if an Archsketch is created and you want to trace a sketch made with Sketcher, it does work.

@jsolersallent , thanks for outlining the steps; however,  other peoples may probably not aware that an external add-on is required before it is possible to create the ArchSketch - a Sketcher::SketchObjectPython object.

I have uploaded your file to enable developers to test :D

**Comment by jsolersallent** [comment]
> I have uploaded your file to enable developers to test :D

Thanks @paullee0

**Comment by luzpaz** [comment]
maybe sketcher devs can revisit this Arch issue ?

**Comment by Syres916** [comment]
@paullee0 it will probably have to wait until after 1.0 Release but it looks like I've got a solution https://github.com/FreeCAD/FreeCAD/compare/main...Syres916:FreeCAD:CarbonCopy_Fix_SketchArchPython_dev

Just need to do some regression testing and wait for the TNP stuff to calm down but at least some progress.

**Comment by paullee0** [comment]
Thanks @Syres916 :)  I have no knowledge about c++, glad you fix it.
