### ISSUE TITLE
[Problem] Assembly4 Workbench - Animation only works once for any given assembly

### ISSUE THREAD

**Issue by JimShip** [FreeCAD/FreeCAD#9768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
I've tried Fedora 38 packaged versions 0.20.1, 0.20.2 as well as 0.21 (built from git source) with same result.

Assembly4 installed via the built in workbench installer.

Linux laurie.family.net 6.3.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 30 15:44:17 UTC 2023 x86_64 GNU/Linux
64GB RAM
12T Disk space
NVIDIA GeForce GTX 750 Ti
Gnome 44.1
X11
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

Create the problem:
1) Create a new project using Part design
2) Switch to Assembly4 and import body's
3) Connect LCS
4) Annimate
5) GUI Works fine animation is perfect

6) Save project and reload
7) Bring up the Animate GUI
8) I get the following instantly upon opening the Animate GUI

Traceback (most recent call last):
12:39:39    File "/home/shipman/.local/share/FreeCAD/Mod/Assembly4/./AnimationLib.py", line 221, in onSelectDoc
12:39:39      self.updateVarList()
12:39:39    File "/home/shipman/.local/share/FreeCAD/Mod/Assembly4/./AnimationLib.py", line 206, in updateVarList
12:39:39      animationHints.cleanUp(self.Variables)
12:39:39    File "/home/shipman/.local/share/FreeCAD/Mod/Assembly4/./AnimationLib.py", line 819, in cleanUp
12:39:39      hint = hintList.get(entry, None)
12:39:39             ^^^^^^^^^^^^
12:39:39  AttributeError: 'NoneType' object has no attribute 'get'

Nothing works after this.  The close button just gives more errors.  I have to use the X in the corner to get rid of the dialog window.

Saving/reloading nothing works after this.  I can't use the Animate dialog again until I create a new model.  The new model then works once, and not thereafter.  All the old projects still don't work ever again.

Jim Shipman

### Anything else?

[GearAssy.zip](https://github.com/FreeCAD/FreeCAD/files/11738785/GearAssy.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Wrong repository. This ticket should be opened in https://github.com/Zolko-123/FreeCAD_Assembly4
