### ISSUE TITLE
[Problem] Overlapping PartDesign Pipes fail to generate the correct solid

### ISSUE THREAD

**Issue by racer-coder** [FreeCAD/FreeCAD#9807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33345 (Git)
Build type: Release
Branch: master
Hash: a3c4f4bb01f5201daf666852444a8f9c5adbda8d
Python 3.8.16, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * sheetmetal
[/code]

Also tried 0.20.2:
[code]
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * sheetmetal
[/code]
```

### Subproject(s) affected?

PartDesign

### Problem description

I have two pipes that overlap, but after creating the second pipe the solid only contains the first pipe.  I believe it may be related to having a datum plane.  If you change the Attachment Angle of SecondaryPlaneClock001 to either -45 or 0, it works, but it seems to fail at -75 or -90.

### Anything else?

[QCFittingBad.zip](https://github.com/FreeCAD/FreeCAD/files/11837171/QCFittingBad.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Closing as duplicate
