### ISSUE TITLE
[Feature Request] Better Icon alignment in the default 'no stylesheet' UI option (solved in other stylesheets)

### ISSUE THREAD

**Issue by NXTler** [FreeCAD/FreeCAD#9819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: makepkg
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.11.3, Qt 5.15.9, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * PieMenu 1.2.7
  * sheetmetal 0.2.63
  * toSketch 1.0.1
  * A2plus 0.4.60n
  * QuickMeasure 2022.10.28
  * Curves 0.6.12
  * CfdOF 1.23.1
  * TabBar
  * IconThemes
  * Glass
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

Core

### Problem description

Hello all,
when placing the toolbars vertical, the Icons will not align in a straight line because the dropdown menus are longer:
![Screenshot_20230625_191121](https://github.com/FreeCAD/FreeCAD/assets/73062438/72ecbdfc-1d03-468a-ba54-9883ae6ac440)

### Anything else?

Other Programs handle this by aligning all Icons to the left side, not the Center:
![6Unbenannt](https://github.com/FreeCAD/FreeCAD/assets/73062438/a7ec9c48-222a-4b22-89e2-84f6571fc869)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
If you're going to ask for UI/UX improvements, please use the development version v0.21.x  
TIA

**Comment by NXTler** [comment]
Though this is still present in version v.0.21.0

**Comment by yorikvanhavre** [comment]
Possible solutions https://forum.qt.io/topic/59049/left-align-qtoolbuttons-in-a-vertical-qtoolbar

**Comment by adrianinsaval** [comment]
> Possible solutions https://forum.qt.io/topic/59049/left-align-qtoolbuttons-in-a-vertical-qtoolbar

if applying something like this care must be taken to not negatively affect right to left systems.

How does it look when you use the appimage or enable a stylesheet? this might rather be a problem with the system theme you are using. Are you running in a gtk system that uses a qt theme dervied from the gtk theme? those are usually buggy. Although it kinda looks like breeze too.

**Comment by NXTler** [comment]
I'm using KDE with breeze. Using the release version or the stylesheets changes nothing about the icon alignment.

**Comment by adrianinsaval** [comment]
And the appimage? (The appimage doesn't load the system theme)

Can you try configuring a different style on your KDE settings? Like oxygen or fusion

**Comment by NXTler** [comment]
Yeah, I'm running the Appimage right now. Changing the KDE style does not change the Icon behavior.

**Comment by luzpaz** [comment]
@MisterMakerNL would you mind weighing-in ? TIA!

**Comment by MisterMakerNL** [comment]
It's fixed in Linkstage and in my theme pr. Also in ExtremeProDark preference pack.

**Comment by luzpaz** [comment]
@MisterMakerNL Thanks! One more request, can you permlink to the stylesheet code that does this.perhaps ?

**Comment by MisterMakerNL** [comment]
Currently not near my computer but you can see how it's fixed with the code here. https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta

**Comment by MisterMakerNL** [comment]
In the new stylesheets it looks like this:
![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/29804962/4e0038a3-8d8b-4288-9d03-4d7b8bc8806f)
It's added here: https://github.com/FreeCAD/FreeCAD/pull/9715
Although still not added in the no-stylesheet. But there can probably be a discussion that the no-stylesheet should be as universal as possible and the old way is maybe a bit more easy to click on since the arrow is located next to the icon instead in it?

**Comment by luzpaz** [comment]
Since the fix is available in the new addon, what should we do with this ticket ?

**Comment by luzpaz** [comment]
bump

**Comment by NXTler** [comment]
This is exactly what I was looking for! I don't think it affects the usability that much and looks a bit more polished, so I don's see a reason why not to add it to no-stylesheet.

**Comment by MisterMakerNL** [comment]
> Since the fix is available in the new addon, what should we do with this ticket ?

This is already in 0.21 so can be closed in my opinion.
