### ISSUE TITLE
[Problem] [Curves WB] "execute is disabled during editing"-Warning Message displayed too often

### ISSUE THREAD

**Issue by michacassola** [FreeCAD/FreeCAD#9840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.0.33458 (Git)
Build type: Release
Branch: master
Hash: 8b89dd29d2382c72d738c52e8974216130ffa9db
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Assembly4 0.50.2
  * CurvedShapes 1.0.4
  * Curves 0.6.12
  * lattice2 1.0.0
  * Nodes 0.1.36
  * ProDarkThemePreferencePack 1.0.0
  * Silk 0.1.3
  * TabBar
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

[Curves WB] An Extrude of B-Splines in a Sketch is used as the Cutting Object in Split Curves of B-Splines in Sketches. Resulting Points are connected with Freehand B-Splines. After editing the Sketch with the curves that get extruded the warning pops up once for each Freehand B-Spline although the idividual Editing Mode of the Freehand B-Splines was not used.
[FreeCAD-0.21.0-weekly-execute is disabled during editing-warnings.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11904586/FreeCAD-0.21.0-weekly-execute.is.disabled.during.editing-warnings.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Thanks for the report. 

Unfortunately (for you) Curves is an external addon, the dedicated repository is at https://github.com/tomate44/CurvesWB therefore please understand that we're closing it here because it's out of scope.  This ticket should be filed there. TIA for your understanding.
