### ISSUE TITLE
[Problem] UI: Some text is essentially illegible in "dark mode"

### ISSUE THREAD

**Issue by Stokestack** [FreeCAD/FreeCAD#9841]
Just a couple of examples on the Model and Tasks tabs...

```
OS: macOS 13.4.1
Word size of FreeCAD: 64-bit
Version: 0.21.0.33458 (Git)
Build type: Release
Branch: master
Hash: 8b89dd29d2382c72d738c52e8974216130ffa9db
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Manipulator 1.5.0
  * lattice2 1.0.0
  * Help 1.0.3
```

<img width="743" alt="darkModeProbs" src="https://github.com/FreeCAD/FreeCAD-Bundle/assets/196304/78c78507-e44f-4be3-9e08-d7266ea0aff0">

**Comment by luzpaz** [comment]
@PLChris can you confirm ?

**Comment by adrianinsaval** [comment]
related: https://github.com/FreeCAD/FreeCAD/issues/8845 and https://github.com/FreeCAD/FreeCAD/issues/7623

did this happen with older versions too or is it a new bug? Does setting one of the bundled stylesheet work correctly?

**Comment by Stokestack** [comment]
This does not happen with 0.20.2. I had to do some work and encountered some other bugs, so I went back to that version. I'll reinstall the latest. Where do you "set the bundled stylesheet?"

**Comment by YosypC** [comment]
I also get issues on Spreadsheets workbench

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33345 (Git)
Build type: Release
Branch: master
Hash: a3c4f4bb01f5201daf666852444a8f9c5adbda8d
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/Europe (en_150)
```

**Comment by luzpaz** [comment]
@adrianinsaval an aside, perhaps we should add to the About info what stylesheet is being used ?

**Comment by adrianinsaval** [comment]
Too rarely relevant IMO

**Comment by Stokestack** [comment]
@adrianinsaval What is?

**Comment by app4soft** [comment]
What about light gray text on white background in drop-down lists in all built-in `Dark-*` themes (see *"Tasks > Pad parameters > Type"*).

Is it related to this issue or need to create a separate on?

![Screenshot_2023-07-09_13-50-42](https://github.com/FreeCAD/FreeCAD/assets/22447924/83aa6fa7-ec89-4d14-b71c-5334cc44985a)

**Comment by MisterMakerNL** [comment]
Could everyone here with issues test them on the new stylesheets you can test them by building freecad or install it true the addon browser they are called 
![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/29804962/95c3d515-62a2-49eb-9839-3dd31abf63b6)

**Comment by MisterMakerNL** [comment]
Thanks for your feedback!
I think the hidden line thing is how it should work, the background can screw up the visibility of the lines so it changes to a single color. This happens with every theme even the no-stylesheet option.
The highlight of which preference pack is applied isn't a feature I understand why this sound logical to have, but with the ability of the user to modify as they like it's will be broken as soon as they start to alter anything.
The place holder I cannot reproduce, bot sure what is going on there, could you look at it without stylesheet?

**Comment by luzpaz** [comment]
We also need [About](https://wiki.freecad.org/About) info

**Comment by MisterMakerNL** [comment]
> Just installed the last weekly and looked for the add-on displayed above. It's not listed as available (installed or not).
> <img alt="Screenshot 2023-07-18 at 3 32 12 PM" width="1040" src="https://user-images.githubusercontent.com/196304/254396065-54a7b070-2362-488b-b87a-63186fc22e68.png">

CAn you put this filter one, then it should be visible since there aren't a lot of preference packs:
https://i.imgur.com/CyPUTQZ.png

**Comment by app4soft** [comment]
> The place holder I cannot reproduce, not sure what is going on there, could you look at it without stylesheet?

With "No stylesheet" there are no such placeholders, but turning stylesheet back placeholders appears again.

![Screenshot_2023-07-20_03-08-59](https://github.com/FreeCAD/FreeCAD/assets/22447924/7089871b-610f-4633-873d-9d772e862576)

**Comment by Stokestack** [comment]
@MisterMakerNL Thanks, but that doesn't fix it. If it did, that would in fact be another bug, since "all" should mean all. Here's what happens if I filter as you suggest:

<img width="997" alt="noColorThingy" src="https://github.com/FreeCAD/FreeCAD/assets/196304/4ac401a5-4df0-4c76-8a03-229940fcdaf4">

**Comment by MisterMakerNL** [comment]
> @MisterMakerNL Thanks, but that doesn't fix it. If it did, that would in fact be another bug, since "all" should mean all. Here's what happens if I filter as you suggest:
> <img alt="noColorThingy" width="997" src="https://user-images.githubusercontent.com/196304/254752374-4ac401a5-4df0-4c76-8a03-229940fcdaf4.png">

I have no idea what is going on here, I double checked if the addon file is still good, and it is. Also I myself deleted the addon and reinstalled it true the addon manager.....

**Comment by MisterMakerNL** [comment]
> 

Something else going on there it shouldn't look like that:
![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/29804962/3092ccd4-2478-41d2-9c52-e9e12293d484)
Could you post your version and if you use the addon or the newest build?

**Comment by app4soft** [comment]
> Could you post your version and if you use the addon or the newest build?


```Bash
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33593 (Git) AppImage
Build type: Release
Branch: master
Hash: 15371a04f38bbeb5a04edc5a91020ada1e30ef88
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * dodo 1.0.0
  * sheetmetal 0.2.63
  * IconThemes
  * Freecad-Built-in-themes-beta 1.0.1
  * fasteners 0.4.56
  * CurvedShapes 1.0.4
  * Assembly3 0.12.0
  * Curves 0.6.12
  * A2plus 0.4.60n
  * ExplodedAssembly
  * Curves.backup1689700155.7726495 0.6.12 (Disabled)
  * Silk 0.1.3
  * Assembly4 0.50.2
```

> Something else going on there it shouldn't look like that, your pulldown menu is floating in the air?

All pulldown menus are floating and all has empty placeholders.

With "No stylesheet" it is also floating, but there is no emptyplaceholders.

![Screenshot_2023-07-20_23-03-51](https://github.com/FreeCAD/FreeCAD/assets/22447924/c1d545b6-083c-49d1-87c3-d0551b06c267)
![Screenshot_2023-07-20_23-07-34](https://github.com/FreeCAD/FreeCAD/assets/22447924/267e4b17-a229-400c-ac72-1ec48f058833)

**Comment by Stokestack** [comment]
@luzpaz Hi! Should I file a bug against the add-on browser for missing a bunch of stuff (per my screen shots above)? I was using last week's build on Mac OS.

**Comment by luzpaz** [comment]
@Stokestack yes, but file it in https://github.com/FreeCAD/FreeCAD/issues and link to this ticket please? TIA

**Comment by ooswald** [comment]
...and even if you get the colours right in the day, they UI falls apart in the evening when the OS enables dark mode. I had to switch back to 0.20 because the colour issue was killing my productivity.

**Comment by MisterMakerNL** [comment]
I think this placeholder issue is related to set style in linux.

https://forum.freecad.org/viewtopic.php?t=81122

**Comment by MisterMakerNL** [comment]
Fix for the placeholders, it indeed where placeholders for checkmarks. And the check-mark was there but not visible.
PR that should fix this: https://github.com/FreeCAD/FreeCAD/pull/10968

**Comment by drf5n** [comment]
They are somewhat illegible on a Mac in light mode as well:

<img width="1246" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/221f9b55-f1ca-4676-b4ae-a5fe977717c7">

The report, console, and text editor QPlainTextEdit colors don't appear to change with the stylesheet changes, and remain somewhat illegible in light, dark, or none:

<img width="1254" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/bd4efcbe-0f88-4b8a-89ce-94c4d42404bf">

<img width="1255" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/e46cb83a-1462-4fe7-b72c-13bfde3df198">

**Comment by luzpaz** [comment]
Thanks @drf5n! It's great to have more macOS users involved in UI/UX related tickets :pray:

**Comment by drf5n** [comment]
Oops.  I think some of the problems in my screenshots above were from persistence -- old text is not being re-written with the preference change.

Here's some Python Console code that exercises the Preferences/General/Report view, Python Console, and Python Editor window colors:

```
""" 
Preferences_Python_Editor_SampleCode.py 
FreeCAD Preferences/Python/Editor Short Python Sample Code 
for experimenting with Python Editor, Console, and Report View Colors  
"""
# Short Python sample
import sys
class Junk:
	"Test class highlighting"
	def foo(self,begin, end):
		i = begin
		while i < end:
			print(i)
			i = i + 1
			print("Text")
		return None
	def testReportViewMessages(self):
	    FreeCAD.Console.PrintMessage("\n\nHello world FreeCAD.Console.PrintMessage\n")
	    FreeCAD.Console.PrintLog("Hello world FreeCAD.Console.PrintLog\n")
	    FreeCAD.Console.PrintWarning("Hello world FreeCAD.Console.PrintWarning\n")
	    FreeCAD.Console.PrintError("Hello world FreeCAD.Console.PrintError\n")

junk = Junk()
junk.foo(0, 1)
junk.testReportViewMessages()
```

If I choose Preferences/General/ (apply a preference pack)  and then open up the console, report and a .py file, then this the big green arrow to run the script, I get this for Classic:

<img width="1071" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/334bc63b-dcf2-4b81-9a0c-f853f075e54c">

Yellow or grey on white is difficult to read.

This for Dark Theme:

<img width="1067" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/1e50f292-6b7d-4004-a124-f1386fa2eb47">

Navy on Black is difficult.

And this for light theme:

<img width="1065" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/7db2d574-deed-4420-b221-35d37c5efb7d">

Grey on white is difficult.

## About
```
OS: macOS 13.2.1
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * startup.py.FCMacro
  * MacroStartup
  * Macro_MeshToPart.png
  * junk2.FCMacro
  * junk.py
  * MeshToPart.FCMacro
  * 3D_Printing_Tools
```

**Comment by drf5n** [comment]
Here's an overlay preference pack that adjusts the colors of the editor and report windows away from a white background to darker fonts. 

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<FCParameters>

  <FCParamGroup Name="Root">
    <FCParamGroup Name="BaseApp">
      <FCParamGroup Name="Preferences">
        <FCParamGroup Name="Editor">
          <FCUInt Name="Text" Value="0"/>
          <FCUInt Name="Bookmark" Value="16776960"/>
          <FCUInt Name="Breakpoint" Value="4278190080"/>
          <FCUInt Name="Keyword" Value="774831872"/>
          <FCUInt Name="Comment" Value="6815744"/>
          <FCUInt Name="Block comment" Value="6815744"/>
          <FCUInt Name="Number" Value="65280"/>
          <FCUInt Name="String" Value="3053453312"/>
          <FCUInt Name="Character" Value="3053453312"/>
          <FCUInt Name="Class name" Value="2052063232"/>
          <FCUInt Name="Define name" Value="2052063232"/>
          <FCUInt Name="Operator" Value="1465342976"/>
          <FCUInt Name="Python output" Value="1482177536"/>
          <FCUInt Name="Python error" Value="3003121664"/>
          <FCUInt Name="Current line highlight" Value="3974949888"/>
        </FCParamGroup>
        <FCParamGroup Name="OutputWindow">
          <FCUInt Name="colorText" Value="255"/>
          <FCUInt Name="colorLogging" Value="5349119"/>
          <FCUInt Name="colorWarning" Value="1969619199"/>
          <FCUInt Name="colorError" Value="2818572543"/>
        </FCParamGroup>
      </FCParamGroup>
    </FCParamGroup>
  </FCParamGroup>

</FCParameters>
```

It I used the https://dequeuniversity.com/color-contrast tool to adjust the Classic text colors away from a background color of #ffffff, and saved the preference pack with only the Preferences/General/General/Save New... "Editor Colors" and "Console Colors" checked.  One would apply it by saving it in a subdirectory of your `Application Support/FreeCAD/SavedPreferencePacks/`  like `/Users/drf/Library/Application Support/FreeCAD/SavedPreferencePacks/mod_darkerTextUI_drf/mod_darkerTextUI_drf.cfg` on my Mac, then Apply a lighter preference pack to set up the interface, and then apply this overlay to just change these `Editor` and `OutputWindow` colors.

Here is a sample, created from the Classic theme with this mod_darkerTextUI_drf overlay:

<img width="1142" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/ab4f56ab-e3cf-43ac-ad2c-3faa00b231d6">

And another sample with Light Theme, with the mod_darkerTextUI_drf overlay applied: 

<img width="1142" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/b80989dc-ae2f-416a-a132-a95b85239a84">

I'll update this post with a mod_lighterTextUI_drf when I work through the numbers for the default Dark preference pack.

**Comment by MisterMakerNL** [comment]
The biggest issue here is the lightgray text and the yellow?
Also need too push such best contrast set too main.
It's way better and I'm getting tired of seeing those websites over and over again.😉

**Comment by luzpaz** [comment]
@MisterMakerNL ping him on discord ?

**Comment by drf5n** [comment]
After I installed the beta preference pack Tools/Addon Manager/  Typed 'beta' in the filter:

<img width="1081" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/ea920ef9-f6a9-439d-8f08-67893b974eeb">

..then applied Light-theme-beta, 

<img width="718" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/ee61b701-92e6-474a-b854-d3ec8b9ec829">

...exited and reloaded, and loaded up and ran a macro script to test the logger output:  

<img width="1154" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/b9b5cde3-dfec-4c35-9711-d2a60863e4a8">

It still looks too washed out for my old eyes, so I overlaid the bits from above to get some darker text in the editor window and darken the warning and error text in the Report View:

<img width="1154" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/fe531692-194d-4e6e-93e4-271ac17ecba4">

With Dark theme beta:

<img width="1147" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/17d22d25-593a-4c2e-baf7-9a7016ecd092">

versus my overly pastel text overlay with:
<img width="1139" alt="image" src="https://github.com/FreeCAD/FreeCAD/assets/2236516/38678e54-6b07-458c-a3b1-630fb54dba27">

**Comment by luzpaz** [comment]
bumping for status

**Comment by MisterMakerNL** [comment]
I think this can be closed no idea what is left to do here.

**Comment by Stokestack** [comment]
Are there changes we can take a look at in a weekly build?

**Comment by lucas-bueno777** [comment]
in the latest weekly build (commit 38127, Windows platform) I noticed some text that is hard to read in the default dark theme. I'm currently doing a test within the BIM tutorial and the text of the progress bar at the bottom is barely readable:
![image](https://github.com/user-attachments/assets/33da4938-021e-441f-87d6-7bc60792819b)

**Comment by maxwxyz** [comment]
Original issue is fixed. If there are still issues left, please open individual issues.
