### ISSUE TITLE
[Problem] Arch: gui_snapper.py: module 'inspect' has no attribute 'getargspec' (v0.20.2)

### ISSUE THREAD

**Issue by zoechi** [FreeCAD/FreeCAD#9875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Debian GNU/Linux 12 (bookworm)
Word size of FreeCAD: 64-bit
Version: 0.20.2.
Build type: Release
Python 3.11.1, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.56
  * BIM 2021.12.0
  * Assembly4 0.50.2
[/code]
```

### Subproject(s) affected?

Arch

### Problem description

When I try to add a window to a wall in Arch or BIM workbench

```
16:39:13  Choose a face on an existing object or select a preset
16:39:14  <class 'AttributeError'>
16:39:14  Traceback (most recent call last):
16:39:14    File "/usr/share/freecad/Mod/Draft/draftguitools/gui_snapper.py", line 1417, in click
16:39:14      accept()
16:39:14    File "/usr/share/freecad/Mod/Draft/draftguitools/gui_snapper.py", line 1429, in accept
16:39:14      if len(inspect.getargspec(callback).args) > 1:
16:39:14             ^^^^^^^^^^^^^^^^^^
16:39:14  AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

### Anything else?

Probably related to #8079

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@zoechi please confirm fix in development version https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by luzpaz** [comment]
please report back

**Comment by yorikvanhavre** [comment]
This has been fixed already by https://github.com/FreeCAD/FreeCAD/commit/fe02d63c8c9b1280978be841d04e68a0a55cceb9
