### ISSUE TITLE
[Problem] Cosmetic center lines add length to TD ExtentDimensions

### ISSUE THREAD

**Issue by FC-FBXL5** [FreeCAD/FreeCAD#9879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: macOS 12.6.7
Word size of FreeCAD: 64-bit
Version: 0.21.0.33485 (Git)
Build type: Release
Branch: master
Hash: 0ef101d8170c4017de42b4e6d80529a9c0494268
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.0.0
  * fcgear 1.0.0
  * Render 2023.2.6
  * Curves.backup1662374221.0929039
  * fasteners 0.4.56
  * sheetmetal 0.2.63
  * Help 1.0.3
  * Curves 0.6.12
  * Assembly3 0.12.0
[/code]

Also 0.21.0.33445 and 0.21.0.33458, at least.
```

### Subproject(s) affected?

Techdraw

### Problem description

I have a TD view with added [TechDraw_HorizontalExtentDimension](https://wiki.freecad.org/TechDraw_HorizontalExtentDimension) and [TechDraw_VerticalExtentDimension](https://wiki.freecad.org/TechDraw_VerticalExtentDimension).
<img width="300" alt="TD-OML" src="https://github.com/FreeCAD/FreeCAD/assets/103560699/a9fb4320-2da2-4f90-ab76-d89a00c6ca23">
When I add cosmetic center lines the ExtentDimension displays the length of a center line instead of the length of the shape. Other cosmetic geometry outside the object adds to the dimensions in the same way.
<img width="300" alt="TD-MML" src="https://github.com/FreeCAD/FreeCAD/assets/103560699/df90123d-4daf-4ef2-a43c-3f55105b6b44">

ExtentDimensions should not reference on cosmetic geometry.

### Anything else?

See [[TD ExtendDimensions do not like cosmetics](https://forum.freecad.org/viewtopic.php?t=79472)](https://forum.freecad.org/viewtopic.php?t=79472) on the forum.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
should be fixed by http://github.com/FreeCAD/FreeCAD/commit/584bd77c29
