### ISSUE TITLE
[Problem] edit->Preferences->general deselect the Enable splash screen at start up radio box, FreeCAD cannot be opened

### ISSUE THREAD

**Issue by Lian-Zekun** [FreeCAD/FreeCAD#9897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Chinese/China (zh_CN)
```

### Subproject(s) affected?

None

### Problem description

![微信图片_20230709124238](https://github.com/FreeCAD/FreeCAD/assets/42426070/75c28dd3-0a3f-417c-a9e4-3a4be6c81819)
Deselecting causes FreeCAD to fail to open again

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Please confirm on development version (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds)

**Comment by Lian-Zekun** [comment]
The FreeCAD-0.20.2-WIN-x64-installer-3.exe file I downloaded from this website https://www.freecad.org/downloads.php Can reproduce the problem I described.
I downloaded the installation package for this website and found that the issue has been resolved https://github.com/FreeCAD/FreeCAD/releases/tag/0.20.2.

**Comment by Lian-Zekun** [comment]
> Please confirm on development version (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds)

The FreeCAD-0.20.2-WIN-x64-installer-3.exe file I downloaded from this website https://www.freecad.org/downloads.php Can reproduce the problem I described.
I downloaded the installation package for this website and found that the issue has been resolved https://github.com/FreeCAD/FreeCAD/releases/tag/0.20.2.

**Comment by yorikvanhavre** [comment]
Cannot reproduce on Linux. Can another Windows user confirm?

**Comment by Lian-Zekun** [comment]
> Cannot reproduce on Linux. Can another Windows user confirm?

I used a Windows computer that had never installed FreeCAD before and could reproduce it.
But since the latest code of 0.20.2 cannot be replicated, there should be no problem.

**Comment by yorikvanhavre** [comment]
Ok I'll close the report then!
