### ISSUE TITLE
Excessive mirror copies when mirroring an array

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#9900]
Different orders of operations lead to different results.

1. The combination "object - > Array - > Mirror" creates a lot of redundant copies of the Mirror array. And sometimes the copies are created after applying the Mirror tool. For example, when drawing a line that is not connected to an array.

2. The combination "object - > Mirror - > Array" doesn't create extra mirror copies. But I have to make two arrays of objects instead of one. (double work).

I don't know if this behavior of these tools is normal, but it can mislead users. Is there any way to make option 1 give results without extra copies?

video demonstration
https://youtu.be/1QRU2NAV3Eo

File
https://disk.yandex.ru/d/n6uDKr11IoUnUQ

**Comment by Roy-043** [comment]
Forum topic:
https://forum.freecad.org/viewtopic.php?t=79555
