### ISSUE TITLE
wrong tooltip text for "Import invisible objects" in STEP import settings

### ISSUE THREAD

**Issue by bdieterm** [FreeCAD/FreeCAD#9941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)
and also master

### Problem description

There is a contradiction between the label and the tooltip text

see
https://github.com/FreeCAD/FreeCAD/blob/15371a04f38bbeb5a04edc5a91020ada1e30ef88/src/Mod/Part/Gui/DlgImportStep.ui#L58-L63

![wrong-tooltiptext](https://github.com/FreeCAD/FreeCAD/assets/119257544/fd3132b6-d445-4f5c-a6e5-747cf9b650d9)

The tooltip text is wrong (and not the label text).
Fixing this would also require updated translations.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Thanks!  
Question for anyone: What is our current definition of 'invisible objects' ? That also would be useful to add to the tooltip, imho.

**Comment by benj5378** [comment]
@luzpaz Perhaps invisible objects are just toggled objects in the tree view? https://wiki.freecad.org/Std_ToggleVisibility

**Comment by luzpaz** [comment]
@benj5378 thanks for spearheading it. Closing as fixed by you.

**Comment by benj5378** [comment]
@luzpaz plz check forum
