### ISSUE TITLE
[Problem] TechDraw page returns incorrect width and height in Python

### ISSUE THREAD

**Issue by benj5378** [FreeCAD/FreeCAD#9990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Ubuntu 22.10 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33650 (Git)
Build type: Debug
Branch: iss11
Hash: 0fee9c98f036d18762b6eceb4a6aecbc8f9f948d
Python 3.10.7, Qt 5.15.6, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Techdraw

### Problem description

If one tries to retrieve the page width and height before the TechDraw page has been opened in the gui, then one gets the value `0`.

Example code from @Roy-043 

```
import FreeCAD as App

doc = App.ActiveDocument
box = doc.addObject("Part::Box", "Box")

page = doc.addObject("TechDraw::DrawPage", "Page")
template = doc.addObject("TechDraw::DrawSVGTemplate", "Template")
template.Template = App.getResourceDir() + "Mod/TechDraw/Templates/A4_LandscapeTD.svg"
page.Template = template

view = doc.addObject("TechDraw::DrawViewPart", "View")
page.addView(view)
view.Source = [box]
view.Direction = (0.0, 0.0, 1.0)

doc.recompute()

page.PageWidth  // Returns 0
page.PageHeight  // Returns 0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benj5378** [comment]
https://forum.freecad.org/viewtopic.php?p=695067#p695067

**Comment by luzpaz** [comment]
What's the status on this ?

**Comment by WandererFan** [comment]
It is build on top of a PR that doesn't work.

**Comment by WandererFan** [comment]
Should be fixed by commit 622df46971.

**Comment by benj5378** [comment]
@WandererFan Is #9991 still relevant?

**Comment by benj5378** [comment]
@WandererFan Is https://github.com/FreeCAD/FreeCAD/pull/9991 still relevant?

**Comment by WandererFan** [comment]
The part about using only 1 property for the template would be good but hard to implement while preserving backwards compatibility.   Making PageResult hidden in the tree might solve most of the confusion around having 2 properties with only a 1 line change.
